### ISSUE TITLE
TTS model

### ISSUE THREAD

**Issue by cogmeta** [alphacep/vosk-api#1]
The tts output quality is amazingly well. Any plans to make those model available (commercially or otherwise?) Can we discuss about it?

**Comment by nshmyrev** [comment]
I'm sorry, not clear what do you ask about?

**Comment by cogmeta** [comment]
We would like to use TTS models but offline. Is there possibility of you releasing the pre trained model or even the training code of the TTS models?

**Comment by nshmyrev** [comment]
Sorry, there are no plans to release TTS in near future.

You can try https://nvidia.github.io/NeMo/tts/tutorial.html

**Comment by cogmeta** [comment]
That is what we are using in production right now :) But quality is not good.

**Comment by nshmyrev** [comment]
What do you mean by "not good"?
