### ISSUE TITLE
I got a error when I installed on windows.

### ISSUE THREAD

**Issue by uouo111845** [alphacep/vosk-api#10]
hi 
I deployed the code on  windows and used visual studio compile. My openfst is referencing the url :https://github.com/kkm000/openfst.
But I get the following error when I compile model.cc. Can you help me how to resolve it? 
Many thanks.

model.obj: error LNK2019: Unresolved external symbol "public: unsigned __int64 __cdecl fst :: BitmapIndex :: Rank1 (unsigned __int64) const" (? Rank1 @ BitmapIndex @ fst @@ QEBA_K_K @ Z) in the function "public: class fst :: TropicalWeightTpl <float> __cdecl fst :: internal :: NGramFstImpl <struct fst :: ArcTpl <class fst :: TropicalWeightTpl <float>>> :: Final (int) const "(? Final @? $ NGramFstImpl @ U ? $ ArcTpl @ V? $ TropicalWeightTpl @ M @ fst @@@ fst @@@ internal @ fst @@ QEBA? AV? $ TropicalWeightTpl @ M @ 3 @ H @ Z) is referenced
model.obj: error LNK2019: unresolved external symbol "public: unsigned __int64 __cdecl fst :: BitmapIndex :: Select1 (unsigned __int64) const" (? Select1 @ BitmapIndex @ fst @@ QEBA_K_K @ Z) in function "public: virtual bool __cdecl fst :: NGramFstMatcher <struct fst :: ArcTpl <class fst :: TropicalWeightTpl <float>>> :: Find (int) "(? Find @? $ NGramFstMatcher @ U? $ ArcTpl @ V? $ TropicalWeightTpl @ M @fst @@@ fst @@@ fst @@ UEAA_NH @ Z)
model.obj: error LNK2019: Unresolved external symbol "public: struct std :: pair <unsigned __int64, unsigned __int64> __cdecl fst :: BitmapIndex :: Select0s (unsigned __int64) const" (? Select0s @ BitmapIndex @ fst @@ QEBA? AU? $ Pair @ _K_K @ std @@ _ K @ Z) in the function "public: void __cdecl fst :: internal :: NGramFstImpl <struct fst :: ArcTpl <class fst :: TropicalWeightTpl <float>> :: Init (char const *, bool, class fst :: MappedFile *) "(? Init @? $ NGramFstImpl @ U? $ ArcTpl @ V? $ TropicalWeightTpl @ M @ fst @@ fst @@@ internal @ fst @@ QEAAXPEBD_NPEAVMappedFile @ 3 @@ Z) is referenced
model.obj: error LNK2019: Unresolved external symbol "public: void __cdecl fst :: BitmapIndex :: BuildIndex (unsigned __int64 const *, unsigned __int64)" (? BuildIndex @ BitmapIndex @ fst @@ QEAAXPEB_K_K @ Z) in function "public: void __cdecl fst :: internal :: NGramFstImpl <struct fst :: ArcTpl <class fst :: TropicalWeightTpl <float>>> :: Init (char const *, bool, class fst :: MappedFile *)" (? Init @? $ NGramFstImpl @ U? $ ArcTpl @ V? $ TropicalWeightTpl @ M @ fst @@@ fst @@@ internal @ fst @@ QEAAXPEBD_NPEAVMappedFile @ 3 @@ Z) is referenced
MSVCRTD.lib (exe_main.obj): error LNK2019: Unresolved external symbol main is referenced in function "int __cdecl invoke_main (void)" (? Invoke_main @@ YAHXZ)
C: \ Users \ celine \ kaldi \ kaldiwin_vs2017_OPENBLAS \ zzz_vosk_api \ x64 \ Debug \ zzz_vosk_api.exe: fatal error LNK1120: 5 unresolvable external symbols

**Comment by nshmyrev** [comment]
Hi Celine

Windows version is not ready yet, hopefully next week. I'll let you know. Overall, I recommend to build windows binaries in linux with mingw cross-compiler, not with visual studio.

**Comment by uouo111845** [comment]
I need the windows version very much,and I will try it.
Thank you very much for your help.

**Comment by nshmyrev** [comment]
Will close once windows is deployed.

**Comment by anasvaf** [comment]
Hello. Any updates regarding the Windows installation?

**Comment by nshmyrev** [comment]
It appears to be not very trivial. Someone with VS17 install should probably compile kaldi dlls from our branch. It seems mingw will not work. Details here

https://github.com/numpy/numpy/blob/master/INSTALL.rst.txt#id10
https://mingwpy.github.io/
https://stackoverflow.com/questions/48518055/cross-compile-extension-on-linux-for-windows

**Comment by anasvaf** [comment]
@nshmyrev Thank you so much for your prompt response!

**Comment by dtreskunov** [comment]
@anasvaf @uouo111845 

Please help test the Windows release! I'm hoping you were looking to use the Python library. If so, you're in luck, because I have a [PR open](https://github.com/alphacep/vosk-api/pull/28) to enable building it on Windows.

Here are the files created from my fork:
https://github.com/dtreskunov/vosk-api/releases/tag/untagged-1c853e7b14e3c4dca7fa

**Comment by nshmyrev** [comment]
I've uploaded Windows wheels, should be ok for now. It would be still nice to automate the process.
