### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Iagodel** [alphacep/vosk-api#100]
I had install all the dependences, I done step by step, but when I try to run with "python3 test_simple.py test.wav" just return "Segmentation fault (core dumped)" and nothing more.

Did I do something wrong?
![core](https://user-images.githubusercontent.com/47003942/81831418-b31a8b80-9513-11ea-92f4-4b023beaeef6.png)

**Comment by nshmyrev** [comment]
> I had install all the dependences, I done step by step

What exactly have you done? You need to provide more information. You can also run

     valgrind python3 test_simple.py test.wav

to get more information about the crash.

**Comment by nshmyrev** [comment]
@Iagodel feel free to reopen if you have additional information on the problem.

**Comment by Lirein** [comment]
I had this issue too. With help of debug and testing different methods, i resolve that an issue appears primary at virtualized systems with Intel MKL mathematical engine. To resolve this issue, you can rebuild Kaldi and then vosk-api with this compilation flags:
./configure --static --shared --mathlib=OPENBLAS --static-math=yes
Otherway, you may start decoding with help of NvidiaCard, but not tested yet on my systems.

**Comment by AghilasSini** [comment]
Hello,

I am trying to run the vosk-api python wrap, but I got **Segmentation fault (core dumped)**


![error_example_running](https://user-images.githubusercontent.com/16865777/100120922-ccb06e80-2e78-11eb-9d2f-4d09e43d709a.png)





So let me give you some information about the machine configuration that I am using for runining this commande:

- Python 3.6.9
- Ubuntu 18.04


Here the message that I have when running the command: 
`python3 setup.py install --user --single-version-externally-managed --root=/`

![vosk_python_v1](https://user-images.githubusercontent.com/16865777/100120350-26fcff80-2e78-11eb-9543-43ca6cdc618c.png)

![vosk_python_install](https://user-images.githubusercontent.com/16865777/100120236-0634aa00-2e78-11eb-9908-9793a19fe767.png)


Thank you

**Comment by AghilasSini** [comment]
Hello,

I solved the issue by installing python3.8.

Sorry for the inconvenience

Thanks

**Comment by eatyofood** [comment]
> Hello,
> 
> I solved the issue by installing python3.8.
> 
> Sorry for the inconvenience
> 
> Thanks

no 
thank you!  i had the same issue.

**Comment by russele7** [comment]
@nshmyrev 
Dear Nickolay,
Thank you very much for wonderfull open source ASR solution.
I am trying your examples  test_ffmpeg.py / test_simple.py with   big Russian model < vosk-model-ru-0.10.zip >  and I got error < Segmentation fault (core dumped)>
Report with valgrind is in attachment. 
I am using:
•	Ubuntu 20.04.1 LTS
•	Python 3.8.10
•	vosk==0.3.31
•	CPU - Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
P.S. small Russian model < vosk-model-small-ru-0.15> working succesfully without error.
Could you please help and advice with resolving this issue.
[valgrind.txt](https://github.com/alphacep/vosk-api/files/7301759/valgrind.txt)
Thank you in advance!

**Comment by nshmyrev** [comment]
> I am trying your examples test_ffmpeg.py / test_simple.py with big Russian model < vosk-model-ru-0.10.zip > and I got error < Segmentation fault (core dumped)>

You need to create new issue and provide information about hardware
