### ISSUE TITLE
vosk-api on riscv64

### ISSUE THREAD

**Issue by abhishekwalia33** [alphacep/vosk-api#1000]
Hi,

I am want to compile vosk-api for riscv64 for that i tried to compile using makefile so bellow error I am getting.

:~/abhi/vosk-api/src# make
g++ -g -O3 -std=c++17 -Wno-deprecated-declarations -fPIC -DFST_NO_DYNAMIC_LINKING -I. -I/home/root/travis/kaldi/src -I/home/root/travis/kaldi/tools/openfst/include  -I/home/root/travis/kaldi/tools/OpenBLAS/install/include -c -o recognizer.o recognizer.cc
In file included from recognizer.cc:15:
recognizer.h:18:10: fatal error: base/kaldi-common.h: No such file or directory
   18 | #include "base/kaldi-common.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:112: recognizer.o] Error 1

why i am getting this error of kaldi related or if Makefile is not taking this kaldi is their any other way to compile vosk-api for riscv64. please help me out I am new in package porting.

**Comment by abhishekwalia33** [comment]
i tried using python3 also below is my log 

~/abhi/vosk-api/python# python3 setup.py build
running build
running build_py
file vosk/vosk_cffi.py (for module vosk.vosk_cffi) not found
creating build
creating build/lib
creating build/lib/vosk
copying vosk/__init__.py -> build/lib/vosk
creating build/lib/vosk/transcriber
copying vosk/transcriber/cli.py -> build/lib/vosk/transcriber
copying vosk/transcriber/transcriber.py -> build/lib/vosk/transcriber
copying vosk/transcriber/__init__.py -> build/lib/vosk/transcriber
running egg_info
creating vosk.egg-info
writing vosk.egg-info/PKG-INFO
writing dependency_links to vosk.egg-info/dependency_links.txt
writing entry points to vosk.egg-info/entry_points.txt
writing requirements to vosk.egg-info/requires.txt
writing top-level names to vosk.egg-info/top_level.txt
writing manifest file 'vosk.egg-info/SOURCES.txt'
reading manifest file 'vosk.egg-info/SOURCES.txt'
writing manifest file 'vosk.egg-info/SOURCES.txt'
file vosk/vosk_cffi.py (for module vosk.vosk_cffi) not found
generating cffi module 'build/lib/vosk/vosk_cffi.py'


when I am trying to import it so it is giving for libvosk.so not found 

error:
/usr/lib/python3.8/site-packages/vosk-0.3.42-py3.8.egg/vosk/libvosk.so: cannot open shared object file: No such file or directory

why libvosk.so not generating I am not getting can anybody help me out.

**Comment by nshmyrev** [comment]
> 18 | #include "base/kaldi-common.h"

You need to specify KALDI_ROOT in makefile argumens.

Overall, the same issue as #989
