### ISSUE TITLE
Unable to use `vosk-transcriber` command line utility.

### ISSUE THREAD

**Issue by Aradhye2002** [alphacep/vosk-api#1002]
Through the documentation, I got to know of a vosk-transcriber cmdline tool that can be used as follows:

`vosk-transcriber [-h] [-model MODEL] [-list_models] [-list_languages] [-model_name MODEL_NAME] [-lang LANG] [-input INPUT]         [-output OUTPUT] [-otype OUTPUTTYPE] [--log LOG]
`
This was working with the -list_languages arg but when I tried to convert a .mp4 video file into text, it was just stuck at the following screen:

![Screenshot from 2022-06-07 21-42-33](https://user-images.githubusercontent.com/20011003/172430270-499c086d-e521-4320-96ca-fcb23b7e98b4.png)

Kindly provide some guidance. 

Thanks

**Comment by nshmyrev** [comment]
It probably works, just wait a bit. @vadimdddd it would be nice to add some progress indicator.

**Comment by Aradhye2002** [comment]
> It probably works, just wait a bit. @vadimdddd it would be nice to add some progress indicator.

Is it because the library is downloading models which it can't find? Also a couple of more doubts:
1. Why have language and model both been given as an option to pass to vosk-transcriber command? Like by specifying language you are restricting the model space to only large and small plus the dialects, right?
Really appreciate being so dedicated and replying quickly. Love from India.

EDIT: No, it's not working even after waiting for 30 minutes. 
EDIT2: Finally worked.

**Comment by nshmyrev** [comment]
Big models also require up to 16Gb of free memory, if you do not have enough memory things will be slow.

> Why have language and model both been given as an option to pass to vosk-transcriber command? Like by specifying language you are restricting the model space to only large and small plus the dialects, right?

Yes!

**Comment by nshmyrev** [comment]
We added progress logging now.
