### ISSUE TITLE
Poor performance with background noise

### ISSUE THREAD

**Issue by Aradhye2002** [alphacep/vosk-api#1004]
While the library seems to work well with low noise conditions, even when the background noise is slightly high (for ex. for outdoor applications, which happens to be of interest for me) the model does not seem to detect anything. For example running the en-in-small model on the following audio sample 
[Aradhye-en-unclear.zip](https://github.com/alphacep/vosk-api/files/8858441/Aradhye-en-unclear.zip)

I get:

![Screenshot from 2022-06-08 10-33-36](https://user-images.githubusercontent.com/20011003/172535700-ca3a6a66-cb0a-4c25-ad6e-f5b98195cec1.png)

So is there a scope for recognising such audio samples (possibly by fine tuning), or do I need to search for some other library or train my own model?

Thanks

**Comment by nshmyrev** [comment]
> So is there a scope for recognising such audio samples (possibly by fine tuning)

not right now

> or do I need to search for some other library or train my own model?

its up to you
