### ISSUE TITLE
android-api cant load speakmodel

### ISSUE THREAD

**Issue by UnstoppableCurry** [alphacep/vosk-api#1005]
![image](https://user-images.githubusercontent.com/65523997/172578817-0d265adb-0701-4d73-8261-0f13d38e0413.png)
![image](https://user-images.githubusercontent.com/65523997/172579692-c1ee40b5-14f8-4dc6-a0f9-6889c959406d.png)

![image](https://user-images.githubusercontent.com/65523997/172579035-05b0dbf8-e396-4e94-9a18-16e09813132c.png)
igit

i get the model path ,but i don't know why can't load it

**Comment by UnstoppableCurry** [comment]
ide recommed con't find the uuid  so i remove the uuid's code,but it also can't load the model,can you tell me how to fix it,thanks for you !

**Comment by nshmyrev** [comment]
There was no need to remove UUID, you'd better create UUID with gradle, see demo project for example.

**Comment by nshmyrev** [comment]
Same as #846
