### ISSUE TITLE
Inference seems to be CPU-bound

### ISSUE THREAD

**Issue by andrestone** [alphacep/vosk-api#1007]
Hello!

First of all, thanks for the amazing OSS.

I'm trying to determine what's the best setup for parallel execution of transcription jobs at the lowest possible latency (the time it takes to fully transcribe about 1 minute of audio data).

So far, it seems to me that the performance is CPU-bound, in such a way that even using the `BatchModel` / `BatchRecognizer`, it still requires a disproportional amount of CPU.

My next step is to test how the `BatchModel` / `BatchRecognizer` (or even just the GPU enabled images) might help when testing parallel executions, but I'd appreciate any guidance on setup might work best for my use case.

Thanks!

**Comment by nshmyrev** [comment]
> First of all, thanks for the amazing OSS.

Thank you for trying Vosk

> I'm trying to determine what's the best setup for parallel execution of transcription jobs at the lowest possible latency (the time it takes to fully transcribe about 1 minute of audio data).

Time taken to transcribe 1 minute of audio is not latency. Latency means how fast you get the results after audio stream is over, usually it is less than 1 second. You probably look for throughput.

> the performance is CPU-bound

Yes

> My next step is to test how the BatchModel

GPU can process more audio, you are welcome to try.

**Comment by andrestone** [comment]
Thanks for the quick response!

That's exactly what I meant to say. 

If I may ask you another question, it's my understanding that the `BatchedModel` doesn't load / perform rescoring. Is that correct? If so, is there any particular reason why?

**Comment by nshmyrev** [comment]
> BatchedModel doesn't load / perform rescoring. Is that correct? 

Yes

> If so, is there any particular reason why?

No implemented yet
