### ISSUE TITLE
I got error: Folder 'model' does not contain model files.

### ISSUE THREAD

**Issue by zydjohnHotmail** [alphacep/vosk-api#1008]
Hello:
I want to test the repo on Windows 10 .NET 5.0 or even .NET 6.0. (X64 CPU)
I created a console app with Visual Studio 2022.
I installed NUGET package latest version: 0.3.38
PM> Install-Package Vosk -Version 0.3.38

The following is my C# code:

        public static void DemoBytes(Model model)
        {
            // Demo byte buffer
            VoskRecognizer rec = new(model, 16000.0f);
            rec.SetMaxAlternatives(0);
            rec.SetWords(true);
            using (Stream source = File.OpenRead(@"C:\Audio\1.wav"))
            {
                byte[] buffer = new byte[4096];
                int bytesRead;
                while ((bytesRead = source.Read(buffer, 0, buffer.Length)) > 0)
                {
                    if (rec.AcceptWaveform(buffer, bytesRead))
                    {
                        Console.WriteLine(rec.Result());
                    }
                    else
                    {
                        Console.WriteLine(rec.PartialResult());
                    }
                }
            }
            Console.WriteLine(rec.FinalResult());
        }

But when I run my code, I got the error:
ERROR (VoskAPI:Model():model.cc:122) Folder 'model' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

I looked at the whole project folder, I can’t even find any folder named “model”.
Let me know if I miss anything.
By only install nuget package: 0.3.38 seems not enough to fix missing model folder issue.
Please advise,
By the way, I have quite a number of WAV files with SampleRate of 44100.
Like the following:

D:\Audios\>mp4box -info Speech_10s.wav
# Movie Info - 1 track - TimeScale 1000
Duration 00:00:10.031
Fragmented: no
Progressive (moov before mdat)
Major Brand isom - version 1 - compatible brands: isom
Created: GMT Thu Jun  9 08:52:08 2022

File has root IOD (9 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: No visual capability required (0xff)
Audio PL: AAC Profile @ Level 2 (0x29)
No streams included in root OD

# Track 1 Info - ID 2 - TimeScale 44100
Media Duration 00:00:10.054
Track has 1 edits: track duration is 00:00:10.031
Track flags: Enabled In Movie
Media Info: Language "English (eng)" - Type "soun:mp4a" - 433 samples
Alternate Group ID 1
MPEG-4 Audio AAC LC (AOT=2 implicit) - 1 Channel(s) - SampleRate 44100
        RFC6381 Codec Parameters: mp4a.40.2
        All samples are sync
        Max sample duration: 1024 / 44100

Let me know if I have to change the statement of this:
VoskRecognizer rec = new(model, 16000.0f);
To something like this:
VoskRecognizer rec = new(model, 44100.0f);
Thanks,

**Comment by nshmyrev** [comment]
you need to download model

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I downloaded the biggest model for Ukrainian language, and I got one small wav file for testing.  The following is the information about the wav file:
D:\Audios\> mp4box -info Speech_10s.wav
# Movie Info - 2 tracks - TimeScale 1000
Duration 00:00:10.023
Fragmented: no
Progressive (moov before mdat)
Major Brand isom - version 1 - compatible brands: isom
Created: GMT Thu Jun  9 11:19:27 2022

File has root IOD (9 bytes)
Scene PL 0xff - Graphics PL 0xff - OD PL 0xff
Visual PL: AVC/H264 Profile (0x7f)
Audio PL: AAC Profile @ Level 2 (0x29)
No streams included in root OD

# Track 1 Info - ID 1 - TimeScale 44100
Media Duration 00:00:10.240
Track has 1 edits: track duration is 00:00:10.000
Track flags: Enabled In Movie
Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 251 samples
Visual Sample Entry Info: width=1280 height=720 (depth=24 bits)
Visual Track layout: x=0 y=0 width=1280 height=720
AVC/H264 Video - Visual Size 1280 x 720
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 3.1
        NAL Unit length bits: 32
        Pixel Aspect Ratio 1:1 - Indicated track size 1280 x 720
        Chroma format YUV 4:2:0 - Luma bit depth 8 - chroma bit depth 8
        SPS#1 hash: 47A712A912E548A6D9065E7B7C5E3D467F361B69
        PPS#1 hash: 6648DAA985D842149E548D6CDE2C2151B02BF03F
        RFC6381 Codec Parameters: avc1.64001F
        Average GOP length: 251 samples
        Max sample duration: 1764 / 44100

# Track 2 Info - ID 2 - TimeScale 44100
Media Duration 00:00:10.023
Track has 1 edits: track duration is 00:00:10.023
Track flags: Enabled In Movie
Media Info: Language "English (eng)" - Type "soun:mp4a" - 432 samples
Alternate Group ID 1
MPEG-4 Audio AAC LC (AOT=2 implicit) - 1 Channel(s) - SampleRate 44100
        RFC6381 Codec Parameters: mp4a.40.2
        All samples are sync
        Max sample duration: 1024 / 44100

I want to do some testing to see if I can get text from the speech in the WAV file.
        static void Main(string[] args)
        {
            Vosk.Vosk.SetLogLevel(0);
            Model model = new(Model_Path);
            DemoBytes(model);
            DemoFloats(model);
            DemoSpeaker(model);
        }

But what I got are just empty messages, like this:
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from C:\Speech2Text\VoskTest\VoskTest\bin\Debug\net5.0\Model\vosk-model-uk-v3/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from C:\Speech2Text\VoskTest\VoskTest\bin\Debug\net5.0\Model\vosk-model-uk-v3/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading words from C:\Speech2Text\VoskTest\VoskTest\bin\Debug\net5.0\Model\vosk-model-uk-v3/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo C:\Speech2Text\VoskTest\VoskTest\bin\Debug\net5.0\Model\vosk-model-uk-v3/graph/phones/word_boundary.int
{
  "partial" : ""
}
{
  "partial" : ""
}
......
{
  "text" : ""
}

Let me know if I made any mistake.  The C# code is the same as in C# demo program.  I just set the model path, and provide WAV file location.
I don't know how to upload a WAV file, as it is not support by Github, so I tried to upload a MP4 file with the mono audio built-in.

Thanks,

**Comment by nshmyrev** [comment]
The audio file format is not wav 16khz 16 bit mono. You need to convert to wav with ffmpeg.
