### ISSUE TITLE
Can not install vosk on 64-bit rPi 4

### ISSUE THREAD

**Issue by Nixoals** [alphacep/vosk-api#1009]
Dear all,

I'm despererately trying to install vosk on 64-bit raspberry Pi 4 but with "pip3 install vosk" command I get this error message:

ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk

pip version: 22.1.2
python verison 3.9.2
hardware: raspberry pi 4 8GB
System: debian bullseye 64-bit
everything is up to date

I had no problem with 32-bit bullseye. 

I'm not good enough to compile from source. Is there any availbale wheel for this? Or a detailed step by step guide to compile?

Thanks!

**Comment by nshmyrev** [comment]
Pip doesn't support 64-bit arm, you have to download wheel from releases.

**Comment by nshmyrev** [comment]
Same as #479

**Comment by Nixoals** [comment]
> Pip doesn't support 64-bit arm, you have to download wheel from releases.

Thanks a lot!
