### ISSUE TITLE
Using a wide band model 

### ISSUE THREAD

**Issue by erksch** [alphacep/vosk-api#101]
Hey!

I just wanted to ask if it is possible to use a big wide band model with, say the C# client.
The small models (e.g. vosk-model-small-de-zamia-0.3) seem to work out of the box but the big one (e.g. tuda-de) does not. Is the big model compatible with use in the wrapped APIs?

Also both models have very different folder structures:

*vosk-model-small-de-zamia-0.3*
<img src="https://user-images.githubusercontent.com/19290349/81837963-ccd4c680-9545-11ea-9942-778c39176dd2.png" width="200" />
*tuda-de*
<img src="https://user-images.githubusercontent.com/19290349/81838057-ebd35880-9545-11ea-9fb3-72eccbef55f1.png" width="200" />

Is there maybe a way to change of the file structure to make it usable in the wrapped API?

**Comment by erksch** [comment]
So my first try was to copy `/conf/mfcc.conf` to just `/mfcc.conf` and rename `ivector_extractor` to just `ivector`. Results in the following output:
```
LOG (vosk[5.5]:ComputeDerivedVars():ivector\ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (vosk[5.5]:ComputeDerivedVars():ivector\ivector-extractor.cc:204) Done.
LOG (vosk[5.5]:RemoveOrphanNodes():nnet3\nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (vosk[5.5]:RemoveOrphanComponents():nnet3\nnet-nnet.cc:847) Removing 2 orphan components.
LOG (vosk[5.5]:Collapse():nnet3\nnet-utils.cc:1472) Added 1 components, removed 2
LOG (vosk[5.5]:CompileLooped():nnet3\nnet-compile-looped.cc:345) Spent 0.0189979 seconds in looped compilation.
LOG (vosk[5.5]:ReadDataFiles():src/model.cc:190) Loading HCLG from ml_models/kaldi/de_400k_nnet3chain_tdnn1f_2048_sp_bi/HCLG.fst
LOG (vosk[5.5]:ReadDataFiles():src/model.cc:209) Loading words from ml_models/kaldi/de_400k_nnet3chain_tdnn1f_2048_sp_bi/words.txt
LOG (vosk[5.5]:ReadDataFiles():src/model.cc:217) Loading winfo ml_models/kaldi/de_400k_nnet3chain_tdnn1f_2048_sp_bi/word_boundary.int
ERROR (vosk[5.5]:OnlineTransform():feat\online-feature.cc:533) Dimension mismatch: source features have dimension 91 and LDA #cols is 280
```

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-server/issues/25. You should use mfcc_hires.conf instead of mfcc.conf

**Comment by erksch** [comment]
Sorry for the duplication! It works and thank you for your reply!
