### ISSUE TITLE
Speaker distance together with the vectors and text

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#1010]
Dear Respected Sir, 

I have been using this tool since almost two years. This is really interesting scientific research. 

Since you changed a lot in different versions and the formats are also bit change. I have to ask a question. 

```
while True:
    data = wf.readframes(4000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
#        res = json.loads(rec.Result())
#        print ("Text:", res['text'])
        print(rec.FinalResult())
        res = json.loads(rec.Result())
        if 'spk' in res:
            print ("Speaker distance:", cosine_dist(spk_sig, res['spk']), "based on", res['spk_frames'], "frames")
```

I have imported both models language `"en-us"` and `"spk_model"`

Now with this routine I get 

```
{
  "text" : ""
}
{
  "result" : [{
      "conf" : 1.000000,
      "end" : 7.090000,
      "start" : 6.850000,
      "word" : "when"
    }}],
  "spk" : [1.585943, -0.251023, 1.071922, 1.439962, -1.259629],
  "spk_frames" : 1314,
  "text" : "when"
}
```

while together with speaker x vectors, I also need speaker distance. Is there any way to get the distance as well? or only distance instead of vectors? Your kind guide is highly appreciated.

**Comment by nshmyrev** [comment]
you have to calculate the distance yourself

**Comment by nshmyrev** [comment]
Same as #405

**Comment by Tortoise17** [comment]
@nshmyrev Thank you so much. Can we get the timestamps for speakers with recognition this way?

**Comment by Tortoise17** [comment]
@nshmyrev I get the results with speaker distance with this piece of code. But the text is without timestamps and in a fragment. Is it possible to get also the timestamps for each word ? what mistake I am making if you can guide. 

```
while True:
    data = wf.readframes(4000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        res = json.loads(rec.Result())
        print ("Text:", res['text'])
        if 'spk' in res:
            spk = ("Speaker distance:", cosine_dist(spk_sig, res['spk']))
```
