### ISSUE TITLE
How to save recognized text in a file?

### ISSUE THREAD

**Issue by zydjohnHotmail** [alphacep/vosk-api#1011]
Hello:
I can use the repo to recognize speech for non-English language, but from screen, all those non-English text looks garbage.
How I can save all recognized words in a text file, so I can edit it later on by other editor program?
I am using C# on Windows 10.
Please advise,
Thanks,

**Comment by nshmyrev** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-write-to-a-text-file
