### ISSUE TITLE
How to decrease activation threshold in the neural network?

### ISSUE THREAD

**Issue by Aradhye2002** [alphacep/vosk-api#1016]
I noticed that in a noisy environment the small model was giving the wrong output: it was giving gibberish. But the large model was not giving any output at all. So I think that decreasing the activation threshold would be a promising way forward; hence my question. 

I tried changing the min-activations in the model.conf file but it had no effect on the output.

**Comment by nshmyrev** [comment]
1. Which small model exactly. We have many of them.
2. Provide audio sample and expected outputs.
3.

**Comment by Aradhye2002** [comment]
@nshmyrev 

1. small model : Indian English model for mobile Vosk applications (Do not know exact version as I have renamed the original folder

2. large model: Indian English model from Alpha Cephei, Suitable for telecom applications
audio sample: [Aradhye-en-unclear.zip](https://github.com/alphacep/vosk-api/files/8891704/Aradhye-en-unclear.zip)
3. expected output:  
                                 .....
                                 .....
                   {"text" : "man is standing two metres away from the block"}

5. Actual output
                   {"text" : ""}

[terminal_output.txt](https://github.com/alphacep/vosk-api/files/8891856/terminal_output.txt)

**Comment by nshmyrev** [comment]
Ok, you already asked the same question in #1004 and got the answer. Please do not spam our tracker.
