### ISSUE TITLE
Where can I find the necessary files to compile "vosk-model-en-us-0.22-lgraph"?

### ISSUE THREAD

**Issue by mathigatti** [alphacep/vosk-api#1018]
Hi! Thanks for such an awesome project. I'm trying to extend the vocabulary and LM probabilities of "vosk-model-en-us-0.22-lgraph-compile" by adding some texts to "extra.txt" and compiling the model.

I found [this link](https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-lgraph-compile.zip) containing a 0.22 model, I'm not sure if it's the lgraph one or the other one (the bigger and slower one). If it's the latter do you know where can I found the files for the lgraph one?

Thanks!

**Comment by nshmyrev** [comment]
The same compilation package compiles lgraph, see last lines with mkgraph_lookahead.sh

**Comment by mathigatti** [comment]
Awesome. I was able to make it work thank you very much! By the way why is the small model outdated in comparison to the other ones (0.15 instead of 0.22)?

**Comment by nshmyrev** [comment]
Because we didn't update it for some time.

**Comment by mathigatti** [comment]
Makes sense, thanks for the nice support! I love the project

**Comment by apostolistzimas** [comment]
Can one add words to vosk-model-en-us-0.22 model that is about 1.8gb and appears to be more accurate than the rest?
