### ISSUE TITLE
Fix code to make it python 3.5 compatible

### ISSUE THREAD

**Issue by boyapavel** [alphacep/vosk-api#1021]
Установил vosk через pip3
Далее при попытке импортировать Model из vosk ругается:
Traceback (most recent call last):
  File "test_simple.py", line 3, in <module>
    from vosk import Model
  File "/usr/local/lib/python3.5/dist-packages/vosk/__init__.py", line 89
    model_file = [model for model in model_file_list if match(f"vosk-model(-small)?-{lang}", model)]
                                                                                          ^
SyntaxError: invalid syntax

**Comment by vadimdddd** [comment]
@boyapavel Здравствуйте, попробуйте питоном 3.7+ версией воспользоваться

**Comment by nshmyrev** [comment]
@vadimdddd you need to fix this part to use older string format style.

**Comment by boyapavel** [comment]
> @boyapavel Здравствуйте, попробуйте питоном 3.7+ версией воспользоваться

поставил питон версии 3.8 заработало. спасибо.

**Comment by nshmyrev** [comment]
Should be fixed now
