### ISSUE TITLE
vosk with speecrecognition - AttributeError: 'Recognizer' object has no attribute 'recognize_vosk'

### ISSUE THREAD

**Issue by ramleda** [alphacep/vosk-api#1026]
Dear Sir, 

I'm using vosk with speechrecognition in python. First, I want to be glad about your project. 

I have some problems using the vosk with speech recognition, when I call the method "recognizer_Instance.recognize_vosk(audio)", I had receiving the following message:

AttributeError: 'Recognizer' object has no attribute 'recognize_vosk'. Did you mean: 'recognize_api'?

My code:

            import speech_recognition as speechreco
            import pyttsx3 as tts
            import vosk
            
            recognizer = speechreco.Recognizer()

            recognizer.adjust_for_ambient_noise(mic)
            print("begin listening")
            audio = recognizer.listen(mic)

            text = recognizer.recognize_vosk(audio)

I'm using python version: 3.10.4.
Need I to use a downgrade version?

**Comment by nshmyrev** [comment]
Use vosk directly instead of speech_recognition wrapper.

**Comment by ramleda** [comment]
I did it. Thank you.

**Comment by mattiasu96** [comment]
How did you solve this? I have a similar problem
