### ISSUE TITLE
Error using model vosk-model-pt-fb-v0.1.1-20220516_2113.zip

### ISSUE THREAD

**Issue by ramleda** [alphacep/vosk-api#1028]
I was trying to use Portuguese model:

https://alphacephei.com/vosk/models/vosk-model-pt-fb-v0.1.1-20220516_2113.zip

when I try to create the class Model, I have the following error:

model = Model(
  File "C:\Python310\lib\site-packages\vosk\__init__.py", line 53, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

Any help?

**Comment by nshmyrev** [comment]
Please format your post properly and provide the full output from the script

**Comment by ramleda** [comment]
I was trying to use the Portuguese model:

https://alphacephei.com/vosk/models/vosk-model-pt-fb-v0.1.1-20220516_2113.zip

I'm importing the vosk:

> **> `from vosk import Model, KaldiRecognizer`**


Instantiate the model class, recognizer  and set the model PATH:

     model = Model(
     r'C:\Users\user\Projects\studies\models\vosk-model-pt-fb-v0.1.1-20220516_2113')
     recognizer = KaldiRecognizer(model, 16000)
     recognizer.SetWords(True)`

The rest of the code is irrelevant. But when I run the py script the following happens:


**>  `LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=7000 lattice-beam=6
>      LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
>      LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
>      LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
>      LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from C:\Users\user\Projects\studies\models\vosk-model-pt-fb-v0.1.1-20220516_2113/ivector/final.ie
>      LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
>      LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
>      LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from C:\Users\user\Projects\studies\models\vosk-model-pt-fb-v0.1.1-20220516_2113/graph/HCLG.fst
>      LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading words from C:\Users\user\Projects\studies\models\vosk-model-pt-fb-v0.1.1-20220516_2113/graph/words.txt
>      LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo C:\Users\user\Projects\studies\models\vosk-model-pt-fb-v0.1.1-20220516_2113/graph/phones/word_boundary.int
>      LOG (VoskAPI:ReadDataFiles():model.cc:310) Loading subtract G.fst model from C:\Users\user\Projects\studies\models\vosk-model-pt-fb-v0.1.1-20220516_2113/rescore/G.fst
>      LOG (VoskAPI:ReadDataFiles():model.cc:312) Loading CARPA model from C:\Users\user\Projects\studies\studies\models\vosk-model-pt-fb-v0.1.1-20220516_2113/rescore/G.carpa
>      ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.
>      Traceback (most recent call last):
>      File "C:\Users\user\Projects\studies\speechrecovosk.py", line 5, in <module>
>     model = Model(
>      File "C:\Python310\lib\site-packages\vosk\__init__.py", line 53, in __init__
>      raise Exception("Failed to create a model")
>      Exception: Failed to create a model`**

Any help?

**Comment by nshmyrev** [comment]
I've just tried and it works fine. Are you using 32-bit python by chance? Or the file is corrupted. Check file sizes:

```
-rw-r--r-- 1 shmyrev shmyrev   40059022 May 17 02:13 ./rescore/G.fst
-rw-r--r-- 1 shmyrev shmyrev 2278821072 May 17 02:13 ./rescore/G.carpa
```

**Comment by ramleda** [comment]
The same does not run on windows. Did you try windows?

**Comment by nshmyrev** [comment]
I do not have any Windows machine around. Are you sure you are not on 32-bit? It should work fine on 64-bit python.

**Comment by ramleda** [comment]
64-bit, sure!

**Comment by ramleda** [comment]
Solved it! Thanks!

**Comment by nshmyrev** [comment]
And, what is the solution? Could you share so it helps others?

**Comment by ramleda** [comment]
Oh, sorry. Nothing special. I download again the model. Although the model has the same size, the first one looks corrupted. 

Sorry for do not mention it. I tried both in Linux and windows and the first one I downloaded failed in both OS. 

Thanks for your help. My next step is to increase the lexicon! Thanks too much!

**Comment by nshmyrev** [comment]
ok, thank you

**Comment by nshmyrev** [comment]
Same as #991

**Comment by ywanes** [comment]
here it worked after leaving the folder structure like this:

./align_lexicon.int
./align_lexicon.txt
./disambig.int
./disambig.txt
./disambig_tid.int
./final.mdl
./G.carpa
./G.fst
./Gr.fst
./HCLG.fst
./HCLr.fst
./ivector
./ivector/final.dubm
./ivector/final.ie
./ivector/final.mat
./ivector/global_cmvn.stats
./ivector/online_cmvn.conf
./ivector/splice.conf
./ivector/splice_opts
./mfcc.conf
./model.conf
./optional_silence.csl
./optional_silence.int
./optional_silence.txt
./phones.txt
./silence.csl
./tree
./words.txt
./word_boundary.int
./word_boundary.txt

*note that there is only one folder called ivector
*I changed the structure based on the small model

**Comment by Abzal171** [comment]
Guys, no vosk model worked for me and that's how I solved it:
1.Run Pycharm as an administrator
2.Insert your language model into any folder from the "public":       model = Model(r'C:\Users\Public\Downloads\vosk-model-small-ru-0.22 ')
3. We launch and rejoice

Ребята,у меня не работала никакая модель на vosk и вот как я его решил:
1.Запускаем Pycharm от имени администратора
2.Вставляем вашу языковую модель в любую папку из "общие":       model = Model(r'C:\Users\Public\Downloads\vosk-model-small-ru-0.22')
3.Запускаем и радуемся

**Comment by Glauber-Sc** [comment]
Olá Também estou com problema ao tentar usar o modelo do https://alphacephei.com/vosk/models (vosk-model-pt-fb-v0.1.1-20220516_2113)

Porém ao rodar o meu projeto com o node.js ele da esse erro ---> ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.



PS C:\Users\glaub\Desktop\AudioEmTexto_server> yarn start
yarn run v1.22.22
$ nodemon index.js
[nodemon] 3.1.4
[nodemon] to restart at any time, enter `rs`  
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node index.js`
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from model/vosk-model-pt-fb-v0.1.1-20220516_2113/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from model/vosk-model-pt-fb-v0.1.1-20220516_2113/graph/HCLG.fst    
LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading words from model/vosk-model-pt-fb-v0.1.1-20220516_2113/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo model/vosk-model-pt-fb-v0.1.1-20220516_2113/graph/phones/word_boundary.int    
LOG (VoskAPI:ReadDataFiles():model.cc:310) Loading subtract G.fst model from model/vosk-model-pt-fb-v0.1.1-20220516_2113/rescore/G.fst 
LOG (VoskAPI:ReadDataFiles():model.cc:312) Loading CARPA model from model/vosk-model-pt-fb-v0.1.1-20220516_2113/rescore/G.carpa        
ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.
Servidor rodando na porta 3000


Alguém poderia da uma força ?
