### ISSUE TITLE
Android Studio version for build vosk-android-demo

### ISSUE THREAD

**Issue by pacomaq** [alphacep/vosk-api#1029]
What Android Studio version are required for build 'vosk-android-demo' v. 0.3.38 ? In Android Studio Chipmunk | 2021.2.1 Patch 1 i can't build it.

**Comment by nshmyrev** [comment]
It should work. What is the particular error you see?

**Comment by pacomaq** [comment]
FAILURE: Build completed with 2 failures.

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.sun.jna.AltCallingConvention found in modules jetified-jna-5.11.0 (net.java.dev.jna:jna:5.11.0) and jetified-jna-5.11.0-runtime (net.java.dev.jna:jna:5.11.0)
     Duplicate class com.sun.jna.Callback found in modules jetified-jna-5.11.0 (net.java.dev.jna:jna:5.11.0) and jetified-jna-5.11.0-runtime (net.java.dev.jna:jna:5.11.0)
     Duplicate class com.sun.jna.Callback$UncaughtExceptionHandler found in modules jetified-jna-5.11.0 (net.java.dev.jna:jna:5.11.0) and jetified-jna-5.11.0-runtime (net.java.dev.jna:jna:5.11.0)
     Duplicate class com.sun.jna.CallbackParameterContext found in modules jetified-jna-5.11.0 (net.java.dev.jna:jna:5.11.0) and jetified-jna-5.11.0-runtime (net.java.dev.jna:jna:5.11.0)
    …………….
 Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
======================================================================
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/AL2.0' from inputs:
      - C:\Users\Apocalypsis\.gradle\caches\transforms-3\ac7827ee159d36005e73e5a7d062cd2f\transformed\jetified-jna-5.11.0\jars\classes.jar
      - C:\Users\Apocalypsis\.gradle\caches\transforms-3\090353a1b7950485e5f4baa04986492b\transformed\jetified-jna-5.11.0.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information
………
BUILD FAILED in 31s
```

**Comment by nshmyrev** [comment]
You can remove jna in app gradle like described in https://github.com/alphacep/vosk-api/issues/757#issuecomment-964739708:

`    //implementation 'net.java.dev.jna:jna:5.8.0@aar'
`

and it should work

**Comment by pacomaq** [comment]
Ещё вопрос - с микрофона распознавание работает с моделью русского языка, а .wav файлы 
на русском не распознаются. Пробовал файлы с двумя значениями bit rate: 1411 kbps; и 13 kbps - в обоих случаях получаю пустые значения "partial", "text". Сейчас в VoskActivity.java:
210:
 private void recognizeFile() {
        if (speechStreamService != null) {
            setUiState(STATE_DONE);
            speechStreamService.stop();
            speechStreamService = null;
        } else {
            setUiState(STATE_FILE);
            try {
                Recognizer rec = new Recognizer(model, 16000.f, "[\"one zero zero zero one\", " +
                        "\"oh zero one two three four five six seven eight nine\", \"[unk]\"]");
//----------------------------------------------------------------model RU:
/*                InputStream ais = getAssets().open(
                        "10001-90210-01803.wav"); */
                InputStream ais = getAssets().open(
                        "счет_а_2_16kbps.wav");
                if (ais.skip(44) != 44) throw new IOException("File too short");

                speechStreamService = new SpeechStreamService(rec, ais, 16000);
                speechStreamService.start(this);
            } catch (IOException e) {
                setErrorState(e.getMessage());
            }
        }
    }

**Comment by nshmyrev** [comment]
Формат файла неправильный. Должно быть 16bit 16khz mono. kbps смотреть не надо, это для сжатых файлов.

**Comment by nshmyrev** [comment]
It works now more or less
