### ISSUE TITLE
Why is speech recognition lagging so much behind other AI based projects?

### ISSUE THREAD

**Issue by ls-milkyway** [alphacep/vosk-api#1035]
I mean we have tremendous improvement in hardware, other AI based projects...but I feel speech recognition is far behind others due to:

1) No complex data is being used to train the models ....all are simply using old & clear voice data to train.
Why not to begin with complex data like movie/film audio & then move to simpler ones?? With following approach:

---->Data--------->Pre-Processing (Spleeter etc.)---------->Model Training----------->Trained Model (with custom vocabulary additions)-------->Post-Processing (Spell & Grammar Checkers etc).

2) Limitation of data ....specially clear voice data .....that can be solved by using audio data from complex sources as mentioned above.
Also a boon for projects with multi-lingual models.

3) Low accuracy in non-english models due to less & less reliable data.

**Comment by nshmyrev** [comment]
> No complex data is being used to train the models 

Sorry, this is not really true, gigaspeech model appeared last month recently (wenet and sherpa). Nvidia/Facebook also trains transformers on 24+k hours of data. There are multilingual models like XLS-R

> Low accuracy in non-english models due to less & less reliable data.

Not true either. Some languages like Chinese, Russian, German have enormous amount of data and accurate model. We just released Esperanto model trained on 2k hours of data.

**Comment by ls-milkyway** [comment]
> Sorry, this is not really true, gigaspeech model appeared last month recently (wenet and sherpa). Nvidia/Facebook also trains transformers on 24+k hours of data. There are multilingual models like XLS-R

Will get my hands on .....& check their real world performance...using various types of audio with/without noise , slang, bad words etc ....actually collecting them to perform a more practical standard benchmark.

> Not true either. Some languages like Chinese, Russian, German have enormous amount of data and accurate model. We just released Esperanto model trained on 2k hours of data.

Of course Chinese (Mandarin) is most spoken ....hence will have good collection of data.....but I feel some sort of intelligence is needed to be applied to the training data for better results....for eg.

1. An 24+k hours of data containing many repetitive words & sentences.....cannot be more useful than an 15+k hours of data containing all possible words with new sentences including all possible tone, noise, verbal expressions etc. 
2.  Hence this sort of intelligence is needed to obtain an ideal training data....hence pre processing the data (rather than only splitting it) to be used in training is required to increase the asr efficiency.

---->Data--------->Pre-Processing (another AI project, remove same words/sentences with same tone etc.)---------->Model Training----------->Trained Model (custom additions which trained model missed)-------->Post-Processing (Spell & Grammar Checkers etc).
OR
Collect all the DATA--------->Pre-Process It (as suggested) --------->Validate (If Ideal)----->Store it on blockchain project like [Arweave](https://www.arweave.org/) as a standard/ideal data for training.
Hence one division will solely work on pre-processing & storing the training data.

**Comment by ls-milkyway** [comment]
**To elaborate the role of blockchain & training data:**

Suppose we want to train UK english model......so according to me first 
1. I will consider to use all single words of the UK dictionary...by grabbing audio dictionary with all words (correct pronunciation).
2. I will collect UK film audio with 100% accurate subtitles & break the audio as sentences (using FFmpeg) according to time-codes in the subtitles
3. Hashes of the audio sentences and their audio wave-forms will be stored on a blockchain.

Finally, the new data will be included if and only if when the sentences in the data and/or it's wave-form do not match (that's because it has different tone, background noise etc.) with the hashes on the blockchain....this can be done by using an API call to the blockchain and compare the hashes.

Obviously hashes will be written on the blockchain when they are validated (100% accurate). Hence we have smart data and less time, energy or resources required to train....resulting in tremendous increase in the model's efficiency.
