### ISSUE TITLE
openfst (compiled by docker script) too limited for update packages

### ISSUE THREAD

**Issue by svenha** [alphacep/vosk-api#1038]
I followed the docker script. The openfst build is missing a `libfstscript.so`, which is needed by the update packages (via opengrm for `ngram` etc.).
The configure line for openfst is listed as:

    ./configure --prefix=/opt/kaldi/tools/openfst --enable-static --enable-shared --enable-far --enable-ngram-fsts --enable-lookahead-fsts --with-pic --disable-bin

How to adjust to also satisfy the needs of an update package?

**Comment by nshmyrev** [comment]
We do not have a docker suitable for update package. It might be interesting to create one. Or even add update API to Vosk itself.

**Comment by svenha** [comment]
Thanks for the answer. I don't use dockers. I just would like to know which configure options (for openfst) are needed in contrast to the ones listed above?

**Comment by nshmyrev** [comment]
Remove --disable-bin and thats probably it. libfstscript should be there.

**Comment by svenha** [comment]
Thanks. You helped me a lot.
