### ISSUE TITLE
How to use it with go lang

### ISSUE THREAD

**Issue by hajsf** [alphacep/vosk-api#1039]
I'm trying to use it with golang, but I stuck, what I did is:

1. Creating go module: `go mod init stt`
2. Installed the golib as: `go get github.com/alphacep/vosk-api/go`
3. Downloaded the Arabic model `vosk-model-ar-mgb2-0.4.zip` at folder `model`
4. Copied the existing audio file to folder: `audio/data.oga`
5. Writing the below code:
```go
package main

import (
	"fmt"
	"io/ioutil"

	vosk "github.com/alphacep/vosk-api/go"
)

func main() {

	model, err := vosk.NewModel("models/vosk-model-ar-mgb2-0.4.zip")
	if err != nil {
		fmt.Println("Error reading model,", err)
	}

	recognizer, err := vosk.NewRecognizer(model, 16000)
	if err != nil {
		fmt.Println("Error reading model,", err)
	}

	audio, err := ioutil.ReadFile("./audio/data.oga")
	if err != nil {
		fmt.Println(err)
	}
}
```

So my app now looks like:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/98168280/175765685-051b8842-d91f-44d6-81f8-4139e35ac1f8.png">

How to proceed further?

**Comment by nshmyrev** [comment]
See the example here:

https://github.com/alphacep/vosk-api/blob/master/go/example/test_simple.go

also note that you need to download binary release file for your platform and unpack it in specific folder.  

See also a duplicate https://github.com/alphacep/vosk-api/issues/708. Lets discuss in the previous issue.

**Comment by hajsf** [comment]
> unpack it in specific folder

I downloaded `vosk-win64-0.3.42.zip` but did not get it at what folder/path shall I unpack it

**Comment by hajsf** [comment]
> Lets discuss in the previous issue

ok
