### ISSUE TITLE
VOSK installation : ERROR: No matching distribution found for vosk Rpi 4 arm64

### ISSUE THREAD

**Issue by BeJay8675309** [alphacep/vosk-api#1042]
Hi,
Having issues installing vosk on fresh bullseye raspbian using pip3 and python 3.9.2 out of the box:

`sudo pip3 install vosk
Using pip 22.1.2 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk`

Any ideas would be great. Thanks!

**Comment by nshmyrev** [comment]
If you have trouble installing, check the output of the following commands and provide it for reference:

```
python3 --version
pip3 --version
pip3 -v install vosk
```

**Comment by BeJay8675309** [comment]
$ python3 --version
Python 3.9.2

$ pip3 --version
pip 22.1.2 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

$ pip3 -v install vosk
Using pip 22.1.2 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk

**Comment by nshmyrev** [comment]
Please note that some platforms are not fully supported by pip, for example on arm64 you have install from released wheels:

pip3 install https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-0.3.42-py3-none-linux_aarch64.whl

**Comment by BeJay8675309** [comment]
Thanks for the link will try it. The website (https://alphacephei.com/vosk/install) shows a 404 of this: https://github.com/alphacep/vosk-api/releases/download/v0.3.41/vosk-0.3.41-py3-none-linux_aarch64.whl

**Comment by nshmyrev** [comment]
Same as #479
