### ISSUE TITLE
Adjusting lm weight 

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#1044]
how to modify lm weight in vosk? kaldi  provid  parameter "--inv-acoustic-scale=10.0" to adjust  lm weight .

**Comment by nshmyrev** [comment]
There is `--acoustic-scale=1.0` in `model/conf/model.conf`, you can adjust there.

**Comment by zyb8543d** [comment]
> There is `--acoustic-scale=1.0` in `model/conf/model.conf`, you can adjust there.

“ --acoustic-scale=1.0 ” is relatively fixed parameters for chain model，generally not to change it.

**Comment by nshmyrev** [comment]
No, you can change it to adjust language weight. Try values like 0.8 or 1.2. It is the same as inv-acoustic-scale.

**Comment by zyb8543d** [comment]
> No, you can change it to adjust language weight. Try values like 0.8 or 1.2. It is the same as inv-acoustic-scale.

thanks，I close it

**Comment by zyb8543d** [comment]
@nshmyrev  I also use "--acoustic-scale=1.0" to adjust rescore lm weight?
