### ISSUE TITLE
cannot find -ldl

### ISSUE THREAD

**Issue by hajsf** [alphacep/vosk-api#1048]
I'm getting this error:
```bash
D:/Development/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
collect2.exe: error: ld returned 1 exit status
```

Knowing that I downloaded the binary from [vosk-win64-0.3.42.zip](https://github.com/alphacep/vosk-api/releases/tag/v0.3.42) and extracted it at `D:\Downloads\vosk-api-master\vosk-api-master\src` directory.

But while testing the provided example file as `D:\Downloads\vosk-api-master\vosk-api-master\go\example> go run test_simple.go` I got the mentioned error.

So, where can I find/download this -ldl file?

**Comment by nshmyrev** [comment]
Same as #672 672

**Comment by hajsf** [comment]
Both `vosk_api.h` and `libvosk.dll` are required to be downloaded from the binary [releases](https://github.com/alphacep/vosk-api/releases) and added to the app:

- `libvosk.dll` to be added to :
-- The `src` folder of the `vosk` package, in the go command you'll point to it as `// #cgo CPPFLAGS: -I src` and `// #cgo LDFLAGS: -L src -lvosk -lpthread`
-- The root path of your package, beside the `go.mod`
- `vosk_api.h` to be added beside your code funcion wherever you are calling the `vosk` commands, in the go command you'll point to it as `// #include <vosk_api.h>`

Notes: 
- Make sure to use the correct paths of the libraries in you code that is pointing to the For windows, you do not need the `-ldl`
- You can copy the `vosk_api.h` and `libvosk.dll` in other location, but have to ensure you are pointing to them correctly at the `.go` file
- The  `libvosk.dll` is a must to be copied at the root folder of the app (i.e. near to `go.mod` for the app to run correctly.

<img width="1079" alt="vosk" src="https://user-images.githubusercontent.com/98168280/184526391-01e6ada6-307a-4d20-a314-fcddafa12d9d.png">

You can copy the files beside the `.go` file that is calling the `vosk` commands, and point to it as `.` in the `FLAG` where `.` means these files are exisiting in the current directory:
```go
// #cgo CPPFLAGS: -I .
// #cgo LDFLAGS: -L . -lvosk -lpthread
// #include <stdlib.h>
// #include <vosk_api.h>
import "C"
import "unsafe"

// VoskModel contains a reference to the C VoskModel
type VoskModel struct {
	model *C.struct_VoskModel
}
```

<img width="116" alt="image" src="https://user-images.githubusercontent.com/98168280/184526784-80930636-cede-4806-8b8e-021b277ee666.png">
