### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tazz4843** [alphacep/vosk-api#1049]
Sorry for creating a duplicate issue, but I can't seem to reopen #1036 at all.

See the original thread for the full details, but I'll copy and paste my reply here:

I'm using Rust, with bindings to the C FFI, as here: https://github.com/Bear-03/vosk-rs.

I have been able to consistently reproduce this, no matter how I handle the Recognizers, whether that be freeing them as soon as I'm done with them, or holding on to them as long as possible.

**Comment by nshmyrev** [comment]
You can comment to reopen, it is a bad idea to open duplicates

Same as #1036
