### ISSUE TITLE
Language detection

### ISSUE THREAD

**Issue by hajsf** [alphacep/vosk-api#1053]
Is there a way to detect the spoken language before selecting the proper model?
In my app the user may speck English or Arabic, for English I can use either `model, err := vosk.NewModel("models/vosk-model-en-us-0.22-lgraph")` or `model, err := vosk.NewModel("models/vosk-model-en-us-0.22")` and for Arabic I can use `model, err := vosk.NewModel("models/vosk-model-ar-mgb2-0.4")` I need to be able to know the language spoken so I select the proper model?

**Comment by nshmyrev** [comment]
Yes, but you have to use external tools for that. Something like

https://huggingface.co/speechbrain/lang-id-commonlanguage_ecapa

https://github.com/igorsitdikov/lid_kaldi/

**Comment by nshmyrev** [comment]
Same as #420
