### ISSUE TITLE
cp: cannot stat 'exp/chain/tdnn1j_sp_online/final.mdl': No such file or directory

### ISSUE THREAD

**Issue by ramleda** [alphacep/vosk-api#1063]
When the Kaldi is on the step to generate dnn graph (lookahead) I receive the message:

`cp: cannot stat 'exp/chain/tdnn1j_sp_online/final.mdl': No such file or directory`

Bellow the execution that causes the message:

``utils/mkgraph_lookahead.sh : compiling grammar data/lang_test_small/G.fst
tree-info exp/chain/tree_sp/tree
tree-info exp/chain/tree_sp/tree
fstdeterminizestar data/lang_test_small/L_disambig.fst
fstcomposecontext --context-size=2 --central-position=1 --read-disambig-syms=data/lang_test_small/phones/disambig.int --write-disambig-syms=exp/chain/tree_sp/graph_small_lookahead/disambig_ilabels_2_1.int exp/chain/tree_sp/graph_small_lookahead/ilabels_2_1.7918 exp/chain/tree_sp/graph_small_lookahead/L_disambig_det.fst
make-h-transducer --disambig-syms-out=exp/chain/tree_sp/graph_small_lookahead/disambig_tid.int --transition-scale=1.0 exp/chain/tree_sp/graph_small_lookahead/ilabels_2_1 exp/chain/tree_sp/tree exp/chain/tree_sp/final.mdl
fstdeterminizestar
add-self-loops --disambig-syms=exp/chain/tree_sp/graph_small_lookahead/disambig_tid.int --self-loop-scale=1.0 --reorder=true exp/chain/tree_sp/final.mdl``

I can't see when `tdnn1j_sp_online` is created only `tdnn1j_sp`

**Comment by nshmyrev** [comment]
What command are you running exactly?

**Comment by nshmyrev** [comment]
Let us know when you have extra information
