### ISSUE TITLE
Реализация многопоточности для обрабатывания множества аудио данных

### ISSUE THREAD

**Issue by Saivaks** [alphacep/vosk-api#1066]
К сожалению большая модель Vosk работает достаточно медленно. Хотелось бы используя одну модель и один объект VoskRecognizer запускать распознавания сразу множества аудио файлов. Возможно ли это? Мои попытки использования Vosk таким образом приводили к краху программы. Или же необходимо для каждого потока создавать отдельный VoskRecognizer таким образом:

```
VoskModel* model = vosk_model_new("vosk-model-ru-0.22");
// recognizer object for 1 thread
VoskRecognizer* recognizer_1 = vosk_recognizer_new(model, Samplerate);
// recognizer object for 2 thread
VoskRecognizer* recognizer_2 = vosk_recognizer_new(model, Samplerate);
// recognizer object for 3 thread
VoskRecognizer* recognizer_3 = vosk_recognizer_new(model, Samplerate);
...
```

**Comment by nshmyrev** [comment]
Необходимо для каждого потока создавать отдельный VoskRecognizer
