### ISSUE TITLE
Package DataTang TDNN Chain Model

### ISSUE THREAD

**Issue by LyonGu** [alphacep/vosk-api#1071]
Hello:
    Please add this model [https://kaldi-asr.org/models/m10](https://kaldi-asr.org/models/m10).
    Or please show me some steps to convert it to Vosk.
    Thank you!

**Comment by nshmyrev** [comment]
You can get packaged model here:

https://alphacephei.com/vosk/models/vosk-model-cn-kaldi-aidatatang-m10.zip 

you just arrange the files. Take a note that this model works with vosk-0.3.32 or 0.3.43, not with 0.3.37-42

It is not very accurate model overall, we recommend you to use our latest models instead.

**Comment by LyonGu** [comment]
Thank you for your quick response!

> It is not very accurate model overall, we recommend you to use our latest models instead.

Ok, I'll consider your suggestion.
