### ISSUE TITLE
Confidence is not in a right format in NLSML format

### ISSUE THREAD

**Issue by sadrasabouri** [alphacep/vosk-api#1073]
I was checking out the `test_nlsml.py` and I got somethings like bellow results:
```xml
<?xml version="1.0"?>
<result grammar="default">
<interpretation grammar="default" confidence="210.007">
<input mode="speech">zero one eight zero three</input>
<instance>zero one eight zero three</instance>
</interpretation>
</result>
```
As I find out [here](https://www.lumenvox.com/knowledgebase/index.php?/article/AA-01803/0/NLSML.html):
> **confidence:** An optional integer from 0-100 (MRCPv1) or 0.0 to   1.0 (MRCPv2) indicating the semantic analyzer's confidence in this   interpretation.

and `210.007` won't fit into either of them.

I thinks [this](https://github.com/alphacep/vosk-api/blob/master/src/recognizer.cc#L644) line:
```
float likelihood = -(weight.Weight().Value1() + weight.Weight().Value2());
```
should be changed to `exp(weight.Weight().Value1())` or something like this.

**Comment by nshmyrev** [comment]
Same as #604
