### ISSUE TITLE
ModuleNotFoundError: No module named 'websockets'

### ISSUE THREAD

**Issue by michael1006** [alphacep/vosk-api#1077]
I had a problem earlier today (#1076) where `vosk-transcribe` wouldn't work after installing for the first time, and the solution was to upgrade from 0.3.42 to 0.3.43 which fixed #988. 

So I ran `pip3 install -U vosk` and the good news is, that did fix that problem. Thank you!

The bad news was, now running `vosk-transcriber` even simply like `vosk-transcriber --help` produces the following error:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/vosk-transcriber", line 5, in <module>
    from vosk.transcriber.cli import main
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/transcriber/cli.py", line 9, in <module>
    from vosk.transcriber.transcriber import Transcriber
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/transcriber/transcriber.py", line 8, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'
```

The solution -- running `pip3 install websockets` -- worked fine. But it seems like the pip3 Vosk installer is missing the websockets dependency to install it automatically. Since I didn't have this problem before, I'm guessing it was introduced with 0.3.43.

Again, I'm on a Macbook Air M1 running up-to-date Monterey, with Python3 installed via Homebrew.

**Comment by nshmyrev** [comment]
@vadimdddd please fix asap

**Comment by nshmyrev** [comment]
Fixed now

**Comment by zacheryparkin** [comment]
how did you guys fix this?

**Comment by nshmyrev** [comment]
> how did you guys fix this?

pip3 install websockets
