### ISSUE TITLE
Building failed with error: 'WordAlignLatticePartial' was not declared in this scope

### ISSUE THREAD

**Issue by hbasafa** [alphacep/vosk-api#1082]
Hi, I was trying to build vosk-api docker image using [this docker file from vosk-server](https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-vosk-server).

After building the kaldi image, it tries to build vosk-api, and then uses the vosk-server to serve the models. The vosk-api modules are build by running the following command:

```bash
    git clone https://github.com/alphacep/vosk-api /opt/vosk-api \
    && cd /opt/vosk-api/src \
    && KALDI_MKL=$KALDI_MKL KALDI_ROOT=/opt/kaldi make -j $(nproc) \
    && cd /opt/vosk-api/python \
    && python3 ./setup.py install 
```

which is noted [here](https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-vosk-server#L52).

This line failed with error:
```
recognizer.cc: In member function 'const char* Recognizer::PartialResult()': 
recognizer.cc:752:13: error: 'WordAlignLatticePartial' was not declared in this scope 
                        WordAlignLatticePartial(clat, *model_->trans_model_, *model_->winfo_, 0, &aligned_lat); 
                         ^~~~~~~~~~~~~~~~~~~~~~~ 
make: *** [Makefile:112: recognizer.o] Error 1 
make: *** Waiting for unfinished jobs....
```

I have review the file: ``` recognizer.cc ``` and it's true; there is no definition for the function WordAlignLatticePartial.

Thanks for any help.

**Comment by nshmyrev** [comment]
Looks like you are trying to use incompatible kaldi version. Our branch has this method.

**Comment by hbasafa** [comment]
Yes, that was true. The vosk image was using the cashed kaldi image which was the old one. I just rebuilt my kaldi image by cleaning the cashed one, and it got build without any error. Thanks.

I recommend to anybody facing this issue to build and run their docker file with this option: ```--no-cache```. It will mostly fix this issue.

**Comment by jtojnar** [comment]
Specifically, it looks like it needs `vosk` branch from this fork: https://github.com/alphacep/kaldi, according to https://alphacephei.com/vosk/install#building-the-library-libvoskso.

@nshmyrev is there any plan to eventually upstream [these changes](https://github.com/kaldi-asr/kaldi/compare/master...alphacep:kaldi:vosk)?

**Comment by nshmyrev** [comment]
@jtojnar thanks for asking. sure, there is a plan, we already pushed some changes upstream. No definite deadlines though

**Comment by PureTryOut** [comment]
Is there any progress on upstreaming things? I managed to compile the master branch of kaldi, but the `vosk` branch in the fork has all kinds of compilation issues. Could it at least be rebased every once and while? :sweat_smile:

**Comment by Moore123** [comment]
IMHO: maybe [ WordAlignLatticePartial ] in the code segment  for android , but it's should be [WordAlignLattice] for x86-linux.

**Comment by nshmyrev** [comment]
@PureTryOut what issues do you see exactly? It compiles well here.
