### ISSUE TITLE
lib.ts error in libvosk

### ISSUE THREAD

**Issue by donyam** [alphacep/vosk-api#1083]
TSError: ⨯ Unable to compile TypeScript:
src/lib.ts:307:7 - error TS2322: Type '{ vosk_model_new: ForeignFunction<Pointer<void>, [string | null]>; vosk_model_free: ForeignFunction<void, [Pointer<void>]>; ... 17 more ...; vosk_gpu_thread_init: ForeignFunction<...>; }' is not assignable to type 'VoskLibrary'.
  The types of 'vosk_model_new.async' are incompatible between these types.
    Type '(args_0: string | null, args_1: (err: any, value: Pointer<void>) => void) => void' is not assignable to type '(modelPath: string, cb: (err: Error | null, model: Type<Pointer<void>> | null) => void) => void'.
      Types of parameters 'args_1' and 'cb' are incompatible.
        Types of parameters 'model' and 'value' are incompatible.
          Type 'Pointer<void>' is missing the following properties from type 'Type<Pointer<void>>': size, indirection, get

307 const libvosk: VoskLibrary = ffi.Library(soname, {
          ~~~~~~~

    at createTSError (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2322 ]

**Comment by donyam** [comment]
> TSError: ⨯ Unable to compile TypeScript: src/lib.ts:307:7 - error TS2322: Type '{ vosk_model_new: ForeignFunction<Pointer, [string | null]>; vosk_model_free: ForeignFunction<void, [Pointer]>; ... 17 more ...; vosk_gpu_thread_init: ForeignFunction<...>; }' is not assignable to type 'VoskLibrary'. The types of 'vosk_model_new.async' are incompatible between these types. Type '(args_0: string | null, args_1: (err: any, value: Pointer) => void) => void' is not assignable to type '(modelPath: string, cb: (err: Error | null, model: Type<Pointer> | null) => void) => void'. Types of parameters 'args_1' and 'cb' are incompatible. Types of parameters 'model' and 'value' are incompatible. Type 'Pointer' is missing the following properties from type 'Type<Pointer>': size, indirection, get
> 
> 307 const libvosk: VoskLibrary = ffi.Library(soname, { ~~~~~~~
> 
> ```
> at createTSError (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:859:12)
> at reportTSError (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:863:19)
> at getOutput (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:1077:36)
> at Object.compile (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:1433:41)
> at Module.m._compile (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:1617:30)
> at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
> at Object.require.extensions.<computed> [as .ts] (C:\Users\Win 10 1903\Desktop\fahime\doc-yar\final\node_modules\ts-node\src\index.ts:1621:12)
> at Module.load (node:internal/modules/cjs/loader:981:32)
> at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> at Module.require (node:internal/modules/cjs/loader:1005:19) {
> ```
> 
> diagnosticCodes: [ 2322 ]

**Comment by donyam** [comment]
This issue happened when I used 
"@types/ffi-napi": "^4.0.5",
    "@types/ref-napi": "^3.0.4",
    
 But when I used 
 "@types/ffi-napi": "^2.4.3",
    "@types/ref-napi": "^1.4.1",
    
    I didn't have any error in my lib.ts but I had new error in build . so after enter yarn build I have this error
    
    Found 21 errors in 2 files.

Errors  Files
     2  node_modules/@types/ffi-napi/index.d.ts:149
    19  node_modules/@types/ref-struct-di/index.d.ts:26

**Comment by nshmyrev** [comment]
We have typescript pull request between, see here: https://github.com/alphacep/vosk-api/pull/546

**Comment by donyam** [comment]
I used that but I had new issue in src/lib.ts    in line 307  "const libvosk: VoskLibrary = ffi.Library(soname, { ....."



const libvosk: VoskLibrary
Type '{ vosk_model_new: ForeignFunction<Pointer<void>, [string | null]>; vosk_model_free: ForeignFunction<void, [Pointer<void>]>; ... 17 more ...; vosk_gpu_thread_init: ForeignFunction<...>; }' is not assignable to type 'VoskLibrary'.
  The types of 'vosk_model_new.async' are incompatible between these types.
    Type '(args_0: string | null, args_1: (err: any, value: Pointer<void>) => void) => void' is not assignable to type '(modelPath: string, cb: (err: Error | null, model: Type<Pointer<void>> | null) => void) => void'.
      Types of parameters 'args_1' and 'cb' are incompatible.
        Types of parameters 'model' and 'value' are incompatible.
          Type 'Pointer<void>' is missing the following properties from type 'Type<Pointer<void>>': size, indirection, getts(2322)
