### ISSUE TITLE
Training data for french model

### ISSUE THREAD

**Issue by melcherc** [alphacep/vosk-api#1085]
Hi, I would like to know on which data was trained the following french model : [vosk-model-fr-0.22](https://alphacephei.com/vosk/models/vosk-model-fr-0.22.zip).
Is it possible to obtain the relevant training files ?
Thank you

**Comment by nshmyrev** [comment]
We do not distribute model training data, sorry.

**Comment by nshmyrev** [comment]
Same as #719

**Comment by melcherc** [comment]
Thanks for your answer.

**Comment by Tebounet** [comment]
The result with vosk-model-fr.0.22 is impeccable for some videos, and completely unrelated to the audio for other videos. If we restart, we always get the same crazy result. Could the cause be the fact that it is a dialogue between two people?

**Comment by nshmyrev** [comment]
> Could the cause be the fact that it is a dialogue between two people?

Yes, sure. It is a usual problem.
