### ISSUE TITLE
how to convert the kaldi SAD model to vosk model ? 

### ISSUE THREAD

**Issue by shuiyuejihua** [alphacep/vosk-api#1086]
I do not  install  the kaldi , and want to know how to convert  the kaldi model to vosk model , such as [ASpIRE SAD Model 1a](https://kaldi-asr.org/models/m4) or [Chime 6 SAD system](https://kaldi-asr.org/models/m12).

I found a closed isuue [#1071 Package DataTang TDNN Chain Model](https://github.com/alphacep/vosk-api/issues/1071) .

Is the convert method scipt in kaldi ?

**Comment by nshmyrev** [comment]
Vosk doesn't support Kaldi SAD models, yo can not convert them

**Comment by shuiyuejihua** [comment]
ok
