### ISSUE TITLE
Is there any way to get Vosk to run fast on a Raspberry pi 4B?

### ISSUE THREAD

**Issue by Tomohiro-Doi** [alphacep/vosk-api#1088]
Hi. We are trying to use Vosk with a Raspberry pi 4B. 
However, the Raspberry pi 4B takes about 3 seconds to recognize speech. 

Is there any way to improve this voice recognition time and speed up the recognition?

**Comment by nshmyrev** [comment]
> Hi. We are trying to use Vosk with a Raspberry pi 4B.

Which model are you trying?

> However, the Raspberry pi 4B takes about 3 seconds to recognize speech.

How long is that speech? An hour or two?

**Comment by nshmyrev** [comment]
Please provide more details on your problem

**Comment by Tomohiro-Doi** [comment]
> Which model are you trying?

I used vosk-model-small-jp-0.22

> How long is that speech? An hour or two?

No. Short, four or five second words.

I am trying to run real-time offline speech recognition as much as possible using vosk on a Raspberry pi 4B. But as you can see in the video, the speech recognition takes a long time. I would like to know how to solve this problem.

**Comment by nshmyrev** [comment]
Please edit model.conf inside the model like this:

```
--max-active=3000
--beam=10.0
--lattice-beam=2.0
```

instead of current values.

**Comment by Tomohiro-Doi** [comment]
Thank you very much for response. I will try this.
