### ISSUE TITLE
raise Exception("Failed to create a model") with vosk-model-pt-fb-v0.1.1-20220516_2113

### ISSUE THREAD

**Issue by communitydev2** [alphacep/vosk-api#1090]
Hi, I currently use the english model and works great, so I used the exact same code for the pt-fb model and the raise Exception("Failed to create a model") comes up. 

I tried to redownload the model, and still doesn't work. Is there any issue with it that I'm unaware of? 

Thanks in advance.

**Comment by nshmyrev** [comment]
What is the memory available in your system

**Comment by nshmyrev** [comment]
Same is #991, please continue there

**Comment by mukunda1002** [comment]
I am getting Failed to create model error in vosk

**Comment by ELigoP** [comment]
Me too.
```
...
ERROR (VoskAPI:Model():model.cc:122) Folder '/home/user/.cache/vosk/vosk-model-tts-ru-0.6-multi' does not contain model files.
...
```

But there clearly are files:
```
$ ls ~/.cache/vosk/vosk-model-tts-ru-0.6-multi/ -alrh
total 232M
-rw-rw-r-- 1 user user 136M Jun  5 21:29 model.onnx
-rw-rw-r-- 1 user user  97M Jun  5 21:29 dictionary
-rw-rw-r-- 1 user user 2.8K Jun  5 21:29 config.json
drwxrwxr-x 3 user user 4.0K Jun  5 21:29 ..
drwxrwxr-x 2 user user 4.0K Jun  5 21:29 .
```

**Comment by nshmyrev** [comment]
> Me too.
> 
> ```
> ...
> ERROR (VoskAPI:Model():model.cc:122) Folder '/home/user/.cache/vosk/vosk-model-tts-ru-0.6-multi' does not contain model files.
> ...
> ```
> 
> But there clearly are files:
> 
> ```
> $ ls ~/.cache/vosk/vosk-model-tts-ru-0.6-multi/ -alrh
> total 232M
> -rw-rw-r-- 1 user user 136M Jun  5 21:29 model.onnx
> -rw-rw-r-- 1 user user  97M Jun  5 21:29 dictionary
> -rw-rw-r-- 1 user user 2.8K Jun  5 21:29 config.json
> drwxrwxr-x 3 user user 4.0K Jun  5 21:29 ..
> drwxrwxr-x 2 user user 4.0K Jun  5 21:29 .
> ```

Its completely unrelated. You are trying to load TTS model into ASR recognizer

**Comment by isaquecsilva** [comment]
Hi!

I dont know if you guys still have this problem, but the way i solved was just to move all the files inside folders to outside, except for ivector.

Now its running.

**Comment by KubaSlv** [comment]
Hi,

I had this exact problem, the "Exception: Failed to create a model", in my case, I was copying the path incorrectly, most often you're told to copy the vosk model path up until the first folder "vosk-model-small-pl-0.22", but I found that copying the path to the second one worked for me.

Now it works and hopefully it will for you too.
