### ISSUE TITLE
Alternative German models 

### ISSUE THREAD

**Issue by zonradkuse** [alphacep/vosk-api#1093]
Hello and thanks for the work on vosk! Using vosk, I've implemented a system which helps me transcribing interviews. The results are already decent considering that language in interviews can be really tough to recognize.

However, I was looking into checking out different models and noticed that it is pretty hard to find any other German models (besides the three listed on the vosk homepage). Unfortunately, I don't have the resources to train another model or adapt one.

Has anybody had the time to check out https://github.com/uhh-lt/kaldi-tuda-de and if it is feasible to get it running in vosk? They report an WER of about 7% on tuda-de-dev which is slightly better than the large German 0.21 model.

**Comment by nshmyrev** [comment]
Hello. We are kind of upset you don't trust our capabilities to train a good model ;)

Tuda model is huge in size. You can try it in vosk here:
https://alphacephei.com/vosk/models/vosk-model-de-tuda-0.5-722k.zip

If you really want more accuracy you can also try https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_de_conformer_transducer_large

**Comment by zonradkuse** [comment]
Thank you :) Also for linking back #139 - I wasn't aware that creating the vosk model from the tuda one is relatively easy.

No offense meant ;) - I was already impressed by how well your model performs on the (really really really) unstructured voice data I have. Getting WER down by another few (2 or so) percent might save me a few hours of manual transcription.

**Comment by zonradkuse** [comment]
This model already works nicely! thanks again!

I just tried setting up the even more recent and slightly larger [tuda-de-900k](https://github.com/uhh-lt/kaldi-tuda-de#newest-pretrained-models) model for vosk myself. It seems like all necessary files are present but I can't find the `G.fst` file in the const arpa model they provide. Am I blind or am I (more likely) missing a fundamental step?

**Comment by zonradkuse** [comment]
I found one in http://ltdata1.informatik.uni-hamburg.de/kaldi_tuda_de/de_900k_lang_dirs.tar.bz2 -- I guess, they cleaned it.

**Comment by nshmyrev** [comment]
Ok, I created too

https://alphacephei.com/vosk/models/vosk-model-de-tuda-0.6-900k.zip
