### ISSUE TITLE
node-ffi version giving precedence to DLLs from system path instead of local directory

### ISSUE THREAD

**Issue by rotemdan** [alphacep/vosk-api#1096]
For more information see [my comment](https://github.com/alphacep/vosk-api/issues/755#issuecomment-1200103183) on the issue [Dynamic Linking Error Win32 error 127](https://github.com/alphacep/vosk-api/issues/755#).

I had that error happen and resolved it by removing/downgrading the versions of:
```
libstdc++-6.dll
libwinpthread-1.dll
```

That were installed by Anaconda on `~\anaconda3\Library\mingw-w64\bin`, a directory which by default it adds to system path. The particular packages responsible for these files were `m2w64-gcc-libs-5.3.0-7` or `m2w64-gcc-libs-core-5.3.0-7`.

This shouldn't happen and I can imagine would cause issues for many users. I'm not sure if this is caused by Vosk itself or by some behavior of `node-ffi`.

**Comment by nshmyrev** [comment]
Hi! This is extremely helpful, thanks for figuring this problem out.

I have just pushed a fix, please check if it fixes the issue.

**Comment by rotemdan** [comment]
I replicated the change you made on https://github.com/alphacep/vosk-api/commit/967024d20ab8c824269602b00a14a4280099a74d manually in `index.js`:

changed:
```js
process.env.Path = currentPath + path.delimiter + dllDirectory;
```

to:
```js
process.env.Path = dllDirectory + path.delimiter + currentPath;
```

Now the issue seems resolved on my machine. Thanks for the quick response.
