### ISSUE TITLE
Automatic download of the models, hugginface style

### ISSUE THREAD

**Issue by dimjava** [alphacep/vosk-api#11]
Ubuntu 16.04, installed with "pip3 install vosk"

>> python3.5 test-vosk.py test.wav 
vosk --min-active=200 --max-active=3000 --beam=10.0 --lattice-beam=2.0 --acoustic-scale=1.0 --frame-subsampling-factor=3 --endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10 --endpoint.rule2.min-trailing-silence=0.5 --endpoint.rule3.min-trailing-silence=1.0 --endpoint.rule4.min-trailing-silence=2.0 
ERROR (vosk[5.5.599~1-11bed]:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf

**Comment by nshmyrev** [comment]
Please download and extract the model from https://github.com/alphacep/kaldi-android-demo/releases and unpack to "model" folder.

**Comment by dimjava** [comment]
> Please download and extract the model from https://github.com/alphacep/kaldi-android-demo/releases and unpack to "model" folder.

Thanks, I just thought that these models are embedded in the package

**Comment by nshmyrev** [comment]
Right, I need to implement some kind of automatic download.

**Comment by cjbassi** [comment]
If users are able to use different models, would it still make sense to automatically download a model? I think the readme instructions for how to download a model might be sufficient.

**Comment by nshmyrev** [comment]
You'll be surprised how many people unable to download the file according to the instructions ;)

**Comment by nshmyrev** [comment]
Done now!
