### ISSUE TITLE
Kaldi version for vosk android

### ISSUE THREAD

**Issue by fly2mun** [alphacep/vosk-api#1100]
What version of Kaldi did you use when making the vosk android version?
I need help setting up my environment. 
I want to use the kaldi script that you have published at github.
Thanks. Moon.

**Comment by nshmyrev** [comment]
Hello. The script uses vosk-android branch on github

https://github.com/alphacep/vosk-api/blob/master/android/lib/build-vosk.sh#L112

**Comment by fly2mun** [comment]
Hello. nshmyrev

Thanks for your support.

My plan is to ask you to re-train for english android mobile version.

I am trying to use the following script.

https://github.com/alphacep/vosk-api/blob/master/training/run.sh#L22

Please wish me good luck.

Thanks, Moon.

**Comment by nshmyrev** [comment]
Good luck
