### ISSUE TITLE
Text output while mic is muted

### ISSUE THREAD

**Issue by auandaru** [alphacep/vosk-api#1101]
Hello, I am using nerd-dictation with vosk and I think this is the place I need to go... 

So basically what happens is while the speech recognition is running, and there should be no sound inputs whatsoever, the software still produces "huh huh huh" every few seconds or minute or so.  

- the mic inputs are all muted in pulseaudio
- I even went to alsamixer and muted the Capture (mic) input
- The hardware mic is unplugged, the internal mic is muted
- I can leave the (quiet) room and it still does this, also I thought it might be my computer fan but the mute should rule this out

I know this is similar to other reports about "huh" and "the", but I think this might be a bit different because presumably the absence of noise should not cause any reactions. (Unless I missed something)

I am still figuring out how to change the model and see if this is specific to the default model, or happens across models.

Edit: Ah, actually if I kill the process and start it again with everything muted as above, the "huh" stops spamming. Interesting.. So we do this again: toggling alsamixer capture doesn't seem to have an effect, the key to reproducing this is in pulseaudio and under applications there is a "parec" process. Muting that causes the program to stop picking up my voice, but the app still types "huh" every few seconds.

**Comment by nshmyrev** [comment]
It is the same issue as #837. Total silence also might produce garbage words. Model needs update.
