### ISSUE TITLE
Implement gradio demo

### ISSUE THREAD

**Issue by nshmyrev** [alphacep/vosk-api#1113]
as we discussed

**Comment by nshmyrev** [comment]
Merged now

**Comment by oliverxuyong** [comment]
Hi There,
When I run the test_gradio.py, I got an error as follows:
===========================
/Users/oxu/learn-english/venv/bin/python /Users/oxu/learn-english/vosk-api/python/example/test_gradio.py
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /Users/oxu/.cache/vosk/vosk-model-small-en-us-0.15/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCL and G from /Users/oxu/.cache/vosk/vosk-model-small-en-us-0.15/graph/HCLr.fst /Users/oxu/.cache/vosk/vosk-model-small-en-us-0.15/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo /Users/oxu/.cache/vosk/vosk-model-small-en-us-0.15/graph/phones/word_boundary.int
Traceback (most recent call last):
  File "/Users/oxu/learn-english/vosk-api/python/example/test_gradio.py", line 33, in <module>
    gr.Audio(source="microphone", type="numpy", streaming=True),
  File "/Users/oxu/learn-english/venv/lib/python3.8/site-packages/gradio/component_meta.py", line 155, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'

**Comment by nshmyrev** [comment]
Fixed now, please update from github

**Comment by nshmyrev** [comment]
@oliverxuyong we needed to update to latest gradio api
