### ISSUE TITLE
How do i used vosk C# with a microphone?

### ISSUE THREAD

**Issue by smbika007** [alphacep/vosk-api#1116]
Hi, I am using c# in VS 2019. I tried googling for how to use a microphone and found mainly people using NAudio. I tried several versions of NAudio and they either lacked one function or another (WaveFileWriter, WaveInEvent...) or gave me this:

**System.BadImageFormatException: 'Could not load file or assembly 'NAudio, Version=1.5.3.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.'**

Ironically the error above came after I finally got it to compile using a version from Github.

Any advice? Can I use a microphone for live speech recognition without NAudio?

Thanks,
Smbika

**Comment by nshmyrev** [comment]
>  I tried several versions of NAudio

Which version exactly did you try?

> System.BadImageFormatException: 'Could not load file or assembly 'NAudio, Version=1.5.3.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.'

Last on was definitely wrong.

**Comment by smbika007** [comment]
from the package I downloaded from:
https://www.nuget.org/packages/NAudio
i tried the versions in the following folders:
net6.0
net6.-windows7.0
net472
netcoreapp3.1
each one gave me compilation errors (could not find this or that)

**Comment by smbika007** [comment]
so, is NAudio required to run Vosk with a microphone?

**Comment by nshmyrev** [comment]
> each one gave me compilation errors (could not find this or that)

Which error exactly?

> so, is NAudio required to run Vosk with a microphone?

No, you can use other audio recording packages as well

**Comment by nshmyrev** [comment]
Same as #986

**Comment by smbika007** [comment]
WaveFileWriter, WaveInEvent and one other function wasn't found in NAudio.Wave - weird.

So, #986 is where I can find other mentions of audio packages. I will look at them - I actually got the code I am trying to make work with NAudio from the first comments on that page. 

Thanks.

**Comment by smbika007** [comment]
If there is a preferred NAudio version, do you know what it is?

**Comment by nshmyrev** [comment]
Any version should work including the latest one, yo can check example here https://github.com/naudio/NAudio/blob/master/Docs/RecordWavFileWinFormsWaveIn.md

**Comment by smbika007** [comment]
Thanks. I'll see what I can do.
