### ISSUE TITLE
Can I change some parameters in Vosk?

### ISSUE THREAD

**Issue by Iagodel** [alphacep/vosk-api#112]
I got some results on the decoder from Kaldi and results from Vosk. The results from Kaldi decoder are better than results from Vosk.

I want to do some changes in the parameters like beam, lattice-beam and others.

**Comment by nshmyrev** [comment]
Which parameters do you want to change exactly?

**Comment by nshmyrev** [comment]
beam, lattice-beam and max-active are configured inside the model in conf/model.conf. For others, let me know.
