### ISSUE TITLE
The system cannot find the path specified: 'C:\Users\.cache\vosk'

### ISSUE THREAD

**Issue by codingzebra333** [alphacep/vosk-api#1125]
Hi,
I am trying to get vosk to recognize all .wav files in a specific folder and return the results in a text file. Is there any easy solution for it in Python?

**Comment by vadimdddd** [comment]
@codingzebra333, hello, https://github.com/alphacep/vosk-api/tree/master/python/vosk/transcriber this is exactly what you need then. After you download it will be here: .../vosk-api/python/vosk/transcriber, then you just simply need to run this like: vosk-transcriber -i path_to_folder_with_files -o path_to_folder_with_results(vosk-transcriber -i home/user/examples -o home/user/results)

**Comment by codingzebra333** [comment]
Thanks! After I run the command, I get this error:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\.cache\\vosk'
Exception ignored in: <function Model.__del__ at 0x00000163AF18ED30>
Traceback (most recent call last):
  File "C:\Users\lib\site-packages\vosk\__init__.py", line 56, in __del__
    _c.vosk_model_free(self._handle)
AttributeError: 'Model' object has no attribute '_handle'

**Comment by vadimdddd** [comment]
@codingzebra333 https://github.com/alphacep/vosk-api/issues/988 looks like this issue, but I fixed that so it has to work now, did you download latest VOSK version? The error means this path doesn't exist: 'C:\Users\.cache\vosk' - check it and create it manually if not, and let me know about your current VOSK version, that bug was fixed so I thought all ok for current version, thanks.

**Comment by codingzebra333** [comment]
Thank you! This solved the issue. Is there a way to get all results saved in one text file instead of multiple?

**Comment by vadimdddd** [comment]
@codingzebra333 1) tell me your VOSK version pls(path: .../vosk-api/python, here open setup.py file and check 49 string there, I have to know you download prev version or I made smth wrong current, It's important for me) and 2) no, if you have multiple files at start - you will get multiple files at end, if you have 1 file at start you will get 1 file at end.

**Comment by codingzebra333** [comment]
1) Version 0.3.43
2) Thank you!

**Comment by nshmyrev** [comment]
Yet to figure out why the folder was not created automatically

**Comment by codingzebra333** [comment]
I have another question regarding reading all files in a folder - where can I specify which model to use?

**Comment by codingzebra333** [comment]
I have another question - how can I change the vosk model? It uses small model by default.

**Comment by vadimdddd** [comment]
@codingzebra333 
key -l (language) en-us, it, ru etc.
key -m (model path) select path to your model folder.
key -n (model_name) vosk-model-small-en-us-0.15 - as default.
also you can check available languages and models, using: --list-languages/--list-models
you can find full info in cli.py script parser-args part.
