### ISSUE TITLE
go: freeRecognizer / freeModel

### ISSUE THREAD

**Issue by andrestone** [alphacep/vosk-api#1128]
Is there any particular reason why these two functions are not exported?

**Comment by nshmyrev** [comment]
There is Free

https://github.com/alphacep/vosk-api/blob/master/go/vosk.go#L73
https://github.com/alphacep/vosk-api/blob/master/go/vosk.go#L24

**Comment by andrestone** [comment]
Oh! I was running on v0.3.36 for some reason. No `Free` there. 

Thanks!

**Comment by nshmyrev** [comment]
Ok, good
