### ISSUE TITLE
{Question] How to fetch logs and reduce CPU usage

### ISSUE THREAD

**Issue by nishanth-cn** [alphacep/vosk-api#1132]
Hi 

I am trying to use vosk library for audio to text convertion in server. When I try to launch multiple apps and use 10-15 clients to run a audio script and convert audio in each app, my server is crashing without any logs. Setting any log level is not helping to get vosk logs. How can I get vosk logs in a file , is there any crash log file in VOSK or any log callback ?
Also when I try to launch more than 100 threads in server, CPU usage shoots up drastically. All threads create individual recognizer but I am loading model only once. So I am looking for suggestions to reduce CPU usage.

Thanks in Advance
Nishanth

**Comment by nshmyrev** [comment]
it depends on your server hardware

**Comment by nishanth-cn** [comment]
@nshmyrev what about logs ? any ways to get crash logs ?

**Comment by nshmyrev** [comment]
Logs are printed on standard output. The process is probably killed by OOM detector, you will not get logs then but a message in system log.
