### ISSUE TITLE
Error building the library libvosk.so

### ISSUE THREAD

**Issue by siliconvallley** [alphacep/vosk-api#1136]
Reference steps:
[Building the library libvosk.so](https://alphacephei.com/vosk/install)

> cd <KALDI_ROOT>
git clone -b vosk --single-branch https://github.com/alphacep/kaldi /opt/kaldi
cd kaldi/tools
make openfst
./extras/install_openblas_clapack.sh
cd ../src
./configure --mathlib=OPENBLAS_CLAPACK --shared
make -j 10 online2 lm rnnlm
cd ../..
git clone https://github.com/alphacep/vosk-api
cd vosk-api/src
KALDI_ROOT=<KALDI_ROOT> make

My steps：

> cd <KALDI_ROOT>
git clone https://github.com/alphacep/kaldi 
cd kaldi/tools
make openfst
 // There is no install_openblas_clapack.sh script in kaldi, only install_openblas.sh.
 // ./extras/install_openblas_clapack.sh  
./extras/install_openblas.sh  
cd ../src
// ./configure --mathlib=OPENBLAS_CLAPACK --shared
 ./configure  --shared
make -j 10 online2 lm rnnlm

> git clone https://github.com/alphacep/vosk-api
cd vosk-api/src
KALDI_ROOT=<KALDI_ROOT> make

Execute the command "KALDI_ROOT=<KALDI_ROOT> make", and the following exception occurs::

> g++ -g -O3 -std=c++17 -Wno-deprecated-declarations -fPIC -DFST_NO_DYNAMIC_LINKING -I. -I/home/dinghui/code/kaldi/kaldi/src -I/home/dinghui/code/kaldi/kaldi/tools/openfst/include  -I/home/dinghui/code/kaldi/kaldi/tools/OpenBLAS/install/include -c -o recognizer.o recognizer.cc
recognizer.cc: In member function ‘const char* Recognizer::PartialResult()’:
recognizer.cc:752:13: error: ‘WordAlignLatticePartial’ was not declared in this scope
  752 |             WordAlignLatticePartial(clat, *model_->trans_model_, *model_->winfo_, 0, &aligned_lat);
      |             ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:112: recognizer.o] Error 1

Please help to solve the current exception, thank you.

**Comment by nshmyrev** [comment]
You need to follow steps closely, the command was 

git clone -b vosk --single-branch https://github.com/alphacep/kaldi /opt/kaldi

**Comment by siliconvallley** [comment]
> You need to follow steps closely, the command was
> 
> git clone -b vosk --single-branch https://github.com/alphacep/kaldi /opt/kaldi

Thank you, .so has been compiled.

**Comment by nshmyrev** [comment]
ok, great

**Comment by nshmyrev** [comment]
Same as #1082
