### ISSUE TITLE
Release 0.3.43 - Not Available in Python

### ISSUE THREAD

**Issue by djfight** [alphacep/vosk-api#1138]
I went to pull the latest release (0.3.43), but pip is telling me that version 0.3.43 is not available.

Here's the command output that I get when trying to upgrade
```
pip install vosk==0.3.43
ERROR: Could not find a version that satisfies the requirement vosk==0.3.43 (from versions: 0.3.18, 0.3.21, 0.3.22, 0.3.27, 0.3.28, 0.3.29, 0.3.30, 0.3.31, 0.3.32, 0.3.38, 0.3.40, 0.3.41, 0.3.42)
ERROR: No matching distribution found for vosk==0.3.43
```

**Comment by nshmyrev** [comment]
We probably left out some platforms

**Comment by berhram** [comment]
> We probably left out some platforms

Such as Android (Maven Central). Please update

**Comment by breandan** [comment]
I also noticed the latest build on Maven Central seems to be [`0.3.38`](https://search.maven.org/artifact/com.alphacephei/vosk/0.3.38/jar).

**Comment by nshmyrev** [comment]
I published 0.3.45, but OSX build is broken, I need to find a workaround to build OSX versions

**Comment by vikasthange** [comment]
I can confirm MacOS is still broken. I would like to hear if anyone had any workaround.

**Comment by nshmyrev** [comment]
For OSX tracked here: https://github.com/alphacep/vosk-api/issues/1422
