### ISSUE TITLE
Error when loading model without iVectors

### ISSUE THREAD

**Issue by FBorgeat** [alphacep/vosk-api#114]
I tried loading a model made from the TiDigits recipe from the kaldi for dummies tutorial and got this error:

E/VoskAPI: ExpectToken():io-funcs.cc:209) Expected token "<Nnet3>", got instead "<DIMENSION>".

**Comment by nshmyrev** [comment]
Which model exactly? You'd better share it. Most likely some file is wrong.

**Comment by FBorgeat** [comment]
Apart from saying TiDigits, I'm not sure how to tell which model but those are the files I put in:

G.fst
HCLG.fst
L_disambig.fst
final.mdl
mfcc.conf
phones.txt
word_boundary.int
words.txt

based on the proposed model structure in: https://github.com/alphacep/vosk-api/blob/master/doc/models.md. Let me know if there's anything else I should provide, like the scripts I used maybe?

**Comment by nshmyrev** [comment]
Provide the model in archive

**Comment by FBorgeat** [comment]
It's not from the archive, it was generated through the TiDigits recipe
using kenlm instead of SRILM.


Frédéric Borgeat

**Comment by nshmyrev** [comment]
> It's not from the archive, it was generated through the TiDigits recipe

You need to share that model so I can check, otherwise I can't really help. Hard to guess what happens on your side. As far as I know kaldi for dummies doesn't build nnet3 model, you need neural network model first of all.

**Comment by FBorgeat** [comment]
I had tried to give you the model last night but it might not have gone
through, so here is the whole directory in attachments, with what you told
me also earlier, i have also been trying to to make another version of
mini_librispeech with the same data i used in the kaldi for dummies
tutorial, since the original recipe has so much data that it produces a
500MB sized HCLG which android studio will not take, but it does produce
the iVector files. I simply need a model for very limited vocabulary(few
short commands and many 3 digit numbers) along with data augmentation to
compensate for a frequent periodic "tick" background noise. Which I have
read in a google group is better to simply add the noise in the sound files.

I thank you in advance for any advice and hope all is well during these
challenging times,

Frédéric Borgeat

**Comment by nshmyrev** [comment]
@FBorgeat I don't see your attachment or links to google drive

As for big hclg, you need to use smaller language model, then the graph will be small. And you need to compile lookahead graph. You can probably just use smaller graph with our default model as in https://github.com/alphacep/vosk-api/blob/master/doc/adaptation.md

**Comment by FBorgeat** [comment]
[tidigits.zip](https://github.com/alphacep/vosk-api/files/4697827/tidigits.zip)

thanks for the reference, i will apply it but i still need a model based on my own data for legal purposes

**Comment by nshmyrev** [comment]
> tidigits.zip

This is gmm model, you need nnet3 model. Even default en-us will be very accurate compared to gmm.

**Comment by FBorgeat** [comment]
So mini_librispeech with my own data with added background "tick" noise should do the job?

**Comment by nshmyrev** [comment]
> So mini_librispeech with my own data with added background "tick" noise should do the job?

mini_librispeech should be ok, but don't forget to disable online cmvn in tdnn. We do not support online cmvn yet.

For "tick" you'd better provide me the sample to better understand what your tick is about.

**Comment by FBorgeat** [comment]
Would it be possible to send the sample to you privately?

**Comment by nshmyrev** [comment]
Yes, sure, nshmyrev@gmail.com

**Comment by FBorgeat** [comment]
Also just to confirm, the lookahead graph is generated by mkgraph_lookahead.sh?

**Comment by nshmyrev** [comment]
> Also just to confirm, the lookahead graph is generated by mkgraph_lookahead.sh?

Yes
