### ISSUE TITLE
Question about the program running multiple times.

### ISSUE THREAD

**Issue by StianWiu** [alphacep/vosk-api#1144]
Hi, I noticed in the Node.js code example that it is set to run multiple times. I was wondering what the purpose of this was. Is it to get a more accurate final result or something?

**Comment by nshmyrev** [comment]
It is just a way demo implemented to showcase various scenarios.

**Comment by StianWiu** [comment]
Ok, so there is no benefit to it?

**Comment by nshmyrev** [comment]
No
