### ISSUE TITLE
Mac OS Intel Python install

### ISSUE THREAD

**Issue by boxabirds** [alphacep/vosk-api#1147]
Hi y'all so I am trying to get vosk running on my Intel Mac. 

1. `python setup.py build` then `python setup.py install` ran with final output `Finished processing dependencies for vosk==0.3.43`
1. Then running I got `'/…/vosk-0.3.43-py3.9.egg/vosk/libvosk.dyld' (no such file)`
2. Researching suggested the install process doesn't install the `dylib` file so I downloaded [this version](https://github.com/alphacep/vosk-api/releases/download/v0.3.32/vosk-osx-0.3.32.zip) because 0.3.43 Mac OS X [doesn't seem to exist](https://github.com/alphacep/vosk-api/releases/download/v0.3.43/vosk-osx-0.3.43.zip)… and put it inside the vosk folder where it was looking. 
3. Error now is
`'/…/vosk-0.3.43-py3.9.egg/vosk/libvosk.dyld' not valid for use in process: library load disallowed by system policy)`

The error that comes up in a dialog box is

`“libvosk.dyld” cannot be opened because the developer cannot be verified.`

Command line error is

`/…/vosk/libvosk.dyld' not valid for use in process: library load disallowed by system policy)`

Does anyone know how to ask my Mac to accept this binary? Or more generally, how to get Vosk installed and working on Intel Macs? 

Any guidance most warmly appreciated!

**Comment by nshmyrev** [comment]
`pip3 install vosk` should work

**Comment by boxabirds** [comment]
Thanks yes I somehow got into a tangle and everything went horribly wrong. But a fresh install worked. I assume running `python setup.py build` probably wreaked havoc …
