### ISSUE TITLE
Why doesn`t .gitignore contain "vosk-api/python/vosk/vosk_cffi.py" ?

### ISSUE THREAD

**Issue by tez3998** [alphacep/vosk-api#1149]
Sorry to ask something so elementary.

vosk_cffi.py is automatically generated by running vosk_builder.py.
However, according to .gitignore, Git tracks vosk_cffi.py.
Is this intentional?
If so, do you always delete or do git stash vosk_cffi.py before doing git checkout?

```.gitignore
# Python
wheelhouse
__pycache__
*.egg-info
python/dist
python/build
python/vosk/*.so
python/test/db
python/test/hyp
python/test/model
python/test/ref
python/test/result.txt
python/test/wav.scp
```

**Comment by nshmyrev** [comment]
vosk_cffi.py is created in python/build/lib and ignored according to .gitignore.

We do not create vosk-api/python/vosk/vosk_cffi.py during build

**Comment by tez3998** [comment]
Thanks for the reply.
It seems like I did not read setup.py enough.
