### ISSUE TITLE
about kaldi make, "x86_64-linux-android-x86_64-linux-android21-clang++" is not install?

### ISSUE THREAD

**Issue by Nie-Yingying** [alphacep/vosk-api#115]
Hi,
when I do " gradle build " in "android", there is always CXX problem as follows. 

========================log==================================
+ cd /home/user6/workspace/vosk-api-master/android/build/kaldi_x86_64/kaldi/src
+ CXX=x86_64-linux-android21-clang++
+ CXXFLAGS=' -O3 -DFST_NO_DYNAMIC_LINKING'
+ ./configure --use-cuda=no --mathlib=OPENBLAS --shared --android-incdir=/home/user6/software/android-sdk-linux/ndk/21.1.6352462//toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include --host=x86_64-linux-android --openblas-root=/home/user6/workspace/vosk-api-master/android/build/kaldi_x86_64/local --fst-root=/home/user6/workspace/vosk-api-master/android/build/kaldi_x86_64/local --fst-version=1.6.7
Configuring KALDI to use OPENBLAS.
Checking compiler x86_64-linux-android-x86_64-linux-android21-clang++ ...
***configure failed: x86_64-linux-android-x86_64-linux-android21-clang++ is not installed.
             You need g++ >= 4.7, Apple clang >= 5.0 or LLVM clang >= 3.3. ***
+ make -j 8 depend
Makefile:30: kaldi.mk: 没有那个文件或目录
================================================================

IF I update the kaldi/src/configue, and comment out the lines 942-945, there is other problem.
if is_set $HOST; then
  #CXX="$HOST-$CXX"
  #AR="$HOST-$AR"
  #AS="$HOST-$AS"
  #RANLIB="$HOST-$RANLIB"

============================log=================================
> Task :externalNativeBuildDebug FAILED
Build kaldi_jni_armeabi-v7a
ninja: error: '../../../../build/kaldi_arm_32/kaldi/src/online2/kaldi-online2.a', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libkaldi_jni.so', missing and no known rule to make it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/user6/software/android-sdk-linux/cmake/3.6.4111459/bin/cmake with arguments {--build /home/user6/workspace/vosk-api-master/android/.cxx/cmake/debug/armeabi-v7a --target kaldi_jni}

  ninja: error: '../../../../build/kaldi_arm_32/kaldi/src/online2/kaldi-online2.a', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libkaldi_jni.so', missing and no known rule to make it

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================

Thanks for your attention!

**Comment by nshmyrev** [comment]
So you miss `x86_64-linux-android-x86_64-linux-android21-clang++`, you need to figure out which version do you have and why it is not installed. It is part of the SDK, you need to reinstall SDK probably.

**Comment by nshmyrev** [comment]
I hope this one is solved now. Feel free to reopen if you need further help.

**Comment by gunjanddave** [comment]
@Nie-Yingying  Hey, you able to resolve this? I am facing the same issue.

**Comment by nshmyrev** [comment]
> @Nie-Yingying Hey, you able to resolve this? I am facing the same issue.

What is the content of `sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin` in your case. Do you have ndk installed at all?

**Comment by gunjanddave** [comment]
Yes, I do have NDK Installed instead of linux-x86_64 its darwin because of MACOS.
Attached is the screenshot of content, content also has others arch as well.
<img width="533" alt="Screenshot 2020-06-12 at 1 51 15 PM" src="https://user-images.githubusercontent.com/36508093/84481561-e0de2600-acb3-11ea-835e-1ba6be9dcd04.png">

**Comment by nshmyrev** [comment]
> I do have NDK Installed instead of linux-x86_64 its darwin because of MACOS.

You should have start with mentioning that.

I have just pushed the fix for osx. Update and try again.

**Comment by gunjanddave** [comment]
@nshmyrev It is working fine now for OSX.
