### ISSUE TITLE
Testing output: seeking deterministic results

### ISSUE THREAD

**Issue by boxabirds** [alphacep/vosk-api#1152]
Hi there: as this is probabilistic technology, I understand there are always going to be variations between invocations. I also wanted to know if there’s anyway to  be able to freeze a set of parameters such that my test cases are going to consistently produce the same result? Maybe we manually set a seed somewhere? If not I’d love to know how other people are testing vosk.

**Comment by nshmyrev** [comment]
Same as #868 

We might implement this feature soon
