### ISSUE TITLE
[Newbie Question] Subtitles in srt format with only one word per line

### ISSUE THREAD

**Issue by Gonzalo-Canavesio** [alphacep/vosk-api#1154]
Hello,
I am generating subtitles for a video using "vosk-transcriber -i video.mp4 -t srt -o video.srt".

Can you help me to know how to make the generated subtitles have only one word per line? The srt file should look like this:

```
1
00:00:05 --> 00:00:07
Hi

2
00:00:9 --> 00:00:10
how

3
00:00:11 --> 00:00:12
are

4
00:00:13 --> 00:00:15
you
```

ps: sorry for asking such a specific question, I don't have much programming experience, although I understand some python.

**Comment by nshmyrev** [comment]
When you use [test_srt.py](https://github.com/alphacep/vosk-api/blob/master/python/example/test_srt.py) you can change words_per_line argument to 1:

https://github.com/alphacep/vosk-api/blob/master/python/vosk/__init__.py#L199

**Comment by Gonzalo-Canavesio** [comment]
Thank you for the help
