### ISSUE TITLE
Linux wheel have bad names except x86_64

### ISSUE THREAD

**Issue by papoteur-mga** [alphacep/vosk-api#1155]
When installing wheel build on i586 or arm arches, this fails with module vosk not being found.
```
ERROR: Could not find a version that satisfies the requirement 
vosk==0.3.43 (from versions: none)
```
In fact, the name is not what is expected.
on 32 bits architectures, the names are vosk-0.3.43-py3-none-linux_32bit.whl,
On aarch64, the name is vosk-0.3.43-py3-none-linux_x86_64.whl
These wheel are not accepted by pip to be installed.
Here is a patch to have a conform name.
https://svnweb.mageia.org/packages/cauldron/python-vosk-api/current/SOURCES/vosk-api-py-wheel.patch?view=markup
The author is Jani Välimaa.

**Comment by nshmyrev** [comment]
I'm sorry, I don't get the issue. It builds fine here, we make wheels. Could you elaborate?

**Comment by papoteur-mga** [comment]
I used pyproject macros for the build in a spec file for building rpm package in Mageia.
The build went fine in x86_86 but failed on other arches. The fail occurs at install step when a command is launched to install the wheel file previously built. The command which fails is:
```
/usr/bin/python3 -m pip install --root /builddir/build/BUILDROOT/python-vosk-api-0.3.43-1.pap.mlo9.i386 --prefix /usr --no-deps --disable-pip-version-check --progress-bar off --verbose --ignore-installed --no-warn-script-location --no-index --no-cache-dir --find-links /builddir/build/BUILD/vosk-api-0.3.43/pyproject-wheeldir vosk==0.3.43
```
And the result:
```
Using pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)
Looking in links: /builddir/build/BUILD/vosk-api-0.3.43/pyproject-wheeldir
ERROR: Could not find a version that satisfies the requirement 
vosk==0.3.43 (from versions: none)
ERROR: No matching distribution found for vosk==0.3.43
```
When I tried directly to install the wheel inside the chroot where the build is done, I get this error:
```
vosk-0.3.43-py3-none-linux_32bit.whl is not a supported wheel on this platform
```
The wheel was `vosk-0.3.43-py3-none-linux_32bit.whl`

**Comment by papoteur-mga** [comment]
I presume that the environment variables VOSK_SYSTEM and VOSK_ARCHITECTURE are defined on your build system, and it don't use default ones.
https://github.com/alphacep/vosk-api/blob/32aa980069495b88aa79d192d1ef42ad88d0ec73/python/setup.py#L10-L11
On aarch64, platform.architecture()[0]' returns '64bit', which leads to tag the wheel with 'x86_64'.

**Comment by nshmyrev** [comment]
Ok, we might use platform.machine to distinguish between x86_64 linux and aarch64 without external variables. Thnaks for the report

**Comment by nshmyrev** [comment]
It should be fixed now
