### ISSUE TITLE
A solution of noise and silence being recognized as "嗯" for chinese  asr model

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#1157]
For chinese asr model, I met a problem that noise and silence have been recognized as "嗯".
I check the LM corpus, find a large mount of word "嗯" in it. so I remove all  word "嗯" in LM corpus, add a few sentence including words "嗯" in LM corpus ,then retrain the LM, finally the problem have been solved completely.

**Comment by zyb8543d** [comment]
close it，if need help，please comment it.

**Comment by allanwxm** [comment]
> close it，if need help，please comment it.

您好，请问能推荐一下相关技术文章吗？之前没接触过机器学习和模型训练，我们现在的需求是想在vosk中文识别模型里增加几个不在词库里的关键词，然后重新训练。参考了vosk官网的文档Vosk Language Model Adaptation，但还是不太明白具体的处理步骤。

**Comment by nshmyrev** [comment]
打开新问题并随时提出具体问题，我们应该能够提供帮助。 您也可以通过 contact@alphacephei.com 或微信 (nv_shmyrev) 将单词列表和项目描述发送给我。 我会为您更新模型。

**Comment by allanwxm** [comment]
> 打开新问题并随时提出具体问题，我们应该能够提供帮助。 您也可以通过 [contact@alphacephei.com](mailto:contact@alphacephei.com) 或微信 (nv_shmyrev) 将单词列表和项目描述发送给我。 我会为您更新模型。

感谢您的回复，我会给您发送一封电子邮件。
