### ISSUE TITLE
error docker

### ISSUE THREAD

**Issue by bottookku** [alphacep/vosk-api#1160]
Sep 28 23:45:21 asterisk systemd: Started libcontainer container 72a35f648d56e71b6f297d8f96724d3bc743db06232b925fdb1b12dfb8d22e11.
Sep 28 23:45:22 asterisk kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Sep 28 23:45:22 asterisk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sep 28 23:45:22 asterisk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth896090a: link becomes ready
Sep 28 23:45:22 asterisk kernel: docker0: port 1(veth896090a) entered blocking state
Sep 28 23:45:22 asterisk kernel: docker0: port 1(veth896090a) entered forwarding state
Sep 28 23:45:22 asterisk NetworkManager[904]: <info>  [1664376322.3372] device (veth896090a): carrier: link connected
Sep 28 23:45:22 asterisk NetworkManager[904]: <info>  [1664376322.3381] device (docker0): carrier: link connected
Sep 28 23:45:23 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
Sep 28 23:45:23 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
Sep 28 23:45:26 asterisk journal: LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
Sep 28 23:45:26 asterisk journal: LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
Sep 28 23:45:26 asterisk journal: LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
Sep 28 23:45:27 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /opt/vosk-model-ru/model/ivector/final.ie
Sep 28 23:45:28 asterisk journal: LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
Sep 28 23:45:28 asterisk journal: LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
Sep 28 23:45:28 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from /opt/vosk-model-ru/model/graph/HCLG.fst
Sep 28 23:45:36 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading words from /opt/vosk-model-ru/model/graph/words.txt
Sep 28 23:45:36 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo /opt/vosk-model-ru/model/graph/phones/word_boundary.int
Sep 28 23:45:36 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:310) Loading subtract G.fst model from /opt/vosk-model-ru/model/rescore/G.fst
Sep 28 23:45:38 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:312) Loading CARPA model from /opt/vosk-model-ru/model/rescore/G.carpa
Sep 28 23:45:52 asterisk journal: LOG (VoskAPI:ReadDataFiles():model.cc:318) Loading RNNLM model from /opt/vosk-model-ru/model/rnnlm/final.raw
Sep 28 23:46:02 asterisk systemd: Started Session 2427 of user root.
Sep 28 23:46:06 asterisk journal: Traceback (most recent call last):
Sep 28 23:46:06 asterisk journal:  File "/opt/vosk-server/websocket/./asr_server.py", line 116, in <module>
Sep 28 23:46:06 asterisk journal:    asyncio.run(start())
Sep 28 23:46:06 asterisk journal:  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Sep 28 23:46:06 asterisk journal:    return loop.run_until_complete(main)
Sep 28 23:46:06 asterisk journal:  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Sep 28 23:46:06 asterisk journal:    return future.result()
Sep 28 23:46:06 asterisk journal:  File "/opt/vosk-server/websocket/./asr_server.py", line 106, in start
Sep 28 23:46:06 asterisk journal:    model = Model(args.model_path)
Sep 28 23:46:06 asterisk journal:  File "/usr/local/lib/python3.9/dist-packages/vosk-0.3.38-py3.9.egg/vosk/__init__.py", line 29, in __init__
Sep 28 23:46:06 asterisk journal:    raise Exception("Failed to create a model")
Sep 28 23:46:06 asterisk journal: Exception: Failed to create a model
Sep 28 23:46:08 asterisk kernel: docker0: port 1(veth896090a) entered disabled state
Sep 28 23:46:08 asterisk NetworkManager[904]: <info>  [1664376368.8526] manager: (vethe38e76d): new Veth device (/org/freedesktop/NetworkManager/Devices/30)
Sep 28 23:46:09 asterisk kernel: docker0: port 1(veth896090a) entered disabled state
Sep 28 23:46:09 asterisk kernel: device veth896090a left promiscuous mode
Sep 28 23:46:09 asterisk kernel: docker0: port 1(veth896090a) entered disabled state
Sep 28 23:46:09 asterisk NetworkManager[904]: <info>  [1664376369.0263] device (veth896090a): released from master device docker0
Sep 28 23:46:09 asterisk dockerd-current: time="2022-09-28T23:46:09.690870287+09:00" level=warning msg="72a35f648d56e71b6f297d8f96724d3bc743db06232b925fdb1b12dfb8d22e11 cleanup: failed to unmount secrets: invalid argument"

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-server/issues/77. You do not have enough memory. You need 16Gb

**Comment by bottookku** [comment]
memory is RAM or disk?
