### ISSUE TITLE
openfst float equality failed

### ISSUE THREAD

**Issue by johngebbie** [alphacep/vosk-api#1161]
Hello. I'm trying to package vosk but it's failing to compile openfst (your version) for i686.
The continuous integration says:
```
configure: error: Test float equality failed! Compile with -msse -mfpmath=sse if using g++.
188
See `config.log' for more details
189
=> ERROR: vosk-api-0.3.43_1: pre_build: 'CXXFLAGS="$CXXFLAGS -msse -mfpmath=sse" ./configure ${CROSS_BUILD:+--host="${XBPS_CROSS_TRIPLET}"} --prefix="${wrksrc}/kaldi-${_kaldi_commit}/tools/openfst" --enable-static --enable-shared --enable-far --enable-ngram-fsts --enable-lookahead-fsts --with-pic --disable-bin' exited with 1
```

As you can see I even added the -msse -mfpmath=sse it says to add, after the first time it failed (which broke the other architectures :/).
It  cross compiles successfully on my x86_64 machine, but I think the continuous integration is actually i686.

I see you added a commit regarding this test:
https://github.com/alphacep/openfst/commit/256f83e52112a5cd37e37a34beff2c4f0eae4660
And hope you might know what to do. Thank you.

The full continuous integration output:
https://github.com/void-linux/void-packages/actions/runs/3144957627/jobs/5116830966

**Comment by nshmyrev** [comment]
You should have add --host and --build as in:

https://github.com/alphacep/vosk-api/blob/master/travis/Dockerfile.dockcross#L42

there is no need for -msse

**Comment by johngebbie** [comment]
Thank you! I've got --host, I'll look into --build and that's good to know. I'll report back.

**Comment by johngebbie** [comment]
I've added --host and --build but I'm still having trouble.
The error is now:
```
configure: error: Test float equality failed! Compile with -msse -mfpmath=sse if using g++.
See `config.log' for more details
=> ERROR: vosk-api-0.3.43_1: pre_build: './configure --host="${XBPS_TRIPLET}" ${CROSS_BUILD:+--host="${XBPS_CROSS_TRIPLET}"} --build="${XBPS_TRIPLET}" --prefix="${wrksrc}/kaldi-${_kaldi_commit}/tools/openfst" --enable-static --enable-shared --enable-far --enable-ngram-fsts --enable-lookahead-fsts --with-pic --disable-bin' exited with 1
=> ERROR:   in pre_build() at srcpkgs/vosk-api/template:57
```
https://github.com/void-linux/void-packages/actions/runs/3159496036/jobs/5143218476

**Comment by nshmyrev** [comment]
build must be x86-linux-gnu, see the link

**Comment by johngebbie** [comment]
Oh it must be cross compiled from x86_64? Is that due to any constraint or just simplicity and what you know works?
I had a look and the build system has a no-cross compilation option but I don't see a cross compile only option.

**Comment by nshmyrev** [comment]
We cross-compile vosk for x86, you won't be able to compile it natively. Build of openfst templates require like 8Gb of memory, it will not fit x86 memory space.

The patch disables check for cross-compilation, not for standard build.

**Comment by johngebbie** [comment]
> We cross-compile vosk for x86, ..., not fit x86 memory space.

I'm sorry, I'm still lost.
The --build option specifies the system on which the package is built doesn't it.
So --build=x86-linux-gnu means building on x86_64 for whatever --host architecture.

I'm not using Docker but Void Linux's xbps-src, and so I don't know if the memory concern is relevant in this case.

The Void Linux continuous integration seems to want to compile for i686 on i686.
It seems like openfst should be able to compile for i686 on i686.

Back in a bit, it's my tea.
