### ISSUE TITLE
Is it possible to switch off the language model?

### ISSUE THREAD

**Issue by RobinE89** [alphacep/vosk-api#1163]
Hey, 

I'm very excited about what VOSK has to offer. I would be interested if there is a way to turn off the LanguageModel and get the uncorrected transcription of the AcousticModel instead. 

Many thanks for advice!! 
Robin

**Comment by nshmyrev** [comment]
No, it is not possible in Vosk

Similar to https://github.com/alphacep/vosk-api/issues/736

**Comment by RobinE89** [comment]
ok. that would be a very helpful option for some use cases though! For example, if you want to identify pronunciation errors or if you want to use an asr  to assign system commands without the need for correct spelling. in this case, you can use other optimization methods to effectively correct transcription errors. with the elimination of the LM, you then have a massive performance advantage.
long story short:
I would be very happy if this feature would also be available in VOSK in the future! but thanks for your (very) quick reply!

**Comment by nshmyrev** [comment]
Sure, thank you for your comments

**Comment by ruohoruotsi** [comment]
What about adjusting the `acoustic scale` similar to https://github.com/alphacep/vosk-api/issues/1044?
