### ISSUE TITLE
Endpointer parameters description

### ISSUE THREAD

**Issue by fly2mun** [alphacep/vosk-api#1171]
I wonder what the parameters of model.conf contain.
Other parameters can be found in kaldi script.
But I can't find the following content, what does it mean?

--min-active=200
--max-active=3000
--beam=10.0
--lattice-beam=2.0
--acoustic-scale=1.0
--frame-subsampling-factor=3
--endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10

======> this... 
--endpoint.rule2.min-trailing-silence=0.5 --> this !!!!
--endpoint.rule3.min-trailing-silence=0.75 --> this !!!
--endpoint.rule4.min-trailing-silence=1.0 --> this !!!

I also looked for the neural net xconfig parser parameter in run_tdnn.sh, but I can't figure out exactly what it means.

Is this not necessary?

**Comment by nshmyrev** [comment]
Endpointer rules are explained in Kaldi code and documentation. See here:

https://github.com/kaldi-asr/kaldi/blob/master/src/online2/online-endpoint.h#L128

and here:

https://kaldi-asr.org/doc/structkaldi_1_1OnlineEndpointRule.html

**Comment by nshmyrev** [comment]
Same as #380
