### ISSUE TITLE
from vosk import Model, KaldiRecognizer ImportError: No module named vosk

### ISSUE THREAD

**Issue by Mesutdelen** [alphacep/vosk-api#1176]
Hello,

I am working with vosk software using orange pi zero 256mb and python.  I try so many idea and always ı see this error. I installed old version of Vosk and download old-new  (.whl) file  make a virtual environment (env) but doesnt work anyone. Please help 

**Note:** 
> This code works on Pc-python. 
> Pip and python all the last version. 
> I was just able to upload this "Vosk-0.3.44-py3-none-linux_armv7l.whl" .  The other versions not supported.

**My Code**

> from vosk import Model, KaldiRecognizer
> import os
> if not os.path.exists("tr"):
>     exit (1)
> import pyaudio
> p = pyaudio.PyAudio()
> stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=8000)
> stream.start_stream()
> model = Model("tr")
> rec = KaldiRecognizer(model, 16000)
> while True:
>    data = stream.read(2000, exception_on_overflow = False)
>    if len(data) == 0:
>        break
>    if rec.AcceptWaveform(data):
>        print(rec.Result())
> print(rec.FinalResult())

![Ekran görüntüsü 2022-10-21 223540](https://user-images.githubusercontent.com/114522926/197277160-ea65e0ca-17d8-4647-88cd-83e2c00f8346.png)

**Comment by nshmyrev** [comment]
You need to provide pip install log.

**Comment by Mesutdelen** [comment]
[LOG_FILE.txt](https://github.com/alphacep/vosk-api/files/9842117/LOG_FILE.txt)


> You need to provide pip install log.

**Comment by nshmyrev** [comment]
This log has nothing to do about Vosk, it is about some other package

**Comment by Mesutdelen** [comment]
> This log has nothing to do about Vosk, it is about some other package

- 2022-10-22T00:32:41,278 Using pip 22.3 from /home/duvarlar123/.local/lib/python3.8/site-packages/pip (python 3.8)
- 2022-10-22T00:32:41,295 Defaulting to user installation because normal site-packages is not writeable
- 2022-10-22T00:32:42,152 Created temporary directory: /tmp/pip-build-tracker-lyunso9f
- 2022-10-22T00:32:42,153 Initialized build tracking at /tmp/pip-build-tracker-lyunso9f
- 2022-10-22T00:32:42,154 Created build tracker: /tmp/pip-build-tracker-lyunso9f
- 2022-10-22T00:32:42,154 Entered build tracker: /tmp/pip-build-tracker-lyunso9f
- 2022-10-22T00:32:42,155 Created temporary directory: /tmp/pip-install-92lfh2l8
- 2022-10-22T00:32:42,162 Created temporary directory: /tmp/pip-ephem-wheel-cache-twpudra1
- 2022-10-22T00:32:42,369 Requirement already satisfied: vosk in ./.local/lib/python3.8/site-packages (0.3.44)
- 2022-10-22T00:32:42,409 Requirement already satisfied: tqdm in ./.local/lib/python3.8/site-packages (from vosk) (4.64.1)
- 2022-10-22T00:32:42,415 Requirement already satisfied: websockets in ./.local/lib/python3.8/site-packages (from vosk) (8.1)
- 2022-10-22T00:32:42,420 Requirement already satisfied: srt in ./.local/lib/python3.8/site-packages (from vosk) (3.5.2)
- 2022-10-22T00:32:42,428 Requirement already satisfied: cffi>=1.0 in ./.local/lib/python3.8/site-packages (from vosk) (1.15.1)
- 2022-10-22T00:32:42,433 Requirement already satisfied: requests in ./.local/lib/python3.8/site-packages (from vosk) (2.28.1)
- 2022-10-22T00:32:42,448 Requirement already satisfied: pycparser in ./.local/lib/python3.8/site-packages (from cffi>=1.0->vosk) (2.21)
- 2022-10-22T00:32:42,525 Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->vosk) (2.8)
- 2022-10-22T00:32:42,535 Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->vosk) (2019.11.28)
- 2022-10-22T00:32:42,544 Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->vosk) (1.25.8)
- 2022-10-22T00:32:42,553 Requirement already satisfied: charset-normalizer<3,>=2 in ./.local/lib/python3.8/site-packages (from requests->vosk) (2.1.1)
- 2022-10-22T00:32:42,750 Created temporary directory: /tmp/pip-unpack-kgp0zmzk
- 2022-10-22T00:32:45,154 Remote version of pip: 22.3
- 2022-10-22T00:32:45,155 Local version of pip:  22.3
- 2022-10-22T00:32:45,158 Was pip installed by pip? True
- 2022-10-22T00:32:45,160 Removed build tracker: '/tmp/pip-build-tracker-lyunso9f'

**Comment by nshmyrev** [comment]
This is not an install log, the package is already installed probably.

If you install from user, it will not work as root under sudo probably, you need to install with sudo as well

**Comment by Mesutdelen** [comment]
I already tried as sudo but reinstalling armbian system solved my problem. Thank you for your interest.
