### ISSUE TITLE
How to use speaker identification

### ISSUE THREAD

**Issue by frech87** [alphacep/vosk-api#1178]
Hi. Great Job. In models I see "vosk-model-spk-0.4". Have you example, how to use this model for speaker language identification?

**Comment by nshmyrev** [comment]
You are welcome. Speaker identification is discussed in #405

**Comment by MehdiyevSoltan2004** [comment]
Hi. I want to use the model "vosk-model-spk-0.4", but I keep getting this error:
ERROR (VoskAPI:Model():model.cc:122) Folder 'vosk-model-spk-0.4' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Exception: Failed to create a model.
Can anyone help?

**Comment by dfengpo** [comment]
405 didn't give any helpful answers at all
