### ISSUE TITLE
build from source error

### ISSUE THREAD

**Issue by qyou** [alphacep/vosk-api#118]
When I build from source, error happens:
```bash
vosk/kaldi_recognizer.cc:287:29: error: no member named 'GetNonsilenceFrames' in 'kaldi::OnlineSilenceWeighting'
        silence_weighting_->GetNonsilenceFrames(feature_pipeline_->NumFramesReady(),
```
It seems that the `OnlineSilenceWeighting` class has no such member function  `GetNonsilenceFrames`. Which `kaldi` version should I use to compile the code?

**Comment by nshmyrev** [comment]
Lookahead branch from our fork. See

https://github.com/alphacep/vosk-api#kaldi-compilation-for-local-python-node-and-java-modules

**Comment by emiboy68** [comment]
GetNonsilenceFrames is not a method in online2/online-ivector-feature.cc

**Comment by nshmyrev** [comment]
The corresponding patch was merged into kaldi too, so you might just update kaldi.
