### ISSUE TITLE
How to compile source code for python

### ISSUE THREAD

**Issue by MahdiEsrafili** [alphacep/vosk-api#1188]
Hello. I want to change some parts of source code in `src` directory. I did some changes and then run `vosk_builder.py` in `python` directory. This file output these lines:    
```
E:\anaconda3\lib\site-packages\cffi\cparser.py:150: UserWarning: String literal found in cdef() or type source. String literals are ignored here, but you should remove them anyway because some character sequences confuse pre-parsing.
  warnings.warn("String literal found in cdef() or type source. "
generating .\vosk\vosk_cffi.py
```
But no changes affected when running python code. So what else should be done?

**Comment by nshmyrev** [comment]
You should be very careful about things you put in header file, it is parsed automatically and not always correctly. It is better to follow original style.

**Comment by MahdiEsrafili** [comment]
@nshmyrev The changes were too small. I just changed the `words` in output of `Result` method. 

So for compiling, is these steps enough? or should I follow `Compilation from source steps` mentioned in documents?

**Comment by MahdiEsrafili** [comment]
I could finally figured out how to compile. It's NOT enough to run `vosk_builder.py`; It doesn't compile the source code.  It's needed to run `build-docker.sh` in `travis` directory.
