### ISSUE TITLE
Pre-trained model on Librispeech Dataset.

### ISSUE THREAD

**Issue by Pradii23** [alphacep/vosk-api#119]
Can anyone provide a pre-trained Kaldi model on Librispeech dataset compatible with vosk.

**Comment by nshmyrev** [comment]
This model should work http://kaldi-asr.org/models/m13

**Comment by Pradii23** [comment]
I tried to use this model with vosk but got an error with Kaldi's fatal error.

ERROR (VoskAPI:OnlineTransform():online-feature.cc:533) Dimension mismatch: source features have dimension 91 and LDA #cols is 281
terminate called after throwing an instance of 'kaldi::KaldiFatalError'

**Comment by nshmyrev** [comment]
You took mfcc.conf instead of mfcc_hires.conf, see the [documentation](https://github.com/alphacep/vosk-api/blob/master/doc/models.md#model-structure) 

`conf/mfcc.conf - mfcc config file. Make sure you take mfcc_hires.conf version if you are using hires model (most external ones)
`

**Comment by Pradii23** [comment]
HCLG.fst file is not present in this model.
Will you please tell me how can we get it ?

**Comment by nshmyrev** [comment]
hclg is created with mkgraph kaldi script, don't forget to add --self-loop-scale 1.0

**Comment by Pradii23** [comment]
Will you please elaborate on this.

**Comment by nshmyrev** [comment]
You can download https://alphacephei.com/kaldi/models/vosk-model-en-us-librispeech-0.2.zip

**Comment by mbelcen** [comment]
just remove mfcc.conf, rename mfcc_hires.conf (if it's there) into mfcc.conf and it should work
