### ISSUE TITLE
Understanding partial confidence

### ISSUE THREAD

**Issue by johngebbie** [alphacep/vosk-api#1191]
Hello, my program pretty much the presses keys on different words, and I'd like a mode where it reacts quicker even if less accurately, and thought reacting to partial results would be the way.
I've got it reacting to partial results without any confidence threshold and it's too unaccurate.
But I don't understand the confidence values from my tests.

When I limit the vocab to: ["external", "externally", "exterminate", "exterminated", "extermination", "exterminator"]
and say "eggs", I often get "external" with a conf of 1.0.

I thought confidence would be how likely it thinks what you've said will be a specific keyword, so it would be low if you say the start common to lots of phrases.
In my case, I'd like it to wait for more information if unsure.
Is that not how it works? Is this a bad approach?

Thank you!

Probably not helpful, but here's my test program (that reads audio from stdin):
```
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	vosk "github.com/alphacep/vosk-api/go"
)

func main() {
	vosk.SetLogLevel(-1)
	model, err := vosk.NewModel("model")
	if err != nil {
		panic(err)
	}
	rec, err := vosk.NewRecognizerGrm(model, 16000, `["external", "externally", "exterminate", "exterminated", "extermination", "exterminator"]`)
	if err != nil {
		panic(err)
	}
	rec.SetWords(1)
	rec.SetPartialWords(1)

	r := bufio.NewReader(os.Stdin)
	buf := make([]byte, 4096)

	for {
		_, err := io.ReadFull(r, buf)
		if err != nil {
			if err == io.EOF || err == io.ErrUnexpectedEOF {
				break
			}
			panic(err)
		}

		if rec.AcceptWaveform(buf) == 0 {
			fmt.Println(rec.PartialResult())
		} else {
			fmt.Println(rec.FinalResult())
		}
	}

	fmt.Println(string(rec.FinalResult()))
}
```

**Comment by nshmyrev** [comment]
If you want confidence it is a bad idea to limit vocabulary for just a few words

**Comment by johngebbie** [comment]
Okay, thank you. My real program has about 130 words, I'll try implementing it for realsies and report back.

**Comment by johngebbie** [comment]
I seemed to get 1.0 confidence very nearly always, but I found a non-vosk issue about keys not being released in that mode that was making it look much worse than it was.
Now using partials with no condition is working pretty okay.
I might dig deeper into using confidences later, but I'm happy for now.
Thank you, you must be sick of dumb issues.

**Comment by johngebbie** [comment]
You kindly put it on your integrations page a year or so ago but I've released my voice input software (there's a video of me using it [here](https://numen.johngebbie.com)) so many thanks!
