### ISSUE TITLE
Option to pass custom model files in BatchModel GPU inferance

### ISSUE THREAD

**Issue by mehadi92** [alphacep/vosk-api#1195]
Hi, I'm working with the script [test_gpu_batch.py](https://github.com/alphacep/vosk-api/blob/master/python/example/test_gpu_batch.py)
And it's working in GPU env without any issues. But I could not find any options to pass custom model files to the `BatchModel` object like,
```python
model = BatchModel("<path_to_my_custom_model_files>")
```
Also, I try to pass the model  name from [vosk models](https://alphacephei.com/vosk/models) but it always loads the same model

I check the source code of the `BatchModel` object in [here](https://github1s.com/alphacep/vosk-api/blob/HEAD/src/batch_model.cc#L32-L37) and found static values like bellow,
```c
    string nnet3_rxfilename_ = "model/am/final.mdl";
    string hclg_fst_rxfilename_ = "model/graph/HCLG.fst";
    string word_syms_rxfilename_ = "model/graph/words.txt";
    string winfo_rxfilename_ = "model/graph/phones/word_boundary.int";
    string std_fst_rxfilename_ = "model/rescore/G.fst";
    string carpa_rxfilename_ = "model/rescore/G.carpa";
``` 
Is there anything that I missing Or BatchModel don't support custom model yet

Thanks

**Comment by nshmyrev** [comment]
For now path is hardcoded. You still can put any model at that path.

**Comment by mehadi92** [comment]
@nshmyrev Thanks. Putting the different model in that path solves my issue
