### ISSUE TITLE
Getting segmentation fault with Librispeech model implementation

### ISSUE THREAD

**Issue by sharma2ananya** [alphacep/vosk-api#120]
LOG (VoskAPI:ConfigureV2():vosk/model.cc:175) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ConfigureV2():vosk/model.cc:178) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0458219 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:233) Loading HCLG from model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:252) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:260) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:268) Loading CARPA model from model/rescore/G.carpa
Segmentation fault (core dumped)

**Comment by nshmyrev** [comment]
Upload your model and give here a link

**Comment by sharma2ananya** [comment]
model file is too big to upload can we try any other way.

**Comment by nshmyrev** [comment]
Same as #121
