### ISSUE TITLE
speech recognization problem while making a call on speakerphone

### ISSUE THREAD

**Issue by allanwxm** [alphacep/vosk-api#1205]
I'm using vosk freeswitch plugin to do speech recognization, and playAndGetDigits function to play an audio to user while doing speech recognization. There is a problem that while user is using speakerphone to make the call and is keeping quiet, the audio played will be recoginized. How can I omit the audio played and only detect the user speaking? Thanks!

**Comment by nshmyrev** [comment]
It depends on the model a lot. Recent models should ignore music.

**Comment by allanwxm** [comment]
> It depends on the model a lot. Recent models should ignore music.

Thank you for your reply! The audio we are using does not play a music , but a sentence speaked by a tts model, like 'Please say what you want to query'. If the speakerphone is used to make the call and user keeps quiet, the recognization result will be 'Please say what you want to query'.

**Comment by nshmyrev** [comment]
Thats kind of expected. AEC algorithm should probably deal with recorded playback.

**Comment by allanwxm** [comment]
> Thats kind of expected. AEC algorithm should probably deal with recorded playback.

Thanks, that helps a lot.
