### ISSUE TITLE
Native library for iOS

### ISSUE THREAD

**Issue by Flocksserver** [alphacep/vosk-api#1207]
Hi,
I would like to use the vosk lib for iOS. Is it possible to just use the existing build scripts? The android buildscript for example?  Does that fit for iOS? What are the parameters I would need to use?

```
          BLAS_ARCH=
          HOST=
          AR=
          RANLIB=
          CC=
          CXX=
          ARCHFLAGS=
```
Thanks for any hints to get the native lib :)

**Comment by nshmyrev** [comment]
To get the native build you need to mail contact@alphacephei.com and describe the project you are doing. Same as https://github.com/alphacep/vosk-api/issues/45

**Comment by Flocksserver** [comment]
Ok, my approach was to compile this myself. That is a bit more "sustainable". Not just asking for the lib. Because of this I opened the issue and have not written the mail. But well, then I will send a mail :)
