### ISSUE TITLE
German model "vosk-model-de-tuda-0.6-900k" does not work

### ISSUE THREAD

**Issue by ralf3u** [alphacep/vosk-api#1208]
English works.
French works with the model vosk-model-fr-0.22.
German works with the model vosk-model-de-0.21.

But German does not work with the model vosk-model-de-tuda-0.6-900k, what I got from https://alphacephei.com/vosk/models.
This is the command:
```
vosk-transcriber -m ~/Downloads/vosk-model-de-tuda-0.6-900k -i hello4.wav -o test1.1-de.txt
```

And this is the result:
```
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /home/t/Downloads/vosk-model-de-tuda-0.6-900k/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from /home/t/Downloads/vosk-model-de-tuda-0.6-900k/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading words from /home/t/Downloads/vosk-model-de-tuda-0.6-900k/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo /home/t/Downloads/vosk-model-de-tuda-0.6-900k/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:310) Loading subtract G.fst model from /home/t/Downloads/vosk-model-de-tuda-0.6-900k/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:312) Loading CARPA model from /home/t/Downloads/vosk-model-de-tuda-0.6-900k/rescore/G.carpa
LOG (VoskAPI:ReadDataFiles():model.cc:318) Loading RNNLM model from /home/t/Downloads/vosk-model-de-tuda-0.6-900k/rnnlm/final.raw
Killed
```

**Comment by nshmyrev** [comment]
It goes out of memory and get killed by kernel. You probably need 16 Gb to run it.

**Comment by ralf3u** [comment]
>It goes out of memory and get killed by kernel. You probably need 16 Gb to run it.

For an audio-file that is only 2 seconds long?

**Comment by nshmyrev** [comment]
Memory usage doesn't depend on the file length, the model is big by itself.

**Comment by ralf3u** [comment]
>Memory usage doesn't depend on the file length, the model is big by itself.

How much memory you use?

**Comment by nshmyrev** [comment]
We usually use 128Gb servers

**Comment by ralf3u** [comment]
I use 8GB.

>We usually use 128Gb servers

OK! And how much should a normal user use?

**Comment by ralf3u** [comment]
>It goes out of memory and get killed by kernel. You probably need 16 Gb to run it.

You are right. I can see it in the process manager. In the moment where the swap is full, the process get killed. My swap is 500 MB by default. So I will increase the swap in the next days to see if that has an impact.

**Comment by nshmyrev** [comment]
Swap will not help. You can remove rnnlm folder from the model to make it more lightweight.

**Comment by ralf3u** [comment]
>You can remove rnnlm folder from the model to make it more lightweight.

True! Thank you so much for your help. And the model respects capital letters!!!
What is the disadvantage when removing rnnlm?

**Comment by nshmyrev** [comment]
Couple percent less accurate recognition

**Comment by ralf3u** [comment]
>Swap will not help.

I can not confirm. I added again the folder `rnnlm` in the model, and I closed many windows. And then 8 GB RAM with 11 GB swap worked for me. I can see in the Process Manager the amount of RAM used, and how good it is to have a big swap for that work.

**Comment by CactusJack1393** [comment]
Hi! Please tell me, when I load the model, I get the following error. I have 16GB of RAM, or does this model require 16GB of free RAM space? Thank you for your help! When I get this error, my RAM is 60% full 

LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from C:/Models/vosk-model-de-tuda-0.6-900k/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from C:/Models/vosk-model-de-tuda-0.6-900k/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:297) Loading words from C:/Models/vosk-model-de-tuda-0.6-900k/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo C:/Models/vosk-model-de-tuda-0.6-900k/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:315) Loading subtract G.fst model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.carpa
ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.
Traceback (most recent call last):
  File "C:\Speech\Server.py", line 62, in <module>
    vosk_model = Model(model_path)
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\vosk\__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

**Comment by CactusJack1393** [comment]
Hi! Please tell me, when I load the model, I get the following error. I have 16GB of RAM, or does this model require 16GB of free RAM space?  When I get this error, my RAM is 60% full. Or is it related to another problem? Other models with a smaller size load and work correctly. Thanks 

LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from C:/Models/vosk-model-de-tuda-0.6-900k/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from C:/Models/vosk-model-de-tuda-0.6-900k/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:297) Loading words from C:/Models/vosk-model-de-tuda-0.6-900k/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo C:/Models/vosk-model-de-tuda-0.6-900k/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:315) Loading subtract G.fst model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.carpa
ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.
Traceback (most recent call last):
  File "C:\Speech\Server.py", line 62, in <module>
    vosk_model = Model(model_path)
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\vosk\__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/991
