### ISSUE TITLE
Librispeech model

### ISSUE THREAD

**Issue by sharma2ananya** [alphacep/vosk-api#121]
sir the files given here http://kaldi-asr.org/models/m13 are neither structured nor present according to the requirement of vosk-model as mentioned here https://github.com/alphacep/vosk-api/blob/master/doc/models.md, can you please provide working libri-speech model with vosk here.

**Comment by nshmyrev** [comment]
https://alphacephei.com/kaldi/models/vosk-model-en-us-librispeech-0.2.zip should work for you.

**Comment by sharma2ananya** [comment]
Thanks a lot, sir it worked, but the accuracy is not as per mentioned in the Kaldi documentation so is there any way to tune the parameters so that the predictions of the model become more accurate and is there any other model which is better than the above model in terms of predictions.

**Comment by PeterLocas** [comment]
> https://alphacephei.com/kaldi/models/vosk-model-en-us-librispeech-0.2.zip should work for you.

this model has chinese？
