### ISSUE TITLE
Punctuation Model does not work

### ISSUE THREAD

**Issue by ralf3u** [alphacep/vosk-api#1210]
I downloaded the English and the German punctuation model from
https://alphacephei.com/vosk/models#punctuation-models,
so vosk-recasepunc-en-0.22 and vosk-recasepunc-de-0.21. I extracted both.

This was the command in the terminal:
```
vosk-transcriber -m /home/t/Downloads/vosk-recasepunc-de-0.21 -i hello7.wav -o test7.1-de.txt
```
The result:
```
ERROR (VoskAPI:Model():model.cc:122) Folder '/home/t/Downloads/vosk-recasepunc-de-0.21' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Traceback (most recent call last):
  File "/home/t/.local/bin/vosk-transcriber", line 8, in <module>
    sys.exit(main())
  File "/home/t/.local/lib/python3.10/site-packages/vosk/transcriber/cli.py", line 71, in main
    transcriber = Transcriber(args)
  File "/home/t/.local/lib/python3.10/site-packages/vosk/transcriber/transcriber.py", line 21, in __init__
    self.model = Model(model_path=args.model, model_name=args.model_name, lang=args.lang)
  File "/home/t/.local/lib/python3.10/site-packages/vosk/__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model
```

What did I do wrong?
Thank you for an answer in advance.

**Comment by nshmyrev** [comment]
Punctuation models are not integrated into vosk-transcriber, you have to run them separately.

**Comment by nshmyrev** [comment]
Same issue as the previous one #1204. Please do not open duplicated issues.

**Comment by ralf3u** [comment]
>Punctuation models are not integrated into vosk-transcriber, you have to run them separately.

OK, so I should not take the command `vosk-transcriber` for the punctuation model.
But then, which command should I use? Could you please give me a command as example.

**Comment by ralf3u** [comment]
I downloaded `vosk-recasepunc-en-0.22` and unzipped the zip. In the folder there is a README. The content is:
```
1. Install pytorch and transformers:

    pip3 install transformers

2. Run python3 example.py de-test.txt

3. Compare with de-test.txt.orig
```
So, in the terminal I did: `pip3 install transformers`
Then in the terminal I navigated to the folder where the document `example.py` is located.
Then I did `python3 example.py de-test.txt`. The result is
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "/home/t/Downloads/vosk-recasepunc-en-0.22/example.py", line 4, in <module>
    from recasepunc import CasePuncPredictor
  File "/home/t/Downloads/vosk-recasepunc-en-0.22/recasepunc.py", line 7, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

What did I do wrong?
Thank you for an answer in advance.

**Comment by nshmyrev** [comment]
It says you need to install torch

**Comment by ralf3u** [comment]
I couldn't find a simple manual to install torch on Lubuntu 22.04.

**Comment by nshmyrev** [comment]
pip3 install torch

should work. See also https://pytorch.org/get-started/locally/

**Comment by ralf3u** [comment]
The German zip works fine (https://alphacephei.com/vosk/models/vosk-recasepunc-en-0.22.zip), There are those two documents:
de-test.txt
de-test.txt.orig

But in the English zip-version (https://alphacephei.com/vosk/models/vosk-recasepunc-en-0.22.zip), the README is not correct:
```
2. Run python3 example.py de-test.txt

3. Compare with de-test.txt.orig

```
I think de-test.txt is wrong and the document does not exist in the zip-file. Same for de-test.txt.orig.

Compared to the German version, two documents are missing:
en-test.txt
en-test.txt.orig

**Comment by ralf3u** [comment]
To my last comment: Should I open a new issue for that?

**Comment by nshmyrev** [comment]
It is enough to mention it here, thank you for the report!

**Comment by ralf3u** [comment]
When I run `python3 example.py de-test.txt`, then the result appears in the terminal. Is there a command to output the result in a text-document?

**Comment by nshmyrev** [comment]
You can use shell redirection

     python3 example.py de-test.txt > de-test-output.txt

**Comment by ralf3u** [comment]
I think it would be good to add in all README of the punctuation models something like this:
```
pip3 install torch
python3 example.py de-test.txt > de-test-output.txt
```
