### ISSUE TITLE
Librispeech model accuracy

### ISSUE THREAD

**Issue by sharma2ananya** [alphacep/vosk-api#122]
Thanks a lot, sir the link you provided worked, but the accuracy is not as per mentioned in the Kaldi documentation so is there any way to tune the parameters so that the predictions of the model become more accurate and is there any other model which is better than the librispeech model in terms of predictions.

**Comment by nshmyrev** [comment]
> but the accuracy is not as per mentioned 

What is the accuracy exactly?

> which is better than the librispeech model in terms of predictions.

our default model is better than librispeech (surprise)

**Comment by sharma2ananya** [comment]
can you please provide me the link to the default model

**Comment by nshmyrev** [comment]
http://alphacephei.com/kaldi/models/vosk-model-en-us-aspire-0.2.zip

**Comment by sharma2ananya** [comment]
sir do you have a model trained on Indian English data ?

**Comment by nshmyrev** [comment]
Yes, but it is commercial, not free.

**Comment by sharma2ananya** [comment]
What is the price for the model can you please provide the details.
