### ISSUE TITLE
Feature request: Add code examples for Speaker Identification in Python

### ISSUE THREAD

**Issue by inglesuniversal** [alphacep/vosk-api#1223]
I don't see any code samples provided on your site.

Help is needed to understand usage to allow a webpage to identify users by their voice as a way to identify them as users.

**Comment by nshmyrev** [comment]
We have issue https://github.com/alphacep/vosk-api/issues/405 about it. 

You are welcome to ask about details if you do not understand something.

**Comment by dfengpo** [comment]
#1689 405 didn't give any helpful answers at all
