### ISSUE TITLE
method GetNonSilenceFrames not in online-ivector-feature.h (neither master nor lookahead branches)

### ISSUE THREAD

**Issue by emiboy68** [alphacep/vosk-api#123]
Hello. I can't found the method GetNonSilenceFrames in your kaldi repository units.

Regards

**Comment by nshmyrev** [comment]
See here https://github.com/alphacep/kaldi/blob/b087e2b84e50577326d3864b907e0c343b9a080e/src/online2/online-ivector-feature.cc#L707

**Comment by nshmyrev** [comment]
Same as #118
