### ISSUE TITLE
C#. Attempted to read or write protected memory

### ISSUE THREAD

**Issue by Neogamezzz** [alphacep/vosk-api#1238]
C# console aplication:
VoskRecognizer rec = new VoskRecognizer(model, 16000.0f);

Error:
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

![Screenshot 2022-12-25 034025](https://user-images.githubusercontent.com/47366635/209455473-e6bda0ec-daf2-40e3-8b0b-7fa0c1af9e1f.jpg)

**Comment by nshmyrev** [comment]
You probably didn't download the model, same as #824
