### ISSUE TITLE
Difficulties Processing Batch Commands

### ISSUE THREAD

**Issue by ehobson** [alphacep/vosk-api#1240]
I've noticed that Vosk has problems with running batch commands. If there are more than two files being processed in one instance, Vosk will frequently only save the output for the last file in the sequence (or sometimes just the first and last files) and will not write any of the data for the remaining transcriptions to file, even though it can be seen in the terminal that transcription is occurring. Vosk will generate output files with the correct names but that contain no data. Why might Vosk struggle with batch commands?

**Comment by ehobson** [comment]
Just want to note that the behavior is inconsistent.

**Comment by nshmyrev** [comment]
What exact command are you running please?

**Comment by nshmyrev** [comment]
Let us know when you are able to provide more information
