### ISSUE TITLE
allow for multiple threads from vosk-translate

### ISSUE THREAD

**Issue by apple-corps** [alphacep/vosk-api#1252]
Hello,

This looks like a great piece of software. I'm looking forward to seeing a presentation in Chinese that I got from the net and doesn't caption. It's also awesome that we can use this software on our own devices!

I think the vosk-translate script should be modified to take a thread parameter to speed up translation. I tried the `tasks` parameter but it didn't look like it started threads or processes on my other CPUs. It looked like it was just using one or two cores. 

Then would it be possible to add this to the translate script?

**Comment by nshmyrev** [comment]
Same issue as #1117
