### ISSUE TITLE
Можно ли уменьшить время ожидания перехода из частичной строки в полную ?

### ISSUE THREAD

**Issue by svsdval** [alphacep/vosk-api#1256]
```
rec = vosk.KaldiRecognizer(model, args.samplerate)
while True:
    data = q.get()
    if rec.AcceptWaveform(data):
     rec.Result()
```
К примеру что бы не секунду ждала а пол секунды ? Или делать обёртку над rec.PartialResult() ?

**Comment by nshmyrev** [comment]
Можно отредактировать conf/model.conf, подробнее https://github.com/alphacep/vosk-api/issues/380
