### ISSUE TITLE
Human sound recognition

### ISSUE THREAD

**Issue by johngebbie** [alphacep/vosk-api#1257]
Hello,
I'd like to write a tool to let people play games by making sounds.  I'm inspired by [this project](https://github.com/chaosparrot/parrot.py) ([video](https://www.youtube.com/watch?v=aG2qiFiOOYo)).  It would use sounds like "sssssssss" and "fffffffff" so they can be discerned from each other straight away, and you can make the sounds for a longer or shorter duration.

I made quick test using vosk-model-small-en-us with partial results and limiting the vocab to ["ah", "oh", "ssh"].  To make it more responsive I made the AcceptWaveform audio chunks very small (512 bytes) and edited the lines of the  conf/model.conf to:

	--endpoint.rule2.min-trailing-silence=0.01
	--endpoint.rule3.min-trailing-silence=0.01
	--endpoint.rule4.min-trailing-silence=0.01

which made a big difference but there's still a bit of a delay in the results before and after making a sound.  Is anything else I could tweak?  This seems like it should be simpler than speech recognition with no need for word sequence probabilities and the like. I tried setting `--beam` and `--lattice-beam` to 0.01 among other things but didn't notice a difference.

**Comment by nshmyrev** [comment]
There are many factors that contribute to latency. Acoustic model has very long right context (about 0.3 seconds). If you want to detect things faster you need to train another one with smaller context.
