### ISSUE TITLE
phonemes for Spanish

### ISSUE THREAD

**Issue by ChenFangDart** [alphacep/vosk-api#1258]
Hello,

Is there anyway to get both phonemes and words at the same time for Spanish? I checked the two available Spanish models, neither of them have a phones.txt

Thanks and appreciate your help!

**Comment by nshmyrev** [comment]
No, we do not support phoneme outputs, sorry.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/687
