### ISSUE TITLE
Circular import error..

### ISSUE THREAD

**Issue by narem-sumanth** [alphacep/vosk-api#1260]
When I'm running the code, it is giving a circular import error. And when I fix that error it again giving an error that no method named "Model" in module "vosk"

**Comment by nshmyrev** [comment]
It is probably about wrong file name. You should not name your local files "vosk".

**Comment by nshmyrev** [comment]
And you need to provide more details if you need help (file and module layout, code sample and so on).

**Comment by Danger-3003** [comment]
This is the code where I've used the vosk module. I'm getting the circular import error whenever I'm running this code.

Anyone please help to fix that error. Thank you in Advance 😊.

import vosk
#from vosk import Model
#from vosk import KaldiRecognizer
import pyaudio
import pyttsx3
import datetime

model = vosk.Model("E:\vosk-model-small-en-us-0.15")
recognizer = vosk.KaldiRecognizer(model, 16000)

source = pyaudio.PyAudio()
engine = pyttsx3.init()
listening = False

def get_command():
    listening=True
    stream = source.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=8192)
    while listening:
        stream.start_stream()
        try:
            data = stream.read(4096)
            if recognizer.AcceptWaveform(data):
                result = recognizer.Result()
                response = result[14:-3]
                listening = False
                stream.close()
                return response
        except OSError:
            pass

def speak(text):
    engine.say(text)
    engine.runAndwait()

while True:
    print("Listening...")
    command=get_command()
    print(command)
    if command == "":
        pass
    elif "hello" in command:
        print("hello boss")
        speak("hello boss")
    elif "time" in command and "now" in command:
        time = datetime.datetime.now().strftime("%H %M")
        print(time)
        speak(time)

**Comment by narem-sumanth** [comment]
> It is probably about wrong file name. You should not name your local files "vosk".

Sir, this method actually worked. Thank you 😊.

**Comment by nshmyrev** [comment]
Ok, it is same as #273
