### ISSUE TITLE
How to clean partial

### ISSUE THREAD

**Issue by michoael** [alphacep/vosk-api#1263]
hello, how are you?

how can remove already get recognizer.getPartialResult()  with resume recognizing

**Comment by nshmyrev** [comment]
recognizer.reset() should work

**Comment by michoael** [comment]
More details
Example like : hi i am michael
If use string append in onPartialresult
Hi hi i hi i am hi i am michael

And when use rest in partial Results
Some words not get and after some seconds have crash

**Comment by nshmyrev** [comment]
You want to provide more information on what you are doing including code samples

**Comment by michoael** [comment]
i use vosk on android 
implements RecognitionListener 
and in onPartialResult

when use this code with setPartialWord(true) 

`JSONObject jsonObject = new JSONObject(s);
            if (!jsonObject.getString("partial").equals("")) {
                speechToText.setText(jsonObject.getString("partial"));
            }


            if (!jsonObject.isNull("partial_result")){
                JSONArray jsonArray = jsonObject.getJSONArray("partial_result");
                int jSize = jsonArray.length();
                for (int i = 0; i < jSize; i++){
                     if (i == jSize -1){
                        speechService.reset();

                    }
                }
                speechService.reset();
            }`

i have result after some words but i need speed more and some words not get like if set false
i think this because when set true get result on words so have some slowly 

i hope if you can put two options like   speechService.setWordTrust(false) for get like speechService.partialWord.set(false) 
and i think i should by set word true because reset();

if you can tell me anther  code with out setword true please tell me 
i don't need long words 

important note * when setPartialWord true have slow and not get some words even if use only this code in partialResult

`
         if (!jsonObject.getString("partial").equals("")) {
                speechToText.setText(jsonObject.getString("partial"));
            }
`

**Comment by nshmyrev** [comment]
Please format your previous message properly

**Comment by michoael** [comment]
`
try {
   JSONObject jsonObject = new JSONObject(s);
if (!jsonObject.getString("partial").equals("")) {
speechToText.setText(jsonObject.getString("partial"));
}
        if (!jsonObject.isNull("partial_result")){
            JSONArray jsonArray = jsonObject.getJSONArray("partial_result");
            int jSize = jsonArray.length();
            for (int i = 0; i < jSize; i++){
                 if (i == jSize -1){
                    speechService.reset();

                }
            }
            speechService.reset();
        }


        } catch (JSONException e) {
            e.printStackTrace();
        }
`

**Comment by nshmyrev** [comment]
Please read here about triple ticks:

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by michoael** [comment]
I don't know why i can't edit
But i want say when setWordPartial true have a slow and some words not get
And if you can do setSentence

**Comment by michoael** [comment]
I research in old issues here and i found same my say
https://github.com/alphacep/vosk-api/issues/1224

When use setPartialWord true get very bad results
For that i say make more code setTrustWord false

Becouse get results speed and right with set reset after listening only some words not after partial end

Try get partial resulte with setwordpartial true
And try again with false you can show different easy with same model files and same code only change between true and false

**Comment by michoael** [comment]
Thanks
