### ISSUE TITLE
keyword spotting using vosk-api

### ISSUE THREAD

**Issue by summer1704** [alphacep/vosk-api#1264]
I am planning  to detect single keyword with a  good accuracy in any sentence.
For example while someone is speaking, if they say the keyword "help" at any given time, it triggers an action. Is there any way that I can approach this problem using vosk-api

**Comment by nshmyrev** [comment]
Sure, if you see a word "help" in recognition results you act accordingly. Thats it!

**Comment by nshmyrev** [comment]
Same as #107

**Comment by summer1704** [comment]
Can I use this model to trigger an action immediately after the keyword has uttered without having to wait for the entire speech to get transcribed and then do the trigger action.

**Comment by nshmyrev** [comment]
Sure, analyze partial results
