### ISSUE TITLE
Android - API - Accuracies

### ISSUE THREAD

**Issue by CarlaSoffia** [alphacep/vosk-api#1266]
Hello, 

I would like to compreend if it's possible to get the accuracy of the models predictions in Android.

Thank you!

**Comment by nshmyrev** [comment]
Sure, you record a test set, run the recognition and then compute WER with a tool like texterrors.

**Comment by CarlaSoffia** [comment]
Ok, I will try that!
Thank you!

**Comment by nshmyrev** [comment]
Sure, let us know if you need any help
