### ISSUE TITLE
Custom dictionary - how-to?

### ISSUE THREAD

**Issue by dhamya** [alphacep/vosk-api#1271]
I was looking for ways to use a custom dictionary - a tiny one of no more than 10 words. Are there any "Step by step" instructions available for, what amounts to, essentially replacing the default dictionary with my custom words directory.

I'm building an app that can understand only a handful of words/commands, any pointers will be appreciated. Also, if there's a better forum to ask such questions, do let me know.

**Comment by dhamya** [comment]
For now, I'm taking route of sending in grammar at the time or recognizer creation ...

```
 List<String> vocab = new ArrayList<String>();
vocab.add("word1 word2 word3 word4");
vocab.add("[unk]");
String json = new Gson().toJson(vocab);
Recognizer rec = new Recognizer(result, 16000.0f, json);
```

Let me know if this makes sense.

**Comment by nshmyrev** [comment]
It is ok if you want to recognize only fixed words. You can also recompile LM to add new words

**Comment by dhamya** [comment]
Thanks @nshmyrev - yes, I'm building an assistant with very limited word knowledge that responds to only handful of commands (for now, anyway :))

**Comment by omlins** [comment]
@dhamya : maybe serves your needs: https://github.com/omlins/JustSayIt.jl
