### ISSUE TITLE
test_microphone.py has OSError: [Errno -9981] Input overflowed on OSX

### ISSUE THREAD

**Issue by skabbit** [alphacep/vosk-api#128]
Trying to run python/example/test_microphone.py and got error:
```
Traceback (most recent call last):
  File "./test_microphone.py", line 20, in <module>
    data = stream.read(4000)
  File "/Users/me/venv/lib/python3.8/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed
```
My system is OSX Mojave, brewed python@3.8, vosk installed from pip, model is vosk-model-ru-0.10.zip

Found two solutions for that problem:
1) Place model initialization before audio stream initialization, as it takes much more time than a buffer is capable to contain:
```
model = Model("model")
rec = KaldiRecognizer(model, 16000)

p = pyaudio.PyAudio()
stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=8000)
stream.start_stream()
```
2) Add exception_on_overflow=False argument to stream.read(4000):
`    data = stream.read(4000, exception_on_overflow=False)
`

But the first is preferable, I suppose.

**Comment by nshmyrev** [comment]
Fxed, thank you!

**Comment by ojosedanilo** [comment]
Thank you very much! I was having the same error in my code but I managed to solve it using the second solution.

**Comment by LuggesMugges** [comment]
i want you to know that you are a hero

**Comment by LuggesMugges** [comment]
i want you to know that you are a hero
