### ISSUE TITLE
Vosk-transcriber.exe fails with vosk-model-de-tuda-0.6-900k

### ISSUE THREAD

**Issue by HWutte** [alphacep/vosk-api#1282]
Hi,

When I try to run Vosk-transcriber.exe using the big 4GB German model "vosk-model-de-tuda-0.6-900k" I always receive an error (see below). I tried to run on 2 different windows PC...always the same issue. 
All other models work fine on the same PCs. Any ideas?

Windows x64

C:\Users\hwutt\AppData\Local\Programs\Python\Python311\Scripts>vosk-transcriber.exe --model "C:\Temp\vosk-model-de-tuda-0.6-900k" --input "C:\Temp\d7a27652-fdb8-466d-adcf-1224fb5034b6.mp4" --output "C:\Temp\websocket_test16k.txt"
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from C:\Temp\vosk-model-de-tuda-0.6-900k/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from C:\Temp\vosk-model-de-tuda-0.6-900k/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:297) Loading words from C:\Temp\vosk-model-de-tuda-0.6-900k/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo C:\Temp\vosk-model-de-tuda-0.6-900k/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:315) Loading subtract G.fst model from C:\Temp\vosk-model-de-tuda-0.6-900k/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from C:\Temp\vosk-model-de-tuda-0.6-900k/rescore/G.carpa
ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\hwutt\AppData\Local\Programs\Python\Python311\Scripts\vosk-transcriber.exe\__main__.py", line 7, in <module>
  File "C:\Users\hwutt\AppData\Local\Programs\Python\Python311\Lib\site-packages\vosk\transcriber\cli.py", line 71, in main
    transcriber = Transcriber(args)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\hwutt\AppData\Local\Programs\Python\Python311\Lib\site-packages\vosk\transcriber\transcriber.py", line 21, in __init__
    self.model = Model(model_path=args.model, model_name=args.model_name, lang=args.lang)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hwutt\AppData\Local\Programs\Python\Python311\Lib\site-packages\vosk\__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

**Comment by nshmyrev** [comment]
Same as #991, Windows can't allocate enough memory. Simple use our model instead, it is more accurate.
