### ISSUE TITLE
Choose CPU core via API?

### ISSUE THREAD

**Issue by fquirin** [alphacep/vosk-api#1288]
I'm running some tests on Orange Pi 5 and noticed that Vosk is running on one of the efficiency cores. OPi5 has 8 cores (4 performance, 4 efficiency).
Its still faster than realtime 😄, so its ok for streaming audio use-cases, but for batch transcriptions it could be much faster.
Can we tweak the code somehow to select a performance core instead?

**Comment by nshmyrev** [comment]
Core layout is arranged by the OS, not software. If you run more heavy processing I suppose it should move the process to performance core.

**Comment by fquirin** [comment]
Thanks, I'll just look for a Linux tool instead :-)
