### ISSUE TITLE
Nodejs Vosk Error

### ISSUE THREAD

**Issue by Fyphen1223** [alphacep/vosk-api#1294]
When I copied the demo of microphone test javascript, it shows me an error which 
```
Error: spawn arecord ENOENT
```
I don't know how can I solve this. If some one can hyelp me, please help me.

Thanks,

**Comment by nshmyrev** [comment]
Install sox or use other microphone recording module instead of mic

**Comment by Fyphen1223** [comment]
Nah it didn't fix this issue, but when I re-install that, it had fixed. Thanks,
