### ISSUE TITLE
Cannot pip install vosk

### ISSUE THREAD

**Issue by xor2003** [alphacep/vosk-api#13]
Failed on both win and ubuntu.
Python is 3.6 and 3.7.
See attached logs.
[vosk_ubuntu.log](https://github.com/alphacep/vosk-api/files/4050478/vosk_ubuntu.log)
[vosk_win.log](https://github.com/alphacep/vosk-api/files/4050479/vosk_win.log)

**Comment by nshmyrev** [comment]
Hi

Ubuntu log says that python3 is older than 3.5, are you sure you have 3.6? Maybe you need to specify proper pip path then.

Windows is not yet supported, will be supported soon!

**Comment by xor2003** [comment]
I have both Pythons 2 and 3.

$ lsb_release -a
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
xor@xor-desktop:~$ uname -a
Linux xor-desktop 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)

$ pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

$ pip3 -v install vosk
Collecting vosk
  1 location(s) to search for versions of vosk:
  * https://pypi.python.org/simple/vosk/
  Getting page https://pypi.python.org/simple/vosk/
  Looking up "https://pypi.python.org/simple/vosk/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/vosk/" in the cache
  Current age based on date: 330
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 330
  Analyzing links from page https://pypi.org/simple/vosk/
...
  Skipping link https://files.pythonhosted.org/packages/5c/f5/e9cd1aa7cea7ea196cc4ddf3c2c34a9fe463a00d7ac75978f8093c8640d4/vosk-0.3-cp35-cp35m-manylinux2010_x86_64.whl#sha256=5bc1e981ba4704746e9850fb194d63f767ad4fcd861d8f3decb68a8eb0486815 (from https://pypi.org/simple/vosk/) (requires-python:>=3.5); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/6d/84/64f08ad906cc897362998b1ce7426d1d771eee6198edaf79a22f423f9806/vosk-0.3-cp36-cp36m-manylinux2010_x86_64.whl#sha256=e7b603b5945a89c9cf70c67091e5f6a20cec0045a6d8a85c1e89d0e5e49f918a (from https://pypi.org/simple/vosk/) (requires-python:>=3.5); it is not compatible with this Python

**Comment by nshmyrev** [comment]
I figured out manylinux packages are not supported with pip9, you need to upgrade to pip19.

You can install it with `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`, but make sure you removed the pip3 from distribution. Otherwise you'll meet this issue:

https://askubuntu.com/questions/1025793/running-pip3-importerror-cannot-import-name-main

**Comment by xor2003** [comment]
Thank you!
