### ISSUE TITLE
unable to run on aarch64 libgfortran.so.3 error/missing

### ISSUE THREAD

**Issue by varungujjar** [alphacep/vosk-api#130]
Hey Guyz.. 

I am trying to run this on my raspberry pi4 4gb 64 OS (aarch64) with python 3.7 however gets me the error for libgfortran.so.3 missing 

Traceback (most recent call last):
  File "test_microphone.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer
  File "/home/pi/dev/env/lib/python3.7/site-packages/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel, SetLogLevel
  File "/home/pi/dev/env/lib/python3.7/site-packages/vosk/vosk.py", line 13, in <module>
    from . import _vosk
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory

have tried sudo-apt get install  libgfortran3.   
get this following error
Package libgfortran3:armhf is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgfortran3:armhf' has no installation candidate

I tried to force install a stretch package libgfortran3 but still that didnt help.. 
kind of lost and could use a little help..

**Comment by nshmyrev** [comment]
What is the distribution you are trying? You can try Raspbian on RPi4, it should work.

**Comment by varungujjar** [comment]
@nshmyrev am using the new raspbian OS 64bit..

**Comment by nshmyrev** [comment]
The one that has beta status?

**Comment by varungujjar** [comment]
Yes.. no complains so far on the 64 bit beta OS :)  finally managed to make it work..:D
1)  compiled kaldi ( took me 5hours ) pi4 4GB
2)  compiled vosk 

and now all models are working tried with mic streaming and really close to real time

**Comment by nshmyrev** [comment]
Nice, congratulations! I was going to rebuild for libgfortran.so.5, it is just not supported on dockcross. I'll update this a bit later.

**Comment by varungujjar** [comment]
[aarch64_pi4_64bitos.zip](https://github.com/alphacep/vosk-api/files/4742166/aarch64_pi4_64bitos.zip)
sharing my vosk python compiled files.. incase it saves someones time :)

**Comment by mohgavin** [comment]
Hi, i also get libgfortran.so.3 missing error. Currently, running on ubuntu server 20.04 focal fossa

**Comment by nshmyrev** [comment]
Since 0.3.16 we do not depend on gfortran anymore, using clapack instead.
