### ISSUE TITLE
C# GPU inferencing

### ISSUE THREAD

**Issue by kitsim93** [alphacep/vosk-api#1305]
Hello.
I compiled Vosk 0.3.45 with Kaldi environment to use GPU in c#. All was good to make the object file and shared library file.
Once I put the new library to nuget folder and when I compile the new nuget package, I realized that csharp src file didn't have the batchModel,cs and batchRecognizer.cs.
As a result, when I call "GpuInit()", it looks okay because I can see the relevant log message and confirm via "nvidia-smi". But because of the lack of BatchModel and BatchRecognizer, it's not working at all. (all operation runs in CPU core).
Can you please add the BatchModel.cs and BatchRecognizer.cs in repository?
Thanks !!!

**Comment by nshmyrev** [comment]
Please add them yourself and submit a pull request. It is very simple, 20 lines of code.

**Comment by mason-acronode** [comment]
I created the PR.
c# supports GPU inference #1307

**Comment by nshmyrev** [comment]
Great thanks a lot!
