### ISSUE TITLE
how to get spk_sig

### ISSUE THREAD

**Issue by atticushawk** [alphacep/vosk-api#131]
how to get spk_sig(speaker fingerprint), for someone, to use in the speaker recognition program?

**Comment by nshmyrev** [comment]
Record a sample audio of 20 seconds, recognize with speaker model, it will give you a signature.

**Comment by atticushawk** [comment]
Thank you. Your work has been very helpful to me. Could you please specify the link of the same(where i can find the code which is used to give the signature)

**Comment by nshmyrev** [comment]
https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py
