### ISSUE TITLE
no v0.3.45 for pip on macos

### ISSUE THREAD

**Issue by hamidreza-ghader** [alphacep/vosk-api#1316]
Hi,

I get the following error when trying to install vosk 0.3.45 on my mac book pro:
`ERROR: Could not find a version that satisfies the requirement vosk==0.3.45 (from versions: 0.3.21, 0.3.29, 0.3.30, 0.3.31, 0.3.32, 0.3.38, 0.3.40, 0.3.41, 0.3.42, 0.3.43, 0.3.44)`
`ERROR: No matching distribution found for vosk==0.3.45`

My system information is:
`OS: Ventura 13.2.1`
`Chip: Apple M1 Pro`
`Python==3.11.2`
`pip3==23.0.1`

Is there a `0.3.45`  release for Mac?

Thanks

**Comment by nshmyrev** [comment]
No, we do not have access to hardware to build it right now

**Comment by nshmyrev** [comment]
Same as #681
