### ISSUE TITLE
How to use "vosk-model-spk-0.4"? It gives error

### ISSUE THREAD

**Issue by MehdiyevSoltan2004** [alphacep/vosk-api#1324]
Hi. I want to use the model "vosk-model-spk-0.4", but I keep getting this error:
ERROR (VoskAPI:Model():model.cc:122) Folder 'vosk-model-spk-0.4' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Exception: Failed to create a model.
Can anyone help?

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/405

See test_speaker.py
