### ISSUE TITLE
PAUSE THRESHOLD?

### ISSUE THREAD

**Issue by botbahlul** [alphacep/vosk-api#1329]
Is there any way to set/change vosk 'pause threshold' in python?

Ussualy vosk will produce very long rec.PartialResult() before it finally return a rec.Result() if it's a long talk.

I need to reduce the 'pause threshold' (if any) so the rec.PartialResult() is not to long

TIA

**Comment by nshmyrev** [comment]
You can change pause length in model in file model.conf. Same as https://github.com/alphacep/vosk-api/issues/380

**Comment by botbahlul** [comment]
no any "programmatically" way to change it globally for dynamic selected language?

**Comment by nshmyrev** [comment]
No, we do not have API for that although such API is possible and would be nice to hav
