### ISSUE TITLE
【中文模型微调】How to finetune chinses mdel? Has anyone tried it?

### ISSUE THREAD

**Issue by F5Psyche** [alphacep/vosk-api#1333]
I am a newcomer in the field of speech recognition, I want to finetune the chinese model 'vosk-model-small-cn-0.22.zip'. 
Let the model recognize some common dialects, but there is too little information on the Internet to find useful information, please give pointers. cheers

我是语音识别领域的新人，我想微调中文模型“vosk-model-small-cn-0.22.zip”。
让模型识别一些常见的方言，但是网上资料太少，找不到有效的代码资料，请指点。

**Comment by nshmyrev** [comment]
Same as #185, we have scripts for finetuning but we didn't release them yet
