### ISSUE TITLE
Adding new words to the Persian model

### ISSUE THREAD

**Issue by imanshaameli** [alphacep/vosk-api#1338]
Hello
I want to train new words in Persian model, but I couldn't find the steps!
How can I re-train the model with my own words!?
What should my dataset look like and what should be changed?
Thankful

**Comment by svenha** [comment]
You will need an "update package", see https://alphacephei.com/vosk/lm#update-process

You might need to ask for one because your language is not listed there?

**Comment by nshmyrev** [comment]
Same as #1687
