### ISSUE TITLE
Troubles compiling csharp on MacOSX

### ISSUE THREAD

**Issue by Engeor** [alphacep/vosk-api#134]
When I try to create wrapper on OS X Catalina I get this error.
`clang: cannot specify -o when generating multiple output files`
I think that makefile doesn't count with clang as possible compiler. I fixed it by removing all .h files as they are not necessary as they doesn't produce any files.
_Also I think OpenBLAS is in extras so makefile should refer to it._

**Comment by nshmyrev** [comment]
> clang: cannot specify -o when generating multiple output files

Not sure what this is about, please provide full log.

> Also I think OpenBLAS is in extras so makefile should refer to it.

On osx kaldi uses accelerate framework with -framework Accelerate, not openblas. You can check python setup.py for details.

**Comment by Engeor** [comment]
Just to be sure, I am referring to vosk-api/csharp makefile.

> Not sure what this is about, please provide full log.

I am afraid that this is the only what 'make' says about the error.

> On osx kaldi uses accelerate framework with -framework Accelerate, not openblas.

I have read it, however, openblas.a is still present in makefile.

**Comment by nshmyrev** [comment]
> I have read it, however, openblas.a is still present in makefile.

So you need to change it if you want to compile on osx.

**Comment by Engeor** [comment]
Yes :-) 
1) Point is to make this makefile universal (or with variants)
2) Even if I am on Windows, openblas.a looks misplaced... or do I miss something?

**Comment by nshmyrev** [comment]
Ok, thats not a highest priority for us to support windows yet. We'd better focus on accuracy. I'll let you know when fixed.

**Comment by Engeor** [comment]
I actually did manage run csharp test.exe on mac os x and it worked! I have just wanted to let you know. But I understand. No problem :-)

**Comment by nshmyrev** [comment]
> I actually did manage run csharp test.exe on mac os x and it worked! I have just wanted to let you know. But I understand. No problem :-)

Cool, let me know if you have further questions!

**Comment by nshmyrev** [comment]
This seems to be fixed now.
