### ISSUE TITLE
Automatic .srt file

### ISSUE THREAD

**Issue by nahtan-dev** [alphacep/vosk-api#1347]
Hello, is it possible in Python to use vosk-api to make automatic subtitles (.srt file) using a audio (.wav) file like in Subtitle Edit app? If yes, how? Thanks for your answer

**Comment by nshmyrev** [comment]
Sure, see example here:

https://github.com/alphacep/vosk-api/blob/master/python/example/test_srt.py

**Comment by nahtan-dev** [comment]
> Sure, see example here:
> 
> https://github.com/alphacep/vosk-api/blob/master/python/example/test_srt.py

Thanks for your answer! I saw this example, however I don't exactly get it. 

Where do I put the name of my audio file in order that it creates subtitles? 

Why do I get `list index out of range` error with `sys.argv[1],`?

Also, why does Model(lang="fr") uses small model instead of the big one?

Sorry for all these questions, hoping you can help me

**Comment by nshmyrev** [comment]
>Where do I put the name of my audio file in order that it creates subtitles?

You can use the name of the file instead of sys.argv[1]

> Why do I get list index out of range error with sys.argv[1],?

Because you do not provide command line argument

> Also, why does Model(lang="fr") uses small model instead of the big one?

You have to specify model name instead `Model(model_name="vosk-model-fr-0.22")`

**Comment by nahtan-dev** [comment]
Thanks a lot it works! Last question, how to save as .srt file instead of print it?

**Comment by nshmyrev** [comment]
Something like 

```
with open("file.srt", "w") as fh:
     fh.write(rec.SrtResult(stream))

```

**Comment by nahtan-dev** [comment]
Thanks!!! Is there an option to save with an encoding utf-8 without BOM?

**Comment by nshmyrev** [comment]
I suppose

```
with open("file.srt", "w", encoding='utf-8') as fh:
     fh.write(rec.SrtResult(stream))
```

**Comment by nahtan-dev** [comment]
> I suppose
> 
> ```
> with open("file.srt", "w", encoding='utf-8') as fh:
>      fh.write(rec.SrtResult(stream))
> ```

Ah yes I'm dumb. Thank you for your help, have a nice evening!

**Comment by nshmyrev** [comment]
Ok, let us know how it goes
