### ISSUE TITLE
Code to build speaker identifier model

### ISSUE THREAD

**Issue by hungnvk54** [alphacep/vosk-api#135]
Hi @nshmyrev 
Please let me know where is the source from kaldi framework with you build the vosk-model-spk-0.3.
Can I build this model from scrash?

**Comment by nshmyrev** [comment]
> Can I build this model from scrash?

Yes, sure, check any kaldi SRE recipe like Voxceleb. Just make sure you train from shorter chunks.

**Comment by hungnvk54** [comment]
Thanks you so much.
Is vosk-model-spk-0.3 model was trained from Voxceleb. I want to train Voxceleb from kaldi framework. But if vosk-model-spk-0.3 was train from Voxceleb receip, I will not retrain it.

**Comment by nshmyrev** [comment]
> Is vosk-model-spk-0.3 model was trained from Voxceleb.

No, it is from http://kaldi-asr.org/models/m6 because

1) Chunk for xvectors are shorter
2) Its for 8khz, so works with telephony

**Comment by hungnvk54** [comment]
Hi @nshmyrev 
I found the pretrain-model for Voxcel from here https://kaldi-asr.org/models/m7.
Can i use this model with the vos-api?

**Comment by nshmyrev** [comment]
Yes, you can but you need to verify the accuracy.

**Comment by hungnvk54** [comment]
I have run the vosk-api with vosk-model-spk-0.3 and Voxcel. The cosine distance between different voice and same voice is very small. There are no big diffrent between them. Do you have any suggestion about it?

**Comment by nshmyrev** [comment]
Share the samples, I will take a look.

**Comment by hungnvk54** [comment]
Hi @nshmyrev 
This is [the link](https://drive.google.com/drive/folders/1G3URzqgFZjzxXqRHdZO2H5zVw5sVeOq7?usp=sharing) that contain the test data.
The first speaker have three audio file: 1_1.wav, 1_2.wav, 1_3.wav
The second speaker have three audio file: 2_1.wav, 2_2.wav, 2_3.wav

The output file is the embeding from vosk-model-spk-0.3.

Please take a look at it. Thanks you

**Comment by kascad** [comment]
Hi @hungnvk54, I got this data too in files with sample rate 16000Hz. You got incorrect data because your sample rate is higher than 8000Hz. Check your input audio file for sample rate 8000Hz or resample your file to 8000Hz.

**Comment by nshmyrev** [comment]
Now it should be fixed. Please test commit https://github.com/alphacep/vosk-api/commit/41035485dbcabfc9978876c7c36e1c83f64a9c4e and the model https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip

Please reopen if needed.
