### ISSUE TITLE
How to Recognize digits with this lib

### ISSUE THREAD

**Issue by altaf2892** [alphacep/vosk-api#1350]
**below is the initial implementation**

**Example: if i speak 123456 so lib gives me result := one two three four five six,  Example2: if i speak 2000(two thousands) so lib should give me result := 2000, Please help me to achieve my reqirement**
`    private fun setUpSpeechReorganization() {
       val rec = Recognizer(model, 16000.0f)
       // val rec = Recognizer(model, 16000f, "[\"one zero zero zero one\", " + "\"oh zero one two three four five six seven eight nine\", \"[unk]\"]")

        speechService = org.vosk.android.SpeechService(rec, 16000.0f)

    }
`
`   private fun initModel() {
        StorageService.unpack(this, "model-en-us", "model", { model: Model ->
            this.model = model

        }) { exception: IOException ->
            Log.e("Speech Models", "Failed to unpack the model" + exception.message)
        }
    }
`

**Comment by nshmyrev** [comment]
Same as #627
