### ISSUE TITLE
Segfault on Import Vosk

### ISSUE THREAD

**Issue by jakefoehner** [alphacep/vosk-api#1352]
Hi,

I am trying to use the test code 'test_words.py' when I run the command I get a sefault error.

When digging deeper this is the specific issue. 

OSError: cannot load library '/home/kxm/PycharmProjects/vosk-api/venv/lib/python3.6/site-packages/vosk/libvosk.so': /home/kxm/PycharmProjects/vosk-api/venv/lib/python3.6/site-packages/vosk/libvosk.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

This error happens when the line import vosk is run. 

I am using:

- Python 3.6
- a custom version of ubuntu 18.04
- and a 6-core NVIDIA Carmel ARM 64-bit

I had no issue install the correct python package for my build. 

Any advice is appreciated!

**Comment by nshmyrev** [comment]
You can recompile package from source, your libstdc++ is old version or incompatible.

**Comment by jakefoehner** [comment]
Ok so i followed this process: https://forums.linuxmint.com/viewtopic.php?t=178574

For recompiling libstdc++ and I am still getting the same error

**Comment by jakefoehner** [comment]
OSError: cannot load library '/usr/local/lib/python3.6/dist-packages/vosk-0.3.45-py3.6.egg/vosk/libvosk.so': /usr/local/lib/python3.6/dist-packages/vosk-0.3.45-py3.6.egg/vosk/libvosk.so: cannot open shared object file: No such file or directory

Actually I changed some other stuff and this is the error I am getting now.

**Comment by nshmyrev** [comment]
You probably didn't compile libvosk.so properly when you installed python package. The file must be really missing.

**Comment by jakefoehner** [comment]
You're right. I just added the file back and I am continuing to get the same error

**Comment by nshmyrev** [comment]
What is your libstdc++ version

**Comment by jakefoehner** [comment]
3.4

**Comment by nshmyrev** [comment]
3.4 what? You need 3.4.26 reports say.

**Comment by jakefoehner** [comment]
ahhh I missed that. I believe I have 3.4.25. Let me try upgrading and see if that fixes it. Thank you so much for your help!

**Comment by jakefoehner** [comment]
That worked!! thanks!

**Comment by nshmyrev** [comment]
Good, thanks for figuring that out

**Comment by zts2002** [comment]
> Ok so i followed this process: https://forums.linuxmint.com/viewtopic.php?t=178574好的，所以我遵循了这个过程： https://forums.linuxmint.com/viewtopic.php?t=178574
> 
> For recompiling libstdc++ and I am still getting the same error对于重新编译 libstdc++，我仍然遇到同样的错误

how you deal with this problem sir? i have the same wrong on jetson nano with the same report,i did not understand the answer of the link,may you show me how to deal with that with more particulars?

**Comment by nshmyrev** [comment]
> how you deal with this problem sir? i have the same wrong on jetson nano with the same report,i did not understand the answer of the link,may you show me how to deal with that with more particulars?

We have new Vosk coming out for Jetson nano. Contact me by email contact@alphacephei.com, I'll give you the link.

**Comment by mohamedabdelhadi** [comment]
I having the same issue
I am trying to run it on :
- NVIDIA Tegra X1 (nvgpu)/integrated.
- processor ARMv8.
- Ubuntu 18.04 LTS  64-bit.
- python 3.9.16.
