### ISSUE TITLE
how to disable warn logs?

### ISSUE THREAD

**Issue by munstr** [alphacep/vosk-api#1357]
Is there a function similar to SetLogLevel to disable logs with output "[WARN] Overflow - reader is not reading fast enough." How to disable such logs?

**Comment by nshmyrev** [comment]
Those are from portaudio, not from vosk, you have to ask there.

In general you need more lightweight model as this warning means accuracy suffers a lot.

**Comment by nshmyrev** [comment]
Like I wrote, you need to use sounddevice, not pyaudio

**Comment by munstr** [comment]
Thanks
