### ISSUE TITLE
Speech to text in Subtitle Edit 3.6.6.0

### ISSUE THREAD

**Issue by Hermit6202** [alphacep/vosk-api#1359]
An application error occurred in Subtitle Edit 3.6.6.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Die Datei "C:\Users\User\AppData\Local\Temp\2d996be3-a640-41c3-a28d-03865e191b30.wav" konnte nicht gefunden werden.

Stack Trace:
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileInfo.get_Length()
   bei Nikse.SubtitleEdit.Forms.AudioToText.TranscribeViaVosk(String waveFileName, String modelFileName)
   bei Nikse.SubtitleEdit.Forms.AudioToText.ButtonGenerate_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by nshmyrev** [comment]
You'd better report this issue to subtitleedit, it is not really related to Vosk. Message says file not found.
