### ISSUE TITLE
ERROR: FstHeader::Read: Bad FST header: Gr.fst

### ISSUE THREAD

**Issue by AllisonHanHY** [alphacep/vosk-api#136]
按照https://alphacephei.com/vosk/adaptation.html里写的build一个新的grammar，但是运行fstsymbols的时候报错，错误信息是ERROR: FstHeader::Read: Bad FST header: Gr.fst
PS：微信群二维码过期了，求入群

**Comment by nshmyrev** [comment]
> 按照https://alphacephei.com/vosk/adaptation.html里写的build一个新的grammar，但是运行fstsymbols的时候报错，错误信息是ERROR: FstHeader::Read: Bad FST header: Gr.fst

您需要正确设置LD_LIBRARY_PATH并使用grm编译openfst
> PS：微信群二维码过期了，求入群

我已经更新了，请再试一次

**Comment by AllisonHanHY** [comment]
用grm编译openfst是https://alphacephei.com/vosk/adaptation.html这个ppl之外的步骤么

**Comment by nshmyrev** [comment]
它应该已经包括在内。 只需检查ngram-fsts.so之类的文件

您很可能只需要正确设置LD_LIBRARY_PATH

**Comment by AllisonHanHY** [comment]
好的，谢谢。另外，text.txt文件有什么格式要求么？目前我的text文件格式如下，就是一句话一行，也就是一个utterance一行
sheep in a leap told on the road
go to in a boat here at the fair
owl on the prowl pig in a wig

**Comment by nshmyrev** [comment]
没有任何要求。 这个看起来不错。

**Comment by AllisonHanHY** [comment]
十分感谢！

**Comment by zyb8543d** [comment]
@nshmyrev 我用kaldi官方的命令生成了Gr.fst,解码结果完全牛头不对马嘴：
`gunzip -c data/local/lm_new/v1/3gram-mincount/lm_unpruned.gz | ngramread --OOV_symbol=`cat data/lang/oov.txt` --symbols=exp/chain/tdnn_1000hr_all_sp/graph_lookahead/words.txt --ARPA | \
    fstarcsort --sort_type=ilabel | \
      fstconvert --fst_type=ngram > exp/chain/tdnn_1000hr_all_sp/graph_lookahead/Gr.fst.$$`

请问text.txt是适应了所有格式吗
```
itt1 sheep in a leap told on the road
itt2 go to in a boat here at the fair
itt3 owl on the prowl pig in a wig
```
这样的格式也是可以的吗？
