### ISSUE TITLE
当我在解析中文语音时候，解析得到的是词语，而不是字

### ISSUE THREAD

**Issue by PengChaoJay** [alphacep/vosk-api#1360]
我调用vosk_recognizer_set_words(VoskRecognizer *recognizer, int words);，word设置的是1，但是返回得到的数据是词语，是什么原因呀，是因为directionary的使用错误吗

**Comment by svenha** [comment]
Please add more context and describe your issue in English.

**Comment by PengChaoJay** [comment]
When I parse Chinese speech, I get words, not word，I want to get 
I call vosk_recognizer_set_words(VoskRecognizer *recognizer, int words); , words set to 1, but the returned data is a word, what is the reason, is it because of the wrong use of directionary?

**Comment by SaintE419** [comment]
> 我调用vosk_recognizer_set_words(VoskRecognizer *recognizer, int words);，word设置的是1，但是返回得到的数据是词语，是什么原因呀，是因为directionary的使用错误吗

我遇到的问题有点类似，请问解决了吗
