### ISSUE TITLE
Example running Vosk in AWS Lambda

### ISSUE THREAD

**Issue by evbo** [alphacep/vosk-api#1363]
Only when trying to build for compatibility mode (for amazon linux 2 Arm64) do I get this error:
```shell
python3 -m venv ./venv
./venv/bin/pip3 install --upgrade pip
./venv/bin/pip3 install \
    --platform manylinux2014_aarch64 \
    --target="./venv/lib/python3.10/site-packages" \
    --implementation cp \
    --python 3.10 \
    --only-binary=:all: \
    --upgrade \
    srt vosk
```

> Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-23.1.2
ERROR: Could not find a version that satisfies the requirement srt (from versions: none)
ERROR: No matching distribution found for srt

Is there anyway to build properly for AWS Lambda? Any examples? For example, if I only keep the `--upgrade` argument in pip `libatomic.so.1` appears to be missing when running in AWS Lambda, just as reported here for Amazon Linux 2:
https://github.com/shaka-project/shaka-packager/issues/965

**Comment by nshmyrev** [comment]
You can install libatomic yourself. As for srt, you need to enable build from source, it will build srt module properly.

**Comment by evbo** [comment]
@nshmyrev thank you, after considering the options, it seems container runtime is the cleanest way to install libatomic. So that is no longer my issue, but I am now finally realizing that `vosk` requires GLIBC >= 2.27 but the aws Lambda/Python images specifically only support GLIBC 2.26.

The only option is to build a custom image, e.g. using `Ubuntu`, `Debian` ("bullseye"), or some such Linux image that supports newer versions of GLIBC. This also has the added benefit of enabling python 3.11, which has many performance improvements.

I'm not sure if it's possible to support running vosk on 2.26 for the benefit of running on Amazon Linux 2? Would that break too many dependencies or cause significant performance? It may be a while till Amazon supports 2.27, and running serverless is a pretty big opportunity for vosk. 

If supporting GLIBC for backwards compatibility with Amazon Linux isn't desirable, using a custom image isn't too big of a deal so this could probably be closed
