### ISSUE TITLE
Issue with 'KaldiRecognizer' constructor in Vosk library

### ISSUE THREAD

**Issue by Snowmnason** [alphacep/vosk-api#1368]
I'm currently working on integrating the Vosk speech recognition library into my Node.js project. However, I'm encountering an issue with the KaldiRecognizer constructor. Whenever I try to instantiate a KaldiRecognizer object, I receive a "TypeError:  KaldiRecognizer is not a constructor" error.

I have installed the vosk package using npm and made sure the package is up to date. I've also checked the import statements and ensured that the necessary dependencies are installed. However, the error persists.

Here's a most simplified version of my code:
```
const { Model, KaldiRecognizer } = require('vosk');

const model = new Model('path/to/model');
const recognizer = new KaldiRecognizer(model, 16000); // Error occurs here

// Rest of the code...
```
or another attempt
```
const vosk = require('vosk');

const model = new vosk.Model('path/to/modelh');
const recognizer = vosk.KaldiRecognizer(model, 16000);

// Rest of the code...
```

Am I missing something or using the KaldiRecognizer constructor incorrectly? Any help or insights on resolving this issue would be greatly appreciated.

**Comment by nshmyrev** [comment]
It is just Recognizer, not KaldiRecognizer. You can find an example here:

https://github.com/alphacep/vosk-api/blob/master/nodejs/demo/test_simple.js
