### ISSUE TITLE
wechat group issue 微信群问题

### ISSUE THREAD

**Issue by Marcnuth** [alphacep/vosk-api#137]
“该群已开启进群验证，只可通过邀请进群”

**Comment by nshmyrev** [comment]
谢谢。 我们已经更新了网站消息。

> 我们有一个非常大的微信群，所以它仅受邀请。 发邮件给我们加入小组，并提供一些有关您自己的信息

**Comment by nshmyrev** [comment]
Let me know if you have further queries on this please.
