### ISSUE TITLE
Invalid HTTPS certificate - can't access Maven

### ISSUE THREAD

**Issue by luispinho** [alphacep/vosk-api#1373]
The HTTPS certificate appears to have expired yesterday, can't access the official website nor Maven. This is blocking our project from building since it can't fetch the dependency.

Screenshot with details:
<img width="749" alt="Screenshot 2023-05-29 at 12 22 04" src="https://github.com/alphacep/vosk-api/assets/11448049/fb933271-db1d-454e-ab9d-eaf1a3f48d09">

Can anyone who's in charge of the certificate take a look into this, please?
Thanks

**Comment by nshmyrev** [comment]
Should be fixed now, thank you!
