### ISSUE TITLE
 vosk: Increase accuracy

### ISSUE THREAD

**Issue by amina1403** [alphacep/vosk-api#1378]
What changes should we make in the module vosk code to make it more accurate in pre-recorded files?
What changes can be made on audio files?
I made my program, but I need to increase the accuracy of the conversion.

info:
I use the large conversion model.
language: farsi (persian)

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/1369, please don't ask the same question many times
