### ISSUE TITLE
Changing the following values ​​has an impact on the accuracy of the vosk module?

### ISSUE THREAD

**Issue by amina1403** [alphacep/vosk-api#1379]
Changing the following values ​​has an impact on the accuracy of the vosk module?

model.conf:
--min-active=200
--max-active=3000
--beam=10.0
--lattice-beam=2.0
--acoustic-scale=1.0
--frame-subsampling-factor=3
--endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10
--endpoint.rule2.min-trailing-silence=0.5
--endpoint.rule3.min-trailing-silence=1.0
--endpoint.rule4.min-trailing-silence=2.0

mfcc.conf:
--use-energy=false
--num-mel-bins=20
--num-ceps=20
--low-freq=20
--high-freq=7600

**Comment by nshmyrev** [comment]
Same as #1369, please don't ask the same question many times
