### ISSUE TITLE
Have any plans for Hindi language support?

### ISSUE THREAD

**Issue by azain47** [alphacep/vosk-api#138]

**Comment by nshmyrev** [comment]
We have models for Hindi (and few other languages of India too), we don't yet plan to distribute them.

**Comment by azain47** [comment]
When do you all plan to distribute it, may I ask?
Also, any way to make own models?

**Comment by nshmyrev** [comment]
> Also, any way to make own models?

It is documented here:

https://alphacephei.com/vosk/models.html#training-your-own-model

**Comment by nshmyrev** [comment]
We have released Hindi models recently. See https://alphacephei.com/vosk/models
