### ISSUE TITLE
 random_device could not be read

### ISSUE THREAD

**Issue by AntonSeredenkov** [alphacep/vosk-api#1380]
I tried to launch a docker container with the vosk library installed, but for some reason this error pops up.
![image](https://github.com/alphacep/vosk-api/assets/71722885/15285dea-1f66-4c38-b083-b11501e7d1bd)

**Comment by nshmyrev** [comment]
You need to have random device in a docker. The details on how to fix it depend on the host OS and hardware.

**Comment by AntonSeredenkov** [comment]
The host OS is windows, but the same problem occurs with my colleagues who have an ubuntu operating system. How to fix this problem in general?

**Comment by nshmyrev** [comment]
Are you only using vosk in python or are you using pytorch also?

**Comment by AntonSeredenkov** [comment]
I also use pytorch

**Comment by nshmyrev** [comment]
try to change order of imports - torch before vosk and other way too

**Comment by AntonSeredenkov** [comment]
Thanks, it worked!

**Comment by Caet-pip** [comment]
Could you provide any guidance on deploying it in Docker using python?

**Comment by AntonSeredenkov** [comment]
Well in requirements.txt the installation of "vosk" was added, and the installation of the model was added to the dockerfile using this command:

ENV RUVERSION 0.22
RUN wget -q http://alphacephei.com/kaldi/models/vosk-model-small-ru-${RUVERSION}.zip \
   && unzip vosk-model-small-ru-${RUVERSION}.zip \
   && rm -rf model/extra \
   && rm -rf vosk-model-small-ru-${RUVERSION}.zip
   
   
   But i think that's another question and doesn't fit to this issue
