### ISSUE TITLE
Guidance on deploying Vosk as an endpoint using Azure ML

### ISSUE THREAD

**Issue by Caet-pip** [alphacep/vosk-api#1382]
Hello!
I am trying to deploy Vosk in Azure ML for inference on telephony calls. Could you please guide me as I have been able to run it locally for inference using the microphone_text.py file but am finding it difficult to translate this to cloud. Any guidance on how to proceed with pickling and creating endpoint will be helpful thanks!

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-server/issues/225
