### ISSUE TITLE
Trouble with OpenBLAS threading

### ISSUE THREAD

**Issue by johngebbie** [alphacep/vosk-api#1385]
Hello, I'm sorry to nag again.

I'm trying to package vosk for Alpine Linux. My test currently segfaults because Alpine's openblas package isn't compiled with `USE_LOCKING=1 USE_THREAD=0`. The test works if I set the environment variable `OPENBLAS_NUM_THREADS=1` but I'm not sure how to do it properly from vosk/kaldi (which I can apply patches to) so it can be packaged.

I see openblas has an `openblas_set_num_threads` function. Do you know where I could add `openblas_set_num_threads(1)` to vosk/kaldi to make it work?

**Comment by johngebbie** [comment]
I've asked on kaldi-help: https://groups.google.com/g/kaldi-help/c/tcaxZiVZly8
Sorry asking here first, I thought messaging kaldi-help required a google account.

**Comment by nshmyrev** [comment]
Hey, sorry, I missed this one. You can add here:

https://github.com/alphacep/vosk-api/blob/master/src/model.cc#L117

there is already a statement for MKL

**Comment by johngebbie** [comment]
Oh that's great! I don't know how I missed that, apparently my greping isn't what it used to be. Thank you!
