### ISSUE TITLE
Trying to Pickle model gives error

### ISSUE THREAD

**Issue by mlcatinit** [alphacep/vosk-api#1387]
When trying to use:

model = Model(lang="en-us")
filename= 'vosk.pkl'
joblib.dump(model,open(filename, 'wb'))

getting this error:
TypeError: cannot pickle '_cffi_backend._CDataBase' object

I need to deploy english model as an endpoint in azure and am using pickle to get a pkl file for registering as a model

**Comment by nshmyrev** [comment]
It is not going to work this way, you can not store the model in pickle file since it is C object, you will have to write custom code. It is easier to load model from a folder instead

**Comment by mlcatinit** [comment]
Thank you
