### ISSUE TITLE
Wideband server model from tuda-de 

### ISSUE THREAD

**Issue by eqikkwkp25** [alphacep/vosk-api#139]
First of all, thank you for your work on opensource STT. 

It was quite easy to test models from https://alphacephei.com/kaldi/models/ which are partially listed here https://alphacephei.com/vosk/models.html but not the tuda-de one. As it says 'server model' some additional work has to be done i guess. 

Can I convert it somehow to directly use it within vosk / vosk-api without setting up a server? Any hints are welcome. Thank you.

**Comment by nshmyrev** [comment]
You just need to arrange files like this:

https://github.com/alphacep/vosk-server/blob/1066f92b91d922499eda0ab7943317696d283b81/docker/Dockerfile.kaldi-de#L5

**Comment by nshmyrev** [comment]
Feel free to reopen if you need further info

**Comment by nshmyrev** [comment]
Latest tuda model linked in #1093
