### ISSUE TITLE
Please add more languages 

### ISSUE THREAD

**Issue by michoael** [alphacep/vosk-api#1390]
You said more languages soon, but this before a lot time. Any new of this. Or you will don't it.
I hope answer to me, Thanks.

**Comment by nshmyrev** [comment]
Which language are you interested in?

**Comment by michoael** [comment]
a lot languages for android
Arabic, Korean, Tamil, Hungarian, and more languages.
I hope add all languages 😅
I think you know of new model from openai (whisper) have 98 languages all in one model and auto detect language i need like that but from vosk because vosk faster, real time, timestamp and i can use easy with android ( no important all in one model but i important add more languages)
I hope bear me, thanks.

**Comment by michoael** [comment]
Any answer please

**Comment by nshmyrev** [comment]
We try to create good models for languages we support, it takes time unfortunately. Korean and Arabic are our top priority.

**Comment by michoael** [comment]
Okay, thank you very much.
