### ISSUE TITLE
Add uppercase letters and dots in a .srt file

### ISSUE THREAD

**Issue by nahtan-dev** [alphacep/vosk-api#1393]
Hello,
The Windows app "Subtitles Edit" use vosk-api and it automatically adds a uppercase letter at the beginning of each sentence and a dot at the ending of each sentence in a SubRip file. 
I was wondering if it was possible to do the same, and how?

**Comment by nshmyrev** [comment]
We have punctuation models on models page, you can check them

https://alphacephei.com/vosk/models

In general there are many postprocessing packages which add caps and punctuation. We are working on integration, it is not there yet.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/152

**Comment by nahtan-dev** [comment]
Thanks for your answer! 
Do you think the english model will work with french?
Also I downloaded it and I don't exactly get how it works, can I use it aside "vosk-model-fr-0.22" model in a code like this one for a SubRip file: python/example/test_srt.py ?
