### ISSUE TITLE
Some thread parameter

### ISSUE THREAD

**Issue by Just-ne-Just** [alphacep/vosk-api#1395]
Hello! I want to use VOSK model on a pretty good CPU. I saw somewhere that I can pass some "thread num" parameter (maybe set some ENV variable etc) which will allow model to parallel computations in separate threads, but I can't find the exact example. Am I right or this is the only example how I can do that (https://github.com/alphacep/vosk-api/blob/master/python/test/transcribe_scp.py)?

P.s. I am quite new to this lib, so this question might be silly, sorry for that 

P.p.s. The goal in general is to make inference for one audio file faster

**Comment by nshmyrev** [comment]
> Am I right or this is the only example how I can do that (https://github.com/alphacep/vosk-api/blob/master/python/test/transcribe_scp.py)?

Yes, if you want to process many streams in parallel. Vosk can't parallelize single stream

**Comment by Just-ne-Just** [comment]
Thank you!
