### ISSUE TITLE
Exception: Failed to create a model

### ISSUE THREAD

**Issue by VitalyDyachkov** [alphacep/vosk-api#1401]
Greetings! There is a problem when creating a model. Processing the Russian language.
https://alphacephei.com/vosk/models/vosk-model-ru-0.22.zip

LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6

LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:297) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:315) Loading subtract G.fst model from model/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from model/rescore/G.carpa
LOG (VoskAPI:ReadDataFiles():model.cc:323) Loading RNNLM model from model/rnnlm/final.raw
Traceback (most recent call last):
  File "C:\Users\X\PycharmProjects\voice\main.py", line 18, in <module>
    model = Model("model")
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\vosk\__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

**Comment by nshmyrev** [comment]
You probably do not have enough memory, it needs 16gb

**Comment by nshmyrev** [comment]
and we have more accurate 0.42 already.

**Comment by VitalyDyachkov** [comment]
Yes, I have 12GB. I tried 0.42, yes it works.

**Comment by VitalyDyachkov** [comment]
Thank you!
