### ISSUE TITLE
Numbers in letters

### ISSUE THREAD

**Issue by nahtan-dev** [alphacep/vosk-api#1402]
Hi, is there a way to make numbers in numerals instead of letters?
For instance:
"24" : "twenty four" => "24"
"24" : "vingt quatre" => "24"

**Comment by nshmyrev** [comment]
https://github.com/allo-media/text2num

**Comment by nshmyrev** [comment]
Same as #627

**Comment by nahtan-dev** [comment]
Thanks for answering!

**Is there a way to edit the text before it is written on a subtitles file?**
Like my config is one word per line and if I edit the numbers of the subtitles file, it will do something like that:
_twenty => 20
four => 4_
Insted of:
_twenty four => 24_

**Comment by nshmyrev** [comment]
Sure, you need to write a simple code to call a library linked above.

**Comment by nahtan-dev** [comment]
Thanks again for answering!

What do you mean?
