### ISSUE TITLE
A/VoskAPI: Check():online-ivector-feature.cc:81) Assertion failed: (global_cmvn_stats.NumRows() == 2)

### ISSUE THREAD

**Issue by WeMakeBest** [alphacep/vosk-api#1410]
I am using Vosk Android library which was working great few days ago suddenly it stopped working and showing this errors in logs.
`A/VoskAPI: Check():online-ivector-feature.cc:81) Assertion failed: (global_cmvn_stats.NumRows() == 2)`

And this was logs when loading the library and model.
`I/VoskAPI: ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6`
`I/VoskAPI: ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5`

`I/VoskAPI: RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.`
`I/VoskAPI: RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.`
`I/VoskAPI: Collapse():nnet-utils.cc:1488) Added 1 components, removed 2`

`I/VoskAPI: CompileLooped():nnet-compile-looped.cc:345) Spent 0.0935929 seconds in looped compilation.`
`I/VoskAPI: ReadDataFiles():model.cc:248) Loading i-vector extractor from /storage/emulated/0/Android/data/me.resight.app/files/vosk-model-ar-0.22-linto-1.1.0/ivector/final.ie`

`I/VoskAPI: ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor`

`I/VoskAPI: ComputeDerivedVars():ivector-extractor.cc:204) Done.`
`I/VoskAPI: ReadDataFiles():model.cc:278) Loading HCLG from /storage/emulated/0/Android/data/me.resight.app/files/vosk-model-ar-0.22-linto-1.1.0/graph/HCLG.fst`
`I/VoskAPI: ReadDataFiles():model.cc:293) Loading words from /storage/emulated/0/Android/data/me.resight.app/files/vosk-model-ar-0.22-linto-1.1.0/graph/words.txt`
`I/VoskAPI: ReadDataFiles():model.cc:302) Loading winfo /storage/emulated/0/Android/data/me.resight.app/files/vosk-model-ar-0.22-linto-1.1.0/graph/phones/word_boundary.int`
`I/VoskAPI: ReadDataFiles():model.cc:309) Loading subtract G.fst model from /storage/emulated/0/Android/data/me.resight.app/files/vosk-model-ar-0.22-linto-1.1.0/rescore/G.fst`
`I/VoskAPI: ReadDataFiles():model.cc:311) Loading CARPA model from /storage/emulated/0/Android/data/me.resight.app/files/vosk-model-ar-0.22-linto-1.1.0/rescore/G.carpa`

Let me know what's wrong.

Thanks

**Comment by nshmyrev** [comment]
We didn't change anything, maybe something external changed data files on sdcard. Remove model files and load them again please.

**Comment by WeMakeBest** [comment]
I tried in multiple devices and even tried 2 models and removed everything again extracted the mode still the same

**Comment by nshmyrev** [comment]
What other model did you try beside vosk-model-ar-0.22-linto-1.1.0 ? What is the logcat for other model then?

**Comment by WeMakeBest** [comment]
English model. Logcat is same as ar model

**Comment by nshmyrev** [comment]
Logcat for different model must be different. Please provide an updated logcat.

**Comment by WeMakeBest** [comment]
` A/VoskAPI: Check():online-ivector-feature.cc:81) Assertion failed: (global_cmvn_stats.NumRows() == 2)`

Issue was the same on it just the file name changes

**Comment by nshmyrev** [comment]
Ok, share the contents of the folder /storage/emulated/0/Android/data/me.resight.app/files/vosk-model-ar-0.22-linto-1.1.0/ivector

**Comment by WeMakeBest** [comment]
![image](https://github.com/alphacep/vosk-api/assets/84631396/5356d8da-2793-45f1-a563-64ab13e77d30)

**Comment by nshmyrev** [comment]
Ok, please provide full logcat output as a file.

**Comment by WeMakeBest** [comment]
[vosk_errors_logcat.txt](https://github.com/alphacep/vosk-api/files/12013909/vosk_errors_logcat.txt)

**Comment by nshmyrev** [comment]
How about small English model, does it work?

**Comment by WeMakeBest** [comment]
No it doesn't work

**Comment by nshmyrev** [comment]
And what about vosk-android-demo apk? does it work?

**Comment by WeMakeBest** [comment]
As I said it was working earlier but suddenly yesterday it stopped working I didn't even changed the code

**Comment by WeMakeBest** [comment]
Any updates?

**Comment by WeMakeBest** [comment]
`implementation 'net.java.dev.jna:jna:5.8.0@aar'`
`implementation group: 'com.alphacephei', name: 'vosk-android', version: '0.3.32'`

I am using above version

**Comment by WeMakeBest** [comment]
Update the library to latest version
