### ISSUE TITLE
Is there a way to train the data to get phonetic respelling for words? 

### ISSUE THREAD

**Issue by Deuos** [alphacep/vosk-api#1413]
For the word, "Composition" the phonetic respelling would be "kaam·puh·zi·shn", what would be a good approach to get to this point or something similar?

**Comment by damian-666** [comment]
this might help..
https://stackoverflow.com/questions/3495301/best-practice-for-specifying-pronunciation-for-android-tts-engine

i like radio protocol.  Nato coms are standard.    ships, military search rescue.. Kilo Alpha Alpha, Papa Zulu india Serra  Hotel n= for spelling or hot labels on UI completion.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/687
