### ISSUE TITLE
can't install library on C++

### ISSUE THREAD

**Issue by Lie2264** [alphacep/vosk-api#1420]
I tried to find some information on how to download Vosk in C++ but I couldn't find anything. I tried to download via NUGET following the instructions as in C# but I had a problem with JSON not wanting to be installed in C++. 

Please give me instructions how to download Vosk in C++ on Windows, preferably some video but at least explain it in text.

**Comment by nshmyrev** [comment]
You just download precompiled version and include it into your project

https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-win64-0.3.45.zip 

try it and let us know if you have any specific issue. Provide the details.
