### ISSUE TITLE
Wrong formatted json if locale has other decimal seperator

### ISSUE THREAD

**Issue by m-fuchs** [alphacep/vosk-api#1425]
Hello,

I am using the C library from Freepascal on a German system. When I compile my program with support for locale under linux, the return of vosk_recognizer_final_result is incorrect:

```
{
  "alternatives" : [{
      "confidence" : 535,251099,
      "text" : "dies ist der erste satz dies ist der zweite satz"
    }]
}
```

In the JSON here, the value of "confidence" is incorrectly encoded with a comma instead of a period.

There seems to be a problem with Vosk's JSON converter. It *always* has to be a period, no matter what decimal separator setting the system contains.

**Comment by nshmyrev** [comment]
Yes, we have this problem, same as #808
