### ISSUE TITLE
No examples of working with the voice identification model vosk-model-spk-0.4

### ISSUE THREAD

**Issue by virex-84** [alphacep/vosk-api#1429]
En:
I didn’t find an example of voice identification anywhere, so I made my own for android: https://github.com/virex-84/VoskIdentification
An example is the code: https://github.com/alphacep/vosk-api/blob/12f29a3415e4967e088ed09202bfb0007e5a1787/python/example/test_speaker.py#L53

Ru:
Нигде не нашел пример идентификации голоса, поэтому сделал свой для android: https://github.com/virex-84/VoskIdentification
Примером послужил код: https://github.com/alphacep/vosk-api/blob/12f29a3415e4967e088ed09202bfb0007e5a1787/python/example/test_speaker.py#L53

**Comment by nshmyrev** [comment]
Same as #405

Thank you for the demo!
