### ISSUE TITLE
Memory increased rapidly when run asr_server.py in docker

### ISSUE THREAD

**Issue by hungnvk54** [alphacep/vosk-api#143]
Hi @nshmyrev 
When i try running asr_server.py in docker, I got a problem. Memory increase rapidly. It increases 1.GB after decoding 5 minutes audio. Even if when the time is greater than 10 minute (at this time, feature_pile and decoder will be renew), the memory not decrease much.

But when I run the python/example/test.py, memory not increase much. Only 100-200MB for 60 minutes audio.

Eviroment:
kaldi: master branch 
vosk-api: master brach
python: 3.5.2 (i also happend on 3.6.9)
docker image: ubuntu 16.4 (it also happend on ubuntu 18.04)

**Comment by nshmyrev** [comment]
Do you rebuild docker image? Our default one is based on debian.

Might be related to pretty commonly reported https://github.com/alphacep/vosk-server/issues/44
which I can not yet reproduce.

I'm going to look soon.

**Comment by hungnvk54** [comment]
Yes. I rebuild image from Ubuntu 16.04 and 18.04. I also build the code from scratch.

**Comment by nshmyrev** [comment]
Please share your changes so I can reproduce

**Comment by hungnvk54** [comment]
No. I change nothing from your code. I only change the model change i have trained my self and add one more config option --add-pitch=true.

**Comment by hungnvk54** [comment]
@nshmyrev Please note that, with the same container, when i testing with file example/test_text.py, memory is ok. The different between asr_python.py and test_text.py is only the websockets. Do you thing the problem is websockets?

**Comment by hungnvk54** [comment]
Hi @nshmyrev 
When I replace the the following code
`response, stop = await loop.run_in_executor(pool, process_chunk, rec, message)`
by 
`response, stop =  process_chunk( rec, message)`

The memory seem not grow rapidly.

You may inspect from that

**Comment by nshmyrev** [comment]
What server are you running on? What hardware exactly?

**Comment by hungnvk54** [comment]
I'm running on my local server. 
- Hardware information
RAM: 64GB
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
- Software information
Docker version: 19.0.3
Image: ubuntu 16.04
- OS: Ubuntu Desktop 18.04.

**Comment by nshmyrev** [comment]
I can not reproduce this issue with my kaldi-en docker. How do you measure memory? What is the exact memory outputs? How to reproduce your memory growth? Can you reproduce it with our docker?

**Comment by hungnvk54** [comment]
>  How do you measure memory?

I use docker stats command do measure memory (sometimes, htop linux command is also used)

> What is the exact memory outputs?

Memory increase rapidly when decoding (from 700MB to 1.9GB) and it increase slower at this point. Event if finish decoding, memory not decrease.

>  Can you reproduce it with our docker?

Of course. When I keep the original code from asr_server.py, memory issue appear, 

`response, stop = await loop.run_in_executor(pool, process_chunk, rec, message)` (original)

`response, stop = process_chunk( rec, message)` (modified)

When i run modified asr_server.py, memory only around 700MB -> 820MB.

**Comment by nshmyrev** [comment]
Well, it is not really memory leak, just excessive use by many threads. I reduced thread count in https://github.com/alphacep/vosk-server/commit/14daebd236ea16f3ec2850c7b2978bf41b23db23, it should be better now. To further reduce one can have one thread executor with 1 worker by each stream, but I consider it a bit excessive. Let it stay as a pool.

**Comment by hungnvk54** [comment]
Well, The new code is now good. Thanks you so much.

By the way, When I compare the time it takes to decode audio between the vosk-api (via asr_server.py) and online2-tcp-nnet3-decode-faster in orignal kaldi github. I run two decoder on same hardware. The vosk-api is slower than online2-tcp-nnet3-decode-faster, it is approximate 1.5 time. I saw the code of kaldi_recognizer and online2-tcp-nnet3-decode-faster, there is no different much. Do you have any suggest to reduces decoding time when using vosk-api?

**Comment by nshmyrev** [comment]
> The vosk-api is slower than online2-tcp-nnet3-decode-faster, it is approximate 1.5 time. I

Are beams and math library (openblas) the same?

**Comment by hungnvk54** [comment]
> Are beams and math library (openblas) the same?

- Yeap. The beams is same and openblas is 0.3.5.

**Comment by nshmyrev** [comment]
vosk server does rescoring on top of results, but that shouldn't affect the speed much. I failed to reproduce this issue unfortunately, I tried with default aspire model and the tcp server time is 4m while vosk server time is 3m45s, so I can't reproduce your problem again. You'd better open a separate issue on this and provide a way to reproduce the problem with our default models.

**Comment by dpny518** [comment]
> No. I change nothing from your code. I only change the model change i have trained my self and add one more config option --add-pitch=true.

how did you get the docker working with pitch=true, when i try i get the error 

 ERROR (VoskAPI:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:46) Input feature dimension mismatch: got 40 but network expects 43
