### ISSUE TITLE
Termux no install ( android 11 arm )

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#1434]
Termux arm64 - install done.
Termux arm - no install.

![Screenshot_20230822-113124_Termux](https://github.com/alphacep/vosk-api/assets/142758388/4c1fde69-1c9b-46c2-ad50-c24048807bc8)

**Comment by nshmyrev** [comment]
Show supported platforms with 'pip3 debug -v'

**Comment by ghost** [comment]
pip version: pip 23.2.1 from /data/data/com.termux/files/usr/lib/python3.11/site-packages/pip (python 3.11)
sys.version: 3.11.4 (main, Jul  2 2023, 11:17:16) [Clang 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0
sys.executable: /data/data/com.termux/files/usr/bin/python3.11
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: utf-8
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: global
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.12.11
  colorama==0.4.6
  distlib==0.3.6
  distro==1.8.0
  msgpack==1.0.5
  packaging==21.3
  platformdirs==3.8.1
  pyparsing==3.1.0
  pyproject-hooks==1.0.0
  requests==2.31.0
  certifi==2023.05.07
  chardet==5.1.0
  idna==3.4
  urllib3==1.26.16
  rich==13.4.2 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.15.1
  typing_extensions==4.7.1 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==1.0.1
  setuptools==68.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.2.2 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.0.1
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 39
  cp311-cp311-linux_armv8l
  cp311-abi3-linux_armv8l
  cp311-none-linux_armv8l
  cp310-abi3-linux_armv8l
  cp39-abi3-linux_armv8l
  cp38-abi3-linux_armv8l
  cp37-abi3-linux_armv8l
  cp36-abi3-linux_armv8l
  cp35-abi3-linux_armv8l
  cp34-abi3-linux_armv8l
  cp33-abi3-linux_armv8l
  cp32-abi3-linux_armv8l
  py311-none-linux_armv8l
  py3-none-linux_armv8l
  py310-none-linux_armv8l
  py39-none-linux_armv8l
  py38-none-linux_armv8l
  py37-none-linux_armv8l
  py36-none-linux_armv8l
  py35-none-linux_armv8l
  py34-none-linux_armv8l
  py33-none-linux_armv8l
  py32-none-linux_armv8l
  py31-none-linux_armv8l
  py30-none-linux_armv8l
  cp311-none-any
  py311-none-any
  py3-none-any
  py310-none-any
  py39-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

**Comment by ghost** [comment]
I understand.
