### ISSUE TITLE
Transcription never works

### ISSUE THREAD

**Issue by es20490446e** [alphacep/vosk-api#1438]
---
### System

Manjaro Linux KDE minimal.

It happens with both Firefox and Chromium, both the internal and external webcam mics, any volume, and any distance from the mic.

In the system's sound settings the proper mic and volume are selected, and it displays as receiving audio properly. All applications, like OBS, are able to record the sound coming from the mics at good volume and clarity.

Both mics are stereo.

---
### On the web browser

If I go to:
https://alphacephei.com/en/

And click on:
Try it now

The speech transcription doesn't work.

But if I go to:
https://www.onlinemictest.com/

I can see my microphone working.

---
### On an emulator

If I install the emulator `simple64` along with `vosk-api`, I'm allowed to emulate the Voice Recognition Unit of the console.

But when I launch the game `Hey You Pikachu!`, the unit is detected but Pikachu never recognizes my voice.

---

**Comment by nshmyrev** [comment]
Web demo works only in Chrome, not in Chromium or Firefox

As for simple64, not sure what is going on there, there must be some messages if you start it from console.

**Comment by es20490446e** [comment]
Strange, because the demo worked on Firefox mobile.

And there was no message in the console.

I guess I shall ask `simple64` developers first.

**Comment by es20490446e** [comment]
https://github.com/simple64/simple64/issues/390
