### ISSUE TITLE
Why do we need Speech model for Speaker Identification?

### ISSUE THREAD

**Issue by omerasif-itu** [alphacep/vosk-api#144]
In `python/example/test_speaker.py`, why do we need to provide a speech model with speaker model? As speaker identification is independent of speech model. 

> vosk-model-spk-0.3 | 13M | TBD | Model for speaker identification, should work for all languages

**Comment by nshmyrev** [comment]
Speech model is used to extract utterances (think of very advanced VAD).

**Comment by omerasif-itu** [comment]
Ahan. So I am assuming that one needs a Russian Model to identify Russian Speakers. Is it correct?

**Comment by nshmyrev** [comment]
You can probably use any vad, we just don't have this in the API.

**Comment by omerasif-itu** [comment]
Alright. Thanks!
