### ISSUE TITLE
used memory size increase (java)

### ISSUE THREAD

**Issue by sutekyara** [alphacep/vosk-api#1441]
I am running vosk on JVM with JNI library.
I figure out this message in log, and JVM seems to use more memory up to JVM MAX MEMORY SIZE.
the log was written around "acceptWebForm" or "getResult" methods called.

```
LOG (VoskAPI:RebuildRepository():determinize-lattice-pruned.cc:283) Rebuilding repository.
WARNING (VoskAPI:CheckMemoryUsage():determinize-lattice-pruned.cc:316) Did not reach requested beam in determinize-lattice: size exceeds maximum 50000000 bytes; (repo,arcs,elems) = (20482176,1971328,27550152), after rebuilding, repo size was 13310912, effective beam was 5.86185 vs. requested beam 6
```

I want to know why "Rebuilding repository" operation was executed and how to resolve those problems.

**Comment by nshmyrev** [comment]
C++ library doesn't use JVM memory, it uses own allocator, so max memory size is not relevant.

Rebuilding repository discussed here: https://github.com/alphacep/vosk-api/issues/1127
