### ISSUE TITLE
Garbled characters when using JNA:5.10.0+

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [alphacep/vosk-api#1449]
When I use java api and the jna version is 5.10.0+, the result is garbled, and it is normal when switching to 5.7.0
I want to know if this is a bug or if it requires me to make additional changes to the code?

Language: Eclipse Temurin JDK 17.0.8.1
Version: 
* com.alphacephei:vosk:0.3.45
* net.java.dev.jna:jna:5.10.0+

Modal: vosk-model-small-cn-0.22
Code: Base from https://github.com/alphacep/vosk-api/blob/master/java/demo/src/main/java/org/vosk/demo/DecoderDemo.java

JNA 5.13.0
![image](https://github.com/alphacep/vosk-api/assets/57802425/e399d229-942d-40e1-b95c-a7a3566c846a)

JNA 5.7.0
![image](https://github.com/alphacep/vosk-api/assets/57802425/b9697eb2-c454-4a84-b693-6a0760781af8)

**Comment by unknowIfGuestInDream** [comment]
This problem has appeared since JNA5.10.0

**Comment by nshmyrev** [comment]
What about 5.14 the latest version please?

**Comment by unknowIfGuestInDream** [comment]
> What about 5.14 the latest version please?

Now the latest version of JNA is 5.13.0, and there is this problem.

**Comment by unknowIfGuestInDream** [comment]
> What about 5.14 the latest version please?

5.14 still has this problem

**Comment by unknowIfGuestInDream** [comment]
I found the cause of the problem.
https://github.com/java-native-access/jna/pull/1393/files#diff-2b1161da4142a2565bc95b82de87e04020a982e6dc03eb43e98247857f66fbe5R142
I have to set `jna.encoding` to ensure `DEFAULT_ENCODING` is `GBK`.
```java
System.setProperty("jna.encoding", "GBK");
```
If you have no other comments, I will close this issue soon.

**Comment by unknowIfGuestInDream** [comment]
I may have found the cause of the problem.
https://github.com/java-native-access/jna/pull/1393/files#diff-2b1161da4142a2565bc95b82de87e04020a982e6dc03eb43e98247857f66fbe5R142
I have to set `jna.encoding=UTF-8` before calling `LibVosk` (such as : `LibVosk.setLogLevel(LogLevel.INFO);`)
```java
System.setProperty("jna.encoding", "UTF-8");
```
![image](https://github.com/alphacep/vosk-api/assets/57802425/c9cd2bf3-c645-4481-aa32-f1b4f31a53a5)

If you have no other comments, I will close this issue soon.
