### ISSUE TITLE
Why do we need to convert short[] to byte[] in VOSK.i?

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#145]
Sorry, I don't know why do we need to convert short[] to byte[] in VOSK.i?

```
public boolean AcceptWaveform(short[] data, int len) {
        byte[] bdata = new byte[len * 2];
        ByteBuffer.wrap(bdata).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().put(data, 0, len);
        return AcceptWaveform(bdata, bdata.length);
  }
```

Thanks!

**Comment by nshmyrev** [comment]
swig java doesn't have efficient way to pass const short array into the C function without memory duplication, they only pass input-output arrays which means they copy the contents after method invocation again which is pretty slow.

So we only have byte wrapper and our current approach is just more efficient. 

Overall I'm not very happy about swig, it lacks basic things but complicates unneeded things instead.

**Comment by nshmyrev** [comment]
Let me know if you have further questions.
