### ISSUE TITLE
Voice input

### ISSUE THREAD

**Issue by ambioi** [alphacep/vosk-api#1455]
Please tell me how i can to use this solution on the Android platform for voice input? many thanks for great joab. You are the best!!!

![Screenshot_20231028-111936_Settings](https://github.com/alphacep/vosk-api/assets/141431798/97208dd3-f3b6-4424-9fd9-e4bc50a3e7a1)

**Comment by nshmyrev** [comment]
Yes, we have this thing

https://github.com/alphacep/vosk-android-service

it should integrate with a keyboard

**Comment by ambioi** [comment]
oh my god you do my day 🤩

**Comment by ambioi** [comment]
hhhm. I have encountered a new problem. Can you advise on how to solve it
![Screenshot_20231028-124128_Package installer](https://github.com/alphacep/vosk-api/assets/141431798/c18c43a4-6b18-4c40-8a25-7d7c6cae8d92)
