### ISSUE TITLE
Urlretrieve usage causes certificate error

### ISSUE THREAD

**Issue by yilun11** [alphacep/vosk-api#1456]
Related to issue #1015, I think the problem is line 117 in vosk-api\python\vosk\\\__init__.py

`
urlretrieve(MODEL_PRE_URL + str(model_name.name) + ".zip", str(model_name) + ".zip", reporthook=reporthook, data=None)
`

An alternative like requests.get() works fine.

To replicate (on Windows, Py 3.11.5) following throws CERTIFICATE_VERIFY_FAILED:

```
from urllib.request import urlretrieve

urlretrieve("https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip", "d:\temp.zip")
```

This does not throw the error:

```
import requests

file = requests.get("https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip")
```

**Comment by nshmyrev** [comment]
What is Windows version please? something very old?

**Comment by yilun11** [comment]
I am on Windows 11 Home Version 10.0.22624 Build 22624. I've seen other issues with certs, and think requests with certifi is the better approach.

**Comment by nshmyrev** [comment]
Ok, thanks. I can check a bit later if time permits. Getting a good certificate from proper authority is the right way of course.

**Comment by yilun11** [comment]
I think the certificate has the cross signed with expired DST Root CA X3 issue, which would explain the expiration error thrown. Unsure if this is a known issue on urllib and resolved in requests on the Windows platform.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/1137
