### ISSUE TITLE
Check if a zip file is a Vosk Model

### ISSUE THREAD

**Issue by ElishaAz** [alphacep/vosk-api#1460]
Hi, 
I need a way to check if a zip file is a Vosk Model.

Are there any specific files / folders that should always be in the zip?

**Comment by nshmyrev** [comment]
You can look for model/am/final.mdl, it should be always there.

**Comment by ElishaAz** [comment]
That's what I'm doing at the moment, but e.g. https://alphacephei.com/vosk/models/vosk-model-small-pt-0.3.zip has it at `model/final.mdl`

**Comment by ElishaAz** [comment]
Are these the only places it can be?

**Comment by nshmyrev** [comment]
Yes. Pt layout will change soon.

**Comment by ElishaAz** [comment]
Ok thanks!
