### ISSUE TITLE
Setting endpoint rules silence at runtime

### ISSUE THREAD

**Issue by m1adow** [alphacep/vosk-api#1462]
Hi! I have a small console application written on .NET for offline text recognition. Models are making huge sentences when audio has short pauses between phrases. I want to fix it. So I have found that the endpoint rule of silence (--endpoint.rule.min-trailing-silence) can help me with this problem. I wrote a workaround for changing values in model configurations but for changes to take place, the model needs to be reloaded which can take a while. Is there any way to implement it without reloading the model?

**Comment by nshmyrev** [comment]
We have ongoing discussion here

https://github.com/alphacep/vosk-api/pull/1457

Same as #1348
