### ISSUE TITLE
Question :: resampling in kaldi

### ISSUE THREAD

**Issue by madkote** [alphacep/vosk-api#1463]
Hi Nickolay (@nshmyrev )

since models can accept 8 or 16khz data, could you please point me to the place in kaldi sources where resampling (up/down) happens?

thanks!

**Comment by nshmyrev** [comment]
Sure, see 

https://github.com/kaldi-asr/kaldi/blob/master/src/feat/resample.cc
https://github.com/kaldi-asr/kaldi/blob/master/src/feat/online-feature.cc#L84
