### ISSUE TITLE
Installing vosk on Windows 11 - ffi-napi problem

### ISSUE THREAD

**Issue by tansyxiao** [alphacep/vosk-api#1465]
Trying to get a node.js Vosk project that was initially built on Mac to work on a Windows machine.
Here's the log. 
[error log.log](https://github.com/alphacep/vosk-api/files/13342584/error.log.log)

**Comment by nshmyrev** [comment]
Its ffi-napi bug, not vosk. Pretty common on the web, for example here:

https://stackoverflow.com/questions/54532854/error-c-program-files-x86-microsoft-visual-studio-2017-buildtools-msbuild-1

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1

something wrong with your build environment

**Comment by tansyxiao** [comment]
I tried a few things mentioned in this post. The `npm install --global windows-build-tools` command no longer works. Switching to a different python version, cache clean then npm install, or reinstalling node.js also didn't help.

**Comment by tansyxiao** [comment]
Solved by 1. uninstalling the current version of node.js; 2. using [nvm windows](https://github.com/coreybutler/nvm-windows) to downgrade node.js to v11.15.0 (any version prior to this is not compatible with vosk for some reason, but this one works); 3. same old npm install vosk.
On a separate note, didn't realize that Windows has to use a .exe install file for SoX, the npm installed one didn't work for SoX for some reason.
