### ISSUE TITLE
model for french/english

### ISSUE THREAD

**Issue by atticushawk** [alphacep/vosk-api#147]
hello,

I noticed in issue #122, you had mentioned about commercial models. Do you have models for french? and maybe a better model for English that you give commercially?

**Comment by nshmyrev** [comment]
Hi. Best models are specialized for some kind of application. Feel free to contact me by email contact@alphacephei.com, I'd be happy to discuss.

**Comment by nshmyrev** [comment]
Feel free to reopen if needed.
