### ISSUE TITLE
Absence of C language installation instructions

### ISSUE THREAD

**Issue by Taher0321** [alphacep/vosk-api#1471]
Hi,
We are making a device that needs vosk. We are programming the same device with C.
When we visited vosk installation page: https://alphacephei.com/vosk/install we didn't find installation instructions for C language.

Kindly help us with the "install instructions for C".

**Comment by Boussetta** [comment]
You can follow the instructions from the **Building the library libvosk.so** paragraph for C projects.

**Comment by Taher0321** [comment]
> You can follow the instructions from the **Building the library libvosk.so** paragraph for C projects.

Could you give us the link to that page, please? We cannot find it. It would be a great help..

**Comment by Boussetta** [comment]
> > You can follow the instructions from the **Building the library libvosk.so** paragraph for C projects.
> 
> Could you give us the link to that page, please? We cannot find it. It would be a great help..

It's on the same link you mentioned in your earlier post.


> When we visited vosk installation page: https://alphacephei.com/vosk/install we didn't find installation instructions for C language.

Just scroll down on the page and you will find the paragraph.

**Comment by Taher0321** [comment]
> You can follow the instructions from the **Building the library libvosk.so** paragraph for C projects.

Thanks bud

**Comment by Taher0321** [comment]
> > > You can follow the instructions from the **Building the library libvosk.so** paragraph for C projects.
> > 
> > 
> > Could you give us the link to that page, please? We cannot find it. It would be a great help..
> 
> It's on the same link you mentioned in your earlier post.
> 
> > When we visited vosk installation page: https://alphacephei.com/vosk/install we didn't find installation instructions for C language.
> 
> Just scroll down on the page and you will find the paragraph.


Hi, the problem still persists:
This is the instructions in building the library libvosk.so:
Building the library libvosk.so
Take a note that you need special Kaldi from our repo and also you need special compilation mode (openblas+clapack or mkl, shared, optionally cuda). For more details on build see our dockerfiles.

cd <KALDI_ROOT>
git clone -b vosk --single-branch --depth=1 https://github.com/alphacep/kaldi /opt/kaldi
cd kaldi/tools
make openfst cub
./extras/install_openblas_clapack.sh
cd ../src
./configure --mathlib=OPENBLAS_CLAPACK --shared
make -j 10 online2 lm rnnlm
cd ../..
git clone https://github.com/alphacep/vosk-api --depth=1
cd vosk-api/src
KALDI_ROOT=<KALDI_ROOT> make


But no instructions is given for where to paste this. libvosk.so link is not opening. When we paste the link on windows cmd it shows incorrect command. 

Kindly guide us in this

**Comment by nshmyrev** [comment]
>  When we paste the link on windows cmd it shows incorrect command.

You need Linux to build Vosk. For Windows you can download precompiled binary in releases.

**Comment by Taher0321** [comment]
> You need Linux to build Vosk. For Windows you can download precompiled binary in releases.

https://github.com/alphacep/vosk-api/blob/master/c/test_vosk_speaker.c

is this link will be helpful?

**Comment by nshmyrev** [comment]
> is this link will be helpful?

You'd better describe the problem you have and we will help you

**Comment by Taher0321** [comment]
> > is this link will be helpful?
> 
> You'd better describe the problem you have and we will help you

This is our problem:
We want to integrate vosk in our IoT device. Which is powered with a Qualcomm chip. For integrating the same we need vosk code in C language. 

But on the installation page we did not found any installation instructions for C. One of the user helped us by saying we will find paragraph in "Building the library libvosk.so". But there also we didn't found any help.


**Precisely, We need a link to the webpage which has installation instructions for C language and instructions to where to post those commands i.e in Visual studio, windows cmd or IDE (Qualcomm Visual studio). And integrate vosk in the our device make it work as per the requirements. Note: we are not using Raspberry Pi, we use Qualcomm chip**

**Comment by nshmyrev** [comment]
To build vosk for custom device you need to use custom device toolchain (SDK) and Linux. You can not use Windows.

Your device should have Linux SDK.

**Comment by Taher0321** [comment]
> To build vosk for custom device you need to use custom device toolchain (SDK) and Linux. You can not use Windows.
> 
> Your device should have Linux SDK.

Yes. We have these. Could you give us installation/build instructions webpage link now?

**Comment by nshmyrev** [comment]
> Could you give us installation/build instructions webpage link now?

Sure, see here https://alphacephei.com/vosk/install

You need to have some experience with cross-compilation though, for example, on how to redefine compiler with environment variable.

**Comment by KaustubhaPundir** [comment]
https://github.com/hwpoison/vosk-voice-recognition-c
Maybe this can help you in implementation of vosk in C (in windows).

**Comment by Taher0321** [comment]
> https://github.com/hwpoison/vosk-voice-recognition-c Maybe this can help you in implementation of vosk in C (in windows).

Thank you
