### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)

### ISSUE THREAD

**Issue by mdarwish** [alphacep/vosk-api#1472]
I get this error trying to install vosk on macos 12.3.

```
ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk
```

Attached the outputs of diagnostic commands.
[vosk-diags.txt](https://github.com/alphacep/vosk-api/files/13465029/vosk-diags.txt)

Can you help please?

**Comment by nshmyrev** [comment]
You need to upgrade pip to 20.3, you have 20.2. Install instructions mention that. 

Same as https://github.com/alphacep/vosk-api/issues/699
