### ISSUE TITLE
How to convert vosk-model-cn-kaldi-multicn-0.15 to small one?

### ISSUE THREAD

**Issue by deepsadness** [alphacep/vosk-api#1476]
Hello. This repo is aweasmone. 
But there is a doubt that bothers me.

In the model list. I found vosk-model-cn-kaldi-multicn-0.15. 
Is there any way to convert it into a small version?
How should I train small one?

**Comment by nshmyrev** [comment]
You can not convert, you have to train a new one. The training script example is here:

https://github.com/alphacep/vosk-api/tree/master/training

see also

https://github.com/alphacep/vosk-api/blob/master/python/example/colab/vosk-training.ipynb

You can also check the original Kaldi multicn recipe

**Comment by nshmyrev** [comment]
Let us know if you have other questions
