### ISSUE TITLE
Exception: Failed to create a model

### ISSUE THREAD

**Issue by EvilGeorgee** [alphacep/vosk-api#1478]
**Having this issue, (model folder is unpacked), I've tried different models, always the same error
What might be the problem?**
![image](https://github.com/alphacep/vosk-api/assets/97786475/b6ff134f-d2e2-4c9d-94d7-e91f5b3d7bf8)

**Comment by nshmyrev** [comment]
You specify wrong path to the model. If you are not sure about relative model path, use absolute model path. Also read the log output above the exception, it contains hints.

**Comment by EvilGeorgee** [comment]
**Specifying an absolute path helped, thank you :)**
