### ISSUE TITLE
test_word, error

### ISSUE THREAD

**Issue by Clunx** [alphacep/vosk-api#148]
hello, thank you for your amazing work.

I had an error while running "test_word.py" to run kaldi_recognizer through a list of words. the error was the following, i have tried using it with the default english model provided for vosk.

ERROR (VoskAPI:KaldiRecognizer():build-libkaldiwrap/kaldi_recognizer.cc:82) Can't create decoding graph.

**Comment by nshmyrev** [comment]
Did you modify the list of words? What exactly did you modify?

**Comment by Clunx** [comment]
It's okay I have solved it.
Thank you.
