### ISSUE TITLE
Unable to find  libvosk.lib or libvosk.a library file. in my VOSK API repository.

### ISSUE THREAD

**Issue by Taher0321** [alphacep/vosk-api#1485]
Hi,
In my VOSK API repository I couldn't find the libvosk.lib or libvosk.a library file. Same for my portaudio API where I couldn't find the libportaudio.a library file so could you guys tell me from where I could download the file or is there any vosk repository or portaudio repository where I could find this files.

**And we are developing this in C language.**

Looking forward for your help,

**Comment by nshmyrev** [comment]
https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-win64-0.3.45.zip

**Comment by Taher0321** [comment]
Thank you for sending the zip. But the zip doesn't have 'libportaudio.a' or libportaudio.lib'

We still need this files:  'libportaudio.a' or libportaudio.lib'

kindly help us with this.

**Comment by nshmyrev** [comment]
Something like https://github.com/shivang51/portaudio probably

**Comment by Taher0321** [comment]
![IMG-20231227-WA0004](https://github.com/alphacep/vosk-api/assets/151981876/7c80d6bd-0f88-4fb4-9cfd-b39c21a1db24)

I have provided all the necessary path for vosk API and portaudio API in code .jason file e.g  "-I/C:/portaudio/include","-I/C:/vosk/include","-L/C:/portaudio/lib","-L/C:/vosk/lib" it still showing the error as shown in below image is there any solution to run the code in windows? Or you could direct us to solve this error? @nshmyrev kindly help.

**Comment by nshmyrev** [comment]
You need to link the library itself with -lportaudio, /L only specifies the path.

**Comment by Taher0321** [comment]
> You need to link the library itself with -lportaudio, /L only specifies the path.

We followed this process and still getting the same error. We executed this in following way:
g++ speech.cpp -o speech.exe C:/portaudio/lib/portaudio.lib
specified the library and tried to link using the g++  still showing the below error                                                             cc1plus.exe: fatal error: speech.cpp: No such file or directory also  tried to solve using changing the path in task.json and properties.json as shown below but still showing the error shown in an image. do you have any way resolve this issue? 

**kindly help** @nshmyrev 


Screenshot is attached for your reference. 
![IMG-20231228-WA0003](https://github.com/alphacep/vosk-api/assets/151981876/ff9bb6f1-815f-4725-bd32-912442645a19)
![IMG-20231228-WA0004](https://github.com/alphacep/vosk-api/assets/151981876/42409b87-bbf4-41a1-94d2-113bfc52ad69)

**Comment by Taher0321** [comment]
> You need to link the library itself with -lportaudio, /L only specifies the path.

We used this line to link the library with -lportaudio using this command: **gcc speech.cpp -o speech.exe -LC:/path/to/vosk/lib -lvosk -LC:/path/to/portaudio/lib -lportaudio**

But the errors still persists. See the screenshot
![WhatsApp Image 2023-12-30 at 10 19 03 PM](https://github.com/alphacep/vosk-api/assets/151981876/ac149883-ee03-4e53-af48-20a524fd29ce)

**Comment by nshmyrev** [comment]
and what files are in C:/portaudio/lib
