### ISSUE TITLE
Dose the sever support concurrency?

### ISSUE THREAD

**Issue by kli017** [alphacep/vosk-api#149]
hello could this sever support concurrency, could it accept multiple requests from different client at the same time?

**Comment by nshmyrev** [comment]
Yes

**Comment by kli017** [comment]
@nshmyrev Thanks! any example how to set the server opts?

**Comment by nshmyrev** [comment]
> @nshmyrev Thanks! any example how to set the server opts?

Which opt exactly? Some can be configured with environment variables:

https://github.com/alphacep/vosk-server/blob/f616010fb5f29cd8545f113e2099fa0f1bc11e25/websocket/asr_server.py#L19
