### ISSUE TITLE
The transcription with the Spanish model does not include exclamation, question or punctuation marks.

### ISSUE THREAD

**Issue by dcfan75** [alphacep/vosk-api#1491]
Hello.

I use Vosk's Spanish subtitle transcription models and I have a question. How can I get the transcript to include punctuation marks, such as commas, periods, or exclamation marks or question marks?

Thank you.

**Comment by nshmyrev** [comment]
You can apply recasepunc model on top of results, same as https://github.com/alphacep/vosk-api/issues/152
