### ISSUE TITLE
Facing libvosk and portaudio error. 

### ISSUE THREAD

**Issue by Taher0321** [alphacep/vosk-api#1494]
We followed this process and still getting the same error. We executed this in following way:
g++ speech.cpp -o speech.exe C:/portaudio/lib/portaudio.lib
specified the library and tried to link using the g++  still showing the below error                                                             cc1plus.exe: fatal error: speech.cpp: No such file or directory also  tried to solve using changing the path in task.json and properties.json as shown below but still showing the error shown in an image. do you have any way resolve this issue? 

**kindly help**

Screenshot is attached for your reference. 
![IMG-20231228-WA0003](https://github.com/alphacep/vosk-api/assets/151981876/ff9bb6f1-815f-4725-bd32-912442645a19)
![IMG-20231228-WA0004](https://github.com/alphacep/vosk-api/assets/151981876/42409b87-bbf4-41a1-94d2-113bfc52ad69)

_Originally posted by @Taher0321 in https://github.com/alphacep/vosk-api/issues/1485#issuecomment-1871130001_

**Comment by nshmyrev** [comment]
Same as #1485, no need to open another one on the same topic
