### ISSUE TITLE
CMAKE File error

### ISSUE THREAD

**Issue by wcarl221** [alphacep/vosk-api#1495]
![WhatsApp Image 2024-01-01 at 8 08 01 PM](https://github.com/alphacep/vosk-api/assets/155376976/1a17d46a-47b8-4376-97e1-f63a505b2baa)
Hello, we are installing vosk in C. We are facing path error in CMAKE file, we tried backward/forward slash but the error still persists. 

How can we solve this? need your support

**Comment by nshmyrev** [comment]
Same as #1496
