### ISSUE TITLE
CMAKE file error

### ISSUE THREAD

**Issue by Taher0321** [alphacep/vosk-api#1496]
![WhatsApp Image 2024-01-01 at 8 08 01 PM](https://github.com/alphacep/vosk-android-service/assets/151981876/94e6a8c1-94ff-4267-8c10-4961873c9b67)
We are developing vosk for C and created CMAKE file. In the CMAKE file we are facing path error, though the path is right we are encountering this problem.
Kindly help. We tried forward/blackward slash but still facing the same error.

**Comment by nshmyrev** [comment]
The issue with Portaudio and Cmake has no relation to our project

**Comment by nshmyrev** [comment]
You can use find_library instead of find_package for portaudio too
