### ISSUE TITLE
Path errors for vosk lib

### ISSUE THREAD

**Issue by wcarl221** [alphacep/vosk-api#1497]
![WhatsApp Image 2024-01-02 at 11 04 45 AM](https://github.com/alphacep/vosk-api/assets/155376976/888f6cbb-d114-44a7-8252-bfc365c87618)

Hi, The last error was solved. Thanks for help.

We are encountering path error for vosk(See the screenshot) though we have given right path, this kind of error is coming up. 

Please help.

**Comment by nshmyrev** [comment]
Please stop opening new bugs again and again, not really related to Vosk. Same as

https://github.com/alphacep/vosk-api/issues/1495
