### ISSUE TITLE
Creating model purely on my custom data

### ISSUE THREAD

**Issue by kundanashish** [alphacep/vosk-api#1498]
I tried to finetune the model with my data but still it is not very much accurate.
I want to create an indian english model purely on my custom data. Can someone pls guide me what would be the best approach?

**Comment by nshmyrev** [comment]
Our training setup is here:

https://github.com/alphacep/vosk-api/tree/master/training

you can run it in colab

https://github.com/alphacep/vosk-api/blob/master/python/example/colab/vosk-training.ipynb

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/41
