### ISSUE TITLE
Vosk long loading time when cell is stopped prints: "error loading waveform"

### ISSUE THREAD

**Issue by Rahil8533** [alphacep/vosk-api#1499]
I have been trying to use vosk however it keeps loading without printing output in jupyter notebook
here is my code:
from vosk import Model, KaldiRecognizer
import os
import queue
import vosk
import sys
import json
import wave 
model_dir="./vosk-model-en-us-0.22"
if not os.path.exists(model_dir):
    print ("Please download a model for your language from https://alphacephei.com/vosk/models")
    print ("and unpack as "+model_dir+"' in the current folder.")
    #sys.exit(0)
model = vosk.Model(model_dir)
#with wave.open("Audio_Files/EN/checkin.wav") as wf:
with wave.open("./checkin.wav") as wf:
    assert wf.getnchannels() == 1, "must be a mono wav"
    assert wf.getsampwidth() == 2, "must be a 16bit wav"
    assert wf.getcomptype() == "NONE", "must be PCM data"
#wf.getnframes()
    rec = vosk.KaldiRecognizer(model, wf.getframerate())
    while True:
        data = wf.readframes(4000)
        if rec.AcceptWaveform(data):
            res = json.loads(rec.Result())
            print(res["text"])

I have tried the [vosk-model-small-en-us-0.15](https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip) model as well with the same result

**Comment by nshmyrev** [comment]
You'd better show a screenshot with the problem

**Comment by nshmyrev** [comment]
Let us know if you need extra help
