### ISSUE TITLE
Cannot setup python package on Linux (Ubuntu 18.04)

### ISSUE THREAD

**Issue by sakhnevych** [alphacep/vosk-api#15]
Thank you for a great lib!
But I didn't get a chance to try it, because I can't install python module.

There were some errors during installation:
1. During Kaldi installation, the command helps to install all necessary dependencies before "make -j 10".
./kaldi/tools./extras/check_dependencies.sh

2. I had to install CMake 3.10.1 or higher.
https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu

3. I tried to run `sudo python3 setup.py install` but got an error:
> fatal error: Python.h: No such file or directory

I've added to `CMakeLists.txt` 2 lines and it worked for me.
> find_package(PythonLibs REQUIRED)
> include_directories(${PYTHON_INCLUDE_DIRS})

*from here https://stackoverflow.com/questions/11041299/python-h-no-such-file-or-directory

4. After that I installed required OpenFST as described here:
https://aghriss.github.io/posts/2018/01/01/OpenFSTubuntu.html

5. And a step with hack:
copied folders from `kaldi/src/` to `vosk-api/src/`.
I am not sure, how to do it corect, but it helped me to move further.

6. Now I have a lot of errors. The first is:
/usr/bin/c++  

> -D_vosk_EXPORTS -I/usr/include/python3.5m -I/home/smartly/tmp/vosk-api/python/../src -I/src -I/tools/openfst/include  -O3 -DFST_NO_DYNAMIC_LINKING  -O3 -DNDEBUG -fPIC   -o CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o -c /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5/voskPYTHON_wrap.cxx
> In file included from /usr/include/c++/5/cstdint:35:0,
>                  from /usr/local/include/fst/types.h:19,
>                  from /home/smartly/tmp/vosk-api/python/../src/base/kaldi-types.h:44,
>                  from /home/smartly/tmp/vosk-api/python/../src/base/kaldi-error.h:34,
>                  from /home/smartly/tmp/vosk-api/python/../src/base/kaldi-common.h:35,
>                  from /home/smartly/tmp/vosk-api/python/../src/kaldi_recognizer.h:1,
>                  from /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5/voskPYTHON_wrap.cxx:3121:
> /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
>  #error This file requires compiler and library support \
>   ^
> In file included from /home/smartly/tmp/vosk-api/python/../src/base/kaldi-types.h:44:0,
>                  from /home/smartly/tmp/vosk-api/python/../src/base/kaldi-error.h:34,
>                  from /home/smartly/tmp/vosk-api/python/../src/base/kaldi-common.h:35,
>                  from /home/smartly/tmp/vosk-api/python/../src/kaldi_recognizer.h:1,
>                  from /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5/voskPYTHON_wrap.cxx:3121:
> /usr/local/include/fst/types.h:24:7: error: expected nested-name-specifier before ‘int8’
>  using int8 = int8_t;
>        ^
> /usr/local/include/fst/types.h:25:7: error: expected nested-name-specifier before ‘int16’
>  using int16 = int16_t;

Can you please help me to fix it?

**Comment by nshmyrev** [comment]
Try to add  -std=c++11 in CMakeLists.txt
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -O3 -DFST_NO_DYNAMIC_LINKING")
```

**Comment by nshmyrev** [comment]
And you can simply install precompiled version with pip:

`pip3 install vosk`

You will need to upgrade to pip 19 though

**Comment by nshmyrev** [comment]
Some other notes:

```
I had to install CMake 3.10.1 or higher.
https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu
```
cmake 3.10.2 is default on ubuntu 18, you just run 'apt install cmake'

> After that I installed required OpenFST as described here:
> https://aghriss.github.io/posts/2018/01/01/OpenFSTubuntu.html

That was not a great idea, openfst is compiled as part of kaldi when you run make in tools

> And a step with hack:
> copied folders from kaldi/src/ to vosk-api/src/.
> I am not sure, how to do it corect, but it helped me to move further.

It was better to set KALDI_ROOT environment variable.

**Comment by sakhnevych** [comment]
OK, thank you for the explanations.
I am not good in C. I will try to do it one more time.

Unfortunatelly, I can't install
`$ pip3 install vosk`
> Collecting vosk
>   Could not find a version that satisfies the requirement vosk (from versions: )
> No matching distribution found for vosk

But `-std=c++11` fixed the issue.

**Comment by sakhnevych** [comment]
Now I have this one. But I guess, it could be caused by some additional steps, which I did.
I will try to reinstall later.

> $ sudo python3 setup.py install
> /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
>   warnings.warn(msg)
> running install
> running bdist_egg
> running egg_info
> writing top-level names to vosk.egg-info/top_level.txt
> writing vosk.egg-info/PKG-INFO
> writing dependency_links to vosk.egg-info/dependency_links.txt
> reading manifest file 'vosk.egg-info/SOURCES.txt'
> writing manifest file 'vosk.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5
> /opt/cmake-3.16.2-Linux-x86_64/bin/cmake -S/home/smartly/tmp/vosk-api/python -B/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5 --check-build-system CMakeFiles/Makefile.cmake 0
> make -f CMakeFiles/Makefile2 _vosk
> make[1]: Entering directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> /opt/cmake-3.16.2-Linux-x86_64/bin/cmake -S/home/smartly/tmp/vosk-api/python -B/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5 --check-build-system CMakeFiles/Makefile.cmake 0
> /opt/cmake-3.16.2-Linux-x86_64/bin/cmake -E cmake_progress_start /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5/CMakeFiles 5
> make -f CMakeFiles/Makefile2 CMakeFiles/_vosk.dir/all
> make[2]: Entering directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> make -f CMakeFiles/vosk_swig_compilation.dir/build.make CMakeFiles/vosk_swig_compilation.dir/depend
> make[3]: Entering directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> cd /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5 && /opt/cmake-3.16.2-Linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /home/smartly/tmp/vosk-api/python /home/smartly/tmp/vosk-api/python /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5 /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5 /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5/CMakeFiles/vosk_swig_compilation.dir/DependInfo.cmake --color=
> make[3]: Leaving directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> make -f CMakeFiles/vosk_swig_compilation.dir/build.make CMakeFiles/vosk_swig_compilation.dir/build
> make[3]: Entering directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> make[3]: Nothing to be done for 'CMakeFiles/vosk_swig_compilation.dir/build'.
> make[3]: Leaving directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> [ 20%] Built target vosk_swig_compilation
> make -f CMakeFiles/_vosk.dir/build.make CMakeFiles/_vosk.dir/depend
> make[3]: Entering directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> cd /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5 && /opt/cmake-3.16.2-Linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /home/smartly/tmp/vosk-api/python /home/smartly/tmp/vosk-api/python /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5 /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5 /home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5/CMakeFiles/_vosk.dir/DependInfo.cmake --color=
> make[3]: Leaving directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> make -f CMakeFiles/_vosk.dir/build.make CMakeFiles/_vosk.dir/build
> make[3]: Entering directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> [ 40%] Building CXX object CMakeFiles/_vosk.dir/home/smartly/tmp/vosk-api/src/model.cc.o
> /usr/bin/c++  -D_vosk_EXPORTS -I/usr/include/python3.5m -I/home/smartly/tmp/vosk-api/python/../src -I/src -I/tools/openfst/include  -std=c++11 -O3 -DFST_NO_DYNAMIC_LINKING -O3 -DFST_NO_DYNAMIC_LINKING  -O3 -DNDEBUG -fPIC   -o CMakeFiles/_vosk.dir/home/smartly/tmp/vosk-api/src/model.cc.o -c /home/smartly/tmp/vosk-api/src/model.cc
> make[3]: *** No rule to make target '/src/online2/kaldi-online2.a', needed by '../lib.linux-x86_64-3.5/vosk/_vosk.so'.  Stop.
> make[3]: Leaving directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/_vosk.dir/all' failed
> make[2]: *** [CMakeFiles/_vosk.dir/all] Error 2
> make[2]: Leaving directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/_vosk.dir/rule' failed
> make[1]: *** [CMakeFiles/_vosk.dir/rule] Error 2
> make[1]: Leaving directory '/home/smartly/tmp/vosk-api/python/build/temp.linux-x86_64-3.5'
> Makefile:131: recipe for target '_vosk' failed
> make: *** [_vosk] Error 2
> Traceback (most recent call last):
>   File "setup.py", line 28, in <module>
>     python_requires='>=3.4',
>   File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
>     self.do_egg_install()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
>     self.run_command('bdist_egg')
>   File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
>     self.run_command(cmdname)
>   File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
>     self.build()
>   File "/usr/lib/python3.5/distutils/command/install_lib.py", line 107, in build
>     self.run_command('build_py')
>   File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/home/smartly/tmp/vosk-api/python/cmake.py", line 73, in run
>     self.run_command("build_ext")
>   File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 75, in run
>     _build_ext.run(self)
>   File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
>     self.build_extensions()
>   File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
>     self._build_extensions_serial()
>   File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
>     self.build_extension(ext)
>   File "/home/smartly/tmp/vosk-api/python/cmake.py", line 64, in build_extension
>     env=env)
>   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['make', 'VERBOSE=1', '_vosk']' returned non-zero exit status 2

**Comment by sakhnevych** [comment]
> You will need to upgrade to pip 19 though

Just saw this note. I have an old one.

**Comment by nshmyrev** [comment]
> make[3]: *** No rule to make target '/src/online2/kaldi-online2.a', needed by '../lib.linux-x86_64-3.5/vosk/_vosk.so'. Stop.

You need to set KALDI_ROOT environment variable

**Comment by sakhnevych** [comment]
Thank you for the great support.
I've installed it using
`pip3 install vosk`

It would be cool to see this option or the link to PyPI repository in the Readme.
