### ISSUE TITLE
Technical requirements

### ISSUE THREAD

**Issue by verloka** [alphacep/vosk-api#150]
Скажите, пожалуйста, какие аппаратные средства (процессор/видеокарта)  были использованы для обучения [этой модели](https://alphacephei.com/vosk/models/vosk-model-ru-0.10.zip) и сколько по времени это заняло? Спасибо.

**Comment by nshmyrev** [comment]
8 GPU GTX1080Ti карт на два сервера. Полная тренировка где-то месяц занимает.
