### ISSUE TITLE
Vosk.dll file error

### ISSUE THREAD

**Issue by Taher0321** [alphacep/vosk-api#1500]
![IMG-20240104-WA0008](https://github.com/alphacep/vosk-api/assets/151981876/128b087f-f85c-410f-847a-04d6f1f1f6b1)

We have downloaded vosk.dll file from: https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-win64-0.3.45.zip

**But in our code we are facing this error:** corrupt or invalid file. 

System we are using:
Vs code community
Windows
C++ language. 

Kindly help.

**Comment by nshmyrev** [comment]
https://stackoverflow.com/a/35920570

**Comment by Taher0321** [comment]
> https://stackoverflow.com/a/35920570

This error is solved. But as soon as the window proceeds with execution we are getting this error:
**"module was build without symbols"**, **"Entry point not found"**. See the attached screenshot
![WhatsApp Image 2024-01-04 at 9 24 59 PM](https://github.com/alphacep/vosk-api/assets/151981876/0ac87c2e-1c4d-4211-8c74-80ba30b15168)

the path given is correct and as per the instructions in the stackoverflow link you provided.

Our system is of: 64bits, and we have installed necessary vosk files from your github.


How to solve this?

**Comment by Taher0321** [comment]
Error is solved. Thanks
