### ISSUE TITLE
Larger Turkish language model.

### ISSUE THREAD

**Issue by hanzydev** [alphacep/vosk-api#1503]
The vosk-model-small-tr-0.3 model is not enough for the project I am working on. Could you please train a large Turkish model? If you ask why don't you train it yourself, I found the necessary documentation very insufficient. Vosk is really important for my project.

**Comment by nshmyrev** [comment]
We have big Turkish model, you can contact us by email to get it.

**Comment by eda4github** [comment]
> We have big Turkish model

Dear Nickolay V. Shmyrev,
Would you please get me the larger Turkish model.please
I have already sent you an email
all the best
Eda

**Comment by donemuhendislik** [comment]
Could you share that larger Turkish model ? We need it too for our a RD project. We searched every link but we could not reach it. Thanks for your help.

**Comment by sametgungoren** [comment]
@nshmyrev, bigger Turkish model is in the enterprise package?

**Comment by eda4github** [comment]
still waiting for the larger Turkish model link to download please
ask us to email the request, I did, and no response
Why don't you post the link here or respond to the email ?

**Comment by nshmyrev** [comment]
> @nshmyrev, bigger Turkish model is in the enterprise package?

Yes, and that too. We give it out as well if person can explain the use case.

**Comment by nshmyrev** [comment]
> Why don't you post the link here or respond to the email ?

We do not respond to anonymous emails

**Comment by eda4github** [comment]
@nshmyrev
-You have asked here to email you
-I have sent you an email which was not anonymous at all.
-Now you asking to explain the use case
-Why didn't you ask that in response to my email
-if I give you the answer, what excuse will you have?
-Stop making excuses & get real, will you
-check your inbox and respond to my email (eda @ tuta) , if you are serious enough 
if not, stop lying about it

**Comment by ESDLisans** [comment]
This idiot doesn't have such a model, he wants attention. A lot of people have e-mailed him but he won't share. 

Kimseye dosyayı vermiyor tamamen gerizekalı bir primci alabilen varsa paylaşsın herkesle

**Comment by ESDLisans** [comment]
he wants attention. A lot of people have e-mailed him but he won't share.

Kimseye dosyayı vermiyor tamamen bir primci alabilen varsa paylaşsın herkesle

**Comment by ilbarsseckin** [comment]
I think there is no advanced Turkish model yet.

**Comment by eda4github** [comment]
I think he has a lot explanation he has to, he owes us
If he doesn't
 he should be banned from the platform by misleading us and wasting our valuable time
 I personally ready for an action

**Comment by Kadir-Atmaca1** [comment]
hello nshmyrev
Nikolay V. Shmyrev, I sent you an e-mail, but you did not reply. Could you please give me the big Turkish model? This is necessary for my project. Please, I tried to train it myself with common voice Turkish audio data but my system gave error, can you please give me the large Turkish model?
vosk-model-small-tr-0.3 does not detect very well


my project https://github.com/Kadir-Atmaca/Asistan-STT-Vosk

**Comment by nshmyrev** [comment]
@Kadir-Atmaca1 I haven't seen any email that resembles your name, sorry. Send it again and describe what your project is about.

**Comment by Kadir-Atmaca1** [comment]
This e-mail is for me, I sent you an e-mail from here. I am Kadir Atcaca, my project is a voice assistant.

If this email is correct, I sent it to contact@alphacephei.com

**Comment by berkayk** [comment]
Hi, I also would like to get a larger Turkish model. I would be grateful if you could send me. Thanks. Sent a mail to [contact@alphacephei.com](mailto:contact@alphacephei.com)

**Comment by Kadir-Atmaca1** [comment]
Merhaba Berkay ben bundan 3 hafta belkide 5 hafta önce
***@***.*** mail gönderdim bana geri dönüş yaptılar ama model
vermediler

Berkay Kaya ***@***.***>, 26 Nis 2024 Cum, 16:31 tarihinde
şunu yazdı:

**Comment by hanzydev** [comment]
Understand this, he is not giving anyone the larger Turkish language model

**Comment by Kadir-Atmaca1** [comment]
you are absolutely right

Emirhan ***@***.***>, 29 Nis 2024 Pzt, 03:25 tarihinde şunu
yazdı:

**Comment by Kadir-Atmaca1** [comment]
best to use openai whisper ai

musti poroje ***@***.***>, 30 Nis 2024 Sal, 23:26
tarihinde şunu yazdı:

**Comment by cerenokutangh** [comment]
> > We have big Turkish model
> 
> Dear Nickolay V. Shmyrev, Would you please get me the larger Turkish model.please I have already sent you an email all the best Eda

Eda Hanım, 
Bigger Turkish model'e ulaşabildiniz mi?

**Comment by rehberim360** [comment]
Yani mükemmel bir çalışma yapmışlar hakkını vermek lazım. Geçekten gerçek zamanlı konuşma tanıma olsun, kullanıcının seslerini vektöre dönüştürme ile konuşmacı tanımlama olsun mükemmel çalışıyor. Bir çok dilde geniş model var. Türkçede de var ama vermiyorlar. Unityde kaliteli bir asistan projesi üstünde çalışıyorum ve Vosk en temelini oluşturuyordu. Okadar mail attım o kadar konuştum ama vermediler. Diyalog tabanlı bir uygulama desemde ısrarla bana belirli metinleri ver özel bir model atayım demelerine rağmen sonuç yok. Yazık üzücü. Buradan küçük dil modeli yetersiz. Ne anladım ben bu işten. Neden açık kaynak yapıyorsun ki? Projemden Vosk u tamamen kaldırdım. Gerçekten üzücü ve modeli paylaşmamaları bencilce.

**Comment by alizorlu** [comment]
> Yani mükemmel bir çalışma yapmışlar hakkını vermek lazım. Geçekten gerçek zamanlı konuşma tanıma olsun, kullanıcının seslerini vektöre dönüştürme ile konuşmacı tanımlama olsun mükemmel çalışıyor. Bir çok dilde geniş model var. Türkçede de var ama vermiyorlar. Unityde kaliteli bir asistan projesi üstünde çalışıyorum ve Vosk en temelini oluşturuyordu. Okadar mail attım o kadar konuştum ama vermediler. Diyalog tabanlı bir uygulama desemde ısrarla bana belirli metinleri ver özel bir model atayım demelerine rağmen sonuç yok. Yazık üzücü. Buradan küçük dil modeli yetersiz. Ne anladım ben bu işten. Neden açık kaynak yapıyorsun ki? Projemden Vosk u tamamen kaldırdım. Gerçekten üzücü ve modeli paylaşmamaları bencilce.


Merhaba, yorumuna istinaden yazıyorum. 
Kurumsal bir iş için modele ihtiyacım oldu 2 haftalık bi mailleşme süreci sonrası ilettiler. 3GB'ı aşkın bi model. Türk arkadaşlar için yayınlayabilecek bir upload ortamı bulamadım ama benimle iletişime geçerseniz ileteyim sizler için. 

Kolaylıklar

**Comment by rehberim360** [comment]
> > Yani mükemmel bir çalışma yapmışlar hakkını vermek lazım. Geçekten gerçek zamanlı konuşma tanıma olsun, kullanıcının seslerini vektöre dönüştürme ile konuşmacı tanımlama olsun mükemmel çalışıyor. Bir çok dilde geniş model var. Türkçede de var ama vermiyorlar. Unityde kaliteli bir asistan projesi üstünde çalışıyorum ve Vosk en temelini oluşturuyordu. Okadar mail attım o kadar konuştum ama vermediler. Diyalog tabanlı bir uygulama desemde ısrarla bana belirli metinleri ver özel bir model atayım demelerine rağmen sonuç yok. Yazık üzücü. Buradan küçük dil modeli yetersiz. Ne anladım ben bu işten. Neden açık kaynak yapıyorsun ki? Projemden Vosk u tamamen kaldırdım. Gerçekten üzücü ve modeli paylaşmamaları bencilce.
> 
> Merhaba, yorumuna istinaden yazıyorum. Kurumsal bir iş için modele ihtiyacım oldu 2 haftalık bi mailleşme süreci sonrası ilettiler. 3GB'ı aşkın bi model. Türk arkadaşlar için yayınlayabilecek bir upload ortamı bulamadım ama benimle iletişime geçerseniz ileteyim sizler için.
> 
> Kolaylıklar

Mail attım size. Benim mailim dncgogo@gmail.com  Gerçekten modeli bana ulaştırabilirseniz minnettar kalırım.

**Comment by nshmyrev** [comment]
Hello guys. Please note that it is a violation of copyright to distribute the model you received from us. Each model is watermarked and can be traced to original correspondent.

Overall, I'm very upset by the community behavior here.
