### ISSUE TITLE
different phones.txt and words.txt

### ISSUE THREAD

**Issue by YangangCao** [alphacep/vosk-api#1506]
Hi dear author,

I have trained my own model with this doc https://github.com/alphacep/vosk-api/tree/master/training, but it's totally different from vosk-model-small-en-us-0.15 and vosk-model-en-us-0.22-lgraph.

1.words.txt  and phones.txt in vosk-model-en-us-0.22-lgraph are different from my own model,  and  vosk-model-small-en-us-0.15 don't include these 2 files. In my practice, I delete the Gr.fst in vosk-model-small-en-us-0.15 and copy  words.txt from  vosk-model-en-us-0.22-lgraph to vosk-model-small-en-us-0.15, I got bad result in ASR with grammar, so I think vosk-model-en-us-0.22-lgraph and vosk-model-small-en-us-0.15 use different words.txt (because I delete Gr.fst in vosk-model-en-us-0.22-lgraph and use words.txt also get correct result), right?

2.no tree in vosk-model-small-en-us-0.15. actually, I need tree and L.fst to calculate goodness of pronunciation(gop), and I also need ASR with grammar

I dont know the resaons, can you please explain how to get tree, phones.txt  words.txt and L.fst in vosk-model-small-en-us-0.15?

Thanks very much !!!

**Comment by nshmyrev** [comment]
You can contact us by email to get an update package for vosk-model-small-en-us-0.15. Update package includes tree and other required files.

**Comment by nshmyrev** [comment]
Same as #1687
