### ISSUE TITLE
Improve recongition of certain words

### ISSUE THREAD

**Issue by ilyamiro** [alphacep/vosk-api#1507]
I am creating a project, where i need some specific words to be recognized more often than others. But i don't mean recognizing ONLY these words, i mean recognizing all the words, but just increase the probability that when i say something very similar to key words, a model would most likely recognize that key word, not something close to it. But if the input is not even close to the input word - it will recognize it as it is. Is it possible to achieve?

**Comment by nshmyrev** [comment]
Sure, you can add more examples to extra.txt and recompile the graph. It will increase probability of your keyword. See https://alphacephei.com/vosk/lm

**Comment by nshmyrev** [comment]
Same as #866
