### ISSUE TITLE
vosk-model-en-us-0.22-lgraph and vosk-model-en-us-0.22 model both are not performing well

### ISSUE THREAD

**Issue by Greatz08** [alphacep/vosk-api#1508]
getting random text generation for audio file and music file. i mean it is not even generating and getting stuck in between result generation too.Compared to openai whisper it is performing in worst possible way

**Comment by nshmyrev** [comment]
Share the file

**Comment by nshmyrev** [comment]
And the way you run the decoding

**Comment by Greatz08** [comment]
![20240127_17h25m02s_grim](https://github.com/alphacep/vosk-api/assets/55040435/6ce63e7b-9c23-472e-ba0d-6cc6fc251a4f)
![20240127_17h32m18s_grim](https://github.com/alphacep/vosk-api/assets/55040435/ea4ffa95-d718-480c-8320-418f5b07baa2)
![20240129_12h54m41s_grim](https://github.com/alphacep/vosk-api/assets/55040435/087e0a40-a3ce-4bd2-8c84-93f586cffc60)
![20240129_12h54m47s_grim](https://github.com/alphacep/vosk-api/assets/55040435/6147bb9e-68f6-46bc-8a50-c0759f2231ab)
![20240129_12h54m59s_grim](https://github.com/alphacep/vosk-api/assets/55040435/08de3631-e8fa-4a38-b979-c2b2cab683d8)
![20240129_12h55m07s_grim](https://github.com/alphacep/vosk-api/assets/55040435/3c617323-b34b-4f4b-929b-7b8bb6feb853)
![20240129_12h55m29s_grim](https://github.com/alphacep/vosk-api/assets/55040435/f8d9fff0-1143-4694-94ac-8a267bdba05c)

**Comment by Greatz08** [comment]
i have attached both whisper model result in first two images and after that you can see how vosk model process the music file and generate the file in which nothing useful is there you can in last image, plus in cli too it is not detecting and showing perfect lines of music at all and i tried with different ones too and got same result @nshmyrev

**Comment by Greatz08** [comment]
if you wanna test yourself you can download linkin park music from net and test for yourself or any other file you can test and tell if i am doing something wrong because i got this command from documentation and guides

**Comment by nshmyrev** [comment]
Ok, that kind of task is beyond our current capabilities for now. For the future we might look into it

https://www.youtube.com/watch?v=1bQXcxZeits

**Comment by Greatz08** [comment]
@nshmyrev ok, hope it atleast reach to open ai whisper model level because their small models are also working very well even on my potato laptop haha so i was expecting not that level but still i was expecting some decent lines generation but it completely failed so i thought like am i doing something wrong or the project development is stopped or is not capable enough yet
