### ISSUE TITLE
[solved - fault in Kdenlive-23.08.4] Vosk on Siduction (Debian Sid), in a venv providing "access" to kdenlive.

### ISSUE THREAD

**Issue by TassieDevyl** [alphacep/vosk-api#1511]
Hi folks,
I've been looking for a means to improve upon subtitles in my video collection, particularly "fill in the gaps" where languages other than English are spoken.

To that end I'm excited about the potential of Vosk.

I've watched videos on YouTube showing it in action through kdenlive, where the results look good.

Attempting to install vosk using pip failed, an error message was displayed stating to install in a venv.

Installing vosk in a python venv was successful.

I've learned also that in order for applications to access libraries/modules in the venv it needs to be active.

Even with the venv active and running  to confirm that the venv is included in the PYTHONPATH kdenlive still doesn't "see" vosk.

`python3 -c "import sys; print(sys.path)"`
`['', /usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/venv-vosk/voskapi/lib/python3.11/site-packages']`

![kdenlive-vosk](https://github.com/alphacep/vosk-api/assets/19159354/a244d963-eccc-4c3d-9a82-5dda12c18384)

Any advice will be greatly appreciated.

**Edit: update**

I've found a thread on the KDE forums that is almost identical to the problems I've been experiencing.
The only difference being the poster is using Debian Stable.
It appears that there is a possible regression in the current version of Kdenlive (23.08.4) that prevents the detection of the vosk-transcriber and srt.

Also I've found that a request has been made for an official debian package 'python-vosk' with wishlist status.

Hopefully, then at some stage that will be actioned.

**Comment by nshmyrev** [comment]
Thanks for the update!
