### ISSUE TITLE
 size exceeds maximum 50000000 bytes

### ISSUE THREAD

**Issue by zgp123-wq** [alphacep/vosk-api#1512]
Rebuilding repository. WARNING (VoskAPI:CheckMemoryUsage():determinize-lattice-pruned.cc:316) Did not reach requested beam in determinize-lattice: size exceeds maximum 50000000 bytes; (repo,arcs,elems) = (49596928,256352,217176), after rebuilding, repo size was 44101664, effective beam was 5.98777 vs. requested beam 6

I have encountered this problem while using the https://alphacephei.com/vosk/models/vosk-model-en-us-0.22.zip model.

**Comment by nshmyrev** [comment]
Same issue as https://github.com/alphacep/vosk-api/issues/1127

**Comment by nshmyrev** [comment]
You can ignore this warning for now
