### ISSUE TITLE
Attempted to read or write protected memory while running C# demo

### ISSUE THREAD

**Issue by farhantahir80** [alphacep/vosk-api#1524]
I am using console application of c#. I have installed vosk from nuget manager. When system tries to run this command

VoskRecognizer rec = new VoskRecognizer(model, 16000.0f);

It is giving me an error.
'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

**Comment by farhantahir80** [comment]
I have downloaded the model and it worked... 

Can you please share c# example to capture Live speaking from mic and translate?

**Comment by nshmyrev** [comment]
Microphone code is here:

https://github.com/alphacep/vosk-api/issues/986
