### ISSUE TITLE
support very long grammar

### ISSUE THREAD

**Issue by YangangCao** [alphacep/vosk-api#1525]
Hi, dear author, I try to construct very long(about more than 400 words) grammar in Vosk, Now Vosk will report an error in such situation. Any idea about support very long grammar? 

Actually I want to align the very long text and the corresponding audio in pronunciation assessment, ASR with grammar is accurate and fast. The text is in order, I am not sure ordered text  is helpful for constructing very long grammar?

Thanks for your attention!

**Comment by nshmyrev** [comment]
What kind of error do you see?

**Comment by YangangCao** [comment]
Sorry, it's my fault, too short  char grammar buffer to use long grammar, when I change into long buffer, it runs as normal.
