### ISSUE TITLE
Turkish Big Model

### ISSUE THREAD

**Issue by ilbarsseckin** [alphacep/vosk-api#1526]

**Comment by nshmyrev** [comment]
Same as #1503

**Comment by ESDLisans** [comment]
İlbars hocam alabildiniz mi acaba?

**Comment by nshmyrev** [comment]
Ilbars got the model already

**Comment by cerenokutangh** [comment]
> No description provided.

İlbars Bey Merhaba,
bigger Turkish model'den memnun musunuz?

**Comment by nshmyrev** [comment]
@ibrahimlab2223-bot you have to contact us by email!

**Comment by ilbarsseckin** [comment]
Yes, not with me, Nikolay V. Shmyrev, thank you.

Nickolay V. Shmyrev ***@***.***>, 12 Şub 2026 Per, 12:05
tarihinde şunu yazdı:
