### ISSUE TITLE
Raspberry Pi 5 support

### ISSUE THREAD

**Issue by StremaLot** [alphacep/vosk-api#1527]
Can't install vosk on Raspberry Pi 5.
Get error: 
Error: Could not find a version that satisfies the requirement
Error: No matching distribution found for vosk

pip 23.3.1
Python 3.11.8

**Comment by nshmyrev** [comment]
What is the output of `pip3 install -v vosk` and `pip3 debug --verbose`

**Comment by StremaLot** [comment]
Sorry for inconvenience. I misstaked because of the zoo of linux-like platforms for Rpi. I installed Home Assistant OS 12 (Alpine linux) on RPi5 yesterday and it's gave that error. So today i install  Raspberry PI OS (64bit), port of Debian Bookworm and it give me install Vosk whithout problem. This issue can be closed.

**Comment by nshmyrev** [comment]
Ok, let us know how it goes!
