### ISSUE TITLE
How to create and train the model for new language? Tajik language

### ISSUE THREAD

**Issue by komyor09** [alphacep/vosk-api#1528]
Hi,

I am Komyor. I want to start create new model for Tajik language.

How to create it ?
How to build and compile it?
 How to share it?

Asap like to start works for new language.

Regards, Komyor.

**Comment by nshmyrev** [comment]
I told you already, you need to collect 1000+ hours of Tajik voices from youtube as a first step

**Comment by komyor09** [comment]
> Я уже говорил вам, что вам нужно собрать 1000+ часов таджикских голосов с YouTube в качестве первого шага.

 After that what?

**Comment by komyor09** [comment]
> Я уже говорил вам, что вам нужно собрать 1000+ часов таджикских голосов на YouTube в качестве первого шага.

After that what I should do?
Please tell all steps.

**Comment by nshmyrev** [comment]
You first collect and share the data then I tell you the steps

**Comment by komyor09** [comment]
> You first collect and share the data then I tell you the steps

Okay thanks
