### ISSUE TITLE
[feature request] upgrade nodejs module

### ISSUE THREAD

**Issue by silvioprog** [alphacep/vosk-api#1530]
Hi.

It would be nice to upgrade the official [NodeJS module](https://www.npmjs.com/package/vosk).

Is it missing important APIs like `vosk_recognizer_set_nlsml`, `vosk_recognizer_set_endpointer_mode`, `vosk_recognizer_set_endpointer_delays` etc.

TIA

**Comment by nshmyrev** [comment]
Same as #1522, we will try to make it.

Thanks!
