### ISSUE TITLE
Missing files in french update package

### ISSUE THREAD

**Issue by baptxste** [alphacep/vosk-api#1532]
I'm trying to finetune the french model on personnal data but it seems that all files about rnnlm are missing : 
/rnnlm 
/exp/rnnlm
/exp/rnnlm_out 
...
Is it possible to use the one provided in the en-model ? If not, do you have the files for the french model ?

**Comment by nshmyrev** [comment]
>  If not, do you have the files for the french model ?

What model do you need an update package for? What model are you trying to modify?

**Comment by baptxste** [comment]
I'm trying to modify this model https://alphacephei.com/vosk/models/vosk-model-fr-0.6-linto-2.2.0-compile.zip provided by the vosk website but the files mentioned above are missing. 
I downloaded the english version(https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-compile.zip) to compare and the files are present in this package. Can I use theses files in the french model to improve it ?

**Comment by nshmyrev** [comment]
> I'm trying to modify this model https://alphacephei.com/vosk/models/vosk-model-fr-0.6-linto-2.2.0-compile.zip provided by the vosk website but the files mentioned above are missing.

Linto model doesn't use llm rescoring, our vosk-model-fr does use it

> I downloaded the english version(https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-compile.zip) to compare and the files are present in this package. Can I use theses files in the french model to improve it ?

You need a model with rnnlm support, english files are not going to work in french model

**Comment by baptxste** [comment]
Ok thanks for the clarification. The big french model (https://alphacephei.com/vosk/models/vosk-model-fr-0.22.zip ) seems to be rnnlm based but there is no compile package for it. Do you have one or can I use the script from the en-us compile package ? 
Is it possible to finetune the acoustic model of the Linto compile package "easily" or do I need to finetune directly from kaldi ?

**Comment by nshmyrev** [comment]
> Do you have one or can I use the script from the en-us compile package ?

You can get it by writing us an email

> Is it possible to finetune the acoustic model of the Linto compile package "easily" or do I need to finetune directly from kaldi

There is no easy finetuning for the acoustic model

**Comment by baptxste** [comment]
Ok thanks I willl write you an email right now.
