### ISSUE TITLE
Where can I find more chinese models

### ISSUE THREAD

**Issue by taoqf** [alphacep/vosk-api#1538]
With [vosk-model-cn-0.22](https://alphacephei.com/vosk/models/vosk-model-cn-0.22.zip), I did some tests, But the output results is not correct sometimes, Is there any large chinese models could I download ? @nshmyrev

**Comment by nshmyrev** [comment]
If you want great accuracy you need to check FunASR model from Alibaba, we won't be able to match them in a near future

**Comment by nshmyrev** [comment]
More or less the same as #731

**Comment by taoqf** [comment]
Thanks
