### ISSUE TITLE
Is it possible to detect the spoken language?

### ISSUE THREAD

**Issue by silvioprog** [alphacep/vosk-api#1541]
Hi.

I have been developing this [free transcription website](https://fastranscribe.com) using the model `vosk-model-en-us-0.42-gigaspeech`, so it should accept only English videos, however, I've noticed some people sending videos in Portuguese, Spanish, Japanese and so on, and I would like to block it.

So, it that possible to detect if the audio (extracted from the video) is really in English language? (Something like [whisper.detect_language()](https://github.com/openai/whisper?tab=readme-ov-file#python-usage))

TIA for any help!

**Comment by nshmyrev** [comment]
There is no problem to use whisper for initial language identification step, you can also use other models like

https://huggingface.co/speechbrain/lang-id-voxlingua107-ecapa

**Comment by silvioprog** [comment]
@nshmyrev After a couple of tests, I decided to go with  [speechbrain/lang-id-voxlingua107-ecapa](https://huggingface.co/speechbrain/lang-id-voxlingua107-ecapa). Thanks a lot for this excellent suggestion!

**Comment by nshmyrev** [comment]
Tracked in https://github.com/alphacep/vosk-api/issues/420
