### ISSUE TITLE
Is there an example of a Java client connecting to the webRtc server

### ISSUE THREAD

**Issue by xubinlu** [alphacep/vosk-api#1544]
1、I haven't used WebRtc before. We are an Android application. Have anyone else implemented an example of using WebRtc to connect to a server from an Android application before
2、Can multiple client connections be supported simultaneously if using the webRtc server?

**Comment by nshmyrev** [comment]
1. Something like this probably

https://webrtc.github.io/webrtc-org/native-code/android/

2. Yes

**Comment by xubinlu** [comment]
> 1. Something like this probably
> 
> https://webrtc.github.io/webrtc-org/native-code/android/
thanks, I have seen this before, but after reading it, I still don't know how to write it. Unlike webSocket, which has Java client code examples, I am very clear about how to do it after reading it

**Comment by xubinlu** [comment]
I still have some questions. 
What is the address when connecting to the webRtc server in android? I know that the address in the browser is https://SERVER_IP:2700/

**Comment by nshmyrev** [comment]
You need to setup a forward from ssl-configured nginx to localhost:2700, in android you use external nginx url. You also have to open udp ports fro connection

**Comment by xubinlu** [comment]
When I was looking at other examples of webRtc used in android, I found that I need to use webSocket to connect to an address, and then use webRtc. Is the “external nginx url” the address to use webSocket to connect to?

**Comment by nshmyrev** [comment]
Offer comes with simple http post, not websocket. Yes post goes to external address.
