### ISSUE TITLE
.NET - x86 support

### ISSUE THREAD

**Issue by m1adow** [alphacep/vosk-api#1548]
Hi! Is there any way to make the Vosk library work in the x86 configuration? Because when I'm loading any model in code, I'm getting this exception:
`System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format.`

If not, can you implement x86 support?

**Comment by nshmyrev** [comment]
You have to build nuget package yourself, just put precompiled lib and update targets here:

https://github.com/alphacep/vosk-api/blob/master/csharp/nuget/build/Vosk.targets

it should work if you properly specify target

**Comment by m1adow** [comment]
Hi again! I tried like you said, but got the same error. Are you sure that precompiled lib supports x86? Because the exception is thrown here
![Bad image](https://github.com/alphacep/vosk-api/assets/84251113/4788b0b3-f604-456b-bcc5-287bf03b3822)

**Comment by nshmyrev** [comment]
Precompiled libs for x86 here

https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-linux-x86-0.3.45.zip

**Comment by m1adow** [comment]
Yeah, thanks a lot, it worked 😊
