### ISSUE TITLE
Issue with abbreviations

### ISSUE THREAD

**Issue by ujjwalgupta0909** [alphacep/vosk-api#155]
Hello, I have been using the Daanzu model for STT. It's really impressive but i want it to recognize some abbreviations like EPC , AFN etc and its not able understand them. Is there any way i can do that??

Thanks!

**Comment by nshmyrev** [comment]
You can add words with model compilation like this one:

https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/

**Comment by ujjwalgupta0909** [comment]
Thank you so much!
