### ISSUE TITLE
remove vocabulary from the model

### ISSUE THREAD

**Issue by baptxste** [alphacep/vosk-api#1553]
Hi, in order to improve the model on a specific task, I have updated the vocabulary and the language model but I still get mis-prediction on few words. For instance I often get 'udr' instead of 'edr'. In my case I will never have to use the word 'udr' and I was wondering if it was possible to delete this word from the dictionnary to avoid this type of misprediction. 
Do I simply need to remove it from the fr.dic and fr.vocab an then recompile the graph or is there another way to do this.

**Comment by nshmyrev** [comment]
If you remove words from vocab and dictionary and recompile the package, it should work, yes.
