### ISSUE TITLE
how to fine tuning Uzbek language dataset for Vosk model ?

### ISSUE THREAD

**Issue by RifatMamayusupov** [alphacep/vosk-api#1558]
I have dataset created in Kaldi format, so I want to build powerful ASR for uzbek language . I searched several ways to fine tuning and train , but I cannot find enough information.  I want to learn to fine tuning my own dataset to Vosk toolkit using Kaldi.

and there is  other issue , too which is lexicon dictionary. How to build lexicon dictionary. 
and if anyone has guide to train  dataset , please share it .

Thanks your respose.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/185
