### ISSUE TITLE
Vidoe tutorial for fine tuing Vosk model for any language .

### ISSUE THREAD

**Issue by RifatMamayusupov** [alphacep/vosk-api#1559]
I looked at all issues, and many people need to train or fine tuning their own dataset . So , if alphacep admin makes vidoe tutorial to fine tuning any language dataset , it is useful to all new coder and searching ways to fine .

if it is possible to make video tutorial , please help us admin , and other professional coder can do it .

Thanks all.

**Comment by nshmyrev** [comment]
Same as #1514
