### ISSUE TITLE
Adding custom new words

### ISSUE THREAD

**Issue by Varsha-Rao** [alphacep/vosk-api#156]
I am currently using vosk-api to get Kaldi working easily as a speech recognition tool for my webpage. However, I see that some less commonly used words like medical, dental and other terms like Abrasion Abscess Acute Benign Biopsy Chronic Contusion Edema Epidermis Fracture Hypertension Inpatient Intravenous Malignant Outpatient are not recognized by the kaldi decoder. Can someone clearly explain how to add these words into the model for training? I don't see a lexicon.txt in the model directory. I'm using Python for the server side code (import vosk).

**Comment by azain47** [comment]
Try using larger model

**Comment by nshmyrev** [comment]
This blog explains how to add words into Kaldi models:

https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/

**Comment by Varsha-Rao** [comment]
> This blog explains how to add words into Kaldi models:
> 
> https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/

Thanks. This worked!
