### ISSUE TITLE
Wondering how to train small models, big models work

### ISSUE THREAD

**Issue by Binozo** [alphacep/vosk-api#1560]
Hello there 👋

recently I successfully trained a new word for the german `vosk-model-de-0.21` :)

As I am currently running vosk on my Pi 5 I have limited memory and that german model already exceedes 5GB in memory usage. I wanted to perform that training on a smaller model like `vosk-model-small-de-zamia-0.3)` or `vosk-model-small-de-0.15` as I already had really good results with those in my case.

On your [page](https://alphacephei.com/vosk/lm) is the following instruction: `For small model, just pick the required files from exp/chain/tdnn/lgraph.` but sadly that `lgraph` directory is nowhere to find.

I found a reference to that directory in `compile-graph.sh:8`: `rm -rf exp/lgraph` but nowhere else 🤔

All other required directories and files for the big models do exist and work as expected. Does anybody know how to compile for those smaller models?

**Comment by nshmyrev** [comment]
You need a small model compilation package, you can request it over email contact@alphacephei.com

**Comment by Binozo** [comment]
Ok thanks!
