### ISSUE TITLE
What does the new postprocessors do?

### ISSUE THREAD

**Issue by msqr1** [alphacep/vosk-api#1562]

**Comment by nshmyrev** [comment]
They can convert numbers to digits like "five thousand" -> 5000. You can get corresponding models here:

https://github.com/NVIDIA/NeMo-text-processing

**Comment by msqr1** [comment]
Is this integrates into Vosk so I have to compile them together, or this is a separate component?

**Comment by nshmyrev** [comment]
Its part of the vosk, no need for anything extra

**Comment by msqr1** [comment]
So the asr is gonna output 5000, and this is going to convert it to five thousands?
 I can compile and run just fine without it, i dont see why I need it to postprocess the result?

**Comment by nshmyrev** [comment]
> So the asr is gonna output 5000, and this is going to convert it to five thousands?

opposite way

> I can compile and run just fine without it, i dont see why I need it to postprocess the result?

If you want to see 5000

**Comment by msqr1** [comment]
Oh ok, thanks so much!
