### ISSUE TITLE
Vosk for speech recognition on MCU

### ISSUE THREAD

**Issue by Taher0321** [alphacep/vosk-api#1564]
Hi,
We are using vosk api in our voice to text conversion product which we will commercialize and sell in India and later in the world, cool?

**Comment by nshmyrev** [comment]
Absolutely! Let us know if you need any help, we are interested to get it running.

**Comment by Taher0321** [comment]
Thanks

**Comment by Taher0321** [comment]
Hi,
We are facing so many difficulties in using Vosk, actually the device which will have Vosk API into it is a small wireless headphone like device, so it is being very difficult to find an MCU which can run big model like vosk, so do you:
1) Have any lighter version/solution that we can use in our device?
2) Do you suggest any MCU/microprocessor we can use that will run VOSK?

The language models on your website is very heavy, do you have an alternative solution?

Let me know if we are making any mistake here, just PL the VOSK API and put it into our device is all that needed, no need to use language models?

@nshmyrev

**Comment by nshmyrev** [comment]
@Taher0321 Vosk is not suitable for MCU and not designed for it as it doesn't have enough compute capabilities. If you describe your task better we can help you do decide the software. For example you can check https://github.com/ARM-software/ML-KWS-for-MCU

**Comment by Taher0321** [comment]
@nshmyrev https://www.techecies.com/nekosa - This what we are building. Let me know how we can implement vosk in it.

**Comment by Taher0321** [comment]
Hey, I am awaited for your response.

**Comment by nshmyrev** [comment]
Well, I think MCU has not enough compute capabilities for this task, you have to offload audio somewhere, at least on the phone. There are efficient recognizers for MCU, but they still limited for very small topic.

I know some people run Vosk on smart glasses, which is similar to your device, but they run full-scale Linux, not really and MCU.

**Comment by Taher0321** [comment]
Do you think this MCU will work:
https://robu.in/product/seeed-studio-xiao-esp32s3-sense-2-4ghz-wi-fi-ble-5-0-ov2640-camera-sensor-digital-microphone-battery-charge-supported-rich-interface-iot-embedded-ml/

I bet it will. What do you think?

**Comment by nshmyrev** [comment]
No. For AI you need something like https://www.mistywest.com/mistysom/

**Comment by Taher0321** [comment]
Thanks but its not helping. I think latest nvidia jetson chips may help, we are studying it

**Comment by nshmyrev** [comment]
Ok, let us know how it goes
