### ISSUE TITLE
How to deal with homonyms in grammer

### ISSUE THREAD

**Issue by MooWeii** [alphacep/vosk-api#1565]
I defined grammer, in which there are two homophonic Chinese characters "摆" and "百". Now there is a sentence with the correct format of "摆料等待时间修改为一百", but always return "百料等待时间修改为一百". It doesn't work if I add "摆料" to grammer, so what should I do

**Comment by nshmyrev** [comment]
Hi

You can improve language model to give more priority for correct word. See https://alphacephei.com/vosk/lm

**Comment by MooWeii** [comment]
> Hi
> 
> You can improve language model to give more priority for correct word. See https://alphacephei.com/vosk/lm

Thank you for your reply and contribution. In addition, where can I download the Chinese upgrade package. I see that the upgrade needs to download the upgrade package, but there is no Chinese link.

**Comment by nshmyrev** [comment]
You can request it over email

**Comment by nshmyrev** [comment]
Same as #866
