### ISSUE TITLE
Nodejs: undefined symbol: __cudaRegisterFatBinary

### ISSUE THREAD

**Issue by gormonn** [alphacep/vosk-api#157]
Hi!
When i'm trying to run `nodejs/example/test.js`:
```
node test.js
```
I get this error:
```
node: symbol lookup error: /home/dimon/vosk-api/nodejs/build/Release/vosk.node: undefined symbol: __cudaRegisterFatBinary
```

**Comment by nshmyrev** [comment]
recompile kaldi without cuda

**Comment by gormonn** [comment]
The fact is that I use CUDA. Does this mean that Vosk-api does not support Cuda?

I read somewhere in the comments that you doubt the appropriateness of using a GPU.
However, judging by the papers and [this](https://github.com/kaldi-asr/kaldi/issues/4042) comment, the NVidia V100 Tensor Core gives x240 acceleration.

What do you think about this?

**Comment by nshmyrev** [comment]
> However, judging by the papers and this comment, the NVidia V100 Tensor Core gives x240 acceleration.

The papers are about batch processing, not streaming processing like Vosk. Streaming GPU code is also fast, but not yet supported by vosk and still works in a batch mode, i.e. requires many streams merged in a batch chunks for online processing.

https://github.com/kaldi-asr/kaldi/pull/3568
