### ISSUE TITLE
Unable to Recognize Characters Properly in JAVA Vosk {   "text" : "�?�?��?�?�� �?�?���?���?�?" }

### ISSUE THREAD

**Issue by tegaatm** [alphacep/vosk-api#1571]
I've encountered an issue where characters are not being recognized properly in JAVA Vosk. Despite providing valid input, the output seems to be garbled or incorrect. This impacts the usability and reliability of the application.
{
  "text" : "�?�?��?�?�� �?�?���?���?�?"
}
![image](https://github.com/alphacep/vosk-api/assets/168930498/63b4ae66-3a55-4a1c-8977-ab55084c7aef)

**Comment by nshmyrev** [comment]
You have to set the codepage or you can redirect output to a file.

https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/1449 actually
