### ISSUE TITLE
Having problem importing EndpointerMode 

### ISSUE THREAD

**Issue by MarioIb14** [alphacep/vosk-api#1572]
I using the python version of Vosk. I am trying to import the EndpointerMode to change it for shorter commands. But I am continue to get this error when importing EndpointerMode (Using python 3.9.18) :"Error:cannot import name 'EndpointerMode' from 'vosk'" . I am using test_microphone.py example code plus EndpointerMode portion from test_ep.py example code.

**Comment by nshmyrev** [comment]
It is not yet pushed to pip I think

**Comment by MarioIb14** [comment]
How would I get it pushed to pip, I am not familiar with this issue? It seems I can import everything else like SetLogLevel and GpuInit. Also when I compared the __init__.py to one in GitHub it seems like older version because its missing the EndpointerMode portion of the code. Do you think it downloaded the wrong version ?

-------------------------------------------------------------------------------------------------------------------------
Looking over version of vosk I notice I have version 3.4.5 not 3.5.0. I uninstalled the old version and retried installing the new version but it keeps on installing the older one. I am using python version 3.9.18 and  pip version 23.3.1.
ERROR: Could not find a version that satisfies the requirement vosk==3.5 (from versions: 0.3.18, 0.3.21, 0.3.22, 0.3.27, 0.3.28, 0.3.29, 0.3.30, 0.3.31, 0.3.32, 0.3.38, 0.3.40, 0.3.41, 0.3.42, 0.3.44, 0.3.45)

**Comment by nshmyrev** [comment]
Same as #1622
