### ISSUE TITLE
Adding new words to Filipino model

### ISSUE THREAD

**Issue by moodpanda** [alphacep/vosk-api#1573]
just wanna ask if is it possible to use my dataset it is formatted like this
audio, transcription in csv file.

thanks for answering

**Comment by juliustuliao** [comment]
up same question

**Comment by nshmyrev** [comment]
This question is too vague for me to answer. If you need help you need to provide the details. What problem are you tryign to solve, what data do you have and so on.

**Comment by moodpanda** [comment]
I want the model to recognize new words or sentences using my own dataset. Currently, my dataset is formatted with each entry containing the path to an audio file and its corresponding transcription. I am new to Kaldi and unsure of how to properly format my data. inorder to perform model adaptation

my dataset example:
audio_file_path, transcription
data/chunk_001.wav, hello, world

**Comment by nshmyrev** [comment]
Vosk models are adapted with just text, not the audio + text.

What is the language of your dataset. What models did you try? What is the current accuracy of the model.

**Comment by moodpanda** [comment]
my dataset language is filipino and I'm trying to use model adaptation [vosk-model-tl-ph-generic-0.6](https://alphacephei.com/vosk/models/vosk-model-tl-ph-generic-0.6.zip) to add new words or sentence on the model vocabulary

**Comment by nshmyrev** [comment]
@moodpanda this model is precompiled and we can not modify it. You have to contact Fed directly for update, https://github.com/feddybear/flipside_ph only he can do it.

**Comment by moodpanda** [comment]
> @moodpanda this model is precompiled and we can not modify it. You have to contact Fed directly for update, https://github.com/feddybear/flipside_ph only he can do it.

got it thankyou very much I will try to email him if he still active thankyou

**Comment by nshmyrev** [comment]
He certainly can help you. Best.
