### ISSUE TITLE
Fine Tuning the en-us-0.22 model to specific commands (modify the grammar)

### ISSUE THREAD

**Issue by FaVe1996** [alphacep/vosk-api#1579]
My issue is that the re-training or fine-tuning documentation does not give a precise way on how to actually fine tune a model. I would like to fine tune my model so it can derive specific commands for my application. Therefore, I want to add and remove words. Furthermore, I want to use it as a dynamic model. Regarding this I have some some questions. 
1. Is fine-tuning possible? 
2. Which script should I use/edit ?
3. (e.g. when saying "blue engange tango one" I get as result "blue end gates tangled one") ~ Is there a way to change the recognition of this example?

**Comment by nshmyrev** [comment]
You can follow guide here:

https://alphacephei.com/vosk/lm

If you have more detailed question feel free to ask.

Same as #866
