### ISSUE TITLE
Error using vosk-model-en-us-daanzu-20200328-train.tar.gz model

### ISSUE THREAD

**Issue by murugeshmanthiramoorthi** [alphacep/vosk-api#158]
I am trying to use english daanzu model for my project. I downloaded the model and stored it in python/example folder as model. But when I run the test_simple.py, I get the following error.

ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError

Can someone help with this issue.

**Comment by murugeshmanthiramoorthi** [comment]
After installing, after converting the audio to mono 16000 bitrate, I used the following command.

python3 ./test_simple.py /content/vosk-api/python/example/myfile.wav 

This causes the error. 

I tried with vosk-model-en-us-aspire-0.2.zip model and it worked perfectly.

**Comment by nshmyrev** [comment]
You made a mistake arranging the files I supposes. You can use existing model https://github.com/daanzu/kaldi-active-grammar/releases/download/v1.4.0/vosk-model-en-us-daanzu-20200328.zip if you have problems with copying files.
