### ISSUE TITLE
Does VOSK Raspberry pi support zero 2W?

### ISSUE THREAD

**Issue by Dreamerandhardworker** [alphacep/vosk-api#1592]
I bought RPi zero. It took me a while to realize that vosk no longer supports it. The question is simple. Is vosk RPi zero 2 W supported? I know you recommend RPi 4, but it's too big for my task

**Comment by nshmyrev** [comment]
Speech recognition requires powerful CPU. Zero not going to work. We recommend Intel-based board actually, not even RIP4

**Comment by Dreamerandhardworker** [comment]
I used your VOSK library via Python on RPi 4. Everything worked more than very well. I only need to occasionally recognize phrases for 3-5 seconds. In addition, I have already rewritten the code in C. But I can't compile your library to RPi zero. Will I be able to compile/install your VOSK library via pip on RPi zero 2W, or will there be an error?
The 50 MB version of the neural network is used

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/918
