### ISSUE TITLE
Linux library for RPi

### ISSUE THREAD

**Issue by Dreamerandhardworker** [alphacep/vosk-api#1593]
I found ready-made compiled ones libgost.so for the C language libraries on Linux, but for x86 processors. Are there ready-made compiled libraries on Linux for ARM ?

**Comment by nshmyrev** [comment]
https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-linux-armv7l-0.3.45.zip

https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-linux-aarch64-0.3.45.zip

**Comment by nshmyrev** [comment]
Let us know if you have other questions
