### ISSUE TITLE
ngram_order in language model  

### ISSUE THREAD

**Issue by YangangCao** [alphacep/vosk-api#1594]
Hi, Dear author,

I want to improve the accuracy grammar ASR, so I  set ngram_order to 3 in language model , but appear this:
`ASSERTION_FAILED (VoskAPI:AssignFstStates():language_model.cc:137) Assertion failed: (current_fst_state == num_active_lm_states_)
`
Any idea to set more than 2 ngram_order?
Thanks very much!

**Comment by nshmyrev** [comment]
Please clarify in more details what exact changes have you made. Is it to grammar code?

**Comment by YangangCao** [comment]
I only change opts.ngram_order from 2 to 3 in LanguageModelOptions in recognize.cc

**Comment by nshmyrev** [comment]
I pushed the fix for your problem here in commit cc48ff95672f9a04d5ec7afcc4bcab5f70305c1d
