### ISSUE TITLE
any script that dumps vosk outputs to a file?

### ISSUE THREAD

**Issue by zenny** [alphacep/vosk-api#160]
Hi,

Great work. Is there any scripts that dumps vosk outputs to a file?

Thanks and cheers,
/z

**Comment by ManuKulamkombil** [comment]
Is this what you are referring to - https://softwarerecs.stackexchange.com/a/74789 ?

**Comment by zenny** [comment]
> Is this what you are referring to - https://softwarerecs.stackexchange.com/a/74789 ?

Thanks @ManuKulamkombil. Can this be used live (means concurrently) while speaking which get transcribed to text automatically for dictation?

**Comment by nshmyrev** [comment]
Should be solved in #727
