### ISSUE TITLE
SpeakerModel on Android

### ISSUE THREAD

**Issue by andreystarenky** [alphacep/vosk-api#1602]
Hi, how do I unpack the SpeakerModel on Android? The StorageService.unpack() method (used for the regular model) returns a Model not SpeakerModel object.

Is there any documentation or examples for this? The vosk-android-demo doesn't implement the SpeakerModel anywhere that I can see.

**Comment by andreystarenky** [comment]
I made a method to unpack SpeakerModel, and it looks like it worked. But when I pass the SpeakerModel to the Recognizer object it doesn't return anything about speaker vector/signature in the hypothesis.

**Comment by andreystarenky** [comment]
I figured out the issue: when SetAlternatives(n) is used, it disables the SpeakerModel functionality. It also disables SetWords which is annoying but I am not sure if this is intentional or limited by kaldi model framework.

**Comment by nshmyrev** [comment]
It is good you figured things out. Overall speaker issues tracked in https://github.com/alphacep/vosk-api/issues/405

**Comment by Cui0526** [comment]
I developed a method to decompress SpeakerModel, and it appears to have been successful. However, when I provide the SpeakerModel to the Recognizer object, it doesn't yield any information regarding the speaker vector or signature in the hypothesis.
Can you share the code  please
