### ISSUE TITLE
Missing Documentation Reference

### ISSUE THREAD

**Issue by Tristan-Peters** [alphacep/vosk-api#1605]
The documentation on _https://alphacephei.com/vosk/android_ directs to look at _https://github.com/alphacep/vosk-api/blob/master/doc/adapation.md_ for documentation on updating the grammar / acoustic model, but the adapation.md file does not exist.

readme.md directs users to documentation on https://alphacephei.com/vosk

**Comment by nshmyrev** [comment]
I fixed the link, thank you for the report!
