### ISSUE TITLE
Regarding speaker recognition

### ISSUE THREAD

**Issue by maliqin** [alphacep/vosk-api#1611]
I used two audio clips from the same person and obtained some vectors, as shown below. How can I determine if these two vectors are from the same speaker using C#?
![屏幕截图 2024-07-12 103751](https://github.com/user-attachments/assets/e86b74e5-30de-4d4b-a1dd-e5a71c17d6f3)
thank you ！

**Comment by nshmyrev** [comment]
Compute cosine distance and compare to threshold. 

Same as #405

**Comment by maliqin** [comment]
The two sentences output a total of 7 vectors. The first sentence outputs 3 vectors, and the second sentence outputs 4 vectors. I am unsure which two vectors to use for comparison. Thank you very much for your help

**Comment by maliqin** [comment]
The two sentences output a total of 7 vectors. The first sentence outputs 3 vectors, and the second sentence outputs 4 vectors. I am unsure which two vectors to use for compute cosine distance. Thank you very much for your help @nshmyrev
