### ISSUE TITLE
where is libvosk.so?

### ISSUE THREAD

**Issue by 40476** [alphacep/vosk-api#1615]
could somebody point me towards where libvosk.so is for x86? (thank you)

**Comment by nshmyrev** [comment]
https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-linux-x86-0.3.45.zip

https://github.com/alphacep/vosk-api/releases/v0.3.45

**Comment by 40476** [comment]
thanks!

I am trying to make a program that takes what i say and sends it back out at me through `espeak-ng`!

**Comment by 40476** [comment]
when i run it, it says:
```
wrong ELF class: ELFCLASS32
```

What part am I doing wrong?

**Comment by 40476** [comment]
that is a 32 bit library. 
```
sprec: error while loading shared libraries: libvosk.so: wrong ELF class: ELFCLASS32
```

this is where i found out that this is a thing that happens
https://askubuntu.com/questions/398929/unable-to-load-shared-object-wrong-elf-class-elfclass32

**Comment by nshmyrev** [comment]
There is another one which is 64 bit in the same release. You asked for x86 originally

**Comment by 40476** [comment]
My fault, I had thought that x86 was the same thing as x86_64, feel free to close this issue.On Aug 9, 2024, at 7:22 PM, Nickolay V. Shmyrev ***@***.***> wrote:﻿
There is another one which is 64 bit in the same release. You asked for x86 originally

**Comment by nshmyrev** [comment]
Ok, let us know if you have other questions.

**Comment by 40476** [comment]
👍On Aug 10, 2024, at 9:58 AM, Nickolay V. Shmyrev ***@***.***> wrote:﻿
Ok, let us know if you have other questions.

**Comment by 40476** [comment]
Yes, that reminds me, in order to add custom words, do I need to retrain the model, or is there a way to do that?On Aug 10, 2024, at 9:58 AM, Nickolay V. Shmyrev ***@***.***> wrote:﻿
Ok, let us know if you have other questions.
