### ISSUE TITLE
Java example is Missing or is not too easy to find

### ISSUE THREAD

**Issue by JoaoPedroFortes** [alphacep/vosk-api#1621]
I'm trying to implement a solution using Java, but the only example that I found was that: 
[https://github.com/linto-ai/linto-vosk-api/blob/6d60a20a237bc5df0ebbf5689243360a4334aab7/java/demo/src/main/java/org/vosk/demo/DecoderDemo.java](url) 

I'm trying to use VoiceReconizer with a Portuguese model, but until now, I only recovered a few words  and don't know how to configure the recognizer to get a better accuracy. 

I don't understood how to use the "setPartialWords", "setGrammar" or "setMaxAlternatives" methods to get a better result.

Thanks in advance

**Comment by nshmyrev** [comment]
Hi. 

Our demo is here, not on Linto

https://github.com/alphacep/vosk-api/blob/master/java/demo/src/main/java/org/vosk/demo/DecoderDemo.java

As for few words, the biggest source of trouble is wrong file format. Make sure your audio is 16khz 16bit mono. 

If you still have troubles with the accuracy share the problematic file.

**Comment by JoaoPedroFortes** [comment]
Hi, Nickolay.

Thanks for reply. I'll check my record method and try again.

**Comment by nshmyrev** [comment]
Let us know how it goes.

**Comment by JoaoPedroFortes** [comment]
I changed my audioFormat setting to
`private static final AudioFormat FORMAT = new AudioFormat(16000.0F, 16, 1, true, false);`

and now it's working

Thank you very much
