### ISSUE TITLE
Rebuilding repository.

### ISSUE THREAD

**Issue by YangangCao** [alphacep/vosk-api#1624]
Hi, deat author, I encouter this warning when processing music noise or some bad audio clips. this warning will stuck the programe for a long time, are there any idea to avoid it? I don't care ASR result (becasue usually the result is bad, I have to give up it), and I need stream processing and speed, only care how to skip the warning. I read some other issue, but don't find the solutions

```
LOG (VoskAPI:RebuildRepository():determinize-lattice-pruned.cc:283) Rebuilding repository.
WARNING (VoskAPI:CheckMemoryUsage():determinize-lattice-pruned.cc:316) Did not reach requested beam in determinize-lattice: size exceeds maximum 50000000 bytes; (repo,arcs,elems) = (26463104,514528,23040336), after rebuilding, repo size was 16992416, effective beam was 5.81556 vs. requested beam 6
WARNING (VoskAPI:OutputArcForce():word-align-lattice.cc:594) Discarding word-ids at the end of a sentence, that don't have alignments.
```

**Comment by nshmyrev** [comment]
Ignore it, it is expected

Same as https://github.com/alphacep/vosk-api/issues/1127
