### ISSUE TITLE
Voice recognition stops recognizing after several seconds of silence on Android Emulator

### ISSUE THREAD

**Issue by rokij6698** [alphacep/vosk-api#1629]
I am programming a React Native mobile app, and I want the Vosk voice recognition to continue listening without stopping, even after long periods of silence. Although the microphone's green dot remains on, the voice recognition stops working. I have tried editing mfcc.conf and model.conf and adjusting settings like --endpoint.silence-phones and min-trailing-silence, but these changes haven’t prevented the voice recognition from stopping after silence and failing to resume when speaking into the microphone. I’ve also attempted to modify the React Native code, but it still doesn't resolve the issue.

Is there a way to configure the voice recognition to keep listening, allowing the user to activate the microphone, speak, remain silent for a few minutes, and then come back and continue speaking to the microphone?

Thank you.

**Comment by rokij6698** [comment]
It works on the real device, but not the emulator. Solved

**Comment by nshmyrev** [comment]
Yeah, we figured that out. Thanks!
