### ISSUE TITLE
how build vosk for Orange PI4 with armv8

### ISSUE THREAD

**Issue by AlexRodch** [alphacep/vosk-api#163]

**Comment by AlexRodch** [comment]
pip3 install vosk not work...
OS Armbian Focal 5.4.49.
build from source kaldi 
ImportError: /root/.local/lib/python3.8/site-packages/vosk/_vosk.cpython-38-aarch64-linux-gnu.so: invalid ELF header

**Comment by Aculeasis** [comment]
`pip3 install https://github.com/alphacep/vosk-api/releases/download/0.3.10/vosk-0.3.10-cp38-cp38-linux_aarch64.whl` must work.

**Comment by AlexRodch** [comment]
thanks )
build success and vosk work

**Comment by nshmyrev** [comment]
It is mentioned in readme. Let us know if you need further help!
