### ISSUE TITLE
Alpine Linux/ARMv7/32 bit/rpi 2b/ Unable to import Vosk: libvosk.so error

### ISSUE THREAD

**Issue by sunwaterdev** [alphacep/vosk-api#1633]
Hello,
I installed Vosk with pip on Alpine Linux, in a raspberry pi 2b, for prototyping, and when I import I have this error:

(xxxx) xxxx:~/xxxx# ./xxxx.sh
Traceback (most recent call last):
File "/root/xxxx/xxxx/core.py", line 16, in <module>
import vosk
File "/root/xxxx/lib/python3.12/site-packages/vosk/__init__.py", line 36, in <module>
_c = open_dll()
^^^^^^^^^^
File "/root/xxxx/lib/python3.12/site-packages/vosk/__init__.py", line 30, in open_dll
return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library '/root/xxxx/lib/python3.12/site-packages/vosk/libvosk.so': Error relocating /root/xxxxx/lib/python3.12/site-packages/vosk/libvosk.so: backtrace_symbols: symbol not found

So I reinstalled Vosk, cffi, the problem does not change. I am in a virtual environment where the file exists.

Thanks in advance for your answers/fix

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/509

Alpine Linux requires special build

**Comment by sunwaterdev** [comment]
Where can I get the instructions to import Vosk? Beacause as I read, the user get problem for installing, me, i've problem to import the vosk module.

**Comment by nshmyrev** [comment]
Vosk is not going to work on RPI2B anyway, minimum is RPI3B+, better RPI4. Don't spend much time on that.
