### ISSUE TITLE
Issue with SetMaxAlternatives Affecting Speaker Vectors in Recognition Results

### ISSUE THREAD

**Issue by SorooshGb** [alphacep/vosk-api#1647]
When using the following code:
```
rec = KaldiRecognizer(model, args.samplerate)
rec.SetSpkModel(spk_model)
rec.SetMaxAlternatives(4)
```
If I don't use SetMaxAlternatives, the recognizer's result includes speaker vectors (spk property) for each utterance as expected.
However, as soon as I call rec.SetMaxAlternatives, the spk property with the speaker vector values disappears from the recognition result.

Tested Scenarios:
- Using the test_speaker.py example
- Using the microphone.py example

I also tested this on a Raspberry Pi running Vosk with the C API, using the vosk_recognizer_set_max_alternatives method. The same issue occurred: speaker vectors were no longer included in the results.

**Comment by nshmyrev** [comment]
It should be fixed now, will be in the next release.
