### ISSUE TITLE
How to use additional models?

### ISSUE THREAD

**Issue by mcondarelli** [alphacep/vosk-api#1649]
Sorry for the stupid question, I was unable to find the answer myself.

I am trying to use `vosk` and testing using `vosk-api/python/example/test_microphone.py`.

It seems to work well with English (default) and Italian (`-m it`) but it fails with Greek (`-m el`) with the following error:
```
mcon@cinderella:~/prove/FlashCube$ venv/bin/python t5.py -d 9 -m el
lang el does not exist
Exception ignored in: <function Model.__del__ at 0x7fe63da60e00>
Traceback (most recent call last):
  File "/home/mcon/prove/FlashCube/venv/lib/python3.12/site-packages/vosk/__init__.py", line 60, in __del__
    _c.vosk_model_free(self._handle)
                       ^^^^^^^^^^^^
AttributeError: 'Model' object has no attribute '_handle'
```
It seems to me the model is missing from bundled `libvosk.so`.
I downloaded `vosk-model-el-gr-0.7.zip` but I have two problems here:
1. this seems a "large model" and I was unable to find a similar `vosk-model-small-el-gr-0.7.zip`
2. I have no clue where I should unpack it (I didn't find the other models either `libvosk.so` is too small to hold them inside).

Can someone point me in the right direction?
Many Thanks in Advance
Mauro

**Comment by nshmyrev** [comment]
> this seems a "large model" and I was unable to find a similar vosk-model-small-el-gr-0.7.zip

We never trained it

> I have no clue where I should unpack it (I didn't find the other models either libvosk.so is too small to hold them inside).

You can unpack it anywhere and load from that path. Or you can load by model name. Models are in $HOME/.cache/vosk usually

**Comment by mcondarelli** [comment]
Thanks.
It is working now.
Is there any hope to get a `...-small-el...`?
BTW: this doesn't seem to be very accurate, but Greek is not my mother tongue so it could be my poor pronunciation.

**Comment by nshmyrev** [comment]
Our Greek model is pretty basic and not accurate at all, needs more work. Hopefully one time we will find practical case to work on it.
