### ISSUE TITLE
Adding words to the model built from existing Phones

### ISSUE THREAD

**Issue by communig8-public** [alphacep/vosk-api#165]
I realise this is not an issue with the demo but I'm trying to find a relatively simple method of doing this as I'm VERY new to ASR. The model included with the demo App contains over 67,000 words but obviously does not include words that could be domain specific such as a product name constructed by someone from a marketing background such as "flyble" (perhaps a new airline). However, it is "constructed" from two Phones "fly" as in fly and "bl" as in able. I assume that these Phones exist in the model in some way.

So is it possible to update the model in some simple way, using data already in the models folder, to get it to recognise "flyble" as a word and if so, how?

Thank your, Richard

**Comment by nshmyrev** [comment]
The overall process is described here:

https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/

we haven't yet automated it fully, maybe we will automate it later so you will be able to compile graphs quickly with simply python API.

**Comment by communig8-public** [comment]
Thanks. I have seen that. I could be wrong, being so new to this but that looked as if it was specific to the Aspire Model and needed all the original data that goes to build the model. Not just the model that is part of the vosk-android-demo App.

**Comment by nshmyrev** [comment]
Yes, it is not fully automated. You can check the scripts inside https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz for example on how to compile graph for android model.

**Comment by communig8-public** [comment]
OK, I've been through the rather lengthy process of downloading and building all the various packages listed in the INSTALL files and the ones that are not mentioned, so I could get to the stage of compiling the graph for the Android App without any changes for the word I want to add. I expected to end up with a set of files that matched the set in the Android App's model's Graph folder but they are not the same. e.g. words.txt in the Android App is 968KB in size but the compiled one is only 77KB, so far fewer words. Plus there are other files created that don't existing the Android App.

How can I get to the point of creating the set of files exactly as it is in the App?
Also, how do I actually create my new word from the two Phones that I want?

**Comment by communig8-public** [comment]
An update, the new set of files still works in the App.
And I figured out how to create my own limited list of words with a new one in the list constructed from existing Phones.
So all done and ok now thanks.
