### ISSUE TITLE
Question: Is it possible to share VoskModel between threads?

### ISSUE THREAD

**Issue by dibalavs** [alphacep/vosk-api#1651]
Hello, 
I try to use vosk recognizer in my voice assistant.  For this task I have 10 microphones in 10 rooms and 1 PC which handle all streams,

Currently I use separate processes to recognize separate microphone streams. But it requires large memory amount, because model is more than 200mb.

Is it possible to handle all streams in one process in separate threads  with sharing 1 instance of VoskModel between all threads?

```
    model = VoskModel(lang="ru")
    recognizer = KaldiRecognizer(model, cfg.MIC_FRAME_RATE)
    for r in range(1,10):
      init_room_worker_thread(r, model, recognizer)
```

???

**Comment by nshmyrev** [comment]
Yes, sure. That is what server is doing. 

You have to create recognizer inside the thread though, you can only share the model. Recognizer is lightweight.

**Comment by dibalavs** [comment]
Thank you!
