### ISSUE TITLE
PyPi version out of date, example not working

### ISSUE THREAD

**Issue by studiostephe** [alphacep/vosk-api#1656]
I was trying to adjust EndpointerMode as seen in the example at:
https://github.com/alphacep/vosk-api/blob/master/python/example/test_ep.py

but it failed with:
AttributeError: 'KaldiRecognizer' object has no attribute 'SetEndpointerMode'

I looked into what vosk version I have and discovered that pip installs version 0.3.45. The release notes for 0.3.50 say "Endpointer config updates" so I assume that's all I need. 

As you state in your docs, "compilation is not straightforward and includes several nuances," so it would be great to have an easy way to install the latest version on my raspberry pi 5.

Thank you for all your work!

**Comment by nshmyrev** [comment]
Basically same as https://github.com/alphacep/vosk-api/issues/1622

We need to release 0.3.50 one day. Thanks

**Comment by route250** [comment]
I am eagerly looking forward to the release of Vosk 0.3.50 on PyPI. Currently, in streaming applications, Vosk often proves to be more useful than Whisper, and the inclusion of SetEndpointerMode would undoubtedly be highly beneficial.

**Comment by dany171** [comment]
Same for me looking for version 0.3.50 
hopefully you can push it soon :)
