### ISSUE TITLE
How to rebuild a language model and why it is necessary

### ISSUE THREAD

**Issue by Sasaki303** [alphacep/vosk-api#1667]
We would like to add vocabulary to our small Japanese model to be able to recognize specific names, but we are having trouble creating a successful custom dictionary.
First, I added the words I want to register to words.txt. (For example, for “nasas”, I added “nasas 400000”)
Then I added the vocabulary I want to add as text.txt. (For example, for “nasas”, I added “nasas n_B a_I s_I a_I s_I u_E”)
In phones.txt, we added “...,m_B 115,m_E 116,m_I 117,...” and is registered as “m_B 115,m_E 116,m_I 117,...”.
So, if I run “farcompilestrings --fst_type=compact --symbols=words.txt --keep_symbols text.txt > text.far” in WSL,
ERROR: ConvertSymbolToLabel: Symbol “n_B” is not mapped to any integer label, symbol table = words.txt
FATAL: FarCompileStrings: Compiling string number 1 in file text.txt failed with token_type = symbol and entry_type = line”
is displayed.
Am I doing something wrong to begin with? Can you please tell me how best to add vocabulary to the Japanese model?
If I want to add a specific person's name that is not in the language model, do I need to rebuild the model?
Please let us know.
Thank you in advance.
(This message is using DeepL translation)

**Comment by nshmyrev** [comment]
You need to request update package from us, mail contact@alphacephei.com, we can add it for you. See also https://alphacephei.com/vosk/lm

**Comment by Sasaki303** [comment]
Since I was going to deal with personal information, I was thinking of creating a local dictionary to recognize it, but is that too demanding?

**Comment by nshmyrev** [comment]
You don't have to share your information, you can rebuild locally once you have the update package

**Comment by nshmyrev** [comment]
Same as #1687
