### ISSUE TITLE
Creating the model.conf file

### ISSUE THREAD

**Issue by jen-co** [alphacep/vosk-api#167]
Hi,

Thank you for such an awesome library and all the documentation so far! 

I followed this [tutorial](https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/) for customisation and got it working with kaldi but I want to now integrate the new models and other files to get it running with vosk-api. 

I copied the relevant files across as detailed in the "Model Structure" section [here](https://alphacephei.com/vosk/models) but it one thing that is not clear to me is this sentence for the conf/model.conf file - "provide default decoding beams and silence phones. you have to create this file yourself, it is not present in kaldi model'. How does one do this? Is there any documentation for this?

Thanks again!
Jennifer

**Comment by nshmyrev** [comment]
You simply copy it from existing model and update the values

**Comment by jen-co** [comment]
Thanks! How do you update the values though?

**Comment by jen-co** [comment]
oh nevermind I see that it is simply a text editable document!

**Comment by HubKing** [comment]
> 
> 
> You simply copy it from existing model and update the values

What if I cannot find the existing one? In the models page ( https://alphacephei.com/vosk/models ), I downloaded "[fr-pguyot-zamia-20191016-tdnn_f](https://github.com/pguyot/zamia-speech/releases/download/20190930/kaldi-generic-fr-tdnn_f-r20191016.tar.xz)", but it has no "model.conf" in it. The models page says nothing but "you have to create this file yourself", but I don't know anything about voice recognition and I just want to use existing software as it is.

**Comment by nshmyrev** [comment]
You can find the model.conf inside this one:

https://alphacephei.com/vosk/models/vosk-model-de-0.6.zip

we will slowly update all the models to respect this new layout, fr is not just updated yet.
