### ISSUE TITLE
 Application Crash Due to std::bad_alloc Exception After Prolonged Use

### ISSUE THREAD

**Issue by alokkumarathava** [alphacep/vosk-api#1675]
My Android application is experiencing a crash after extended usage, triggered by a **std::bad_alloc** exception. The crash occurs during the loading of the Vosk speech recognition model, as indicated by the following log excerpt:

```
ReadDataFiles():model.cc:249) Loading i-vector extractor from /storage/emulated/0/Android/data/com.globaldws.trinityvillage_social_application/files/model/model-en-us/ivector/final.ie
ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
ComputeDerivedVars():ivector-extractor.cc:204) Done.
ReadDataFiles():model.cc:285) Loading HCL and G from /storage/emulated/0/Android/data/com.globaldws.trinityvillage_social_application/files/model/model-en-us/graph/HCLr.fst /storage/emulated/0/Android/data/com.globaldws.trinityvillage_social_application/files/model/model-en-us/graph/Gr.fst
/buildbot/src/android/ndk-release-r23/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed
Fatal signal 6 (SIGABRT), code -6 in tid 26369 (pool-32-thread-)
pid: 22228, tid: 26369, name: pool-32-thread-  >>> com.globaldws.trinityvillage_social_application <<<
    #07 pc 005096bf  /data/app/com.globaldws.trinityvillage_social_application-1/base.apk (offset 0x3d1c000)
[Application Error: com.globaldws.trinityvillage_social_application] connect: already connected (cur=1 req=1)
channel 'caa570 com.globaldws.trinityvillage_social_application/com.globaldws.trinityvillage_social_application.ui.homescreen.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Steps to Reproduce:**
1. Launch the application.
2. Utilize the Vosk speech recognition feature over an extended period.
3. Observe the application crash during the model loading process.

**Observed Behavior:**
After prolonged use, the application crashes with a std::bad_alloc exception, indicating a failure to allocate memory during the loading of the Vosk model.

**Expected Behavior**
The application should manage memory effectively to prevent crashes, ensuring stable operation of the speech recognition feature even after extended use.

**Additional Information**
This issue resembles a previously reported problem in the Vosk Android demo, where a std::bad_alloc exception occurred due to insufficient memory allocation for large models, but I am using the smallest model of 40 MB size.

**Request for Assistance:**
We seek guidance on optimizing memory usage during the Vosk model loading process to prevent **std::bad_alloc** exceptions. Specifically, we would appreciate recommendations on:

- Reducing the memory footprint of the Vosk model.
- Implementing efficient memory management practices during model initialization.
- Identifying and addressing potential memory leaks related to the Vosk integration.

**Comment by nshmyrev** [comment]
What is the amount of memory you have on system? Is it taken by some other app?

**Comment by alokkumarathava** [comment]
My device has 2 GB of memory, as I am monitoring application consumes near to about 400MB, and I have force stopped other applications and services.

**Comment by nshmyrev** [comment]
Ok, it is same as

https://github.com/alphacep/vosk-android-demo/issues/121

I need to look closer one day.

**Comment by alokkumarathava** [comment]
Thank you
