### ISSUE TITLE
Missing libvosk.a File in iOS Demo Project

### ISSUE THREAD

**Issue by EswarSatti** [alphacep/vosk-api#1679]
The iOS demo project for Vosk is missing the libvosk.a file. Attempting to build the project results in a "ld: library not found for -lvosk" error. There is no guidance in the README about obtaining or generating this file.

The demo project should either include the libvosk.a file or please provide clear instructions for generating or downloading it.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/45. You have to request it by email.
