### ISSUE TITLE
Error looking up function 'vosk_recognizer_set_grm': dlsym(0x47ef2670, vosk_recognizer_set_grm): symbol not found

### ISSUE THREAD

**Issue by huifer** [alphacep/vosk-api#1682]
Java Version 

```
openjdk version "23.0.1" 2024-10-15
OpenJDK Runtime Environment (build 23.0.1+11-39)
OpenJDK 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)

```

dependency

```
        <dependency>
            <groupId>com.alphacephei</groupId>
            <artifactId>vosk</artifactId>
            <version>0.3.45</version>
        </dependency>

```

jar content 

![image](https://github.com/user-attachments/assets/fd08dd25-3713-49ba-ab1f-8c56c844ac44)

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/1622, we didn't release new version yet

**Comment by huifer** [comment]
@nshmyrev  I am using 0.3.45, which is not a new version. Do I need to wait for the new version to be released?

**Comment by nshmyrev** [comment]
Yes please, hope to release it soon. It is a new API.

**Comment by ljucas10** [comment]
need new api~
