### ISSUE TITLE
can not build vosk-api\src file on linux

### ISSUE THREAD

**Issue by dfengpo** [alphacep/vosk-api#1685]
![image](https://github.com/user-attachments/assets/ab66d0c7-b0f7-4937-936f-3b8f382a210c)

**Comment by nshmyrev** [comment]
KALDI_ROOT is not correct, you have to specify it in makefile, by default you expect to have kaldi in $HOME/travis/kaldi

https://github.com/alphacep/vosk-api/blob/master/src/Makefile#L2

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/193
