### ISSUE TITLE
How to use vosk-model-spk-0.4 model

### ISSUE THREAD

**Issue by dfengpo** [alphacep/vosk-api#1686]
I use  vosk-model-cn-0.22 and vosk-model-spk-0.4 model to get speaker recognition result.
but I get this result like this:
![image](https://github.com/user-attachments/assets/638174a0-0181-43c7-95ff-f7badee62f1b)

What does "spk"  and "spk_frames" : 1140 means?
How to get speaker recognition id like 
speaker1
speaker2
speaker3
speaker1

**Comment by nshmyrev** [comment]
spk_frames is number of frames used to estimate the speaker. Spk is speaker fingerprint (xvector). Read more about xvector please.

See also here https://github.com/alphacep/vosk-api/issues/405
