### ISSUE TITLE
Golang uses the official website demo

### ISSUE THREAD

**Issue by shrkx** [alphacep/vosk-api#1688]
I used the example of golang on the official website
![1734573335787](https://github.com/user-attachments/assets/debe31b0-37c7-48ee-ada2-8085657a25c0)
![1734573394151](https://github.com/user-attachments/assets/2d69a0c9-6416-4dbd-9d20-368ed0b72abd)
The environment is also configured, but there are still errors

**Comment by nshmyrev** [comment]
Same as here:

https://github.com/alphacep/vosk-api/issues/816

You need to download and unpack vosk library before you compile. See also

https://github.com/alphacep/vosk-api/issues/672

**Comment by shrkx** [comment]
Have you implemented it using Golang on the Windows system ,I have installed gcc

# github.com/alphacep/vosk-api/go
..\..\..\pkg\mod\github.com\alphacep\vosk-api\go@v0.3.50\vosk.go:7:11: fatal error: vosk_api.h: No such file or directory
    7 | // #include <vosk_api.h>
      |           ^~~~~~~~~~~~
compilation terminated.

![1734578501582](https://github.com/user-attachments/assets/b0d7588b-5e71-4744-9281-7e6ff6945bbf)

**Comment by nshmyrev** [comment]
vosk library must be in ../src as in CGO arguments, not in the current folder. Or you have to add "-I." to load from the current folder.

**Comment by nshmyrev** [comment]
Or you have to replace VOSK_PATH with the actual absolute path.
