### ISSUE TITLE
Decoding performance difference between different CPU

### ISSUE THREAD

**Issue by hungnvk54** [alphacep/vosk-api#169]
Hi @nshmyrev 
I have installed the vosk-api and websocket server on docker. using ubuntu 16.04.

Server 1: 
- CPU - Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
- RAM: 64G

Server 2:
- CPU Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
- RAM: 32G

Both server running same docker image.

To decoding 10 minutes audio using VOSK API, It takes:
- Server 1: 4 minutes
- Server 2: 2.5 minutes

To decoding 10 minutes audio using online2-tcp-nnet3-decode-faster, It takes:
- Server 1: 2.2 minutes
- Server 2: 2.3 minutes

Both of Vosk api and online2-tcp-nnet3-decode-faster have same configuration (beam-size, ivector, ...)

Do you have experience about this case?

**Comment by nshmyrev** [comment]
You probably use mkl as math library in the second case.

**Comment by hungnvk54** [comment]
> You probably use mkl as math library in the second case.

Yes. You are right. I use docker file from the kaldi repos and mkl using as default math library.

But in second case, why decoding time on two server have big diffrent while it using same math library (same version)?

**Comment by nshmyrev** [comment]
It mostly depends on memory cache bottleneck. Xeon has bigger cache so it is faster. You can see much bigger effect with multiple streams processed in parallel.

**Comment by hungnvk54** [comment]
Oh no. In this case, The xeon server take more time than Core I server.

**Comment by hungnvk54** [comment]
After inspect and try other docker image, I found that:

-  Debian 10 + mkl or openblas => Good performance
- Ubuntu 18.04 + mkl ==> When running decoding, This process occupy full 23 thread/64 thread CPU even if we decode one audio stream.
- Ubuntu 18.04 + openblas => Bad Performance on Xeon CPU (Decoding time slower than two times CORE i7 )

And i will close this issues by using Debian 10 + mkl like your docker in vosk-server

**Comment by nshmyrev** [comment]
> Ubuntu 18.04 + openblas => Bad Performance on Xeon CPU (Decoding time slower than two times CORE i7 )

This is interesting. Is it a recent build with openblas CPU multiarch or older one please?

**Comment by vonguyen1982** [comment]
@nshmyrev I am quite new to this vosk. I wonder I am using I am using vosk api nuget running in docker linux container. How do I set the math library?
I have a test with big model and it took 60s to transcribe 2.30 mins audio and it is using only 1 core. Any tip to make it faster and using all cores etc.
Thanks
