### ISSUE TITLE
I need a Hungarian Speech-To-Text solution from Vosk.

### ISSUE THREAD

**Issue by agu5a** [alphacep/vosk-api#1692]
I use python actively with AI based on open source pythin libs. 
So far I tried models like 'openai/whisper-large-v2', 'jonatasgrosman/wav2vec2-large-xlsr-53-hungarian', 'sarpba/whisper-base-hungarian_v1' but they misunderstood words a lot.

Please helm ;)

**Comment by nshmyrev** [comment]
This is same as #1626, lets continue there

**Comment by nshmyrev** [comment]
@agu5a good language support requires some effort. If you have some practical need, let us know.
