### ISSUE TITLE
vosk-api python module build error

### ISSUE THREAD

**Issue by meusername** [alphacep/vosk-api#17]
Hi.
While trying python3 setup.py install 

[ 40%] Building CXX object CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o
/usr/bin/c++  -D_vosk_EXPORTS -I/opt/vosk/vosk-api/python/../src -I/opt/vosk/kaldi/src -I/opt/vosk/kaldi/tools/openfst/include -I/usr/include/python3.5m  -O3 -DFST_NO_DYNAMIC_LINKING -std=c++11  -O3 -DNDEBUG -fPIC   -o CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o -c /opt/vosk/vosk-api/python/build/temp.linux-x86_64-3.5/voskPYTHON_wrap.cxx
In file included from /opt/vosk/vosk-api/python/build/temp.linux-x86_64-3.5/voskPYTHON_wrap.cxx:3119:0:
/opt/vosk/vosk-api/python/../src/kaldi_recognizer.h:35:14: error: ‘LookaheadFst’ in namespace ‘fst’ does not name a template type
         fst::LookaheadFst<fst::StdArc, int32> *decode_fst_;
              ^~~~~~~~~~~~
CMakeFiles/_vosk.dir/build.make:62: recipe for target 'CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o' failed
make[3]: *** [CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o] Error 1
make[3]: Leaving directory '/opt/vosk/vosk-api/python/build/temp.linux-x86_64-3.5'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/_vosk.dir/all' failed
make[2]: *** [CMakeFiles/_vosk.dir/all] Error 2
make[2]: Leaving directory '/opt/vosk/vosk-api/python/build/temp.linux-x86_64-3.5'
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/_vosk.dir/rule' failed
make[1]: *** [CMakeFiles/_vosk.dir/rule] Error 2
make[1]: Leaving directory '/opt/vosk/vosk-api/python/build/temp.linux-x86_64-3.5'
Makefile:131: recipe for target '_vosk' failed
make: *** [_vosk] Error 2

**Comment by nshmyrev** [comment]
It doesn't seem you have Kaldi build from our branch. Follow the instructions in README if you want to build from source:

https://github.com/alphacep/vosk-api#python-module-build

**Comment by meusername** [comment]
Thank's for answer.
The same error.

I clone git repo to /opt/vosk/kaldi and make tools and src with succes. Then i clone vosk-api to /opt/vosk/vosk-api (directory python does not exist in kaldi repo and "cd python" is impossible), set the KALDI_ROOT to /opt/vosk/kaldi, change dir to /opt/vosk/vosk-api/python and try to run "pyton3 setup.py install".

As result i have error.

/opt/vosk/vosk-api/python/../src/kaldi_recognizer.h:35:14: error: ‘LookaheadFst’ in namespace ‘fst’ does not name a template type
fst::LookaheadFst<fst::StdArc, int32> *decode_fst;
^~~~~~~~~~~~
CMakeFiles/_vosk.dir/build.make:62: recipe for target 'CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o' failed

Debian GNU/Linux 9
Python 3.5.3

**Comment by nshmyrev** [comment]
You can type `git status && git remote -v` inside kaldi folder and paste here.

**Comment by meusername** [comment]
git status && git remote -v
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        tools/OpenBLAS-0.3.7.tar.gz

nothing added to commit but untracked files present (use "git add" to track)
origin  https://github.com/alphacep/kaldi.git (fetch)
origin  https://github.com/alphacep/kaldi.git (push)

**Comment by nshmyrev** [comment]
You need to checkout lookahead branch with `git checkout lookahead` as instruction says.

**Comment by meusername** [comment]
Great! Now that error did goes away.
Thank's alot.

**Comment by nshmyrev** [comment]
Ok, it is the same as #7
