### ISSUE TITLE
Do I have to build the thing called KALDI?

### ISSUE THREAD

**Issue by HubKing** [alphacep/vosk-api#170]
> The easiest way to install vosk api is with pip. **You do not have to compile anything.**

I executed pip3 install vosk, but when I ran setup.py, I got "Define KALDI_ROOT". What does that mean; do I have to compile KALDI? But the documentation said I don't have to compile anything...

**Comment by nshmyrev** [comment]
> but when I ran setup.py, I got "Define KALDI_ROOT"

You should not run setup.py if you already installed vosk with pip.
