### ISSUE TITLE
when run c example make, error occur

### ISSUE THREAD

**Issue by DaisyHH** [alphacep/vosk-api#172]
hello, 
when i run c example （env is ubuntu 16.04-64, ）, during make operation, an error occur， do you have any idear?
（i run python success by pip3 install vosk）

`dy@srcn2:~/github/vosk-api/c$ make

g++ -g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I/home/dy/github/kaldi/src -I/home/dy/github/kaldi/tools/openfst-1.6.7/include -c -o test_vosk.o test_vosk.c

g++ -std=c++11 -g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I/home/dy/github/kaldi/src -I/home/dy/github/kaldi/tools/openfst-1.6.7/include -c -o ../src/kaldi_recognizer.o ../src/kaldi_recognizer.cc

In file included from ../src/kaldi_recognizer.cc:15:0:

../src/kaldi_recognizer.h:64:14: error: ‘LookAheadFst’ in namespace ‘fst’ does not name a template type

         fst::LookAheadFst<fst::StdArc, int32> *decode_fst_;

              ^~~~~~~~~~~~

../src/kaldi_recognizer.cc: In constructor ‘KaldiRecognizer::KaldiRecognizer(Model*, float)’:

../src/kaldi_recognizer.cc:31:5: error: ‘decode_fst_’ was not declared in this scope

     decode_fst_ = NULL;

     ^~~~~~~~~~~

../src/kaldi_recognizer.cc: In constructor ‘KaldiRecognizer::KaldiRecognizer(Model*, float, const char*)’:

../src/kaldi_recognizer.cc:82:9: error: ‘decode_fst_’ was not declared in this scope

         decode_fst_ = LookaheadComposeFst(*model_->hcl_fst_, *g_fst_, model_->disambig_);

         ^~~~~~~~~~~

../src/kaldi_recognizer.cc:84:9: error: ‘decode_fst_’ was not declared in this scope

         decode_fst_ = NULL;

         ^~~~~~~~~~~

../src/kaldi_recognizer.cc:91:55: error: ‘decode_fst_’ was not declared in this scope

             model_->hclg_fst_ ? *model_->hclg_fst_ : *decode_fst_,

                                                       ^~~~~~~~~~~

../src/kaldi_recognizer.cc: In constructor ‘KaldiRecognizer::KaldiRecognizer(Model*, SpkModel*, float)’:

../src/kaldi_recognizer.cc:108:5: error: ‘decode_fst_’ was not declared in this scope

     decode_fst_ = NULL;

     ^~~~~~~~~~~

../src/kaldi_recognizer.cc: In destructor ‘KaldiRecognizer::~KaldiRecognizer()’:

../src/kaldi_recognizer.cc:136:12: error: ‘decode_fst_’ was not declared in this scope

     delete decode_fst_;

            ^~~~~~~~~~~

../src/kaldi_recognizer.cc: In member function ‘void KaldiRecognizer::CleanUp()’:

../src/kaldi_recognizer.cc:197:55: error: ‘decode_fst_’ was not declared in this scope

             model_->hclg_fst_ ? *model_->hclg_fst_ : *decode_fst_,

                                                       ^~~~~~~~~~~

Makefile:35: recipe for target '../src/kaldi_recognizer.o' failed

make: *** [../src/kaldi_recognizer.o] Error 1

`

**Comment by nshmyrev** [comment]
You need more or less recent kaldi version

**Comment by DaisyHH** [comment]
it's ok now, thanks!
i guess it's about gcc version(5.4version, now 6.1version), i'm not sure.
 and others(c/makefile, firstly i change the openfst  to openfst-1.6.7, it's strage, now i only modify the KALDI_ROOT)

**Comment by nshmyrev** [comment]
Ok, let me know if you have further issues.
