### ISSUE TITLE
How to train model for the VOSK

### ISSUE THREAD

**Issue by IceFloe** [alphacep/vosk-api#173]
Hi, I did not find any tutorial for training the custom model. 

What I did, I prepared the dataset, and using voxforge from egs kaldi project train the model, it is succeed.
Right now I have results in the exp folder, but don't know how to match them with vosk, can you provide for me more details how to do that or what should I read to understand this.

**Comment by nshmyrev** [comment]
Documented here: https://alphacephei.com/vosk/models#training-your-own-model
