### ISSUE TITLE
Building the C test of the Vosk-API library

### ISSUE THREAD

**Issue by Naezzhy** [alphacep/vosk-api#178]
Hello @nshmyrev. I am trying to compile a C test of the Vosk-API library following the instructions at **_https://alphacephei.com/vosk/install_**. Kaldi compiled fine, but there were some difficulties with the C test and the Vosk library. When I run **make** in the **../vosk-api/c/** directory **g++** gives errors:

`g++ -std=c++11 -g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I/home/robouser/travis/kaldi/src -I/home/robouser/travis/kaldi/tools/openfst/include -c -o ../src/kaldi_recognizer.o ../src/kaldi_recognizer.cc
In file included from ../src/kaldi_recognizer.cc:15:
../src/kaldi_recognizer.h:64:14: error: ‘LookaheadFst’ in namespace ‘fst’ does not name a template type
         fst::LookaheadFst<fst::StdArc, int32> *decode_fst_;
              ^~~~~~~~~~~~
../src/kaldi_recognizer.h:64:9: note: suggested alternative: ‘kLookAheadFlags’
         fst::LookaheadFst<fst::StdArc, int32> *decode_fst_;
         ^~~
         kLookAheadFlags
../src/kaldi_recognizer.cc: In constructor ‘KaldiRecognizer::KaldiRecognizer(Model*, float)’:
../src/kaldi_recognizer.cc:31:5: error: ‘decode_fst_’ was not declared in this scope
     decode_fst_ = NULL;
     ^~~~~~~~~~~
../src/kaldi_recognizer.cc:31:5: note: suggested alternative: ‘decoder_’
     decode_fst_ = NULL;
     ^~~~~~~~~~~
     decoder_
../src/kaldi_recognizer.cc:35:27: error: ‘LookaheadComposeFst’ was not declared in this scope
             decode_fst_ = LookaheadComposeFst(*model_->hcl_fst_, *model_->g_fst_, model_->disambig_);
                           ^~~~~~~~~~~~~~~~~~~
../src/kaldi_recognizer.cc: In constructor ‘KaldiRecognizer::KaldiRecognizer(Model*, float, const char*)’:
../src/kaldi_recognizer.cc:82:9: error: ‘decode_fst_’ was not declared in this scope
         decode_fst_ = LookaheadComposeFst(*model_->hcl_fst_, *g_fst_, model_->disambig_);
         ^~~~~~~~~~~
../src/kaldi_recognizer.cc:82:9: note: suggested alternative: ‘decoder_’
         decode_fst_ = LookaheadComposeFst(*model_->hcl_fst_, *g_fst_, model_->disambig_);
         ^~~~~~~~~~~
         decoder_
../src/kaldi_recognizer.cc:82:23: error: ‘LookaheadComposeFst’ was not declared in this scope
         decode_fst_ = LookaheadComposeFst(*model_->hcl_fst_, *g_fst_, model_->disambig_);
                       ^~~~~~~~~~~~~~~~~~~
../src/kaldi_recognizer.cc:84:9: error: ‘decode_fst_’ was not declared in this scope
         decode_fst_ = NULL;
         ^~~~~~~~~~~
../src/kaldi_recognizer.cc:84:9: note: suggested alternative: ‘decoder_’
         decode_fst_ = NULL;
         ^~~~~~~~~~~
         decoder_
../src/kaldi_recognizer.cc:91:55: error: ‘decode_fst_’ was not declared in this scope
             model_->hclg_fst_ ? *model_->hclg_fst_ : *decode_fst_,
                                                       ^~~~~~~~~~~
../src/kaldi_recognizer.cc:91:55: note: suggested alternative: ‘decoder_’
             model_->hclg_fst_ ? *model_->hclg_fst_ : *decode_fst_,
                                                       ^~~~~~~~~~~
                                                       decoder_
../src/kaldi_recognizer.cc: In constructor ‘KaldiRecognizer::KaldiRecognizer(Model*, SpkModel*, float)’:
../src/kaldi_recognizer.cc:108:5: error: ‘decode_fst_’ was not declared in this scope
     decode_fst_ = NULL;
     ^~~~~~~~~~~
../src/kaldi_recognizer.cc:108:5: note: suggested alternative: ‘decoder_’
     decode_fst_ = NULL;
     ^~~~~~~~~~~
     decoder_
../src/kaldi_recognizer.cc:113:27: error: ‘LookaheadComposeFst’ was not declared in this scope
             decode_fst_ = LookaheadComposeFst(*model_->hcl_fst_, *model_->g_fst_, model_->disambig_);
                           ^~~~~~~~~~~~~~~~~~~
../src/kaldi_recognizer.cc: In destructor ‘KaldiRecognizer::~KaldiRecognizer()’:
../src/kaldi_recognizer.cc:136:12: error: ‘decode_fst_’ was not declared in this scope
     delete decode_fst_;
            ^~~~~~~~~~~
../src/kaldi_recognizer.cc:136:12: note: suggested alternative: ‘decoder_’
     delete decode_fst_;
            ^~~~~~~~~~~
            decoder_
../src/kaldi_recognizer.cc: In member function ‘void KaldiRecognizer::CleanUp()’:
../src/kaldi_recognizer.cc:197:55: error: ‘decode_fst_’ was not declared in this scope
             model_->hclg_fst_ ? *model_->hclg_fst_ : *decode_fst_,
                                                       ^~~~~~~~~~~
../src/kaldi_recognizer.cc:197:55: note: suggested alternative: ‘decoder_’
             model_->hclg_fst_ ? *model_->hclg_fst_ : *decode_fst_,
                                                       ^~~~~~~~~~~
                                                       decoder_
../src/kaldi_recognizer.cc: In member function ‘bool KaldiRecognizer::GetSpkVector(kaldi::Vector<float>&)’:
../src/kaldi_recognizer.cc:307:78: error: no matching function for call to ‘kaldi::OnlineSilenceWeighting::ComputeCurrentTraceback(const kaldi::LatticeFasterOnlineDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > >&, bool)’
         silence_weighting_->ComputeCurrentTraceback(decoder_->Decoder(), true);
                                                                              ^
In file included from /home/robouser/travis/kaldi/src/online2/online-nnet2-feature-pipeline.h:33,
                 from /home/robouser/travis/kaldi/src/online2/online-nnet3-decoding.h:35,
                 from ../src/model.h:24,
                 from ../src/kaldi_recognizer.h:27,
                 from ../src/kaldi_recognizer.cc:15:
/home/robouser/travis/kaldi/src/online2/online-ivector-feature.h:482:8: note: candidate: ‘template<class FST> void kaldi::OnlineSilenceWeighting::ComputeCurrentTraceback(const kaldi::LatticeFasterOnlineDecoderTpl<FST>&)’
   void ComputeCurrentTraceback(const LatticeFasterOnlineDecoderTpl<FST> &decoder);
        ^~~~~~~~~~~~~~~~~~~~~~~
/home/robouser/travis/kaldi/src/online2/online-ivector-feature.h:482:8: note:   template argument deduction/substitution failed:
../src/kaldi_recognizer.cc:307:78: note:   candidate expects 1 argument, 2 provided
         silence_weighting_->ComputeCurrentTraceback(decoder_->Decoder(), true);
                                                                              ^
../src/kaldi_recognizer.cc:308:29: error: ‘class kaldi::OnlineSilenceWeighting’ has no member named ‘GetNonsilenceFrames’
         silence_weighting_->GetNonsilenceFrames(feature_pipeline_->NumFramesReady(),
                             ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:35: ../src/kaldi_recognizer.o] Ошибка 1`

Looking at the errors, I assumed that the matter was in the outdated version 1.6.3 of the OpenFST library, but after compiling and installing the latest 1.7.9 version, nothing changed. Please tell me what I'm doing wrong.

**Comment by nshmyrev** [comment]
Your Kaldi doesn't have LookaheadFst, you need to update it. The version from lookahead branch from https://github.com/alphacep/kaldi or latest kaldi master should work fine.

**Comment by Naezzhy** [comment]
Many thanks! The test compiled successfully!
