### ISSUE TITLE
what happened here? partial is correct, final result is not.

### ISSUE THREAD

**Issue by maidenone** [alphacep/vosk-api#183]
first of all this works great! good job!

i am getting a bit confused about my result, can you explan what happened here? (i stated: "My name is anton")

{
  "partial" : "my name is"
}
{
  "partial" : "my name is antonio"
}
{
  "partial" : "my name is anton"
}
{
  "partial" : "my name is anton"
}
{
  "partial" : "my name is anton"
}
{
  "partial" : "my name is anton"
}
{
  "result" : [{
      "conf" : 1.000000,
      "end" : 71.160000,
      "start" : 70.920000,
      "word" : "my"
    }, {
      "conf" : 1.000000,
      "end" : 71.520000,
      "start" : 71.160000,
      "word" : "name"
    }, {
      "conf" : 1.000000,
      "end" : 71.700000,
      "start" : 71.520000,
      "word" : "is"
    }, {
      "conf" : 0.999340,
      "end" : 72.000000,
      "start" : 71.760000,
      "word" : "on"
    }, {
      "conf" : 0.999292,
      "end" : 72.300000,
      "start" : 72.000000,
      "word" : "town"
    }],
  "text" : "my name is on town"
}

**Comment by nshmyrev** [comment]
Big language model rescored result and selected better variant

**Comment by maidenone** [comment]
ok, thanks for the quick reply, for reference i used vosk-model-small-en-us-0.3, and i guess names is always hard.
Is there a list of what words was used to train the model?

Dave, Peter, Tom, Sophia works well, but Joel, Anton, Alva does not work at all no matter how i try to pronounce it. I guess they are not part of the wordlist that it was trained on.

**Comment by nshmyrev** [comment]
You can find the list of words here for example:

https://github.com/alphacep/vosk-android-demo/blob/master/models/src/main/assets/sync/model-android/graph/words.txt

Those words are present. For accuracy analysis you'd better provide audio samples.

**Comment by GlebOlden** [comment]
Hello! I have the same problem with Russian simple model, vosk-model-small-ru-0.4. When I try to say: "My name is Gleb" in Russian, Vosk returns: "my name is" without a name. How can I add new words to the model? I tried to specify the possible word list in test_microphone.py file, but it does not complement the current model.

What should I do?

**Comment by nshmyrev** [comment]
Scripts to add word to the model described here https://alphacephei.com/vosk/lm
