### ISSUE TITLE
Gradle build for Android

### ISSUE THREAD

**Issue by gunjanddave** [alphacep/vosk-api#186]
d/build/kaldi_x86_64/local/lib/libclapack.a /vosk-api/android/build/kaldi_x86_64/local/lib/liblapack.a /vosk-api/android/build/kaldi_x86_64/local/lib/libblas.a /vosk-api/android/build/kaldi_x86_64/local/lib/libf2c.a -lm -ldl clang++: error: no such file or directory: '/vosk-api/android/build/kaldi_x86_64/local/lib/libclapack.a' clang++: error: no such file or directory: '/vosk-api/android/build/kaldi_x86_64/local/lib/liblapack.a' clang++: error: no such file or directory: '/vosk-api/android/build/kaldi_x86_64/local/lib/libblas.a' clang++: error: no such file or directory: '/vosk-api/android/build/kaldi_x86_64/local/lib/libf2c.a'

Getting the above error where some files are missing.

OS: Mac OS Catalina.
Build - For Android.

**Comment by nshmyrev** [comment]
There should be errors earlier in the log where those libraries failed to build. You need to read/share the whole log.

**Comment by gunjanddave** [comment]
> There should be errors earlier in the log where those libraries failed to build. You need to read/share the whole log.

Making install in lookahead
 ../../.././install-sh -c -d '/vosk-api/android/build/kaldi_arm_32/local/lib'
 /bin/sh ../../../libtool   --mode=install /usr/bin/install -c   libfstlookahead.la '/vosk-api/android/build/kaldi_arm_32/local/lib'
libtool:   error: error: cannot install 'libfstlookahead.la' to a directory not ending in /vosk-api/android/build/kaldi_arm_32/local/lib
make[4]: *** [install-libLTLIBRARIES] Error 1
make[3]: *** [install-am] Error 2
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

I can see this error apart from the above mentioned one.

**Comment by nshmyrev** [comment]
Share the whole build log. You can run from a clean state likel this:

     gradle build >& build.log

then attach build log here.

**Comment by gunjanddave** [comment]
> Share the whole build log. You can run from a clean state likel this:
> 
> ```
>  gradle build >& build.log
> ```
> 
> then attach build log here.

Attaching Logs:

[vosk_api_logs.txt](https://github.com/alphacep/vosk-api/files/5074741/vosk_api_logs.txt)

**Comment by nshmyrev** [comment]
Those logs are not from a clean state. Remove old tree, clone vosk-api again and run again and provide the logs.

**Comment by gunjanddave** [comment]
Doing a clean slate, I am able to resolve this issue.
