### ISSUE TITLE
Undefined reference to ‘vsPowx’

### ISSUE THREAD

**Issue by bin872686** [alphacep/vosk-api#188]
Undefined reference to ‘vsPowx’ in the function ‘kaldi::VectorBase<float>::Pow(kaldi::VectorBase<float> const&, float)’ when make under the c folder

**Comment by nshmyrev** [comment]
It means your kaldi is linked with mkl libraries. We prefer kaldi build with openblas (as in documentation) but if you still want to build with mkl you need to link to mkl libraries:

`-L/opt/intel/mkl/lib/intel64 -Wl,-rpath=/opt/intel/mkl/lib/intel64 -lmkl_rt -lmkl_intel_lp64 -lmkl_core -lmkl_sequential`

**Comment by bin872686** [comment]
ok,thanks
