### ISSUE TITLE
C++ exceptions crash Python interpreter

### ISSUE THREAD

**Issue by dtreskunov** [alphacep/vosk-api#19]
Related to #18 , using the same code, note how the C++ exception is not handled and causes Python to abort.

Perhaps it would be possible to let Python code handle exceptions thrown from C++?

I'd like to help, but it would take me some time to learn C++ and SWIG :)

```python
from vosk import Model, KaldiRecognizer

try:
  model = Model('fr')
  rec = KaldiRecognizer(model, 8000)
  data = b'\x00' * 1000
  print(rec.AcceptWaveform(data))
except Exception as e:
  print('Exception!', e)
  raise e

print('OK')
```

**Comment by nshmyrev** [comment]
Honestly exceptions in bindings are pretty complicated thing, many memory safety issues and swig issues too. Also Kaldi exceptions are not really part of the API, they raise when something goes wrong from the beginning. 

I would leave it as is for now.
