### ISSUE TITLE
Runtime change in language model.

### ISSUE THREAD

**Issue by gunjanddave** [alphacep/vosk-api#190]
First of all, Thank you so much for such a wonderful library.

I need help. I want to start with very minimum words and max I would have 100 words at a time. But this would change for different users.
So, according to [https://alphacephei.com/vosk/adaptation](url) I am able to adjust the probability of words to improve recognition. By re-compiling, the language model from the text works great.

Can we do this at runtime? from Android?

**Comment by nshmyrev** [comment]
Yes, you can, see here:

https://github.com/alphacep/vosk-android-demo/blob/49a353448255234bc90741f130e42a2c16c14519/app/src/main/java/org/kaldi/demo/KaldiActivity.java#L147

**Comment by gunjanddave** [comment]
Thanks for the response.

What models from kaldi vosk-api models has dynamic graph which supports runtime modification?

Also, facing below issue.
In Mac OS, step mentioned in https://alphacephei.com/vosk/adaptation is not working. Facing issue while re-compilation.

**Comment by gunjanddave** [comment]
With a clean slate on MAC, I am able to re-compile the graph with minimum words.

What models from Kaldi vosk-api models has a dynamic graph which supports runtime modification?

**Comment by nshmyrev** [comment]
> What models from Kaldi vosk-api models has a dynamic graph which supports runtime modification?

all small mobile ones

**Comment by gunjanddave** [comment]
@nshmyrev Thanks for the response.
Is there any way or recipe available to add new words or increase the accuracy in existing vosk small model?

Is there any way or documentation available to train model like vosk models?

**Comment by nshmyrev** [comment]
> Is there any way or recipe available to add new words 

https://alphacephei.com/vosk/adaptation

>  increase the accuracy in existing vosk small model?

https://alphacephei.com/vosk/accuracy

> Is there any way or documentation available to train model like vosk models?

https://alphacephei.com/vosk/models#training-your-own-model

**Comment by gunjanddave** [comment]
@nshmyrev I am following this tutorial 
https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/
In this, on MAC OS I am facing issues with the "tree-info" command. I have installed a tree but still, it is giving me this error. Do you suggest any alternative?

**Comment by nshmyrev** [comment]
>  I am facing issues with the "tree-info" command. 

What issue exactly

> Do you suggest any alternative?

There are no alternatives

**Comment by gunjanddave** [comment]
In root "/kaldi/egs/aspire/s5" while executing this command 

`utils/mkgraph.sh --self-loop-scale 1.0 data/lang_pp_test exp/tdnn_7b_chain_online exp/tdnn_7b_chain_online/graph_pp 
`
```
getting this below error

utils/mkgraph.sh: line 75: tree-info: command not found
Error when getting context-width
```

**Comment by nshmyrev** [comment]
tree-info is part of kaldi, you need to make sure you compiled it properly (the tree-info binary is there) and that the path is set correctly.
