### ISSUE TITLE
VOSK in Flutter

### ISSUE THREAD

**Issue by ekremsahin** [alphacep/vosk-api#191]
Hi.

I'am new to Speech Recognition tools. I have a project that i need to use VOSK in Flutter app if its possible.

I want to learn if it is possible and if it is possible what i need to do for it. If it is a dumb question sorry about that i am still newbie

Thanks for any help :)

**Comment by nshmyrev** [comment]
> if it is possible

Yes it is possible, you have to write the integration part

https://flutter.dev/docs/development/platform-integration/platform-channels

**Comment by ekremsahin** [comment]
Thank you much for help and fast response :1st_place_medal:

**Comment by DeRealMorgan** [comment]
@ekremsahin have you implemented it?

**Comment by ekremsahin** [comment]
not implemented it yet

**Comment by nshmyrev** [comment]
Lets track in #262

**Comment by alpha-21** [comment]
@ekremsahin have you implemented it?

**Comment by SaudSultan2001** [comment]
@ekremsahin have you implemented it, would be great help if you could tell us how you managed to do it?
