### ISSUE TITLE
Training a Common Voice Model

### ISSUE THREAD

**Issue by kromoxpro** [alphacep/vosk-api#192]
Hello, Is it possible to train a model for Vosk using the Common Voice dataset?

I have used the small model of the Spanish language, is there a larger model as it happens in the English language?

https://commonvoice.mozilla.org/es/datasets

Thanks.

**Comment by nshmyrev** [comment]
> Hello, Is it possible to train a model for Vosk using the Common Voice dataset?

Yes, but CV is not the good source for training. You'd better get mailabs audiobooks and some youtube data.

> I have used the small model of the Spanish language, is there a larger model as it happens in the English language?

Big Spanish model is not yet public.

**Comment by kromoxpro** [comment]
Thank you very much for your answer @nshmyrev 

> Yes, but CV is not the good source for training. You'd better get mailabs audiobooks and some youtube data.

**Where can I get this youtube data?**

**Is there any documentation to train the mailabs dataset and the youtube data that you comment?**

> Big Spanish model is not yet public.


The small model is amazing, I can't imagine what the big model will be like.

**Do you have any idea when this model will be available?**

**Comment by nshmyrev** [comment]
> Where can I get this youtube data? Is there any documentation to train the mailabs dataset and the youtube data that you comment?

https://github.com/EgorLakomkin/KTSpeechCrawler

> Do you have any idea when this model will be available?

Sorry, we do not have near plans to open source it right now

**Comment by ajaysg-zz** [comment]
@nshmyrev is it possible to train Keywords and Digits(multiple digits) using VOSK basically for warehouse automation. We have datasets from the warehouse.

**Comment by nshmyrev** [comment]
> @nshmyrev is it possible to train Keywords and Digits(multiple digits) using VOSK basically for warehouse automation. We have datasets from the warehouse.

Yes, sure, why not. We also recommend to mix generic datasets into training even if you need just digits for better generalization.

**Comment by correlator** [comment]
Why is common voice a bad dataset for training models?  It depends on what you will use the models for.  Youtube and audiobooks are great transcriptions, but the audio is very clear and well produced.  These should work well for adding transcripts to videos.  Common voice is people around the world reading into computer microphones, and so this should be better for things like phone calls and video conference meetings.

**Comment by nshmyrev** [comment]
> Common voice is people around the world reading into computer microphones, and so this should be better for things like phone calls and video conference meetings.

No, it doesn't work. Language in phone calls is very different from read speech. Also the lines recorded in CV are not variable enough. 

Improvement from adding common voice data to the training is marginal on many languages (English, German).

**Comment by correlator** [comment]
That is quite interesting and surprising to hear (I love surprising news because that is where learning happens).  Is there a citation for this information, or is this a result from testing you have done?

**Comment by nshmyrev** [comment]
You can check figure 5 [here](https://www.researchgate.net/publication/336532830_German_End-to-end_Speech_Recognition_based_on_DeepSpeech)

**Comment by nshmyrev** [comment]
Feel free to reopen if you have further questions.
