### ISSUE TITLE
3 out of 5 English Models are Killed Mid-Process

### ISSUE THREAD

**Issue by feliciatrinh** [alphacep/vosk-api#194]
### Description
I am using all five English models to process the [LibriSpeech Test Clean dataset](http://www.openslr.org/12) (2620 audio files equaling 5.4 hours), but the larger models (vosk-model-en-us-aspire-0.2, vosk-model-en-us-daanzu, vosk-model-en-us-librispeech-0.2) are killed after processing about 215 audio files equaling about 0.4 hours. 

### Details
- Ubuntu 20.04.1
- Python3
- Occurs regardless of whether I am in a virtual environment
- 391 GB available

I've attached the program log and additional information.
[vosk-librispeech-0.2-kill-log.txt](https://github.com/alphacep/vosk-api/files/5119328/vosk-librispeech-0.2-kill-log.txt)
[info.txt](https://github.com/alphacep/vosk-api/files/5119329/info.txt)

**Comment by nshmyrev** [comment]
Show your code.

You load too many models. You should not create Model every time, just recognizer object.

You can check https://github.com/alphacep/vosk-api/blob/master/python/test/transcribe_scp.py for example.

**Comment by feliciatrinh** [comment]
You are correct. I currently create a Model each time. I'll change that. Thanks!

I have two scripts. `benchmark.py` creates a Vosk engine instance and calls its transcribe method.
```
engine = ASREngine.create()
for i in range(dataset.size()):
    audio_file_path = dataset.get(i)
    transcript = engine.transcribe(audio_file_path )
```

`engine.py`:
```
class VoskASREngine(ASREngine):
    def __init__(self, model):
        ...

    def transcribe(self, path):
        from vosk import KaldiRecognizer, Model, SetLogLevel

        SetLogLevel(0)
        model = Model(...)
        rec = KaldiRecognizer(model, 16000)

        with open(path, 'rb') as audio_file:
            while True:
                data = audio_file.read(4000)
                if len(data) == 0:
                    break
                if rec.AcceptWaveform(data):
                    res = json.loads(rec.Result())['text']
                    break
                else:
                    partial = json.loads(rec.PartialResult())['partial']
```

**Comment by nshmyrev** [comment]
Ok, please move Model into `__init__` out of `transcribe`.
