### ISSUE TITLE
Unrecognized word at the beginning of the phrase

### ISSUE THREAD

**Issue by kdorichev** [alphacep/vosk-api#195]
**Short** words in the _beginning_ of the phrase are not properly recognized. It seems that it takes time for the algorithm to catch up.
Example: 
Factual text:        ```"и нужно было придумать нечто объединяющее всех граждан"```
Recognized text: ```"нужно было придумать нечто объединяющее всех граждан"```

**Comment by kdorichev** [comment]
A workaround -- add some silence at the beginning of the audio.
```bash
sox infile outfile pad 0.5
```
This helps the current implementation to correctly distinguish the firsh short word.

**Comment by nshmyrev** [comment]
Same issue as https://github.com/alphacep/vosk-api/issues/223, lets track there. i-vector extractor needs more love to adapt to volume faster.
