### ISSUE TITLE
[Support]Cross compile vosk

### ISSUE THREAD

**Issue by AlexTraan** [alphacep/vosk-api#196]
Hi,

I am trying to cross compile (https://github.com/alphacep/vosk-api/tree/master/c) but failed, it show error as below:
"../../toolchain/bin/arm-linux-gnueabihf-g++ -g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I../../kaldi/src -I../../kaldi/tools/openfst/include -c -o test_vosk.o test_vosk.c
../../toolchain/bin/arm-linux-gnueabihf-g++ -std=c++11 -g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I../../kaldi/src -I../../kaldi/tools/openfst/include -c -o ../src/kaldi_recognizer.o ../src/kaldi_recognizer.cc
../../toolchain/bin/arm-linux-gnueabihf-g++ -std=c++11 -g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I../../kaldi/src -I../../kaldi/tools/openfst/include -c -o ../src/model.o ../src/model.cc
../../toolchain/bin/arm-linux-gnueabihf-g++ -std=c++11 -g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I../../kaldi/src -I../../kaldi/tools/openfst/include -c -o ../src/spk_model.o ../src/spk_model.cc
../../toolchain/bin/arm-linux-gnueabihf-g++ -std=c++11 -g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I../../kaldi/src -I../../kaldi/tools/openfst/include -c -o ../src/vosk_api.o ../src/vosk_api.cc
../../toolchain/bin/arm-linux-gnueabihf-ar rcs libvosk.a ../src/kaldi_recognizer.o ../src/model.o ../src/spk_model.o ../src/vosk_api.o
../../toolchain/bin/arm-linux-gnueabihf-g++ --sysroot=../../sysroot test_vosk.o libvosk.a -o test_vosk ../../kaldi/src/online2/kaldi-online2.a ../../kaldi/src/decoder/kaldi-decoder.a ../../kaldi/src/ivector/kaldi-ivector.a ../../kaldi/src/gmm/kaldi-gmm.a ../../kaldi/src/nnet3/kaldi-nnet3.a ../../kaldi/src/tree/kaldi-tree.a ../../kaldi/src/feat/kaldi-feat.a ../../kaldi/src/lat/kaldi-lat.a ../../kaldi/src/lm/kaldi-lm.a ../../kaldi/src/hmm/kaldi-hmm.a ../../kaldi/src/transform/kaldi-transform.a ../../kaldi/src/cudamatrix/kaldi-cudamatrix.a ../../kaldi/src/matrix/kaldi-matrix.a ../../kaldi/src/fstext/kaldi-fstext.a ../../kaldi/src/util/kaldi-util.a ../../kaldi/src/base/kaldi-base.a ../../kaldi/tools/OpenBLAS/libopenblas.a ../../kaldi/tools/openfst/lib/libfst.a ../../kaldi/tools/openfst/lib/libfstngram.a -static-libstdc++ -L/usr/lib/arm-linux-gnueabihf/gfortran.so.3 -lpthread
libvosk.a(kaldi_recognizer.o): In function `RunNnetComputation':
/home/alex/Working/vosk-api-master/c/../src/kaldi_recognizer.cc:281: undefined reference to `kaldi::nnet3::IoSpecification::IoSpecification(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)'
/home/alex/Working/vosk-api-master/c/../src/kaldi_recognizer.cc:293: undefined reference to `kaldi::nnet3::NnetComputer::AcceptInput(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::CuMatrix<float>*)'
/home/alex/Working/vosk-api-master/c/../src/kaldi_recognizer.cc:296: undefined reference to `kaldi::nnet3::NnetComputer::GetOutputDestructive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::CuMatrix<float>*)'
libvosk.a(kaldi_recognizer.o): In function `fst::internal::SymbolTableImpl::Find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/symbol-table.h:237: undefined reference to `fst::internal::DenseSymbolMap::Find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/symbol-table.h:237: undefined reference to `fst::internal::DenseSymbolMap::Find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libvosk.a(kaldi_recognizer.o): In function `fst::internal::FstImpl<fst::ArcTpl<fst::LatticeWeightTpl<float> > >::WriteFstHeader(fst::Fst<fst::ArcTpl<fst::LatticeWeightTpl<float> > > const&, std::ostream&, fst::FstWriteOptions const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long, fst::FstHeader*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:813: undefined reference to `fst::FstHeader::Write(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libvosk.a(kaldi_recognizer.o): In function `fst::internal::FstImpl<fst::ArcTpl<fst::TropicalWeightTpl<float> > >::WriteFstHeader(fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, std::ostream&, fst::FstWriteOptions const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long, fst::FstHeader*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:813: undefined reference to `fst::FstHeader::Write(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libvosk.a(kaldi_recognizer.o): In function `fst::internal::FstImpl<fst::ArcTpl<fst::CompactLatticeWeightTpl<fst::LatticeWeightTpl<float>, int> > >::WriteFstHeader(fst::Fst<fst::ArcTpl<fst::CompactLatticeWeightTpl<fst::LatticeWeightTpl<float>, int> > > const&, std::ostream&, fst::FstWriteOptions const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long, fst::FstHeader*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:813: undefined reference to `fst::FstHeader::Write(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libvosk.a(model.o): In function `Model::ConfigureV2()':
/home/alex/Working/vosk-api-master/c/../src/model.cc:172: undefined reference to `kaldi::ParseOptions::ReadConfigFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libvosk.a(model.o): In function `Model::ReadDataFiles()':
/home/alex/Working/vosk-api-master/c/../src/model.cc:208: undefined reference to `kaldi::Input::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*)'
/home/alex/Working/vosk-api-master/c/../src/model.cc:236: undefined reference to `fst::ReadFstKaldiGeneric(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)'
/home/alex/Working/vosk-api-master/c/../src/model.cc:244: undefined reference to `kaldi::ReadIntegerVectorSimple(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<int, std::allocator<int> >*)'
/home/alex/Working/vosk-api-master/c/../src/model.cc:255: undefined reference to `fst::SymbolTable::ReadText(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, fst::SymbolTableTextOptions const&)'
/home/alex/Working/vosk-api-master/c/../src/model.cc:271: undefined reference to `fst::ReadFstKaldi(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
libvosk.a(model.o): In function `void kaldi::ReadKaldiObject<kaldi::ConstArpaLm>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::ConstArpaLm*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/util/kaldi-io.h:242: undefined reference to `kaldi::Input::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*)'
libvosk.a(model.o): In function `Model::ReadDataFiles()':
/home/alex/Working/vosk-api-master/c/../src/model.cc:264: undefined reference to `kaldi::WordBoundaryInfo::WordBoundaryInfo(kaldi::WordBoundaryInfoNewOpts const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
libvosk.a(model.o): In function `fst::FstRegister<fst::ArcTpl<fst::TropicalWeightTpl<float> > >::ConvertKeyToSoFilename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/register.h:61: undefined reference to `fst::ConvertToLegalCSymbol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
libvosk.a(model.o): In function `kaldi::ParseOptions::ParseOptions(char const*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/util/parse-options.h:45: undefined reference to `void kaldi::ParseOptions::RegisterStandard<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/util/parse-options.h:47: undefined reference to `void kaldi::ParseOptions::RegisterStandard<bool>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/util/parse-options.h:48: undefined reference to `void kaldi::ParseOptions::RegisterStandard<bool>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/util/parse-options.h:50: undefined reference to `void kaldi::ParseOptions::RegisterStandard<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libvosk.a(model.o): In function `kaldi::nnet3::NnetSimpleLoopedComputationOptions::Register(kaldi::OptionsItf*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/nnet3/decodable-simple-looped.h:88: undefined reference to `kaldi::ParseOptions::ParseOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/nnet3/decodable-simple-looped.h:92: undefined reference to `kaldi::ParseOptions::ParseOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)'
libvosk.a(model.o): In function `kaldi::nnet3::NnetComputeOptions::Register(kaldi::OptionsItf*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/nnet3/nnet-compute.h:45: undefined reference to `kaldi::ParseOptions::Register(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libvosk.a(model.o): In function `void kaldi::ReadConfigFromFile<kaldi::MfccOptions>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::MfccOptions*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/util/parse-options.h:244: undefined reference to `kaldi::ParseOptions::ReadConfigFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libvosk.a(model.o): In function `kaldi::OnlineEndpointRule::RegisterWithPrefix(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:122: undefined reference to `kaldi::ParseOptions::ParseOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:122: undefined reference to `kaldi::ParseOptions::ParseOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)'
libvosk.a(model.o): In function `kaldi::OnlineEndpointRule::Register(kaldi::OptionsItf*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:106: undefined reference to `kaldi::ParseOptions::Register(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:109: undefined reference to `kaldi::ParseOptions::Register(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:113: undefined reference to `kaldi::ParseOptions::Register(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:116: undefined reference to `kaldi::ParseOptions::Register(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libvosk.a(model.o): In function `kaldi::OnlineEndpointRule::RegisterWithPrefix(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:122: undefined reference to `kaldi::ParseOptions::ParseOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:122: undefined reference to `kaldi::ParseOptions::ParseOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)'
/home/alex/Working/vosk-api-master/c/../../kaldi/src/online2/online-endpoint.h:122: undefined reference to `kaldi::ParseOptions::ParseOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::OptionsItf*)'
libvosk.a(model.o): In function `fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >::Read(std::istream&, fst::FstReadOptions const&)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:242: undefined reference to `fst::FstHeader::Read(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
libvosk.a(model.o): In function `fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >::Read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:267: undefined reference to `fst::FstReadOptions::FstReadOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, fst::FstHeader const*, fst::SymbolTable const*, fst::SymbolTable const*)'
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:265: undefined reference to `fst::FstReadOptions::FstReadOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, fst::FstHeader const*, fst::SymbolTable const*, fst::SymbolTable const*)'
libvosk.a(model.o): In function `fst::internal::FstImpl<fst::ArcTpl<fst::TropicalWeightTpl<float> > >::ReadHeader(std::istream&, fst::FstReadOptions const&, int, fst::FstHeader*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:874: undefined reference to `fst::FstHeader::Read(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
libvosk.a(model.o): In function `fst::internal::ConstFstImpl<fst::ArcTpl<fst::TropicalWeightTpl<float> >, unsigned int>::Read(std::istream&, fst::FstReadOptions const&)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/const-fst.h:200: undefined reference to `fst::MappedFile::Map(std::istream*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/const-fst.h:213: undefined reference to `fst::MappedFile::Map(std::istream*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'
libvosk.a(model.o): In function `fst::internal::AddOnImpl<fst::ConstFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, unsigned int>, fst::AddOnPair<fst::LabelReachableData<int>, fst::LabelReachableData<int> > >::Read(std::istream&, fst::FstReadOptions const&)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/add-on.h:158: undefined reference to `fst::FstHeader::Read(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
libvosk.a(model.o): In function `fst::LabelLookAheadRelabeler<fst::ArcTpl<fst::TropicalWeightTpl<float> >, fst::LabelReachableData<int> >::LabelLookAheadRelabeler<fst::internal::AddOnImpl<fst::ConstFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, unsigned int>, fst::AddOnPair<fst::LabelReachableData<int>, fst::LabelReachableData<int> > > >(std::shared_ptr<fst::internal::AddOnImpl<fst::ConstFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, unsigned int>, fst::AddOnPair<fst::LabelReachableData<int>, fst::LabelReachableData<int> > > >*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/lookahead-matcher.h:724: undefined reference to `FLAGS_save_relabel_opairs[abi:cxx11]'
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/lookahead-matcher.h:724: undefined reference to `FLAGS_save_relabel_ipairs[abi:cxx11]'
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/lookahead-matcher.h:724: undefined reference to `FLAGS_save_relabel_opairs[abi:cxx11]'
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/lookahead-matcher.h:724: undefined reference to `FLAGS_save_relabel_ipairs[abi:cxx11]'
libvosk.a(model.o): In function `fst::internal::FstImpl<fst::ArcTpl<fst::TropicalWeightTpl<float> > >::WriteHeader(std::ostream&, fst::FstWriteOptions const&, int, fst::FstHeader*) const':
/home/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:785: undefined reference to `fst::FstHeader::Write(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libvosk.a(spk_model.o): In function `void kaldi::ReadKaldiObject<kaldi::nnet3::Nnet>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::nnet3::Nnet*)':
/home/alex/Working/vosk-api-master/c/../../kaldi/src/util/kaldi-io.h:242: undefined reference to `kaldi::Input::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*)'
../../kaldi/tools/OpenBLAS/libopenblas.a(sgesvd.o): In function `sgesvd_':
sgesvd.f:(.text+0x300): undefined reference to `_gfortran_concat_string'
sgesvd.f:(.text+0x5cc): undefined reference to `_gfortran_concat_string'
../../kaldi/tools/OpenBLAS/libopenblas.a(sormbr.o): In function `sormbr_':
sormbr.f:(.text+0x330): undefined reference to `_gfortran_concat_string'
sormbr.f:(.text+0x4e4): undefined reference to `_gfortran_concat_string'
sormbr.f:(.text+0x51c): undefined reference to `_gfortran_concat_string'
../../kaldi/tools/OpenBLAS/libopenblas.a(sormbr.o):sormbr.f:(.text+0x57c): more undefined references to `_gfortran_concat_string' follow
collect2: error: ld returned 1 exit status
Makefile:44: recipe for target 'test_vosk' failed
make: *** [test_vosk] Error 1
"
i have native build kaldi before try this (already generated *.a file in kaldi folder).

Can you help to give some direction to fix this for me?

**Comment by AlexTraan** [comment]
And, here is my Makefile:
TOOLCHAIN=../../toolchain
KALDI_ROOT=../../kaldi
#Set Architecture
ARCH := arm

#Compilers
ifeq ($(ARCH),arm)
CC  := $(TOOLCHAIN)/bin/arm-linux-gnueabihf-g++
GCC := $(TOOLCHAIN)/bin/arm-linux-gnueabihf-gcc
AR  := $(TOOLCHAIN)/bin/arm-linux-gnueabihf-ar
else
CC  := g++
GCC := gcc
AR  := ar
endif

VOSK_SOURCES=../src/kaldi_recognizer.cc ../src/model.cc ../src/spk_model.cc ../src/vosk_api.cc
CFLAGS=-g -O2 -DFST_NO_DYNAMIC_LINKING -I../src -I$(KALDI_ROOT)/src -I$(KALDI_ROOT)/tools/openfst/include
LIBS= \
	$(KALDI_ROOT)/src/online2/kaldi-online2.a \
	$(KALDI_ROOT)/src/decoder/kaldi-decoder.a \
	$(KALDI_ROOT)/src/ivector/kaldi-ivector.a \
	$(KALDI_ROOT)/src/gmm/kaldi-gmm.a \
	$(KALDI_ROOT)/src/nnet3/kaldi-nnet3.a \
	$(KALDI_ROOT)/src/tree/kaldi-tree.a \
	$(KALDI_ROOT)/src/feat/kaldi-feat.a \
	$(KALDI_ROOT)/src/lat/kaldi-lat.a \
	$(KALDI_ROOT)/src/lm/kaldi-lm.a \
	$(KALDI_ROOT)/src/hmm/kaldi-hmm.a \
	$(KALDI_ROOT)/src/transform/kaldi-transform.a \
	$(KALDI_ROOT)/src/cudamatrix/kaldi-cudamatrix.a \
	$(KALDI_ROOT)/src/matrix/kaldi-matrix.a \
	$(KALDI_ROOT)/src/fstext/kaldi-fstext.a \
	$(KALDI_ROOT)/src/util/kaldi-util.a \
	$(KALDI_ROOT)/src/base/kaldi-base.a \
	$(KALDI_ROOT)/tools/OpenBLAS/libopenblas.a \
	$(KALDI_ROOT)/tools/openfst/lib/libfst.a \
	$(KALDI_ROOT)/tools/openfst/lib/libfstngram.a

all: test_vosk
#test_vosk_speaker

test_vosk: test_vosk.o libvosk.a
	$(CC) --sysroot=../../sysroot $^ -o $@ $(LIBS) -static-libstdc++ -L/usr/lib/arm-linux-gnueabihf/gfortran.so.3 -lpthread

libvosk.a: $(VOSK_SOURCES:.cc=.o)
	$(AR) rcs $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

%.o: %.cc
	$(CC) -std=c++11 $(CFLAGS) -c -o $@ $<

clean:
	rm -f *.o *.a test_vosk ../src/*.o

**Comment by AlexTraan** [comment]
I cannot cross-compile Kaldi, so i native compile Kaldi in my ARM board, i not sure that point can produce this issue or not?

Hope anyone help

**Comment by nshmyrev** [comment]
> I cannot cross-compile Kaldi

You should be able to do it, you can check [build script in dockcross](https://github.com/alphacep/vosk-api/blob/master/travis/Dockerfile.dockcross#L88)

> more undefined references to _gfortran_concat_string' follow

You miss libgfortran

> ome/alex/Working/vosk-api-master/c/../../kaldi/tools/openfst/include/fst/fst.h:267: undefined reference to fst::FstReadOptions::FstReadOptions(std::__cxx11::basic_string<char, std::char_traits<char>,

This is due to the openfst version mismatch. Vosk uses openfst 1.7.7 as you can see in the build script above

**Comment by nshmyrev** [comment]
@AlexTraan is it still relevant?

**Comment by AlexTraan** [comment]
@nshmyrev Sorry for late feedback,
i can cross-compile my c/c++ program based on your comment/guidance, thank you so much
