### ISSUE TITLE
Vosk can't create decoding graph

### ISSUE THREAD

**Issue by ABoltachev** [alphacep/vosk-api#198]
I created a new linguistic model according to the instructions presented on [this site](https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/)
At the end, I have provided the detailed order of the commands that I ran.
In the folder with the unpacked vosk-model-small-en-us-0.3, I replaced all the files with the ones obtained after running these commands.
Unfortunately, when I try to test the resulting model, I get the following output:
```
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00910306 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:235) Loading HCLG from model/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:254) Loading words from model/words.txt
ERROR (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:81) Can't create decoding graph
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)
```
The commands I ran to create the model:
- git clone https://github.com/kaldi-asr/kaldi
- cd kaldi/egs/aspire/s5
- wget http://kaldi-asr.org/models/1/0001_aspire_chain_model.tar.gz
- tar xfv 0001_aspire_chain_model.tar.gz
- utils/mkgraph.sh --self-loop-scale 1.0 data/lang_pp_test exp/tdnn_7b_chain_online exp/tdnn_7b_chain_online/graph_pp
- grep -oE "[A-Za-z\\-\\']{1,}" corpus.txt | tr '[:lower:]' '[:upper:]' | sort | uniq > words.txt
> For this point, I used the model (model-b.key) that is presented on [this site](https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/)
- g2p.py --model model-7 --apply words.txt > words.dic
> For this point, instead of SRILM, I used KenLM, because the SRILM site does not load for me
- Insteed `ngram-count -text corpus.txt -order 3 -limit-vocab -vocab words.txt -unk -map-unk "" -kndiscount -interpolate -lm lm.arpa` I ran `python3 generate_lm.py --input_txt corpus.txt --output_dir . --top_k 500000 --kenlm_bins path/to/kenlm/build/bin/ --arpa_order 5 --max_arpa_memory "85%" --arpa_prune "0|0|1" --binary_a_bits 255 --binary_q_bits 8 --binary_type trie` from [Mozilla STT](https://github.com/mozilla/STT/blob/master/doc/Scorer.rst)
- mkdir -p new/local/dict
- cp data/local/dict/extra_questions.txt new/local/dict/
- cp data/local/dict/nonsilence_phones.txt new/local/dict/
- cp data/local/dict/optional_silence.txt new/local/dict/
- cp data/local/dict/silence_phones.txt new/local/dict/
- cp words.dic new/local/dict/lexicon.txt
- mkdir -p new/local/lang
- cp lm.arpa new/local/lang/
- . cmd.sh
- . path.sh
- model=exp/tdnn_7b_chain_online
- phones_src=exp/tdnn_7b_chain_online/phones.txt
- dict_src=new/local/dict
- lm_src=new/local/lang/lm.arpa
- lang=new/lang
- dict=new/dict
- dict_tmp=new/dict_tmp
- graph=new/graph
- utils/prepare_lang.sh --phone-symbol-table $phones_src $dict_src "" $dict_tmp $dict
- gzip  $lm_src
- utils/format_lm.sh $dict $lm_src.gz $dict_src/lexicon.txt $lang
- utils/mkgraph.sh --self-loop-scale 1.0 $lang $model $graph
- steps/online/nnet3/prepare_online_decoding.sh --mfcc-config conf/mfcc_hires.conf $dict exp/nnet3/extractor exp/chain/tdnn_7b new

I ended up with the following file hierarchy:
```
/export/vosk-api/python/example/model/:
total 295592
drwxr-xr-x 3 root root      4096 Aug 25 00:25 ./
drwxr-xr-x 5 root root      4096 Aug 25 07:05 ../
-rw-r--r-- 1 root root 154522817 Aug 25 00:10 HCLG.fst
-rw-r--r-- 1 root root        36 Aug 25 00:10 disambig_tid.int
-rwxr-xr-x 1 root root 148114959 Aug 25 00:10 final.mdl*
drwxr-xr-x 2 root root      4096 Aug 25 00:13 ivector/
-rwxr-xr-x 1 root root       623 Aug 25 00:16 mfcc.conf*
-rw-r--r-- 1 root root     23143 Aug 25 00:22 words.txt

/export/vosk-api/python/example/model/ivector:
total 19528
drwxr-xr-x 2 root root     4096 Aug 25 00:13 ./
drwxr-xr-x 3 root root     4096 Aug 25 00:25 ../
-rwxr-xr-x 1 root root   168048 Aug 25 00:13 final.dubm*
-rwxr-xr-x 1 root root 19757687 Aug 25 00:13 final.ie*
-rwxr-xr-x 1 root root    44815 Aug 25 00:13 final.mat*
-rwxr-xr-x 1 root root     1082 Aug 25 00:13 global_cmvn.stats*
-rwxr-xr-x 1 root root       95 Aug 25 00:13 online_cmvn.conf*
-rwxr-xr-x 1 root root       35 Aug 25 00:14 splice.conf*
```

**Comment by nshmyrev** [comment]
Big models with static graph do not support dynamic vocabulary, you can use kaldi recognizer without words.

**Comment by ABoltachev** [comment]
> Big models with static graph do not support dynamic vocabulary, you can use kaldi recognizer without words.

Would You tell me please how i can create a model based on vosk-model-small-en-us-0.3 with my corpus?

**Comment by nshmyrev** [comment]
Try https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz

**Comment by ABoltachev** [comment]
> Try https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz

Do I need to follow the same steps I mentioned at the beginning, but only with this model?

**Comment by nshmyrev** [comment]
You can check readme and the scripts inside the archive.

**Comment by gunjanddave** [comment]
@nshmyrev Try https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz in this we would be able to add new words?

**Comment by nshmyrev** [comment]
@gunjanddave yes

**Comment by nshmyrev** [comment]
Feel free to reopen if you have further questions.

**Comment by gunjanddave** [comment]
@nshmyrev I have followed the steps mentioned ReadMe of https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz
 But still, I am getting below error. 

`./compile-graph.sh: line 12: ngram-count: command not found
./compile-graph.sh: line 14: utils/prepare_lang.sh: No such file or directory
./compile-graph.sh: line 17: utils/mkgraph_lookahead.sh: No such file or directory`

Am I missing anything here?

**Comment by nshmyrev** [comment]
ngram-count is part of srilm, utils/mkgraph_lookahead.sh is part of recent kaldi, you should find them.

**Comment by gunjanddave** [comment]
Not seeing this utils/mkgraph_lookahead.sh in the latest code of the Kaldi master branch

**Comment by nshmyrev** [comment]
https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/mkgraph_lookahead.sh

**Comment by gunjanddave** [comment]
> https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/mkgraph_lookahead.sh

I am executing installl_srilm.sh. But facing the below issue. For this what I am missing which has not been installed on my machine.

`echo "GNU awk is not installed so SRILM will probably not work correctly: refusing to install" && exit 1;`

**Comment by gunjanddave** [comment]
> > https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/mkgraph_lookahead.sh
> 
> I am executing installl_srilm.sh. But facing the below issue. For this what I am missing which has not been installed on my machine.
> 
> `echo "GNU awk is not installed so SRILM will probably not work correctly: refusing to install" && exit 1;`

This would be resolved after the installation of gawk

**Comment by gunjanddave** [comment]
I want to know one thing. After compiling the graph successfully which files do I need to replace in the model's folder?

How to add new words in the data? Just adding a word in lexicon.txt would be enough? If yes, Is there any process to create a lexicon file ?

**Comment by nshmyrev** [comment]
> After compiling the graph successfully which files do I need to replace in the model's folder?

the files in the graph folder

> How to add new words in the data? Just adding a word in lexicon.txt would be enough? 

You need to add words both to the language model and the lexicon

> If yes, Is there any process to create a lexicon file ?

You can write it yourself by hand or use g2p tool like phonetisaurus

**Comment by gunjanddave** [comment]
@nshmyrev  I am able to compile the graph successfully using https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz but when I am replacing the files from graph folder to vosk-small-model/graph folder and testing on mobile device.

I am seeing below crash

`09-08 13:19:50.691 3512-4067/org.kaldi.demo E/VoskAPI: TypeOfPhone():lat/word-align-lattice.h:149) Phone 169 was not specified in word-boundary file (or options)
09-08 13:19:50.700 3512-4067/org.kaldi.demo E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
09-08 13:19:50.700 3512-4067/org.kaldi.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4067 (Thread-179)`

**Comment by nshmyrev** [comment]
> 09-08 13:19:50.691 3512-4067/org.kaldi.demo E/VoskAPI: TypeOfPhone():lat/word-align-lattice.h:149) Phone 169

Looks like you introduced extra phone, you should use existing phoneset.

**Comment by gunjanddave** [comment]
I have not made any changes to the phone set. Attaching the phone folder from path en-android-compile-graph/db
[phone.zip](https://github.com/alphacep/vosk-api/files/5188521/phone.zip)

But yes I have added more text words in db/robinson.txt and db/robinson.txt.clean

**Comment by nshmyrev** [comment]
You introduced new phones in lexicon.txt

**Comment by gunjanddave** [comment]
As lexicon.txt is created automatically 
dict.py db/robinson.txt.clean db/cmudict.dict > data/dict/lexicon.txt

So, as I had made a change in robinson.txt.clean (Corpus) data which is adding new phones to lexicon.txt and leading to this issue which I am assuming. So what you suggest here If I need to add new data or words?

**Comment by nshmyrev** [comment]
You need to review what is created automatically and compare lang/phones.txt to see what is different at phone 169.

**Comment by gunjanddave** [comment]
Here is the phones.txt at lang/phones.txt and also attached word_boundary file. As per the error, I can see that phone 169 is not specified in this work_boundary. It only has 166.

[word_boundary.int.zip](https://github.com/alphacep/vosk-api/files/5189535/word_boundary.int.zip)

[phones.txt](https://github.com/alphacep/vosk-api/files/5189510/phones.txt)

**Comment by nshmyrev** [comment]
> Here is the phones.txt at lang/phones.txt and also attached word_boundary file. As per the error, I can see that phone 169 is not specified in this work_boundary. It only has 166.

It is a bad thing obviously, phones must match I told you few comments above

**Comment by gunjanddave** [comment]
@nshmyrev  Thank you so much. I am able to resolve this. By correcting the file which I was using a input data.

I wanted to know. Is it possible to compile a graph on phone(android)?

**Comment by nshmyrev** [comment]
> I wanted to know. Is it possible to compile a graph on phone(android)?

We do not support this feature yet

**Comment by gunjanddave** [comment]
It is possible?

**Comment by nshmyrev** [comment]
Yes, sure

**Comment by gunjanddave** [comment]
Is any guide available? I would like to implement this learning and developing approach.

**Comment by gunjanddave** [comment]
@nshmyrev How to generate clean data from any data set? like robinson.txt.clean

**Comment by gunjanddave** [comment]
@nshmyrev Using this model https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz I have added new words. Does this have a dynamic graph?

**Comment by nshmyrev** [comment]
> I have added new words. Does this have a dynamic graph?

Yes

**Comment by FirasHm** [comment]
@nshmyrev, the link https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz does not work. Could you load it please?

**Comment by joaodamastdx** [comment]
Also looking for this [https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz](https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz) @nshmyrev !

**Comment by nshmyrev** [comment]
Hello everyone. To get the package please mail us contact@alphacephei.com and describe the details about your project.

**Comment by mukeshbadgujar** [comment]
i had also issue on running Vosk Language Model Adaptation Please Help

i have downloaded US English - https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-compile.zip
after creating Kaldi Setup on Ubuntu 20, and Given Path of Kaldi to Vosk and runs
I checked Kaldi setup is Working by ./run.sh in /kaldi/egs/mini_librispeech/s5

i added 2 words for test in db/extra.txt and 

 ./compile-graph.sh

Error >>

kaldi::KaldiFatalError
+ rnnlm/change_vocab.sh data/lang/words.txt exp/rnnlm exp/rnnlm_out
rnnlm/change_vocab.sh: Copying config directory.
rnnlm/change_vocab.sh: Re-generating words.txt, unigram_probs.txt, word_feats.txt and word_embedding.final.mat.
rnnlm/get_word_features.py: made features for 368710 words.
rnnlm-get-word-embedding exp/rnnlm_out/word_feats.txt exp/rnnlm_out/feat_embedding.final.mat exp/rnnlm_out/word_embedding.final.mat 
+ utils/mkgraph_lookahead.sh --self-loop-scale 1.0 data/lang exp/chain/tdnn data/en-mix-small.lm.gz exp/chain/tdnn/lgraph
utils/mkgraph_lookahead.sh : compiling grammar data/en-mix-small.lm.gz
utils/mkgraph_lookahead.sh : expected data/en-mix-small.lm.gz to exist
