### ISSUE TITLE
why the file "final.ie" in big and small model differ so much?  such  as Chinese  model vosk-model-cn-0.1.zip vs vosk-model-small-cn-0.3

### ISSUE THREAD

**Issue by l2009312042** [alphacep/vosk-api#199]
i  have download  the model from  https://alphacephei.com/vosk,  

i conver the final.ie  to txt by  
''' 
ivector-extractor-copy --binary=false final.ie ie.txt
'''
,and the txt size as follow :
       in vosk-model-cn-0.1.zip,the final.ie size is 28m, 
and in vosk-model-small-cn-0.3,the final.ie size is 11m ,why the two differ so much ? 

the content is nearly the same ,which is confusing me

**Comment by nshmyrev** [comment]
> why the two differ so much 

small model uses ivector dim 30 for fast calculation on mobile phone

big model uses more common ivector dim 100 for more accuracy (sometimes).

**Comment by l2009312042** [comment]
yes  i see it  thank  you  close
