### ISSUE TITLE
Missing install_openfst.sh

### ISSUE THREAD

**Issue by HorstBaerbel** [alphacep/vosk-api#20]
See [this pulll request](https://github.com/alphacep/kaldi/pull/1). Make sure you mention it in the [README](https://github.com/alphacep/vosk-api/blob/master/README.md#L43).

**Comment by nshmyrev** [comment]
Hi. Openfst is installed in kaldi when you run make in tools. There is no need for a separate script I think.

**Comment by HorstBaerbel** [comment]
No. It didn't .configure for me. It told me OpenFst was not found. I'm running Ubuntu 19.10.
