### ISSUE TITLE
Update models

### ISSUE THREAD

**Issue by verloka** [alphacep/vosk-api#201]
Есть какие нибудь туториалы как обновить модель?

1. Улучшить распознание некоторых слов, которые модель иногда распознает плохо.
2. Добавить новые слова, которые модель не знает?

**Comment by nshmyrev** [comment]
https://alphacephei.com/vosk/adaptation

**Comment by verloka** [comment]
> https://alphacephei.com/vosk/adaptation

Правильно ли я понимаю - это будет работать для любой модели c [этой](https://alphacephei.com/vosk/models) страницы. Например для [этой](https://alphacephei.com/vosk/models/vosk-model-ru-0.10.zip)?

**Comment by nshmyrev** [comment]
Для большой модели будет работать большая адаптация:

https://alphacephei.com/vosk/adaptation#updating-words-and-the-vocabulary-in-the-big-models

**Comment by verloka** [comment]
> Для большой модели будет работать большая адаптация:
> 
> https://alphacephei.com/vosk/adaptation#updating-words-and-the-vocabulary-in-the-big-models

Благодарю за ответы!
