### ISSUE TITLE
[QUESTION] Is Vosk useable for my usecase?

### ISSUE THREAD

**Issue by DeRealMorgan** [alphacep/vosk-api#202]
The infos on github and on the homepage are good but can you answer these questions directly for me please:

My usecase: 
I need to listen for a keyword to then translate numbers to text. 
Example: "hey calculator, forty-five, sixty, eighty"
Is it possible to continuously listen to this keyword and start the speech to text process then?

I saw you can install an "offline dictionary" with limited words for 50mb per language. Is it possible to provide an own set of words (as I only need the keyword and numbers from 1-100) ?
Also how would it behave if there are words which it cannot understand (especially with this limited set of words)?

The listening should be continuous and only if the app is opened. Is that possible?
Also how is the battery consumption on smartphones? (As the default options like SpeechRecognizer are quite heavy)?

Many thanks in advance!

**Comment by nshmyrev** [comment]
> Is it possible to continuously listen to this keyword and start the speech to text process then?

We do not support keyword spotting yet, see https://github.com/alphacep/vosk-api/issues/107, you can use external library meanwhile

> I saw you can install an "offline dictionary" with limited words for 50mb per language. Is it possible to provide an own set of words (as I only need the keyword and numbers from 1-100) ?

Yes, you can update the words in Gr.fst with https://alphacephei.com/vosk/adaptation#updating-the-language-model

> Also how would it behave if there are words which it cannot understand (especially with this limited set of words)?

You can add [unk] word so it will handle the rest of noises

> The listening should be continuous and only if the app is opened. Is that possible?

You can try but probably it will be very battery consuming. You have to figure that out yourself.

**Comment by nshmyrev** [comment]
Essentially the same as #107, stay tuned.
