### ISSUE TITLE
the res['spk'] output in the c example is inconsistent with the res['spk'] output in the Python example

### ISSUE THREAD

**Issue by bin872686** [alphacep/vosk-api#203]
Hello,I did a comparison with the same audio. Under the same circumstances, the res['spk'] output in the c example is inconsistent with the res['spk'] output in the Python example.
 In the c example, the difference in cosine distance of different speakers is very small, and their spk_sig is almost equal to the same value. I found that the sample-frequency in spkmodel's mfcc.conf is 8k, and speechmodel only supports 16k, which makes me very confused. I would be very grateful if I could receive your reply.

**Comment by nshmyrev** [comment]
Overall one has to debug this - setup voxceleb properly, setup EER test with vosk code and get some EER estimation. No time for this right now, maybe some times later this month.

If you want to help with this, try to get EER with kaldi setup first.

**Comment by bin872686** [comment]
Thanks for your answer.   I am still a little confused

The spkmodel in vosk comes from http://kaldi-asr.org/models/m6. My previous comparison is based on this model.
Is your suggestion to replace m6 with m7?

I found that m7 has got EER (EER: 3.1%) through Kaldi. Do I need to perform EER test under vosk? Then debug this during the ERR test.

All in all,  I need to make some changes in vosk to get good results

**Comment by nshmyrev** [comment]
> Do I need to perform EER test under vosk?

Yes, you need to run the same test in vosk with the same models as you do in kaldi and compare the numbers.

**Comment by lalimili6** [comment]
I have some experiments in speaker identification using vosk code and compare result to Kaldi.
I use Kaldi pre-train voxceleb speaker verification model (https://kaldi-asr.org/models/m7) and using plda for the backend.
I extract xvectors from vosk and Kaldi and compute eer, here results:
```
Kaldi:  Equal error rate is 18.0198%, at threshold -1.61988
vosk: Equal error rate is 46.7987%, at threshold 52.362
```

vosk compute xvectors every endpoint, I mean them, however, my dataset is short, and voices almost are about 2 seconds. I think If we extract xvectors in vosk and train a plda it must better.

@bin872686 
can you share your result in vosk too? 

best regards

**Comment by nshmyrev** [comment]
I have pushed a proper fix, now it should be working. You need to update the model though to [vosk-model-spk-0.4](https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip)

https://github.com/alphacep/vosk-api/commit/41035485dbcabfc9978876c7c36e1c83f64a9c4e

**Comment by rafiuddinkhan** [comment]
Thanks, @nshmyrev I will try and compare the results.

**Comment by bin872686** [comment]
Thanks a lot，@nshmyrev .  Based on your solution, I successfully used the obtained out_xvector for plda scoring, and the distinction between different speakers was significantly improved.

I have been trying to use voxceleb to score plda, but there are always some error messages. These errors are related to dimensions.
When I saw your solution, I made some modifications as "you whiten the vector with global mean and transform and normalize mean". But there are still errors
The error is as follows:
ASSERTION_FAILED (VoskAPI:AddMatVec():kaldi-vector.cc:98) Assertion failed: ((trans == kNoTrans && M.NumCols() == v.dim_ && M.NumRows() == dim_) || (trans == kTrans && M.NumRows() == v.dim_ && M.NumCols() == dim_))
This error occurred in xvector.AddMatVec()when transforming the mean

I found that the dimension of the vector derived from the voxceleb model is 512. When replacing the spkmodel with the voxceleb model, do I need to make any changes? I just made the changes in mfcc.conf "num-ceps=30 num-mel-bins= 30"

**Comment by nshmyrev** [comment]
> When replacing the spkmodel with the voxceleb model, do I need to make any changes?

You need to extract the model with extract.config, did you do that?

**Comment by bin872686** [comment]
Yes , i have done that

**Comment by pukhrajp** [comment]
> 
> 
> I have pushed a proper fix, now it should be working. You need to update the model though to [vosk-model-spk-0.4](https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip)
> 
> [4103548](https://github.com/alphacep/vosk-api/commit/41035485dbcabfc9978876c7c36e1c83f64a9c4e)

Hi,
Vosk-api is very good for offline recognition, thanks for this, i tried the speaker test with latest pip install version it works once we disable the last print statements.
is there a binary with the latest commits, I want to test on rpi4, and kaldi is not compiling.
If there is a whl file for the latest commit i can install it with pip and test.

**Comment by nshmyrev** [comment]
Latest version 0.3.18 should have all updates.
