### ISSUE TITLE
[QUESTION] : potability of java compilation

### ISSUE THREAD

**Issue by abhiman84** [alphacep/vosk-api#204]
Hi,

I successfully compiled libvosk_jni.so from java folder following the instructions given in that folder on an ubuntu machine (16.04).  I intend to use the java vosk-api on a target machine (Red Hat) which is not connected to the internet. Java is installed on the target machine. Therefore, I copied the pre-compiled libvosk_jni.so and the generated .java files on the target machine.  

 I execute the following  command on the target machine to test the api:

`java -Djava.library.path=. -cp . test.DecoderTest`

I get the following error:  

```
A fatal error has been detected by the Java Runtime Environment:
Java VM: OpenJDK 64-Bit Server VM (25.222-b03 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [libvosk_jni.so+0x697bb0]  cblas_dscal+0x0
An error report file with more information is saved as:
/home/asr/hs_err_pid7906.log
If you would like to submit a bug report, please visit:
 http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.
```

The log file mentioned in the error message is attached in this post.

1. My question is , is it possible to use libvosk_jni.so on one machine on another machine which might have different gcc and gfortran version ?

2. If yes, then could you kindly look into this error and suggest a resolution so that I can use vosk api on a different system than the one on which it is compiled ?

[hs_err_pid7906.log](https://github.com/alphacep/vosk-api/files/5160259/hs_err_pid7906.log)

**Comment by nshmyrev** [comment]
Format your question properly first

**Comment by abhiman84** [comment]
Hi ,

I have edited my post (as seen above and I hope it is more readable now )
Thanks.

**Comment by nshmyrev** [comment]
You need to format log with the code marks like this:

```
this is code
```

**Comment by abhiman84** [comment]
Hi, you may look at it again now. Thanks.

**Comment by nshmyrev** [comment]
SIGILL in your means you compiled it for newer CPU than you are trying to run it and some instructions are not supported. You can recompile openblas with dynamic architecture DYNAMIC_ARCH=1 to avoid this as in:

https://github.com/alphacep/vosk-server/blob/fb9b937da41a4625fdba98d1621ed29ea72b2b79/docker/Dockerfile.kaldi-vosk-server#L37

**Comment by abhiman84** [comment]
Thanks a lot ! It solved the issue.

**Comment by nshmyrev** [comment]
Ok, great!
