### ISSUE TITLE
[Support] Cross-compile WebRTC with cross vosk api docker

### ISSUE THREAD

**Issue by AlexTraan** [alphacep/vosk-api#205]
Hi,

I am try to cross-compile webrtc library with cross vosk docker (https://github.com/alphacep/vosk-api/blob/master/travis/Dockerfile.dockcross), it can be build success but when i run a simple test (on ARM7 board), i faced as below error:
"(gdb) r
Starting program: /root/workspace/vosk_api/webrtc/src/out/Default/tools_unittests 

Program received signal SIGSEGV, Segmentation fault.
0x76fdf218 in relocate_pc24 (value=1420468224, addend=<optimized out>, map=0x76fff968)
    at ../ports/sysdeps/arm/dl-machine.h:337
337	../ports/sysdeps/arm/dl-machine.h: No such file or directory.
(gdb) 
"
I already googled but not solved yet. would be great if anyone have idea/direction to help me?

**Comment by nshmyrev** [comment]
What is webrtc library? How vosk is related? what is tools_unittests? we do not have anything like that in our codebase.

You need to provide more information if you need help.

**Comment by AlexTraan** [comment]
Hi @nshmyrev,

1> "What is webrtc library?"
>> I would like to mention this: https://chromium.googlesource.com/external/webrtc/

2> "How vosk is related? "
>> This not directly related to vosk, i just use webrtc (audio processing part) and vosk in my target application

3> "what is tools_unittests?"
>> This is one test example output when i try to build webrtc, tools_unittets live in webrtc codebase

In general, it seem my question raise in wrong place (because this not much relevant to vosk), i will close this.

Thank you
>>

**Comment by nshmyrev** [comment]
@AlexTraan you can use https://github.com/alphacep/vosk-server/blob/master/webrtc/asr_server_webrtc.py

**Comment by AlexTraan** [comment]
@nshmyrev Thank for your link, but my program based on C/C++, so it seem not fit with my target
