### ISSUE TITLE
Package android models for bintray

### ISSUE THREAD

**Issue by nshmyrev** [alphacep/vosk-api#207]
So we can simply plug a language with dependencies

**Comment by gunjanddave** [comment]
@nshmyrev 
Added vosk-model-small-en-us-0.3 model packaged as bintray and would add more later on.

Gradle Dependency
implementation 'com.kaldi.models:VoskAPI-Kaldi-Model:1.0.1'

https://dl.bintray.com/gunjanddave/VoskAPI-Kaldi-Model

**Comment by nshmyrev** [comment]
Thank you @gunjanddave. Looks nice! I will try to do similar things!

**Comment by gunjanddave** [comment]
I have pushed the bintray.gradle code on this forked branch https://github.com/gunjanddave/vosk-android-demo.git

**Comment by nshmyrev** [comment]
Cool. It would be also cool to read assets directly from zip file. Time to look on zlib integration into C code for that.

**Comment by gunjanddave** [comment]
Let me have a look.

**Comment by nshmyrev** [comment]
We now distribute Vosk on mavencentral, bintray is not really relevant
