### ISSUE TITLE
(android)Looking forward for speakerid

### ISSUE THREAD

**Issue by coolsou** [alphacep/vosk-api#208]
need this,Thanks a lot!

**Comment by nshmyrev** [comment]
I have just pushed AAR to bintray with the spk fixes, now it should work. You can simpy initialize recognizer with spk model here:

https://github.com/alphacep/vosk-android-demo/blob/4854ecf3c8888348d7cb4f54b2683b076cd524ed/app/src/main/java/org/kaldi/demo/KaldiActivity.java#L274

**Comment by nshmyrev** [comment]
Let me know if you have further questions
