### ISSUE TITLE
Problem building Python module

### ISSUE THREAD

**Issue by HorstBaerbel** [alphacep/vosk-api#21]
I'm having an error similar to #17 here. I've compiled kaldi from git and try to build the python module. I don't do that with `python3 setup.py install`, because that needs super-user rights on my system and will fail because KALDI_ROOT is only exported for the current user. I do `python3 setup.py build`. But get the error:

> [ 80%] Building CXX object CMakeFiles/_vosk.dir/home/magic/vosk-api/src/model.cc.o
> /usr/bin/c++  -D_vosk_EXPORTS -I/home/magic/vosk-api/python/../src -I/home/magic/kaldi/src -I/home/magic/kaldi/tools/openfst/include -I/usr/include/python3.7m  -O3 -DFST_NO_DYNAMIC_LINKING  -O3 -DNDEBUG -fPIC   -o CMakeFiles/_vosk.dir/home/magic/vosk-api/src/model.cc.o -c /home/magic/vosk-api/src/model.cc
> make[3]: *** Keine Regel vorhanden, um das Ziel „/home/magic/kaldi/src/online2/kaldi-online2.a“, 
>   benötigt von „../lib.linux-x86_64-3.7/vosk/_vosk.so“, zu erstellen.  Schluss.

Any hints on what the error is and hints on installing afterwards?

**Comment by nshmyrev** [comment]
The file /home/magic/kaldi/src/online2/kaldi-online2.a should exist if you compiled kaldi properly and specified the KALDI_ROOT path.

For sudo you can add -E to preserve environment variables.

If you have troubles to build software, it is often easier to use `pip install`

**Comment by HorstBaerbel** [comment]
So does this mean "pip3 install vosk-api" does install kaldi too? I though I could install only vosk-api and had to build kaldi on my own...

About the error: It failed building kaldi-online2.a

**Comment by nshmyrev** [comment]
`pip3 install vosk` installs everything required including kaldi.

**Comment by HorstBaerbel** [comment]
Doh. Ok. Maybe mention it in the README for dummies like me... ;)

**Comment by nshmyrev** [comment]
Ok, done
