### ISSUE TITLE
Error in "make run" for java

### ISSUE THREAD

**Issue by kromoxpro** [alphacep/vosk-api#210]
Hello,

I am following the following steps to use Vosk in Java:

1. Build recent kaldi
2. git clone https://github.com/alphacep/vosk-api
3. cd vosk-api/java
4. export KALDI_ROOT=<KALDI_ROOT>
5. export JAVA_HOME=<JAVA_HOME>
6. make
7. make run

When i try to use "make run" i get the following error:

`unzip vosk-model-spk-0.3.zip && rm vosk-model-spk-0.3.zip`
`Archive:  vosk-model-spk-0.3.zip`
`   creating: vosk-model-spk-0.3/`
`  inflating: vosk-model-spk-0.3/final.ext.raw`
`  inflating: vosk-model-spk-0.3/mfcc.conf`
`mv vosk-model-spk-0.3 model-spk`
`javac test/*.java org/kaldi/*.java`
`java -Djava.library.path=. -cp . test.DecoderTest`
`java: symbol lookup error: **********/Vosk/java/vosk-api/java/libvosk_jni.so: undefined symbol: vdPowx`
`make: *** [Makefile:65: run] Error 127`

Additional Information:

When i was bulding Kaldi (first step) I used the following commands:

Starting from "tools" folder:

`make -j 8 openblas`
`make`
`cd ../src/`
`./configure --shared`
`make depend -j 8`
`make -j 8`

Another question, I have seen that there is an example to use Vosk with Java importing Audio files. How can I use vosk using the Microphone in java?

Thank you very much.

**Comment by nshmyrev** [comment]
> ./configure --shared

add --mathlib=OPENBLAS as in https://alphacephei.com/vosk/install

> Another question, I have seen that there is an example to use Vosk with Java importing Audio files. How can I use vosk using the Microphone in java?

Just like the file, read chunk by chunk from the TargetLine and pass into the recognizer.

**Comment by kromoxpro** [comment]
Thanks @nshmyrev , I was able to compile the java module.

Now trying to run the test code (DecoderTest.java) in my own project, I get the following error:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: no vosk_jni in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]`

when the line is executed:

`Vosk.SetLogLevel(-10);`

What I did was copy the folder "org" that is inside `vosk-api/ java/` in my project (Using IntelliJ IDEA). Am I missing something?

**Comment by nshmyrev** [comment]
Set java.library.path in project properties or command line or copy libvosk_jni.so file to one of the folders above. See the run command in java/Makefile:

```
java -Djava.library.path=. -cp . test.DecoderTest
```

**Comment by nshmyrev** [comment]
@kromoxpro still relevant? Feel free to reopen.
