### ISSUE TITLE
MRCP Deployment

### ISSUE THREAD

**Issue by amolinero** [alphacep/vosk-api#211]
Hi,
we are trying to deploy vosk in integration with IVR via MRCP. We have seen UNIMRCP plugin is available for that but we have not found any info about hoy to deploy it the complete stack. Is there info about it? 

thanks in advance!

**Comment by nshmyrev** [comment]
Hi

I don't think we will support unimrcp in the long term, we recommend vosk-asterisk which is more straightforward. The plugin is here in vosk-plugin branch:

https://github.com/alphacep/unimrcp-vosk-plugin/tree/vosk-plugin/plugins/kaldi-recog/src

you compile it and then run the unimrcp server and thats it. The corresponding plugin is already enabled in config:

https://github.com/unispeech/unimrcp/compare/master...alphacep:vosk-plugin

it is not very actively supported code though.

**Comment by amolinero** [comment]
Hi Nickolay,
it would be great using vosk-asterisk but we have already in the customer an IVR (MRCP Enable) connect to a Avaya PBX, so i understand only way to integrate for ASR via Vosk is using UniMRCP plugin. Is there any other way? What it would be recommended deployment for IVRs (cisco, avaya, etc.)?

thanks

**Comment by nshmyrev** [comment]
> in the customer an IVR (MRCP Enable) connect to a Avaya PBX

I see. Well, the plugin will probably work. Please try to compile it from the branch and let me know how it goes. If there will be issues we can fix them!

**Comment by amolinero** [comment]
We wil be using this info to compile your UniMRCP code: https://www.unimrcp.org/manuals/html/InstallationManual.html and deploy in CentOS 7 box. About bosk server, it must be deploye in same box? Where UniMRCP server (and plugin) is looking for Vosk services?

**Comment by nshmyrev** [comment]
> We wil be using this info to compile your UniMRCP code: https://www.unimrcp.org/manuals/html/InstallationManual.html and deploy in CentOS 7 box.

Ok, looks good but remember you also need to compile Kaldi first and edit kaldi path in unimrcp makefile.

> Where UniMRCP server (and plugin) is looking for Vosk services?

The unimrpc Vosk plugin doesn't look for Vosk services, it uses the model directly loading it into memory.

**Comment by amolinero** [comment]
> The unimrpc Vosk plugin doesn't look for Vosk services, it uses the model directly loading it into memory.

you mean in the UniMRCP plugin is Vosk server embeded? or do we install previously vosk server and plugin will communicate with it?

**Comment by nshmyrev** [comment]
Yes, it is embedded, you do not need a separate vosk server.

**Comment by amolinero** [comment]
next steps, to compile kaldi from centos7 (following description in 'Kaldi compilation for local python, node and java modules'):
- git clone -b lookahead --single-branch https://github.com/alphacep/kaldi
- cd kaldi/tools
- make

some errors generated in compilation (attached file)

[kaldi_compilation_errors.log](https://github.com/alphacep/vosk-api/files/5208280/kaldi_compilation_errors.log)

**Comment by nshmyrev** [comment]
Yeah, I remember this issue, this is a centos compiler which is pretty old. Maybe you can install newer gcc on centos first or try on debian.

**Comment by amolinero** [comment]
The gcc installed is in newest version:

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.prometeus.net
 * extras: mirrors.prometeus.net
 * updates: mirrors.prometeus.net
Package gcc-4.8.5-39.el7.x86_64 already installed and latest version
Nothing to do

any idea?

**Comment by nshmyrev** [comment]
> Package gcc-4.8.5-39.el7.x86_64 already installed and latest version

This is very old GCC. Try to install GCC7.0 or GCC8. You can get them from external repositories.

**Comment by amolinero** [comment]
Finally we managed to install GCC7 in CentOS7 and compile kaldi ("All done OK." message at last), anyway to check is properly installed? About next step is clone https://github.com/alphacep/unimrcp-vosk-plugin/tree/vosk-plugin and compile it. you talked about "and edit kaldi path in unimrcp makefile", can you give more detail?

**Comment by nshmyrev** [comment]
Here https://github.com/alphacep/unimrcp-vosk-plugin/blob/cca9851f20fb6025562b0c9c62ae97b720f65c2f/plugins/kaldi-recog/Makefile.am#L4

**Comment by amolinero** [comment]
Great. About to check is kaldi is properly installed, is there any way?

**Comment by amolinero** [comment]
Hi Nickolay,
we have compiled properly master branch of https://github.com/alphacep/unimrcp-vosk-plugin.git and make some execution tests, everything was right except in this default branch is not the vosk plugin code hehe
So we have cloned 'vosk-plugin' branch this time and getting this compile error of the plugin:

_*** Warning: Linking the shared library kaldirecog.la against the
*** static library /opt/kaldi/kaldi/src/base/kaldi-base.a is not portable!
g++: error: /opt/kaldi/kaldi/src/online2/kaldi-online2.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/decoder/kaldi-decoder.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/ivector/kaldi-ivector.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/gmm/kaldi-gmm.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/nnet3/kaldi-nnet3.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/tree/kaldi-tree.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/feat/kaldi-feat.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/lat/kaldi-lat.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/hmm/kaldi-hmm.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/transform/kaldi-transform.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/cudamatrix/kaldi-cudamatrix.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/matrix/kaldi-matrix.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/fstext/kaldi-fstext.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/util/kaldi-util.a: No such file or directory
g++: error: /opt/kaldi/kaldi/src/base/kaldi-base.a: No such file or directory
make[2]: *** [Makefile:474: kaldirecog.la] Error 1
make[2]: se sale del directorio '/opt/unimrcp-vosk-plugin/plugins/kaldi-recog'
make[1]: *** [Makefile:372: all-recursive] Error 1
make[1]: se sale del directorio '/opt/unimrcp-vosk-plugin/plugins'
make: *** [Makefile:419: all-recursive] Error 1_ 

the path for kaldi is right, this is the content of the folder:

[root@vosk unimrcp-vosk-plugin]# cd /opt/kaldi/kaldi/src/
[root@vosk src]# ls
base      configure       cudafeatbin  Doxyfile  fstbin  gst-plugin  ivector     lat     Makefile   nnet2     nnetbin  online2bin  rnnlmbin  tfrnnlmbin  util
bin       cudadecoder     cudamatrix   feat      fstext  hmm         ivectorbin  latbin  makefiles  nnet2bin  NOTES    onlinebin   sgmm2     TODO
chain     cudadecoderbin  decoder      featbin   gmm     INSTALL     kws         lm      matrix     nnet3     online   probe       sgmm2bin  transform
chainbin  cudafeat        doc          fgmmbin   gmmbin  itf         kwsbin      lmbin   nnet       nnet3bin  online2  rnnlm       tfrnnlm   tree

It seems some paths are missing.

thanks

**Comment by nshmyrev** [comment]
My friend, you didn't compile kaldi since the files are missing. Return back to kaldi compilation and make sure the libraries are there.

**Comment by amolinero** [comment]
i did compile kaldi, as a said in previous post, and installation finishes like 'All done OK.' (you have compile log attached). I think the problem is the way to link this libraries, this is from uniMRCP compile (also compile log attached):

*** Warning: Linking the shared library kaldirecog.la against the
*** static library /opt/kaldi/kaldi/src/online2/kaldi-online2.a is not portable!

[make_unimrcp.log](https://github.com/alphacep/vosk-api/files/5212374/make_unimrcp.log)
[make_kaldi.log](https://github.com/alphacep/vosk-api/files/5212375/make_kaldi.log)

**Comment by nshmyrev** [comment]
> make_kaldi.log

This is not kaldi log, this is tools log. You missed these commands:
```
extras/install_openblas.sh
cd ../src
./configure --mathlib=OPENBLAS --shared --use-cuda=no
make -j 10
```

**Comment by amolinero** [comment]
After installation of lot of dependencies packages and rpms i have managed to make uniMRCP with kaldi plugin. But now when i am starting unimrcp and is loading plugins:

_2020-09-12 05:17:22:027319 [INFO]   Load Plugin [Kaldi-Recog-1] [/usr/local/unimrcp/plugin/kaldirecog.so]
2020-09-12 05:17:22:030337 [WARN]   Failed to Load DSO: /lib64/libblas.so.3: undefined symbol: ATL_zger2u_

After, making a test from uniMRCP for recognition proccess i am getting:

_2020-09-12 05:21:42:549727 [NOTICE] Add Session <84343016f4f211ea>
2020-09-12 05:21:42:549739 [INFO]   Receive Offer 0x7fe800001b18 <84343016f4f211ea> [c:1 a:1 v:0]
2020-09-12 05:21:42:549747 [WARN]   Failed to Find MRCP Engine for Resource [speechrecog] 0x7fe800001b18 <84343016f4f211ea>
2020-09-12 05:21:42:549750 [WARN]   Failed to Create Engine Channel 0x7fe800001b18 <84343016f4f211ea> [speechrecog]
2020-09-12 05:21:42:549918 [INFO]   Add Pending Control Channel <84343016f4f211ea@speechrecog> [1]
2020-09-12 05:21:42:552256 [INFO]   Enable RTP Session 127.0.0.1:5000
2020-09-12 05:21:42:552365 [INFO]   Send Answer 0x7fe800001b18 <84343016f4f211ea> [c:1 a:1 v:0] Status Not Acceptable
2020-09-12 05:21:42:553246 [INFO]   Receive SIP Event [nua_i_state] Status 406 Not Acceptable [SIP-Agent-1]
2020-09-12 05:21:42:553256 [NOTICE] SIP Call State 0x7fe800001b18 [terminated]
2020-09-12 05:21:42:553265 [INFO]   Receive SIP Event [nua_i_terminated] Status 406 Not Acceptable [SIP-Agent-1]
2020-09-12 05:21:42:553378 [INFO]   Deactivate Session 0x7fe800001b18 <84343016f4f211ea>
2020-09-12 05:21:42:553386 [INFO]   Terminate Session 0x7fe800001b18 <84343016f4f211ea>
2020-09-12 05:21:42:553480 [INFO]   Remove Pending Control Channel <84343016f4f211ea@speechrecog> [0]
2020-09-12 05:21:42:562308 [INFO]   Remove RTP Session 127.0.0.1:5000
2020-09-12 05:21:42:562365 [NOTICE] Remove Session <84343016f4f211ea>
2020-09-12 05:21:42:562370 [INFO]   Session Terminated 0x7fe800001b18 <84343016f4f211ea>
2020-09-12 05:21:42:562415 [NOTICE] Destroy Session <84343016f4f211ea>_

any idea to fix it?

**Comment by amolinero** [comment]
Update. New installation over CentOS 8. I have managed to make everything (kaldi tools, kaldi, uniMRCP dependencies, uniMRCP). Starting unimrcp found:

2020-09-13 06:23:59:658150 [INFO]   Load Plugin [Kaldi-Recog-1] [/usr/local/unimrcp/plugin/kaldirecog.so]
2020-09-13 06:23:59:672596 [WARN]   Failed to Load DSO: /usr/local/unimrcp/plugin/kaldirecog.so: undefined symbol: _ZTVN5kaldi27ConstArpaLmDeterministicFstE

Confirmed the file is avaible in that path:

<img width="471" alt="imagen" src="https://user-images.githubusercontent.com/3083779/93015896-747a0800-f5bd-11ea-9cc3-a9d4938dae13.png">

any ideas?

**Comment by nshmyrev** [comment]
Add a line here:

https://github.com/alphacep/unimrcp-vosk-plugin/blob/cca9851f20fb6025562b0c9c62ae97b720f65c2f/plugins/kaldi-recog/Makefile.am#L23

```
$(KALDI_ROOT)/src/lm/kaldi-lm.a \
```

**Comment by amolinero** [comment]
Added that line. Executed 'make' for uniMRCP again and 'make install' with success. Starting uniMRCP now we have:

_2020-09-13 06:50:16:550268 [INFO]   Load Plugin [Kaldi-Recog-1] [/usr/local/unimrcp/plugin/kaldirecog.so]
2020-09-13 06:50:16:594808 [WARN]   Failed to Load DSO: /usr/local/unimrcp/plugin/kaldirecog.so: undefined symbol: ssptri__

**Comment by nshmyrev** [comment]
I pushed some updates to vosk-api repo, update and try again.

**Comment by amolinero** [comment]
updated. Execution:

_2020-09-13 10:48:48:392171 [INFO]   Load Plugin [Kaldi-Recog-1] [/usr/local/unimrcp/plugin/kaldirecog.so]
LOG (VoskAPI:ReadDataFiles():src/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():src/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: /opt/kaldi/model/mfcc.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (`core' generado)_

**Comment by nshmyrev** [comment]
You need to unpack the model to that folder

**Comment by amolinero** [comment]
sorry, i am newbie with kaldi, how can i unpack any model to that folder?

**Comment by nshmyrev** [comment]
> sorry, i am newbie with kaldi, how can i unpack any model to that folder?

```
wget <url>
unzip filename.zip
sudo mv filename /opt/kaldi/model
```

**Comment by amolinero** [comment]
The plugin is looking for that /opt/kaldi/model/mfcc.conf, is that path hardcoded? i mean, i have downloaded  0001_aspire_chain_model and untar as README explains:

_you should un-tar this inside the egs/aspire/s5 directory of kaldi;_

is not possible now to point to egs/aspire/s5/conf/mfcc.conf from the plugin? otherwise, what must be tree folder for the plugin?

**Comment by nshmyrev** [comment]
You should download vosk models obviously:

https://alphacephei.com/vosk/models/vosk-model-en-us-aspire-0.2.zip

path is hardcoded here:

https://github.com/alphacep/unimrcp-vosk-plugin/blob/ff4c6ade87bcc4508566e5136e7d06e290543642/plugins/kaldi-recog/src/kaldi_recog_engine.cc#L164

**Comment by amolinero** [comment]
is that needed also?

<img width="729" alt="imagen" src="https://user-images.githubusercontent.com/3083779/93100932-ff383100-f6a9-11ea-95b5-878acd841784.png">

**Comment by amolinero** [comment]
Anyway, finally i have managed to start uniMRCP and load the plugin:

_2020-09-14 10:56:40:783325 [INFO]   Load Plugin [Kaldi-Recog-1] [/usr/local/unimrcp/plugin/kaldirecog.so]
LOG (VoskAPI:ReadDataFiles():src/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():src/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00666308 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():src/model.cc:219) Loading i-vector extractor from /opt/kaldi/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():src/model.cc:235) Loading HCLG from /opt/kaldi/model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():src/model.cc:254) Loading words from /opt/kaldi/model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():src/model.cc:262) Loading winfo /opt/kaldi/model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():src/model.cc:270) Loading CARPA model from /opt/kaldi/model/rescore/G.carpa
2020-09-14 10:56:51:634460 [INFO]   Register MRCP Engine [Kaldi-Recog-1]_ 

then i have tested with umc a recog session, and crash:

_2020-09-14 10:58:06:433828 [INFO]   Receive MRCPv2 Data 127.0.0.1:1544 <-> 127.0.0.1:32896 [304 bytes]
MRCP/2.0 304 RECOGNIZE 2
Channel-Identifier: b23fe2c6f69a11ea@speechrecog
Content-Type: text/uri-list
Cancel-If-Queue: false
No-Input-Timeout: 5000
Recognition-Timeout: 10000
Start-Input-Timers: true
Confidence-Threshold: 0.5
Save-Waveform: true
Content-Length: 27

session:request1@form-level
2020-09-14 10:58:06:434052 [INFO]   Process RECOGNIZE Request <b23fe2c6f69a11ea@speechrecog> [2]
2020-09-14 10:58:06:434242 [INFO]   Open Utterance Output File [/usr/local/unimrcp/var/utter-8kHz-b23fe2c6f69a11ea.pcm] for Writing
2020-09-14 10:58:06:434671 [INFO]   Process RECOGNIZE Response <b23fe2c6f69a11ea@speechrecog> [2]
2020-09-14 10:58:06:434713 [INFO]   State Transition IDLE -> RECOGNIZING <b23fe2c6f69a11ea@speechrecog>
2020-09-14 10:58:06:434816 [INFO]   Send MRCPv2 Data 127.0.0.1:1544 <-> 127.0.0.1:32896 [83 bytes]
MRCP/2.0 83 2 200 IN-PROGRESS
Channel-Identifier: b23fe2c6f69a11ea@speechrecog


Segmentation fault (`core' generado)_


Nickolay, do you have any deployment of this (docker, vmware ova or whatever) that you can share where plugin works ?

**Comment by nshmyrev** [comment]
> Segmentation fault (`core' generado)_

You need to collect stacktrace

> Nickolay, do you have any deployment of this (docker, vmware ova or whatever) that you can share where plugin works ?

No

**Comment by amolinero** [comment]
what exact you want to be done?

**Comment by evios** [comment]
Hello Nikolay! Thank you for plugin.
Can confirm, that have same error without any issues during install.
Moreover, even client test scenario run recog (./umc) fails server with same code.
How can we collect  stackrace? And what library do you recommend for collecting?
