### ISSUE TITLE
Speaker Adaptation with Limited Data

### ISSUE THREAD

**Issue by ThThoma** [alphacep/vosk-api#212]
Hello, I've worked with CMU pocketsphinx for a while and now I'm transitioning to Vosk.
I'm really happy with the models and the recognition speed, thank you and kudos!
(especially [vosk-model-en-us-daanzu-20200905-lgraph](https://alphacephei.com/vosk/models) has >90% accuracy for my voice)

However i would like to offer the choice for my users to adapt to their environment/voice with limited audio data.
With pocketsphinx models you could [create a MLLR matrix](https://cmusphinx.github.io/wiki/tutorialadapt/) and that improved accuracy by +5-10% for the speaker.

From what i understood, vosk models are based (or similar) to Kaldi models.
So i peeked at [Kaldi transform documentation](http://kaldi-asr.org/doc/transform.html)
and i am wondering if there is a way to create and apply MLLR matrices to vosk models?

Or are MLLR matrices considered outdated now and fine tuning (with ~1hour data) is our only choice?

**Comment by nshmyrev** [comment]
Hi! Thanks for your feedback!

MLLR is not compatible anymore, you can not use it.

Our models use ivectors internally which kind of superseeds MLLR and work automatically inside, so you should not worry about that.

Finetuning is the way but not very straightforward unfortunately. But Daanzu does it sometimes with helpful results https://github.com/daanzu/kaldi-active-grammar/issues/33

See also here: https://www.quora.com/Does-adaptation-help-with-speech-recognition-accuracy

**Comment by ThThoma** [comment]
Thank you for the quick and clear response!
I will eventually look into finetuning. 

[your post](https://www.quora.com/Does-adaptation-help-with-speech-recognition-accuracy) on adaptation with modern speech recognition tool kits is enough :)
