### ISSUE TITLE
simple recognition  of specific words with VOSK

### ISSUE THREAD

**Issue by MartinsMaker** [alphacep/vosk-api#213]
Good morning/evening I'm trying to program a simple assistant in python with VOSK but I'm a little bit confused.
My idea was doing something like this:

```
if mySpeech == "hello":
   print("good morning")
```

how I can do something like this? 
I'm sorry if this question seems stupid...

**Comment by nshmyrev** [comment]
In the [microphone example](https://github.com/alphacep/vosk-api/blob/master/python/example/test_microphone.py) do like this:

```
import json

if rec.AcceptWaveform(data):
    jres = json.loads(rec.Result)
    if jres['text'] == "hello":
         print ("hello")
```

it should work. Let us know if you need other help.

**Comment by MartinsMaker** [comment]
Thank you very much

**Comment by nshmyrev** [comment]
Feel free to reopen if you have further questions
