### ISSUE TITLE
Feature Request: Go API

### ISSUE THREAD

**Issue by jdvala** [alphacep/vosk-api#214]
Go is becoming popular, so it would be good it we have a Go API for vosk as well.

**Comment by nshmyrev** [comment]
It would be great indeed!

**Comment by jdvala** [comment]
I can possibly do it, but I need to understand the structure of the project, also I don't have much experience in Go but I will give it a try

**Comment by nshmyrev** [comment]
Cool, let me know if you have any questions!

**Comment by jdvala** [comment]
Will start coding it in the weekend! Thanks for the documentation.

**Comment by agorman** [comment]
Any movement on this?

**Comment by nshmyrev** [comment]
Someone has to write it. Given we moved away from swig and now distribute simple C library libvosk, it might be even easier with https://golang.org/cmd/cgo/

**Comment by gregtzar** [comment]
@nshmyrev I was already thinking about writing a go wrapper for myself, so I'd be willing to [give it a crack](https://github.com/gregtczap/go-vosk-api). This would just be a golang interface around the `libvosk` C library right?

**Comment by gregtczap** [comment]
@nshmyrev You hosting any generated documentation for the C library?

**Comment by gregtczap** [comment]
https://github.com/gregtczap/vosk-api-go

**Comment by agorman** [comment]
@gregtczap take a look here https://github.com/zachwe/govosk. I tried for a bit and failed to get it to compile but it's worth a look.

**Comment by gregtzar** [comment]
@agorman Awesome I'll check it out

**Comment by gregtzar** [comment]
@agorman I'm currently working on generating all of the library dependencies (eg: kaldi) to get your version to compile. However, it looks like your wrapper is SWIG generated. Didn't I read somewhere that the developers of this project are no longer using SWIG? I think the wrapper may need to be re-written.

**Comment by agorman** [comment]
@gregtczap that's not my repo just something I found that I thought might be useful for you. I'm not sure of the implementation details.

**Comment by nshmyrev** [comment]
@gregtczap You do not need swig for govosk, you can simply compile with libvosk.so library.

**Comment by nshmyrev** [comment]
And you do not need to compile kaldi, you can simply use prebuilt library from here:

https://github.com/alphacep/vosk-api/releases/download/0.3.30/vosk-linux-x86-0.3.30.zip

**Comment by gregtzar** [comment]
@nshmyrev As govosk [references](https://github.com/zachwe/govosk/blob/master/govosk.go) all of the `kaldi*.a` files I was attempting to locate them to get it to build. Also my understanding of cgo is that it works best with static libraries. It might be able to use libvosk.so but apparently not in it's current state. Correct me if I'm missing something here though. If govosk builds and works fine with libvosk.so, doesn't require swig, etc, then why isn't it already just part of this repo's api wrappers?

**Comment by nshmyrev** [comment]
I have just pushed https://github.com/alphacep/vosk-api/commit/fee63d712f2512966d22b82ec4b1f8d63f447f03 to the repo. It works, but bindings are not yet complete, need more love.

**Comment by nshmyrev** [comment]
It more or less work, the major issue is to load the library as in #708 
Otherwise we are good
