### ISSUE TITLE
Ivector feature dimension mismatch

### ISSUE THREAD

**Issue by antondim** [alphacep/vosk-api#215]
Hello, 

I have installed vosk-api on a python3 virtual env with "pip3 install vosk" and not from source, in order to use Kaldi Recognizer.

While working with an english model (i.e "vosk-model-en-us-daanzu-20200905") everything seems to work smoothly. In this case, I wanna move to a different level and try vosk with Kaldi Recognizer with the given "narrowband greek model for server processing".

**Q1: Can this server model somehow be used locally like "vosk-model-en-us-daanzu-20200905" ?**

When I tried to copy it in the example folder as "model" I got the following error:

LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0205479 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:235) Loading HCLG from model/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:254) Loading words from model/words.txt
ERROR (VoskAPI:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:50) Ivector feature dimension mismatch: got -1 but network expects 30
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)

**Q2: If not, should I try work on vosk-webserver repo with it?**

I guess Q1 and Q2 are correlated.

**Comment by nshmyrev** [comment]
You just need to arrange files properly. You forgot ivector folder.

I have uploaded properly repackaged  https://alphacephei.com/kaldi/models/vosk-model-el-gr-0.7.zip, it will work without modificaitons for you.

**Comment by antondim** [comment]
Thank you for your immediate response ! Works like a charm.
