### ISSUE TITLE
Models with dynamic graph

### ISSUE THREAD

**Issue by ThThoma** [alphacep/vosk-api#217]
Hello, in the documentation for [adaptation](https://alphacephei.com/vosk/adaptation),
on section **Updating recognizer vocabulary in runtime** there is a note on which models support this modification.
Models with static graph vs models with dynamic graph.

Since i don't have enough experience, I'm looking around the models to pinpoint what makes a _dynamic graph_.
I noticed that models that allow the vocabulary modification on runtime (i.e have a dynamic graph) have
"Gr.fst" and "HCLr.fst" files, vs static models that have only a "HCLG.fst" file instead.

I would like to know what model is used by the user to either allow this vocabulary modification
 or to prevent a fatal error (kaldi::KaldiFatalError).

Is it enough to search the model directory and check if both "Gr.fst" and "HCLr.fst" files exist 
to conclude that the given model has a dynamic graph?
Or is there a different parameter/file that i should check?

**Comment by nshmyrev** [comment]
> Is it enough to search the model directory and check if both "Gr.fst" and "HCLr.fst" files exist
to conclude that the given model has a dynamic graph?

Yes

**Comment by ThThoma** [comment]
Ok, thanks for the quick response again :)

Another similar question is: 
"You can rebuild the graph in the _big_ models" 
(from **Updating words and the vocabulary in the big models**)
Are _big_ models the same as static models (i.e. have HCLG.fst file) ?

**Comment by nshmyrev** [comment]
Yes

**Comment by ThThoma** [comment]
Thank you!

closing
