### ISSUE TITLE
Accuracy of English Models

### ISSUE THREAD

**Issue by feliciatrinh** [alphacep/vosk-api#218]
Which TEDLIUM release was used to measure the accuracy of each English model listed [here](https://alphacephei.com/vosk/models)?

Thank you.

**Comment by nshmyrev** [comment]
Tedlium test data from here http://openslr.org/51/ (1157 utts)

**Comment by feliciatrinh** [comment]
Are you using the legacy corpus distribution?

**Comment by nshmyrev** [comment]
Yes!
