### ISSUE TITLE
Implement Vosk in SpeechRecognition Python package

### ISSUE THREAD

**Issue by mytja** [alphacep/vosk-api#220]
Hello @alphacep
I just want you to know, that your library has been integrated into SpeechRecognition by me.
You can see discussion here.
Since @Uberi is quite slow with updates, It will probably take a while to do it. Meanwhile, here is a library with your Vosk: https://github.com/mytja/speech_recognition
Works amazing.
You may close this issue (and also delete if you want) when you see this
Keep the good work going and congratulations for embeddment
-@mytja

**Comment by mytja** [comment]
Here it is: https://github.com/Uberi/speech_recognition/pull/513

**Comment by nshmyrev** [comment]
Great job, thank you!

I left some comments in the issue about model object that should not be shared.

Overall, we are proponents of streaming speech recognition as opposed to fixed chunks in SpeechRecognition library. It would be nice to change the overall design of SpeechRecognition to allow streaming.

**Comment by mytja** [comment]
We can do that in future...

**Comment by nshmyrev** [comment]
It has been merged some time ago. Great!
