### ISSUE TITLE
Not all Kaldi libs is compiled for Android

### ISSUE THREAD

**Issue by vgritsko** [alphacep/vosk-api#225]
Hello!
I'm trying to compile VOSK-API for Android. But it's seems not all libs is compiled from Kaldi. I see only :

1. ibkaldi-base.so
2. libkaldi-cudamatrix.so
3. libkaldi-feat.so
4. libkaldi-gmm.so  
5. libkaldi-ivector.so  
6. libkaldi-lm.so      
7. libkaldi-nnet2.so 
8. libkaldi-online2.so   
9. libkaldi-tree.so
10. libkaldi-chain.so  
11. libkaldi-decoder.so     
12. libkaldi-fstext.so  
13. libkaldi-hmm.so  
14. libkaldi-lat.so      
15. libkaldi-matrix.so 
16. libkaldi-nnet3.so 
17. libkaldi-transform.so 
18. libkaldi-util.so

There are no any errors . 
But why next libs is not compiled:
**libkaldi-nnet.so
libkaldi-online.so
libkaldi-kws.so**

Thanks.

**Comment by nshmyrev** [comment]
We do not compile the libraries we do not use to save space. nnet and online are old implementations which are not relevant anymore. kws is not yet integrated anyway.

**Comment by vgritsko** [comment]
> We do not compile the libraries we do not use to save space. nnet and online are old implementations which are not relevant anymore. kws is not yet integrated anyway.

@nshmyrev , thanks for reply. Could you tell me where you define compile or not compile library from Kaldi.

**Comment by nshmyrev** [comment]
Here:

https://github.com/alphacep/vosk-api/blob/62885e8963282adbe3e0994eccbc70dbf953277b/android/build-kaldi.sh#L139

You can add `kws` there to build kws library.

**Comment by nshmyrev** [comment]
Reopen if you have further queries
