### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [alphacep/vosk-api#226]
I would like to point out that an identifier like “[`_VOSK_API_H_`](https://github.com/alphacep/vosk-api/blob/e5c08f7710dd5201970d930d58602b896480aae4/src/vosk_api.h#L17 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by nshmyrev** [comment]
Thank you for your suggestion!

**Comment by elfring** [comment]
Thanks for [your adjustment of include guards](https://github.com/alphacep/vosk-api/commit/8d88b89db1217169fc4607b6b3c53032686a840e "Update for include guards").
[Was another update candidate left over](https://github.com/alphacep/vosk-api/blob/fad954e6e3d24f9bfaf2d444fb287a58b98a63a1/ios/VoskApiTest/Vosk/vosk_api.h#L16 "Update candidate")?
