### ISSUE TITLE
Selection of support for C++ exceptions across C API boundaries

### ISSUE THREAD

**Issue by elfring** [alphacep/vosk-api#228]
[Some functions were marked](https://github.com/alphacep/vosk-api/blob/8d88b89db1217169fc4607b6b3c53032686a840e/src/vosk_api.h#L15 "C API for Vosk speech recognition system") for the usage according to an application programming interface.
:bulb: I suggest to take software build settings into account for the design choice if [C++ exceptions may be passed across C API boundaries](https://stackoverflow.com/questions/9252139/passing-exceptions-across-a-c-api-boundary "Passing exceptions across a C API boundary").
How do you think about to [adjust any function implementations accordingly](https://github.com/alphacep/vosk-api/blob/80219066e98e469be08514df73d4873fc1c7de70/src/vosk_api.cc#L24 "Update candidate")?

**Comment by nshmyrev** [comment]
We have just implemented catch, so bindings can raise native exceptions:

https://github.com/alphacep/vosk-api/commit/5e46825474e5e630f0c02514e3f21702f878ba45

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/alphacep/vosk-api/commit/5e46825474e5e630f0c02514e3f21702f878ba45 "Add try/catch wrapper for C++ method to raise native exceptions.").
