### ISSUE TITLE
Vosk adaptation

### ISSUE THREAD

**Issue by bouchradahamni** [alphacep/vosk-api#230]
can we modify the vosk dictionary in python ??

**Comment by nshmyrev** [comment]
We have static precompiled dictionary. If you want to modify it you have to compile graph again. See for details

https://alphacephei.com/vosk/adaptation

**Comment by bouchradahamni** [comment]
I follow the steps that are in your site , I already compile Kaldi and install the dependencies .but the adaptation doesn't work .I have these errors when I run the commands (in the screenshot) .and I can't find Gr.fst in the model.
thank you for helping me.
![image](https://user-images.githubusercontent.com/35856677/94489524-988b3b00-01b2-11eb-90fc-f2a4b4717922.png)

**Comment by nshmyrev** [comment]
It is pretty bad idea to post screenshot which is cut on the borders

**Comment by bouchradahamni** [comment]
I'm really sorry , it was the size of my screen . here another screenshot .

![image](https://user-images.githubusercontent.com/35856677/94490476-5662f900-01b4-11eb-8fa6-b35d054a8c24.png)

my txt file : 
![image](https://user-images.githubusercontent.com/35856677/94490733-d4270480-01b4-11eb-9d6a-257272b37826.png)

**Comment by bouchradahamni** [comment]
I'm using the big model of Daanzu.

**Comment by nshmyrev** [comment]
Never paste log messages as screenshot, paste them as a text in backticks.

**Comment by bouchradahamni** [comment]
when I run this command : fstsymbols --save_osymbols=words.txt Gr.fst > /dev/null
I got this error :  ERROR: ReadFst: Can't open file: Gr.fst 
and I see that there is no Gr.fst file .
I'm using the big model of Daanzu.

**Comment by nshmyrev** [comment]
There is lgraph version for daanzu which has Gr.fst

https://alphacephei.com/vosk/models/vosk-model-en-us-daanzu-20200905-lgraph.zip

big model requires full graph rebuild.

**Comment by bouchradahamni** [comment]
so the steps in the site of vosk are not for big model ? . if yes , which model I have to use to update the language , because my case is so specific .

**Comment by nshmyrev** [comment]
There is lgraph version for daanzu which has Gr.fst

https://alphacephei.com/vosk/models/vosk-model-en-us-daanzu-20200905-lgraph.zip

**Comment by bouchradahamni** [comment]
so ,even if I use daanzu which have Gr.fst , I can't adapt the language by following the steps of Vosk site ?? . If yes , which model I have to use in order to adapt the language easily . Now I change the model with the one which have Gr.fst , and when  I run : fstsymbols --save_osymbols=words.txt Gr.fst > /dev/null 
I got this error : ERROR: GenericRegister::GetEntry: ngram-fst.so: cannot open shared object file: No such file or directory
ERROR: Fst::Read: Unknown FST type ngram (arc type = standard): Gr.fst . 
thank you for your reply

**Comment by nshmyrev** [comment]
Same as #243
