### ISSUE TITLE
Audio data preprocessing + alternative audio stream settings

### ISSUE THREAD

**Issue by antondim** [alphacep/vosk-api#231]
Hello,
on vosk website, it is mentioned that .wav file should be of sampling rate 16kHz  , 16bit mono. 

KaldiRecognizer still gets to work with sapling rate of 48kHz on real time stream. 

In theory, more RATE means more max frequencies. Would it be correct to say that this would increase model's accuracy?

Also  changing format to paInt32 or paFloat32 (more precision), doesn't seem to trigger the recognizer.

What is more, by applying active noise reduction (with noisereduction on each stream read audio chunk) on pyaudio stream or by applying noise reduction on wav file and then feeding it to "test_simple.py" seems to give me same results and some times even slightly worse (!?). Is noise reduction a good choice for this tool?  (noisereduce module == spectral gating algorithm)

Thank you

**Comment by nshmyrev** [comment]
> In theory, more RATE means more max frequencies. Would it be correct to say that this would increase model's accuracy?

Model is trained on 16khz data and doesn't handle higher frequencies so higher rate will have no effect. If you retrain the model you'll see a slight increase in accuracy.

>  Is noise reduction a good choice for this tool?

Noise reduction doesn't understand the words, so it can not remove noise as effectively as recognizer. It is known that noise reduction degrades speech recognition accuracy. You should not apply any separate noise reduction, it is already embedded into recognizer.

**Comment by antondim** [comment]
Thank you for your quick response.

Could you please elaborate on how a clean from static noise signal wouldn't help the recognizer spot words more accurately?

**Comment by nshmyrev** [comment]
> Could you please elaborate on how a clean from static noise signal wouldn't help the recognizer spot words more accurately?

Any cleaner corrupts speech in unpredictable way because speech is also a static noise sometimes (sounds like s, sh, etc).

**Comment by antondim** [comment]
I see... So I guess, by increasing audio quality through a more hardware oriented way (better mic etc) could possibly be a better approach if any1 would want to have better transcriptions.

**Comment by nshmyrev** [comment]
> So I guess, by increasing audio quality through a more hardware oriented way (better mic etc) could possibly be a better approach if any1 would want to have better transcriptions.

Yes

**Comment by antondim** [comment]
Thank you for your help!
