### ISSUE TITLE
"fr-pguyot-zamia-20191016-tdnn_f"

### ISSUE THREAD

**Issue by doublex** [alphacep/vosk-api#232]
Hello,
We would like to use "vosk" in french.
Are there any plans to port `fr-pguyot-zamia-20191016-tdnn_f` to `vosk`?
Best wishes!

**Comment by nshmyrev** [comment]
Eventually we'll train our own model. You can follow these commands to arrange  fr-pguyot-zamia-20191016-tdnn_f files:

https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-fr

Let me know if you need any help.

**Comment by doublex** [comment]
Works like a charm!

**Comment by ShantanuNair** [comment]
If anyone runs across this - this was the version of the file @doublex was referring to https://github.com/alphacep/vosk-server/blob/f616010fb5f29cd8545f113e2099fa0f1bc11e25/docker/Dockerfile.kaldi-fr

**Comment by nshmyrev** [comment]
@doublex, @ShantanuNair  there is newer model available with better accuracy please check

https://alphacephei.com/nsh/2020/10/21/french.html

docker is also updated.

**Comment by doublex** [comment]
@nshmyrev 
Thank you for all the efforts!
