### ISSUE TITLE
Transcription of two separate words is more accurate than their combination

### ISSUE THREAD

**Issue by antondim** [alphacep/vosk-api#234]
Hello, 

with the use of language model, we can somehow understand why saying separately 2 words is more accurate than their combination based on the lattice re-scoring.

For example, when saying "word_A" , recognizer gets it with high confidence (~1.0) and so does with "word_B" too. 
But, saying "word_A word_B", gets it wrong or sometimes correct , but with kinda low confidence.
Also, results with low confidence demand more processing time (I get that).

Can I somehow interfere and enhance the phrase "word_A    word_B" .

Apart from trying to improve the audio input quality (e.g better mic) which would result in better phone capture, could this be improved with model adaptation method? (https://alphacephei.com/vosk/adaptation)

**Comment by nshmyrev** [comment]
> this be improved with model adaptation method?

Yes, sure

**Comment by antondim** [comment]
Getting following error after running ./install_opengrm.sh:
```
make[3]: Entering directory '/home/foo/projects/kaldi/tools/extras/ngram-1.3.7/src/lib'
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./../include -fno-exceptions -funsigned-char  -I/home/foo/projects/kaldi/tools/extras/ngram-1.3.7/../openfst/include -std=c++11 -MT hist-arc.lo -MD -MP -MF .deps/hist-arc.Tpo -c -o hist-arc.lo hist-arc.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I./../include -fno-exceptions -funsigned-char -I/home/foo/projects/kaldi/tools/extras/ngram-1.3.7/../openfst/include -std=c++11 -MT hist-arc.lo -MD -MP -MF .deps/hist-arc.Tpo -c hist-arc.cc  -fPIC -DPIC -o .libs/hist-arc.o
hist-arc.cc:22:10: fatal error: fst/script/register.h: No such file or directory
 #include <fst/script/register.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:494: recipe for target 'hist-arc.lo' failed
make[3]: *** [hist-arc.lo] Error 1
make[3]: Leaving directory '/home/foo/projects/kaldi/tools/extras/ngram-1.3.7/src/lib'
Makefile:354: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/foo/projects/kaldi/tools/extras/ngram-1.3.7/src'
Makefile:401: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/foo/projects/kaldi/tools/extras/ngram-1.3.7'
Makefile:333: recipe for target 'all' failed
```
At first it couldn't find "fst.h"

Tried to install openfst folloing this : https://stackoverflow.com/questions/60606879/error-when-instaling-openfst-thrax-configure-error-fst-fst-h-header-not-found 

Then bypassed this error and the upper problem occured. 

I make clean and make again kaldi , then follow only your instructions again but problem persists

**Comment by nshmyrev** [comment]
I suppose you have to compile kaldi tools first before you compile opengrm.

**Comment by antondim** [comment]
kaldi and vosk are built succesfully from source and I  can use the test scripts normally outside of the virtual enviroment where I "pip3 install vosk". (Re-compiled though again, but problem persists). gcc , g++ version 6

Apart from that, to be sure of what I am doing, I read on of your posts about adaptation.

What I am trying to do is "update" the already working model of daanzu (vosk-model-en-us-daanzu-20200905==big model) in order to somehow Increase the probability of a certain phrase. This should be done through "Updating the language model" section. That model uses G.fst and not Gr.fst by the way.

**Comment by antondim** [comment]
Update 
solved the 1st issue:

in ./install_opengrm.sh  , OPENFST prefix is set to  : 'pwd'/../openfst

Following this seems to be wrong ,as no fst/script folder exists.

changed  'pwd'/../openfst  to 'pwd'/../../openfst and copied the register.h file (which exists)  to kaldi/tools/openfst/include/fst/script folder. 

Now I get :
```
/usr/bin/x86_64-linux-gnu-ld: ngramapply-main.o: undefined reference to symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEPKc@@GLIBCXX_3.4.21'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
```
After looking  into similar issues, I changed from gcc,g++ 6 to 7 and by passed this error with 'warnings'

```
libtool: warning: '../lib/libngram.la' has not been installed in '/home/foo/projects/kaldi/tools/extras/ngram-1.3.7/../openfst/lib'
```

**Comment by nshmyrev** [comment]
More or less the same as #309 , lets track there.

Audio file samples would be helpful.
