### ISSUE TITLE
Question: Standalone 'Speaker identification'

### ISSUE THREAD

**Issue by doublex** [alphacep/vosk-api#237]
Hello,
Is it possible to use the `Speaker identification model` standalone, e.g. without speech recognition?
Best wishes

**Comment by nshmyrev** [comment]
Not for now, speech recognition is required to find the utterances. You can create some lightweight speech recognition model though.

**Comment by doublex** [comment]
Thanks for the fast explanation!
Best wishes

**Comment by balaji7363** [comment]
how to identify who is speaking in audio wav file sir?
its possible vosk library ?

Thanks in advance!
