### ISSUE TITLE
Add new models

### ISSUE THREAD

**Issue by doublex** [alphacep/vosk-api#238]
Hello, 

Are there any plans to port these models to vosk?

Bigger Vietnamese model:
```
https://github.com/synesthesiam/vi_kaldi-montreal/archive/v1.1.zip
```
Swedish model:
```
https://github.com/synesthesiam/sv_kaldi-montreal/archive/v1.2.zip
```
Korean model:
```
https://github.com/synesthesiam/ko-kr_kaldi-montreal/archive/v1.0.zip
```

**Comment by nshmyrev** [comment]
Those models are trained by montreal forced alignment project on very small datasets. They are ok for forced alignment, but they are not accurate at all for large vocabulary transcription. They are also based on GMM classifiers, much less accurate than neural networks.

We can train bigger Korean and Vietnamese models probably, if there is sufficient interest, but the models above are not really suitable.

**Comment by doublex** [comment]
@nshmyrev 
Thank you very much for the effort.
