### ISSUE TITLE
Error handling for model creation failures

### ISSUE THREAD

**Issue by erksch** [alphacep/vosk-api#239]
Hey there!

I realized, when using 
``` 
model = Model(path)
``` 
that this line will throw a `kaldi::KaldiFatalError` when something is wrong with model:
```
E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
``` 
But I can't seem to catch it using Java / Kotlin because the error comes from C++. 
This is a bit bad because if something is wrong with the model, the app will crash and there is no way to react to these errors. 
Would it be possible to expose these errors to Java so they can be handled?

**Comment by nshmyrev** [comment]
It is possible but it requires a bit more work on bindings. Related to https://github.com/alphacep/vosk-api/issues/228

**Comment by nshmyrev** [comment]
Lets track it in #228
