### ISSUE TITLE
Can't create decoding graph

### ISSUE THREAD

**Issue by bouchradahamni** [alphacep/vosk-api#243]
hello ,
I want to adapt the words in the big model , so I recompile the graph using kaldi and following the steps in the tutoriel of Extending the ASpIRE model. 
when replace the graph by graph which I recompile, I have this error:   
bouchra@DESKTOP-4HLF9NU:/mnt/c/Users/BOUCHRA/Desktop/Vosk-exemple/vosk-api/python/example$ python3 test_microphone.py
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0350461 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:235) Loading HCLG from model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:254) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:262) Loading winfo model/graph/phones/word_boundary.int
ERROR (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:85) Can't create decoding graph
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted

thank you for your reply and help .

**Comment by nshmyrev** [comment]
You probably try to configure words with big model, it is not supported.

**Comment by bouchradahamni** [comment]
no,  I rebuild the graph , I didn't add words in runtime . the folder graph of the model , I replace it with recompile graph of kaldi .

**Comment by nshmyrev** [comment]
This error is from the older kaldi anyway, try to update vosk, run `pip3 install -U vosk`.

**Comment by bouchradahamni** [comment]
I fix it . But now when I run the example with the new graphe , it does not finish the recognition by displaying this : 
C:\Users\BOUCHRA\Desktop\Vosk-exemple\vosk-api\python\example>python test_microphone.py
LOG (VoskAPI:ConfigureV2():build-libkaldiwrap/model.cc:202) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ConfigureV2():build-libkaldiwrap/model.cc:205) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0500002 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():build-libkaldiwrap/model.cc:254) Loading HCLG from model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():build-libkaldiwrap/model.cc:273) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():build-libkaldiwrap/model.cc:281) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():build-libkaldiwrap/model.cc:289) Loading CARPA model from model/rescore/G.carpa
{
  "partial" : ""
}
{
  "partial" : ""
}

C:\Users\BOUCHRA\Desktop\Vosk-exemple\vosk-api\python\example>

**Comment by nshmyrev** [comment]
You probably didn't update words from a new graph. Also, you'd better try without carpa if you use different language model. You can remove rescore folder from the model.

**Comment by bouchradahamni** [comment]
it look like this the structure of my new graph : 
![image](https://user-images.githubusercontent.com/35856677/95225068-6046b680-07c9-11eb-829d-1556ce168d82.png)
and inside words.txt , I find all the words that I have added.

**Comment by nshmyrev** [comment]
First remove rescore folder from the model

**Comment by bouchradahamni** [comment]
I have already done it . Nothing has changed.

**Comment by nshmyrev** [comment]
Ok, probably you made some mistakes in graph compilation. Provide full compilation log. Make sure you don't have unknown words warnings due compilation. It happens when cases of dictionary and lm mismatch

**Comment by bouchradahamni** [comment]
thank you for your reply . I make it work by using aspire model of vosk .

**Comment by nshmyrev** [comment]
Ok, great!

**Comment by v-yunbin** [comment]
make Gr.fst with follows commands:
```
fstsymbols --save_osymbols=words.txt Gr.fst > /dev/null
farcompilestrings --fst_type=compact --symbols=words.txt --keep_symbols text.txt | \
 ngramcount | ngrammake | \
 fstconvert --fst_type=ngram > Gr.new.fst
```
errors is as follows
` farcompilestrings --fst_type=compact --symbols=words.txt --keep_symbols text.txt | \
>  ngramcount | ngrammake | \
>  fstconvert --fst_type=ngram > Gr.new.fst
FATAL: FarCompileStrings: Compiling string number 2321 in file text.txt failed with token_type = symbol and entry_type = line
FATAL: STListReader: Error reading file: stdin
ERROR: FstHeader::Read: Bad FST header: standard input
ERROR: FstHeader::Read: Bad FST header: standard input
`
