### ISSUE TITLE
Swift MacOS Support?

### ISSUE THREAD

**Issue by hadiidbouk** [alphacep/vosk-api#244]
Is it possible to make it works on a MacOS project?
I tried to add the `vosk_api.h` header file, but I am getting this

```
Undefined symbols for architecture x86_64:
  "_vosk_model_free", referenced from:
      QuickSRT.Vosk.recognizeAudio(Foundation.URL) -> Swift.String in Vosk.o
  "_vosk_model_new", referenced from:
      QuickSRT.Vosk.recognizeAudio(Foundation.URL) -> Swift.String in Vosk.o
  "_vosk_recognizer_accept_waveform", referenced from:
      closure #1 (Swift.UnsafePointer<Swift.Int8>) -> Swift.Int32 in QuickSRT.Vosk.recognizeAudio(Foundation.URL) -> Swift.String in Vosk.o
  "_vosk_recognizer_final_result", referenced from:
      QuickSRT.Vosk.recognizeAudio(Foundation.URL) -> Swift.String in Vosk.o
  "_vosk_recognizer_free", referenced from:
      QuickSRT.Vosk.recognizeAudio(Foundation.URL) -> Swift.String in Vosk.o
  "_vosk_recognizer_new", referenced from:
      QuickSRT.Vosk.recognizeAudio(Foundation.URL) -> Swift.String in Vosk.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So it's compiled with this architecture x86_64 which is different than the macOS application architecture?

**Comment by nshmyrev** [comment]
Hi. I'm sorry, you have to compile the library for OSX yourself, you need to build kaldi from branch and then vosk-api sources too and it should work.

You can follow https://github.com/alphacep/vosk-api/tree/master/c for details.

Let me know if you need further help.

**Comment by nshmyrev** [comment]
We provide OSX builds now:

https://github.com/alphacep/vosk-api/releases/download/v0.3.31/vosk-osx-0.3.31.zip

though builds are still not fully automated. Tracked at #681
