### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by crinny** [alphacep/vosk-api#245]
When I try using vosk from Python, I encounter the following error:
```sh
Traceback (most recent call last):
  File "C:/.../vosk-test.py", line 1, in <module>
    from vosk import Model, KaldiRecognizer
  File "C:\...\site-packages\vosk\__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel
  File "C:\...site-packages\vosk\vosk.py", line 13, in <module>
    from . import _vosk
ImportError: DLL load failed: %1 is not a valid Win32 application.
```
I have previously installed vosk by running `pip3 install https://github.com/alphacep/vosk-api/releases/download/0.3.3/vosk-0.3.3-cp37-cp37m-win_amd64.whl`. I explicitly used the wheel file because `pip3 -v install vosk` doesn't manage to find one.

> In case of trouble installing, verify and provide for analysis the output of the following commands

```sh
> python3 --version
Python 3.7.8
> pip3 --version
pip 20.2.3 from c:\...\site-packages\pip (python 3.7)
> pip3 -v install vosk
https://pastebin.com/LNdX8niH
> pip3 -v install https://github.com/alphacep/vosk-api/releases/download/0.3.3/vosk-0.3.3-cp37-cp37m-win_amd64.whl
https://pastebin.com/5QNhNBjs
```

**System information**
- OS: Windows 10 Pro 1909 (x64)
- Python: 3.7.8

**Comment by nshmyrev** [comment]
We only support 64-bit python 3.8

You have 32-bit python it seems. Also, it is a bad idea to install old version.

**Comment by crinny** [comment]
Works with 64-bit Python 3.8. Thanks a lot for a quick reply and help!
