### ISSUE TITLE
Package Vosk on Nuget

### ISSUE THREAD

**Issue by miketech92** [alphacep/vosk-api#246]
Hello! So I'm a bit new to using github and I'm having some trouble getting what I need. So I looked at the instructions for installing vosk for c# but I have no idea where I'm supposed to use this command and/or what software I need. I'm running windows 10. Any help would be greatly appreciated.

**Comment by nshmyrev** [comment]
We do not support C# on windows yet. If you still want to compile you need to:

   * compile kaldi according to instructions
   * compile dll according to [makefile](https://github.com/alphacep/vosk-api/blob/master/csharp/Makefile)

It is not very straightforward process though.

I might take a look later how to build prebuilt binaries.

**Comment by miketech92** [comment]
Yes that would be much appreciated. I'm mostly self-taught and some of this gets very complicated.

**Comment by CobraCalle** [comment]
+1 for "prebuilt binaries"... or perhaps a nuget? :-)

...setting up everything on a windows machine with the current instructions is a little bit "complicated"

**Comment by nshmyrev** [comment]
I created vosk package, it is not yet functional though, something to work on soon:

https://www.nuget.org/packages/Vosk/

**Comment by CobraCalle** [comment]
coool.... can´t wait to test this :-)

**Comment by CobraCalle** [comment]
![image](https://user-images.githubusercontent.com/6218368/97268487-3f9fd880-182c-11eb-9ad3-0b0fbd0ec14f.png)

@nshmyrev can I help you with the package...? I`ve already build some nugets in the past...

**Comment by cdibbs** [comment]
Whew! I thought I would also try my hand at getting this built for Windows 10, and it's tough cookies. I am trying to do it via Ubuntu running under Windows as an app. My desire was to modify the csharp Makefile so that it both generates the current linux binary, and also cross compiles an x64 Windows binary (that should be possible right?).

This proved to be a bit out of my depth, so I hope someone more experienced can help us out. I'm going to stop for now, but might circle back later even if just to learn a bit more about the Linux build system.

**Comment by nshmyrev** [comment]
> My desire was to modify the csharp Makefile so that it both generates the current linux binary, and also cross compiles an x64 Windows binary (that should be possible right?).

Yes, thought it is better to keep the makefile and just change the compiler with environment variable. We might also pack it into docker so it would be easier to build in CI.

Something to work on later.

**Comment by nshmyrev** [comment]
We will also share a prebuilt kaldi for win for python build, it will be easier to build C# too

**Comment by cdibbs** [comment]
Sounds good, I look forward to it!

**Comment by nshmyrev** [comment]
New package 0.3.17 that supports Win32 and Win64 uploaded to nuget:

https://www.nuget.org/packages/Vosk/0.3.17

Needs testing though. Lets track remaining issues in #325

**Comment by CobraCalle** [comment]
Works like a charm! Thank your very much 👍
