### ISSUE TITLE
Illegal Instruction while running on Raspberry PI 2

### ISSUE THREAD

**Issue by girishsukukumar** [alphacep/vosk-api#247]
Hi, 
I am trying to run vosk on Raspberry Pi

I had installed it using pip3 install vosk
downloaded and testing the installation with test.wav. The steps  I had followed is

wget https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.3.zip
unzip vosk-model-small-en-us-0.3.zip
mv vosk-model-small-en-us-0.3 model
python3 ./test_simple.py test.wav

When I run this I get the following Illegal Instruction Error.

*pi@stt: /home/pi/vosk$ file test.wav
test.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz*

pi@stt: /home/pi/vosk$ python3 test.py  test.wav
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.526357 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
Illegal instruction
pi@stt:~/vosk$

While searching I had found that the same error was reported.
I followed the instructions given in "Illegal Instruction" on test with Raspbian #48

I tried

pip install https://github.com/alphacep/vosk-api/releases/download/0.3.3/vosk-0.3.3-cp37-cp37m-linux_armv6l.whl
But this gave me an error saying it is not supported in this platform.

May I know how to correct the "illegal instruction" error

**Comment by nshmyrev** [comment]
What is your raspberry pi version and what is your OS?

**Comment by girishsukukumar** [comment]
Thanks for your response

1. Here is the data of OS
pi@stt:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian

2. uname -a give the following
Linux pi@stt 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

3. Hardware Version (Raspberry Pi Board)
 pi@stt:~$ cat /proc/device-tree/model
Raspberry Pi 2 Model B Rev 1.1

**Comment by girishsukukumar** [comment]
Thanks for your response Here is the data of OS   

pi@stt:~$ cat /etc/os-release   
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"   
NAME="Raspbian GNU/Linux"   
VERSION_ID="8"   
VERSION="8 (jessie)"   
ID=raspbian   
ID_LIKE=debian

uname -a give the following   

Linux pi@stt 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
     
Hardware Version (Raspberry Pi Board)   

pi@stt:~$ cat /proc/device-tree/model   
Raspberry Pi 2 Model B Rev 1.1

**Comment by nshmyrev** [comment]
Provide

`cat /proc/cpuinfo`

gdb output to print the instruction

`
gdb --args python3 ./test_simple.py test.wav
`
then when it crashes type in gdb disassemble command and provide the output

`
(gdb) disassemble $pc,+32
`

**Comment by girishsukukumar** [comment]
cat /proc/cpuinfo says ...

processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : BCM2835
Revision        : a21041
Serial          : 00000000f5dea53e
====================================================================

gdb --args python3 ./test_simple.py test.wav

pi@tts:~/vosk$ gdb --args  python3 test.py test.wav
GNU gdb (Raspbian 7.7.1+dfsg-5+rpi1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...done.
(gdb) run
Starting program: /usr/local/bin/python3 test.py test.wav
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
<wave.Wave_read object at 0x76adc9b0>
1
2
NONE
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.529522 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
[New Thread 0x742f1460 (LWP 1042)]

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x742f1460 (LWP 1042)]
0x766ade32 in ?? () from /home/pi/.local/lib/python3.6/site-packages/vosk/_vosk.cpython-36m-arm-linux-gnueabihf.so

(gdb)
(gdb) disassemble $pc,+32
Dump of assembler code from 0x766ade32 to 0x766ade52:
=> 0x766ade32:                  ; <UNDEFINED> instruction: 0xebfb6006
   0x766ade36:  b.n     0x766adf48 <_ZN5kaldi7DiagGmm6ResizeEii+200>
   0x766ade38:  str     r0, [r1, #0]
   0x766ade3a:  b.n     0x766ad948 <_ZNSt6vectorIN5kaldi6MatrixIdEESaIS2_EE17_M_default_appendEj+84>
   0x766ade3c:  lsls    r0, r0, #10
   0x766ade3e:  stmia.w r5, {r3, r4, r5, r6, r7, r8, r9, pc}
   0x766ade42:  ldmia.w sp!, {}
   0x766ade46:  b.n     0x766ae4f6 <_ZN5kaldi7DiagGmmC2ERKSt6vectorISt4pairIfPKS0_ESaIS5_EE+726>
   0x766ade48:  adds    r0, #12
   0x766ade4a:  asrs    r0, r4, #14
   0x766ade4c:  lsls    r3, r2, #26
   0x766ade4e:  asrs    r6, r0, #32
   0x766ade50:                  ; <UNDEFINED> instruction: 0xffb01aff
End of assembler dump.

**Comment by girishsukukumar** [comment]
cat /proc/cpuinfo says ...
processor       : 0model name      : ARMv7 Processor rev 5 (v7l)BogoMIPS        : 38.40Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrmCPU implementer : 0x41CPU architecture: 7CPU variant     : 0x0CPU part        : 0xc07CPU revision    : 5
processor       : 1model name      : ARMv7 Processor rev 5 (v7l)BogoMIPS        : 38.40Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrmCPU implementer : 0x41CPU architecture: 7CPU variant     : 0x0CPU part        : 0xc07CPU revision    : 5
processor       : 2model name      : ARMv7 Processor rev 5 (v7l)BogoMIPS        : 38.40Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrmCPU implementer : 0x41CPU architecture: 7CPU variant     : 0x0CPU part        : 0xc07CPU revision    : 5
processor       : 3model name      : ARMv7 Processor rev 5 (v7l)BogoMIPS        : 38.40Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrmCPU implementer : 0x41CPU architecture: 7CPU variant     : 0x0CPU part        : 0xc07CPU revision    : 5
Hardware        : BCM2835Revision        : a21041Serial          : 00000000f5dea53e====================================================================
gdb --args python3 ./test_simple.py test.wav
pi@tts:~/vosk$ gdb --args  python3 test.py test.wavGNU gdb (Raspbian 7.7.1+dfsg-5+rpi1) 7.7.1Copyright (C) 2014 Free Software Foundation, Inc.License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>This is free software: you are free to change and redistribute it.There is NO WARRANTY, to the extent permitted by law.  Type "show copying"and "show warranty" for details.This GDB was configured as "arm-linux-gnueabihf".Type "show configuration" for configuration details.For bug reporting instructions, please see:<http://www.gnu.org/software/gdb/bugs/>.Find the GDB manual and other documentation resources online at:<http://www.gnu.org/software/gdb/documentation/>.For help, type "help".Type "apropos word" to search for commands related to "word"...Reading symbols from python3...done.(gdb) runStarting program: /usr/local/bin/python3 test.py test.wav[Thread debugging using libthread_db enabled]Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".<wave.Wave_read object at 0x76adc9b0>12NONELOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.529522 seconds in looped compilation.LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ieLOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor[New Thread 0x742f1460 (LWP 1042)]
Program received signal SIGILL, Illegal instruction.[Switching to Thread 0x742f1460 (LWP 1042)]0x766ade32 in ?? () from /home/pi/.local/lib/python3.6/site-packages/vosk/_vosk.cpython-36m-arm-linux-gnueabihf.so
(gdb)(gdb) disassemble $pc,+32Dump of assembler code from 0x766ade32 to 0x766ade52:=> 0x766ade32:                  ; <UNDEFINED> instruction: 0xebfb6006   0x766ade36:  b.n     0x766adf48 <_ZN5kaldi7DiagGmm6ResizeEii+200>   0x766ade38:  str     r0, [r1, #0]   0x766ade3a:  b.n     0x766ad948 <_ZNSt6vectorIN5kaldi6MatrixIdEESaIS2_EE17_M_default_appendEj+84>   0x766ade3c:  lsls    r0, r0, #10   0x766ade3e:  stmia.w r5, {r3, r4, r5, r6, r7, r8, r9, pc}   0x766ade42:  ldmia.w sp!, {}   0x766ade46:  b.n     0x766ae4f6 <_ZN5kaldi7DiagGmmC2ERKSt6vectorISt4pairIfPKS0_ESaIS5_EE+726>   0x766ade48:  adds    r0, #12   0x766ade4a:  asrs    r0, r4, #14   0x766ade4c:  lsls    r3, r2, #26   0x766ade4e:  asrs    r6, r0, #32   0x766ade50:                  ; <UNDEFINED> instruction: 0xffb01affEnd of assembler dump.



    On Sunday, 11 October, 2020, 01:00:18 pm IST, Nickolay V. Shmyrev <notifications@github.com> wrote:  
 
 


Provide

cat /proc/cpuinfo

gdb output to print the instruction


ggdb --args python3 ./test_simple.py test.wavthen when it crashes type in gdb disassemble command and provide the output


(gdb) disassemble $pc,+32

**Comment by nshmyrev** [comment]
@girishsukukumar can you format your message properly? I don't get a thing form it.

**Comment by nshmyrev** [comment]
Also I suppose the default python is 3.7. Why are you using 3.6? Does it work with 3.7?

From the disasm it looks like memory corruption, not sure why the output is broken. Do you have more RPi to try? Is your RPi stable overall?

**Comment by girishsukukumar** [comment]
What I will do is 
1. I have a RP3 with me, I will try on it and see the problem is getting reproduceable or not
2.  Will use python3.7, I really did not check python version details otherwise I would have found it. 
3. If the problem gets reproduced on RPi3. I will format the output and post it here. 

Thanks a lot for the your prompt response.
Regards
Girish

**Comment by girishsukukumar** [comment]
I tried on Raspberry Pi 3 model with python3.7 and it worked without any issues. There are issues with accuracy (That is a different issue). Will try again on Raspberry Pi 2 model with Python 3.7 (will uninstall 3.6) and tell you a in a day's time  Thank you very much for your support

**Comment by nshmyrev** [comment]
Thank you for the testing, update us about the results please!

**Comment by girishsukukumar** [comment]
I had tested the same code,  Python3.7.8 and it worked very well on the same raspberry pi. So conclusion is there is a a problem with Python3.6 where as Python3.7 on Raspberry Pi 2 it worked. well. My testing is as follows
1. Raspberry 3 + Python3.7 + vosk : Worked very well
2. Raspberry Pi 2 Model B Rev 1.1 + Python3.7 + vosk : Worked very well
3. Raspberry Pi 2 Model B Rev 1.1 + Python3.6 + vosk :  Failed 

This indicates that, vosk has a tight dependency on the exact version of Python. Honestly I did not notice this, though python version mentioned 3.7. 

Since vosk has a strong dependency on the exact version of python that need to be use can you do a check on the python version the user is having and then proceed 
Something like platform.python_version_tuple() or sys.version() can do the job
May be you can add this in check the demo program itself. It will do a check report and error in case python version is not meeting the requirements. 

You can close the issue now.

Thanks a lot for your prompt support on this topic.

**Comment by girishsukukumar** [comment]
Hi Nickolay 
Thanks a lot for the help and support. I appreciate that
Girish
