### ISSUE TITLE
Java undefined symbol: vdPowx

### ISSUE THREAD

**Issue by MrMindels** [alphacep/vosk-api#249]
Hi there,

I keep getting an error while trying to run make run, 
the error, `java: symbole lookup error: /home/vosk-api/java/libvosk_jni.so: undefined symbol: vdPowx`

I have repeated the whole process from installing Kaldi to trying to build Vosk multiple times and every time I did exactly as specified in the tutorial, I also added `--mathlib=OPENBLAS` as specified by the tutorial and also on another post with the same error so sadly that does not seem to be the solution.
At this point I am kinda clueless on how to solve this issue so I was hoping there is a fix to this issue that I am missing.

Thanks in advance.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/210

Remove kaldi folder, clone from git again and build with openblas.  Then remove vosk folder, clone vosk again and build.

Provide full kaldi and vosk build logs if you still have trouble.
