### ISSUE TITLE
Error building Java bindings

### ISSUE THREAD

**Issue by stefan-reich** [alphacep/vosk-api#25]
Peppermint Linux 10

```
stefan@stefan-HP-255-G7-Notebook-PC ~/dev/vosk-api-master/java $ KALDI_ROOT=/home/stefan/dev/kaldi-master make
g++ -shared -o libvosk_jni.so -I/home/stefan/dev/jdk-13/include -I/home/stefan/dev/jdk-13/include/linux -I/home/stefan/dev/kaldi-master/src -I/home/stefan/dev/kaldi-master/tools/openfst/include -I../src -g -O2 -DPIC -fPIC -Wno-unused-function vosk_wrap.cc ../src/kaldi_recognizer.cc ../src/kaldi_recognizer.h ../src/model.cc ../src/model.h /home/stefan/dev/kaldi-master/src/online2/kaldi-online2.a /home/stefan/dev/kaldi-master/src/decoder/kaldi-decoder.a /home/stefan/dev/kaldi-master/src/ivector/kaldi-ivector.a /home/stefan/dev/kaldi-master/src/gmm/kaldi-gmm.a /home/stefan/dev/kaldi-master/src/nnet3/kaldi-nnet3.a /home/stefan/dev/kaldi-master/src/tree/kaldi-tree.a /home/stefan/dev/kaldi-master/src/feat/kaldi-feat.a /home/stefan/dev/kaldi-master/src/lat/kaldi-lat.a /home/stefan/dev/kaldi-master/src/hmm/kaldi-hmm.a /home/stefan/dev/kaldi-master/src/transform/kaldi-transform.a /home/stefan/dev/kaldi-master/src/cudamatrix/kaldi-cudamatrix.a /home/stefan/dev/kaldi-master/src/matrix/kaldi-matrix.a /home/stefan/dev/kaldi-master/src/fstext/kaldi-fstext.a /home/stefan/dev/kaldi-master/src/util/kaldi-util.a /home/stefan/dev/kaldi-master/src/base/kaldi-base.a /home/stefan/dev/kaldi-master/tools/openfst/lib/libfst.a /home/stefan/dev/kaldi-master/tools/openfst/lib/libfstngram.a /home/stefan/dev/kaldi-master/tools/OpenBLAS/libopenblas.a -lgfortran
In file included from vosk_wrap.cc:236:0:
../src/kaldi_recognizer.h:50:14: error: ‘LookaheadFst’ in namespace ‘fst’ does not name a template type
         fst::LookaheadFst<fst::StdArc, int32> *decode_fst_;
              ^~~~~~~~~~~~
In file included from ../src/kaldi_recognizer.cc:15:0:
../src/kaldi_recognizer.h:50:14: error: ‘LookaheadFst’ in namespace ‘fst’ does not name a template type
         fst::LookaheadFst<fst::StdArc, int32> *decode_fst_;
              ^~~~~~~~~~~~
../src/kaldi_recognizer.cc: In constructor ‘KaldiRecognizer::KaldiRecognizer(Model&, float)’:
../src/kaldi_recognizer.cc:28:5: error: ‘decode_fst_’ was not declared in this scope
     decode_fst_ = NULL;
     ^~~~~~~~~~~
../src/kaldi_recognizer.cc:28:5: note: suggested alternative: ‘decoder_’
     decode_fst_ = NULL;
     ^~~~~~~~~~~
     decoder_
../src/kaldi_recognizer.cc:32:27: error: ‘LookaheadComposeFst’ was not declared in this scope
             decode_fst_ = LookaheadComposeFst(*model_.hcl_fst_, *model_.g_fst_, model_.disambig_);
                           ^~~~~~~~~~~~~~~~~~~
../src/kaldi_recognizer.cc: In constructor ‘KaldiRecognizer::KaldiRecognizer(Model&, float, const char*)’:
../src/kaldi_recognizer.cc:70:9: error: ‘decode_fst_’ was not declared in this scope
         decode_fst_ = LookaheadComposeFst(*model_.hcl_fst_, g_fst_, model_.disambig_);
         ^~~~~~~~~~~
../src/kaldi_recognizer.cc:70:9: note: suggested alternative: ‘decoder_’
         decode_fst_ = LookaheadComposeFst(*model_.hcl_fst_, g_fst_, model_.disambig_);
         ^~~~~~~~~~~
         decoder_
../src/kaldi_recognizer.cc:70:23: error: ‘LookaheadComposeFst’ was not declared in this scope
         decode_fst_ = LookaheadComposeFst(*model_.hcl_fst_, g_fst_, model_.disambig_);
                       ^~~~~~~~~~~~~~~~~~~
../src/kaldi_recognizer.cc:72:9: error: ‘decode_fst_’ was not declared in this scope
         decode_fst_ = NULL;
         ^~~~~~~~~~~
../src/kaldi_recognizer.cc:72:9: note: suggested alternative: ‘decoder_’
         decode_fst_ = NULL;
         ^~~~~~~~~~~
         decoder_
../src/kaldi_recognizer.cc:79:52: error: ‘decode_fst_’ was not declared in this scope
             model_.hclg_fst_ ? *model.hclg_fst_ : *decode_fst_,
                                                    ^~~~~~~~~~~
../src/kaldi_recognizer.cc:79:52: note: suggested alternative: ‘decoder_’
             model_.hclg_fst_ ? *model.hclg_fst_ : *decode_fst_,
                                                    ^~~~~~~~~~~
                                                    decoder_
../src/kaldi_recognizer.cc: In destructor ‘KaldiRecognizer::~KaldiRecognizer()’:
../src/kaldi_recognizer.cc:90:12: error: ‘decode_fst_’ was not declared in this scope
     delete decode_fst_;
            ^~~~~~~~~~~
../src/kaldi_recognizer.cc:90:12: note: suggested alternative: ‘decoder_’
     delete decode_fst_;
            ^~~~~~~~~~~
            decoder_
../src/kaldi_recognizer.h:50:14: error: ‘LookaheadFst’ in namespace ‘fst’ does not name a template type
         fst::LookaheadFst<fst::StdArc, int32> *decode_fst_;
              ^~~~~~~~~~~~
Makefile:31: recipe for target 'libvosk_jni.so' failed
make: *** [libvosk_jni.so] Error 1

```

**Comment by nshmyrev** [comment]
Hello. You need to build our branch of Kaldi as described in README:

https://github.com/alphacep/vosk-api#kaldi-compilation-for-local-python-node-and-java-modules

The pull request to merge changes is pending

https://github.com/kaldi-asr/kaldi/pull/3616

**Comment by stefan-reich** [comment]
Oooh... I followed the instructions precisely... except for that first line, LOL. Thanks.

BTW German recognition with vosk is very good, best open source recognition I have found so far. (For English, DeepSpeech seems stronger.)

**Comment by nshmyrev** [comment]
Ok, let me know if you have further questions. The German model is from Zamia, you can say thanks to Guenter.

For English you probably compare deepspeech server model with our android model. Our server model is much more accurate while deepspeech android model is not accurate at all.

**Comment by stefan-reich** [comment]
Hmm.. I use the tflite version of DeepSpeech for the main deployment on Raspberry-level machines

**Comment by nshmyrev** [comment]
Ok, you are welcome to provide the test samples, I will take a look.

**Comment by stefan-reich** [comment]
You mean audio files?

**Comment by nshmyrev** [comment]
Yes, audio files and optionally the transcripts.

**Comment by stefan-reich** [comment]
Is there an automated way to add these to a training corpus? That would be amazing. Doesn't seem smart to cause you manual work for every audio sample.

**Comment by nshmyrev** [comment]
Ok, up to you. Model training and language model adaptation is done with standard Kaldi model process, so you can run it too:

http://kaldi-asr.org/doc/online_decoding.html#online_decoding_nnet2_lm

You can also try Zamia RPi model, it might be more accurate for you

https://goofy.zamia.org/zamia-speech/asr-models/

**Comment by stefan-reich** [comment]
Thanks. I'm trying to understand. So when I want to add new words to the recognition, I can put them in a dictionary file which is basically just text or preferably phonemes. Correct?

However, if words that are known are just not well understood, I would probably have to go to a more complicated level of actually retraining the NN?

**Comment by stefan-reich** [comment]
BTW I love how your tool gives me timestamps for each word. Great applications are only waiting to be made with this.

**Comment by nshmyrev** [comment]
> Thanks. I'm trying to understand. So when I want to add new words to the recognition, I can put them in a dictionary file which is basically just text or preferably phonemes. Correct?

You have to add them both to the dictionary and to the language model, then you need to recompile the graph as linked above.

> However, if words that are known are just not well understood, I would probably have to go to a more complicated level of actually retraining the NN?

No, dictionary and LM is usually enough. NN retraining is only required for different acoustic conditions, for example, some unique background noise.

**Comment by stefan-reich** [comment]
Is there a tool to simplify this process? Looks like quiite some file formats, tool names and terminology have to be learned in order to do this. Not sure if I have the time but it's interesting

**Comment by nshmyrev** [comment]
No, there is no official tool yet, only the scripts linked above. It would be nice to have one though.

There are scripts in other packages like:

https://github.com/gooofy/zamia-speech/blob/master/speech_kaldi_adapt.py

https://github.com/synesthesiam/rhasspy/blob/2730c131d014670626f62bc23adb72ff56c3088f/rhasspy/stt_train.py

but I'm not sure if you can use them easily.
