### ISSUE TITLE
How to install on windows 10 with python 3.7

### ISSUE THREAD

**Issue by MrByte98** [alphacep/vosk-api#250]
hi, please help me to install this awesome package on windows 10 with python 3.7 version.

**Comment by nshmyrev** [comment]
We only support 3.8. We might support 3.7 some time in the future, but not a huge priority for us.

**Comment by MrByte98** [comment]
So please help me to install on python 3.8.
after run "pip install vosk" : ERROR: Could not find a version that satisfies the requirement vosk

**Comment by nshmyrev** [comment]
Make sure your python is 64-bit version, same as #252
