### ISSUE TITLE
Yet Another Speaker Identification Question

### ISSUE THREAD

**Issue by madkote** [alphacep/vosk-api#253]
Hi here!

Working currently on speaker identification and after I faced an unknown speaker "problem", Google guided me to this project.
In test scripts, there is an exampe to calculate the score of decoded xvector to the **stored** "signature" (in fact that could be a bunch of vectors).

Is there a way to find out if new decoded vector does not belong to the any known speakers? Sometimes the distance is dependent on the background noise and the language the speaker speaks.

Thanks!

**Comment by nshmyrev** [comment]
> Is there a way to find out if new decoded vector does not belong to the any known speakers? 

if distance is large the speaker is different.

> Sometimes the distance is dependent on the background noise and the language the speaker speaks.

If model is trained properly it should not matter.

Of course, current algorithms and models could be improved.

**Comment by madkote** [comment]
@nshmyrev Thanks for reply!

> > Is there a way to find out if new decoded vector does not belong to the any known speakers?
> 
> if distance is large the speaker is different.
Well, this is relative and in practice not useful for unknown speakers:
* for known => simply take the highest score
* for unknown => there might be some known signatures, where the score is also high, but speakers are different. (I have 5 speakers in my test setup).
 
> > Sometimes the distance is dependent on the background noise and the language the speaker speaks.
> 
> If model is trained properly it should not matter.
I use the default model available for kaldi (speaker diarization)

=== === === ====
Q) Just curious (I am not very expert in Kaldi world) - are there ranges in XVector, which might be more relevant for speaker then the environment (channel, background)? Or does the complete vector representing the speaker acoustic model?

Thank you!

**Comment by nshmyrev** [comment]
>  there might be some known signatures, where the score is also high, but speakers are different. (I have 5 speakers in my test setup).

You can provide audio data for analysis. In general, if speakers are different the score should be different

> Just curious (I am not very expert in Kaldi world) - are there ranges in XVector, which might be more relevant for speaker then the environment (channel, background)? Or does the complete vector representing the speaker acoustic model?

The vector represents the speaker voice (not the acoustic model). It should be independent on background (if model is trained properly).

**Comment by madkote** [comment]
Thank you @nshmyrev !
---
Regarding audio samples - I need then record myself or search free available samples (I can not send data not belonging to me).

---
Interesting, is that depending on mic and background - results might be also different.

---
I can share this:
```
>>> UNKNOWN [(0.729344, 'yyy'), (0.759806, 'xxx'), (0.805145, 'aaa'), (0.847765, 'zzz')]
>>> UNKNOWN (0.847765, 'zzz')
```
Where `xxx, yyy, zzz, aaa` are mean vectors (per speaker I collect multiple vectors and do a mean of them -> new vector), finally I compare. My expectation was, that distance between UNKNOWN and other should be low (0.8 could be the border - but distances do vary even for known speakers.

**Comment by nshmyrev** [comment]
Ok, let me know when you have more information.

**Comment by thefighter22** [comment]
how to calculate the distance between  the  x-vector to determine the identity of the speaker ?

**Comment by nshmyrev** [comment]
> how to calculate the distance between the x-vector to determine the identity of the speaker ?

With cosine distance like in the code sample

**Comment by nshmyrev** [comment]
Lets track this issue in #405
