### ISSUE TITLE
unimrcp-vosk-plugin - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by evios** [alphacep/vosk-api#254]
Hello Nikolay! Thank you for your work!

I wonder is it any special things to install to make this plugin work?

I built Kaldi, then uniMRCP dependencies for 1.6.0 ./build-dep-libs.sh

Then install plugin
git clone -b vosk-plugin https://github.com/alphacep/unimrcp-vosk-plugin.git /opt/unimrcp && cd /opt/unimrcp/ \
    && cd /opt/unimrcp/ \
    && export KALDI_ROOT=/opt/kaldi \
    && ./bootstrap \
    && ./configure \
    && make \
    && make install

No mistakes, everything built and install good.
But strange behaviour of server. 
Fail with (I will share in the end few more lines):
free(): invalid pointer
Aborted (core dumped)

More interesting - I ran demo test client scenarious
/usr/local/unimrcp/bin/umc

If I start with 
run recog # test scenario for speech recognition
2020-10-15 13:24:50:208341 [DEBUG]  Wait for Messages [MRCP Server]
2020-10-15 13:24:50:208351 [DEBUG]  Process Poller Wakeup [MRCPv2-Agent-1]
2020-10-15 13:24:50:208357 [DEBUG]  Process Message [MRCPv2-Agent-1] [0x7f91740012c0;1;0]
2020-10-15 13:24:50:208362 [INFO]   Send MRCPv2 Data 172.17.0.2:1544 <-> 172.17.0.2:38096 [83 bytes]
MRCP/2.0 83 2 200 IN-PROGRESS
Channel-Identifier: cd733c5c0ee911eb@speechrecog

2020-10-15 13:24:50:208411 [DEBUG]  Wait for Messages [MRCPv2-Agent-1] timeout [600000]
Segmentation fault (core dumped)

BUT if I run run synth, and than run recog - it works for test client scenarious

However still not worked with real applications - 
2020-10-15 13:26:28:608458 [INFO]   State Transition IDLE -> RECOGNIZING <0819a1840eea11eb@speechrecog>
2020-10-15 13:26:28:608463 [DEBUG]  Signal Message to [MRCPv2-Agent-1] [0x7f66100014e0;1;0]
2020-10-15 13:26:28:608472 [DEBUG]  Wait for Messages [MRCP Server]
2020-10-15 13:26:28:608487 [DEBUG]  Process Poller Wakeup [MRCPv2-Agent-1]
2020-10-15 13:26:28:608493 [DEBUG]  Process Message [MRCPv2-Agent-1] [0x7f66100014e0;1;0]
2020-10-15 13:26:28:608499 [INFO]   Send MRCPv2 Data 172.17.0.2:1544 <-> 172.18.96.47:44028 [85 bytes]
MRCP/2.0 85 103 200 IN-PROGRESS
Channel-Identifier: 0819a1840eea11eb@speechrecog

2020-10-15 13:26:28:608509 [DEBUG]  Wait for Messages [MRCPv2-Agent-1] timeout [600000]
free(): invalid pointer
Aborted (core dumped)

Can you recommend the best way to collect stacktrace?
Thank you

**Comment by evios** [comment]
my Dockerfile to reproduce issue:
```
docker build . t unimrcp_server
docker run -p 1544:1544 -p 8060:8060 -p 5001-5400:5001-5400 -v /opt/kaldi/model:/opt/kaldi/model:ro -it unimrcp_server
cd /usr/local/unimrcp/bin && tmux # just for easyness
run in first tmux ./unimrcpserver
run in second tmux ./umc # and inside of umc # run recog
```


```
FROM debian:10.4

ARG KALDI_MKL

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        g++ \
        gfortran \
        bzip2 \
        unzip \
        make \
        wget \
        git \
        python3 \
        python3-dev \
        python3-websockets \
        python3-setuptools \
        python3-pip \
        python3-wheel \
        zlib1g-dev \
        patch \
        ca-certificates \
        swig \
        cmake \
        xz-utils \
    && rm -rf /var/lib/apt/lists/*

RUN \
    git clone -b lookahead --single-branch https://github.com/alphacep/kaldi /opt/kaldi \
    && cd /opt/kaldi/tools \
    && sed -i 's:status=0:exit 0:g' extras/check_dependencies.sh \
    && sed -i 's:openfst_add_CXXFLAGS = -g -O2:openfst_add_CXXFLAGS = -g -O3 -msse2:g' Makefile \
    && sed -i 's:--enable-ngram-fsts:--enable-ngram-fsts --disable-bin:g' Makefile \
    && make -j $(nproc) openfst cub \
    && if [ "x$KALDI_MKL" != "x1" ] ; then \
          sed -i 's:python:python3:g' extras/install_openblas.sh; \
          sed -i 's:USE_LOCKING=1:DYNAMIC_ARCH=1 USE_LOCKING=1:g' extras/install_openblas.sh; \
          extras/install_openblas.sh; \
       else \
          extras/install_mkl.sh; \
       fi

RUN cd /opt/kaldi/src \
    && if [ "x$KALDI_MKL" != "x1" ] ; then \
          ./configure --mathlib=OPENBLAS --shared; \
       else \
          ./configure --mathlib=MKL --shared; \
       fi \
    && sed -i 's:-msse -msse2:-msse -msse2:g' kaldi.mk \
    && sed -i 's: -O1 : -O3 :g' kaldi.mk \
    && make -j $(nproc) online2 lm rnnlm \
    \
    && rm -rf /root/.cache \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    sudo \
    autoconf \
    automake \
    pkg-config \
    libtool \
    gcc 
     
RUN mkdir -p /opt/unimrcp-deps && wget http://www.unimrcp.org/project/component-view/unimrcp-deps-1-6-0-tar-gz/download -O - | tar -xz --strip-components=1 --directory /opt/unimrcp-deps
RUN cd /opt/unimrcp-deps && yes y | ./build-dep-libs.sh && ldconfig

RUN git clone -b vosk-plugin https://github.com/alphacep/unimrcp-vosk-plugin.git /opt/unimrcp && cd /opt/unimrcp/ \
    && cd /opt/unimrcp/ \
    && export KALDI_ROOT=/opt/kaldi \
    && ./bootstrap \
    && ./configure LDFLAGS="-rdynamic" \
    && make \
    && make install

##### just to work inside
RUN apt-get install -y --no-install-recommends \
    nano \
    tmux

CMD ["/bin/bash"]
```

**Comment by nshmyrev** [comment]
Fixed with https://github.com/alphacep/unimrcp-vosk-plugin/commit/8548e70bc028c7cc12008503b4959e5a1d07356e

**Comment by nshmyrev** [comment]
I also pushed docker image, you can run with simple:

`docker run  -p 1544:1544 -p 8060:8060 -p 5001-5200:5001-5200 alphacep/vosk-unimrcp`

**Comment by evios** [comment]
Nikolay, great, thank you!
I can confirm - now it works!
