### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by iProMC** [alphacep/vosk-api#255]
Hello, I have a problem with the code: wf = wave.open(sys.argv[1], "rb") when I ever start the project it says list index out of range. IDK this happens.

I just copy the test_simple.py

**Comment by nshmyrev** [comment]
You need to specify file name to read

**Comment by iProMC** [comment]
can you tell me what I can do in order to fix that?

**Comment by nshmyrev** [comment]
replace sys.argv[1] with the filename or check microphone example if you want to recognizer from microphone.

**Comment by iProMC** [comment]
ok thank you but I have a question do you have an example for wake up 
I mean if I say a specific word the vosk can start listening.

**Comment by nshmyrev** [comment]
> ok thank you but I have a question do you have an example for wake up

No, we do not support wakeup yet

**Comment by iProMC** [comment]
ok, do you know how I can stop print the res['text']. if I didn't say anything

**Comment by iProMC** [comment]
because even I didn't say anything the vosk still print empty text and I want to stop that

**Comment by nshmyrev** [comment]
Check if text is empty and skip print ;)

**Comment by iProMC** [comment]
can you give the code or an example of how to do that?

**Comment by iProMC** [comment]
I think I got the problem if the text empty it should skip print I think in this code

    if len(data) == 0:
        break

**Comment by nshmyrev** [comment]
Should be closed now I think, feel free to reopen if you have further questions.

**Comment by vlasych368** [comment]
Hello, I do have the same exact mistake:
 sys.argv[1],
IndexError: list index out of range
How do I should change the line sys.argv[1] to solve it? name of mp4 file is 1.mp4
