### ISSUE TITLE
Question: Error in Windows 10: The system cannot find the file specified

### ISSUE THREAD

**Issue by ecrofpu** [alphacep/vosk-api#256]
![image](https://user-images.githubusercontent.com/72737199/96337396-7cd5cf00-10a4-11eb-87f5-b9f2617779c7.png)

I am trying to run the example file `test_ffmpeg.py` file in Windows 10. `vosk` is installed in the machine. I don't really know why I am getting this error. The file 1.mp4 also exists.

**Comment by nshmyrev** [comment]
ffmpeg doesn't exist in your case

**Comment by ecrofpu** [comment]
Thought so. I am trying to install ffmpeg, let us hope that it works after the installation. Thanks for your reply!

**Comment by ecrofpu** [comment]
It worked!
