### ISSUE TITLE
Feature : check if a word can be recognized 

### ISSUE THREAD

**Issue by ThThoma** [alphacep/vosk-api#258]
Hello, 

I think I've read this request/feature in an older issue (can't find it though),

I want my user to create his own phrase list and so  
I want to make sure that my user added a _valid_ word to the phrase list **before** initializing the recognizer.

And by _valid_ word: a word that can be recognized, i.e a word included in the model's vocabulary.
I am only talking about _models with dynamic graphs_ as in #217 .

I wrote a simple function that searches the model's symbol table with `Find()`
and returns `>=0` if true or `-1` otherwise.

Would you like to see my `.diff` file, and if its no trouble, add it to the API?

If it is included in the API it will save me alot of time rebuilding on every new update.

Thank you.

**Comment by nshmyrev** [comment]
You are welcome to submit a pull request

**Comment by nshmyrev** [comment]
Fixed with https://github.com/alphacep/vosk-api/commit/0edab6d558eb4a395b2ba29b01bb11a900dda1ba

**Comment by ThThoma** [comment]
Cheers and thank you! ;)
