### ISSUE TITLE
Speaker Diarization Question

### ISSUE THREAD

**Issue by phunter-lab** [alphacep/vosk-api#261]
Hello! Thanks a lot for your work.
I am trying to label diffirent speakers in a long audio file. I've checked the example https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py but it is unclear for me how to detect speaker change and label recognized words properly. 
At each recognition step I have a specific vector with speaker features res['spk']. I can compare the previous vector with the current res['spk'] vector using the cosine distance measure and get some score. How can I use this score for speaker diarization and how can I label each word in recognition results by appropriate speaker? The partial recognition results usually include up to 1400 frames of the audio file (~10-20 seconds). 
Thanks a lot for your help.

**Comment by nshmyrev** [comment]
We do not support speaker diarization yet, you can run kaldi scripts directly like this post explains instead:

https://towardsdatascience.com/speaker-diarization-with-kaldi-e30301b05cc8

**Comment by nshmyrev** [comment]
Lets track at #405

**Comment by BadriAhmed** [comment]
Hello.
Thank you very much for your awesome work on VOSK, I wanted to know, is the speaker diarization implemented on the API now ?

**Comment by nshmyrev** [comment]
> Thank you very much for your awesome work on VOSK, I wanted to know, is the speaker diarization implemented on the API now ?

No, not yet. You can check kaldi diarization scripts/speechbrain/pyannote depending on your tasks

**Comment by amalvinob007** [comment]
speaker diarization implemented ?

**Comment by Aswad310** [comment]
speaker diarization implemented ?

**Comment by kenenbek** [comment]
speaker diarization implemented ?
