### ISSUE TITLE
vosk 0.3.3 for python 3.7 and win_amd64 expects python 3.8

### ISSUE THREAD

**Issue by padmalcom** [alphacep/vosk-api#266]
Error message is:

```
  File "C:\Users\admin\Anaconda3\envs\05_speech_to_text\lib\site-packages\vosk\vosk.py", line 13, in <module>
    from . import _vosk
ImportError: Module use of python38.dll conflicts with this version of Python.
```

I have a python 3.7 environment.

**Comment by nshmyrev** [comment]
We do not support python 3.7 on Windows, you have to use python 3.8 64-bit.

Maybe sometime later.

**Comment by padmalcom** [comment]
Hey thanks for the quick answer, but you have a wheel for version 0.3.3 here for python 3.7:
https://github.com/alphacep/vosk-api/releases/tag/0.3.3

I edited my answer. I didn't get to run it earlier on python 3.7.

**Comment by nshmyrev** [comment]
I'm sorry, I do not recommend you old version. We need to build for all python versions one day but it requires some work on CI build.

**Comment by nshmyrev** [comment]
Same as your previous bug (still open) https://github.com/alphacep/vosk-api/issues/200

**Comment by padmalcom** [comment]
Yes I know, we spoke in another issue about the CI pipeline. Thanks for your help.
