### ISSUE TITLE
"nspc"?

### ISSUE THREAD

**Issue by stefan-reich** [alphacep/vosk-api#27]
I am randomly getting the prefix "nspc " in the recognized text. Even with German text. "nspc wann nudeln begünstigen". What is this about? :)

**Comment by nshmyrev** [comment]
Explained here https://github.com/gooofy/zamia-speech/issues/66

**Comment by stefan-reich** [comment]
OK, so it's a "noise token"? What exactly is that?

**Comment by nshmyrev** [comment]
It is actually an artifact from incorrect model setup. I've reuploaded https://github.com/alphacep/kaldi-android-demo/releases/download/2020-01/alphacep-model-android-de-zamia-0.3.tar.gz, it should be free from that nspc now.

**Comment by stefan-reich** [comment]
Thank you, Nickolay.
