### ISSUE TITLE
cannot import name 'Model' from partially initialized module 'vosk' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#273]
trying the example 
https://github.com/alphacep/vosk-api/blob/master/python/example/test_ffmpeg.py

    from vosk import Model, KaldiRecognizer
ImportError: cannot import name 'Model' from partially initialized module 'vosk' (most likely due to a circular import) (/Users/xiao_li/repo/Momento/src/vosk.py)

**Comment by nshmyrev** [comment]
You have the source file named vosk.py, when you write import vosk, it imports module from your file, not from the system package. Try to name the file differently.
