### ISSUE TITLE
Vosk api accuracy improvment

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#274]
I have challenges with the Vosk accuracy, wondering what configs need to be tuned or it is the limit of it. 
I feel like the overall accuracy is around 60% on a good day, meaning when it does extract text from audio, it gets 60% of words in it correctly. 

I am using the following code from example with mp4 testfiles attached. 

tried both vosk-model-en-us-aspire-0.2 and vosk-model-small-en-us-0.4

Any suggestion?

Sample Code:

**`sample_rate = 16000
model = Model(model_path2)
rec = KaldiRecognizer(model, sample_rate)

process = subprocess.Popen(['ffmpeg', '-loglevel', 'quiet', '-i',
                            video_file,
                            '-ar', str(sample_rate), '-ac', '1', '-f', 's16le', '-'],
                           stdout=subprocess.PIPE)

while True:
    data = process.stdout.read(4000)
    if len(data) == 0:
        break
    rec.AcceptWaveform(data)`**

[testfiles.zip](https://github.com/alphacep/vosk-api/files/5477023/testfiles.zip)

**Comment by nshmyrev** [comment]
Your samples are expressive speech which are hard to recognize since they are not in the training data.

For best accuracy you'd better try daanzu model.

**Comment by nshmyrev** [comment]
Let me know if you need further help of if we can help somehow.
