### ISSUE TITLE
Split subtitles properly

### ISSUE THREAD

**Issue by nshmyrev** [alphacep/vosk-api#277]
> 
> 
> CVTE model uses pitch and requires code modification.
> 
> Otherwise you have to copy the files, as in https://alphacephei.com/vosk/models#model-structure

I found a short video from youtube to test generating subtitles. But compared with Google's speech recognition api (Google's on the left), I found that the segmentation is not very good, and there is no segmentation when it is needed. How can I solve this problem myself and make it closer to Google's segmentation?
![image](https://user-images.githubusercontent.com/19688305/97954326-eec14e80-1dee-11eb-87af-40a39e1af2b7.png)

_Originally posted by @R0FGV in https://github.com/alphacep/vosk-api/issues/267#issuecomment-720924203_

**Comment by nshmyrev** [comment]
We split by silence. Subtitles must be split by line length, even if there is no silence with 10 words  you need to split. That should be easy to implement in python but not yet implemented.

**Comment by R0FGV** [comment]
> We split by silence. Subtitles must be split by line length, even if there is no silence with 10 words you need to split. That should be easy to implement in python but not yet implemented.

ok  thanks

**Comment by R0FGV** [comment]
> We split by silence. Subtitles must be split by line length, even if there is no silence with 10 words you need to split. That should be easy to implement in python but not yet implemented.

Can you elaborate more? The segmentation operation should be controlled by parameters during the training model stage, right? I checked the python file of test_srt, but I didn't find a good way to split it. Thank you for taking the time

**Comment by nshmyrev** [comment]
Fixed in this commit:

https://github.com/alphacep/vosk-api/commit/746ff477572f6d903be52143e2f689f89c0f6ae8
