### ISSUE TITLE
docker container exits within ~15 seconds

### ISSUE THREAD

**Issue by bigrig2212** [alphacep/vosk-api#278]
Hi there. 
After running the docker container using:
docker run -d -p 2700:2700 alphacep/kaldi-en:latest
with python8.0
it exits after about 15 seconds.
any tips?

**Comment by nshmyrev** [comment]
Try without -d and see what it prints

Most likely it goes out of memory, it needs about 4Gb.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-server/issues/77
