### ISSUE TITLE
How can i only get text result in Android?

### ISSUE THREAD

**Issue by cxdxng** [alphacep/vosk-api#279]
Hello everybody, i know it has been explained for python in the past, but i cannot get the pure text result from Vosk in Android without the debug information. Could anybody please help?

**Comment by nshmyrev** [comment]
Hi. You can use json parser, something like this:

```
JSONObject jres = new JSONObject(result);
String text = jres.get("Result");

```

**Comment by cxdxng** [comment]
Thank you, worked just fine!
