### ISSUE TITLE
help needed 

### ISSUE THREAD

**Issue by thefighter22** [alphacep/vosk-api#282]
excuse me im still new to this area of machine learning and speech recognition i'v read the documentation and  installed  vosk and tried test_microphone in python/examples  and it works very well but i have a problem with some sentences and words like weather  it never  transcribe it correctly instead it says whether or thoose who ,  so can i solve this problem   ?

and another question:
i tried i read the adaption section in the documentation and  understood that for dynamic models we could update the vocabulary   on real time  and i configured the audio to be PCM 16khz 16bit mono and and tried to add some new words in my original language but with english letters but i got  no luck getting it to work so what's wrong here ?

**Comment by nshmyrev** [comment]
You need to provide audio recording samples to get help on the accuracy

You can not recognize non-english words with English model.

**Comment by thefighter22** [comment]
You need to provide audio recording samples to get help on the accuracy
how can i do that ?
is it fine-tuning ?

**Comment by nshmyrev** [comment]
You record an audio sample and attach/link it here.

**Comment by thefighter22** [comment]
[weather.zip](https://github.com/alphacep/vosk-api/files/5503780/weather.zip)

**Comment by thefighter22** [comment]
u mean attaching it here like this ?

**Comment by nshmyrev** [comment]
You can try to force words as in here 

https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py

it should help you.

**Comment by v-yunbin** [comment]
I test a wav named "2ae1fec4-0fd6-4d31-87e6-edefc021ee22.wav" from open data "primewords" 
The  real transcription is ：零五四零四幺六二零零三甘肃天马八三二中国二幺幺二零零幺
I test without hotwords，result is as follows：
`LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0386579 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:242) Loading HCL and G from model/HCLr.fst model/Gr.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:264) Loading winfo model/word_boundary.int
零五 四 零 四 要 六 二零零三 甘肃 天马 八 三 二 中国 二 要 约 二零零 要
`
"幺" is wrongly transcribed as " 要"，so i want to correct it throught the hot words
add hot words：`rec = KaldiRecognizer(model, 16000, '["幺"]')`
but rec result is as follows：
`LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0356669 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:242) Loading HCL and G from model/HCLr.fst model/Gr.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:264) Loading winfo model/word_boundary.int
LOG (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:68) ["幺"]
LOG (VoskAPI:Estimate():vosk/language_model.cc:142) Estimating language model with ngram-order=2, discount=0.5
LOG (VoskAPI:OutputToFst():vosk/language_model.cc:209) Created language model with 2 states and 2 arcs.
幺 幺 幺 幺 幺 幺 幺
幺 幺 幺
幺 幺 幺 幺
`
