### ISSUE TITLE
speaker_indentification what next ?

### ISSUE THREAD

**Issue by thefighter22** [alphacep/vosk-api#284]
after using text_speaker.py with my own wav audio file (CM 16khz 16bit mono) and then extracting the  x-vector of the speaker 
how then can i use this output to determine if the speaker is correct or not (identifying the speaker )
also another question 
can't we identify the speaker by just his voice regardless of the words or sentences ?

**Comment by nshmyrev** [comment]
Same as #237 and #253

**Comment by thefighter22** [comment]
how can i compute the difference  to identify the speaker ?

**Comment by nshmyrev** [comment]
Demonstrated here:

https://github.com/alphacep/vosk-api/blob/b639fb501a78edf7221ec4ccec1a7ad901e75c0c/python/example/test_speaker.py#L35

**Comment by thefighter22** [comment]
i got the distance  in my test .07 and  this is pretty small  so my question what is the distance range  to determine  if the it is small or not  ?
for example  i want to make condition if distance <1  then speaker=1 
my second question is it possible to work  with speaker recognition  with input from  microphone  stream  by pyaudio with no problems ?
you said in #237  than we use speech recognition models to help get the utterances i understand  but  the result in dependent  100% on the speaker  voice  regardless  of  the spoken words for example if  i say hello world and if i say how are you it would i identify the same speaker right ?
