### ISSUE TITLE
accuracy_increase

### ISSUE THREAD

**Issue by thefighter22** [alphacep/vosk-api#285]
first i want to really thank you for your great collaboration  and  the fast response ,
like in #282   i used the test_words with the dynamic models  and  used the 4 wav files like in #282 but i found no increase in the accuracy at all int the word weather  transcription using my microphone stream by pyaudio 
but when i tried the same wave file  as input   it could detect  2 out 5 (weather  word) 
so  what u advise me to do ?

and here is my code 
#!/usr/bin/env python3

from vosk import Model, KaldiRecognizer
import sys
import os
import wave
for i in range (1000):
    
    if not os.path.exists("model"):
        print ("Please download the model from https://alphacephei.com/vosk/models and unpack as 'model' in the current folder.")
        exit (1)
    for k in range(1,5):
        audio='weather'+str(k)+'.wav'
        wf = wave.open(audio, "rb")
        if wf.getnchannels() != 1 or wf.getsampwidth() != 2 or wf.getcomptype() != "NONE":
            print ("Audio file must be WAV format mono PCM.")
            exit (1)

        model = Model("model")

        # You can also specify the possible word or phrase list as JSON list, the order doesn't have to be strict
        rec = KaldiRecognizer(model, 16000, '[" weather  weather  weather  weather  weather ", "[unk]"]')

        while True:
            data = wf.readframes(4000)
            if len(data) == 0:
                break
            if rec.AcceptWaveform(data):
                print(rec.Result())
            else:
                print(rec.PartialResult())

        print(rec.FinalResult())

**Comment by nshmyrev** [comment]
There is no need to file the same issue on the same subject, you can continue in #282
