### ISSUE TITLE
add_new words

### ISSUE THREAD

**Issue by jordankindsons** [alphacep/vosk-api#286]
hello  i'm using vosk-model-en-us-daanzu-20200905-lgraph  and i'm making an ai assistant which basically first take speech as input and transcribe  it into text and then  the text goes to the expert system  which decide  what to say and then  do some text to speech ,  and i 'v used vosk and i want to say i'm quite impressed by the performance  and accuracy it has .
but  i want to ask how can  i add some words to vocabulary like the name of the assistant we will call it semada  can  we add  not just english words but also names and places to  the vocabulary ?

**Comment by nshmyrev** [comment]
it is covered in https://alphacephei.com/vosk/adaptation#updating-words-and-the-vocabulary-in-the-big-models

**Comment by nshmyrev** [comment]
Same as #156
