### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by panmarco83** [alphacep/vosk-api#287]
There does not seem to be any documentation for all the functions and a proper explanation of how to structure a script/program other than the examples.
This is not enough, I'm afraid.
Documentation and references for all available functions.
An example of what I am talking about is trying to disable the excessive logging on model load and only finding a vague reference on stackexchange to something that might work.
Again, I would have liked to reduce the amount of logging by changing the log level instead of setting -1 but I can not find a proper description of the log levels.

**Comment by nshmyrev** [comment]
It is here:

https://github.com/alphacep/vosk-api/blob/b639fb501a78edf7221ec4ccec1a7ad901e75c0c/src/vosk_api.h#L206

**Comment by panmarco83** [comment]
Thank you, but I figured that part out by the stack exchange post mentioned in the first comment.
