### ISSUE TITLE
Latest API Release - Windows 

### ISSUE THREAD

**Issue by ThThoma** [alphacep/vosk-api#288]
Hello, 

when working on Windows with Python 3.8-64bit, I noticed I couldn't get the API's latest release. 
(My pip version is 20.2.1)

After running `pip3 -v install vosk`  I get pretty much the same output as #252 but without the errors at the end.
Instead I get:
 ```
Given no hashes to check 1 links for project 'vosk': discarding no candidates
Using version 0.3.7 (newest of versions: 0.3.7)
Collecting vosk
``` 
The latest release however is `0.3.15`. Is there anyway I can get the latest version on Windows?

**Comment by nshmyrev** [comment]
I will try to rebuild it soon

**Comment by ThThoma** [comment]
Thank you nshmyrev, you are the best!

Would it be possible to know if the new version (i.e `0.3.16`) is coming soon?

**Comment by ThThoma** [comment]
Hey nshmyrev,

I've paid more attention on the commits from version `0.3.15` to now,  
and noticed there is no major difference.  
Sorry for "pushing" for the next release.  

Keep up the good work! Closing.
