### ISSUE TITLE
RunNnetComputation problem

### ISSUE THREAD

**Issue by chenhaitao2026** [alphacep/vosk-api#289]
Hello, 
thanks for this excellent work.

For my application, I want change the SpkModel which extract xvector to extract bottleneck (BNF) features, just as the [ make_bottleneck_features.sh ](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet3/make_bottleneck_features.sh)script    do.  I follow the step as the script, use the output model generate by nnet3-copy.

but errors when run RunNnetComputation function, log as follow:
LOG (VoskAPI:ExplainWhyAllOutputsNotComputable():nnet-computation-graph.cc:351) 1 output cindexes out of 1 were not computable.
LOG (VoskAPI:ExplainWhyAllOutputsNotComputable():nnet-computation-graph.cc:355) Computation request was:  # Computation request:
input-0: name=input, has-deriv=false, indexes=[(0,0:80)]
output-0: name=output, has-deriv=false, indexes=[(0,0)]
need-model-derivative: false
store-component-stats: false

LOG (VoskAPI:ExplainWhyNotComputable():nnet-computation-graph.cc:172) *** cindex output(0, 0, 0) is not computable for the following reason: ***
output(0, 0, 0) is kNotComputable, dependencies: output.affine(0, 0, 0)[kNotComputable], 
output.affine(0, 0, 0) is kNotComputable, dependencies: output.affine_input(0, 0, 0)[kNotComputable], 
output.affine_input(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.batchnorm2(0, 0, 0)[kNotComputable], 
prefinal-chain.batchnorm2(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.batchnorm2_input(0, 0, 0)[kNotComputable], 
prefinal-chain.batchnorm2_input(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.linear(0, 0, 0)[kNotComputable], 
prefinal-chain.linear(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.linear_input(0, 0, 0)[kNotComputable], 
prefinal-chain.linear_input(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.batchnorm1(0, 0, 0)[kNotComputable], 
prefinal-chain.batchnorm1(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.batchnorm1_input(0, 0, 0)[kNotComputable], 
prefinal-chain.batchnorm1_input(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.relu(0, 0, 0)[kNotComputable], 
prefinal-chain.relu(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.relu_input(0, 0, 0)[kNotComputable], 
prefinal-chain.relu_input(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.affine(0, 0, 0)[kNotComputable], 
prefinal-chain.affine(0, 0, 0) is kNotComputable, dependencies: prefinal-chain.affine_input(0, 0, 0)[kNotComputable], 
prefinal-chain.affine_input(0, 0, 0) is kNotComputable, dependencies: prefinal-l(0, 0, 0)[kNotComputable], 
prefinal-l(0, 0, 0) is kNotComputable, dependencies: prefinal-l_input(0, 0, 0)[kNotComputable], 
prefinal-l_input(0, 0, 0) is kNotComputable, dependencies: tdnnf18.noop(0, 0, 0)[kNotComputable], 
tdnnf18.noop(0, 0, 0) is kNotComputable, dependencies: tdnnf18.noop_input(0, 0, 0)[kNotComputable], 
tdnnf18.noop_input(0, 0, 0) is kNotComputable, dependencies: tdnnf17.noop(0, 0, 0)[kNotComputable]tdnnf18.dropout(0, 0, 0)[kUnknown], 
tdnnf17.noop(0, 0, 0) is kNotComputable, dependencies: tdnnf17.noop_input(0, 0, 0)[kNotComputable], 
tdnnf18.dropout(0, 0, 0) is kUnknown, dependencies: tdnnf18.dropout_input(0, 0, 0)[kUnknown], 
tdnnf17.noop_input(0, 0, 0) is kNotComputable, dependencies: tdnnf16.noop(0, 0, 0)[kNotComputable]tdnnf17.dropout(0, 0, 0)[kUnknown], 
tdnnf18.dropout_input(0, 0, 0) is kUnknown, dependencies: tdnnf18.batchnorm(0, 0, 0)[kUnknown], 
tdnnf16.noop(0, 0, 0) is kNotComputable, dependencies: tdnnf16.noop_input(0, 0, 0)[kNotComputable], 
tdnnf17.dropout(0, 0, 0) is kUnknown, dependencies: tdnnf17.dropout_input(0, 0, 0)[kUnknown], 
tdnnf18.batchnorm(0, 0, 0) is kUnknown, dependencies: tdnnf18.batchnorm_input(0, 0, 0)[kUnknown], 
tdnnf16.noop_input(0, 0, 0) is kNotComputable, dependencies: tdnnf15.noop(0, 0, 0)[kNotComputable]tdnnf16.dropout(0, 0, 0)[kUnknown], 
tdnnf17.dropout_input(0, 0, 0) is kUnknown, dependencies: tdnnf17.batchnorm(0, 0, 0)[kUnknown], 
tdnnf18.batchnorm_input(0, 0, 0) is kUnknown, dependencies: tdnnf18.relu(0, 0, 0)[kUnknown], 
tdnnf15.noop(0, 0, 0) is kNotComputable, dependencies: tdnnf15.noop_input(0, 0, 0)[kNotComputable], 
tdnnf16.dropout(0, 0, 0) is kUnknown, dependencies: tdnnf16.dropout_input(0, 0, 0)[kUnknown], 
tdnnf17.batchnorm(0, 0, 0) is kUnknown, dependencies: tdnnf17.batchnorm_input(0, 0, 0)[kUnknown], 
tdnnf18.relu(0, 0, 0) is kUnknown, dependencies: tdnnf18.relu_input(0, 0, 0)[kUnknown], 
tdnnf15.noop_input(0, 0, 0) is kNotComputable, dependencies: tdnnf14.noop(0, 0, 0)[kNotComputable]tdnnf15.dropout(0, 0, 0)[kUnknown], 
tdnnf16.dropout_input(0, 0, 0) is kUnknown, dependencies: tdnnf16.batchnorm(0, 0, 0)[kUnknown], 
tdnnf17.batchnorm_input(0, 0, 0) is kUnknown, dependencies: tdnnf17.relu(0, 0, 0)[kUnknown], 
tdnnf18.relu_input(0, 0, 0) is kUnknown, dependencies: tdnnf18.affine(0, 0, 0)[kUnknown], 
tdnnf14.noop(0, 0, 0) is kNotComputable, dependencies: tdnnf14.noop_input(0, 0, 0)[kNotComputable], 
tdnnf15.dropout(0, 0, 0) is kUnknown, dependencies: tdnnf15.dropout_input(0, 0, 0)[kUnknown], 
tdnnf16.batchnorm(0, 0, 0) is kUnknown, dependencies: tdnnf16.batchnorm_input(0, 0, 0)[kUnknown], 
tdnnf17.relu(0, 0, 0) is kUnknown, dependencies: tdnnf17.relu_input(0, 0, 0)[kUnknown], 
tdnnf18.affine(0, 0, 0) is kUnknown, dependencies: tdnnf18.affine_input(0, 0, 0)[kUnknown]tdnnf18.affine_input(0, 3, 0)[kUnknown], 
tdnnf14.noop_input(0, 0, 0) is kNotComputable, dependencies: tdnnf13.noop(0, 0, 0)[kNotComputable]tdnnf14.dropout(0, 0, 0)[kUnknown], 
tdnnf15.dropout_input(0, 0, 0) is kUnknown, dependencies: tdnnf15.batchnorm(0, 0, 0)[kUnknown], 
tdnnf16.batchnorm_input(0, 0, 0) is kUnknown, dependencies: tdnnf16.relu(0, 0, 0)[kUnknown], 
tdnnf17.relu_input(0, 0, 0) is kUnknown, dependencies: tdnnf17.affine(0, 0, 0)[kUnknown], 
tdnnf18.affine_input(0, 0, 0) is kUnknown, dependencies: tdnnf18.linear(0, 0, 0)[kUnknown], 
tdnnf18.affine_input(0, 3, 0) is kUnknown, dependencies: tdnnf18.linear(0, 3, 0)[kUnknown], 
tdnnf13.noop(0, 0, 0) is kNotComputable, dependencies: tdnnf13.noop_input(0, 0, 0)[kNotComputable], 
tdnnf14.dropout(0, 0, 0) is kUnknown, dependencies: tdnnf14.dropout_input(0, 0, 0)[kUnknown], 
tdnnf15.batchnorm(0, 0, 0) is kUnknown, dependencies: tdnnf15.batchnorm_input(0, 0, 0)[kUnknown], 
tdnnf16.relu(0, 0, 0) is kUnknown, dependencies: tdnnf16.relu_input(0, 0, 0)[kUnknown], 
tdnnf17.affine(0, 0, 0) is kUnknown, dependencies: tdnnf17.affine_input(0, 0, 0)[kUnknown]tdnnf17.affine_input(0, 3, 0)[kUnknown], 
tdnnf18.linear(0, 0, 0) is kUnknown, dependencies: tdnnf18.linear_input(0, -3, 0)[kUnknown]tdnnf18.linear_input(0, 0, 0)[kNotComputable], 
tdnnf18.linear(0, 3, 0) is kUnknown, dependencies: tdnnf18.linear_input(0, 0, 0)[kNotComputable]tdnnf18.linear_input(0, 3, 0)[kUnknown], 
tdnnf13.noop_input(0, 0, 0) is kNotComputable, dependencies: tdnnf12.noop(0, 0, 0)[kNotComputable]tdnnf13.dropout(0, 0, 0)[kUnknown], 
tdnnf14.dropout_input(0, 0, 0) is kUnknown, dependencies: tdnnf14.batchnorm(0, 0, 0)[kUnknown], 
tdnnf15.batchnorm_input(0, 0, 0) is kUnknown, dependencies: tdnnf15.relu(0, 0, 0)[kUnknown], 
tdnnf16.relu_input(0, 0, 0) is kUnknown, dependencies: tdnnf16.affine(0, 0, 0)[kUnknown], 
tdnnf17.affine_input(0, 0, 0) is kUnknown, dependencies: tdnnf17.linear(0, 0, 0)[kUnknown], 
tdnnf17.affine_input(0, 3, 0) is kUnknown, dependencies: tdnnf17.linear(0, 3, 0)[kUnknown], 
tdnnf18.linear_input(0, -3, 0) is kUnknown, dependencies: tdnnf17.noop(0, -3, 0)[kNotComputable], 
tdnnf18.linear_input(0, 0, 0) is kNotComputable, dependencies: tdnnf17.noop(0, 0, 0)[kNotComputable], 
tdnnf18.linear_input(0, 3, 0) is kUnknown, dependencies: tdnnf17.noop(0, 3, 0)[kNotComputable], 
tdnnf12.noop(0, 0, 0) is kNotComputable, dependencies: tdnnf12.noop_input(0, 0, 0)[kNotComputable], 
tdnnf13.dropout(0, 0, 0) is kUnknown, dependencies: tdnnf13.dropout_input(0, 0, 0)[kUnknown], 
tdnnf14.batchnorm(0, 0, 0) is kUnknown, dependencies: tdnnf14.batchnorm_input(0, 0, 0)[kUnknown], 
tdnnf15.relu(0, 0, 0) is kUnknown, dependencies: tdnnf15.relu_input(0, 0, 0)[kUnknown], 
tdnnf16.affine(0, 0, 0) is kUnknown, dependencies: tdnnf16.affine_input(0, 0, 0)[kUnknown]tdnnf16.affine_input(0, 3, 0)[kUnknown], 
tdnnf17.linear(0, 0, 0) is kUnknown, dependencies: tdnnf17.linear_input(0, -3, 0)[kUnknown]tdnnf17.linear_input(0, 0, 0)[kNotComputable], 
tdnnf17.linear(0, 3, 0) is kUnknown, dependencies: tdnnf17.linear_input(0, 0, 0)[kNotComputable]tdnnf17.linear_input(0, 3, 0)[kUnknown], 
tdnnf17.noop(0, -3, 0) is kNotComputable, dependencies: tdnnf17.noop_input(0, -3, 0)[kNotComputable], 
tdnnf17.noop(0, 3, 0) is kNotComputable, dependencies: tdnnf17.noop_input(0, 3, 0)[kNotComputable], 
tdnnf12.noop_input(0, 0, 0) is kNotComputable, dependencies: tdnnf11.noop(0, 0, 0)[kNotComputable]tdnnf12.dropout(0, 0, 0)[kUnknown], 
tdnnf13.dropout_input(0, 0, 0) is kUnknown, dependencies: tdnnf13.batchnorm(0, 0, 0)[kUnknown], 
tdnnf14.batchnorm_input(0, 0, 0) is kUnknown, dependencies: tdnnf14.relu(0, 0, 0)[kUnknown], 
tdnnf15.relu_input(0, 0, 0) is kUnknown, dependencies: tdnnf15.affine(0, 0, 0)[kUnknown], 
tdnnf16.affine_input(0, 0, 0) is kUnknown, dependencies: tdnnf16.linear(0, 0, 0)[kUnknown], 
tdnnf16.affine_input(0, 3, 0) is kUnknown, dependencies: tdnnf16.linear(0, 3, 0)[kUnknown], 
tdnnf17.linear_input(0, -3, 0) is kUnknown, dependencies: tdnnf16.noop(0, -3, 0)[kNotComputable], 
tdnnf17.linear_input(0, 0, 0) is kNotComputable, dependencies: tdnnf16.noop(0, 0, 0)[kNotComputable], 
tdnnf17.linear_input(0, 3, 0) is kUnknown, dependencies: tdnnf16.noop(0, 3, 0)[kNotComputable], 
tdnnf17.noop_input(0, -3, 0) is kNotComputable, dependencies: tdnnf16.noop(0, -3, 0)[kNotComputable]tdnnf17.dropout(0, -3, 0)[kUnknown], 
tdnnf17.noop_input(0, 3, 0) is kNotComputable, dependencies: tdnnf16.noop(0, 3, 0)[kNotComputable]tdnnf17.dropout(0, 3, 0)[kUnknown], 
tdnnf11.noop(0, 0, 0) is kNotComputable, dependencies: tdnnf11.noop_input(0, 0, 0)[kNotComputable], 
tdnnf12.dropout(0, 0, 0) is kUnknown, dependencies: tdnnf12.dropout_input(0, 0, 0)[kUnknown], 
tdnnf13.batchnorm(0, 0, 0) is kUnknown, dependencies: tdnnf13.batchnorm_input(0, 0, 0)[kUnknown], 
tdnnf14.relu(0, 0, 0) is kUnknown, dependencies: tdnnf14.relu_input(0, 0, 0)[kUnknown], 
tdnnf15.affine(0, 0, 0) is kUnknown, dependencies: tdnnf15.affine_input(0, 0, 0)[kUnknown]tdnnf15.affine_input(0, 3, 0)[kUnknown], 
tdnnf16.linear(0, 0, 0) is kUnknown, dependencies: tdnnf16.linear_input(0, -3, 0)[kNotComputable]tdnnf16.linear_input(0, 0, 0)[kNotComputable], 
tdnnf16.linear(0, 3, 0) is kUnknown, dependencies: tdnnf16.linear_input(0, 0, 0)[kNotComputable]tdnnf16.linear_input(0, 3, 0)[kNotComputable], 
tdnnf16.noop(0, -3, 0) is kNotComputable, dependencies: tdnnf16.noop_input(0, -3, 0)[kNotComputable], 
tdnnf16.noop(0, 3, 0) is kNotComputable, dependencies: tdnnf16.noop_input(0, 3, 0)[kNotComputable], 
tdnnf17.dropout(0, -3, 0) is kUnknown, dependencies: tdnnf17.dropout_input(0, -3, 0)[kUnknown], 
tdnnf17.dropout(0, 3, 0) is kUnknown, dependencies: tdnnf17.dropout_input(0, 3, 0)[kUnknown], 
tdnnf11.noop_input(0, 0, 0) is kNotComputable, dependencies: tdnnf10.noop(0, 0, 0)[kNotComputable]tdnnf11.dropout(0, 0, 0)[kUnknown], 
tdnnf12.dropout_input(0, 0, 0) is kUnknown, dependencies: tdnnf12.batchnorm(0, 0, 0)[kUnknown], 
tdnnf13.batchnorm_input(0, 0, 0) is kUnknown, dependencies: tdnnf13.relu(0, 0, 0)[kUnknown], 
tdnnf14.relu_input(0, 0, 0) is kUnknown, dependencies: tdnnf14.affine(0, 0, 0)[kUnknown], 
tdnnf15.affine_input(0, 0, 0) is kUnknown, dependencies: tdnnf15.linear(0, 0, 0)[kUnknown], 
tdnnf15.affine_input(0, 3, 0) is kUnknown, dependencies: tdnnf15.linear(0, 3, 0)[kUnknown], 
tdnnf16.linear_input(0, -3, 0) is kNotComputable, dependencies: tdnnf15.noop(0, -3, 0)[kNotComputable], 

ERROR (VoskAPI:CreateComputation():nnet-compile.cc:59) Not all outputs were computable, cannot create computation.

can you give some suggestions?
thank you.
again, thanks for your greate job.

**Comment by nshmyrev** [comment]
Usually this error means you have less frames that network minimal window requires. Try to increase MIN_SPK_FRAMES to process only longer utterances. I guess it should be more than 80 frames.

**Comment by nshmyrev** [comment]
https://github.com/alphacep/vosk-api/blob/b639fb501a78edf7221ec4ccec1a7ad901e75c0c/src/kaldi_recognizer.cc#L319

**Comment by chenhaitao2026** [comment]
I tried increase MIN_SPK_FEATS to 80 or even more large number 400, but it do not help

**Comment by nshmyrev** [comment]
@chenht2010 sorry, can you explain a bit more, probably I misunderstood. Are you trying to extract features from MFCC, not xvector? I.e. you want to get a sequence of vectors instead of single result? 

Did you try to extract features with Kaldi command line binaries already? Does nnet3-compute work for you?

**Comment by chenhaitao2026** [comment]
Yes, nnet3-compute worked for me. I debug it, find some context setting error, because my model left_context are different from the xvector model.  Finally, I got it work for me.
Again, thanks for your help, and your great job.
