### ISSUE TITLE
Cannot install version 0.3.1 on Raspbian 

### ISSUE THREAD

**Issue by agonzalezd** [alphacep/vosk-api#29]
Hello

First of all, thanks for this repository.

I am trying to install Vosk on Raspbian on a 4GB Raspberry Pi 4 but it cannot install version 0.3.1.

Pip (20.0.2) says that wouldn't find a version 0.3.1 and installs the 0.3. When installing whl files none of them are compatible. I am trying to avoid installing the whole Kaldi in the Raspberry since it will take a lot of free space. 

I want to install this version since I cannot pass a list of words to a KaldiRecognizer in version 0.3. 

Also, the model seems not to find a HCLG.fst file and requires a HCLr.fst and a Gr.fst separatedly, at least in version 0.3, when passing a model folder made by us.

Thanks for your time,

Ander

**Comment by nshmyrev** [comment]
Hi

Sorry to hear that. We are in the process of automating the build with travis, hopefully soon wheels will be updated automatically.

Meanwhile please try https://files.pythonhosted.org/packages/2b/18/d9cc168c602ea0e28d0e967232bd05cbc7aa37a4db7a591b69434e4d8660/vosk-0.3.1-cp37-cp37m-linux_armv7l.whl

Let me know.

**Comment by agonzalezd** [comment]
Yes, thank you

With this build it was perfectly installed. 

It still cannot find an HCLG.fst on the model folder, though; but I may open a new issue for that. 

Thanks!

**Comment by nshmyrev** [comment]
@agonzalezd ok, please try again

https://files.pythonhosted.org/packages/c4/f0/b361875890313eb8aee1eada0c6b1bb1ebd99a513b468be70890a2b0e9f6/vosk-0.3.2-cp37-cp37m-linux_armv7l.whl

that one should be better

**Comment by agonzalezd** [comment]
It still cannot find the HCLG.fst...

Let us discuss this in other new issue in the case anyone may face the same problem.

Thank you!
