### ISSUE TITLE
[unk] when use small LM with big AM

### ISSUE THREAD

**Issue by dmazurok** [alphacep/vosk-api#290]
Hello everyone!

I try to use small language model with a big acoustic model (Russian language), but in that case, instead of words I have only a sequence of _[unk]_ and no a single word. 
What I did was:
1. Substitute graph folder with the one from small model
2. When it didn't work, I tried to add missing files from a big model, such as words.txt and so on, avoiding substitution of matching files

Still have only _[unk]_ as an answer. What is the right way to combine big acoustic model and a small language model? 

Thank you!

**Comment by nshmyrev** [comment]
It is hard to guess, you'd better provide more details - model files, scripts, logs

**Comment by nshmyrev** [comment]
Feel free to reopen if you have more information
