### ISSUE TITLE
Problems building C test_vosk 

### ISSUE THREAD

**Issue by GabrieldeAS** [alphacep/vosk-api#291]
I have encountered this issue while compiling test_vosk:

/usr/bin/ld: /home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-matrix.a(kaldi-vector.o): in function `kaldi::VectorBase<float>::Pow(kaldi::VectorBase<float> const&, float)':
/home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-vector.cc:458: undefined reference to `vsPowx'
/usr/bin/ld: /home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-matrix.a(kaldi-vector.o): in function `kaldi::VectorBase<double>::Pow(kaldi::VectorBase<double> const&, double)':
/home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-vector.cc:462: undefined reference to `vdPowx'
/usr/bin/ld: /home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-matrix.a(kaldi-vector.o): in function `kaldi::VectorBase<float>::Tanh(kaldi::VectorBase<float> const&)':
/home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-vector.cc:891: undefined reference to `vsTanh'
/usr/bin/ld: /home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-matrix.a(kaldi-vector.o): in function `kaldi::VectorBase<double>::Tanh(kaldi::VectorBase<double> const&)':
/home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-vector.cc:896: undefined reference to `vdTanh'
/usr/bin/ld: /home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-matrix.a(kaldi-vector.o): in function `kaldi::VectorBase<float>::Sigmoid(kaldi::VectorBase<float> const&)':
/home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-vector.cc:923: undefined reference to `vsTanh'
/usr/bin/ld: /home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-matrix.a(kaldi-vector.o): in function `kaldi::VectorBase<double>::Sigmoid(kaldi::VectorBase<double> const&)':
/home/proletario/Desktop/venv/packages/vosk-Kaldi/kaldi-vosk-fork/kaldi/src/matrix/kaldi-vector.cc:932: undefined reference to `vdTanh'
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: test_vosk] Error 1

gcc, g++ and gfortran versions are 9.3.0
I used Vosk`s Kaldi fork. The Makefile is in annex.

![test_vosk](https://user-images.githubusercontent.com/48355243/98823438-dbc30580-2410-11eb-8ff8-b7f12bba45aa.png)

**Comment by nshmyrev** [comment]
You compiled Kaldi with mkl, the makefile expects openblas. Recompile Kaldi or change the makefile.

**Comment by GabrieldeAS** [comment]
It worked, thank you.

configure reference: https://github.com/kaldi-asr/kaldi/blob/master/src/configure
