### ISSUE TITLE
open source license?

### ISSUE THREAD

**Issue by bigrig2212** [alphacep/vosk-api#292]
Hi. Just wondering what the open source license details are? Can't find that anywhere on website? Thx.

**Comment by nshmyrev** [comment]
https://github.com/alphacep/vosk-api/blob/master/COPYING ?

**Comment by bigrig2212** [comment]
Fantastic. And how can I support the project? Is there a place where you take donations... or other kind of help you want/need?

**Comment by nshmyrev** [comment]
You are welcome. Thank you, we do not take donations yet. 

Let us know if we can help somehow too.

**Comment by nshmyrev** [comment]
Feel free to reopen.
