### ISSUE TITLE
audio formats limitations?

### ISSUE THREAD

**Issue by WPFilmmaker** [alphacep/vosk-api#293]
Hello on your site you mention:

"When using your own audio file make sure it has the correct format - PCM 16khz 16bit mono"

Why is there such strict audio format requirement? Can user go for another format?

I suggested vosk api to be implemented in a qualitative analysis software(https://github.com/ccbogel/QualCoder/issues/284) however the developed noticed such limitation, and because the idea was to make something easy for the user with a click without needing to use terminal or to change format the idea was dropped.

Is that requirement still valid or now vosk can use whatever audio one has?

**Comment by nshmyrev** [comment]
As a library vosk doesn't convert formats to reduce dependencies and software complexity. 

If your project requires different formats you can simply integrate with existing library like ffmpeg, libav, gstreamer to convert data before processing like demonstrated here here:

https://github.com/alphacep/vosk-api/blob/master/python/example/test_ffmpeg.py

**Comment by WPFilmmaker** [comment]
thank you for your prompt reply, I will let the dev know it :)

**Comment by nshmyrev** [comment]
Seems to be solved. Let us know
