### ISSUE TITLE
Trouble with installation vosk

### ISSUE THREAD

**Issue by EgoVed** [alphacep/vosk-api#294]
Hi! I try to install vosk on my Mac but I can't. I'm working in Anaconda in jypiter
I check in terminal my pip and python's version: 
python3 --version Python 3.8.2
pip3 --version
pip 20.2.4 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)

And installation with pip3 -v install vosk Done

When I import vosk with:
from vosk import Model, KaldiRecognizer

there is error 
ModuleNotFoundError: No module named 'vosk' 

If I check in terminal all installation with **pip list** i can see **vosk   0.3.7**. 

Can you help me what I do wrong?

**Comment by EgoVed** [comment]
I see that my jypiter works with '/opt/anaconda3/bin/python'. 
I'm new to python, so I immediately apologize if my questions seem stupid

**Comment by nshmyrev** [comment]
You need to run pip install inside anaconda too then. Not sure if that would work.

**Comment by EgoVed** [comment]
I did already. write:
ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk
Note: you may need to restart the kernel to use updated packages.

**Comment by EgoVed** [comment]
And I see, if I write pip list in jypiter, there is no vosk in list

**Comment by nshmyrev** [comment]
Maybe python version in Jypiter is different, you need to make sure you have python 3.8.

**Comment by nshmyrev** [comment]
Please let me know if you need further help.

**Comment by ElianAbrao** [comment]
I have a question, for the vosk library to work do I need to be using Python 3.8?
because I have Python 3.9.5 installed on my machine, in this version does vosk work? or do i need to change the python version on my computer?

**Comment by ElianAbrao** [comment]
I'm having the same error that @Author EgoVed had

**Comment by ElianAbrao** [comment]
if my writing is "weird" ignore it, I don't speak English, I'm translating the conversation by Google translator
