### ISSUE TITLE
speaker_recognition_problem

### ISSUE THREAD

**Issue by jessica-byte** [alphacep/vosk-api#295]
hello  first thank you for your great effort  in delivering such  a high quality ASR ,
[speaker.zip](https://github.com/alphacep/vosk-api/files/5535719/speaker.zip)
i tried speaker_recognition  with ur software to identify  speaker  using microphone stream by pyaudio  and then extract the x-vector and it worked fine for  me and i made  a simple  program  to  remove the noise as possible by  getting  the x-vector from  each stream  and getting their mean like in calibration.py  the problem  is after calculating the cosine distance  if  the speaker is correct  sometimes it gives a distance  of <.1
and some times between .1 and .2  and if the speaker isn't correct it gives me  a distance  between .1 and .3  (and i haven't seen any values larger in my implementation ) so sometimes it detect a wrong person  voice as the correct speaker 
so do u have any ideas how can i improve this ?

**Comment by nshmyrev** [comment]
Are you trying this on Windows? What is vosk version? 0.3.7?

**Comment by jessica-byte** [comment]
yes i'm trying on windows and my vosk version is 0.3.7

**Comment by nshmyrev** [comment]
Wait a bit till I update Windows binaries to recent version with xvector fixes.

**Comment by jessica-byte** [comment]
thank you  for your effort

**Comment by jessica-byte** [comment]
excuse me  when 'd you approximately  update  the package with bug fixes  
i'm working  on a project and  i should  get it finished  by the end  of this month  so could i wait  or  switch to linux for now ?

**Comment by nshmyrev** [comment]
Give me couple of days, we'll set everything up

**Comment by jessica-byte** [comment]
any updates ?

**Comment by nshmyrev** [comment]
A bit busy with things sorry, hopefully this week.

**Comment by jessica-byte** [comment]
it's oky take your time and do your stuff and i appreciate your collaboration ,
whenever you finish the update  just inform me

**Comment by nshmyrev** [comment]
Hello, new version 0.3.18 for Windows is released on pypi:

https://pypi.org/project/vosk/0.3.18/

please update, it should be better. Reopen if you see any issues.
