### ISSUE TITLE
Is there a bigger english model containing the names of the cities and the must frequent names/surnames?

### ISSUE THREAD

**Issue by Vricken** [alphacep/vosk-api#297]
Is there a bigger english model containing the names of the cities and the must frequent names/surnames? If not is there a step by step tutorial on how to do this, i tried looking at other threads on how to add custom words but they are too complicated.

**Comment by Vricken** [comment]
i closed 296 because i created it for mistake, also i had a 3.2Gb English model but on here `https://alphacephei.com/vosk/models` it does not seem to exist anymore. Is the 1.4Gb version a more accurate and optimized version? In a video i also saw a version that occupied more than 10Gb has that been removed, did it contain more words if yes where can I find it?

**Comment by nshmyrev** [comment]
Our best open source model is available for download as listed. We do not have better model yet unfortunately.

Adaptation process is mentioned on website too, it is not very straightforward but many people went through it already and it works.

**Comment by nshmyrev** [comment]
The process to add words described at https://alphacephei.com/vosk/lm now
