### ISSUE TITLE
Adapting Big Models - Missing Files

### ISSUE THREAD

**Issue by kjwill555** [alphacep/vosk-api#299]
Hello,

I have followed the instructions [here](https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/) to adapt the version of the English Aspire model that you can download from the Kaldi website.

I would like to adapt the Vosk version of the English Aspire model (and other large Vosk models such as Indian English and German), but even though the Vosk model adaptation webpage says to follow the same steps in the link above, there seem to be several files missing from the Vosk models.

I've listed out my questions below, I'm sorry that there's so many but if you can guide me towards figuring this process out for all the large Vosk models, I'd be happy to write up detailed instructions for the website/github:

- Lexicon:
  - What do I use for the lexicon? In the link, they use `<model_root>/data/local/dict/lexicon4_extra.txt`
  - What do I use for the phones file? In the link, they use `<model_root>/exp/tdnn_7b_chain_online/phones.txt`. I see that the Vosk English Aspire model has this file in `<model_root>/graph`, but some models (e.g. Indian English) do not have this.
- Language model:
  - What do I use for the uncompiled language model? In the link, they use `<model_root>/data/local/lm/3gram-mincount/lm_unpruned`
- Dictionary:
  - In the link, the use some extra dictionary files like `extra_questions.txt`, `nonsilence_phones.txt`, etc. Do I use these for all models, even the non-English ones?
- Model:
  - In the link, they use `<model_root>/exp/tdnn_7b_chain_online` as the model directory. For the Vosk models, this is the `<model_root>/am` folder, right?
- Scripts:
  - In the link, they use a number of scripts that seem to be specific to the Aspire model (`cmd.sh`, `utils/mkgraph.sh`, etc.). Would I use these same scripts for all the large Vosk models (which I guess is another way of asking if all of the large Vosk models were created using the Aspire recipe)?

**Comment by nshmyrev** [comment]
We do not support adaptation of some models yet like the Indian English model. You have to ask us to adapt for you.

**Comment by kjwill555** [comment]
I see. What would that process involve, time- and cost-wise? And is your assistance required for all large models besides English Aspire?

**Comment by nshmyrev** [comment]
> I see. What would that process involve, time- and cost-wise? And is your assistance required for all large models besides English Aspire?

Some models have necessary data like French and German one I think. For others you have to contact us at contact@alphacephei.com or just drop me an email directly.

**Comment by kjwill555** [comment]
Ok, thank you. I will say, I honestly feel a bit misled by the Vosk website. The adaptation webpage, specifically the quote "You can rebuild the graph in the big models" and the fact that you link the blog post about adapting the Aspire model, leads the reader to believe that they themselves can apply this process to all of the large Vosk models. Instead, you should mention what you just told me (that most models require contacting your team). I made plans for a project with the assumption that I could adapt the large models myself using a script that applies the Aspire process to all the models, but this new information is a huge speedbump.

**Comment by nshmyrev** [comment]
I agree with you our documentation is not complete, I'll try to fix it soon.
