### ISSUE TITLE
RE: Illegal instruction

### ISSUE THREAD

**Issue by silver2row** [alphacep/vosk-api#300]
Hello,

I found this source via pocketsphinx. I see you fellows have been busy again making some neat source to use for specific Linux systems and other systems.

Anyway, I have an error that seems a bit odd to me as of now:

    Illegal instruction

That is the error so far. I installed backports for stretch since I use Buster as my OS on armhf. I have a Linux SBC (BBB). 

Seth

P.S. If you are familiar with this error, please do reply. I think I am on to making it work w/ a 32-bit armhf Linux SBC but I may be way off. I understand that 32-bit python does not work. Is there any way around this idea?

**Comment by nshmyrev** [comment]
You have to cross-compile yourself with appropriate toolchain probably.

**Comment by silver2row** [comment]
Hello...okay. I will try that out. Thank you for replying.
