### ISSUE TITLE
Unable to transcribe single words

### ISSUE THREAD

**Issue by rishabh-sachdev** [alphacep/vosk-api#301]
I am trying to transcribe audio files which have single word in standard american Engilsh. The output seems to be break down the word into multiple words. Is there a way to tune the model such that it recognizes single words?

Example - The word is 'Idiosyncratic' and the final output I am getting is 'It isn't critic'

**Comment by nshmyrev** [comment]
You probably have to add the words to the dictionary as in https://alphacephei.com/vosk/adaptation

**Comment by nshmyrev** [comment]
In general, our accuracy on single word task is not perfect, we are working on it, hope to improve in a next major update.

**Comment by nshmyrev** [comment]
Let me know if you need further help.
