### ISSUE TITLE
Provide a option to not automatic rebuild respository

### ISSUE THREAD

**Issue by skrabadiloseidon** [alphacep/vosk-api#303]
Please provide a option to not automatic rebuild respository.
I am using vosk on a raspberry pi (with wordlist), often vosk didnt't recognize the words and tries to rebuild the repository which takes a long time (in this time the app is responding to nothing) an provides no meaningful result or improvement.

If there is a option to not do this and instead return and give no result (like  vosk sometimes does). then i can give feedback (beep sound) and can try again without waiting 30 seconds+.

( I am using the python 3 bindings)

**Comment by nshmyrev** [comment]
> tries to rebuild the repository

What is that? Kaldi warning messages about lattice too large? Can you provide the exact message?

**Comment by skrabadiloseidon** [comment]
Sure, here the message:

LOG (VoskAPI:RebuildRepository():determinize-lattice-pruned.cc:287) Rebuilding repository.
WARNING (VoskAPI:CheckMemoryUsage():determinize-lattice-pruned.cc:320) Did not reach requested beam in determinize-lattice: size exceeds maximum 50000000 bytes; (repo,arcs,elems) = (26419392,947780,22634992), after rebuilding, repo size was 18016320, effective beam was 4.93352 vs. requested beam 6

**Comment by nshmyrev** [comment]
Which version are you using please? With recent phrase list change it should be slightly better

**Comment by skrabadiloseidon** [comment]
I'm using version 0.3.10.
Is there a possibility to disable this complete?

**Comment by nshmyrev** [comment]
Please update to 0.3.15, with new implementation it should be much better

**Comment by skrabadiloseidon** [comment]
thanks, i will try. do i need to update the model when updating vosk?

**Comment by nshmyrev** [comment]
> do i need to update the model when updating vosk?

No, but note that the way to specify phrases changed, see the updated example

**Comment by skrabadiloseidon** [comment]
With 0.3.15 its fine, thanks.

**Comment by nshmyrev** [comment]
Same as #159
