### ISSUE TITLE
Unable to obtain desired text output of wav file 

### ISSUE THREAD

**Issue by Ashutosh1995** [alphacep/vosk-api#307]
I am trying to run vosk-api/python/test_text.py in order to get the speech output from the wav file. 

I also provide the phrase list as following:

rec = KaldiRecognizer(model, 16000, '["Play music", "Play previous song", "Play next song", "[unk]"]')

The following command was run to install python-api

python3 setup.py install --user --single-version-externally-managed --root=/

When I pass the corresponding audio I get the following output 

LOG (VoskAPI:ReadDataFiles():vosk/model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0323901 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:221) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:251) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:265) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:273) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:68) ["Unlock the trunk", "Open the trunk", "Navigate to work", "Navigate to office", "Navigate to work", "Play music", "Play previous song", "Play next song", "Pick up the call", "Accept call", "[unk]"]
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Unlock'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Open'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Navigate'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Navigate'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Navigate'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Play'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Play'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Play'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Pick'
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'Accept'
LOG (VoskAPI:Estimate():vosk/language_model.cc:142) Estimating language model with ngram-order=2, discount=0.5
LOG (VoskAPI:OutputToFst():vosk/language_model.cc:209) Created language model with 13 states and 31 arcs.
{'text':  'Yeah'}

I have provided the Indian English models and as well as Daanzu's model

Could you please help me out in this

PS: Did not find similar issue in the closed section

**Comment by nshmyrev** [comment]
Words have to be lowercase

**Comment by Ashutosh1995** [comment]
changed to lowercase as well but still the same

**Comment by nshmyrev** [comment]
It can not be the same, output should be different.

**Comment by Ashutosh1995** [comment]
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0170498 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:221) Loading i-vector extractor from model3/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:246) Loading HCLG from model3/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:265) Loading words from model3/graph/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:281) Loading CARPA model from model3/rescore/G.carpa
WARNING (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:103) Runtime graphs are not supported by this model
{'result': [{'conf': 0.476289, 'end': 1.83, 'start': 0.0, 'word': 'yeah'}], 'text': 'yeah'}
yeah


This is the output after using the bigger Indian Accent model 





LOG (VoskAPI:ReadDataFiles():vosk/model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0330901 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:221) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:251) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:265) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:273) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:68) ["unlock the trunk", "open the trunk", "navigate to work", "navigate to office", "navigate to work", "play music", "play previous song", "play next song", "pick up the call", "accept call", "[unk]"]
LOG (VoskAPI:Estimate():vosk/language_model.cc:142) Estimating language model with ngram-order=2, discount=0.5
LOG (VoskAPI:OutputToFst():vosk/language_model.cc:209) Created language model with 19 states and 51 arcs.
{'text': ''}

And this with Danzu's model

**Comment by nshmyrev** [comment]
Share your audio file

**Comment by Ashutosh1995** [comment]
[audio.zip](https://github.com/alphacep/vosk-api/files/5603706/audio.zip)

**Comment by nshmyrev** [comment]
The file has wrong format:

file 5fbbbdc04e3a6_16061393285fbbbdc050e13.wav 
5fbbbdc04e3a6_16061393285fbbbdc050e13.wav: MPEG ADTS, layer III, v1, 160 kbps, 48 kHz, JntStereo

**Comment by Ashutosh1995** [comment]
Yeah understood the problem. Thanks a lot!
