### ISSUE TITLE
What NN are written on? Pytorch, tf (I guess none of them)

### ISSUE THREAD

**Issue by dmazurok** [alphacep/vosk-api#308]
Hello!

Would you mind telling the neural nets, such as RNN LM and DNN AM are written on which framework? (maybe kaldi uses it's own implementation on plain C or something else?) 

Thank you a lot!!

**Comment by nshmyrev** [comment]
Kaldi uses its own C++ implementation

**Comment by dmazurok** [comment]
> Kaldi uses its own C++ implementation

Thank you!!
