### ISSUE TITLE
Set evaluation for speaker identification

### ISSUE THREAD

**Issue by jessica-byte** [alphacep/vosk-api#312]
hello i'm using danzuu model along with speaker model and i building ai assistant and i want it to recognize speakers .
i tried extracting the vector  and calculating the distance  so sometimes it gives me final distance betwwen .3 and .5  and i'v another x-vector and i was calculating  two-distances at the same time  and sometimes the first distance is .5 and the other one is .3  why is this happening ?
i also noticed that  when i say for example hello jack ? and get the x-vector  the final distance in any experiment if i say the same sentence is low but if i say any thing else it gets larger up to .5 
i also tried changing the mic and the values tend to change when i use another mic gets larger again 
so first i want to know what is big and what is small ? or should i know that by experimentation ?
second  i don't understand the whole process but  is the x-vector dependant only on the person voice  and not the words at all ?
third why does  changing the mic changes the result ?
sorry for my english and thank you for your help

**Comment by nshmyrev** [comment]
Hi Jessica!

Isn't it the same as https://github.com/alphacep/vosk-api/issues/295 ? Did you update to a newer version?

**Comment by jessica-byte** [comment]
yes now i'm using linux  ubuntu and i'm using the latest version

**Comment by nshmyrev** [comment]
> or should i know that by experimentation ?

Yes, in general it would be nice if you download a voxceleb test dataset and try to setup a test for EER detection using it.

**Comment by jessica-byte** [comment]
ok i will  update you with the results !
thank you

**Comment by jonwomack** [comment]
Hi @nshmyrev,

I'm getting unexpected similarities as well.

vosk: 0.3.15
macOS Catalina: 10.15.6

Models
model: https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.4.zip
speaker_model: https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip

**Comment by nshmyrev** [comment]
Lets track this in #405
