### ISSUE TITLE
The 1.4 GB Aspire model is no longer working.

### ISSUE THREAD

**Issue by MikeyBeez** [alphacep/vosk-api#316]
The 1.0 GB Daanzu model works fine.

**Comment by nshmyrev** [comment]
Sorry, what doesn't work exactly? Seems to work for me.

**Comment by MikeyBeez** [comment]
Here's what I get with the 1.4GB aspire model:  ./test_microphone.py
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00582886 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:235) Loading HCLG from model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:254) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:262) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:270) Loading CARPA model from model/rescore/G.carpa
ERROR (VoskAPI:ExpectToken():io-funcs.cc:209) Expected token "</LmStates>", got instead "
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
[1]    20226 abort (core dumped)  ./test_microphone.py

Everything works fine with the Daanzu model.  BTW, I'm running 0.3.10 now.  I thought I'd try an older version.  It didn't help with the aspire model.  I'll switch back to the latest vosk in a while.  I hope you are enjoying the holiday season.  Thanks for everything.  Cheers, M

**Comment by nshmyrev** [comment]
Hello. 

I have just verified everything works fine. Please download again, unpack and check md5sums:

```
vosk-model-en-us-aspire-0.2 $ find . -type f | xargs md5sum
eccbc87e4b5ce2fe28308fd9f2a7baf3  ./am/frame_subsampling_factor
9f97fcd7ac4a9c1063cba149cb6feacf  ./am/final.mdl
069b532428f83a1acc2505a7dc3be564  ./am/tree
457d01bb597758f4886360edfd345478  ./ivector/ivector.conf
864bc6a2080f7f642d7cd4b3ce1be6d1  ./ivector/mfcc.conf
e1bd7a6e2e81ac9c67e5f84de13b8d03  ./ivector/final.dubm
9f41f14e89d24b20570010ec5ad82f2e  ./ivector/final.ie
1a5e17dc05259c39e2865fe0d431dbad  ./ivector/final.mat
f613ff1ed9f7df0db164adf15caac381  ./ivector/splice.conf
98bef76bf7eb8267004524690de36647  ./ivector/global_cmvn.stats
505902d4fef41ea2f8f4964baec79084  ./ivector/online_cmvn.conf
593b792488021a0b9d1f88b954e535a9  ./README
95c7ca56078d460a673655c39fd2c9dc  ./conf/mfcc.conf
e7786edc028df3656674c62bb61e9623  ./conf/model.conf
8bf21fd04f479d08cdc48e709c4f70fb  ./graph/phones/word_boundary.int
5c9311dbb67315b651b9c8c8cca8162e  ./graph/HCLG.fst
c4eeb69f07e28b5b35eb2fe98f9c29cd  ./graph/phones.txt
d12f04616b43980671b5fe5607d6eaec  ./graph/words.txt
dcac10244b7f552df813801f8430af89  ./rescore/G.carpa
9b500a09d55924714e3eb89d5893c2f8  ./rescore/G.fst
```
Enjoy your holidays too!

**Comment by MikeyBeez** [comment]
That's what I get for keeping an old tar file to save downloading.  Some sums don't match:  067627b7616a2041e1e8e378266c5247  ./rescore/G.carpa
9b500a09d55924714e3eb89d5893c2f8  ./rescore/G.fst
e7786edc028df3656674c62bb61e9623  ./conf/model.conf
95c7ca56078d460a673655c39fd2c9dc  ./conf/mfcc.conf
c4eeb69f07e28b5b35eb2fe98f9c29cd  ./graph/phones.txt
5c9311dbb67315b651b9c8c8cca8162e  ./graph/HCLG.fst
d12f04616b43980671b5fe5607d6eaec  ./graph/words.txt
8bf21fd04f479d08cdc48e709c4f70fb  ./graph/phones/word_boundary.int
1a5e17dc05259c39e2865fe0d431dbad  ./ivector/final.mat
505902d4fef41ea2f8f4964baec79084  ./ivector/online_cmvn.conf
e1bd7a6e2e81ac9c67e5f84de13b8d03  ./ivector/final.dubm
9f41f14e89d24b20570010ec5ad82f2e  ./ivector/final.ie
98bef76bf7eb8267004524690de36647  ./ivector/global_cmvn.stats
457d01bb597758f4886360edfd345478  ./ivector/ivector.conf
f613ff1ed9f7df0db164adf15caac381  ./ivector/splice.conf
864bc6a2080f7f642d7cd4b3ce1be6d1  ./ivector/mfcc.conf
593b792488021a0b9d1f88b954e535a9  ./README
14a1558a1f4d58ace8f4f8b0ca4a5b1f  ./am/final.mdl
eccbc87e4b5ce2fe28308fd9f2a7baf3  ./am/frame_subsampling_factor
069b532428f83a1acc2505a7dc3be564  ./am/tree

**Comment by nshmyrev** [comment]
So it looks some of your files are corrupted somehow. Maybe you can download again please.

**Comment by MikeyBeez** [comment]
That worked.  Thank you.
