### ISSUE TITLE
Release 0.3.15 not supported by Windows

### ISSUE THREAD

**Issue by 5023wbb** [alphacep/vosk-api#317]
Thanks for this amazing work!

#146 solved in the latest release version 0.3.15, which is not supported on Windows. The latest version Windows can get is 0.3.7. How can I use the latest version 0.3.15 on Windows?

Thanks again.

**Comment by nshmyrev** [comment]
Yes, we are working on it, busy times. Please give us a week or two.

**Comment by YuhangPei** [comment]
> Yes, we are working on it, busy times. Please give us a week or two.

I am developing an application recently and there are some problems in windows. These problems did not appear in Ubuntu's vosk0.3.15. I hope you can develop a version 0.3.15 that supports windows as soon as possible. Thank you.

**Comment by nshmyrev** [comment]
Hello, new version 0.3.18 for Windows is released on pypi:

https://pypi.org/project/vosk/0.3.18/

please update, it should be better. Reopen if you see any issues.

**Comment by nshmyrev** [comment]
Hello, new version 0.3.18 for Windows is released on pypi:

https://pypi.org/project/vosk/0.3.18/

please update, it should be better. Reopen if you see any issues.
