### ISSUE TITLE
Android and Chinese

### ISSUE THREAD

**Issue by CVUsers** [alphacep/vosk-api#318]
Hello, how do we use vosk to do Chinese speech recognition and deploy it to android app? Is there any relevant tutorial

**Comment by nshmyrev** [comment]
Hello. Android demo is here:

https://github.com/alphacep/vosk-android-demo

to change the model to Chinese you just download the files and unpack them into models/src/assets over English files:

https://alphacephei.com/vosk/models/vosk-model-small-cn-0.3.zip

We will be retraining models soon for much better accuracy so please stay tuned.

**Comment by CVUsers** [comment]
thanks for your help～
I am Chinese computer vision algorithm engineer～
do you have wechat？

**Comment by nshmyrev** [comment]
@CVUsers yes, you can add me in wechat as nv_shmyrev

**Comment by nshmyrev** [comment]
I suppose this is fixed already.

**Comment by Gudauu** [comment]
Hi, I downloaded and unpacked and got an error
"Folder '/storage/emulated/0/Android/data/org.vosk.demo/files/model/model-cn' does not contain model files"
I also changed the soucePath in "initModel" to model-cn.

**Comment by Devin521314** [comment]
Hello,now I would like to use this model to translate chinese audio to digital numbers,just the digital numbers, 
for example audio file 三百四十点六 translate to 345.6.
Do you have the model files or tell me what I need to do,Thank U so much ?

**Comment by CVUsers** [comment]
add my wechat:zxx15277368495z，can tell u



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 12, 2022 16:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alphacep/vosk-api] Android and Chinese (#318)




 
Hello,now I would like to use this model to translate chinese audio to digital numbers,just the digital numbers,
 for example audio file 三百四十点六 translate to 345.6.
 Do you have the model files or tell me what I need to do,Thank U so much ?
