### ISSUE TITLE
The use of Hot words 

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#319]
I test a wav named "2ae1fec4-0fd6-4d31-87e6-edefc021ee22.wav" from open data "primewords"
The real transcription is ：零五四零四幺六二零零三甘肃天马八三二中国二幺幺二零零幺
I test without hotwords，result is as follows：
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6 LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10 LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes. LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components. LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2 LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0386579 seconds in looped compilation. LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done. LOG (VoskAPI:ReadDataFiles():vosk/model.cc:242) Loading HCL and G from model/HCLr.fst model/Gr.fst LOG (VoskAPI:ReadDataFiles():vosk/model.cc:264) Loading winfo model/word_boundary.int 零五 四 零 四 要 六 二零零三 甘肃 天马 八 三 二 中国 二 要 约 二零零 要

"幺" is wrongly transcribed as " 要"，so i want to correct it throught the hot words
add hot words：rec = KaldiRecognizer(model, 16000, '["幺"]')
but rec result is as follows：
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6 LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10 LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes. LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components. LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2 LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0356669 seconds in looped compilation. LOG (VoskAPI:ReadDataFiles():vosk/model.cc:219) Loading i-vector extractor from model/ivector/final.ie LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done. LOG (VoskAPI:ReadDataFiles():vosk/model.cc:242) Loading HCL and G from model/HCLr.fst model/Gr.fst LOG (VoskAPI:ReadDataFiles():vosk/model.cc:264) Loading winfo model/word_boundary.int LOG (VoskAPI:KaldiRecognizer():vosk/kaldi_recognizer.cc:68) ["幺"] LOG (VoskAPI:Estimate():vosk/language_model.cc:142) Estimating language model with ngram-order=2, discount=0.5 LOG (VoskAPI:OutputToFst():vosk/language_model.cc:209) Created language model with 2 states and 2 arcs. 幺 幺 幺 幺 幺 幺 幺 幺 幺 幺 幺 幺 幺 幺

**Comment by ThThoma** [comment]
Hello @v-yunbin ,

follow the example in [vosk-api/test_words.py](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py).

Two things for this feature:

1.   You have to add `[unk]` at the end, as in the example 
2.   It does not create `hotwords`. Every word is matched to the ones inside the JSON list. 
For example with a recognizer like:
```python
rec = KaldiRecognizer(model, wf.getframerate(), '["one two three", "[unk]"]')
``` 
Even if I say "hello world", the result will only contain a mix of the ` '["one two three", "[unk]"]'`

**Comment by zyb8543d** [comment]
@ThThoma thanks.
 it seems that the it is doing alignment with the audio and probable words list？
i don’t understand that the destnation of giving probable words list or how can it help recognition？

**Comment by ThThoma** [comment]
For the theory behind it, you should wait for @nshmyrev to answer or even better read the [source code](https://github.com/alphacep/vosk-api/blob/master/src/kaldi_recognizer.cc#L54).
I don't understand exactly what it is doing.

Now, how you use it, it is up to you. In the [adaptation page](https://alphacephei.com/vosk/adaptation) it is mentioned as
> Updating recognizer vocabulary in runtime

One thing for sure, it helps recognition **if** the words you are trying to recognize are inside the words list.

I suggest you play around with it ;) It is really fun.

**Comment by zzuzhp** [comment]
so it seems [unk] serves much like a mild char? it matches every word that is below a certain confidence?
i tested this feature with a grammar string like "王 永 [unk]",  but it seems this doesn't work. no [unk] is found in the returned json string when the speech contains other words than "王" and "永". 
the speech actually contains 3 words "王永亮",  and i am expecting a result of “王永[unk]", but instead the returned text is "王永王".  is there anything i am missing?

**Comment by ThThoma** [comment]
@zzuzhp you should read the [example](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py)
more carefully. One comma makes a difference. Try it again like this `'[ "王 永", "[unk]" ]'`.

**Comment by zzuzhp** [comment]
@ThThoma i'm using c++, and expecting a const char * parameter, i tried "[ \\"王 永\\", \\"[unk]\\" ]", but in vain.

**Comment by zzuzhp** [comment]
@ThThoma "王 永 \<UNK\>" works, but the result becomes:
"\<UNK\> \<UNK\>\<UNK\> \<UNK\> \<UNK\>\<UNK\> 王 永\<UNK\>王", the third character is still mistaken.
【i have a typo in my last post, the speech contians "王永亮“ not "王永远“。】

**Comment by ThThoma** [comment]
Hello @zzuzhp ,

I don't know mandarin (I am guessing it is mandarin...), but here are my guesses.  
Maybe the `亮` word is similar to  `王` in any way? 
Have you tried putting them in separate phrases? (e.g `'[ "王",  "永", "[unk]" ]'`)

Also, what are you trying to achieve? Why not include `亮` inside the JSON list?

---

This issue is getting really long now... If you want to continue, open a new issue, rephrase the question and provide 
your system details (OS, Vosk release, model you are using, audio file details and the example code you are using).

(if you do open a new issue, reference this one with `#319` so everything stays organized)

Lastly, do read older open issues and closed ones, many people have similar questions.
It is good practice to search, try and then ask.

**Comment by zzuzhp** [comment]
@ThThoma 
thank you and sorry for my verbose posts. 
i will search before ask and try to make no duplicate questions.

**Comment by zyb8543d** [comment]
> For the theory behind it, you should wait for @nshmyrev to answer or even better read the [source code](https://github.com/alphacep/vosk-api/blob/master/src/kaldi_recognizer.cc#L54).
> I don't understand exactly what it is doing.
> 
> Now, how you use it, it is up to you. In the [adaptation page](https://alphacephei.com/vosk/adaptation) it is mentioned as
> 
> > Updating recognizer vocabulary in runtime
> 
> One thing for sure, it helps recognition **if** the words you are trying to recognize are inside the words list.
> 
> I suggest you play around with it ;) It is really fun.

Thank for your patient reply. 
Maybe still need @nshmyrev' answer

**Comment by nshmyrev** [comment]
@v-yunbin yes, this is how it works. It enforces only the words from the grammar with probable [unk] for everything else. Accuracy/false alarm rate is not yet guaranteed, it is more for dialogs than for keyword spotting.

It is pretty trivial to combine the grammar with the big language model, you just do fstunion, but we are not there yet, still deciding on the API.

So for now it is not really 'hot word'.

**Comment by zyb8543d** [comment]
@nshmyrev thanks, i see it now

**Comment by v-yunbin** [comment]
@nshmyrev The  grammar fst seems not very useful in practical application.
the shallow fusion of grammar fst score and Acoustic score may be useful. This  is hotword and it can increase words recognition probability in grammar fst. (https://github.com/wenet-e2e/wenet/blob/main/docs/context.md)
