### ISSUE TITLE
Model conversion for lookahead?

### ISSUE THREAD

**Issue by dpny518** [alphacep/vosk-api#32]
Do we need to convert models trained for example using aspire, librispeech recipes to allow them to work with passing word list to lookahead
```
https://github.com/alphacep/vosk-api/blob/master/python/example/test_local_words.py
```

I have several tdnn models that I want to use with these api.

**Comment by nshmyrev** [comment]
You don't have to convert, you can use default model with hclg graph, you just need to arrange files properly.

**Comment by nshmyrev** [comment]
For words example you need to build lookahead graphs.

**Comment by dpny518** [comment]
Thank you, I am trying to create the HCLr.fst and Gr.fst similiar to the android model with my own model, i used the following command from the kaldi master branch
```
utils/mkgraph_lookahead.sh --self-loop-scale 1.0 --remove-oov --compose-graph model/data/lang model graph
```
and got the following error
```
ERROR: GenericRegister::GetEntry: olabel_lookahead-fst.so: cannot open shared object file: No such file or directory
FATAL: Fst::Convert: Unknown FST type olabel_lookahead (arc type standard)
```
Am I using the wrong repo?

**Comment by dpny518** [comment]
needed to do this
```
export LD_LIBRARY_PATH=${KALDI_ROOT}/tools/openfst/lib/fst
```
