### ISSUE TITLE
About lookahead models

### ISSUE THREAD

**Issue by zzuzhp** [alphacep/vosk-api#320]
hi, i have a problem about the method 'vosk_recognizer_new_grm', when i pass a grammar, it reports 
ERROR (VoskAPI:KaldiRecognizer():kaldi/kaldi_recognizer.cpp:85) Can't create decoding graph.
i'm building vosk from sources on ubuntu and i built kaldi from the master branch, is this the problem ? should i build kaldi from another branch ?

**Comment by ThThoma** [comment]
Hello @zzuzhp ,

you should provide the name of the model you are working with. 
`vosk_recognizer_new_grm` feature does not work on all models. 

Maybe #217 will help you.

**Comment by zzuzhp** [comment]
yes, i'm using the wrong model file.
now i changed to another one, and the problem gone.
thank you!
