### ISSUE TITLE
Expanding Farsi Vocabulary

### ISSUE THREAD

**Issue by kossarNJ** [alphacep/vosk-api#321]
Hello,
I was wondering if it is possible to add new words to the vocabulary of the Farsi model. I read the documentation on [Updating words and the vocabulary in the big models](https://alphacephei.com/vosk/adaptation) but wasn't sure whether it could be applied to all models (since it states at one point that the graph can only be rebuilt for certain models.) and more specifically if I could rebuild it for the Farsi model. If possible, I would appreciate it if you could give me some pointers on how to proceed.
Thanks!

**Comment by nshmyrev** [comment]
What is the project you are doing? Do you have the list of new words already?

**Comment by kossarNJ** [comment]
I wish to use the speech recognition tool as a part of an app that recognizes voiced commands and performs some actions accordingly. Some specific words may be used and I wondered if I could add them to the model.
I do have a list of words that I predict will be used more often.

**Comment by nshmyrev** [comment]
What words are you missing exactly please?

**Comment by kossarNJ** [comment]
Some names/surnames, informal forms of some words (which may vary a bit from their formal form), some made-up words that represent concepts within the app. Not that many words. Most are already included in the model. Maybe around a couple thousand words.

**Comment by nshmyrev** [comment]
Ok, for now you can send me the list to get a custom graph. We are planning to release graph update things, but not very soon.

**Comment by pourfard** [comment]
> Hello,
> I was wondering if it is possible to add new words to the vocabulary of the Farsi model. I read the documentation on [Updating words and the vocabulary in the big models](https://alphacephei.com/vosk/adaptation) but wasn't sure whether it could be applied to all models (since it states at one point that the graph can only be rebuilt for certain models.) and more specifically if I could rebuild it for the Farsi model. If possible, I would appreciate it if you could give me some pointers on how to proceed.
> Thanks!

I've tried the instruction you have mentioned and there was no problem. You can expand or shrink the vocabulary for better understanding.

**Comment by doctorwho-123** [comment]
> سلام ،
> من فکر می کردم که آیا امکان افزودن کلمات جدید به واژگان مدل فارسی وجود دارد؟ من اسناد مربوط [به](https://alphacephei.com/vosk/adaptation) به [روزرسانی کلمات و واژگان را در مدل های بزرگ مطالعه کردم](https://alphacephei.com/vosk/adaptation) اما مطمئن نبودم که آیا می توان آن را برای همه مدل ها اعمال کرد (از آنجا که در یک نقطه بیان می شود نمودار فقط برای مدل های خاص قابل بازسازی است.) می توانم آن را برای مدل فارسی دوباره بسازم. اگر امکان دارد ، اگر می توانید برخی از راهنماهای نحوه کار را به من بدهید ، از آن استقبال می کنم.
> با تشکر!

@kossarNJ  

سلام بببخشیید میتونید کمکم کنید چطوری میتونم از vosk  برای واژگان فارس استفاده کنم متاسفانه من هر کاری میکنم نمیتونم vosk  رو نصب کنم

**Comment by saeedsamie** [comment]
> > سلام ،
> > من فکر می کردم که آیا امکان افزودن کلمات جدید به واژگان مدل فارسی وجود دارد؟ من اسناد مربوط [به](https://alphacephei.com/vosk/adaptation) به [روزرسانی کلمات و واژگان را در مدل های بزرگ مطالعه کردم](https://alphacephei.com/vosk/adaptation) اما مطمئن نبودم که آیا می توان آن را برای همه مدل ها اعمال کرد (از آنجا که در یک نقطه بیان می شود نمودار فقط برای مدل های خاص قابل بازسازی است.) می توانم آن را برای مدل فارسی دوباره بسازم. اگر امکان دارد ، اگر می توانید برخی از راهنماهای نحوه کار را به من بدهید ، از آن استقبال می کنم.
> > با تشکر!
> 
> @kossarNJ
> 
> سلام بببخشیید میتونید کمکم کنید چطوری میتونم از vosk برای واژگان فارس استفاده کنم متاسفانه من هر کاری میکنم نمیتونم vosk رو نصب کنم
@doctorwho-123 
There is a video here : https://alphacephei.com/vosk/install

**Comment by doctorwho-123** [comment]
@saeedsamie
سلام من میخواهم  همین وسک   رو در محیط ویزال استدیو سی شارپ در محیط سیستم عامل ویندوز نصب کنم ولی متاسفانه نمی تونم لطفا کمکم کنید

**Comment by nshmyrev** [comment]
Same as #382, lets track there

**Comment by sara-najmi** [comment]
hi dear @nshmyrev I appreciate your hard work and thanks for making this useful model available free.
I need to use this offline speech recognition with a list of new words as well as @kossarNJ in Farsi model for made up words and unique words only used by our users, I would appreciate it if you could guide me too.

**Comment by buelomen** [comment]
سلام من مذل فارسی رو از کجا میتونم دانلود کنم ؟

**Comment by nshmyrev** [comment]
> سلام من مذل فارسی رو از کجا میتونم دانلود کنم ؟

https://alphacephei.com/vosk/models/vosk-model-fa-0.42.zip

**Comment by pixlesage17-jpg** [comment]
سلام میخوام vosk رو دانلود کنم نمیشه از خود گیت هاب هم نشد از کجا دانلود کنم
