### ISSUE TITLE
fr-pguyot-zamia-20191016-tdnn_f french model does'nt work

### ISSUE THREAD

**Issue by metal3d** [alphacep/vosk-api#322]
I tried to use the given model in the documentation but, even by moving files to the right place, there is some files that are not found.

The `pguyot` repository hasn't moved for years and there is no issue tab.

What I needed to do after untar and move to "model" directory, if it can help:

```bash
ln -sr model/conf/mfcc.conf model/
ln -sr model/model/final.mdl model/
ln -sr model/model/graph/words.txt model/

# but this one is probably not ok:
ln -sr model/model/graph/HCLG.fst model/HCLr.fst
```

Actually, the model wants to load:
```
Loading HCL and G from model/HCLr.fst model/Gr.fst
```

But, I made link from `HCLG` file - is this ok ?

@pguyot maybe you can help ?

PS: On Raspberry, process is stopped, I will later check on my computer.

**Comment by nshmyrev** [comment]
We have that model already repackaged, simply download it:

https://alphacephei.com/vosk/models/vosk-model-small-fr-pguyot-0.3.zip

**Comment by nshmyrev** [comment]
As for big model, we recommend you to try more accurate linto model, you can find the list here:

https://alphacephei.com/vosk/models

more information on french models here:

https://alphacephei.com/nsh/2020/10/21/french.html

**Comment by nshmyrev** [comment]
And you can also check:

https://github.com/alphacep/vosk-server/blob/f616010fb5f29cd8545f113e2099fa0f1bc11e25/docker/Dockerfile.kaldi-fr

In general, it is the same as #232

**Comment by metal3d** [comment]
Hi @nshmyrev and thanks for your reply.

Both packages vosk-model-small-fr-pguyot-0.3 and fr-pguyot-zamia-20191016-tdnn_f] seems to not be exactly the same, one is 39Mo and the other 289Mo.

If the second one is in documentation, you should probably remove it as it is not compatible (or broken)

**Comment by metal3d** [comment]
I'm looking at the Dockerfile :-) didn't seen that it's not the one I checked earlier, sorry.

**Comment by metal3d** [comment]
OK... the first package is actually the second one repackaged... that was not clear.

**Comment by nshmyrev** [comment]
They are different. Pguyot has two models - small tdnn_f_250 and big one tdnn_f. Small model is f_250 repackaged. Big one is superseeded by linto model.
