### ISSUE TITLE
Errors for making Gr.fst

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#323]
make Gr.fst with follows commands:

```
fstsymbols --save_osymbols=words.txt Gr.fst > /dev/null
farcompilestrings --fst_type=compact --symbols=words.txt --keep_symbols text.txt | \
 ngramcount | ngrammake | \
 fstconvert --fst_type=ngram > Gr.new.fst
```
errors is as follows

```
fstsymbols --save_osymbols=words.txt Gr.fst > /dev/null
ERROR: fstsymbols: Saving osymbols but there are no output symbols.
 farcompilestrings --fst_type=compact --symbols=words.txt --keep_symbols text.txt | \
>  ngramcount | ngrammake | \
>  fstconvert --fst_type=ngram > Gr.new.fst
FATAL: FarCompileStrings: Compiling string number 2321 in file text.txt failed with token_type = symbol and entry_type = line
FATAL: STListReader: Error reading file: stdin
ERROR: FstHeader::Read: Bad FST header: standard input
ERROR: FstHeader::Read: Bad FST header: standard input
```

**Comment by LukasS91** [comment]
How did you solve your problem?
I try to update the language model with a preprocessed text, but receive the same error for the first command. I guess words.txt refers to the existing word symbol table from the model of which I want to update the language model, right?

**Comment by jlalfonso21** [comment]
> I try to update the language model with a preprocessed text, but receive the same error for the first command. I guess words.txt refers to the existing word symbol table from the model of which I want to update the language model, right?

`words.txt` is the output of the symbols table as the help of the command says, it's not required to be created before running the command

```
--save_osymbols: type = string, default = ""
  Save fst file's output symbol table to file
```

**Comment by makdatascientist** [comment]
how did you solve the problem , please reply
