### ISSUE TITLE
Vosk install issue on Debian and Windows 10

### ISSUE THREAD

**Issue by Vagrantin** [alphacep/vosk-api#324]
First of all thanks a lot for the great work this is super cool !
I’m having difficulty to install the python module of vosk either Windows 10 or Debian Stretch:

### Windows 10
![image](https://user-images.githubusercontent.com/19902259/102596426-7d4e1d00-415c-11eb-91f1-996ccca42bbe.png)

### Debian Stretch
![image](https://user-images.githubusercontent.com/19902259/102596528-9eaf0900-415c-11eb-803d-f959c2743d3a.png)

Is this a python version issue ? I don’t know what I’m doing wrong here.
With kind regards
Matthieu

**Comment by nshmyrev** [comment]
On windows we support only python 3.8, you have 3.9

On linux you need to update pip3, we need version 19+

For more information see installation documentation:

https://alphacephei.com/vosk/install#python-installation-from-pypi

**Comment by nshmyrev** [comment]
Feel free to reopen if needed
