### ISSUE TITLE
Error when use C# nuget package

### ISSUE THREAD

**Issue by broteam168** [alphacep/vosk-api#325]
I have download your nuget package(https://www.nuget.org/packages/Vosk/) and add it to my project but when running i have received this error:
'The type initializer for 'Kaldi.VoskPINVOKE' threw an exception.'
when i run this line code:
Model model = new Model("C:\\Users\\Admin\\Desktop\\vosk-model-small-vn-0.3");
![image](https://user-images.githubusercontent.com/67248197/102713624-7b7c7a80-427e-11eb-872b-d845e14987b3.png)

**Comment by nshmyrev** [comment]
Our nuget supports just linux unfortunately, we might add support for windows later.

**Comment by broteam168** [comment]
Thank for answer and i think you should update it soon.I will use this in my robot project.

I have met a new error when use Makefile in Cs folder.
No rule for /src/vosk.i  (something like this )

**Comment by nshmyrev** [comment]
> No rule for /src/vosk.i (something like this )

Source folder variable is empty in makefile, thats why you have /. You need to substitute path properly I think. You also need swig and kaldi build.

**Comment by broteam168** [comment]
:Thank you for all your answers. 

Your nuget package is from Makefile in CS folder, isn't it?

**Comment by nshmyrev** [comment]
> Your nuget package is from Makefile in CS folder, isn't it?

Makefile creates a dll, then you can just use "nuget pack". You can create a similar dll on windows with mingw.

We will do it a bit later, just need some more time.

**Comment by PatrykSajdok** [comment]
Any update on Windows version?

**Comment by broteam168** [comment]
TT any update on Window????
 it is very neccessary to me!!!!!!!!

**Comment by nshmyrev** [comment]
Hey guys, a bit more patience please, it will be ready soon.

**Comment by problemSolvingProgramming** [comment]
@broteam168  
Hi
Excuse me, I did the same thing, but my error did not go away. What should I do to get rid of my error?

**Comment by broteam168** [comment]
@doctorwho-123  you can give more information about your situation?

**Comment by problemSolvingProgramming** [comment]
@broteam168  I want to run this vosk api to convert speech to text for English in Visual Studio C# environment or how can I compile this vosk api ? 
https://github.com/alphacep/vosk-api/blob/master/csharp/test.cs
My goal is to come and say something through the microphone and convert that code into text using vosk.

**Comment by broteam168** [comment]
you can install C# nuget package from Visual studio using command line or GUI. Then you copy that code to your project(notice this nuget package only run on linux) . Run and feel your result @doctorwho-123

**Comment by problemSolvingProgramming** [comment]
tahnks @broteam168 Do I want to run or compile vosk api use visual staduio c# in  Windows? What should I do? I am a beginner in this field? Help me please ?

**Comment by alvaromongon** [comment]
In case this help you, what I did, although it is hacky, might help you meanwhile they get a nudget package working on windows.

I installed vosk with python and from my c# vs2019 solution captured a converted the voice into a wav file and executed a python script getting the result back into my c# program.

I can try to publish and example in GitHub if you are interested.

**Comment by problemSolvingProgramming** [comment]
@alvaromongon Hello, please explain this step by step using C # code and ... with example and image for visual studio c#  in windows  .

**Comment by alvaromongon** [comment]
I will try to set up an example in a GitHub repo during this weekend so you can analyze the code.

**Comment by alvaromongon** [comment]
Here you have it @doctorwho-123 

https://github.com/alvaromongon/windows-csharp-vosk-api

Read the readme first, there are some dependencies.

**Comment by problemSolvingProgramming** [comment]
@alvaromongon Thank you very much. How can I replace the Spanish model with an English model?

**Comment by alvaromongon** [comment]
I have updated the information in the readme.md file about how the Vosk is used and where should it be located.

Please take a look and investigate.

**Comment by broteam168** [comment]
@nshmyrev Can you give me a time for this update? I want to have a plan with this!!

**Comment by problemSolvingProgramming** [comment]
@broteam168 hi . How can I use C # to receive audio through a microphone and convert it to text via vosk api?

**Comment by broteam168** [comment]
You can find it in stackoverflow ỏ you can go to source code of python and convert it to c#

**Comment by problemSolvingProgramming** [comment]
@broteam168   Thanks, but how do I use vosk? I made this error like you?

  I have download your nuget package(https://www.nuget.org/packages/Vosk/) and add it to my project but when running i have received this error:
'The type initializer for 'Kaldi.VoskPINVOKE' threw an exception.'
when i run this line code:
Model model = new Model("C:\Users\Admin\Desktop\vosk-model-small-vn-0.3");


![a6f03e35-3408-4fa0-9063-e68e117ab8fc](https://user-images.githubusercontent.com/20268490/105575826-bbee7d00-5d83-11eb-9fcc-65949d83148b.jpg)

**Comment by broteam168** [comment]
:)) this nuget package can't use in Windows @doctorwho-123

**Comment by nshmyrev** [comment]
New package 0.3.17 that supports Win32 and Win64 uploaded to nuget:

https://www.nuget.org/packages/Vosk/0.3.17

Please test and let us know how it goes.

**Comment by broteam168** [comment]
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'libvosk' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

I still have met this error :(((

![image](https://user-images.githubusercontent.com/67248197/106990371-b2fba380-67a6-11eb-8a8d-c26697aaa96d.png)

**Comment by nshmyrev** [comment]
> I still have met this error :(((

Dlls are inside nuget package, where did it put them after unpack? Could you find them?

**Comment by kikkoi** [comment]
> Unable to load DLL 'libvosk' or one of its dependencies

Initially i got too the error and again check over it
> Dlls are inside nuget package

Yes, had already libvosk filed inside win-x64 folder. Program works well when moving the file them to another directory \bin\Debug\net5.0 👍

**Comment by nshmyrev** [comment]
For the future reference a good source on how to load dlls in nugets:

https://dev.to/jeikabu/loading-native-libraries-in-c-fh6

essentially watch https://github.com/zplus/NNanomsg

**Comment by nshmyrev** [comment]
I have uploaded https://www.nuget.org/packages/Vosk/0.3.18, it should now unpack dlls properly, please check

**Comment by broteam168** [comment]
It have another isues: not found Kaldi library in this package

**Comment by nshmyrev** [comment]
> It have another isues: not found Kaldi library in this package

It was renamed to Vosk, see updated sample hre:

https://github.com/alphacep/vosk-api/blob/master/csharp/demo/VoskDemo.cs

**Comment by broteam168** [comment]
Thanks it is quite good but sorry i have little more error
![image](https://user-images.githubusercontent.com/67248197/107143899-2994ce80-696a-11eb-9d2d-ab9ab85f5a25.png)

**Comment by nshmyrev** [comment]
> Thanks it is quite good but sorry i have little more error

It can not file model folder, you need to place model into appropriate location. Same with test.wav file.

**Comment by broteam168** [comment]
Where i should place it ?

**Comment by nshmyrev** [comment]
You an use absolute path in the code in model constructor if you are not certain.

**Comment by TarkusT** [comment]
Does it work with .NET framework or just .NET Core?

I have installed it for .NET Framework but I got this error when calling any of the methods:

VoskRecognizer.Result()
VoskRecognizer.PartialResult()
VoskRecognizer.FinalResult()

it throws this exception:

Method not found: 'System.String System.Runtime.InteropServices.Marshal.PtrToStringUTF8(IntPtr)'.

I looked it up and found that the method 'System.Runtime.InteropServices.Marshal.PtrToStringUTF8(IntPtr)' exists only in .NET Core 5.0

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostringutf8?view=net-5.0

**Comment by nshmyrev** [comment]
> Does it work with .NET framework or just .NET Core?

Sorry, no idea, you are C# developer, not I. .net 5.0 was release 4 years ago, I suppose it is old enough.

**Comment by TarkusT** [comment]
it's .net core 5.0 not .net framework 5.0.

Anyway thanks for the answer it was very helpful.

**Comment by nshmyrev** [comment]
People report it is working, so closing this. Please reopen if needed.

**Comment by vonguyen1982** [comment]
It is working fine with docker windows container but once I run it with linux container then I hit an issue below

System.DllNotFoundException: 'Unable to load shared library 'libvosk' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibvosk: cannot open shared object file: No such file or directory'

**Comment by vonguyen1982** [comment]
![image](https://user-images.githubusercontent.com/68211937/107468485-209b3b80-6bbc-11eb-97bb-7c5a64052e17.png)

**Comment by vonguyen1982** [comment]
I got issue with running in linux container. Could you please check if the nuget packet could use for linux 
![image](https://user-images.githubusercontent.com/68211937/107501657-cf0aa500-6beb-11eb-98dd-fe15a4820a71.png)
Thanks

**Comment by nshmyrev** [comment]
> I got issue with running in linux container

Try to run

ldd libvosk.so

maybe you miss libatomic

**Comment by vonguyen1982** [comment]
It look like missing libraries. I added latest nuget package from Visual studio, I thought it should include all dynamic library. Where do I find the missing library? Thanks
![image](https://user-images.githubusercontent.com/68211937/107567146-9f828980-6c39-11eb-9b1e-ac56a61516de.png)

**Comment by nshmyrev** [comment]
@vonguyen1982 I have uploaded https://www.nuget.org/packages/Vosk/0.3.19

It must be compatible with older Linux versions. Try, it should work for you.

**Comment by vonguyen1982** [comment]
Sorry I still got error as below. It looks like missing libatomic.so
![image](https://user-images.githubusercontent.com/68211937/107585019-92719480-6c51-11eb-8dc3-4da1ee5bf85c.png)

**Comment by vonguyen1982** [comment]
I have fixed by 
- apt update
- apt install libatomic1
but it should be dependency of nuget package so we don't need extra step in docker file :)
Thanks

**Comment by broteam168** [comment]
I think you should create a new topic Author have fixed my issues it is ok now @vonguyen1982

**Comment by doctorwho-123** [comment]
@broteam168  
How can I use the Speaker identification model vosk api in C # environment using C # via microphone? Is there an example I can use this model?

**Comment by JackBorgman** [comment]
I get the following error: System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'

**Comment by JackBorgman** [comment]
> I get the following error: System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'

I should probably say the line of code it was on: 
VoskRecognizer rec = new VoskRecognizer(new Model(@"C:\Users\Admin\Downloads\vosk-model-small-en-us-0.15\vosk-model-small-en-us-0.15\am\final.mdl"),16000.0f);
