### ISSUE TITLE
speaker recognition

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#327]
This is the most top great library I have seen. Thank you for such great effort.

I have few questions. 

I am using CentOS.

1) I have to ask your help how to get the speaker recognition with the transcription. 
2) Can one transcribe with live audio? I am interested in live audio transcription as well
3) Is it possible to customize and train engine at my own? If you can give little documentation link how to do that.
4) This library and models provided are with Apache 2.0 license? Can be used freely accordingly?

Please guide and help.

I wish you nice Christmas, Happy new year and stay healthy, safe from Corona.

**Comment by nshmyrev** [comment]
> I have to ask your help how to get the speaker recognition with the transcription.

You can find an example here:
https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py

> Can one transcribe with live audio? I am interested in live audio transcription as well

Yes

> Is it possible to customize and train engine at my own? If you can give little documentation link how to do that.

Yes, you can train the model and adapt the model to your needs, you can check.

https://alphacephei.com/vosk/adaptation
 https://alphacephei.com/vosk/models#training-your-own-model

> This library and models provided are with Apache 2.0 license? Can be used freely accordingly?

Library is Apache2. Models have different license, mostly Apache2 too, details on the model download page. Yes, you can use them freely.

**Comment by Tortoise17** [comment]
Your library is my best learning of 2020 before ending this year I must admit. Thank you so much agian. Stay healthy !!

**Comment by nshmyrev** [comment]
You are welcome, let me know if you have further questions.

**Comment by Tortoise17** [comment]
I found out that your training is using Kaldi based trainer with nnet3? and not the tensorflow?
I must admit. Your work is several steps ahead of google, facebook, youtube and twitter and many other researchers. I would like to join your community too. Awesome .

**Comment by Tortoise17** [comment]
I have tried the speaker recognition. I am having as output with some distances cosine based and the text, while I was expecting the speaker number depending on weights with the duration (start, end, speaker number, text ) or at least the speaker number with the text which I could export in json. I just tried your example with simple command 
`python test_speaker.py audio/input.wav`
. Maybe I am approaching it wrong way. Can you guide me a bit if something like this possible or the proper way to use this.

**Comment by nshmyrev** [comment]
You record samples for each speaker, get vectors from them by simply running the recognition.

You record sample for identification, get the vector from recognizer and compute distances to target speakers, the one with the closest distance is the result.

**Comment by Tortoise17** [comment]
Thank you so much. That I understand completely. Is there any way to get this information like json output preety or so to use these values. 
Also, I am facing problem with these lines 49, 50, 56 and 57
```
#        print ("X-vector:", res['spk'])
#        print ("Speaker distance:", cosine_dist(spk_sig, res['spk']), "based on", res['spk_frames'], "frames")
#print ("X-vector:", res['spk'])
#print ("Speaker distance:", cosine_dist(spk_sig, res['spk']), "based on", res['spk_frames'], "frames")


```
and at the moment, I am commenting out but, maybe these have actual info which I am not getting as output. If you can guide what to do with this. I am using current version of vosk and current available models.

**Comment by nshmyrev** [comment]
> Is there any way to get this information like json output preety or so to use these values.

Results are in json format

> Also, I am facing problem with these lines 49, 50, 56 and 57

what problem exactly?

**Comment by Tortoise17** [comment]
When I run the command from your example run:
`$python test_speaker.py out.json`

```
Speaker distance: 0.8933986160396366 based on 462 frames
Text: 
Traceback (most recent call last):
  File "test_speaker.py", line 49, in <module>
    print ("X-vector:", res['spk'])
KeyError: 'spk'
```
These are last lines and it crashes there. Maybe I am using command wrongly? 
`vosk=0.3.15`
`spk-model=0.4`

**Comment by nshmyrev** [comment]
If audio is short speaker might be missing, you can add a check 

```
if 'spk' in res:
     do_something

```

**Comment by Tortoise17** [comment]
If you can suggest, would be kind because I don't know its limitations or hinderness where the vocals are too short how much it can identify. I guess atleast should be 4 seconds? I am new to this framework.

**Comment by nshmyrev** [comment]
The longer the better. Minimum is below 1 second. 4 seconds is reasonable.

**Comment by Tortoise17** [comment]
it would be kind if you can suggest the lines to add, i could test. So, that at least I can run the trial until successful json export. Later I would readjust.

**Comment by nshmyrev** [comment]
> it would be kind if you can suggest the lines to add, i could test. So, that at least I can run the trial until successful json export. Later I would readjust.

Sorry, what do you need?

**Comment by Tortoise17** [comment]
actually, i want to get rid of this error and get the json export with speaker identification. If you can tell me what lines needed to be added here for this in the example run.

**Comment by nshmyrev** [comment]
See updated example here:

https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py

**Comment by Tortoise17** [comment]
Again a bug thank you. The current problem is resolved. thank you. ! but the json is not exported. 
is this the correct way to use this?
`$python test_speaker.py audio/input.wav result_out.json`

**Comment by sskorol** [comment]
@Tortoise17 current example doesn't export anything. It just prints results to the console. But saving `res` to JSON file is one of the most common programming tasks, and not related to speaker recognition. I believe you can easily implement it by yourself in 5 minutes.

**Comment by Tortoise17** [comment]
Thank you. 
and bundles of thank you for such great work.
wish you nice holidays celebrations and Happy new year. /may your new year brings lots o happiness to you. Stay healthy.

**Comment by Tortoise17** [comment]
Is this possible to get the time start with the speaker distance value / or and duration? Because I am unable to understand what other information this model provides with the distances and text. 
I tried to see what info is in **`rec.Result()`** but failed.

**Comment by nshmyrev** [comment]
> Is this possible to get the time start with the speaker distance value / or and duration? Because I am unable to understand what other information this model provides with the distances and text.

result in json format contains timing together with speaker vector. What problem to parse it do you have exactly?

**Comment by Tortoise17** [comment]
```
        res = json.loads(rec.Result())
        res2 = json.dump(rec, ensure_ascii=False) 
        res2.to_json(out_path, indent=4, orient='records', force_ascii=False)
```


I added to get the information exported by above stated commandline. and error is 
```
File "test_speaker.py", line 53, in <module>
    res2 = json.dump(rec, ensure_ascii=False) 
TypeError: dump() missing 1 required positional argument: 'fp'
```

Actually, I am trying to get the weights/distance of speaker with the time start and duration or so.

**Comment by Tortoise17** [comment]
```
        res = json.loads(rec.Result())
        df = pd.DataFrame.from_dict(pd.json_normalize(res), orient='columns')
        df.to_json(out_path, indent=4, orient='records', force_ascii=False)
```
Throws error

```
$ python speaker.py audio/input.wav out.json
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
ERROR (VoskAPI:Input():kaldi-io.cc:756) Error opening input stream /home/model/model-spk/final.mdl
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)
```

**Comment by Tortoise17** [comment]
Dear Sir / Friend / Brother. 
I have tried to understand what is going on with speaker recognition and how to get all the information exported as JSON. I am failed to understand how things are getting processed with spk- recog model. 

Is it possible and would be kind if you can make amendment in example test_speaker.py to get the information exported as JSON. I tried with Results and FinalResults. Both times, unsuccessful. Your kind help is highly appreciated.

**Comment by Tortoise17** [comment]
I have little issue with Speaker recognition JSON export still. I tried but it is wired JSON and cannot further use. 
I am using test_speaker.py example at the moment. 

I am trying to get the export like 
```
[
    {
        "result": [
            {
                "conf": 0.974185,
                "end": 1.14,
                "start": 0.84,
                "word": "something"
            },
            {
                "conf": 1.0,
                "end": 1.32,
                "start": 1.14,
                "word": "like"
            }]
    }
    [
        "Speaker distance:",
        0.9946537738540989
    ]
```
Something like this as exporting routing. As res is dict and when `I try to export as dataframe JSON`, the `error` is (`ValueError: arrays must all be same length`)
If you can comment where my mistake is.

**Comment by milind-soni** [comment]
@Tortoise17 Were you able to figure out how to generate transcript with speaker labels?

**Comment by russele7** [comment]
@nshmyrev 
Dear Nickolay,
I am trying your script test_speaker.py for audio file with several voises and I found that X-vectors are calculating for pieces, which are including different voises.
Is it possible to calculate X-vector for each recognized word? 
If yes, could you please provide some example or guide.  (I am using your russian model vosk-model-small-ru-0.15)

Thank you in advance.

**Comment by nshmyrev** [comment]
> Is it possible to calculate X-vector for each recognized word?

No, the recommended length for reliable x-vector extraction is 10 seconds.

**Comment by russele7** [comment]
@nshmyrev 
Nickolay, thank you for the answer and could you please clarify:
What is we take a short recording with one word (duration for example 1 second) and multiply it to a duration of 10 seconds (it turns out that we play the original recording 10 times). Is it correctly to do like that? Will the accuracy of the X-vector calculation be preserved?

**Comment by nshmyrev** [comment]
> Is it correctly to do like that?

No

**Comment by balaji7363** [comment]
how to identify who is speaker?


please help me
Thanks in advance

**Comment by brvier** [comment]
So there is anyway to identify speaker when there are multiple people speaking (an interview for example) ?

**Comment by russele7** [comment]
@brvier ,@balaji7363,    Hello.   VOSK-recognizer has an option, when together with speech recognition algorithm also calculate 128 additional coefficients for each phrase of audio.   These coefficients is are properties of the voise whish speak the phrase.   So each voise of audio should has specifical combination of these 128 coefficients.  You can apply some algorithm of Machine Learning for clusterization to separate phrases of each voise.   If you know the number of speakers than you can try k-means clusterization.  Otherwise you can try DBSCAN clusterization.   They are most popular and easy algorithms for clusterization.  You can try to find more difficult and more accurate methods.

**Comment by omar5477** [comment]
> 2\. transcribe with live audio? hello im trying to implement real time transcribing with speaker vosk identification which define who is speaker 1 or 2 my application is running but the problem the speaker is not accurately can you please help me?
