### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pourfard** [alphacep/vosk-api#328]
Hi,
I'm trying to build vosk api source for android. First of all i run 'build-kaldi.sh' and it runs without error. The I try to sync my project with gradle but I got this error. How `vosk_wrap.cc` is generated?

`Starting Gradle Daemon...
Gradle Daemon started in 873 ms
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
> Task :model-en:prepareKotlinBuildScriptModel UP-TO-DATE
debug|x86 :-- Check for working C compiler: /XXX/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
debug|x86 :-- Check for working C compiler: /XXX/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
debug|x86 :-- Detecting C compiler ABI info
debug|x86 :-- Detecting C compiler ABI info - done
debug|x86 :-- Detecting C compile features
debug|x86 :-- Detecting C compile features - done
debug|x86 :-- Check for working CXX compiler: /XXX/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
debug|x86 :-- Check for working CXX compiler: /XXXndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
debug|x86 :-- Detecting CXX compiler ABI info
debug|x86 :-- Detecting CXX compiler ABI info - done
debug|x86 :-- Detecting CXX compile features
debug|x86 :-- Detecting CXX compile features - done
debug|x86 :-- Configuring done
debug|x86 :CMake Error at CMakeLists.txt:37 (add_library):
debug|x86 :  Cannot find source file:
**debug|x86 :    build/generated-src/cpp/vosk_wrap.cc**
debug|x86 :  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
debug|x86 :  .hxx .in .txx
**debug|x86 :CMake Error: CMake can not determine linker language for target: vosk_jni**
debug|x86 :-- Generating done
debug|x86 :-- Build files have been written to: /XXX/vosk-api/android/.cxx/cmake/debug/x86
executing external native build for cmake /XXX/vosk-api/android/CMakeLists.txt

FAILURE: Build failed with an exception.`

**Comment by nshmyrev** [comment]
vosk_wrap.cc is created with swig, you probably do not have swig in your system.

**Comment by pourfard** [comment]
Thank you so much,

The problem was that I run `build-kaldi.sh` not `gradle build`
