### ISSUE TITLE
SpkModel reference

### ISSUE THREAD

**Issue by illion20** [alphacep/vosk-api#33]
I just tried to build the android module and got an error when generating the jni file `gradle build:`

`/vosk-api/android/build/generated-src/cpp/vosk_wrap.cc:439: error: undefined reference to 'SpkModel::SpkModel(char const*)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.`

is this a swig problem finding the spk_model.h in the root src folder?

**Comment by illion20** [comment]
Changing the CMakeLists.txt fixed this issue:

`set(API_SOURCES
"${PROJECT_SOURCE_DIR}/../src/kaldi_recognizer.cc"
"${PROJECT_SOURCE_DIR}/../src/kaldi_recognizer.h"
"${PROJECT_SOURCE_DIR}/../src/model.cc"
"${PROJECT_SOURCE_DIR}/../src/model.h"
"${PROJECT_SOURCE_DIR}/../src/spk_model.cc"
"${PROJECT_SOURCE_DIR}/../src/spk_model.h"
)`

**Comment by nshmyrev** [comment]
Thank you for information, I updated the repo as well.
