### ISSUE TITLE
Vosk makefile for windows

### ISSUE THREAD

**Issue by TarkusT** [alphacep/vosk-api#330]
Hi,

I have managed to compile Kaldi for windows and I want to use it with vosk api, but I didn't find a makefile for vosk to be compiled in windows.

The one that exists in the csharp folder compiles it for linux, not for windows.

Do you have any makefile that can be used in windows?

Thanks

**Comment by nshmyrev** [comment]
Makefiles are more or less the same, you just compile sources and add libraries. You can install gmake on windows and use the makefile for example.

If you have some specific trouble let us know.

**Comment by TarkusT** [comment]
When I run the "make -f Makefile" I get this output:

C:\Users\Darkstar\Desktop\vosk-api\csharp>make -f Makefile
mkdir -p gen
swig -csharp -DSWIG_CSHARP_NO_EXCEPTION_HELPER -dllimport "libkaldiwrap" \
    -namespace "Kaldi" -outdir gen -o vosk_wrap.c ../src/vosk.i
process_begin: CreateProcess(NULL, swig -csharp -DSWIG_CSHARP_NO_EXCEPTION_HELPER -dllimport libkaldiwrap -namespace Kaldi -outdir gen -o vosk_wrap.c ../src/vosk.i, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:56: vosk_wrap.c] Error 2


is there a missing file vosk_wrap.c?
