### ISSUE TITLE
Return plain text

### ISSUE THREAD

**Issue by xMpOnEx** [alphacep/vosk-api#333]
the FinalResult() funktion return something like this:
`
Verstanden: {
  "result" : [{
      "conf" : 0.771514,
      "end" : 18.450000,
      "start" : 18.150000,
      "word" : "aber"
    }],
  "text" : "aber"
`
How i can select and return only the **aber** ?

**Comment by nshmyrev** [comment]
import json

**Comment by xMpOnEx** [comment]
I use json Like that:

        print(rec.FinalResult())
        res = json.loads(rec.FinalResult())
        print("Verstanden: " + res["text"])

But output is:

{
  "result" : [{
      "conf" : 1.000000,
      "end" : 1.770000,
      "start" : 1.440000,
      "word" : "sind"
    }, {
      "conf" : 1.000000,
      "end" : 2.040000,
      "start" : 1.770000,
      "word" : "sie"
    }],
  "text" : "sind sie"
}
Verstanden:

**Comment by nshmyrev** [comment]
You need to parse rec.Result(), not just rec.FinalResult()

**Comment by xMpOnEx** [comment]
Its the same error

**Comment by nshmyrev** [comment]
Sorry, holiday time. Let me know if you need further help.

**Comment by xMpOnEx** [comment]
No proplem ive find a working solution.
Next question is if you anyone know how to improve the microphone qualitiy like denoising, trimming and gaining to get best results.

**Comment by sskorol** [comment]
It might be hard to get good results with a common mic. It depends on your environment though. I've tried [ReSpeaker](https://www.seeedstudio.com/ReSpeaker-Core-v2-0.html) for streaming audio chunks to Vosk server. It's not perfect, but there's a bundled API with some DSP algorithms available for this board. Their NS / AGC looks good in general.

**Comment by nshmyrev** [comment]
Seems solved. Feel free to reopen if needed.

**Comment by Berubec** [comment]
> No proplem ive find a working solution.
> Next question is if you anyone know how to improve the microphone qualitiy like denoising, trimming and gaining to get best results.

Could I kindly ask you to share the "working solution" you found?

**Comment by ShruthiRS21** [comment]
> No proplem ive find a working solution.
> Next question is if you anyone know how to improve the microphone qualitiy like denoising, trimming and gaining to get best results.

Please provide the working solution you have found.

**Comment by lonelyleopard** [comment]
```#!/usr/bin/env python3

from vosk import Model, KaldiRecognizer
import sys
import json
import os

if not os.path.exists("model"):
    print ("Please download the model from https://alphacephei.com/vosk/models and unpack as 'model' in the current folder.")
    exit (1)


model = Model("model")

# Large vocabulary free form recognition
rec = KaldiRecognizer(model, 16000)

# You can also specify the possible word list
#rec = KaldiRecognizer(model, 16000, "zero oh one two three four five six seven eight nine")

wf = open(sys.argv[1], "rb")
wf.read(44) # skip header
#  just change the while loop commands on your program surely it will solve your issue
while True:
    data = wf.read(4000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        res = json.loads(rec.Result())
        print (res['text'])

res = json.loads(rec.FinalResult())
print (res['text'])
```
