### ISSUE TITLE
Feasibility with iOS and Android game

### ISSUE THREAD

**Issue by fender** [alphacep/vosk-api#334]
I'm building a game in Unity that will run on iOS and Android. I'd like to be able to pass in an audio buffer (taken from mic input via Unity) of the users spoken voice. I'm only looking to detect a few set phrases and words to control game logic. How trivial is this with Vosk?

**Comment by nshmyrev** [comment]
It is not very straightforward, you have to compile kaldi for android and ios and build a c# wrapper yourself

You can probably start with linux/osx unity first with:

https://github.com/alphacep/vosk-api/tree/master/csharp

**Comment by fender** [comment]
@nshmyrev I see, thank you.
