### ISSUE TITLE
Compiler option -std=c++17 not working on docker image for armv7

### ISSUE THREAD

**Issue by pourfard** [alphacep/vosk-api#335]
Hi, 

As I mentioned, `-std=c++17` not working on cross docker image for armv7, but `-std=c++11` works fine.
 
`extra_compile_args = ['-std=c++17', '-Wno-sign-compare', '-Wno-unused-variable', '-Wno-unused-local-typedefs'])`

**Comment by nshmyrev** [comment]
Should be fixed now https://github.com/alphacep/vosk-api/commit/072b42cac6451b7f43b4541de9b7f31e9659bf5e

I have built our own toolchain
