### ISSUE TITLE
Reduce latency between partial and final result

### ISSUE THREAD

**Issue by pourfard** [alphacep/vosk-api#336]
Hi,

When I say something on microphone, the partial result ("partial" key) is generated after 500-1000 milliseconds, which I think part of this delay depends on buffering and some part depends on processing power. But the final result ("text" key) is generated about 1500-2500 milliseconds after utterance. Some part of the final result delay I think depends on how we detect end of a sentence (the gap between two sentences).

My question is can we reduce this delay? Can you please tell me how kaldi or vosk detects end of sentence and generates the final result?

**Comment by nshmyrev** [comment]
Which model is that about? We have new models with reduced latency (English, German).

https://alphacephei.com/nsh/2020/11/27/latency.html

**Comment by pourfard** [comment]
I am using this model: vosk-model-small-fa-0.4.

**Comment by nshmyrev** [comment]
Yes, this one uses old architecture, needs retrain.

**Comment by pourfard** [comment]
Thanks,
What happens if we decrease frames per buffer and then read and process
less data (1000 instead of 8000 or 16000) frames every time?

**Comment by nshmyrev** [comment]
Internally we process audio with 200ms chunks I think (3200 frames), you can not read less than that, but 8000 is probably too large.

**Comment by pourfard** [comment]
Are you sure?

In [android demo](https://github.com/alphacep/vosk-android-demo/blob/49d0ad72df53012253a0dea7d024ba64e9250cd3/app/src/main/java/org/kaldi/demo/KaldiActivity.java#L149) I see when processing a file the buffer size is 4096 bytes (2048 short number)

**Comment by nshmyrev** [comment]
> Are you sure?

Yes

> In android demo I see when processing a file the buffer size is 4096 bytes (2048 short number)

That also needs fix

**Comment by pourfard** [comment]
Thanks again,

We are waiting for a tutorial for how to train a vosk model from scratch and to change vocabulary of a small model.
