### ISSUE TITLE
Updating recognizer vocabulary in runtime

### ISSUE THREAD

**Issue by hoangkyanh7** [alphacep/vosk-api#338]
Hi,
I want to update my (small) model using a file with known text.
As you showed in test_words.py:
# You can also specify the possible word or phrase list as JSON list, the order doesn't have to be strict
rec = KaldiRecognizer(model, wf.getframerate(), '["this is my text for the file", "[unk]"
What I should do is to run the py file with the known text above to update my small model? and should I use the full text for the file or can use a list of possible words?
If so, how about the difference compared to test_text.py?

Many thanks!

**Comment by nshmyrev** [comment]
>  and should I use the full text for the file or can use a list of possible words?

You just pass list of lines in the text file as phrases.

> If so, how about the difference compared to test_text.py?

test_text just demonstrates json parsing.

**Comment by FirasHm** [comment]
Hello, thank you for this great ASR! Should the "possible word or phrase list" contain only recognized words? or they can contain "new vocab"?

**Comment by CobraCalle** [comment]
Sorry... but I`m totally confused about this... could anyone share a sample string for two or more utterances?

It is...
'["utterence1", "[unk]"]'
'["utterence2", "[unk]"]'

Or...
'["utterence1", "[unk]"]["utterence2", "[unk]"]'

Or...
'["utterence1", "utterence2", "[unk]"]'

Or...
'["utterence1", "[unk]
utterence2", "[unk]"]'

:-)

Tanks a lot

**Comment by nshmyrev** [comment]
This:

> '["utterence1", "utterence2", "[unk]"]'

**Comment by CobraCalle** [comment]
Thank you very much 👍

**Comment by nshmyrev** [comment]
Lets track this in #382

**Comment by Kra1ven** [comment]
Is there a way to add words on top of the existing vocabulary?

If I pass new words like in the following example:
`'["Hello", "[unk]"]'`
Then it will not recognize other words than were in the default vocabulary.
