### ISSUE TITLE
Expanding Portuguese Model

### ISSUE THREAD

**Issue by GabrieldeAS** [alphacep/vosk-api#339]
I'm trying to upgrade the Portuguese language Model, by expanding the lexicon and grammar. 

Following the instructions in section "Updating the language model" in https://alphacephei.com/vosk/adaptation I successfully expanded the grammar. But it is not enough, as adding new words is important.

To expand the Lexicon i will need either (preserving the phoneme set):
1 - The original word-phoneme Lexicon, to serve as training reference for new words
2 - The tools/process used to generate the original Lexicon

To solve using (1) i will need some way to extract the word-phoneme Lexicon from HCLr.fst. Is there a tool for this? 
Or could you please indicate the toolchain for generating a new Lexicon under the same phoneme set?

Is there some important caution in this expansion so that the system will not slow down (a lot) or lose accuracy? Is it also necessary to provide acoustic examples and training for the added words?

**Comment by nshmyrev** [comment]
It is not possible now. You have to mail contact@alphacephei.com and describe details on the project to get support on vocabulary update.

**Comment by nshmyrev** [comment]
Same as #382, lets track there

**Comment by ramleda** [comment]
@GabrieldeAS did you succeed?
