### ISSUE TITLE
Installation: ImportError: libgfortran.so.3 ... No such file

### ISSUE THREAD

**Issue by slowrunner** [alphacep/vosk-api#340]
Platform: Raspberry Pi 3B 
OS: Linux Carl 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
Install Steps:
1) $ pip3 install vosk    ("successfully installed vosk-0.3.15")
2) (brought down vosk-model-small-en-us-0.15 )
3) Vosk cannot find libgfortran.so.3   
```
$ python3 -c 'import vosk'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel, SetLogLevel
  File "/home/pi/.local/lib/python3.7/site-packages/vosk/vosk.py", line 13, in <module>
    from . import _vosk
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
```
4) There is a libgfortran.so.5 installed:
```
$ ldconfig -p | grep libgfortran
	libgfortran.so.5 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libgfortran.so.5
```

**What is the best approach for providing libgfortran.so.3 to Vosk on Raspberry PiOS?**

I tried just creating a symlink to libgfortran.so.5 but the error changes to:
```
ImportError: /usr/lib/libgfortran.so.3: version `GFORTRAN_1.0' not found (required by /home/pi/.local/lib/python3.7/site-packages/vosk/_vosk.cpython-37m-arm-linux-gnueabihf.so)
```

I also tried installing gfortran before installing Vosk - no cigars.

**Comment by candaj** [comment]
Hi,

Did you try to install libgfortran3 through apt?
`sudo apt-get install libgfortran3`

**Comment by slowrunner** [comment]
install libgfortran3 through apt?
sudo apt-get install libgfortran3

Success!  Thanks

**Comment by nshmyrev** [comment]
Same as 

https://github.com/alphacep/vosk-api/issues/130
