### ISSUE TITLE
The accuracy of Chinese recognition by microphone is too low

### ISSUE THREAD

**Issue by wlx007** [alphacep/vosk-api#342]
Hello, I ran vosk-android-demo,File recognition accuracy is very high, but microphone recognition is relatively low.I try to convert the sound file to mono with a sampling rate of 44100 for file recognition，the accuracy is very high.So I wonder if the accuracy of microphone recognition is related to the sound sampling frequency,But I found that in the speechrecognizer class, the sampling frequency is fixed at 16000，Is there any interface to modify the sampling frequency in class speechrecognizer ?I'm looking forward to your reply.

**Comment by nshmyrev** [comment]
We have reworked microphone code in https://github.com/alphacep/vosk-api/commit/6f2d6d0d69faacf3c9183818635cecca18ad6a97, can you please try one more time.

**Comment by nshmyrev** [comment]
It should be ok now
