### ISSUE TITLE
buildozer support for android build

### ISSUE THREAD

**Issue by Krozark** [alphacep/vosk-api#343]
In order to use vosk in python on android, it'll be very helpful to have a buildozer support.

**Comment by nshmyrev** [comment]
Ok, it would be nice to have it one day indeed.

**Comment by nshmyrev** [comment]
I consider it a bit exotic though.

**Comment by nshmyrev** [comment]
I'm not sure it will be our focus, maybe sometime later once someone can contribute. Sorry
