### ISSUE TITLE
Forced alignment?

### ISSUE THREAD

**Issue by lenzo-ka** [alphacep/vosk-api#348]
Is there a way to do forced alignment? Can we get phoneme information and timings?

**Comment by nshmyrev** [comment]
Hi Kevin

For forced alignment you can use phrase feature, just specify the phrase to look for:

https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py

As for phoneme timing, no plans for it yet and probably we will not support it any time soon, you have to implement it yourself.

**Comment by lenzo-ka** [comment]
Thanks
