### ISSUE TITLE
Adapting german language model with text file 

### ISSUE THREAD

**Issue by PhilippKopania** [alphacep/vosk-api#350]
I am new to Kaldi and trying to create a small program which can be controlled by voice. 
I only have to recognize 20 words.
I am using the small german model and it works pretty good, but i want to adapt the model for better recognition.
So i created a text file with the words i want to recognize and followed this instructions: https://alphacephei.com/vosk/adaptation.
When i try to execute **fstsymbols --save_osymbols=words.txt Gr.fst > /dev/null** i get this error:
ERROR: ReadFst: Can't open file: Gr.fst

What am i doing wrong ? 

And i have a second question: When i tried Updating recognizer vocabulary in runtime, i had the problem that if i spoke words, which were non of my 20 voice commands, the program simply "chooses the command, which was most similar to the spoken word. is there a possibility that the program just ignores words which are definitely not in the "updated vocabulary"?
Thank you in advance!

**Comment by nshmyrev** [comment]
> ERROR: ReadFst: Can't open file: Gr.fst

The missing file is inside the model, you just need to find and and make sure you specified proper path.

> And i have a second question: When i tried Updating recognizer vocabulary in runtime, i had the problem that if i spoke words, which were non of my 20 voice commands, the program simply "chooses the command, which was most similar to the spoken word. is there a possibility that the program just ignores words which are definitely not in the "updated vocabulary"?

You can add '[unk]' to the phrase list.

**Comment by PhilippKopania** [comment]
Thank you for your fast answer!
The Gr.fst file is inside the "graph" directory.
How do  i specify the path? ( Sorry  i am completely new to Linux and Kaldi )

**Comment by nshmyrev** [comment]
You just change to the graph folder first:

     cd graph
     pwd

**Comment by PhilippKopania** [comment]
It worked!
Thank you very very much !

**Comment by nshmyrev** [comment]
Ok, feel free to reopen if needed.

**Comment by PhilippKopania** [comment]
> You can add '[unk]' to the phrase list.

i tried using this like in the demo code:  [](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py)

**rec = KaldiRecognizer(model, 16000,'["test kürzen stopp klemmen brücken montage verkabelung verpackung qualitätskontrolle beschriftung produzieren pause kein auftrag fehlendes material rüsten störung logistik administration nacharbeit", "[unk]"]')**

but it still recognizes completely different words and chooses the most similar. 

and additionally it gives me this in the console: 
WARNING (VoskAPI:OutputArcForce():word-align-lattice.cc:578) Invalid word at end of lattice [partial lattice, forced out?]

could you help me again ?
