### ISSUE TITLE
Timestamps without recognition

### ISSUE THREAD

**Issue by qo4on** [alphacep/vosk-api#351]
Thank you for great asr!
I have a mono `pcm_f64le` file and a text file with English words. What is the best way (fast and accurate) to get timestamps for each word with `vosk`?

**Comment by nshmyrev** [comment]
You can recognize with the phrases to get timestamps:

https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py

for more advanced things you have to wait till we implement https://github.com/alphacep/vosk-api/issues/337

**Comment by qo4on** [comment]
Why do you ask for a list in this case?
```
# You can also specify the possible word or phrase list as JSON list, the order doesn't have to be strict
rec = KaldiRecognizer(model, wf.getframerate(), '["oh one two three four five six seven eight nine zero", "[unk]"]')
```
If I have all the words in correct order for the audio do I have to feed a list with only one element `'["oh one two three"]'` or split to words like `'["oh", "one", "two", "three"]'`?

Do you know any workaround to make it work with audio files longer than 7 seconds?

**Comment by nshmyrev** [comment]
> Why do you ask for a list in this case?

You can provide a list of a single phrase, it is up to you what you expect to see in the audio

> Do you know any workaround to make it work with audio files longer than 7 seconds?

It should simply work, there is no need for workaround. It might have trouble with 1-2 hours

**Comment by qo4on** [comment]
I tested this in Colab:
```
!ffmpeg -y -i 1.wav -acodec pcm_s16le 2.wav    # Your model does not work with pcm_f64le
!python3 ./test_words.py 2.wav
```
The input was 2 minutes and 51 seconds. The last word I saw was at 7 second:
```
{
      "conf" : 0.954997,
      "end" : 7.290000,
      "start" : 6.840000,
      "word" : "one"
    }
```

**Comment by nshmyrev** [comment]
Share collab or the files

**Comment by qo4on** [comment]
Sorry, my fault. `vosk` works perfectly. Colab is very slow when uploading a file through a browser window, so when I started transcribing most of the file had not yet been uploaded.
Thank you for your help.

**Comment by qo4on** [comment]
I have one more question about aligning. A text may contain some digits, symbols or smileys. Your model has a text front end that filters out of the vocabulary words. Evidently I will not get exactly the same words in exactly the same order as I fed to the model.
Do you know any algorithm which I can use to align input words and transcribed words with timestamps?

**Comment by nshmyrev** [comment]
The algorithm is https://en.wikipedia.org/wiki/Smith%E2%80%93Waterman_algorithm
