### ISSUE TITLE
Update Vocabulary in runtime

### ISSUE THREAD

**Issue by PhilippKopania** [alphacep/vosk-api#353]
Sorry i couldn't reopen the original issue.
 i have a problem with updating the vocabulary of a small german model in runtime.

> You can add '[unk]' to the phrase list.

i tried using this like in the demo code:  [](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py)

**rec = KaldiRecognizer(model, 16000,'["test kürzen stopp klemmen brücken montage verkabelung verpackung qualitätskontrolle beschriftung produzieren pause kein auftrag fehlendes material rüsten störung logistik administration nacharbeit", "[unk]"]')**

but it still recognizes completely different words and chooses the most similar. 

and additionally it gives me this in the console: 
WARNING (VoskAPI:OutputArcForce():word-align-lattice.cc:578) Invalid word at end of lattice [partial lattice, forced out?]

could you help me again ?

_Originally posted by @PhilippKopania in https://github.com/alphacep/vosk-api/issues/350#issuecomment-756883797_

**Comment by nshmyrev** [comment]
Provide the audio samples to reproduce your problems.

Which Vosk version do you try? Feels like an older one.

**Comment by PhilippKopania** [comment]
i dont have audio samples. i use a microphone and speak the commands i want to detect.

i am using vosk 0.3.7 according to pip list

**Comment by nshmyrev** [comment]
Thats very old, are you on Windows? You have to wait a bit till we release an updated version for Windows

**Comment by PhilippKopania** [comment]
yes i am creating a voice controlled program for my master thesis and this has to be on windows. 
thank you for the answer! 
so the only probability to improve the detection would be to rebuild the language model with a text file, which contains my voice commands, right ? 

or should i create a completly new model ? i have Kaldi installed on a linux system. 
what would i need to train my own model ? just some .wav files and a text file with the corresponding text ? And than just start the run.sh in mini-librispeech?

**Comment by nshmyrev** [comment]
Hello, new version 0.3.18 for Windows is released on pypi:

https://pypi.org/project/vosk/0.3.18/

please update, it should be better. Reopen if you see any issues.
