### ISSUE TITLE
vosk on gpu

### ISSUE THREAD

**Issue by Gustavino123** [alphacep/vosk-api#354]
Hi i work on a little project with (VOSK asr..kaldi model) and i have an issue , on the first its work good on (Python) jupyter anaconda  , but after good time it will be slower on the translating words , im not talking about accuracy but on the time of responding
and other thing how i can work on GPU with vosk 
i thinking about loop of while  my be overload or somthing , can you help me please ? , thanks

**Comment by nshmyrev** [comment]
Not yet possible but we are working on it, track in issue https://github.com/alphacep/vosk-api/issues/74
