### ISSUE TITLE
Male and female speech recognition

### ISSUE THREAD

**Issue by pourfard** [alphacep/vosk-api#359]
Hi,

I have a problem with recognizing women and children voices. When I change pitch of the audio file (change it to sound like man voice) the recognition gets better.

I think this problem depends on the data set that you have trained the model?

**Comment by nshmyrev** [comment]
> I think this problem depends on the data set that you have trained the model?

Yes, I think this too.

**Comment by pourfard** [comment]
Can I try to train a model for "Farsi" language like the small one that you have trained for vosk? Or you can only?

**Comment by nshmyrev** [comment]
> Can I try to train a model for "Farsi" language like the small one that you have trained for vosk? Or you can only?

Sure, you can with mini_librispeech recipe like we mention on our models page.

**Comment by pourfard** [comment]
Thank you so much,

What data you have used for Farsi? and what do you mean by TBD for accuracy?

**Comment by nshmyrev** [comment]
> What data you have used for Farsi? 

Sorry, we do not disclose this information

> and what do you mean by TBD for accuracy?

TBD is "to be defined" means in the future
