### ISSUE TITLE
VOSK gives a single word back if nothing is spoken

### ISSUE THREAD

**Issue by JulianStremel** [alphacep/vosk-api#361]
I just ran Vosk on python using the test_microphone.py and a german server as well as a small model and it detects nothing until i speak the first time which is obiously correct but if i remain silent for a while it gives back the word "einen" on the server model and the word "nun" on the small model without any microphone input.

Is that a Problem with the model or could it be VOSK API sided ?

**Comment by nshmyrev** [comment]
Maybe ghosts whisper in your room

**Comment by nshmyrev** [comment]
We have reworked microphone code:

https://github.com/alphacep/vosk-api/commit/6f2d6d0d69faacf3c9183818635cecca18ad6a97

Please try and collect dump with the --filename argument and share it for analysis.

**Comment by nshmyrev** [comment]
Updated version https://github.com/alphacep/vosk-api/blob/master/python/example/test_microphone.py

**Comment by nshmyrev** [comment]
Same issue with examples actually discussed in #837
