### ISSUE TITLE
Incorrect word detection on a long audio file

### ISSUE THREAD

**Issue by benbense** [alphacep/vosk-api#363]
I tried running the API to transcript a Podcast for example (around 40 min), using this model ```vosk-model-en-us-aspire-0.2```
while running the process I get those warnings:
```WARNING (VoskAPI:LinearCgd():optimization.cc:549) Doing linear CGD in dimension 100, after 15 iterations the squared residual has got worse, 1.42672 > 0.622241.  Will do an exact optimization.
WARNING (VoskAPI:LinearCgd():optimization.cc:549) Doing linear CGD in dimension 100, after 15 iterations the squared residual has got worse, 8.64225 > 6.58775.  Will do an exact optimization.
WARNING (VoskAPI:LinearCgd():optimization.cc:549) Doing linear CGD in dimension 100, after 15 iterations the squared residual has got worse, 19.015 > 18.1152.  Will do an exact optimization.
WARNING (VoskAPI:LinearCgd():optimization.cc:549) Doing linear CGD in dimension 100, after 15 iterations the squared residual has got worse, 5.28956 > 4.29383.  Will do an exact optimization.
WARNING (VoskAPI:LinearCgd():optimization.cc:549) Doing linear CGD in dimension 100, after 15 iterations the squared residual has got worse, 4.5513 > 2.7476.  Will do an exact optimization.
WARNING (VoskAPI:LinearCgd():optimization.cc:549) Doing linear CGD in dimension 100, after 15 iterations the squared residual has got worse, 2.51246 > 0.410331.  Will do an exact optimization.
LOG (VoskAPI:SolveQuadraticProblem<double>():sp-matrix.cc:686) Solving quadratic problem for called-from-linearCGD: floored 1 eigenvalues. 
```

After checking the output of the file as more as im going to the end of the text it get's the words worse, and at the end it's just typing:  ```new boots noodles jules loop holes new shooter new shooter who shoot tutorials luke duke are today luke luke luke noodles boop boop boop boop boop new schools today noodles noodles noodles boots luke who shot luke luke cage new suit new schools new new tools today```

What am I missing or doing wrong?
Should I use other model or just split long files to short ones.
I'm kind of new to this stuff so forgive me for this rookie question.

**Comment by nshmyrev** [comment]
Which vosk-api version are you using? What OS? Are you trying directly or through the server.

Daanzu model should be more accurate for podcasts.

**Comment by nshmyrev** [comment]
Also make sure that audio has proper format (16 khz 16 bit mono)

**Comment by benbense** [comment]
Using version 0.3.7 Running on Win10 1909, I'm running it directly.
Already running the wav file formatted to those specs.
Ill try to use the Daanzu model.
Anything else I can do to improve the recognition?

**Comment by nshmyrev** [comment]
You need to wait for version update for Windows, or try Linux version. Daanzu model should be much better too.

**Comment by benbense** [comment]
Ok great, Ill consider moving to Linux, and also use the Daanzu model.
Thank you very much for your help!
