### ISSUE TITLE
Issue installing nodejs bindings

### ISSUE THREAD

**Issue by DiscoTiger** [alphacep/vosk-api#364]
Hello, I'm trying to install the vosk nodejs bindings following the instructions to build from source [here](https://alphacephei.com/vosk/install) and am running into an issue. It looks like I'm missing some dependencies or something but I'm not sure what to do about it. This is the error I get from gyp.
```
npm install --kaldi_root=/home/caden/kaldi

> vosk@0.3.17 install /home/caden/vosk-api/nodejs
> node-gyp rebuild

make: Entering directory '/home/caden/vosk-api/nodejs/build'
  ACTION binding_gyp_vosk_target_swig vosk_wrap.cc
  CXX(target) Release/obj.target/vosk/../src/kaldi_recognizer.o
  CXX(target) Release/obj.target/vosk/../src/model.o
  CXX(target) Release/obj.target/vosk/../src/language_model.o
  CXX(target) Release/obj.target/vosk/../src/spk_model.o
  CXX(target) Release/obj.target/vosk/../src/vosk_api.o
  CXX(target) Release/obj.target/vosk/vosk_wrap.o
../vosk_wrap.cc: In function ‘void SWIGV8_AddStaticVariable(v8::Handle<v8::Object>, const char*, SwigV8AccessorGetterCallback, SwigV8AccessorSetterCallback)’:
../vosk_wrap.cc:1524:87: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType)’, declared with attribute warn_unused_result [-Wunused-result]
 1524 |   obj->SetAccessor(SWIGV8_CURRENT_CONTEXT(), SWIGV8_SYMBOL_NEW(symbol), getter, setter);
      |                                                                                       ^
In file included from ../vosk_wrap.cc:11:
/home/caden/.cache/node-gyp/10.23.1/include/node/v8.h:3348:37: note: declared here
 3348 |   V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
      |                                     ^~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-ignored-quaifiers’
  SOLINK_MODULE(target) Release/obj.target/vosk.node
g++: error: /home/caden/kaldi/tools/OpenBLAS/install/lib/liblapack.a: No such file or directory
g++: error: /home/caden/kaldi/tools/OpenBLAS/install/lib/libblas.a: No such file or directory
g++: error: /home/caden/kaldi/tools/OpenBLAS/install/lib/libf2c.a: No such file or directory
make: *** [vosk.target.mk:195: Release/obj.target/vosk.node] Error 1
make: Leaving directory '/home/caden/vosk-api/nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/caden/.nvm/versions/node/v10.23.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.8.0-36-generic
gyp ERR! command "/home/caden/.nvm/versions/node/v10.23.1/bin/node" "/home/caden/.nvm/versions/node/v10.23.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/caden/vosk-api/nodejs
gyp ERR! node -v v10.23.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vosk@0.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vosk@0.3.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/caden/.npm/_logs/2021-01-13T00_28_25_597Z-debug.log
```
Specifically I'm missing liblapack.a libblas.a libf2c.a but after compiling again from step 1 I can't figure out why the files aren't being generated.
I am on a fresh install of ubuntu 20.04 LTS because I ran into other issues installing OpenBLAS on arch linux and ubuntu under WSL.

**Comment by nshmyrev** [comment]
You need to follow this steps for kaldi build:

https://github.com/alphacep/vosk-api/blob/fe91b5a717e6ec8e04621ea7d7b988394296705e/travis/Dockerfile.manylinux#L25

**Comment by DiscoTiger** [comment]
Thank you! That worked right away.
I don't think this is reflected in the installation instructions though, unless I missed something.

**Comment by nshmyrev** [comment]
We will be moving to NAPI anyway, I'll rework all these things.

**Comment by dzoba** [comment]
I am looking forward to the update with NAPI.  Do you know approximately when that will be ready?

**Comment by nshmyrev** [comment]
Unlikely very fast, many tasks ahead, but we are moving in that direction. Actually I had a thought of using https://github.com/node-ffi/node-ffi instead. That will help us to create more flexible binaries shared across platforms and plugged through cffi interface (in Python, Java and Node too).

It is really painful to compile 10 wrappers for 10 platforms right now. Most likely we will build a library and use it through cffi instead.

**Comment by nshmyrev** [comment]
Python attempt is here: https://github.com/alphacep/vosk-api/blob/master/python/cffi/test.py

**Comment by dzoba** [comment]
Thank you so much.  This project looks amazing and I've had some trouble getting it running with Node.js but I'm eager to try it out.  Thanks for the link to the python version.

**Comment by nshmyrev** [comment]
I have pushed node-ffi work in https://github.com/alphacep/vosk-api/commit/77b114d434d0721a2cd4791084eaa07f3fd2dd7c, needs some love to organize classes though.

**Comment by nshmyrev** [comment]
Lets track it in https://github.com/alphacep/vosk-api/issues/116
