### ISSUE TITLE
White noise with new microphone example

### ISSUE THREAD

**Issue by candaj** [alphacep/vosk-api#366]
Hello,

I've tested the new python example for mic and something weird happen (but it happen also with the pyaudio one):

With a 44100hz mic I've a lot of white noise in the recording, making impossible for vosk to recognize something, where with a 16000hz mic I've no issue at all. 
I'm wondering if you have seen with issue before I take a look on sounddevice / pyaudio issues

(I'm testing with a raspberry 3+ and vosk 0.3.17)

**Comment by nshmyrev** [comment]
I doubt it is related to vosk, more like alsa driver issue

**Comment by candaj** [comment]
Yeah I know, but as you have a lot more experience than I have in it maybe you had some obvious idea that I'm missing...
I'll try to find something and update that ticket if it can help others :)

**Comment by nshmyrev** [comment]
Probably not relevant anymore.
