### ISSUE TITLE
fastquestion,does it support windows?

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [alphacep/vosk-api#369]
If have support.anyone have success in building and compiling the java or cpp?
I dlwded the repo,but I do not get where is the model,and for java does it depend on c api?
@.@,someone help me.

**Comment by nshmyrev** [comment]
We support Python in Windows, not Java. Java is also possible, maybe some time later.

**Comment by xwaeaewcrhomesysplug** [comment]
Thank you very much,closing this issue to not fill the area.Will check out again in future.^^
