### ISSUE TITLE
Question: can we use other models besides alphacep-model-android*? 

### ISSUE THREAD

**Issue by cjbassi** [alphacep/vosk-api#37]
Like the ones from here: https://kaldi-asr.org/models.html

Also, where are those android models sourced from? And what's the effect of using a smaller model like the android ones?

Thanks!

**Comment by nshmyrev** [comment]
Yes, you can, you just need to arrange files properly. You can check for details:

https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-de

**Comment by nshmyrev** [comment]
> Also, where are those android models sourced from?

They are trained by us on big datsets.

> And what's the effect of using a smaller model like the android ones?

Usually it is like 10% less accurate than the best server model but it compensates by the faster decoding speed and much smaller size, users don't have to download gigabytes and store them in memory.

**Comment by cjbassi** [comment]
Makes sense, thanks!

Another question: I see there is an English docker file that pulls a model from alphapcei.com:

https://github.com/alphacep/vosk-server/blob/58776b0281f74ca67b56f79f077fdb950f85b505/docker/Dockerfile.kaldi-en#L6

Is this one of the official kaldi models that just has its files reordered?

**Comment by nshmyrev** [comment]
It is aspire model from kaldi-asr.org with recompiled graph (slightly better language model).

**Comment by cjbassi** [comment]
Thanks for the help. The server setup is definitely more resource intensive than I would've thought so maybe I'll stick with the android one.
