### ISSUE TITLE
Using Vosk on Jetson Tx2

### ISSUE THREAD

**Issue by xoxoxo13102020** [alphacep/vosk-api#374]
Hello I have a jetson Tx2 which has arm64 based architecture with ubuntu 18.04. I am trying to use vosk on bn jetson I installed vosk successfully with this command(Maybe problem is in there dont know).

`pip3 install https://github.com/alphacep/vosk-api/releases/download/0.3.7/vosk-0.3.7-cp36-cp36m-linux_aarch64.whl`

I found this in  an other issue : https://github.com/alphacep/vosk-api/issues/97

When I try to use test codes I got this error how to fix it? The real question is could I use vosk in Jetson tx2 does anyone know?
```
python3 test_ffmpeg.py 0.mp4
Traceback (most recent call last):
  File "test_ffmpeg.py", line 1, in <module>
    from vosk import *
  File "/usr/local/lib/python3.6/dist-packages/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel, SetLogLevel
  File "/usr/local/lib/python3.6/dist-packages/vosk/vosk.py", line 13, in <module>
    from . import _vosk
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
```
Thank you so muchhhhh

**Comment by nshmyrev** [comment]
Latest version is 0.3.17, you can try

https://github.com/alphacep/vosk-api/releases/download/0.3.17/vosk-0.3.17-cp36-cp36m-linux_aarch64.whl

**Comment by sskorol** [comment]
@xoxoxo13102020 I'd recommend rebuilding Kaldi + Vosk with Cuda support on Jetson boards to reveal all the benefits of this hardware. GPU support will give you a huge performance boost.

**Comment by xoxoxo13102020** [comment]
thank you so much.
