### ISSUE TITLE
problem with exporting speaker_recognition all info as json

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#375]
I have tried to understand the speaker recognition engine and its information. I tried to export the speaker `Text`, `speaker distance`, its `time`  and `duration` and `confidence` as json. 
I have problem.

When I tried to make **json.dump** the `res` information, 
**it is only exporting the last sentence as text and its x_vectors and no time or any info,** 
Can you help me e.g., with your example how to get the maximum information exported or if I can select any specific which I need to test at my end. 
I tried to go through the library code routine and still confused how to handle it.

**Comment by nshmyrev** [comment]
I don't get your problem. You need to provide more details as well as the code you wrote.

**Comment by Tortoise17** [comment]
Dear Sir, 
actually I want to get the `time`, `fragment text` and its `duration` with `confidence` and `speaker distance` as JSON output. I cannot get it unfortunately. I tried this 

```
            with open('output.json', 'w') as f:
                json.dump(res, f, ensure_ascii=False, indent=4)
```

and it exported only the last sentence with some x_vectors. Can you point out where my mistake is? or what needs to get exported to have these information I need?

**Comment by Tortoise17** [comment]
OK now I got little more from this engine. A`ctually, it is providing the results, but for some frames and with my this JSON export, it is updating each time with the frame text, and spk_distance and the previous is gone. Also, the time and confidence is missing.` Not all the results are available with JSON export with the running command. At the end, only the last line or few lines are left in JSON and earlier results are gone with the update. Can you comment how to handle it?

**Comment by Tortoise17** [comment]
In easy words, I want to export complete audio json as metadata with time, duration, fragment/word and speaker distance.

**Comment by Tortoise17** [comment]
I tried to add the speaker distance with general JSON export file. 
```
        with open('output.json', 'a') as f:
                json.dump((res, "Speaker distance:", cosine_dist(spk_sig , res['spk'])), f, ensure_ascii=False, indent=4)
```
it has the following error after two sentences
`KeyError: 'spk'`

while until two sentences it works fairly well.

Here the speaker until two sentences is same and afterwards, it changes. 
It seems, maybe due to my any mistake here while exporting. when speaker changes, it throws error?

**Comment by Tortoise17** [comment]
Sorry, my failure. I resolved with your previous guidelines. Thank you so much. always.

**Comment by Tortoise17** [comment]
Thank you so much. Really I should be your student. You have done such a great job.
