### ISSUE TITLE
Exit without error message after model load

### ISSUE THREAD

**Issue by SMaurischat** [alphacep/vosk-api#376]
Hey man,

first of all, great work on the project!

Now, it seems like, if i put a model in a docker, it just stops without dumping an error message. This is the dump with the last line.

`LOG (VoskAPI:ReadDataFiles():vosk/model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0404391 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:221) Loading i-vector extractor from /${project}/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:246) Loading HCLG from /${project}/model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:265) Loading words from /${project}/model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:273) Loading winfo /${project}/model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:281) Loading CARPA model from /${project}/model/rescore/G.carpa`

`vosk==0.3.17
FROM python:3.9.1
vosk-model-de-0.6`

os.path.isdir(path) is true and there is no "mfcc.conf not found message", so loading it should be successfull.
Without building an image, everything is working fine.

Should i dump you the logging level, or how can i help to debug (maybe you have seen this before)?

**Comment by SMaurischat** [comment]
Here is more: just tested vosk-model-small-de-0.15. This works totally fine.

**Comment by SMaurischat** [comment]
Hm ok, it seems to have to do with memory limitations in the container and setting of the local docker engine. Sucks that there is nothing to hint though. Can you confirm my hypothesis for future readers?

**Comment by SMaurischat** [comment]
And this is a separate issue i guess, but this is also sth i saw which is not solvable for me. Happens in a Kubernetes environment, also with the smaller model, mentioned earlier:
`ERROR (VoskAPI:ExpectToken():io-funcs.cc:209) Expected token "<TransitionModel>", got instead "version".`

**Comment by nshmyrev** [comment]
> Can you confirm my hypothesis for future readers?

It goes out of memory, yes, the process gets killed.

> ERROR (VoskAPI:ExpectToken():io-funcs.cc:209) Expected token "<TransitionModel>", got instead "version".

Looks like model files are corrupted somehow,

**Comment by nshmyrev** [comment]
Feel free to reopen if still relevant
