### ISSUE TITLE
module vosk has no attribute Model

### ISSUE THREAD

**Issue by ludwigsaux** [alphacep/vosk-api#377]
Hi, 
I'm trying to run test_microphone.py, just to understand what I'm saying.
I have a problem on my raspberry 'module vosk has no attribute Model'
I have a french model which work correctly because i tried on ubuntu and everything is good.

I don't know why I have the message on my raspberry : module vosk has no attribute Model

Python3.7, newest pip version and all libraries needed

**Comment by ludwigsaux** [comment]
I'm using the last version of raspian os to run with virtual box but i just zip my file with a custom model running on ubuntu and tranfer it with google drive to my rapsberry pi .
Is it possible the zip just delete a file or something like that ?

**Comment by nshmyrev** [comment]
It might be that you have a local file called vosk.py or a folder vosk with __init__.py and python loads it instead of Vosk library itself. You can run python3 with argument -v to figure out which files are actually loaded.

**Comment by ludwigsaux** [comment]
Here is the command with the -v.
I'm a begginer and i tried to remove all vosk file and init.py

https://docs.google.com/document/d/1R4k2i3Rf2EwcXsmamhSozJ4tg6HglWYghIoqVQsyq7Q/edit?usp=sharing

**Comment by ludwigsaux** [comment]
Hi, 
I don't have news, I'm stuck and I don't know how to do, if someone can help me I will very happy ! 

Have a nice days !

**Comment by nshmyrev** [comment]
From the log it seems your installation is corrupted somehow.

Run the following commands:

```
rm -rf /home/pi/.local/lib/python3.7/site-packages/vosk
pip3 install -U vosk
```
And provide updated `python3 -v ./test_microphone` output including the actual command line you are running

**Comment by ludwigsaux** [comment]
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.7/encodings/__pycache__/__init__.cpython-37.pyc matches /usr/lib/python3.7/encodings/__init__.py
# code object from '/usr/lib/python3.7/encodings/__pycache__/__init__.cpython-37.pyc'
# /usr/lib/python3.7/__pycache__/codecs.cpython-37.pyc matches /usr/lib/python3.7/codecs.py
# code object from '/usr/lib/python3.7/__pycache__/codecs.cpython-37.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0xf768022c>
# /usr/lib/python3.7/encodings/__pycache__/aliases.cpython-37.pyc matches /usr/lib/python3.7/encodings/aliases.py
# code object from '/usr/lib/python3.7/encodings/__pycache__/aliases.cpython-37.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0xf768992c>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0xf7670e0c>
# /usr/lib/python3.7/encodings/__pycache__/utf_8.cpython-37.pyc matches /usr/lib/python3.7/encodings/utf_8.py
# code object from '/usr/lib/python3.7/encodings/__pycache__/utf_8.cpython-37.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0xf769430c>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.7/encodings/__pycache__/latin_1.cpython-37.pyc matches /usr/lib/python3.7/encodings/latin_1.py
# code object from '/usr/lib/python3.7/encodings/__pycache__/latin_1.cpython-37.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0xf76949ec>
# /usr/lib/python3.7/__pycache__/io.cpython-37.pyc matches /usr/lib/python3.7/io.py
# code object from '/usr/lib/python3.7/__pycache__/io.cpython-37.pyc'
# /usr/lib/python3.7/__pycache__/abc.cpython-37.pyc matches /usr/lib/python3.7/abc.py
# code object from '/usr/lib/python3.7/__pycache__/abc.cpython-37.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0xf7694d4c>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0xf7694bac>
# /usr/lib/python3.7/__pycache__/site.cpython-37.pyc matches /usr/lib/python3.7/site.py
# code object from '/usr/lib/python3.7/__pycache__/site.cpython-37.pyc'
# /usr/lib/python3.7/__pycache__/os.cpython-37.pyc matches /usr/lib/python3.7/os.py
# code object from '/usr/lib/python3.7/__pycache__/os.cpython-37.pyc'
# /usr/lib/python3.7/__pycache__/stat.cpython-37.pyc matches /usr/lib/python3.7/stat.py
# code object from '/usr/lib/python3.7/__pycache__/stat.cpython-37.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0xf76ad26c>
# /usr/lib/python3.7/__pycache__/posixpath.cpython-37.pyc matches /usr/lib/python3.7/posixpath.py
# code object from '/usr/lib/python3.7/__pycache__/posixpath.cpython-37.pyc'
# /usr/lib/python3.7/__pycache__/genericpath.cpython-37.pyc matches /usr/lib/python3.7/genericpath.py
# code object from '/usr/lib/python3.7/__pycache__/genericpath.cpython-37.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0xf762f74c>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0xf76ad3ac>
# /usr/lib/python3.7/__pycache__/_collections_abc.cpython-37.pyc matches /usr/lib/python3.7/_collections_abc.py
# code object from '/usr/lib/python3.7/__pycache__/_collections_abc.cpython-37.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0xf762fcac>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0xf76a450c>
# /usr/lib/python3.7/__pycache__/_sitebuiltins.cpython-37.pyc matches /usr/lib/python3.7/_sitebuiltins.py
# code object from '/usr/lib/python3.7/__pycache__/_sitebuiltins.cpython-37.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0xf76a47ac>
# /usr/lib/python3.7/__pycache__/_bootlocale.cpython-37.pyc matches /usr/lib/python3.7/_bootlocale.py
# code object from '/usr/lib/python3.7/__pycache__/_bootlocale.cpython-37.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0xf764e1ec>
# /usr/lib/python3.7/__pycache__/types.cpython-37.pyc matches /usr/lib/python3.7/types.py
# code object from '/usr/lib/python3.7/__pycache__/types.cpython-37.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0xf766006c>
# /usr/lib/python3.7/importlib/__pycache__/__init__.cpython-37.pyc matches /usr/lib/python3.7/importlib/__init__.py
# code object from '/usr/lib/python3.7/importlib/__pycache__/__init__.cpython-37.pyc'
# /usr/lib/python3.7/__pycache__/warnings.cpython-37.pyc matches /usr/lib/python3.7/warnings.py
# code object from '/usr/lib/python3.7/__pycache__/warnings.cpython-37.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0xf76609ec>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0xf766014c>
# /usr/lib/python3.7/importlib/__pycache__/util.cpython-37.pyc matches /usr/lib/python3.7/importlib/util.py
# code object from '/usr/lib/python3.7/importlib/__pycache__/util.cpython-37.pyc'
# /usr/lib/python3.7/importlib/__pycache__/abc.cpython-37.pyc matches /usr/lib/python3.7/importlib/abc.py
# code object from '/usr/lib/python3.7/importlib/__pycache__/abc.cpython-37.pyc'
# /usr/lib/python3.7/importlib/__pycache__/machinery.cpython-37.pyc matches /usr/lib/python3.7/importlib/machinery.py
# code object from '/usr/lib/python3.7/importlib/__pycache__/machinery.cpython-37.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader object at 0xf76693cc>
import 'importlib.abc' # <_frozen_importlib_external.SourceFileLoader object at 0xf76659ac>
# /usr/lib/python3.7/__pycache__/contextlib.cpython-37.pyc matches /usr/lib/python3.7/contextlib.py
# code object from '/usr/lib/python3.7/__pycache__/contextlib.cpython-37.pyc'
# /usr/lib/python3.7/collections/__pycache__/__init__.cpython-37.pyc matches /usr/lib/python3.7/collections/__init__.py
# code object from '/usr/lib/python3.7/collections/__pycache__/__init__.cpython-37.pyc'
# /usr/lib/python3.7/__pycache__/operator.cpython-37.pyc matches /usr/lib/python3.7/operator.py
# code object from '/usr/lib/python3.7/__pycache__/operator.cpython-37.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0xf7607dcc>
# /usr/lib/python3.7/__pycache__/keyword.cpython-37.pyc matches /usr/lib/python3.7/keyword.py
# code object from '/usr/lib/python3.7/__pycache__/keyword.cpython-37.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0xf760c3cc>
# /usr/lib/python3.7/__pycache__/heapq.cpython-37.pyc matches /usr/lib/python3.7/heapq.py
# code object from '/usr/lib/python3.7/__pycache__/heapq.cpython-37.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0xf7610acc>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.7/__pycache__/reprlib.cpython-37.pyc matches /usr/lib/python3.7/reprlib.py
# code object from '/usr/lib/python3.7/__pycache__/reprlib.cpython-37.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0xf761522c>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0xf75f486c>
# /usr/lib/python3.7/__pycache__/functools.cpython-37.pyc matches /usr/lib/python3.7/functools.py
# code object from '/usr/lib/python3.7/__pycache__/functools.cpython-37.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0xf7615eec>
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0xf766904c>
import 'importlib.util' # <_frozen_importlib_external.SourceFileLoader object at 0xf7660dac>
# possible namespace for /usr/lib/python3/dist-packages/logilab
# destroy mpl_toolkits
# /usr/lib/python3.7/__pycache__/sitecustomize.cpython-37.pyc matches /usr/lib/python3.7/sitecustomize.py
# code object from '/usr/lib/python3.7/__pycache__/sitecustomize.cpython-37.pyc'
import 'sitecustomize' # <_frozen_importlib_external.SourceFileLoader object at 0xf75f4f2c>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0xf769c7ec>
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
python3: can't open file './test_microphone': [Errno 2] No such file or directory
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _thread
# cleanup[2] removing _warnings
# cleanup[2] removing _weakref
# cleanup[2] removing zipimport
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing posix
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing codecs
# cleanup[2] removing _codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing io
# destroy io
# cleanup[2] removing abc
# cleanup[2] removing _abc
# cleanup[2] removing site
# destroy site
# cleanup[2] removing os
# cleanup[2] removing stat
# cleanup[2] removing _stat
# cleanup[2] removing posixpath
# cleanup[2] removing genericpath
# cleanup[2] removing os.path
# cleanup[2] removing _collections_abc
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing _locale
# cleanup[2] removing types
# cleanup[2] removing importlib
# destroy importlib
# cleanup[2] removing importlib._bootstrap
# cleanup[2] removing importlib._bootstrap_external
# cleanup[2] removing warnings
# cleanup[2] removing importlib.util
# cleanup[2] removing importlib.abc
# cleanup[2] removing importlib.machinery
# cleanup[2] removing contextlib
# destroy contextlib
# cleanup[2] removing collections
# destroy collections
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing _operator
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing heapq
# cleanup[2] removing _heapq
# cleanup[2] removing itertools
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing functools
# cleanup[2] removing _functools
# cleanup[2] removing logilab
# destroy logilab
# cleanup[2] removing mpl_toolkits
# destroy mpl_toolkits
# cleanup[2] removing sitecustomize
# destroy sitecustomize
# destroy zipimport
# destroy _signal
# destroy _sitebuiltins
# destroy posixpath
# destroy _stat
# destroy genericpath
# destroy os
# destroy stat
# destroy _locale
# destroy importlib.util
# destroy importlib.abc
# destroy functools
# destroy types
# destroy importlib.machinery
# destroy warnings
# destroy abc
# destroy _collections_abc
# destroy heapq
# destroy _operator
# destroy _heapq
# destroy itertools
# destroy _collections
# destroy _abc
# destroy _functools
# cleanup[3] wiping _frozen_importlib
# destroy _frozen_importlib_external
# cleanup[3] wiping _imp
# cleanup[3] wiping _thread
# cleanup[3] wiping _warnings
# cleanup[3] wiping _weakref
# cleanup[3] wiping _io
# cleanup[3] wiping marshal
# cleanup[3] wiping posix
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping importlib._bootstrap
# cleanup[3] wiping sys
# cleanup[3] wiping builtins

**Comment by ludwigsaux** [comment]
[texte.txt](https://github.com/alphacep/vosk-api/files/5872337/texte.txt)

Here is the command : python3 -v ./test_microphone

I reinstall vosk but I have the same error

**Comment by nshmyrev** [comment]
> python3 -v ./test_microphone

Try

python3 -v ./test_microphone.py

**Comment by ludwigsaux** [comment]
[text.txt](https://github.com/alphacep/vosk-api/files/5872749/text.txt)

I did the command with test_microphone.py

Thank you for your help and your time ! :)

**Comment by ludwigsaux** [comment]
I forgot to say that, I'm using raspberry os (not arm but x86) on virtualBox. Could it be the problem ?
