### ISSUE TITLE
installing on windows by c# or visual studio build

### ISSUE THREAD

**Issue by problemSolvingProgramming** [alphacep/vosk-api#379]
How can I compile or build vosk api in Windows environment in Visual Studio C #? I know it only runs in Linux, am I looking for a way I can build it myself, or if so, can you tell me?
I used negut .package . but unfortunately I got an error.
Is there a program or sample for using Wesk through the microphone in C #?

**Comment by nshmyrev** [comment]
You already created issue about it before:

https://github.com/alphacep/vosk-api/issues/362

There is no need to open issues again and again.

Same problem is tracked here:

https://github.com/alphacep/vosk-api/issues/325

please be patient.
