### ISSUE TITLE
Pip install not working on Raspbian

### ISSUE THREAD

**Issue by mipotapenko** [alphacep/vosk-api#384]
Hello,

I am having trouble installing the vosk module on Raspbian, please help.

pip3 version
`(speech-to-text) pi@raspberrypi:~/Public/.venv/speech-to-text/lib/python3.5/site-packages $ pip3 --version
pip 20.3.4 from /home/pi/Public/.venv/speech-to-text/lib/python3.5/site-packages/pip (python 3.5)
`

python3 version
`python3 --version
Python 3.5.3
`

hardware info
`    description: ARMv7 Processor rev 4 (v7l)
    product: Raspberry Pi 3 Model B Rev 1.2
    serial: 000000007f678c86
    width: 32 bits
    capabilities: smp
`

install output
`pip3 install vosk
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement vosk
ERROR: No matching distribution found for vosk
`

I saw in another issue that Python3 needs to be 64 bit. Is that the reason I am having this error and if so, does that mean I will need another model of RPI to use this API?

Thanks,
Mikhail Potapenko

**Comment by nshmyrev** [comment]
It says python 3.5 reached end of life, you need to upgrade python.

**Comment by mipotapenko** [comment]
Could you let me know if 64 bit Python is a requirement? apt does not update past 3.5 for me which I think means I would have to build from source. If I need 64 bit Python to run this then I will order a different RPI model and not bother upgrading Python on this machine.

Also, I am not convinced that error message is requiring me to upgrade Python. It only says that Python 3.5 is not maintained any longer, but I'm not sure this means that the packages which are indexed for it should no longer be available. For instance, I can still install pandas, numpy, etc. The message also explicitly mentions that only pip 20 and 21 will stop supporting it. However, I am using  pip 19. I'm OK trying the upgrade regardless but would prefer to do it only on the machine which can definitely run Vosk.

Thanks,
Mikhail

**Comment by nshmyrev** [comment]
> Could you let me know if 64 bit Python is a requirement?

No

> apt does not update past 3.5 for me which I think means I would have to build from source.

Probably your Raspbian is too old, default python on Raspbian Buster is 3.7

**Comment by mipotapenko** [comment]
You were right! Can't believe I didn't think to check that. In any case, it all works now, thanks for the help.
