### ISSUE TITLE
Adding config parameters in ivector folder

### ISSUE THREAD

**Issue by Michael95-m** [alphacep/vosk-api#386]
I'd like to ask a  question about where and how to add these ivector parameters in ivector folder.

- num-gselect
- min-post
- posterior-scale
- max-remembered-frames
- max-count
- greedy-ivector-extractor

**Comment by nshmyrev** [comment]
We hardcode these parameters for now, we might implement the code to read config from a file some time.

**Comment by Michael95-m** [comment]
@nshmyrev  Thanks for your reply! And I'd like to know one more thing. Are there any detailed reference for optimal parameter settings for **nnet3 chain** model to be used with **vosk api**?? I'm afraid that I didn't find anything about it. I want to use my pretrained chain model with vosk api. Can u also give any recommendation about the parameter configuration for a chain model.

**Comment by nshmyrev** [comment]
> Can u also give any recommendation about the parameter configuration for a chain model.

We wanted to release training recipe some time in the future but we didn't release it yet. For now you can check the parameters of the current models.

**Comment by Michael95-m** [comment]
@nshmyrev , where can I check? Can u show me example chain model? And one more question please !!! Are there any arguments to add for chain model ( not wrong with simple nnet3) in python code.

**Comment by nshmyrev** [comment]
>  Can u show me example chain model?

https://alphacephei.com/vosk/models

> Are there any arguments to add for chain model 

No, we actually don't have that many configuration capabilities

**Comment by Michael95-m** [comment]
@nshmyrev , thank you.
