### ISSUE TITLE
Unable to build python module 

### ISSUE THREAD

**Issue by pga-avionics** [alphacep/vosk-api#387]
I'd need to compile vosk-api from scratch.
I followed the instructions to compile it from the [following link](https://alphacephei.com/vosk/install#kaldi-compilation-for-local-python-node-and-java-modules)
It succeeded.
However, as I try to build the **python module**, I realize that there is no "python" directory from the above resulting directory `/opt/kaldi/tools`

Should I checkout another github repo ?

**Comment by nshmyrev** [comment]
python folder is in the vosk-api package you clone from github. Here:

https://github.com/alphacep/vosk-api/tree/master/python

**Comment by pga-avionics** [comment]
Exactly...I didn't realize the vosk-api link wasn't in the docker lines.
Worked perfectly.
