### ISSUE TITLE
Creating a control/command oriented language-model

### ISSUE THREAD

**Issue by pga-avionics** [alphacep/vosk-api#388]
I've been using PocketSphinx previously with a custom dictionnary and lm focused on control/command target.
I was previously using the Webservice for creating a valid language model based on a corpus text file.

Now I've setup a vosk-api environment, I'm wondering what tool to use for creating such a feature ?
What is the guideline ?

**Comment by nshmyrev** [comment]
We support variety of adaptation methods from dynamic configuration with phrases to static graph rebuild, see

https://alphacephei.com/vosk/adaptation

for details
