### ISSUE TITLE
KWS 

### ISSUE THREAD

**Issue by d-pluschaev** [alphacep/vosk-api#389]
Hello Nikita! 
I know you are a busy person doing lots of cool things, but maybe you'll find some time to implement KWS in Vosk API, like in the Kaldi example https://github.com/kaldi-asr/kaldi/pull/3467/files#diff-a4a6dfc55684dba14292dce1204dba19769651cfb606ba5b61f716e9ccd4f7e6R47
I'm using Vosk API and used Pocket sphinx before for home automation and really appreciate what you're doing for opensource speech recognition technologies.

**Comment by nshmyrev** [comment]
Thank you for your request.

We will work on it once time permits. 

The original issue is tracked here https://github.com/alphacep/vosk-api/issues/107
