### ISSUE TITLE
Process killed when launching G.carpa

### ISSUE THREAD

**Issue by ludwigsaux** [alphacep/vosk-api#394]
Hi ! 
I have a problem with my raspberry, my process is killed when i lauch it. It seems like I don't have enough ram on my raspberry.
Is there a solution to avoid that ?
I'm running with a 3B+ with the right version of python and pip.
Thank you !

**Comment by nshmyrev** [comment]
It goes out of memory, you can use smaller models like lgraph one.

**Comment by ludwigsaux** [comment]
I can't use them, I need a french model and when I use the other model by Paul Guyot I have an error with kaldi.
I don't know kaldi and how to use it

**Comment by nshmyrev** [comment]
>  I have an error with kaldi

What error exactly?

**Comment by ludwigsaux** [comment]
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError

**Comment by ahmedalbahnasawy** [comment]
@ludwigsaux make sure when you build your Dockerfile that 'workdir' should be like model/conf/mfcc.conf if you already have conf, am, graph, ivector folders.
