### ISSUE TITLE
speaker recognition time info

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#396]
I want to know how to get the speaker time `start `and `end` while using speaker recognition. 
Here is the command in your example

if 'spk' in res:
            distance = ("Speaker_distance", cosine_dist(spk_sig , res['spk']))

so, how can I get this info from `res` in FinalResult ?

**Comment by nshmyrev** [comment]
res has words fields, you can get start of the first word and end of the last word

**Comment by Tortoise17** [comment]
thank you
