### ISSUE TITLE
Accuracy varies with audio clip length

### ISSUE THREAD

**Issue by harshitazilen** [alphacep/vosk-api#398]
When I split my audio clip to smaller chunks, the transcription result gets changed. 

**Filename:** user_single_answer.wav
**User Speech Transcription:** yeah

**Filename:** user_single_chunk.wav
**User Speech Transcription:** it is

Please find attached audio file for the same.
[audio_clips.zip](https://github.com/alphacep/vosk-api/files/5923991/audio_clips.zip)

**Comment by nshmyrev** [comment]
More or less same as https://github.com/alphacep/vosk-api/issues/309
