### ISSUE TITLE
Vosk for iOS does not work for armv7

### ISSUE THREAD

**Issue by bragimobile** [alphacep/vosk-api#399]
Hi Vosk Team,

First of all, thank you for your great effort and support. Already we talked about this issue with Nickolay but I wanted to create a ticket for tracking the situation. 

Problem:

- Xcode is able to compile a project for a simulator.
- If I select Any iOS device – Xcode outputs: libkaldiwrap.a(vosk_api.o)' does not contain bitcode.
- If I disable bitcode in the project settings for VoskApiTest target, Xcode outputs the same  `Undefined symbols for architecture armv7` error that I sent in the previous letter.

Is it possible to provide universal library with bitcode enabled? Thanks

**Comment by nshmyrev** [comment]
This should be fixed in new release
