### ISSUE TITLE
[Documentation] Add a list of supported models to the readme

### ISSUE THREAD

**Issue by cjbassi** [alphacep/vosk-api#40]
I think it would be good to give users options for which models they can use along with the pros and cons of each. So add the models from https://github.com/alphacep/vosk-server.

Also, it would probably be good to document the model format and how to create your own or convert one of the official kaldi models.

edit: Just noticed https://github.com/alphacep/vosk-api/blob/master/doc/model.md which is related.

**Comment by nshmyrev** [comment]
Great idea, I will work on it next week.

**Comment by nshmyrev** [comment]
Should be fixed with https://github.com/alphacep/vosk-api/blob/master/doc/models.md

**Comment by cjbassi** [comment]
This looks really great! Thanks!
