### ISSUE TITLE
Models 

### ISSUE THREAD

**Issue by doublex** [alphacep/vosk-api#400]
This page lists some new kaldi-models:
https://github.com/synesthesiam/voice2json-profiles

E.g. bigger model for Italian + Spanish 
Korean, Czech + Swedish

Best wishes!

**Comment by nshmyrev** [comment]
Hi @doublex 

Some extra models there are from Montreal Forced alignment project, they are not compatible with Vosk (GMM instead of DNN architecture) and not very accurate. That is why we don't include them.

Czech model might be interesting to include probably, others are not that good.

**Comment by doublex** [comment]
Ahh sorry. 
You knew them.

**Comment by nshmyrev** [comment]
Yes, I'm tracking Rhasspy news, hopefully we can benefit from it
