### ISSUE TITLE
Multiple KaldiRecognizer instances share same Model

### ISSUE THREAD

**Issue by hyansuper** [alphacep/vosk-api#402]
I am using the Python api.
My case is that I have mutiple KaldiRecognizer instances to recognize speech from seperate sound sources of same language(english).
Is it a good idea for different KaldiRecognizer instances to use same Model? will this save memory space? or will they interfere each other?
Thank you

**Comment by nshmyrev** [comment]
> Is it a good idea for different KaldiRecognizer instances to use same Model? 

Yes

> will this save memory space? 

Yes

>or will they interfere each other?

No

We use many recognizers for a single model in vosk-server, you can check there for details
