### ISSUE TITLE
Windows 10   Python 3.8.7 x64 vosk 0.3.18  OSError: cannot load library 'libvosk.dll': error 0x7e

### ISSUE THREAD

**Issue by fi-da** [alphacep/vosk-api#403]
Hi, I''ve used Vosk for months in Windows 10 and now updating to 0.3.18 I'm getting this error:
```
Traceback (most recent call last):
  File "test_words.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer
  File "C:\Users\fdavalli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\vosk\__init__.py", line 17, in <module>
    _c = open_dll()
  File "C:\Users\fdavalli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\vosk\__init__.py", line 9, in open_dll
    return _ffi.dlopen("libvosk.dll")
OSError: cannot load library 'libvosk.dll': error 0x7e
```
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32

Please any hint?

Thanks a lot

**Comment by nilavdas123** [comment]
same!! today i got the fix its easy , first uninstall the first one ( pip uninstall vosk) now just  downgrade your vosk to 0.3.7 by pip install vosk==0.3.7

**Comment by nshmyrev** [comment]
> same!! today i got the fix its easy , first uninstall the first one ( pip uninstall vosk) now just downgrade your vosk to 0.3.7 by pip install vosk==0.3.7

0.3.7 is not a great idea

**Comment by nilavdas123** [comment]
> > same!! today i got the fix its easy , first uninstall the first one ( pip uninstall vosk) now just downgrade your vosk to 0.3.7 by pip install vosk==0.3.7
> 
> 0.3.7 is not a great idea

yes but in pypi u can't install the previous biuld idk why! you can install  only 2 biulds that is 0.3.18 and 0.3.7

**Comment by nilavdas123** [comment]
> > > same!! today i got the fix its easy , first uninstall the first one ( pip uninstall vosk) now just downgrade your vosk to 0.3.7 by pip install vosk==0.3.7
> > 
> > 
> > 0.3.7 is not a great idea
> 
> yes but in pypi u can't install the previous biuld idk why! you can install only 2 biulds that is 0.3.18 and 0.3.7

ERROR: Could not find a version that satisfies the requirement vosk= 0.3.14(from versions: 0.3.7, 0.3.18)

**Comment by nshmyrev** [comment]
@fi-da Try to add 

```C:\Users\fdavalli\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\vosk\```

to system PATH and see if it works.

**Comment by nshmyrev** [comment]
@fi-da also let me know your cffi version

**Comment by fi-da** [comment]
Meanwhile I tried Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32 with the same result
Adding the vosk path to the PATH variable doesn't work 
I also forced the path on __init_.py  

cffi version is 1.14.5

**Comment by nshmyrev** [comment]
Download dependencywalker an check if there are some unresolved dependencies for libvosk.dll

**Comment by fi-da** [comment]
Dependencywalker returns a list of API-MS-WIN-CORE-XXX.DL, like in this post:

https://ofekshilon.com/2016/03/27/on-api-ms-win-xxxxx-dll-and-other-dependency-walker-glitches/

Unfortunately there's not direct evidence of a missing dll.

Is libvosk.dll built with msvc? Does it require vc runtime?

The nuget package contains a different set of:

libgcc_s_seh-1.dll
libstdc++-6.dll
libvosk.dll
libwinpthread-1.dll

and it works without issues.
It seems an issue cffi related

**Comment by nshmyrev** [comment]
> The nuget package contains a different set of:
```
libgcc_s_seh-1.dll
libstdc++-6.dll
libvosk.dll
libwinpthread-1.dll
```

what is the difference exactly? They should be the same.

People hint me that it might be related to other libraries in the path. Try to change this line in `__init__.py`

        os.environ["PATH"] += os.pathsep + os.path.dirname(__file__)

to 

        os.environ["PATH"] = os.path.dirname(__file__) + os.pathsep + os.environ["PATH"]

hopefully it will work.

**Comment by fi-da** [comment]
Thanks a lot Nickolay for your help, unfortunately the dll still doesn't load.
I noticed the dlls have different size:

NuGet x64 0.3.18 vs Pypi 0.3.18
libgcc_s_seh-1.dll  592 kb vs 1,15 MB
libstdc++-6.dll 25,3 MB vs 18,5 MB
libvosk.dll 24,4 MB vs 23,8 MB
libwinpthread-1.dll 358 KB vs 578 KB

**Comment by nshmyrev** [comment]
Ok, if you put the dlls from nuget into python folder, do they load?

**Comment by fi-da** [comment]
Not working, already tried
Never used cffi, does it have to be initialized in order to read environment variables ?
Some googling points to ffi.cdef()

**Comment by nshmyrev** [comment]
Ok, can you try one more thing, in the same place before dlopen add

     os.add_dll_directory(os.path.dirname(__file__))

Or just specify the path with dlls.

**Comment by fi-da** [comment]
Nickolay Shmyrev, you are a genius
Works smoothly

**Comment by nshmyrev** [comment]
hm, now the task is to figure out why python sometimes require path, sometimes dll directory

**Comment by fi-da** [comment]
This was triggering the error:

```
import` ctypes.util
path = ctypes.util.find_library(name)
```

**Comment by nshmyrev** [comment]
I have pushed https://pypi.org/project/vosk/0.3.21/, please try if it fixes the problem.

**Comment by fi-da** [comment]
Perfect! it works well

**Comment by nshmyrev** [comment]
ok, thank you for your help in debugging
