### ISSUE TITLE
 use the Speaker identification model vosk api  in C # 

### ISSUE THREAD

**Issue by problemSolvingProgramming** [alphacep/vosk-api#409]
Hello
How can I use the Speaker identification model vosk api  in C # environment using C # via microphone? Is there an example I can use this model?

**Comment by nshmyrev** [comment]
It is the same as in Python. See here:

https://github.com/alphacep/vosk-api/blob/2f4124eb663e39e6beeb8195b044862d2ab79aa5/csharp/demo/VoskDemo.cs#L51

**Comment by problemSolvingProgramming** [comment]
@nshmyrev  Hi thanks . But unfortunately I am not familiar with C #. Please write a sample program in C # that receives the sound through a microphone and then uses the Speaker identification model .

**Comment by nshmyrev** [comment]
> Please write a sample program in C # that receives the sound through a microphone and then uses the Speaker identification model .

You can find developers on freelancer website ;)
