### ISSUE TITLE
zamia model not working 

### ISSUE THREAD

**Issue by sciai-ai** [alphacep/vosk-api#410]
Hi,

I am trying to use vosk for zami model: kaldi-generic-en-tdnn_fl-r20190609.tar.xz

I have rearranged the folder structure so the files ca be located, however I  think something is still no right as seen in the log.

LOG (VoskAPI:ReadDataFiles():model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0332391 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:221) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:239) Reading CMVN stats from model/global_cmvn.stats
LOG (VoskAPI:ReadDataFiles():model.cc:246) Loading HCLG from model/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:265) Loading words from model/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:273) Loading winfo model/word_boundary.int
ERROR (VoskAPI:OnlineTransform():online-feature.cc:533) Dimension mismatch: source features have dimension 91 and LDA #cols is 280
terminate called after throwing an instance of 'kaldi::KaldiFatalError'

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/101

You used mfcc.conf, you should use mfcc_hires.conf.

**Comment by sciai-ai** [comment]
Thanks @nshmyrev it works but does not produce the right output as the text comes out to be empty. I used the same model with the same wav file in pykaldi and can get the output and now wanted to migrate to vosk

LOG (VoskAPI:ReadDataFiles():model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0339031 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:221) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:239) Reading CMVN stats from model/global_cmvn.stats
LOG (VoskAPI:ReadDataFiles():model.cc:246) Loading HCLG from model/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:265) Loading words from model/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:273) Loading winfo model/word_boundary.int
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
