### ISSUE TITLE
Behaviour Android Demo app and General question grammar

### ISSUE THREAD

**Issue by SelwynJ** [alphacep/vosk-api#411]
Hello @nshmyrev thank you for your effort in the VOSK library, i am very impressed with its accuracy, ive done a pocketsphinx project in the past and now I would like to upgrade to VOSK/Kaldi

I played around a bit with the Android demo, one thing I noticed is when I use a grammar JSON string to define a domain of possible words the partial result comes up with the next word in line:

"[\"one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen twenty double triple bull bullseye twenty thirty forty fifty sixty seventy eighty ninety hundred\"]");

https://youtu.be/XMBtKwUoM2w

This however does not happen when I leave the grammar string empty.

Second question: in Pocketsphinx it was possible to specify a JSGF with possible outcomes in the word recognition. I would like to have triple twenty, double fifteen as valid detections but exclude for example triple 80. (I think you can see where I am going with this :P) Is something like that possible in VOSK, what other options are available using the grammar JSON file except for word domain definitition? I have tried the path of doing my own compilation but I really lack the knowledge on that part, dont think I will have anything working there soon.

thankyou
Greetings,

**Comment by nshmyrev** [comment]
>  partial result comes up with the next word in line:

If you want to recognize isolated words you need to specify them isolated in a list of phrases:

    "[\"one\", \"two\", \"three\", \"four\"]");

> it was possible to specify a JSGF with possible outcomes in the word recognition

It is not possible to restrict the user in pronouncing triple 80 anyway, so you need to recognize everything, not necessary lines in your grammar and react accordingly. You can postprocess recognition results with regular expressions or more advanced framework. You can read for details:

https://github.com/alphacep/vosk-api/issues/55

https://github.com/cmusphinx/pocketsphinx/issues/13

**Comment by SelwynJ** [comment]
Thanks for your  feedback.
