### ISSUE TITLE
zamia model not producing output 

### ISSUE THREAD

**Issue by sciai-ai** [alphacep/vosk-api#412]
Thanks @nshmyrev #410 the model does t=run but is not producing any output, most partials are empty and the final text is always empty. Somehow the input is getting truncated? I have run the test.wav as well as a few other files but they all show the same pattern

it works but does not produce the right output as the text comes out to be empty. I used the same model with the same wav file in pykaldi and can get the output and now wanted to migrate to vosk

LOG (VoskAPI:ReadDataFiles():model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0339031 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:221) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:239) Reading CMVN stats from model/global_cmvn.stats
LOG (VoskAPI:ReadDataFiles():model.cc:246) Loading HCLG from model/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:265) Loading words from model/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:273) Loading winfo model/word_boundary.int
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{
"partial" : ""
}
{

**Comment by nshmyrev** [comment]
> Reading CMVN stats from model/global_cmvn.stats

I don't think Zamia supports global_cmvn.stats, you should have placed this file accidentally. In general, you can use already prepared Zamia model from our downloads, it will work:

https://alphacephei.com/vosk/models/vosk-model-small-de-zamia-0.3.zip

Btw, our model is much faster and accurate than Zamia:

https://alphacephei.com/vosk/models/vosk-model-small-de-0.15.zip

**Comment by sciai-ai** [comment]
1. yes, removing the global stats works fine. I am working with EN models, is the vosk large EN model better than the zamia one too?

2. Is there a way I can further improve the accuracy of the model, for example, if latency is not a concern for me is there any parameter I can change to further boost performance. I understand that vosk implements the look ahead FST model, is that being used in the backend even for the zamia model.

**Comment by nshmyrev** [comment]
> is the vosk large EN model better than the zamia one too?

Yes

>  is there any parameter I can change to further boost performance

It depends on many factors, you can read https://alphacephei.com/vosk/accuracy for details
