### ISSUE TITLE
Running vosk without ivectors

### ISSUE THREAD

**Issue by pourfard** [alphacep/vosk-api#413]
Hi,

I read [model.cc](https://github.com/alphacep/vosk-api/blob/b92a5c1fc7303e545d0c90183ba52363cc55a87d/src/model.cc#L235) and realized that if we do not provide ivector/final.ie in our model directory then `use_ivectors` will be false.

`feature_info_.use_ivectors = false;`

But when I do this, I get this error:

```
ERROR (VoskAPI:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:50) Ivector feature dimension mismatch: got -1 but network expects 30
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
```

Is there any way to use vosk-api without having ivectors?

**Comment by nshmyrev** [comment]
If you want to run without ivectors you need a model (final.mdl) trained without ivectors. Your model still require ivector of size 30.

**Comment by pourfard** [comment]
Thanks,
 
It worked with a model which was trained without ivectors.
