### ISSUE TITLE
example/test_text.py 

### ISSUE THREAD

**Issue by sova32** [alphacep/vosk-api#414]
/media/vadiki/D_238_GB_WD/vosk_kaldi/vosk-api/python/example/test_text.py 
LOG (VoskAPI:ReadDataFiles():model.cc:194) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0535219 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:221) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:251) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:273) Loading winfo model/graph/phones/word_boundary.int
Traceback (most recent call last):
  File "/media/vadiki/D_238_GB_WD/vosk_kaldi/vosk-api/python/example/test_text.py", line 21, in <module>
    wf = open(sys.argv[1], "rb")
IndexError: list index out of range

**Comment by nshmyrev** [comment]
It says you need to specify the argument (input file text.wav). Same as https://github.com/alphacep/vosk-api/issues/416

**Comment by sova32** [comment]
> В нем говорится, что вам нужно указать аргумент (входной файл text.wav). То же, что [# 416](https://github.com/alphacep/vosk-api/issues/416)

How am I supposed to understand this? Why is there no normal documentation anywhere?
Speech recognition is just awful and recognizes in chunks. Errors are 90%, both in large and small models, regardless of the quality of the microphone. How can I recognize commands and convert them to text, or even better send to ip: port in python or C? I've been breaking my head for over a month !!!

**Comment by sova32** [comment]
где это сказано?

**Comment by nshmyrev** [comment]
>  I've been breaking my head for over a month !!!

Feels like you just downloaded the software today ;)

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/405

**Comment by sova32** [comment]
> > Голову ломаю уже больше месяца !!!
> 
> Похоже, вы только что скачали программу сегодня;)


кажется - креститься надо!
Вместо того чтобы умничать объяснили бы нормально, а не посылали закрывая тему!
