### ISSUE TITLE
Execution failed for task ':kaldi'. 

### ISSUE THREAD

**Issue by stellis7** [alphacep/vosk-api#415]
I downloaded the files for the project and proceeded to open the Android Studio project but I was getting an error from the Cmake after resolving that however I now get the following error whenever I build my project: "Execution failed for task ':kaldi'. > Process 'command './build-kaldi.sh'' finished with non-zero exit value 2." I then decided to run the shell file for Kaldi in terminal and got this output "ANDROID_SDK_HOME environment variable is undefined, define it with local.properties or with export." But my sdk path has been the same for all previous projects with no issues. If you could take a look at the code or if you know a solution to my issue that would be greatly appreciated!
 

[Archive.zip](https://github.com/alphacep/vosk-api/files/5989340/Archive.zip)

**Comment by nshmyrev** [comment]
Please provide complete build output so I can check what is going on. The output must contain the error.
