### ISSUE TITLE
test_words.py

### ISSUE THREAD

**Issue by sova32** [alphacep/vosk-api#417]
python3 test_words.py test.wav 
LOG (VoskAPI:ReadDataFiles():model.cc:194) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0547779 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:221) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:251) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:273) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:68) ["oh one two three four five six seven eight nine zero", "[unk]"]
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'oh'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'one'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'two'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'three'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'four'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'five'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'six'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'seven'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'eight'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'nine'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: 'zero'
LOG (VoskAPI:Estimate():language_model.cc:142) Estimating language model with ngram-order=2, discount=0.5
LOG (VoskAPI:OutputToFst():language_model.cc:209) Created language model with 2 states and 2 arcs.
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "text" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "text" : ""
}

**Comment by nshmyrev** [comment]
There are warnings above that English words are missing in the model. If you are using non-English model, you need to modify the words in the code.

**Comment by sova32** [comment]
> There are warnings above that English words are missing in the model. If you are using non-English model, you need to modify the words in the code.

Эти о и есть мой словарь? что это за слова? объясните пожалуйста

**Comment by sova32** [comment]
> There are warnings above that English words are missing in the model. If you are using non-English model, you need to modify the words in the code.


Is this my dictionary? what are these words? can you explain please

**Comment by nshmyrev** [comment]
You can check the code here:

https://github.com/alphacep/vosk-api/blob/2f4124eb663e39e6beeb8195b044862d2ab79aa5/python/example/test_words.py#L19

also the API reference

https://github.com/alphacep/vosk-api/blob/2f4124eb663e39e6beeb8195b044862d2ab79aa5/src/vosk_api.h#L99

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/405

**Comment by sova32** [comment]
> Вы можете проверить код здесь:
> 
> https://github.com/alphacep/vosk-api/blob/2f4124eb663e39e6beeb8195b044862d2ab79aa5/python/example/test_words.py#L19
> 
> также справочник по API
> 
> https://github.com/alphacep/vosk-api/blob/2f4124eb663e39e6beeb8195b044862d2ab79aa5/src/vosk_api.h#L99

Простите, но я так и не понял, что это за слова. Мне их просто на руский перевести? Почему нельзя нормально объяснить?
