### ISSUE TITLE
Java bindings don't have speaker-model entrypoints

### ISSUE THREAD

**Issue by peterkronenberg** [alphacep/vosk-api#421]
Wanted to play with the speaker recognition (which I'm still trying to understand in general) with the Java bindings, but the sample code, DecoderTest, was missing the entry points to create the speaker model.  It looks like it was in the `dll` bindings, so I just added the entry points to the LibVosk INSTANCE.
 ```
 Pointer vosk_spk_model_new(String path);
 void vosk_spk_model_free(Pointer model);
 Pointer vosk_recognizer_new(Pointer model, Pointer spkModel, float sample_rate);
```

When running, it seems to just hang.

I tried upgrading the jna library from 4.5.0 to 5.7.0, which is the latest one.
However, I get an error while trying to run:
`ASSERTION_FAILED (VoskAPI:SubVector():matrix/kaldi-vector.h:512) Assertion failed: (static_cast<UnsignedMatrixIndexT>(origin)+ static_cast<UnsignedMatrixIndexT>(length) <= static_cast<UnsignedMatrixIndexT>(t.Dim()))`

Is there a reason this doesn't work with Java?

**Comment by nshmyrev** [comment]
> Pointer vosk_recognizer_new(Pointer model, Pointer spkModel, float sample_rate);

It should be 

`Pointer vosk_recognizer_new_spk(Pointer model, Pointer spkModel, float sample_rate);
`

with `_spk` for c function

**Comment by peterkronenberg** [comment]
Ah, ok thanks.  That's better.  In python, it looks like it's the same function.
Now I just have all my other questions about the speaker recognition :-)
