### ISSUE TITLE
test_words.py

### ISSUE THREAD

**Issue by sova32** [alphacep/vosk-api#423]
> Вы можете проверить код здесь:
> 
> https://github.com/alphacep/vosk-api/blob/2f4124eb663e39e6beeb8195b044862d2ab79aa5/python/example/test_words.py#L19
> 
> также справочник по API
> 
> https://github.com/alphacep/vosk-api/blob/2f4124eb663e39e6beeb8195b044862d2ab79aa5/src/vosk_api.h#L99

Простите, но я так и не понял, что это за слова. Мне их просто на русский перевести? Почему нельзя понятно объяснить? Потому что я глупый?

**Comment by LuggerMan** [comment]
Что тут непонятно? Что фраза из одного слова - тоже фраза? И к чьему комментарию этот комментарий в новом issue?
Да, на русский перевести. Все понятно обьяснено

**Comment by LuggerMan** [comment]
В данном случае указывается, что перегрузка метода vosk_recognizer_new может быть вызвана с доп. параметром, который ожидает JSON со списком слов и слов внутри фраз, ограничивающих словарь распознавания. 

//не стыдно не знать, стыдно не хотеть знать и не прилагать ровно никаких усилий для этого. ну серьезно, в гугл переводчик комменты засунуть - уже тему нужно создавать?

**Comment by LuggerMan** [comment]
@sova32 английских слов в русской модели распознавания нет, иди по адресу /model/graph/words.txt - там список слов, ограничивать соответственно только ими или перетренировывай модель

**Comment by nshmyrev** [comment]
Let us know if you have further questions
