### ISSUE TITLE
Requirements for input audio file

### ISSUE THREAD

**Issue by peterkronenberg** [alphacep/vosk-api#424]
@nshmyrev I know that the documentation says that the file must be 16khz.  However, what is the purpose of passing the sample rate to the KaldiRecognizer?   In the examples, it is always hard-coded to 16000.   If I try to pass a file that matches the sample rate I pass in (such as 8000), it doesn't work.  I get an error about specifying the `--allow_{upsample,downsample}` option, but that appears to be a Kaldi option, not Vosk.  Why do we have to pass the sample rate if it is always 16000?

**Comment by LuggerMan** [comment]
@peterkronenberg i`m not confident, but think this is for future of develoment purpose, Currently only 16kHz is supported because all models are trained on 16kHz, but maybe in the future you could train model on let's say 32kHz and then specify another rate.

**Comment by peterkronenberg** [comment]
Ok, I guess that makes sense.  Would probably be better to just have an overloaded method that defaulted to 16000 so you don't have to specify it.  Having to specify it makes it seems like it has meaning and then you just end up getting an error

**Comment by LuggerMan** [comment]
@peterkronenberg u can do just that, but i, for instance, like the occam`s razor principle of this lib

**Comment by nshmyrev** [comment]
Same as #967. We need better docs and also more checks in the code
