### ISSUE TITLE
Typesafe Java bindings

### ISSUE THREAD

**Issue by peterkronenberg** [alphacep/vosk-api#427]
@nshmyrev , I re-wrote the Java interface to be more typesafe, support auto-closing via try-with-resource and conform to Java naming conventions.  Feel free to include with your examples
(System won't let me attach Java files, so I renamed to *.log)

[LibVosk.log](https://github.com/alphacep/vosk-api/files/5997289/LibVosk.log)
[DecoderTypeSafe.log](https://github.com/alphacep/vosk-api/files/5997290/DecoderTypeSafe.log)

**Comment by nshmyrev** [comment]
Great! Looks cool. 

You'd better submit a pull request.

**Comment by peterkronenberg** [comment]
Pull request has been submitted and it looks like it has successfully built

**Comment by nshmyrev** [comment]
https://github.com/alphacep/vosk-api/pull/429 has been merged actually
