### ISSUE TITLE
Differences in the models

### ISSUE THREAD

**Issue by peterkronenberg** [alphacep/vosk-api#432]
Wondering if anyone has any insight on the different models available at https://alphacephei.com/vosk/models.  For example, for English there is `vosk-model-small-en-us-0.15`, which is only 40Mb and then there is `vosk-model-en-us-aspire-0.2`, which is 1.4Gb I'm not necessarily looking for technical details on how they were created.  But more practical differences.   I'm running in a server environment, so storage space is not an issue.  Is the bigger one going to be more accurate?  Any downsides?
It's similar with most of the other languages.  There is a smaller one that's about 40-50Mb and a larger one.  So how do I decide which one to use?  Under what circumstances would you use one rather than the other?

What does `wideband` and `narrowband` mean in this context?  Does `narrowband` mean accurate but only for a limited domain?

**Comment by LuggerMan** [comment]
hi. the small model is for mobile use, it has a dynamic graph and worse accuracy, if u do a server, use a big one (no downsides)

**Comment by peterkronenberg** [comment]
Using the large ones does seem to take longer.  Do you know if there are any quantitative measurements that show how much more accurate it is?

**Comment by nshmyrev** [comment]
> Do you know if there are any quantitative measurements that show how much more accurate it is?

There is a column named "Word error rate" in the table on the page you linked.

**Comment by peterkronenberg** [comment]
Ok, I wasn't totally sure what the references mean to librisspeech and tedlium. But if I'm reading it correctly, it seems to say that the bigger model has a higher error rate.  Is that correct?  That's why I ask what the advantage is to the bigger model?  It seems to take about 3 times longer using the bigger model, but not any more accurate

**Comment by nshmyrev** [comment]
We have now generic good model both for callcenter and wide-band decoding http://alphacephei.com/vosk/models/vosk-model-en-us-0.22.zip, so this aspire question is not relevant anymore.

**Comment by bcatdc** [comment]
I have a similar question. I'm very new to NLP and trying to understand what is meant on the model page by "Word error rate/Speed." After some research, I now understand that the parentheticals like (tedlium) are corpuses of transcribed audio, and I've read the entry on WER in wikipedia, but what does the denominator "speed" mean? Something about how fast the speaker talks, or how quickly the processor parses the audio? Thanks in advance!  (edited because, I found Word Error Rate on wikipedia)

**Comment by KJ7LNW** [comment]
@bcatdc, this is a guess, I don't actually know:  but perhaps it is the word error rate divided by the speed of the detection? 

If so then it is a sort of performance metric...but I would think that having those two values independently would be more useful.  For example, if it is super-fast but has a high error rate, then the "score" might be lower...even though I would (probably) prefer a slower rate in favor of more accuracy.
