### ISSUE TITLE
Integrate with nodeJS api

### ISSUE THREAD

**Issue by SahnounM91** [alphacep/vosk-api#433]
I'm  trying to integrate vosk with nodejs API, I need to receive a list of wav files and treat it one by one to get the text recognition for every one !

**Comment by nshmyrev** [comment]
Node demo is here:

https://github.com/alphacep/vosk-api/blob/master/nodejs/demo/demo.js

what is the problem you have using it exactly?

**Comment by nshmyrev** [comment]
Feel free to reopen if you have other questions.
