### ISSUE TITLE
Can I use the microphone for C#?

### ISSUE THREAD

**Issue by Jochen-sys** [alphacep/vosk-api#438]
Hello,

my problem is, that I can't find the file for transcribing with microphone for C#. The only files I can find are transcribing an audio file. Can anybody help me there? 

Another question which isn't so important, but I think also interesting: Is there an update for unity or is there a website I can follow how far the unity integration is away.

Sorry for my bad English, it isn't my real language.
I'm looking forward for any answers!

**Comment by nshmyrev** [comment]
> Can anybody help me there?

You need to try yourself first. Take the code that records audio and feed it into the recognizer. 
 
> Another question which isn't so important, but I think also interesting: Is there an update for unity or is there a website I can follow how far the unity integration is away.

We have no near plans to support Unity.

**Comment by Jochen-sys** [comment]
Ok first of all thanks your answers. I'll try to make it how you said!

Thanks also for the Unity information.

**Comment by Jochen-sys** [comment]
Another question: Where can I find the Vosk.dll or could you give me a link to it, because the different orders don't work?  I know that they should work and I'm making mistakes, but it is the easiest way to manually say me where I can find the dll.

**Comment by nshmyrev** [comment]
Inside nuget package:

https://www.nuget.org/packages/Vosk/0.3.19

**Comment by Jochen-sys** [comment]
Sadly I tried the commands, but for example when I try the following order:
Install-Package Vosk -Version 0.3.19
I get the error, that Version isn't a known paramter. When I try it without the Version I'm getting the error, that Vosk isn't known. 
But isn't there another link so I can get the dll without any command or shell order or whatever order?

**Comment by nshmyrev** [comment]
in command line `dotnet add package Vosk --version 0.3.19` should work

**Comment by Jochen-sys** [comment]
Ok this actually worked thanks. Ok so there is no real dll file I could see, it's inly this order who does the "magic"?

**Comment by nshmyrev** [comment]
dll is inside nupkg, you can unpack it with unzip and explore

**Comment by Jochen-sys** [comment]
And where is this nupkg? Sorry for the many questions!

**Comment by nshmyrev** [comment]
> And where is this nupkg? Sorry for the many questions!

Don't be sorry, just google before asking

**Comment by Jochen-sys** [comment]
Ouh yeah that's a very good idea! Ok thanks I got it!

**Comment by Jochen-sys** [comment]
In this comment https://github.com/alphacep/vosk-api/issues/438#issuecomment-784137101 you said I should take the code that records audio and feed it into the recognizer. But I already have the VoskRecognizer in the recording audio code. 
I tried to build the Python part which is doing the transcription into C#, but I don't know how I can create an RawInputStream in C#. Google didn't help much. Do you have something like that in your Vosk Code and I didn't see it?

**Comment by LuggerMan** [comment]
@Jochen-sys Do u have a memory buffer of the recorded audio? u obviously dont feed the code into recognizer, but that only buffer (size 3200 bytes) when u have recorded it. so your audio code yield a buffer, u supply it to AcceptWaveform function, and get results as usual

**Comment by Jochen-sys** [comment]
@LuggerMan So I have to create a stream which records the audio  for a buffersize of 3200 bytes and then transcribe this part? Ok but can I create such a stream? My idea was to use the Stream from C# used also in the example, but I don't know how to pass the microphone to the stream.

**Comment by LuggerMan** [comment]
@Jochen-sys u mean this snippet?

public static void DemoBytes(Model model)
   {
        // Demo byte buffer
        VoskRecognizer rec = new VoskRecognizer(model, 16000.0f);

        using(Stream source = File.OpenRead("test.wav")) {

            byte[] buffer = new byte[4096];

            int bytesRead;

            while((bytesRead = source.Read(buffer, 0, buffer.Length)) > 0) {

                if (rec.AcceptWaveform(buffer, bytesRead)) {

                    Console.WriteLine(rec.Result());

                } else {

                    Console.WriteLine(rec.PartialResult());

                }
            }
        }
        Console.WriteLine(rec.FinalResult());  }

u can basically replace that stream with any type u like. For microfone driver for c# u can use NAudio for example

**Comment by Jochen-sys** [comment]
Ok thanks I will google it and try it out.

**Comment by Jochen-sys** [comment]
@LuggerMan Sorry but could you possibly help me again? Nothing is working... I can't find a good "user manual" for NAudio or how to use the microphone for my case.

**Comment by LuggerMan** [comment]
@Jochen-sys https://github.com/naudio/NAudio/blob/master/Docs/AsioRecording.md maybe this? 
https://github.com/naudio/NAudio/blob/master/Docs/RecordWavFileWinFormsWaveIn.md or this? 
**https://stackoverflow.com/questions/24607351/recording-microphone-audio-using-naudio-in-a-console-application**
e.buffer

**Comment by Jochen-sys** [comment]
Sorry, but I don't think this is helping me really because they write the microhone to a wave file and they haven't specialised the buffer size. Maybe I'm very silly and in hour I would get it, but in the moment I don't know.

**Comment by LuggerMan** [comment]
@Jochen-sys look into it, deeper...
https://github.com/naudio/NAudio/blob/63c7011a7559cb55719e306dd3ab716b25e26d6a/NAudio.WinMM/WaveInEvent.cs#L15
line 83 - buffersize
to wave file or to acceptWaveform(); no difference kek

**Comment by Jochen-sys** [comment]
So I got something like that...., but it doesn't seem right:
WaveIn sourceStream;
Stream source;
void Main(){
         sourceStream = new WaveIn
          {
              DeviceNumber = 0,
              WaveFormat =
                  new WaveFormat(44100, 1)
          };
  
          sourceStream.DataAvailable += this.SourceStreamDataAvailable;
  
          sourceStream.StartRecording();
}
public void SourceStreamDataAvailable(object sender, WaveInEventArgs e)
{
        source.Write(e.Buffer, 0, e.BytesRecorded);
        source.Flush();
}
public static void DemoBytes(Model model)
   {
        // Demo byte buffer
        VoskRecognizer rec = new VoskRecognizer(model, 16000.0f);
        using(source) {
            byte[] buffer = new byte[4096];
            int bytesRead;
            while((bytesRead = source.Read(buffer, 0, buffer.Length)) > 0) {
                if (rec.AcceptWaveform(buffer, bytesRead)) {
                    Console.WriteLine(rec.Result());
                } else {
                    Console.WriteLine(rec.PartialResult());
                }
            }
        }
        Console.WriteLine(rec.FinalResult());
}

**Comment by ghost** [comment]
Here is a working realtime code using NAudio as input driver.
```
WaveInEvent waveIn = new WaveInEvent();
waveIn.DataAvailable += WaveInOnDataAvailable;
waveIn.StartRecording();

model = new Model(@"C:\Users\x\Desktop\vosk-model-en-us-daanzu-20200905");
rec = new VoskRecognizer(model, waveIn.WaveFormat.SampleRate);
```

and

```
    private void WaveInOnDataAvailable(object? sender, WaveInEventArgs e)
        {
            try
            {
              
                Dispatcher.Invoke(() =>
                {
                    try
                    {
                     //   writer.Write(e.Buffer, 0, e.BytesRecorded);
                        if (rec.AcceptWaveform(e.Buffer, e.Buffer.Length))
                        {
                            Result.Text = rec.Result();
                        }
                        else
                        {
                            Result.Text = rec.PartialResult();
                        }
                    }
                    catch (Exception exception)
                    {
                    }
  
                });
            }
            catch (Exception exception)
            {
            }
        }
```
the code is a part of some other projects so the code is not clean for a simple example but anyone will get the idea

**Comment by SiriBeta** [comment]
I am searching for a microphone capture solution in C#. It seems to be possible using NAudio, but so far VoskRecognizer behavior is quite strange. Recording at a sampling rate of 8000 causes an exception, when increasing it to 16000 VoskRecognizer accepts the stream, though with large errors in recognition.

**Comment by nshmyrev** [comment]
Unity support is tracked in #691

**Comment by maallain** [comment]
vosk-model-en-us-daanzu-20200905 work great but french model is not working.
rec.AcceptWaveform(e.Buffer, e.Buffer.Length) always true with empty data.

**Comment by nshmyrev** [comment]
> french model is not working

We have several of them, which one exactly? Also, try with smaller model first.

> always true with empty data

Please print the data values and share the log

**Comment by maallain** [comment]
I have try
vosk-model-small-fr-pguyot-0.3
and 
vosk-model-fr-0.6-linto-2.2.0

I initialize the VoskRecognizer like this.
rec = new VoskRecognizer(model, waveIn.WaveFormat.SampleRate);

rec.AcceptWaveform(e.Buffer, e.Buffer.Length) always true

rec.Result()
{"text": ""}

with the english model when rec.AcceptWaveform(e.Buffer, e.Buffer.Length) is true there is meaninful words.

**Comment by nshmyrev** [comment]
And what are the buffer values?

**Comment by maallain** [comment]
e.Buffer.Length = 1600
e.Buffer
new byte[] { 0, 0, 254, 255, 255, 255, 255, 255, 1, 0, 7, 0, 249, 255, 7, 0, 9, 0, 3, 0, 1, 0, 7, 0, 10, 0, 254, 255, 1, 0, 4, 0, 4, 0, 3, 0, 8, 0, 8, 0, 5, 0, 10, 0, 22, 0, 23, 0, 23, 0, 23, 0, 17, 0, 17, 0, 17, 0, 22, 0, 13, 0, 18, 0, 27, 0, 26, 0, 26, 0, 17, 0, 18, 0, 16, 0, 15, 0, 20, 0, 15, 0, 16, 0, 21, 0, 23, 0, 28, 0, 26, 0, 26, 0, 16, 0, 24, 0, 21, 0, 12, 0, 21, 0, 23, 0, 21, 0, 16, 0, 17, 0, 17, 0, 16, 0, 9, 0, 18, 0, 5, 0, 5, 0, 14, 0, 253, 255, 5, 0, 12, 0, 8, 0, 6, 0, 9, 0, 14, 0, 11, 0, 11, 0, 8, 0, 7, 0, 1, 0, 0, 0, 250, 255, 250, 255, 252, 255, 250, 255, 252, 255, 246, 255, 241, 255, 242, 255, 242, 255, 244, 255, 244, 255, 242, 255, 244, 255, 243, 255, 249, 255, 249, 255, 237, 255, 229, 255, 236, 255, 236, 255, 238, 255, 229, 255, 227, 255, 229, 255, 229, 255, 237, 255, 243, 255, 238, 255, 231, 255, 235, 255, 232, 255, 241, 255, 246, 255, 240, 255, 232, 255, 230, 255, 236, 255, 229, 255, 235, 255, 235, 255, 245, 255, 242, 255, 232, 255, 237, 255, 229, 255, 236, 255, 247, 255, 246, 255, 242, 255, 241, 255, 241, 255, 239, 255, 237, 255, 250, 255, 250, 255, 247, 255, 244, 255, 249, 255, 250, 255, 251, 255, 3, 0, 252, 255, 255, 255, 0, 0, 249, 255, 250, 255, 1, 0, 5, 0, 253, 255, 5, 0, 17, 0, 20, 0, 7, 0, 10, 0, 16, 0, 14, 0, 16, 0, 10, 0, 18, 0, 27, 0, 31, 0, 24, 0, 26, 0, 22, 0, 23, 0, 20, 0, 21, 0, 25, 0, 26, 0, 33, 0, 28, 0, 26, 0, 29, 0, 31, 0, 17, 0, 23, 0, 21, 0, 20, 0, 19, 0, 18, 0, 21, 0, 22, 0, 14, 0, 13, 0, 23, 0, 20, 0, 17, 0, 15, 0, 10, 0, 1, 0, 5, 0, 14, 0, 14, 0, 10, 0, 5, 0, 3, 0, 253, 255, 252, 255, 250, 255, 251, 255, 252, 255, 255, 255, 1, 0, 250, 255, 1, 0, 255, 255, 248, 255, 254, 255, 253, 255, 248, 255, 253, 255, 250, 255, 253, 255, 0, 0, 247, 255, 243, 255, 247, 255, 245, 255, 241, 255, 245, 255, 247, 255, 241, 255, 246, 255, 239, 255, 240, 255, 241, 255, 240, 255, 246, 255, 241, 255, 233, 255, 232, 255, 236, 255, 240, 255, 229, 255, 232, 255, 231, 255, 238, 255, 232, 255, 227, 255, 233, 255, 231, 255, 235, 255, 224, 255, 230, 255, 236, 255, 233, 255, 229, 255, 235, 255, 234, 255, 232, 255, 236, 255, 235, 255, 239, 255, 241, 255, 244, 255, 235, 255, 238, 255, 241, 255, 241, 255, 240, 255, 240, 255, 246, 255, 249, 255, 250, 255, 248, 255, 249, 255, 247, 255, 250, 255, 252, 255, 254, 255, 255, 255, 249, 255, 253, 255, 2, 0, 5, 0, 15, 0, 10, 0, 10, 0, 5, 0, 1, 0, 2, 0, 8, 0, 5, 0, 5, 0, 15, 0, 15, 0, 18, 0, 14, 0, 16, 0, 11, 0, 18, 0, 20, 0, 20, 0, 11, 0, 13, 0, 19, 0, 18, 0, 15, 0, 17, 0, 21, 0, 16, 0, 19, 0, 21, 0, 20, 0, 19, 0, 23, 0, 22, 0, 21, 0, 19, 0, 17, 0, 16, 0, 23, 0, 22, 0, 24, 0, 23, 0, 21, 0, 21, 0, 20, 0, 27, 0, 22, 0, 27, 0, 21, 0, 17, 0, 10, 0, 12, 0, 11, 0, 7, 0, 11, 0, 10, 0, 13, 0, 7, 0, 8, 0, 4, 0, 7, 0, 1, 0, 5, 0, 4, 0, 4, 0, 5, 0, 5, 0, 3, 0, 255, 255, 255, 255, 254, 255, 247, 255, 247, 255, 247, 255, 243, 255, 251, 255, 246, 255, 243, 255, 245, 255, 252, 255, 248, 255, 242, 255, 232, 255, 235, 255, 245, 255, 240, 255, 239, 255, 239, 255, 245, 255, 242, 255, 240, 255, 237, 255, 231, 255, 236, 255, 235, 255, 237, 255, 240, 255, 230, 255, 230, 255, 230, 255, 228, 255, 232, 255, 225, 255, 230, 255, 236, 255, 235, 255, 242, 255, 240, 255, 237, 255, 243, 255, 245, 255, 240, 255, 247, 255, 251, 255, 240, 255, 241, 255, 243, 255, 248, 255, 244, 255, 243, 255, 236, 255, 246, 255, 252, 255, 246, 255, 249, 255, 249, 255, 4, 0, 6, 0, 5, 0, 7, 0, 3, 0, 3, 0, 7, 0, 8, 0, 6, 0, 8, 0, 6, 0, 0, 0, 255, 255, 7, 0, 12, 0, 13, 0, 15, 0, 17, 0, 15, 0, 18, 0, 23, 0, 21, 0, 19, 0, 21, 0, 24, 0, 26, 0, 22, 0, 24, 0, 30, 0, 27, 0, 21, 0, 28, 0, 31, 0, 23, 0, 30, 0, 19, 0, 25, 0, 28, 0, 15, 0, 23, 0, 27, 0, 24, 0, 25, 0, 22, 0, 22, 0, 23, 0, 18, 0, 26, 0, 23, 0, 23, 0, 18, 0, 13, 0, 13, 0, 18, 0, 23, 0, 13, 0, 11, 0, 14, 0, 15, 0, 8, 0, 16, 0, 13, 0, 7, 0, 8, 0, 9, 0, 10, 0, 1, 0, 3, 0, 4, 0, 254, 255, 8, 0, 254, 255, 1, 0, 255, 255, 249, 255, 245, 255, 240, 255, 248, 255, 242, 255, 245, 255, 244, 255, 240, 255, 241, 255, 244, 255, 236, 255, 243, 255, 252, 255, 238, 255, 236, 255, 235, 255, 240, 255, 241, 255, 233, 255, 238, 255, 240, 255, 234, 255, 223, 255, 230, 255, 232, 255, 232, 255, 222, 255, 223, 255, 228, 255, 225, 255, 230, 255, 235, 255, 234, 255, 231, 255, 226, 255, 231, 255, 233, 255, 232, 255, 228, 255, 231, 255, 232, 255, 227, 255, 240, 255, 240, 255, 240, 255, 234, 255, 238, 255, 241, 255, 235, 255, 230, 255, 236, 255, 244, 255, 246, 255, 244, 255, 247, 255, 245, 255, 240, 255, 246, 255, 246, 255, 250, 255, 250, 255, 246, 255, 247, 255, 244, 255, 249, 255, 0, 0, 243, 255, 248, 255, 254, 255, 249, 255, 3, 0, 2, 0, 2, 0, 254, 255, 255, 255, 3, 0, 1, 0, 15, 0, 21, 0, 14, 0, 15, 0, 8, 0, 14, 0, 19, 0, 17, 0, 21, 0, 22, 0, 25, 0, 32, 0, 25, 0, 31, 0, 37, 0, 31, 0, 37, 0, 29, 0, 36, 0, 29, 0, 35, 0, 31, 0, 26, 0, 34, 0, 31, 0, 36, 0, 33, 0, 33, 0, 27, 0, 27, 0, 30, 0, 24, 0, 22, 0, 26, 0, 26, 0, 30, 0, 25, 0, 20, 0, 18, 0, 11, 0, 17, 0, 9, 0, 16, 0, 12, 0, 3, 0, 5, 0, 8, 0, 5, 0, 255, 255, 0, 0, 2, 0, 8, 0, 3, 0, 253, 255, 254, 255, 248, 255, 2, 0, 3, 0, 1, 0, 0, 0, 249, 255, 253, 255, 249, 255, 246, 255, 251, 255, 252, 255, 250, 255, 249, 255, 247, 255, 237, 255, 240, 255, 243, 255, 250, 255, 251, 255, 242, 255, 241, 255, 242, 255, 241, 255, 228, 255, 228, 255, 229, 255, 239, 255, 225, 255, 230, 255, 231, 255, 224, 255, 228, 255, 232, 255, 240, 255, 224, 255, 228, 255, 235, 255, 237, 255, 233, 255, 233, 255, 226, 255, 231, 255, 231, 255, 232, 255, 239, 255, 235, 255, 235, 255, 237, 255, 241, 255, 235, 255, 238, 255, 232, 255, 233, 255, 237, 255, 229, 255, 235, 255, 235, 255, 239, 255, 238, 255, 240, 255, 242, 255, 237, 255, 243, 255, 245, 255, 244, 255, 244, 255, 245, 255, 244, 255, 254, 255, 252, 255, 255, 255, 1, 0, 3, 0, 1, 0, 255, 255, 9, 0, 3, 0, 17, 0, 15, 0, 14, 0, 15, 0, 16, 0, 11, 0, 23, 0, 26, 0, 21, 0, 25, 0, 12, 0, 19, 0, 21, 0, 19, 0, 23, 0, 16, 0, 24, 0, 25, 0, 17, 0, 21, 0, 22, 0, 29, 0, 22, 0, 22, 0, 29, 0, 31, 0, 26, 0, 26, 0, 35, 0, 24, 0, 20, 0, 27, 0, 29, 0, 20, 0, 21, 0, 18, 0, 23, 0, 13, 0, 10, 0, 14, 0, 15, 0, 16, 0, 14, 0, 11, 0, 6, 0, 11, 0, 10, 0, 11, 0, 15, 0, 12, 0, 7, 0, 7, 0, 10, 0, 4, 0, 4, 0, 254, 255, 1, 0, 255, 255, 249, 255, 246, 255, 247, 255, 249, 255, 252, 255, 248, 255, 241, 255, 244, 255, 244, 255, 244, 255, 245, 255, 241, 255, 233, 255, 239, 255, 240, 255, 243, 255, 239, 255, 241, 255, 237, 255, 232, 255, 233, 255, 224, 255, 234, 255, 231, 255, 231, 255, 226, 255, 224, 255, 226, 255, 222, 255, 231, 255, 234, 255, 231, 255, 235, 255, 224, 255, 231, 255, 234, 255, 222, 255, 231, 255, 224, 255, 229, 255, 232, 255, 229, 255, 233, 255, 226, 255, 224, 255, 224, 255, 226, 255, 229, 255, 229, 255, 233, 255, 233, 255, 234, 255, 238, 255, 232, 255, 239, 255, 233, 255, 238, 255, 239, 255, 245, 255, 250, 255, 244, 255, 242, 255, 240, 255, 248, 255 }

**Comment by nshmyrev** [comment]
Is this the first buffer? The result after this first buffer is true?

**Comment by maallain** [comment]
yes always true with similar data.

**Comment by nshmyrev** [comment]
Ok, can you reproduce this problem with an audio file and simple code from our demo?

**Comment by maallain** [comment]
yes it produce the same situation, no meaningful words.

```
 public static void DemoSpeaker(Model model)
        {
            // Output speakers
            SpkModel spkModel = new SpkModel("model-spk");
            VoskRecognizer rec = new VoskRecognizer(model, 16000.0f);
            rec.SetSpkModel(spkModel);

            using (Stream source = File.OpenRead("test.wav"))
            {
                byte[] buffer = new byte[4096];
                int bytesRead;
                while ((bytesRead = source.Read(buffer, 0, buffer.Length)) > 0)
                {
                    if (rec.AcceptWaveform(buffer, bytesRead))
                    {
                        var sb = new StringBuilder("new byte[] { ");
                        foreach (var b in buffer)
                        {
                            sb.Append(b + ", ");
                        }
                        sb.Append("}");

                        System.Diagnostics.Debug.WriteLine(sb.ToString());

                        Console.WriteLine(rec.Result());
                    }
                    else
                    {
                        Console.WriteLine(rec.PartialResult());
                    }
                }
            }
            Console.WriteLine(rec.FinalResult());
        }

```

**Comment by nshmyrev** [comment]
I think the output was cut, can yo attach the log as a text file instead?

**Comment by maallain** [comment]
[output.txt](https://github.com/alphacep/vosk-api/files/7507441/output.txt)

3 series of output of 4096 bytes

**Comment by nshmyrev** [comment]
> 3 series of output of 4096 bytes

Those are expected since there are 3 utterances in the test files. The rest go to the partial results in your code and not printed. The code should return 3 utterances. Where are they on console?

**Comment by maallain** [comment]
not much in there
[output2.txt](https://github.com/alphacep/vosk-api/files/7507513/output2.txt)

**Comment by nshmyrev** [comment]
> not much in there

So it detected silence three times and create three utterances. Is the issue that the text is empty? That might be due to the special characters or some other corruption of the words.txt file in the model. Can you delete the model folder and make sure you downloaded the model properly?

**Comment by maallain** [comment]
I'll try the only french model I have not try.

So far english and spannish models work great.

I'm unable to make any french model work.

**Comment by nshmyrev** [comment]
@maallain you are on Windows, right?

**Comment by maallain** [comment]
Yes C# on windows 10
@nshmyrev

**Comment by nshmyrev** [comment]
Ok, let me look coming days. I need to install Windows somehow.

**Comment by maallain** [comment]
@nshmyrev any news on the differences between french model and english/spannish model?

**Comment by nshmyrev** [comment]
@maallain not yet, sorry, I have trouble with Windows as usual ;) A bit later

**Comment by maallain** [comment]
@nshmyrev is there something I can look at to help you with the french model?

**Comment by Straafe** [comment]
> Here is a working realtime code using NAudio as input driver.
> 
> ```
> WaveInEvent waveIn = new WaveInEvent();
> waveIn.DataAvailable += WaveInOnDataAvailable;
> waveIn.StartRecording();
> 
> model = new Model(@"C:\Users\x\Desktop\vosk-model-en-us-daanzu-20200905");
> rec = new VoskRecognizer(model, waveIn.WaveFormat.SampleRate);
> ```
> 
> and
> 
> ```
>     private void WaveInOnDataAvailable(object? sender, WaveInEventArgs e)
>         {
>             try
>             {
>               
>                 Dispatcher.Invoke(() =>
>                 {
>                     try
>                     {
>                      //   writer.Write(e.Buffer, 0, e.BytesRecorded);
>                         if (rec.AcceptWaveform(e.Buffer, e.Buffer.Length))
>                         {
>                             Result.Text = rec.Result();
>                         }
>                         else
>                         {
>                             Result.Text = rec.PartialResult();
>                         }
>                     }
>                     catch (Exception exception)
>                     {
>                     }
>   
>                 });
>             }
>             catch (Exception exception)
>             {
>             }
>         }
> ```
> 
> the code is a part of some other projects so the code is not clean for a simple example but anyone will get the idea

Hey, do you know how one might edit this but using the output device (audio coming from speakers), instead of the mic? There is a WaveOutEvent but it has different properties and methods than the WaveInEvent. I'd like to get Vosk to be converting the audio being played from the speakers to text instead of the audio coming in from the mic.

**Comment by nshmyrev** [comment]
> Hey, do you know how one might edit this but using the output device (audio coming from speakers), instead of the mic? 

You need to install loopback driver for that. It will create a logical input device that records output. It has to be done on system level.

**Comment by Straafe** [comment]
Alright, I installed VoiceMeeter and used its new input device with the above example code and it worked perfectly.  I was hoping to do it all in code without changing with devices, but this is still acceptable.

**Comment by nshmyrev** [comment]
Same as #986

**Comment by KakoytoChel1** [comment]
> Here is a working realtime code using NAudio as input driver.
> 
> ```
> WaveInEvent waveIn = new WaveInEvent();
> waveIn.DataAvailable += WaveInOnDataAvailable;
> waveIn.StartRecording();
> 
> model = new Model(@"C:\Users\x\Desktop\vosk-model-en-us-daanzu-20200905");
> rec = new VoskRecognizer(model, waveIn.WaveFormat.SampleRate);
> ```
> 
> and
> 
> ```
>     private void WaveInOnDataAvailable(object? sender, WaveInEventArgs e)
>         {
>             try
>             {
>               
>                 Dispatcher.Invoke(() =>
>                 {
>                     try
>                     {
>                      //   writer.Write(e.Buffer, 0, e.BytesRecorded);
>                         if (rec.AcceptWaveform(e.Buffer, e.Buffer.Length))
>                         {
>                             Result.Text = rec.Result();
>                         }
>                         else
>                         {
>                             Result.Text = rec.PartialResult();
>                         }
>                     }
>                     catch (Exception exception)
>                     {
>                     }
>   
>                 });
>             }
>             catch (Exception exception)
>             {
>             }
>         }
> ```
> 
> the code is a part of some other projects so the code is not clean for a simple example but anyone will get the idea

What am i doing wrong? I have the following exception on the model string : `System.BadImageFormatException: "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"`
I tried to change model with other languages, or i need to download full model ?

```
using NAudio.Wave;
using System;
using Vosk;

namespace ConsoleTextVosk
{
    internal class Program
    {

        public static VoskRecognizer rec;
        static void Main(string[] args)
        {
            WaveInEvent waveIn = new WaveInEvent();
            waveIn.DataAvailable += WaveInOnDataAvailable;
            Console.ReadKey();
            waveIn.StartRecording();

            Model model = new Model(@"C:\Users\Ivanchik228\Desktop\vosk-model-en-us-daanzu-20200905-lgraph");//Exception is here

            rec = new VoskRecognizer(model, waveIn.WaveFormat.SampleRate);
            Console.ReadKey();
        }

        private static void WaveInOnDataAvailable(object sender, WaveInEventArgs e)
        {
            try
            {
                if (rec.AcceptWaveform(e.Buffer, e.Buffer.Length))
                {
                    Console.WriteLine(rec.Result());
                }
                else
                {
                    Console.WriteLine(rec.PartialResult());
                }
            }
            catch {  }
        }
    }
}
```

**Comment by nshmyrev** [comment]
> I have the following exception on the model string : System.BadImageFormatException: "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"

The exception means you are trying to run 64-bit vosk library in 32-bit mode.
