### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by TimH-DE** [alphacep/vosk-api#440]
LOG (VoskAPI:ReadDataFiles():model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: ./german-vosk-model/mfcc.conf

i have download the modul but it dosent work

**Comment by nshmyrev** [comment]
You can specify absolute path to the model if you are no certain about relative path.

**Comment by PlayTim** [comment]
and i hafe de mic demo copyd why my code not 
is working and i will not in te termianl path --keywords jarvis 
how kann i jange the keyword so that i path in the termal ?
sorry i am german

**Comment by TimH-DE** [comment]
and how path?
my code with vosk:

        model = Model('./german-vosk-model')
        rec = KaldiRecognizer(model, 16000)

**Comment by nshmyrev** [comment]
absolute path starts with /, for example:

model = Model('/home/user/project/test/german-vosk-model')
