### ISSUE TITLE
Expanding word list and rescoring 

### ISSUE THREAD

**Issue by LuggerMan** [alphacep/vosk-api#441]
Following this > https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/
 i stumbled on missing the knowledge what to do to compile interpolated g.fst and g.carpa. Is rescoring any different from initial HCLG.fst?

 also, for example, in Russian model i cannot seem to find HCLr.fst, only HCLG - does that mean rescoring is not run? how to check that?

**Comment by nshmyrev** [comment]
> i stumbled on missing the knowledge what to do to compile interpolated g.fst and g.carpa. 

build_const_arpa_lm.sh script in kaldi utils builds folder with carpa

> Is rescoring any different from initial HCLG.fst?

Yes

> also, for example, in Russian model i cannot seem to find HCLr.fst, only HCLG - does that mean rescoring is not run? how to check that?

HCLr is for dynamic graph. HCLG for static graph. Rescoring is run if you have rescore folder with G.carpa. Big Russian model has rescore folder an runs rescoring.

**Comment by LuggerMan** [comment]
@nshmyrev Thanks, will use this script and read the material part

// maybe change the description at https://alphacephei.com/vosk/models a bit?
