### ISSUE TITLE
 Adding words to the model built from existing Phones

### ISSUE THREAD

**Issue by problemSolvingProgramming** [alphacep/vosk-api#443]
I realise this is not an issue with the demo but I'm trying to find a relatively simple method of doing this as I'm VERY new to ASR. The model included with the demo App contains over 67,000 words but obviously does not include words that could be domain specific such as a product name constructed by someone from a marketing background such as "flyble" (perhaps a new airline). However, it is "constructed" from two Phones "fly" as in fly and "bl" as in able. I assume that these Phones exist in the model in some way.

So is it possible to update the model in some simple way, using data already in the models folder, to get it to recognise "flyble" as a word and if so, how?

**Comment by nshmyrev** [comment]
Same as #382
