### ISSUE TITLE
temporary audio buffer can be rewritten before it will be processed by kaldi

### ISSUE THREAD

**Issue by al-zatv** [alphacep/vosk-api#444]
Here: 

https://github.com/alphacep/vosk-api/blob/4be9874ba2d3a496136a03798fcd022fa1976498/python/example/test_microphone.py#L23

```
def callback(indata, frames, time, status):
    """This is called (from a separate thread) for each audio block."""
    if status:
        print(status, file=sys.stderr)
    q.put(indata)
```

indata in callbacks from RawInputStream use 'buffer' object, which is just a pointer to the internal buffer. The buffer can (and will) be rewritten by new portions of sound. So, it is possible to send wrong audio samples to ASR.
To fix it, use `q.put( bytes(indata) )`

I reproduce this problem on my own code with RawInputStream, not exactly the same. So may be it is not a problem here. But, I think, it is.

**Comment by nshmyrev** [comment]
Great catch, should be fixed now.

**Comment by nshmyrev** [comment]
Thank you!
