### ISSUE TITLE
C# - BadImageFormatException

### ISSUE THREAD

**Issue by GABowers** [alphacep/vosk-api#445]
I created a new Console App in Visual Studio, downloaded the Vosk Nuget package (0.3.19), and tried to run the following:
`string path = "~/vosk-model-en-us-aspire-0.2/";
Vosk.Model m = new Model(path);`

It gives the error `System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'` on the second line.

The path points to the folder which contains the model subfolders (eg `~/vosk-model-en-us-aspire-0.2/am` and `~/vosk-model-en-us-aspire-0.2/conf` and so on). The C# demo here (https://github.com/alphacep/vosk-api/blob/master/csharp/demo/VoskDemo.cs) does not show where specifically the path should point to, so I'm not sure if I'm doing it wrong.

**Comment by nshmyrev** [comment]
The error says that you have 32-bit app, the binaries are 64-bit so you need 64-bit application.

It has nothing about model path.

For desktop applications daanzu model better than aspire.

**Comment by GABowers** [comment]
Okay thanks. I'm now getting a separate error. I have the following:
```
            string speechpath = "~/test_1.wav";
            string path = "~/v_model/";
            Vosk.Model m = new Model(path);
            Vosk.VoskRecognizer vr = new VoskRecognizer(m, 16000);
            var audio = new NAudio.Wave.AudioFileReader(speechpath);
            if(audio.WaveFormat.SampleRate == 16000)
            {
                Console.WriteLine("Loaded audio");
                byte[] data = new byte[audio.Length];
                audio.Read(data, 0, data.Length);
                Stopwatch sw = new Stopwatch();
                sw.Start();
                if(vr.AcceptWaveform(data, data.Length))
                {
                    Console.WriteLine(vr.Result());
                }
                else
                {
                    Console.WriteLine(vr.PartialResult());
                }
                sw.Stop();
                float length = data.Length / 16000.0f;
                string output = (Math.Round((double)(sw.ElapsedMilliseconds / 1000), 1)).ToString()
                    + (Math.Round(length, 1)).ToString();
                Console.WriteLine(output);
                Console.ReadKey();
            }
```

the vr.Result() gives me the following error: `System.MissingMethodException: 'Method not found: 'System.String System.Runtime.InteropServices.Marshal.PtrToStringUTF8(IntPtr)'.'`

**Comment by nshmyrev** [comment]
This method was introduced in newer runtime.

**Comment by GABowers** [comment]
I'm not sure what that means. Are you saying I should use a new .NET Framework version? I tried on 4.8 and got basically the same error: `System.MissingMethodException: 'Method not found: 'System.String `. I'll download 5.0 and try that, but I'm not sure if that's what you're suggesting.

Edit: I've looked into it a bit more and apparently 5.0 is for .NET Core, not .NET Framework. Should I switch, or were you talking about something else?

**Comment by LuggerMan** [comment]
@GABowers core 5.0 should help, 
https://docs.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices.marshal.ptrtostringutf8?view=net-5.0
//pls consider selfclosing this issue when everything works

**Comment by GABowers** [comment]
Okay, it works now. I updated to the most recent Visual Studio (16.9), installed the latest .NET version (5.0.200 I think), then created a new project and set it to use .net 5.0. After adding the Vosk (and NAudio) package, I had to modify the targetframework to set it to to windows only, like so:
```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
```
(in addition to setting the CPU to x64 as you can see)

Following all that, the code I posted before runs successfully and gives me output. Closing as recommended by @LuggerMan 

Edit: Separate question maybe for @nshmyrev If some folks I know have advanced Kaldi models they've built, would they work here? Or would they have to be rebuilt according to the instructions mentioned [here](https://alphacephei.com/vosk/models)?

**Comment by LuggerMan** [comment]
@GABowers those models need to be nnet3 chain setup i think, now (ver .27) with const arpa and rnnlm rescoring
