### ISSUE TITLE
ImportError: cannot import name 'Model' from 'vosk'

### ISSUE THREAD

**Issue by Ichraknaceur** [alphacep/vosk-api#446]
how to solve this error and thank you ?

**Comment by nshmyrev** [comment]
If you have trouble installing, check the output of the following commands and provide it for reference:

```
python3 --version
pip3 --version
pip3 -v install vosk
python3 -v test_simple.py test.wav
```

**Comment by Ichraknaceur** [comment]
(base) C:\Users\MSI>python --version
Python 3.7.0
////

(base) C:\Users\MSI>pip --version
pip 21.0.1 from d:\anaconda\lib\site-packages\pip (python 3.7)
/////////
(base) C:\Users\MSI>pip -v install vosk
Using pip 21.0.1 from d:\anaconda\lib\site-packages\pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: C:\Users\MSI\AppData\Local\Temp\pip-ephem-wheel-cache-ntvbbjb5
Created temporary directory: C:\Users\MSI\AppData\Local\Temp\pip-req-tracker-hfkev1qv
Initialized build tracking at C:\Users\MSI\AppData\Local\Temp\pip-req-tracker-hfkev1qv
Created build tracker: C:\Users\MSI\AppData\Local\Temp\pip-req-tracker-hfkev1qv
Entered build tracker: C:\Users\MSI\AppData\Local\Temp\pip-req-tracker-hfkev1qv
Created temporary directory: C:\Users\MSI\AppData\Local\Temp\pip-install-0tgpyms0
Requirement already satisfied: vosk in d:\anaconda\lib\site-packages (0.3.21)
Requirement already satisfied: cffi>=1.0 in c:\users\msi\appdata\roaming\python\python37\site-packages (from vosk) (1.14.5)
Requirement already satisfied: pycparser in c:\users\msi\appdata\roaming\python\python37\site-packages (from cffi>=1.0->vosk) (2.20)
Created temporary directory: C:\Users\MSI\AppData\Local\Temp\pip-unpack-k1z06gz6
Removed build tracker: 'C:\\Users\\MSI\\AppData\\Local\\Temp\\pip-req-tracker-hfkev1qv'
/////////////
(base) D:\vosk-master>python verify.py wavs-test.txt phones-test.txt data.idx
D:\Anaconda\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
D:\Anaconda\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
D:\Anaconda\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)
Traceback (most recent call last):
  File "D:\vosk-master\phash.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_phash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "verify.py", line 7, in <module>
    import phash
  File "D:\vosk-master\phash.py", line 17, in <module>
    _phash = swig_import_helper()
  File "D:\vosk-master\phash.py", line 16, in swig_import_helper
    return importlib.import_module('_phash')
  File "D:\Anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_phash'

**Comment by nshmyrev** [comment]
Can you format your code properly using markdown format rules, you can read them here:

https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by nshmyrev** [comment]
Feel free to reopen once you make the change
