### ISSUE TITLE
Updating recognizer vocabulary in runtime

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#450]
I want to ask three points

https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py
1) is this example to update dictionary? for input as audio and updates graph?
or maybe I am wrong to update / customize dictionary.

2) Also, how we can provide the proper spelling with the audio to get recognize? at `line 20` with input?

`rec = KaldiRecognizer(model, wf.getframerate(), '[**_"oh one two three four five six seven eight nine zero"_**, "[unk]"]')`

with wav file as input, I can provide the like its given in bold in `"  "` above? 
or just to generate the grammar with and use that generated grammar text with the word_test.py to update model?

3) Please also guide little more, that which big graph is possible and which not for updating like in English, French, Dutch, German. Out of available models, how to see which graphs are of dynamic model because I read that English (except indian), French, German models are dynamic  and Dutch is also or not.?

**Comment by nshmyrev** [comment]
> is this example to update dictionary?

No it is an example of dynamic graph update

> Also, how we can provide the proper spelling with the audio to get recognize? at line 20 with input?

You can not do that

> Please also guide little more, that which big graph is possible and which not for updating like in English, French, Dutch, German. Out of available models, how to see which graphs are of dynamic model because I read that English (except indian), French, German models are dynamic and Dutch is also or not.?

The ones which have HCLr.fst and Gr.fst inside are dynamic

The ones which have HCLG.fst are static

**Comment by Tortoise17** [comment]
With dynamic graph update means, one can add words in dictionary which needs to be recognizable? I mean like some special names which are not in normal day spoken and get trained by normal data. So those words can be updated with this example?

**Comment by nshmyrev** [comment]
> So those words can be updated with this example?

No

**Comment by Tortoise17** [comment]
Is there any possibility to do that? Like to custom dictionary update so that those like words can be included for recognition?

**Comment by nshmyrev** [comment]
Yes, it was already explained in the previous issue you created. 

Same as #382
