### ISSUE TITLE
Updating words and the vocabulary in the big models

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#451]
You said, that 
The ones which have HCLG.fst are static 

and also there is methodology to update that graph too but these are static graphs which i am interested. what thing make them static and is there any chance to make them dynamic?or retrain from this accuracy point?
I am asking about the models which are around 1GB big or so.` fr-pguyot-zamia-20191016-tdnn_f` `vosk-model-de-0.6` `vosk-model-nl-spraakherkenning-0.6`

**Comment by nshmyrev** [comment]
@Tortoise17 please continue this topic in #382
