### ISSUE TITLE
libkaldiwrap.a has a dependency on libstdc++ which is no longer supported in Xcode 10/iOS 12

### ISSUE THREAD

**Issue by davraamides** [alphacep/vosk-api#452]
From the Deprecation Notices section of the [Xcode 10 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-10-release-notes):

> Building with libstdc++ was deprecated with Xcode 8 and is not supported in Xcode 10 when targeting iOS. C++ projects must now migrate to libc++ and are recommended to set a deployment target of iOS 7 or later. Besides changing the C++ Standard Library build setting, developers should audit hard-coded linker flags and target dependencies to remove references to libstdc++ (including -lstdc++, -lstdc++.6.0.9, libstdc++.6.0.9.tbd, and libstdc++.6.0.9.dylib). Project dependencies such as static archives that were built against libstdc++ will also need to be rebuilt against libc++. (40885260)

Given this, some time in the future Apple may reject App Store submissions with dependencies on libstdc++.

**Comment by nshmyrev** [comment]
Should be fixed in new release
