### ISSUE TITLE
error in test_word.py when I run with other model

### ISSUE THREAD

**Issue by thinhbkseea** [alphacep/vosk-api#455]
I want to recognize a few words so I run test_word.py with my words and my language model.
when I run file test_word.py with Vietnamese model, I got the following error:
WARNING (VoskAPI:OutputArcForce():word-align-lattice.cc:578) Invalid word at end of lattice [partial lattice, forced out?]
I have tried it on many different computers, and only one did not get this error. 
Please help me. Thank you.

**Comment by nshmyrev** [comment]
Provide an audio example and the script to reproduce your issue

**Comment by thinhbkseea** [comment]
I just replaced the following code:
#rec = KaldiRecognizer(model, wf.getframerate(), '["oh zero one two three four five six seven eight nine", "[unk]"]')
rec = KaldiRecognizer(model, wf.getframerate(), '["không một hai ba bốn năm sáu bảy tám chín mười", "[unk]"]')
with my language model. 
My computer crashes after getting this error:
{
  "partial" : " một    hai  ba  bốn  năm      sáu          bảy      tám      chín     "
}
{
  "partial" : " một    hai  ba  bốn  năm      sáu          bảy      tám      chín      một "
}
{
  "partial" : " một    hai  ba  bốn  năm      sáu          bảy      tám      chín      một "
}
WARNING (VoskAPI:OutputArcForce():word-align-lattice.cc:578) Invalid word at end of lattice [partial lattice, forced out?]

**Comment by thinhbkseea** [comment]
this is my audio file


[Recording (2).zip](https://github.com/alphacep/vosk-api/files/6110598/Recording.2.zip)

**Comment by thinhbkseea** [comment]
I test on windows 10 64 bit and python 3.8.7

**Comment by nshmyrev** [comment]
> I test on windows 10 64 bit and python 3.8.7

What is your Vosk version?

**Comment by thinhbkseea** [comment]
I think I used the latest version with command: pip install vosk 
The strange thing is that one computer works normally while the other is faulty

**Comment by nshmyrev** [comment]
most likely you have old version installed, try

pip3 install -U vosk

also provide the full script output.

**Comment by thinhbkseea** [comment]
> most likely you have old version installed, try
> 
> pip3 install -U vosk
> 
> also provide the full script output.

Thank you very much. it worked
I have one more question: 
https://github.com/alphacep/vosk-api/blob/master/doc/adaptation.md
What is structure of words.txt when I update language model? Thanks

**Comment by thinhbkseea** [comment]
What can I edit in test_microphone.py to recognize some words via microphone like in test_words.py?

**Comment by nshmyrev** [comment]
> What can I fix in test_microphone.py to recognize some words via mic like in test_words.py?

KaldiRecognizer constuctor.

> What is structure of words.txt when I update language model? Thanks

You can open the existing file and look.

**Comment by thinhbkseea** [comment]
> > What is structure of words.txt when I update language model? Thanks
> 
> You can open the existing file and look.
I can't find any words.txt file in vosk-api

**Comment by nshmyrev** [comment]
> I can't find any words.txt file in vosk-api

Check inside en-us-aspire model

**Comment by thinhbkseea** [comment]
> > I can't find any words.txt file in vosk-api
> 
> Check inside en-us-aspire model

Thank you very much.

**Comment by thinhbkseea** [comment]
> > What can I fix in test_microphone.py to recognize some words via mic like in test_words.py?
> 
> KaldiRecognizer constuctor.
>
I have a problem running words.py with words selected. The system recognizes irrelevant words as pre-selected words, thereby reducing recognition accuracy. Is there a way to ignore unselected words? Thanks

**Comment by nshmyrev** [comment]
> I have a problem running words.py with words selected. The system recognizes irrelevant words as pre-selected words, thereby reducing recognition accuracy. Is there a way to ignore unselected words? Thanks

You can add [unk] word and other words from the language to make them handle words out of your target ones.
