### ISSUE TITLE
Loading DLLs from nodejs on Windows

### ISSUE THREAD

**Issue by aimjel** [alphacep/vosk-api#457]
when using vosk for node js i get 'Error: Dynamic Linking Error: Win32 error 126' error. no idea how to fix

**Comment by nshmyrev** [comment]
You need to figure out why it fails to find the dll, maybe process monitor can help you:

https://stackoverflow.com/questions/14361992/dll-load-library-error-code-126

**Comment by nickdepinet** [comment]
I'm also getting this error on windows 10.
node: v14.16.0
npm: 6.14.11
python: Python 3.8.8

I first did pip3 install vosk - which seemed to succeed
then I did npm install vosk which installed vosk 0.3.23
In my node_modules I see vosk and vosk/index.js is correctly pointing at vosk/lib/win-x86_64/libvosk.dll which exists at that location. Node is bailing on ffi.Library(path/to/libvosk.dll, ...) with the correct path and procmon shows that dll as getting loaded but I can't find what within that dll is bailing.

**Comment by nshmyrev** [comment]
On windows there are dependencies (libwinpthread.dll, etc) which needs to be loaded too, try to copy them from vosk/lib/win-x86_64 to current folder, maybe loader fails to load dependencies from vosk/lib/win-x86_64. Or copy them in PATH.

**Comment by nickdepinet** [comment]
Ok, if i copy the following 4 dlls from vosk/lib/win-x86_64 to a location on my path (in this case, my nodejs install root), the error goes away and vosk attempts to load in the model
`libgcc_s_seh-1.dll
libstdc++-6.dll
libvosk.dll
libwinpthread-1.dll`

**Comment by nshmyrev** [comment]
Whoever meets this problem please try this change:

https://github.com/alphacep/vosk-api/commit/dc44922b92e3ffc8f9c7757c0799eff241bb886d

remove libraries from path and check if this code helps to locate them automatically.

**Comment by nshmyrev** [comment]
I have just published 0.3.27 on npm, it should fix your problem. Please update.
