### ISSUE TITLE
Suitable for raspberry pi 1B

### ISSUE THREAD

**Issue by conlont** [alphacep/vosk-api#463]
Hi, have a raspberry pi 1B lying about the house and was wondering if this library has any requirements that the 1B wouldnt meet? If so I have a tinker board on hand if that would be better?

Thanks for all the work!

**Comment by nshmyrev** [comment]
> Hi, have a raspberry pi 1B lying about the house and was wondering if this library has any requirements that the 1B wouldnt meet?

No, 1B is too slow, sorry. 3B is on the edge, 4 is ok.

**Comment by nshmyrev** [comment]
Maybe we will have more lightweight models some time in the future, but not now for sure.

Meanwhile you can try simple keyword spotting, it should run fast enough.

**Comment by tiarnan-conlon** [comment]
thanks @nshmyrev, You mean like in the test_words.py example? Would that be able to run live?
Keyword spotting is all i really want it for anyway so this will work well.
Thanks

**Comment by nshmyrev** [comment]
> thanks @nshmyrev, You mean like in the test_words.py example? Would that be able to run live?

No, something like https://github.com/ARM-software/ML-KWS-for-MCU

**Comment by nshmyrev** [comment]
Let us know if you have further questions
