### ISSUE TITLE
Update small models' vocabulary

### ISSUE THREAD

**Issue by Scient122** [alphacep/vosk-api#468]
Hi, I'm using the italian small model and I'd like to add new words to the vocabulary in runtime. Is it possible? And how could I do it?

**Comment by nshmyrev** [comment]
Hello, the same issue is #382 

We didn't yet release update package for small Italian model. You have to contact us in private if you need model update.

**Comment by PedroGM80** [comment]
Hello, I have the version vosk-model-es-0.42 and I have problems with the alphabet especially the Ñ others also give certain problems with the P,  R,  V, W 
Thank you in advance

> Hello, the same issue is #382
> 
> We didn't yet release update package for small Italian model. You have to contact us in private if you need model update.

**Comment by PedroGM80** [comment]
Hello, I have the version vosk-model-small-es-0.42 and I have problems with the alphabet especially the Ñ others also give certain problems with the P,  R,  V, W 
Thank you in advance

**Comment by nshmyrev** [comment]
@PedroGM80 you'd better provide audio samples and describe the problems in details and we will be able to help you. Please don't start a discussion in unrelated threads, you can email us or create new issue instead.

**Comment by nshmyrev** [comment]
Same as #1687
