### ISSUE TITLE
Memory Leak with C# nuget package

### ISSUE THREAD

**Issue by vonguyen1982** [alphacep/vosk-api#469]
I tried with c# nuget packet 3.19
The memory keeps increase every minutes. After around 20 mins I got crash and memory reach 10G. 
I use only single model as singleton. Also I start from 1 audio streams to 4 audio streams.
![image](https://user-images.githubusercontent.com/68211937/112588876-428f0b80-8e54-11eb-8a0a-5fd32cf94470.png)

Our code is pretty simple same as the sample 

             string msg = string.Empty;
             await Task.Run(async () =>
             {
                 try
                 {
                     byte[] buffer = new byte[4096];
                     var stopWatch = Stopwatch.StartNew();
                     using (VoskRecognizer rec = new VoskRecognizer(_model, 8000.0f))
                     {
                         using (FileStream fsSource =
                             new FileStream(audioFileName, FileMode.Open, FileAccess.Read, FileShare.Read))
                         {
                             int bytesRead;
                             while ((bytesRead = await fsSource.ReadAsync(buffer, 0, buffer.Length)) > 0)
                             {
                                 if (rec.AcceptWaveform(buffer, bytesRead))
                                 {
                                     //   GC.Collect();
                                 }
                             }
                         }
                         msg = rec.FinalResult();
                         stopWatch.Stop();
                      }
                 }
                 catch (Exception ex)
                 {
                     _logger.LogError(ex, "Unable to transcribe");
                 }
             }).ConfigureAwait(false); `

**Comment by nshmyrev** [comment]
It would help if you

1. Format the code in your message properly. There are special markdown commands for the code
2. Provide reproducible example of the issue.

**Comment by vonguyen1982** [comment]
Sorry I think I sorted out. It was the log application make memory going up.

**Comment by shetzwei** [comment]
Your issue may have been related to the log application, but there is a memory leak that nshmyrev fixed about a month ago [#425](https://github.com/alphacep/vosk-api/issues/425).  There hasn't been a nuget release yet which includes that fix.  Hopefully soon

**Comment by vonguyen1982** [comment]
Ahhh you are right. I fixed my log issue but the memory does not go down after transcription completed. @nshmyrev any idea when we can test the new nuget. Thanks

**Comment by nshmyrev** [comment]
@vonguyen1982 you need to reopen issue if you still need help. You need to provide reproducible test in order to get help as was originally requested.

**Comment by nshmyrev** [comment]
@shetzwei we've just pushed 0.3.21 to nuget

**Comment by vonguyen1982** [comment]
@nshmyrev Thank you very much. I will load test again with new nuget and let you know. Many Many thanks.

**Comment by vonguyen1982** [comment]
@nshmyrev  I would like to understand a bit about memory.
I have a 8G ram with 4 cores CPU. when the vosk starts it load up around 3.3G model data into RAM.
After that I transcribe 6 mins audio. The memory is going up to 4.4G. Should I expect the memory going down to 3.3G again after completed the 6 mins audio ?

Also with long audio file like >20 mins I usually get that message 
LOG (VoskAPI:RebuildRepository():determinize-lattice-pruned.cc:287) Rebuilding repository.
WARNING (VoskAPI:CheckMemoryUsage():determinize-lattice-pruned.cc:320) Did not reach requested beam in determinize-lattice: size exceeds maximum 50000000 bytes; (repo,arcs,elems) = (28701984,1052640,20249904), after rebuilding, repo size was 19416896, effective beam was 2.65608 vs. requested beam 6
WARNING (VoskAPI:DeterminizeLatticePruned():determinize-lattice-pruned.cc:1284) Effective beam 2.65608 was less than beam 6 * cutoff 0.5, pruning raw lattice with new beam 3.99205 and retrying.

At this point the memory is increased a lots then sometimes it is going down. The container usually get crashed because run out of memory. Is that normal ? Any tip for transcribe long audio like 1hour or 2 hours ?

**Comment by vonguyen1982** [comment]
Do we need to call PartialResult() and Result() ? If I skip these 2 methods and only call FinalResult at the end then the memory is keep going up very high. Once I put PartialResult() and Result() back the seem to be sort out my issue with memory keeps increasing.

**Comment by nshmyrev** [comment]
> Do we need to call PartialResult() and Result()

Yes like in the demo.

**Comment by shetzwei** [comment]
@nshmyrev Thanks!  Initial testing is looking good.  The memory issue seems to have been resolved.  Thank you for your hard work and a great product!

**Comment by vonguyen1982** [comment]
Load testing in last few days. It is very stable. Many thanks

**Comment by nshmyrev** [comment]
Thanks for the testing @vonguyen1982, let us know how it goes!
