### ISSUE TITLE
Bible Book parsing

### ISSUE THREAD

**Issue by meichthys** [alphacep/vosk-api#471]
I've been enjoying using vosk and have found it to be quite accurate (even with the small modules!) Thanks for this project! 🚀
I am working on a speech recognition application that needs to recognize books of the Bible 📖. Vosk does well on most books, but it rarely parses others. Some of the books it has a hard time parsing are:

- Ezekiel
- Nahum
- Ecclesiastes
- Galatians
- Haggai
- Philemon
- Zephaniah
- Deuteronomy
- Habakkuk

If it would be possible to improve the recognition of these books, I would greatly appreciate it, otherwise i completely understand.

**Comment by nshmyrev** [comment]
It is possible to add all those words to vocabulary and grammar, see

https://alphacephei.com/vosk/adaptation

it is not very automated process yet though

**Comment by meichthys** [comment]
Great news! I'll check it out.
