### ISSUE TITLE
java build - no make 

### ISSUE THREAD

**Issue by shamik-k-bose** [alphacep/vosk-api#472]
As per documentation following steps were performed, namely 

git clone https://github.com/alphacep/vosk-api
cd vosk-api/java && KALDI_ROOT=<KALDI_ROOT> make
wget https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.15.zip
unzip vosk-model-small-en-us-0.15.zip
mv vosk-model-small-en-us-0.15 model
make run  
make: *** No rule to make target 'run'.  Stop. 
Please advise.
Thanks 
SK

**Comment by nshmyrev** [comment]
You have to use gradle/maven. The demo project is here:

https://github.com/alphacep/vosk-api/tree/master/java/demo

Instructions are updated now.

**Comment by nshmyrev** [comment]
Same as #460

**Comment by shamik-k-bose** [comment]
Thanks nshmyrev. 
It's running with the new code. 
The instruction for java demo needs to be updated.
1. git clone https://github.com/alphacep/vosk-api/tree/master/java/demo
2. cd vosk-api/java/demo
3. wget https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.15.zip
4. unzip vosk-model-small-en-us-0.15.zip
5. mv vosk-model-small-en-us-0.15 model
6. gradle wrapper --gradle-version 6.8.3
7. ./gradlew build
8. ./gradlew run
