### ISSUE TITLE
VOSK-API Windows doesnt work.

### ISSUE THREAD

**Issue by eix128** [alphacep/vosk-api#477]
Hi , i tried simple example vosk with example code:

package test;

import java.io.FileInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.UnsupportedAudioFileException;

import org.vosk.LogLevel;
import org.vosk.Recognizer;
import org.vosk.LibVosk;
import org.vosk.Model;

public class DecoderDemo {

    public static void main(String[] argv) throws IOException, UnsupportedAudioFileException {
        LibVosk.setLogLevel(LogLevel.DEBUG);

        try (Model model = new Model("model");
             InputStream ais = AudioSystem.getAudioInputStream(new BufferedInputStream(new FileInputStream("../../python/example/test.wav")));
             Recognizer recognizer = new Recognizer(model, 16000)) {

            int nbytes;
            byte[] b = new byte[4096];
            while ((nbytes = ais.read(b)) >= 0) {
                if (recognizer.acceptWaveForm(b, nbytes)) {
                    System.out.println(recognizer.getResult());
                } else {
                    System.out.println(recognizer.getPartialResult());
                }
            }

            System.out.println(recognizer.getFinalResult());
        }
    }
}

        <dependency>
            <groupId>vosk</groupId>
            <artifactId>vosk-api</artifactId>
            <scope>system</scope>
            <version>1.0</version>
            <systemPath>${basedir}\lib\vosk-0.3.21.jar</systemPath>
        </dependency>

        
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.7.0</version>
        </dependency>

Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found.

	at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
	at com.sun.jna@5.7.0/com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna@5.7.0/com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna@5.7.0/com.sun.jna.Native.register(Native.java:1723)
	at com.sun.jna@5.7.0/com.sun.jna.Native.register(Native.java:1444)
	at vosk@0.3.21/org.vosk.LibVosk.<clinit>(LibVosk.java:9)
	at DenemeApp@1.0-SNAPSHOT/test.DecoderDemo.main(DecoderDemo.java:19)
Disconnected from the target VM, address: '127.0.0.1:53979', transport: 'socket'

Process finished with exit code 1

**Comment by nshmyrev** [comment]
This should be fixed with

https://github.com/alphacep/vosk-api/pull/478

merged now and maven also published, update please.
