### ISSUE TITLE
Unable to install the Vosk in Python on aarch64

### ISSUE THREAD

**Issue by Avi241** [alphacep/vosk-api#479]
Command : pip3 install https://github.com/alphacep/vosk-api/releases/download/0.3.15/vosk-0.3.15-cp37-cp37m-linux_aarch64.whl
Error :
 WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
ERROR: vosk-0.3.15-cp37-cp37m-linux_aarch64.whl is not a supported wheel on this platform.

Command : pip3 install vosk
Error : 
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement vosk
ERROR: No matching distribution found for vosk

Test:

python3 --version
Python 3.6.9

pip3 --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 21.0.1 from /home/ubuntu/.local/lib/python3.6/site-packages/pip (python 3.6)

Please Help me to install it

**Comment by nshmyrev** [comment]
Try 

     python3 -m pip install https://github.com/alphacep/vosk-api/releases/download/0.3.21/vosk-0.3.21-py3-none-linux_aarch64.whl

**Comment by Avi241** [comment]
Thank You So much It Worked for me.

**Comment by danielquinn** [comment]
Having run into this problem myself I found this issue but note that the version number on the proposed fix is much older than the current (0.3.23).  Have you guys decided not to support aarch64 for all future releases, or its there a particular reason that it's not available for the current release?

**Comment by nshmyrev** [comment]
> Have you guys decided not to support aarch64 for all future releases

Latest aarch64 release is available on github. Pypy still has an issue with aarch64 unfortunately.:

https://github.com/alphacep/vosk-api/releases

**Comment by danielquinn** [comment]
Ah, so this is a PyPI thing?  I wouldn't have guessed.  Thanks for the pointer.  I'm going to try to package this for Arch Linux, and was initialy looking at pypi.org as the source.  If there's problems pushing your releases into there, I'll point to the GitHub release instead.  Thanks!

Update: [here it is](https://aur.archlinux.org/packages/python-vosk-bin/).

**Comment by Xmaxchelour** [comment]
Comment on fait ?

**Comment by Xmaxchelour** [comment]
Déjà installé.
vosk-0.3.45-py3-none-manylinux2014_aarch64.whl

~ $ python3 --version                             Python 3.12.11

~ $ pip3 --version                                pip 25.1.1 from /data/data/com.termux/files/usr/lib/python3.12/site-packages/pip (python 3.12)

~ $ pip install vosk                              ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)           ERROR: No matching distribution found for vosk
