### ISSUE TITLE
Windows x64 Error still persists

### ISSUE THREAD

**Issue by eix128** [alphacep/vosk-api#480]
I just updated latest version.
I tried these steps:

git clone https://github.com/alphacep/vosk-api
cd vosk-api/java/demo
wget https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.15.zip
unzip vosk-model-small-en-us-0.15.zip
ren vosk-model-small-en-us-0.15 model
gradle wrapper --gradle-version 6.8.3
gradlew build

gradlew run

> Task :run FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found.

        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1723)
        at com.sun.jna.Native.register(Native.java:1444)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:9)
        at org.vosk.demo.DecoderDemo.main(DecoderDemo.java:19)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_281\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by nshmyrev** [comment]
@peterkronenberg Peter, did you test it?

**Comment by nshmyrev** [comment]
Continuation of #477 . Please just reopen old bugs if not working.

I suppose I have to install Windows to test.

**Comment by peterkronenberg** [comment]
I did not specifically test it like that, but make sure you have the latest version of LibVosk.  Checked in yesterday

**Comment by achimmihca** [comment]
I just cloned and tried this yesterd (7. April). Have the same error message.
My gradle dependencies are 
```
dependencies {
    implementation group: 'net.java.dev.jna', name: 'jna', version: '5.7.0'
    implementation group: 'com.alphacephei', name: 'vosk', version: '0.3.21+'
}
```
Do I have to update these maybe?

**Comment by nshmyrev** [comment]
You need to put dll dependencies in PATH. Ideally you'd fix library loading and submit a pull request.

**Comment by achimmihca** [comment]
You are right. I just downloaded the dlls from the release page (https://github.com/alphacep/vosk-api/releases/download/0.3.27/vosk-win64-0.3.27.zip) and added the extracted folder location to my PATH. Now it is working.

I did not find info about this on https://alphacephei.com/vosk/install. Maybe you should mention it there.
Anyway, I guess this issue can be closed.
Thanks :)

**Comment by nshmyrev** [comment]
Please check that this change helps:

https://github.com/alphacep/vosk-api/commit/4a4c33fd9d546a8932258cddfb6e1066969da33e

remove libraries from path before that.

**Comment by eix128** [comment]
Adding dlls on the path makes a system wide vulnerability on Windows.
Why are you doing like that ? Why no stable solution ?

**Comment by nshmyrev** [comment]
> Why are you doing like that ? Why no stable solution ?

I'm sorry, did you see the patch? there is nothing about path, it loads dlls from resources.

**Comment by eix128** [comment]
I checked your latest update.
It only works if dll files are on the PATH
you cannot directly run jar

Example:
D:\repo\vosk-api\java\demo>gradlew run

> Task :run FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found.

        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1723)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:11)
        at org.vosk.demo.DecoderDemo.main(DecoderDemo.java:19)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_281\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date


Solution:
I downloaded ,
https://github.com/alphacep/vosk-api/releases/download/0.3.27/vosk-win64-0.3.27.zip

then added to path
set PATH=%PATH%;D:\libs\vosk-win64-0.3.27

D:\repo\vosk-api\java\demo>gradlew run

> Task :run
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.039989 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo model/graph/phones/word_boundary.int
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : "one"
}
{
  "partial" : "one"
}
{
  "partial" : "one zero"
}
{
  "partial" : "one zero"
}
{
  "partial" : "one zero zero"
}
{
  "partial" : "one zero zero"
}
{
  "partial" : "one zero zero"
}
{
  "partial" : "one zero zero"
}
{
  "partial" : "one zero zero zero"
}
{
  "partial" : "one zero zero zero one"
}
{
  "partial" : "one zero zero zero one"
}
{
  "partial" : "one zero zero zero one"
}
{
  "partial" : "one zero zero zero one"
}
{
  "partial" : "one zero zero zero one"
}
{
  "partial" : "one zero zero zero one"
}
{
  "partial" : "one zero zero zero one"
}
{
  "partial" : "one zero zero zero one"
}
{
  "result" : [{
      "conf" : 1.000000,
      "end" : 1.110000,
      "start" : 0.840000,
      "word" : "one"
    }, {
      "conf" : 1.000000,
      "end" : 1.530000,
      "start" : 1.110000,
      "word" : "zero"
    }, {
      "conf" : 1.000000,
      "end" : 1.920000,
      "start" : 1.530000,
      "word" : "zero"
    }, {
      "conf" : 1.000000,
      "end" : 2.310000,
      "start" : 1.920000,
      "word" : "zero"
    }, {
      "conf" : 1.000000,
      "end" : 2.610000,
      "start" : 2.310000,
      "word" : "one"
    }],
  "text" : "one zero zero zero one"
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : "nah no"
}
{
  "partial" : "nah no"
}
{
  "partial" : "nah no"
}
{
  "partial" : "nah no"
}
{
  "partial" : "nah no to"
}
{
  "partial" : "nah no to"
}
{
  "partial" : "nah no to i know"
}
{
  "partial" : "nah no to i know"
}
{
  "partial" : "nah no to i know"
}
{
  "partial" : "nah no to i know"
}
{
  "partial" : "nah no to i know"
}
{
  "partial" : "nah no to i know"
}
{
  "result" : [{
      "conf" : 0.514709,
      "end" : 4.110000,
      "start" : 3.930000,
      "word" : "nah"
    }, {
      "conf" : 0.605781,
      "end" : 4.290000,
      "start" : 4.110000,
      "word" : "no"
    }, {
      "conf" : 0.708856,
      "end" : 4.560000,
      "start" : 4.290000,
      "word" : "to"
    }, {
      "conf" : 0.550283,
      "end" : 4.620000,
      "start" : 4.560000,
      "word" : "i"
    }, {
      "conf" : 0.820500,
      "end" : 4.980000,
      "start" : 4.620000,
      "word" : "know"
    }],
  "text" : "nah no to i know"
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : "zero"
}
{
  "partial" : "zero"
}
{
  "partial" : "zero one"
}
{
  "partial" : "zero one"
}
{
  "partial" : "zero one eight six"
}
{
  "partial" : "zero one eight six"
}
{
  "partial" : "zero one eight zero"
}
{
  "partial" : "zero one eight zero"
}
{
  "partial" : "zero one eight zero"
}
{
  "partial" : "zero one eight zero"
}
{
  "partial" : "zero one eight zero three"
}
{
  "partial" : "zero one eight zero three"
}
{
  "result" : [{
      "conf" : 1.000000,
      "end" : 6.690000,
      "start" : 6.240000,
      "word" : "zero"
    }, {
      "conf" : 1.000000,
      "end" : 6.900000,
      "start" : 6.690000,
      "word" : "one"
    }, {
      "conf" : 1.000000,
      "end" : 7.110000,
      "start" : 6.930000,
      "word" : "eight"
    }, {
      "conf" : 1.000000,
      "end" : 7.500000,
      "start" : 7.110000,
      "word" : "zero"
    }, {
      "conf" : 1.000000,
      "end" : 7.980000,
      "start" : 7.500000,
      "word" : "three"
    }],
  "text" : "zero one eight zero three"
}

BUILD SUCCESSFUL in 4s
2 actionable tasks: 1 executed, 1 up-to-date



It worked yes but i needed to add DLLs to PATH
I checked your latest update

**Comment by nshmyrev** [comment]
Fixed and tested now with https://github.com/alphacep/vosk-api/commit/f57b926f667131437e2bde73fe5f27aeeffd2d6a
