### ISSUE TITLE
Frequent crashing of vosk in our implementation

### ISSUE THREAD

**Issue by rajvirdhakhada7** [alphacep/vosk-api#481]
Hello,
We're using vosk version 0.3.17 for getting call transcription. Calls are made using Twillio and audio data is streaming live. We're facing frequent crashing of vosk in our implementation. There is always one of the following errors for crashing. Can anyone help us identify what we're missing? or doing wrong?

**Error 1:**
Mar 31 07:31:23 sh[27044]: ERROR (VoskAPI:AcceptWaveform():online-feature.cc:136) AcceptWaveform called after InputFinished() was called.
Mar 31 07:31:23 sh[27044]: terminate called after throwing an instance of 'kaldi::KaldiFatalError'
Mar 31 07:31:23 sh[27044]:   what():  kaldi::KaldiFatalError
Mar 31 07:31:23 sh[27044]: Aborted (core dumped)

**Error 2:**  
Mar 31 12:02:40 sh[24844]: ASSERTION_FAILED (VoskAPI:TraceBackBestPath():lattice-faster-online-decoder.cc:151) Assertion failed: (static_cast<size_t>(cur_t) < this->cost_offsets_.size())
Mar 31 12:02:41 sh[24844]: Aborted (core dumped)

**Error 3:**  
Mar 31 11:47:39 sh[28583]: WARNING (VoskAPI:BestPathEnd():lattice-faster-online-decoder.cc:123) No final token found.
Mar 31 11:47:39 sh[28583]: ASSERTION_FAILED (VoskAPI:TraceBackBestPath():lattice-faster-online-decoder.cc:134) Assertion failed:  (!iter.Done() && oarc != NULL)
Mar 31 11:47:39 sh[28583]: Aborted (core dumped)

**Vosk Version:** 0.3.17
**Model:** vosk-model-en-in-0.4 (Indian English Model)
**Folder Structure :** tree model

model
├── README
├── am
│   ├── final.mdl
│   └── frame_subsampling_factor
├── conf
│   ├── mfcc.conf
│   └── model.conf
├── graph
│   ├── HCLG.fst
│   ├── word_boundary.int
│   └── words.txt
├── ivector
│   ├── final.dubm
│   ├── final.ie
│   ├── final.mat
│   ├── global_cmvn.stats
│   ├── ivector.conf
│   ├── online_cmvn.conf
│   └── splice.conf
└── rescore
    ├── G.carpa
    └── G.fst

**Comment by nshmyrev** [comment]
> Mar 31 12:02:40 sh[24844]: ASSERTION_FAILED (VoskAPI:TraceBackBestPath():lattice-faster-online-decoder.cc:151) Assertion failed: (static_cast<s

The text in log here contains the description of the problem. To get help you need to provide this text.

**Comment by rajvirdhakhada7** [comment]
Hey, Thanks for your reply. It's crashing due to one of these errors.

**Error 1** 
ERROR (VoskAPI:AcceptWaveform():online-feature.cc:136) AcceptWaveform called after InputFinished() was called.
 terminate called after throwing an instance of 'kaldi::KaldiFatalError'
 what():  kaldi::KaldiFatalError. 

**Error 2:**
ASSERTION_FAILED (VoskAPI:TraceBackBestPath():lattice-faster-online-decoder.cc:151) Assertion failed: (static_cast<size_t>(cur_t) < this->cost_offsets_.size())

**Error 3:**
WARNING (VoskAPI:BestPathEnd():lattice-faster-online-decoder.cc:123) No final token found.
ASSERTION_FAILED (VoskAPI:TraceBackBestPath():lattice-faster-online-decoder.cc:134) Assertion failed:  (!iter.Done() && oarc != NULL)

**Comment by nshmyrev** [comment]
>  Error 1 already contains a full error message.

No, it lacks the piece after accept waveform

In general, that seems like a memory corruption. 

How are you using our code exactly? 

Do you process audio in threads?

Are you using our python server or some other code? 

How many streams do you process? 

On what hardware?

**Comment by rajvirdhakhada7** [comment]
**How are you using our code exactly?**

> I have created a class that sends audio data to the model for transcription. More details at end

**Do you process audio in threads?**	

> Yes 

**Are you using our python server or some other code?**

> I have below code instead of using any network-based server.
	
```
self.model = Model("/home/ubuntu/vosk-server/websocket/model")
self.rec = KaldiRecognizer(self.model, 8000)
```

**How many streams do you process?**

> I process a single stream at a time

**On what hardware?**

> I have used AWS EC2 instance (m6g.xlarge) with Arm-based AWS Graviton2 processors.


This is how we're using vosk
```
from vosk import Model, KaldiRecognizer, SetLogLevel
import sys
import os
import wave
import queue
from threading import Thread
import json


class VoskTranscriberServer:

    def __init__(self,completion_handler):
        self.chunk_queue = queue.Queue()
        if not os.path.exists("/home/ubuntu/vosk-server/websocket/model"):
            print("Vosk Speech to text Model doesn't exist")

        print("loading vosk model")

        try:
            self.model = Model("/home/ubuntu/vosk-server/websocket/model")
            self.rec = KaldiRecognizer(self.model, 8000)
        except Exception as e:
            print("Error while initializing and loading vosk server {0}".format(e))

        print("loaded vosk model")
        self.is_sending = False
        self.completion = completion_handler

    def start_server(self):
        try:
            if self.model == None:
                self.model = Model("/home/ubuntu/vosk-server/websocket/model")
                self.rec = KaldiRecognizer(self.model, 8000)

            def process_queue():
                while self.chunk_queue.qsize() > 0:
                    chunk = self.chunk_queue.get()
                    self.process_chunk(chunk)
                self.is_sending = False

            t = Thread(target=process_queue)
            t.start()
            self.is_sending = True

        except Exception as e:
            print("Exception while starting vosk server {0}".format(e))

    def add_chunk(self,chunk):
        self.chunk_queue.put(chunk)

        if self.is_sending == False:
            self.start_server()

    def process_chunk(self,chunk):
        try:
            if chunk == '{"eof" : 1}':
                json_response = json.loads(self.rec.FinalResult())
                if json_response["text"] != "":
                    self.completion(json_response["text"],True)
            elif self.rec.AcceptWaveform(chunk):
                json_response = json.loads(self.rec.FinalResult())
                if json_response["text"] != "":
                    self.completion(json_response["text"],True)
            else:
                json_response = json.loads(self.rec.PartialResult())
                if json_response["partial"] != "":
                    self.completion(json_response["partial"],False)
        except Exception as e:
            print(e)


    def terminate(self):
        self.model = None
        self.rec = None
        self.is_sending = False
```

**Comment by nshmyrev** [comment]
I don't quite get the code and also don't quite get the way you are processing things. I see you use one thread, do you start many threads? Do you run several recognizers in parallel? I don't see that part in your code.

Most likely you simply corrupt memory by sending wrong data to wrong recognizer or just reusing recognizers from different threads. It is a bad idea. You'd better follow the approach we have in vosk-server code.

If you share the model across threads and create one recognizer per thread, your code will work fine.

**Comment by nshmyrev** [comment]
Feel free to ask if you need other things
