### ISSUE TITLE
Suggestion: Synchronize versions of ref-napi with ffi-napi

### ISSUE THREAD

**Issue by Sharcoux** [alphacep/vosk-api#482]
It might be interesting to change the package.json to:

```json
  "peerDependencies": {
    "ref-napi": ">=2.0.0"
  },
  "dependencies": {
    "ffi-napi": "^2.1.0",
    "wav": "^1.0.2"
  }
```

Or to downgrade ref-napi version, so that we only depend on one version of ref-napi. I can make a PR if you feel comfortable with this idea.

**Comment by nshmyrev** [comment]
Please submit a pull request. Why 2.1.0 instead of current 3.1.0 ?

**Comment by Sharcoux** [comment]
Well, actually, we could also increase `ffi-napi` to `4.0.3`, which depends on: `"ref-napi": "^2.0.1 || ^3.0.2"`

But right now, `ffi-napi: 2.1.0` depends on `ref-napi: 2.0.1` which makes `vosk` depend on 2 versions of `ref-napi` for nothing.

**Comment by nshmyrev** [comment]
Ok. Merged now.
