### ISSUE TITLE
Question about accuracy of stereo and mono conversation

### ISSUE THREAD

**Issue by vonguyen1982** [alphacep/vosk-api#485]
Hi, 
I wonder if I have a stereo audio file.  I have 2 options here
- Transcribing 2 audio channels separately as 2 mono audio streams 
- Mix the stereo audio to mono file and transcribe as single mono file.
Which option will give me better accuracy rate ?
Thanks

**Comment by nshmyrev** [comment]
Transcribing separately is better. Mix accuracy corrupted by crosstalk.

**Comment by vonguyen1982** [comment]
Thank you
