### ISSUE TITLE
Нужна быстрая пауза в распознавании под андроид

### ISSUE THREAD

**Issue by solkogan** [alphacep/vosk-api#486]
В андроид версии у меня после распознавания каждой фразы я выключал распознавалку через

  recognizer.cancel();
  recognizer = null;

чтобы приложение могло проговорить вслух ответ и в это время ничего не распознавалось

Потом когда синтез речи прекращался я снова создавал 

recognizer = new SpeechRecognizer(model);
recognizer.addListener(this);
recognizer.startListening();

и видимо это  забирало какое то время потому что текст начинал распознаваться только спустя несколько секунд

а я в эти секунды говорил следующую команду и думал что Воск не слышит

Нужно бы сделать быструю паузу наверное, для того чтобы быстро остановить распознавание, а потом так же быстро его запустить

**Comment by nshmyrev** [comment]
В новой версии добавлен метод setPause

https://github.com/alphacep/vosk-api/blob/2221cd02094ff2f64c1707713f6a9b203cf78a68/android/lib/src/main/java/org/vosk/android/SpeechService.java#L146
