### ISSUE TITLE
用kaldi,aishell下s5训练出来的语音识别模型，用vosk无法加载出来的问题

### ISSUE THREAD

**Issue by tuocheng0824** [alphacep/vosk-api#487]
![241617936625_ pic_hd](https://user-images.githubusercontent.com/28757602/114122263-7f620480-9922-11eb-9fff-5a7017fda1ca.jpg)
报Expected token <Nnet3> got instead DIMENSION的问题

**Comment by nshmyrev** [comment]
You need nnet3/chain model final.mdl, you are trying to load GMM model. Check for chain model instead.

**Comment by tuocheng0824** [comment]
你好，我同事用kaldi 下 nnet3/chain 训练中文语音识别出来，然后我这边用vosk 进行加载，报了一个维度问题，
input feature dimension mismatch got 40 but network expects 43，请问vosk对中文语音识别会出现这样的问题是吗

**Comment by tuocheng0824** [comment]
各位好：

我再问一个问题，kaldi中aishell下面的chain训练语音识别的代码和 librispeech下面 chain的代码不一样 一个是tdnn ,一个是tdnnf 然后librispeech会加载出来，aishell会因为维度报错，所以想问问你们那边是否是同样的问题？

**Comment by nshmyrev** [comment]
Further questions answered here:

https://github.com/alphacep/vosk-api/issues/491
