### ISSUE TITLE
Hello. What is the meaning parameter of --min-active=200 and --max-active=3000 model vosk api ?

### ISSUE THREAD

**Issue by problemSolvingProgramming** [alphacep/vosk-api#489]
Hello.

Hello. What is the meaning parameter  of  --min-active=200 and --max-active=3000  model vosk api  ?

vosk --min-active=200 --max-active=7000 --beam=13.0 --lattice-beam=6.0 --acoustic-scale=1.0 ..

**Comment by nshmyrev** [comment]
They are standard beam search parameters
