### ISSUE TITLE
Read JSON output produced by test_simple.py

### ISSUE THREAD

**Issue by xfim** [alphacep/vosk-api#492]
Dear developers,

Thank you very much for the software and its documentation.

I am using the `test_simple.py` file to transcribe some recordings (my plan is to scale it towards full transcription of interviews). The transcription has turned to be very good (compared to my previous tries with deepspeech). The output reported is almost perfect. I send the output to a file (`python3 test_simple.py recording.wav > transcription.txt`), but I can't seem to make the output workable. I would say it is a JSON file, but:

- A validation of the resulting file is unsuccesful (using https://jsonformatter.curiousconcept.com/# or https://jsonformatter.org/).
- If I try with python using [this piece](https://stackoverflow.com/a/27907893/2839239) it reports an error `JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)`.
- If I try with R, neither `rjson` nor `jsonlite' accept the file and parse it.

So my question would be: what is the sort of output produced by `test_simple.py`? And how to treat it?

Thank you very much for your support.

See the file received from myself reading a piece of a wikipedia article:
[transcription.txt](https://github.com/alphacep/vosk-api/files/6296882/transcription.txt)

**Comment by sskorol** [comment]
@xfim hi,

According to the output you attached, it's not a valid JSON, as it's not a single object or array. You have N JSON objects in a single file. Vosk returns a separate JSON object for each audio chunk you send. And when you pipe the output directly to a file, it produces a mess of individual results. If you want to fix that manually, you have to wrap the output into array syntax:
```
[
  {
    ...
  },
  {
    ...
  }
]
```
But I'd rather modify `test_simple.py` to write the result to file in a format you want. It'll be much easier than trying to "fix" it outside the script.

**Comment by xfim** [comment]
Excellent, thank you. I've got it now. I will modify the script accordingly. Just, out of curiosity, what is the rationale behind vosk returning separate JSON objects?

**Comment by nshmyrev** [comment]
> Just, out of curiosity, what is the rationale behind vosk returning separate JSON objects?

It is just a demo script, it is not supposed to be used as is. You can adjust it according to you needs. There is test_srt.py script for example which dumps standard srt files.

> Excellent, thank you. I've got it now. I will modify the script accordingly

Great, let us know how it goes.
