### ISSUE TITLE
RawInputStream vs. RawOutputStream in python to transcribe what the soundcard reproduces

### ISSUE THREAD

**Issue by xfim** [alphacep/vosk-api#493]
Dear all,

As I already mentioned (issue #492 ) my ultimate goal ist to transcribe interviews. I am know, however,  testing whether it would be possible to use the api to transcribe the media reproducing in my soundcard. That is, using the media that my computer is currently processing (for instance, a video / audio file being reproduced independently, a speech being reproduced through the browser, or the output of a videoconference).

My first idea has been to start with `test_microphone.py`, that uses `RawInputStream` and adapt it. As far as my limited familiarity with sounddevice is concerned, it should be possible by replacing that with `RawOutputStream`, but a simple change of such functions does no seem to work, and by trying several combinations I don't seem to go anywhere.

Is there any idea of where can I go after this? Is it worth exploring the `RawOutputStream` function or should I use a different approach?

Thank you very much for your support.

**Comment by nshmyrev** [comment]
RawInputStream is not going to work, to record playback sounds you have to configure the system to allow that. The details how to configure that depends on your OS, it is easier on Linux, requires special driver on Windows.

**Comment by xfim** [comment]
Thank you @nshmyrev for you your reply.

I'm using Gentoo GNU/Linux, and the output of `python3 test_microphone.py -d' is:

```
< 0 HDA Intel PCH: HDMI 0 (hw:0,3), ALSA (0 in, 2 out)
  1 HDA Intel PCH: HDMI 1 (hw:0,7), ALSA (0 in, 8 out)
  2 HDA Intel PCH: HDMI 2 (hw:0,8), ALSA (0 in, 8 out)
  3 HDA Intel PCH: HDMI 3 (hw:0,9), ALSA (0 in, 8 out)
  4 HDA Intel PCH: HDMI 4 (hw:0,10), ALSA (0 in, 8 out)
  5 hdmi, ALSA (0 in, 2 out)
> 6 pulse, ALSA (32 in, 32 out)
```

But none of them seem to work (trying -d 1, -d 2, etc...), neither using instead `RawOutputStream`? 

Any idea on how to do that? Where to start looking?

**Comment by nshmyrev** [comment]
You need to load pulseaudio loopback module, see here:

https://askubuntu.com/questions/403416/how-to-listen-live-sounds-from-input-from-external-sound-card

**Comment by xfim** [comment]
Thank you @nshmyrev. Bingo. I don't know exactly how, but I made it work using the loopback module. Excellent.
