### ISSUE TITLE
C# Text not transcribing from long duration mp3 or wav files

### ISSUE THREAD

**Issue by mbuchok** [alphacep/vosk-api#494]
I'm using the C# nuget package and I have some mp3 files with durations of approximately 20 to 30 minutes in length. I copied the demo exactly, and used the test file at first, which is much shorter in duration. Things were working fine with the test file. As soon as I change the path to one of my files, the Result, PartialResult, and FinalResult are printed as empty strings. I listened to the audio to make sure I didn't supply any files with dead air. Is there anything I can do or any other information I can provide to help look into this?

**Comment by nshmyrev** [comment]
You need to convert mp3 to wav before processing. You can do it with ffmpeg for example.

**Comment by nshmyrev** [comment]
Also you need to make sure wav files are mono

**Comment by mbuchok** [comment]
The mp3 I'm using was indeed stereo. Just ran a test, converted with ffmpeg to mono and .wav. Also had to change the bitrate in the VoskRecognizer object to match that of the audio. Things are working now.

Thanks for your help! I appreciate it.
