### ISSUE TITLE
Undefined reference building on OSX

### ISSUE THREAD

**Issue by xuducan** [alphacep/vosk-api#495]
When i use the script build-vosk.sh to built the project, openblas, clapack and openfst are no problem. the bug appears in kaldi. The log is like below. My ndk version is 22.0.7026061. Waiting for your reply, Thanks!

armv7a-linux-androideabi21-clang++ -dynamiclib -o libkaldi-base.so -install_name @rpath/libkaldi-base.so   -Wl,-rpath -Wl,vosk-api/android/lib/build/kaldi_armeabi-v7a/kaldi/src/lib kaldi-math.o kaldi-error.o io-funcs.o kaldi-utils.o timer.o  vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libfst.a vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libopenblas.a vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/liblapack.a vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libblas.a vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a -lm -ldl
clang++: warning: argument unused during compilation: '-dynamiclib' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-install_name @rpath/libkaldi-base.so' [-Wunused-command-line-argument]
/Users/xuducan/project/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a(sig_die.c.obj):sig_die.c:function sig_die: error: undefined reference to 'stderr'
/Users/xuducan/project/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a(sig_die.c.obj):sig_die.c:function sig_die: error: undefined reference to 'stderr'
/Users/xuducan/project/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a(err.c.obj):err.c:function f__fatal: error: undefined reference to 'stderr'
/Users/xuducan/project/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a(err.c.obj):err.c:function f__fatal: error: undefined reference to 'stderr'
/Users/xuducan/project/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a(err.c.obj):err.c:function f_init: error: undefined reference to 'stdin'
/Users/xuducan/project/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a(err.c.obj):err.c:function f_init: error: undefined reference to 'stdout'
/Users/xuducan/project/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a(main.c.obj):main.c:function main: error: undefined reference to 'MAIN__'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nshmyrev** [comment]
Looks like you are trying to build on OSX, I'd better try on Linux.

If you still want to build on OSX, you'd need to edit this part, it should be ignored on cross-compilation:

https://github.com/kaldi-asr/kaldi/blob/cbed4ff688a172a7f765493d24771c1bd57dcd20/src/Makefile#L63

**Comment by xuducan** [comment]
You are so nice, Thanks so much! I have built success on Linux. Do you known the reason why kaldi built failed on OSX, especially error happened because of stdin stdout stderr and MAINI__ in libf2c.a? What i can realize is just because of the system library，such as libc.

**Comment by nshmyrev** [comment]
> Do you known the reason why kaldi built failed on OSX,

The make has to create dynamic library (adds -dynamic flag), but due to wrongly detected compiler flag (its actually linux compiler, not OSX) it tries to create an executable (-dynamic is ignored) and it expectedly fails. You need to fix make process so it properly creates dynamic library even on OSX even with cross-compiler.

**Comment by xuducan** [comment]
Got it！Thank you and your amazing project！

**Comment by nshmyrev** [comment]
Same as #260

**Comment by tuannguyenbb** [comment]
> Looks like you are trying to build on OSX, I'd better try on Linux.
> 
> If you still want to build on OSX, you'd need to edit this part, it should be ignored on cross-compilation:
> 
> https://github.com/kaldi-asr/kaldi/blob/cbed4ff688a172a7f765493d24771c1bd57dcd20/src/Makefile#L63

@nshmyrev I'm getting the same error even when this change is already present. Do you have any idea about that?

```
clang-12: warning: argument unused during compilation: '-dynamiclib' [-Wunused-command-line-argument]
clang-12: warning: argument unused during compilation: '-install_name @rpath/libkaldi-base.so' [-Wunused-command-line-argument]
ld: error: undefined symbol: MAIN__
>>> referenced by main.c
>>>               main.c.obj:(main) in archive /Users/itabluebelt/Desktop/Projects/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a

ld: error: undefined symbol: stderr
>>> referenced by sig_die.c
>>>               sig_die.c.obj:(sig_die) in archive /Users/itabluebelt/Desktop/Projects/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a
>>> referenced by sig_die.c
>>>               sig_die.c.obj:(sig_die) in archive /Users/itabluebelt/Desktop/Projects/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a
>>> referenced by err.c
>>>               err.c.obj:(f__fatal) in archive /Users/itabluebelt/Desktop/Projects/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a
>>> referenced 7 more times

ld: error: undefined symbol: stdin
>>> referenced by err.c
>>>               err.c.obj:(f_init) in archive /Users/itabluebelt/Desktop/Projects/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a

ld: error: undefined symbol: stdout
>>> referenced by err.c
>>>               err.c.obj:(f_init) in archive /Users/itabluebelt/Desktop/Projects/vosk-api/android/lib/build/kaldi_armeabi-v7a/local/lib/libf2c.a
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

![Screenshot 2024-02-15 at 15 50 47](https://github.com/alphacep/vosk-api/assets/145955611/6629c3ec-c24f-4f97-ac05-cd3f9d411aa0)

I'm building in `Apple Macbook M2`. OS version: `13.4 (22F66)`

**Comment by lgkwl** [comment]
I have the same issue, even when this change is already present  when I build on osx, it shows other errors,just like:

aarch64-linux-android21-clang++ -M -std=c++17 -I.. -I/Users/lgkwl/work/workspace/vosk-android-demo/app/build/kaldi_arm64-v8a/local/include -O1 -Wno-sign-compare -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -Wno-mismatched-tags -DKALDI_DOUBLEPRECISION=0 -DHAVE_CXXABI_H -DHAVE_OPENBLAS -DANDROID_BUILD -I/Users/lgkwl/work/workspace/vosk-android-demo/app/build/kaldi_arm64-v8a/local/include -I/Users/lgkwl/work/software/android-sdk-macosx/ndk-25/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -pthread -g  -fPIC -O3 -DFST_NO_DYNAMIC_LINKING batched-static-nnet3.cc batched-threaded-nnet3-cuda-online-pipeline.cc batched-threaded-nnet3-cuda-pipeline.cc batched-threaded-nnet3-cuda-pipeline2.cc cuda-decoder.cc cuda-fst.cc cuda-online-pipeline-dynamic-batcher.cc cuda-pipeline-common.cc decodable-cumatrix.cc lattice-postprocessor.cc >> .depend.mk
batched-threaded-nnet3-cuda-online-pipeline.cc:19:2: error: CUDA support must be configured to compile this library.
#error CUDA support must be configured to compile this library.
 ^
batched-threaded-nnet3-cuda-online-pipeline.cc:24:10: fatal error: 'nvToolsExt.h' file not found
#include <nvToolsExt.h>
         ^~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/bin/make -C cudadecoderbin/ depend
rm -f .depend.mk
aarch64-linux-android21-clang++ -M -std=c++17 -I.. -I/Users/lgkwl/work/workspace/vosk-android-demo/app/build/kaldi_arm64-v8a/local/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -Wno-mismatched-tags -DKALDI_DOUBLEPRECISION=0 -DHAVE_CXXABI_H -DHAVE_OPENBLAS -DANDROID_BUILD -I/Users/lgkwl/work/workspace/vosk-android-demo/app/build/kaldi_arm64-v8a/local/include -I/Users/lgkwl/work/software/android-sdk-macosx/ndk-25/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -pthread -g  -fPIC -O3 -DFST_NO_DYNAMIC_LINKING batched-wav-nnet3-cuda-online.cc batched-wav-nnet3-cuda.cc batched-wav-nnet3-cuda2.cc >> .depend.mk
2 errors generated.
batched-wav-nnet3-cuda-online.cc:23:2: error: CUDA support must be configured to compile this binary.
#error CUDA support must be configured to compile this binary.
 ^
batched-wav-nnet3-cuda-online.cc:26:10: fatal error: 'cuda.h' file not found
#include <cuda.h>
         ^~~~~~~~
batched-threaded-nnet3-cuda-pipeline.cc:19:2: error: CUDA support must be configured to compile this library.
#error CUDA support must be configured to compile this library.
 ^
2 errors generated.
batched-threaded-nnet3-cuda-pipeline.cc:29:10: fatal error: 'nvToolsExt.h' file not found
#include <nvToolsExt.h>
         ^~~~~~~~~~~~~~
2 errors generated.
batched-threaded-nnet3-cuda-pipeline2.cc:19:2: error: CUDA support is required to compile this library.
#error CUDA support is required to compile this library.
 ^
batched-threaded-nnet3-cuda-pipeline2.cc:26:10: fatal error: 'nvToolsExt.h' file not found
#include <nvToolsExt.h>
         ^~~~~~~~~~~~~~
2 errors generated.
make[1]: [depend] Error 1 (ignored)
cuda-decoder.cc:19:2: error: CUDA support must be configured to compile this library.
#error CUDA support must be configured to compile this library.
 ^
cuda-decoder.cc:40:10: fatal error: 'cuda_runtime_api.h' file not found
#include <cuda_runtime_api.h>
         ^~~~~~~~~~~~~~~~~~~~
2 errors generated.
cuda-fst.cc:19:2: error: CUDA support must be configured to compile this library.
#error CUDA support must be configured to compile this library.
 ^
cuda-fst.cc:25:10: fatal error: 'cuda_runtime_api.h' file not found
#include <cuda_runtime_api.h>
         ^~~~~~~~~~~~~~~~~~~~
2 errors generated.
cuda-online-pipeline-dynamic-batcher.cc:19:2: error: CUDA support must be configured to compile this library.
#error CUDA support must be configured to compile this library.
 ^
1 error generated.
make[1]: [depend] Error 1 (ignored)

the build scripts have already configured "./configure --use-cuda=no", such as:

cd $WORKDIR/kaldi/src
CXX=$CXX AR=$AR RANLIB=$RANLIB CXXFLAGS="$ARCHFLAGS -O3 -DFST_NO_DYNAMIC_LINKING" ./configure --use-cuda=no \
    --mathlib=OPENBLAS_CLAPACK --shared \
    --android-incdir=${ANDROID_TOOLCHAIN_PATH}/sysroot/usr/include \
    --host=$HOST --openblas-root=${WORKDIR}/local \
    --fst-root=${WORKDIR}/local --fst-version=${OPENFST_VERSION}
 

 so how could I fix it ,Thanks in advance.
