### ISSUE TITLE
How to get results combined in a longer string

### ISSUE THREAD

**Issue by jamesoliver1981** [alphacep/vosk-api#499]
Hi,
First up great job, getting some great results especially with the German model.  I have noticed that when I get some longer audio, the results start being put into separate string dictionaries.  When it was just one, I could get the answer out.  When its longer, I don't know how to extract this data.

I am specifically talking about the result element here, first called "several" & then "my" & then "I broke up".  I would want to have access to this together.
![image](https://user-images.githubusercontent.com/13690904/115561676-17160a00-a2b6-11eb-9180-3e0b401a9006.png)

I have seen the suggestion about just getting the text.  However I have found this hasn't worked for me.  Here are the results on the same audio file.

![image](https://user-images.githubusercontent.com/13690904/115562075-71af6600-a2b6-11eb-8ffa-3a5036456eaa.png)

For reference, when there is one "result", this function returns the text for me.

```
def text_from_audio_v2( path, file, location):
    os.chdir("D:/OneDrive/DataSci/Tennis/02_Preprocessing/Voice/VSOK/" + location)
    wf = wave.open(path + file, "rb")
    model = Model("model")
    rec = KaldiRecognizer(model, wf.getframerate())
    while True:
        data = wf.readframes(4000)
        if len(data) == 0:
            break
        if rec.AcceptWaveform(data):
            rec.Result()
        else:
            rec.PartialResult() #print(rec.PartialResult())
    final = rec.FinalResult()
    json_acceptable_string = final.replace("'", "\"")
    final_dict = json.loads(json_acceptable_string)
    print(final_dict["text"])
    return final_dict
```

I appreciate any help you can give me,
Thank you,
James

**Comment by madkote** [comment]
@jamesoliver1981  try
```python
...
results = []
while True:
    data = fin.readframes(4000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        results.append(json.loads(rec.Result())['text'])
resultsappend(json.loads(rec.FinalResult())['text'])
pprint.pprint(results)
```

**Comment by jamesoliver1981** [comment]
Perfect.  Thank you and thank you for the epically quick response

**Comment by frankiedrake** [comment]
Thank you. This should be probably noticed somewhere in the manual 😊
