### ISSUE TITLE
Audio cleanliness recommendations & requirements for accurate results

### ISSUE THREAD

**Issue by jamesoliver1981** [alphacep/vosk-api#500]
Hi,
I get excellent results from when I am sat in a quiet room and there is no background noise.  For my application however, I want to use this on a tennis court to align scores to points in a match.

I have tried removing some noise using noisereduce but this did not improve the results.

```
def text_from_audio_v3( path, file, location):
    os.chdir("D:/OneDrive/DataSci/Tennis/02_Preprocessing/Voice/VSOK/" + location)
    wf = wave.open(path + file, "rb")
    model = Model("model")

    rec = KaldiRecognizer(model, wf.getframerate(), '["second", "serve", "love", "fifteen", "mistake", "thirty", "winner"]')

    results = []
    while True:
        data = wf.readframes(4000)
        if len(data) == 0:
            break
        if rec.AcceptWaveform(data):
            results.append(json.loads(rec.Result())['text'])
    results.append(json.loads(rec.FinalResult())['text'])
    pprint.pprint(results)
    return results

pt1n2_bk_remove2 = text_from_audio_v3(path = "D:/OneDrive/DataSci/Tennis/01_data/",file = "210415_JJOKarstenMatch/AudioExamples/pt1n2_bk_remove.wav", 
                                      location = "English/vosk-model-en-us-aspire-0.2" )
```

The file says: 2nd serve, love 15 double fault, mistake, love 30 sorry winner.  The model returns: ['huh', 'couple', 'oh sorry when', '']

I noticed that on a similar question you asked for the audio files before you started talking in Russian so these are linked [here ](https://1drv.ms/u/s!AiQBClagXLxThboWq7I0k4klK589nQ?e=5I5uwp)

pt1n2_noadjust.wav is the original file
pt1n2_bk_remove2.wav is the file where I have removed background noise
james_english_upd.wav is a test file that showed me that this works well enough

Do you have any advice on how to clean up the files so they give reasonable accuracy?  I don't need 100%.  If I get consistent approximate matches, I can map these across to the result.

When trying out AssmeblyAI, this could deal with the noise.  But it only works in English and I need English & German.

Thank you in advance,
James

**Comment by nshmyrev** [comment]
Noise reduction is not recommended, it reduces accuracy.

To use grammar feature you need a model which supports grammar this one:

https://alphacephei.com/vosk/models/vosk-model-en-us-daanzu-20200905-lgraph.zip

with grammar features it should recognize your audio correctly if you provide proper phrases in the grammar.

pascal1.wav despite extension is mp3 file, you need to convert it to wav.

**Comment by jamesoliver1981** [comment]
Thanks for the tip about noise reduction.  I had that feeling but good to have it confirmed.

By grammar features you mean the list of words I have added?  When I didn't use that, the results were the same as not using it.  Is that because I'm trying to use it with a model where that doesn't work?  I will try it and get back to you.

However my main focus of this will be with German initially.  I don't see that where it states whether grammar is supported or not.  I have until now been using  this model: vosk-model-de-0.6.

The German model worked well with the file "lilligerman_upd.wav" which is in an office space, but poorly with "pascal1_v2.wav" for example.

Pascal1_v2 says: eins null null ein ( 0 1 1 0) fehler (mistake).  What is returned is:
['alles läuft nur leid', 'fehler der ebene', '']

PS thanks for pointing out Pascal1 was incorrectly formatted.  I realised that myself earlier today.

**Comment by nshmyrev** [comment]
Small model for German supports grammars:

https://alphacephei.com/vosk/models/vosk-model-small-de-0.15.zip

**Comment by jamesoliver1981** [comment]
Nice.  Will check them out. Let me know if there is documentation to be using to get these answers instead of posting issues.

The grammar should be a list per phrase, 
'[["second"], ["serve"], ["love"]]
or just a list as I wrote it? like so
'["second", "serve", "love", "fifteen", "mistake", "thirty", "winner"]'

**Comment by nshmyrev** [comment]
Hello.

Documentation is here:

https://github.com/alphacep/vosk-api/blob/91a128b3edf7e84d55649d8fa9a60664b5386292/src/vosk_api.h#L114

Example is here:

https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py

**Comment by jamesoliver1981** [comment]
Just to confirm this has worked superbly now...  Thanks again for the amazing responsiveness here.

It wasn't entirely clear to me how to me from the docs about how to structure the grammar, but this has worked for me: 
```
        rec = KaldiRecognizer(model, wf.getframerate(), 
                '["love", "fifteen","thirty","forty","deuce", "mistake","winner","double fault", "second", "serve", "let"," my advantage"]')
```

**Comment by nast90210** [comment]
> Small model for German supports grammars:
> 
> https://alphacephei.com/vosk/models/vosk-model-small-de-0.15.zip

Does big russian model support grammars?

**Comment by nshmyrev** [comment]
> Does big russian model support grammars?

https://alphacephei.com/vosk/models/vosk-model-ru-0.10-lgraph.zip

**Comment by abnerjacobsen** [comment]
Hi,

The portuguese model support grammars ?

**Comment by nshmyrev** [comment]
> The portuguese model support grammars ?

Yes
