### ISSUE TITLE
Improving Russian model

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#501]
Hi,

I'm using `vosk-api` (modified Python examples) to create subtitles for recordings done by `Olympus WS-852` voice recorder with `vosk-model-ru-0.10.zip`. The software works but real speech recognition is very poor. I want to improve the existing model. Where should I start from? Which licensing method will be applied in case I improve the model? I'm working on FOSS, so GPL/BSD/CC or PD licensing would be nice.

**Comment by nshmyrev** [comment]
You can start with providing a sample of the audio you want to recognize:

https://alphacephei.com/vosk/accuracy

**Comment by nshmyrev** [comment]
Feel free to reopen once you have the data files.
