### ISSUE TITLE
there are something for android and java 

### ISSUE THREAD

**Issue by zhangxincheng** [alphacep/vosk-api#504]
1、use the latest version ,when build it has the tips:can't find lib
2、use the old version,has the tips:"can't find the kaldi.mk"
so can someone write the steps to build aar for android or java ?tks
by the way,how to join the wechat group?
my qq is  1181383822

**Comment by nshmyrev** [comment]
> 1、use the latest version ,when build it has the tips:can't find lib

First build-kaldi.sh, then gradle build

> my qq is 1181383822

I sent you the friend request
