### ISSUE TITLE
How to do transfert Learning

### ISSUE THREAD

**Issue by Asma-droid** [alphacep/vosk-api#505]
Hello,

In my point of the view, the documentations of how to train our own model in vosk as well as how to fine tune pre-trained model (transfert Learning) are not very clear.

I ask if it will possible to provide some additional information

Thanks

**Comment by nshmyrev** [comment]
Sure, you can subscribe for the issue https://github.com/alphacep/vosk-api/issues/185 to get updates on this problem.
