### ISSUE TITLE
[Finetuning] Input files for russian model

### ISSUE THREAD

**Issue by LuggerMan** [alphacep/vosk-api#506]
Hello!
I am trying to implement daanzu`s finetuning script, but it demands:

Required Inputs:
data/finetune (text wav.scp utt2spk)
   src_dir
   tree_dir (tree final.mdl ali.*.gz phones.txt)
   lang_dir (oov.int L.fst words.txt phones.txt phones/disambig.int)
   conf_dir (mfcc.conf mfcc_hires.conf)
  extractor_dir (final.ie final.dubm final.mat global_cmvn.stats splice_opts online_cmvn.conf online_cmvn_iextractor?)

Can i have ali.*.gz files for big and small russian models and extractor_dir files?

**Comment by nshmyrev** [comment]
We didn't release these files to public yet. Tracked at https://github.com/alphacep/vosk-api/issues/185
