### ISSUE TITLE
[Rescoring] Rnnlm

### ISSUE THREAD

**Issue by LuggerMan** [alphacep/vosk-api#507]
How do i get a recompiled rnnlm rescoring files when updating my vocab, and do i need it?

**Comment by nshmyrev** [comment]
> How do i get a recompiled rnnlm rescoring files when updating my vocab

https://github.com/kaldi-asr/kaldi/blob/master/scripts/rnnlm/change_vocab.sh

> and do i need it?

Vosk doesn't support rnnlm yet, you can use it with the kaldi binaries. See https://github.com/alphacep/vosk-api/issues/75
