### ISSUE TITLE
【中文模型微调】How to finetune chinses mdel: vosk-model-cn-0.1.zip? Has anyone tried it?

### ISSUE THREAD

**Issue by Muzzypepper** [alphacep/vosk-api#511]
I am a newcomer in the field of speech recognition,  I want to finetune the chinese model: vosk-model-cn-0.1， but there are few related materials, I hope my seniors can give some guidance。

请问有大佬微调过vosk中文模型 vosk-model-cn-0.1吗，求指教！

**Comment by JINHXu** [comment]
Same question here, the Chinese model does not do well with transcribing numbers, if anyone has done related work, experience sharing would be appreciated!

求问有没有大佬搞过中文模型stt识别数字的fine-tune啊，求指教！

Cheers,
JX

**Comment by nshmyrev** [comment]
Hi

We going to retrain Chinese model soon for significantly better accuracy. If you are interesting in cooperation, submit a test set for your tasks so we can debug the accuracy.

**Comment by JINHXu** [comment]
> Hi
> 
> We going to retrain Chinese model soon for significantly better accuracy. If you are interesting in cooperation, submit a test set for your tasks so we can debug the accuracy.

Hi! 

This is exciting news! Thank you! Should I send it to your gmail?

**Comment by nshmyrev** [comment]
Yes, you can contact me at nshmyrev@gmail.com or nshmyrev@alphacephei.com.

**Comment by JINHXu** [comment]
> Yes, you can contact me at [nshmyrev@gmail.com](mailto:nshmyrev@gmail.com) or [nshmyrev@alphacephei.com](mailto:nshmyrev@alphacephei.com).

btw can I ask when will the new retrained model be released? We sort of have a deadline here :P 
Again, thank you very much for the hard work!

**Comment by nshmyrev** [comment]
> btw can I ask when will the new retrained model be released? We sort of have a deadline here :P

No you can't ask for deadlines for free software.

**Comment by JINHXu** [comment]
> > btw can I ask when will the new retrained model be released? We sort of have a deadline here :P
> 
> No you can't ask for deadlines for free software.

Chill, not asking for a deadline, just wondering if there might be a release date that we can be looking at, so we can consider all our options. Cheers!

**Comment by nshmyrev** [comment]
Still pending, tracked at #731
