### ISSUE TITLE
Using acoustic model from Pocketsphinx

### ISSUE THREAD

**Issue by Dominapp** [alphacep/vosk-api#512]
I have a well trained acoustic model that I'm using today in my android app. Is this possible to convert it to vosk?
I only use it for wake-word logic.

**Comment by nshmyrev** [comment]
We do not support keyword spotting in vosk yet. You can subscribe for updates to the issue https://github.com/alphacep/vosk-api/issues/107

It is not possible to convert pocketsphinx model to vosk. Even default Vosk model is order of magnitude more accurate than pocketsphinx, you'd better use vosk models as is.

**Comment by Dominapp** [comment]
Thanks Nikolay!
I Actually got a great results in vosk in English but I have a specific Phrase in Hebrew which I trained on pocketsphinx that works well but with a lot of false positive.
Can you refer me to a guide on how to make an adaptation to the acoustic mode in vosk?

**Comment by nshmyrev** [comment]
> Can you refer me to a guide on how to make an adaptation to the acoustic mode in vosk?

We do not recommend adaptation, if model is trained well enough it should work out of box.

**Comment by nshmyrev** [comment]
I suppose it is solved now.
