### ISSUE TITLE
Vosk-api Github Enhancement

### ISSUE THREAD

**Issue by sadrasabouri** [alphacep/vosk-api#518]
Hi.
Thanks for your wonderful API at the first place.
I found some important points that considering them can make it more easy to contribute to vosk-api.

Since vosk-api seems to be a really potential API for near future:
+ Merging pull requests to `master` doesn't seem to be a good approach since most of users clone into repository and start to use `master` branch. Changing `master` with high rate can be confusing for users (Including my experience :smile:). I recommend using `dev` branch instead and merging new pull requests or changes to it and then merging `dev` to `master` just for a releasing.
+ Adding a `CHANGELOG.md` file so that users can keep track of changes.
+ Adding more tests for each part (and using Github Actions instead of Travis)
+ Completing the `README.md` file so that it could be more helpful

<hr>

By the way I'm ready to help if you are OK with these changes.

**Comment by nshmyrev** [comment]
Hi

More tests would be nice. 

As for master issue/changelog, vosk is quickly advancing libraries in the process of active development. We focus more on accuracy/latency/throughput issues and languages support as well as on application needs. I don't think we need changelog urgently.

**Comment by sadrasabouri** [comment]
I see
thank you for your quick response.

**Comment by solyarisoftware** [comment]
Hi @sadrasabouri, 

just a minor note: I believe these are not issues (bugs), and [github discussions](https://docs.github.com/en/discussions), if enabled by the project owner, would probably be a better place to convey them. 

@nshmyrev Just as a possible option, if you want to take away notes like this issue: it' very easy to create the github discussions section in your project, just flag the feature here: https://github.com/solyarisoftware/vosk-api/settings

**Comment by nshmyrev** [comment]
Thank you, I think it is ok as is, you can freely discuss your issues here.
