### ISSUE TITLE
Chinese model: difficulty transcribing numbers

### ISSUE THREAD

**Issue by JINHXu** [alphacep/vosk-api#519]
Hey there,

I was trying to build a Chinese stt system with vosk, through I found the model does not do well in transcribing numbers in Chinese. I was wondering anyone has done related work regarding this issue and would like to share your solutions? It would be really appreciated!

Cheers,
JX

**Comment by nshmyrev** [comment]
Hey, you already asked at https://github.com/alphacep/vosk-api/issues/511, I answered you there. If you want to work on accuracy you'd better share a test set to demonstrate your problems.

**Comment by JINHXu** [comment]
Hi! Just saw it. Talk to you there. Thank you!
