### ISSUE TITLE
AcceptWaveform called after InputFinished() was called.

### ISSUE THREAD

**Issue by gklasen** [alphacep/vosk-api#52]
I am getting the above error when using vosk 0.3.3 within a Python Flask Server. The API should be addressed when i call a certain route.

I already initialized Model and KaldiRecognizer on startup to save some time when the route is called. 
First time, it is working fine and fast, but then i get the error. 

It seems that KaldiRecognizer has "CleanUp()"-method, but it is private. Do i really need to re-init the Recognizer every call or is there an easier way, like deepcopying?

**Comment by nshmyrev** [comment]
> Do i really need to re-init the Recognizer every call

Yes

> call or is there an easier way, like deepcopying?

Recognizer is lightweight, it is perfectly fine to reinit it. Our server does it for every new connection.

**Comment by gklasen** [comment]
My bad, the delay was caused by "Model", which still can be initialized at the beginning. I was assuming "KaldiRecognizer" is the reason, but indeed very lightweight. Thanks
