### ISSUE TITLE
Android documentation on speaker recognition

### ISSUE THREAD

**Issue by ian-yang-02** [alphacep/vosk-api#522]
I am doing some work with compiling Vosk for Android, and there seems to not be many resources on how to get a model working in something like Android Studio. Are we supposed to combine the existing Android Demo with the vosk-api/android folder or something similar? I am having trouble getting anything working with the existing code.
Edit: Also, I would like to use Vosk for Speaker Recognition more than Speech Transcription, which is where I am having issues with the provided Android Demo (as it does not seem to implement speaker recognition technology)

**Comment by nshmyrev** [comment]
You need to describe your problem in more detail in order to get help - what did you try, what particular problem do you see and so on.

**Comment by nshmyrev** [comment]
@ian-yang-02 feel free to reopen if you need more help.

As for using vosk for speaker recognition, you just load speaker model and submit it to recognizer constructor, it will work. This constructor:

https://github.com/alphacep/vosk-api/blob/67896cfba7526adae97a05ef40d9bacfc232a11c/java/lib/src/main/java/org/vosk/Recognizer.java#L10

**Comment by ian-yang-02** [comment]
Apologies, I wasn't very clear with my original question.

The README file for the vosk-android-demo project that exists already says that the demo implements speaker verification, and I was wondering if it was necessary to import the necessary functionality from this repo or whether the demo project already contained the functionality, and I simply could not find it. 

Also, I am quite new to Android development. I am trying to take in speaker audio (not an existing audio file) and use the speaker verification to compare it to an existing database of audio files. I am comfortable creating the speaker models, but I am not sure how to write to a model to compare with the existing speaker models using the given functionality. The vosk-android-demo as it comes uses the recognition as I would like (live input of audio) but I am not sure how to generate a model from that input to compare and verify speaker. 

I have this right now in the VoskActivity.java class in the android-demo project, but I am sure I am not doing it correctly:

 private void recognizeSpeaker() {
    	Model model = new Model(/*model path*/);
        //how to receive model data??
    	SpeakerModel spkmod = new SpeakerModel(/*path*/);
    	Recognizer recog = new Recognizer(model, spkmod, 16000.0f);
    	recog.getResult(); //does this return the speaker?
    }

Thanks for this wonderful project, I have learned a lot already and am happy to keep working and debugging.

**Comment by nshmyrev** [comment]
> Thanks for this wonderful project, I have learned a lot already and am happy to keep working and debugging.

Try to ask one question at a time, I'll answer it. Before asking the question try to identify speakers on desktop with prerecorded files.

**Comment by ian-yang-02** [comment]
Would it be possible to provide a step-by-step process for implementing speaker verification in the android demo app? The more I continue attempting implementation the more problems I seem to have.

**Comment by nshmyrev** [comment]
> Would it be possible to provide a step-by-step process for implementing speaker verification in the android demo app?

No, you have to try yourself first.

**Comment by ian-yang-02** [comment]
Okay, does the existing Android Demo app support speaker identification or do I need to create a new runnable class altogether?

**Comment by nshmyrev** [comment]
> or do I need to create a new runnable class altogether?

You have to modify the demo code and add the model for speaker identification in assets

**Comment by ian-yang-02** [comment]
> model for speaker identification

This is the vosk-model-spk-04 speaker model downloadable from the alphacephei website, correct?

**Comment by ian-yang-02** [comment]
This is what I have tried recently:

I initialized a SpeakerModel variable as so: 
`private SpeakerModel spkMod = new SpeakerModel("spk-model");`
(spk-model is the name of the folder I downloaded from the alphacephei website, inside the .../vosk-android-demo/models/src/main/assets/ folder)

I also adjusted the Recognizer constructor in the recognizeMicrophone() method, as so:
`private void recognizeMicrophone() {
        if (speechService != null) {
            setUiState(STATE_DONE);
            speechService.stop();
            speechService = null;
        } else {
            setUiState(STATE_MIC);
            try {
                **Recognizer rec = new Recognizer(model, spkMod, 16000.0f);**
                speechService = new SpeechService(rec, 16000.0f);
                speechService.startListening(this);
            } catch (IOException e) {
                setErrorState(e.getMessage());
            }
        }
    }`

Now, however, Android Studio crashes upon opening the app each time. Here is the logcat

![image](https://user-images.githubusercontent.com/82423739/117616033-9326a380-b138-11eb-87db-89a88d942f09.png)

Not sure what is happening anymore... Do I need to repackage the speaker model?

**Comment by nshmyrev** [comment]
There is additional information in logcat about reason of this assert failure. You can find it few lines below the last line you pasted.

**Comment by ian-yang-02** [comment]
Hm.. it looks like for me this is the entire logcat output.

![image](https://user-images.githubusercontent.com/82423739/117618911-9b80dd80-b13c-11eb-8399-ca7f126d5733.png)

Which line are you referencing?

**Comment by ian-yang-02** [comment]
Does there need to be a method that initializes the SpeakerModel, similar to the initModel() method? I'm not sure why the Speaker Model isn't being recognized otherwise.

**Comment by ian-yang-02** [comment]
I have attempted to make the changes I mentioned above, by including this method in the StorageService class:
`public static void unpackS(Context context, String sourcePath, final String targetPath, final Callback<SpeakerModel> completeCallback, final Callback<IOException> errorCallback) {
        Executor executor = Executors.newSingleThreadExecutor(); // change according to your requirements
        Handler handler = new Handler(Looper.getMainLooper());
        executor.execute(() -> {
            try {
                final String outputPath = sync(context, sourcePath, targetPath);
                SpeakerModel model = new SpeakerModel(outputPath);
                handler.post(() -> completeCallback.onComplete(model));
            } catch (final IOException e) {
                handler.post(() -> errorCallback.onComplete(e));
            }
        });
    }`
and adding this method into the VoskActivity.java class:
`private void initSpk() {
        StorageService.unpackS(this, "spk-model", "spkMod",
                (spkMod) -> {
                    this.spkMod = spkMod;
                    setUiState(STATE_READY);
                },
                (exception) -> setErrorState("Failed to unpack the model" + exception.getMessage()));
    }`

along with this line:
`else {
            initModel();
            initSpk();
        }`
under onCreate().

I am now receiving this error:
![image](https://user-images.githubusercontent.com/82423739/117667030-773ff380-b172-11eb-819e-6d5a69c5c874.png)

I understand that the method cannot be found and that's why there seems to be an error. I'm not sure why it's throwing a NoSuchMethodError though. The StorageService class is in the same directory as the VoskActivity.java class.

**Comment by ian-yang-02** [comment]
Sorry for the many comments - this is my largest project to date and I am eager to make quick progress. I believe I have gotten the model to work, here is my logcat:

![image](https://user-images.githubusercontent.com/82423739/117670273-bae82c80-b175-11eb-9a2b-a2e3cd1c48e0.png)

I was able to achieve the result by adding the unpackS() method from above into the VoskActivity.java class to be able to call it directly, along with supporting methods. Does this seem to be the correct output?

//Now my question is: how would I go about creating a database of voice files to compare speakers to? How would I receive the output result of who the speaker is, based on an ID such as "speaker 1" or "speaker: ian-yang-02"//  ignore

I think a better question now is how would I be able to extract vector data from my own .wav files and collect the vector data from the speaker model? I will use the cosine distance to calculate similarity, but I am unsure on how to retrieve the data in the first place.

Thanks for the help, I await your response.

**Comment by ian-yang-02** [comment]
Followup to previous post^
Where in the functionality allows collecting vector data from existing .wav files?

**Comment by nshmyrev** [comment]
> by including this method in the StorageService class

It was not necessary, you could use the existing code to unpack.

> Where in the functionality allows collecting vector data from existing .wav files?

Recognition from a file demonstrated here: https://github.com/alphacep/vosk-android-demo/blob/248f40de2449a6185a9e7b3fb9d985aa5221312c/app/src/main/java/org/vosk/demo/VoskActivity.java#L216, it returns a speaker vector from a file.

**Comment by ian-yang-02** [comment]
Is there a built-in functionality to train the speaker model given multiple different utterances by the same speaker? I would like to have one x-vector to represent each speaker, if possible.

**Comment by nshmyrev** [comment]
> Is there a built-in functionality to train the speaker model given multiple different utterances by the same speaker? I would like to have one x-vector to represent each speaker, if possible.

Yes, you use the same recognition methods to extract speaker xvectors

**Comment by ian-yang-02** [comment]
I'm not sure I understand ... what kind of computations are done to create a single vector given multiple audio files?

**Comment by nshmyrev** [comment]
> I'm not sure I understand ... what kind of computations are done to create a single vector given multiple audio files?

You can average xvectors to get a single xvector. You can also store them all and compare separately or you can store them all and compare with plda. There are different strategies which might need testing.

**Comment by ian-yang-02** [comment]
Thanks, I will try averaging the vectors

**Comment by ian-yang-02** [comment]
Is there a way to easily enroll speaker data into some kind of database? Other ASR projects have some type of enroll and test scripts - is there something similar that exists in Vosk?

**Comment by nshmyrev** [comment]
> Other ASR projects have some type of enroll and test scripts - is there something similar that exists in Vosk?

Please share a link, we'll do the same.

**Comment by ian-yang-02** [comment]
Sure, something like is seen [here](https://github.com/qianhwan/KaldiBasedSpeakerVerification.git)

**Comment by nshmyrev** [comment]
Lets track in #405

**Comment by UnstoppableCurry** [comment]
> 
![image](https://user-images.githubusercontent.com/65523997/172570031-6da9b853-3e50-48d3-b887-85198845d412.png)
The above steps are followed, but the error is still reported. The path loading shows that the UUID cannot be found. Secondly, the error is still reported as null after the corresponding path is put into speakmdoel (path). Is this the wrong model I found on the official website or other reasons

**Comment by nshmyrev** [comment]
> The path loading shows that the UUID cannot be found

UUID is created by gradle, see the demo project.

>  the error is still reported as null after the corresponding path is put into speakmdoel (path)

Probably you do not unpack files properly.

**Comment by Freelancingonupwork** [comment]
Hello @nshmyrev i.m getting this error: 
`org.vosk.demo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xac in tid 27919 (org.vosk.demo), pid 27919 (org.vosk.demo)`

Here's the code for `build.gradle` file:

    tasks.register('genUUID') {
    def uuid = UUID.randomUUID().toString()
    def spkdir = file("$buildDir/generated/assets/vosk-model-spk-0.4")
    def odir = file("$buildDir/generated/assets/model-en-us")
    def spkfile = file("$spkdir/uuid")
    def ofile = file("$odir/uuid")
    doLast {
        mkdir odir
        mkdir spkdir
        ofile.text = uuid
        spkfile.text = uuid
    }
}

For preparing Speaker Model, I've created this two methods in `VoskActivity.java` class: 

    private void initSpk() {
        unpackS(this, "vosk-model-spk-0.4", "spkMod", (spkMod) -> {
            this.speakerModel = spkMod;
            setUiState(STATE_READY);
        }, (exception) -> setErrorState("Failed to unpack Speaker model" + exception.getMessage()));
    }

and 

    public static void unpackS(Context context, String sourcePath, final String targetPath, final StorageService.Callback<SpeakerModel> completeCallback, final StorageService.Callback<IOException> errorCallback) {
        Executor executor = Executors.newSingleThreadExecutor();
        Handler handler = new Handler(Looper.getMainLooper());
        executor.execute(() -> {
            try {
                final String outputPath = StorageService.sync(context, sourcePath, targetPath);
                SpeakerModel model = new SpeakerModel(outputPath);
                handler.post(() -> completeCallback.onComplete(model));
            } catch (IOException e) {
                handler.post(() -> errorCallback.onComplete(e));
            }
        });
    }

and this is try - catch block from method `recognizeMicrophone()`:

    try {
                Recognizer rec = new Recognizer(model, 16000.0f, speakerModel);
                speechService = new SpeechService(rec, 16000.0f);
                speechService.startListening(this);
            } catch (IOException e) {
                setErrorState(e.getMessage());
            }

Can you please help me to solve this error, i've tried a lot but still error is there, Thank You in Advance..

**Comment by Freelancingonupwork** [comment]
So i just made minor changes to my code and now it's working, i'm posting it so it can be helpful for someone:

    Recognizer rec = new Recognizer(model, 16000.0f);
    rec.setSpeakerModel(speakerModel);
