### ISSUE TITLE
ASSERTION FAILED crash on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by Phasor1** [alphacep/vosk-api#524]
I tried to install vosk-api on a Raspberry Pi Zero W using the ``` test_ffmpeg.py ``` passing a .wav mono file with some italian words inside.
My process was this:

- Successful Installation of the Python library from the .whl file (vosk-0.3.3-cp37-cp37m-linux_armv6l.whl)
- Successful Download of the Italian language model from [this](https://alphacephei.com/vosk/models) link, the file ***vosk-model-small-it-0.4***.
    - After this, I saw some errors on some files (``` Can't open file: model/HCLr.fst ``` and ``` Can't open file: model/HCLr.fst ```) and I fixed them by copying those files to the ``` /model ``` folder
- Running the script, it returns some errors after trying the recognize process, without showing any words on partials results. 

I know the audio file is correct because the same code, audio file and model works perfectly on Windows 10, recognizing the right words.
The error seems to come from the Kaldi library. 
I also tried to change the bit depth of the audio file, but this was not successful at repairing the error.
Is this error caused by the audio file or by the model used in the script of the Raspberry library?  
Here's the complete log:

```
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
ASSERTION_FAILED (vosk[5.5.643~3-7e185]:TransitionIdToPhone():transition-model.cc:786) Assertion failed: (trans_id != 0 && static_cast<size_t>(trans_id) < id2state_.size())

[ Stack-Trace: ]
/usr/local/lib/python3.7/dist-packages/vosk/_vosk.so(kaldi::MessageLogger::LogMessage() const+0x8e4) [0xb64d0180]
/usr/local/lib/python3.7/dist-packages/vosk/_vosk.so(kaldi::KaldiAssertFailure_(char const*, char const*, int, char const*)+0x60) [0xb64d0e94]
/usr/local/lib/python3.7/dist-packages/vosk/_vosk.so(kaldi::TransitionModel::TransitionIdToPhone(int) const+0x58) [0xb63f9338]
/usr/local/lib/python3.7/dist-packages/vosk/_vosk.so(kaldi::OnlineSilenceWeighting::GetDeltaWeights(int, int, std::vector<std::pair<int, float>, std::allocator<std::pair<int, float> > >*)+0x1b0) [0xb61a5634]
/usr/local/lib/python3.7/dist-packages/vosk/_vosk.so(KaldiRecognizer::UpdateSilenceWeights()+0xb0) [0xb614a6a8]
/usr/local/lib/python3.7/dist-packages/vosk/_vosk.so(KaldiRecognizer::AcceptWaveform(kaldi::Vector<float>&)+0x30) [0xb614af2c]
/usr/local/lib/python3.7/dist-packages/vosk/_vosk.so(KaldiRecognizer::AcceptWaveform(char const*, int)+0x6c) [0xb614afe4]
/usr/local/lib/python3.7/dist-packages/vosk/_vosk.so(+0x1f0578) [0xb6149578]
```

Thank you

**Comment by nshmyrev** [comment]
You didn't copy some required files.

In general, you'd better use newer version, it will work with this model without file copy, you can try

https://github.com/alphacep/vosk-api/releases/download/0.3.15/vosk-0.3.15-cp37-cp37m-linux_armv6l.whl

Raspberry Pi Zero is probably too slow to run Vosk, you can only recognize few words with grammar.

**Comment by Phasor1** [comment]
The ***newer version*** (https://github.com/alphacep/vosk-api/releases/download/0.3.15/vosk-0.3.15-cp37-cp37m-linux_armv6l.whl) worked perfectly, thank you so much!
Yeah, it's true that the Pi Zero is a bit slow, i will see if i can use a more powerful one. 
Thank you again!
