### ISSUE TITLE
Вероятно утечка памяти [Probably a memory leak]

### ISSUE THREAD

**Issue by olegk0** [alphacep/vosk-api#526]
Здравствуйте

Я в своем приложении на с++ в отдельном потоке постоянно распознаю данные с микрофона.
и получаю постоянно  увеличение потребления памяти, 
расход зависит от распознаваемых фраз, до 300 мегабайт в час

структура программы такая

```
Vosk::Init()
{
    model = vosk_model_new("./Vosk/rec-model");
    recognizer = vosk_recognizer_new(model, 16000.0);

   thread_work = true;
   ...  // start thread
}

Vosk::thread_loop()
{
    while (thread_work)  {
	char *next_buf = ...

        int final = vosk_recognizer_accept_waveform(recognizer, next_buf, SND_BUF_SIZE);
	if (final) {
		printf("result:%s\n", vosk_recognizer_result(recognizer));
        } else {
		printf("partial:%s\n", vosk_recognizer_partial_result(recognizer));
	}

    }
}

```
используется библиотека libvosk.so  из vosk-0.3.21-py3-none-manylinux2010_x86_64.whl

**Comment by olegk0** [comment]
Утечка пропадает если периодически полностью переинициализировать  библиотеку
типа

```
Vosk::Init()
{
    model = vosk_model_new("./Vosk/rec-model");
    recognizer = vosk_recognizer_new(model, 16000.0);

   thread_work = true;
   ...  // start thread
}

Vosk::thread_loop()
{
    while (thread_work)  {
	char *next_buf = ...

        int final = vosk_recognizer_accept_waveform(recognizer, next_buf, SND_BUF_SIZE);
	if (final) {
		printf("result:%s\n", vosk_recognizer_result(recognizer));
		vosk_recognizer_free(recognizer);
		vosk_model_free(model);
		model = vosk_model_new("./Vosk/rec-model");
		recognizer = vosk_recognizer_new(model, 16000.0);
        } else {
		printf("partial:%s\n", vosk_recognizer_partial_result(recognizer));
	}

    }
}

```
переинициализация только recognizer ( vosk_recognizer_new )  - не помогает

**Comment by LuggerMan** [comment]
Релиз новый? там пару месяцев назад коммит был. vosk_recognizer_free юзаем?

**Comment by olegk0** [comment]
Релиз 0.3.21 кажется последний.

я кажется поспешил, вероятно это не утечка а такой режим работы.

Я провел эксперимент с версией из первого сообщения. Повесил микрофон на ТВ.
такая хронология потребления памяти

минута  мегабайт
0 230
2 300
4 360
8 420
12 446
30 470

т.е. потребление памяти по убывающей.
как будто библиотека постепенно разворачивается в память

**Comment by olegk0** [comment]
Второй этап теста. 
Теперь с примером из второго сообщения с переинициализацией через vosk_model_free

минута мегабайт
0  230
2  370
8  392
16  398
70  400

видимо  vosk_model_free не освобождает полностью память

**Comment by olegk0** [comment]
Последний этап

```
Vosk::thread_loop()
{
    while (thread_work)  {
	char *next_buf = ...

        int final = vosk_recognizer_accept_waveform(recognizer, next_buf, SND_BUF_SIZE);
	if (final) {
		printf("result:%s\n", vosk_recognizer_result(recognizer));
		vosk_recognizer_free(recognizer);
		recognizer = vosk_recognizer_new(model, 16000.0);
        } else {
		printf("partial:%s\n", vosk_recognizer_partial_result(recognizer));
	}

    }
}

```
минута мегабайт
0 230
2 302
10 308
15 308
20 308

стабилизировался размер

по видимому это рабочий вариант

**Comment by nshmyrev** [comment]
```
		printf("result:%s\n", vosk_recognizer_result(recognizer));
		vosk_recognizer_free(recognizer);
		recognizer = vosk_recognizer_new(model, 16000.0);
```

так нельзя делать, существенно падает точность.

> расход зависит от распознаваемых фраз, до 300 мегабайт в час

Не вижу этого в цифрах. Небольшое увеличение использования памяти до 0.5Гб в норме.

Отладить использование памяти можно с помощью подключаемой библиотеки tcmalloc.

**Comment by olegk0** [comment]
> так нельзя делать, существенно падает точность.

Спасибо понятно, потестирую.
 
> Не вижу этого в цифрах. Небольшое увеличение использования памяти до 0.5Гб в норме.

Ясно, я просто не ожидал этого. 

У меня просто домашний проект на АРМ плате с ограниченной памятью 1Гб.

**Comment by nshmyrev** [comment]
> У меня просто домашний проект на АРМ плате с ограниченной памятью 1Гб.

Если ограничивать набор слов как в test_words.py, памяти будет использовать гораздо меньше.

**Comment by olegk0** [comment]
> Если ограничивать набор слов как в test_words.py, памяти будет использовать гораздо меньше.

Спасибо за подсказку, посмотрю.
