### ISSUE TITLE
rec.AcceptWaveform always returns false

### ISSUE THREAD

**Issue by gklasen** [alphacep/vosk-api#527]
Any mistake i am doing in configuration?

On client side, i use [RecordRTC](https://github.com/muaz-khan/RecordRTC) for recording and send it to my Python-Flask-Server as base64:

```
recorder = new RecordRTC(stream, {
  desiredSampRate: 16000,
  mimeType: 'audio/wav',
  numberOfAudioChannels: 1,
  recorderType: RecordRTC.StereoAudioRecorder,
  type: 'audio',
});
```

Server:

```
base64audio = request.get_json()['audio']  //from JSON param of RESTful call
base64audio = base64audio.replace('data:audio/wav;base64,','')     

file = wave.open('userinput.wav', 'wb')
file.setnchannels(1)
file.setsampwidth(2)
file.setcomptype("NONE","not compressed")
file.setframerate(44100)
file.writeframes(base64.b64decode(base64audio))
file.close()

wf = wave.open("userinput.wav", "rb")
rec = KaldiRecognizer(modelInitedEarlier, 16000)

while True:
    data = wf.readframes(4000)
    print(rec.AcceptWaveform(data))    // Always 0 / false
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        print(rec.Result())
    else:
        print(rec.PartialResult())
print (rec.FinalResult())
```

**Comment by nshmyrev** [comment]
Did you listen the audio? Probably it is silent.

Asfor base64,it is a waste of bandwidth, you'd better use opus codec.

**Comment by gklasen** [comment]
The audio has correct sound, unfortunately.

**Comment by nshmyrev** [comment]
Ok. If there was no silence you should always get 0 and you can get result in FinalResult, I don't see an issue here.

**Comment by gklasen** [comment]
okay, i thought that it needed to be 1. Maybe wrong issue description then. But rec.FinalResult() never is printed then, or rec.PartialResult always is empty.

**Comment by nshmyrev** [comment]
From your code I see you write the sample rate 44100 but you init recognizer with rate 16000, it should be the same rate probably.

**Comment by gklasen** [comment]
changed everything to 16000.

Maybe the re-initailization of the recognizer? I reinit it every call with one kaldimodel inited at the beginning. also always getting this log AFTER potential "partial" logs. Is this async and maybe too slow in initialization? I am running within Docker Desktop.

```
{
  "partial" : ""
}
```
....
> LOG (VoskAPI:ReadDataFiles():model.cc:196) Decoding params beam=10 max-active=3000 lattice-beam=2
> LOG (VoskAPI:ReadDataFiles():model.cc:199) Silence phones 1:2:3:4:5:6:7:8:9:10
> LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
> LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
> LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
> LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.027734 seconds in looped compilation.
> LOG (VoskAPI:ReadDataFiles():model.cc:223) Loading i-vector extractor from /app/stt-models/vosk-small-en/ivector/final.ie
> LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
> LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
> LOG (VoskAPI:ReadDataFiles():model.cc:258) Loading HCL and G from /app/stt-models/vosk-small-en/graph/HCLr.fst /app/stt-models/vosk-small-en/graph/Gr.fst
> LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading winfo /app/stt-models/vosk-small-en/graph/phones/word_boundary.int
> LOG (VoskAPI:ReadDataFiles():model.cc:196) Decoding params beam=10 max-active=3000 lattice-beam=2
> LOG (VoskAPI:ReadDataFiles():model.cc:199) Silence phones 1:2:3:4:5:6:7:8:9:10
> LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
> LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
> LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
> LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00652099 seconds in looped compilation.
> LOG (VoskAPI:ReadDataFiles():model.cc:223) Loading i-vector extractor from /app/stt-models/vosk-small-fr/ivector/final.ie
> LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
> LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.

**Comment by nshmyrev** [comment]
> changed everything to 16000.

If you received 44100 from the web you can not change to 16000. Listen the audio again.

**Comment by gklasen** [comment]
I am confused. 

I am using code below to record, where i even force sample rate to be 16000. it cant be 44100.
```

recorder = new RecordRTC(stream, {
  desiredSampRate: 16000,
  mimeType: 'audio/wav',
  numberOfAudioChannels: 1,
  recorderType: RecordRTC.StereoAudioRecorder,
  type: 'audio',
});
```

**Comment by nshmyrev** [comment]
> desiredSampRate

It is usually desired not forced. Did you check the actual audio file like I told you several times? Does it have the proper format?

**Comment by gklasen** [comment]
Sorry, i did check, as you asked if it is silent, it always has valid sound.

Analysis says:

![image](https://user-images.githubusercontent.com/17546555/117052253-ccfe4100-ad17-11eb-9435-f55b8186976f.png)

**Comment by nshmyrev** [comment]
Ok, looks good now. Does it return proper content for longer file?

**Comment by gklasen** [comment]
![image](https://user-images.githubusercontent.com/17546555/117060078-cde7a080-ad20-11eb-92fa-e37c7d4feb67.png)
 
Now a file with 2.4MiB. Same side information then above post. I also added additional info in this.

In both files, only calls "particial" only once and followed by these logs again:
```

{
  "partial" : ""
}
LOG (VoskAPI:ReadDataFiles():model.cc:196) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:199) Silence phones 1:2:3:4:5:6:7:8:9:10
...
```

This is why i was asking if maybe Recognizer Init finishes too late or something. Any other idea?

**Comment by nshmyrev** [comment]
> This is why i was asking if maybe Recognizer Init finishes too late or something. Any other idea?

it is hard to help you without looking on your code here.

**Comment by gklasen** [comment]
https://gitlab.inria.fr/comprise/comprise-personal-server/-/blob/text-transformation/server.py

The Vosk-Code is in "asr"-route, at the top of the file, multiple KaldiModels are initialised and safed in a dict before, depending on the language.

**Comment by nshmyrev** [comment]
Ok, I don't see anything harmful. The output can be buffered so might appear out of order.

**Comment by gklasen** [comment]
Resolved. I was generating the model with a shell-script, which needed to be encoded from CRLF to LF. On Docker for Win, this caused problems, so the model itself was malformed. Thank you for your support.
