### ISSUE TITLE
Dynamically creating spk_sig from current audio

### ISSUE THREAD

**Issue by iry47** [alphacep/vosk-api#529]
I'm implementing Vosk Speech recognition into an application. Looking specifically at the speaker recognition, I've implemented the test_speaker.py from the examples and it is functional. Being new to this, how can I identify and/or create the reference speaker signature? Using the one provided, the list of distances calculated with my audio example doesn't portray the two speakers involved:

`[1.0182311997728735, 0.8679279016022726, 0.8552687907177629, 1.0258941854519696, 0.8666933753723253, 0.9291881495586336, 1.0316585805917928, 1.0227699471036409, 0.8442800102809634, 0.9093189414477789, 0.9153723223264221, 0.9705387223260904, 0.9077720598812595, 0.9524431272217568, 0.9179475137290445]`

If there is not an effective way to calculate a reference speaker from within the audio under analysis, do you know of another solution that can be used with Vosk to identify speakers in an audio file? 

Thanks in advance

**Comment by nshmyrev** [comment]
The keyword to look for is "speaker diarization". There are many speaker diarization packages like pyannote, speechbrain, there is also speaker diarization in kaldi.

For online speaker diarization you need a chinese room algorithm, described and implemented in https://github.com/google/uis-rnn, not easy to implement and requires research though.

This question is tracked at #405

**Comment by iry47** [comment]
amazing, thank you for the explanation and sorry I missed the other issue.
