### ISSUE TITLE
Custom built models is not working properly

### ISSUE THREAD

**Issue by rohithkodali** [alphacep/vosk-api#53]
i have a few domain-specific acoustic and language models and vosk is unable to recognize properly, most of the time it gives empty result. 

model info:
sample frequency: 16000
model type: nnet3 (CNN-TDNN)
silence_phones: 1:2:3:4:5
pitch:false

**Comment by nshmyrev** [comment]
Cool, congratulations! Let us know if you need any help in fixing that.

**Comment by rohithkodali** [comment]
how can i find out where the issue is as the model working well in kaldi gstreamer server, onlne2-wav nnet3 latgen faster, kaldi online server etc, only with vosk it is behaving differently( no output)?  is it because of the model or any other issue?

**Comment by nshmyrev** [comment]
Most likely input data format is wrong.

**Comment by rohithkodali** [comment]
its the same audio format using everywhere 16khz 16-bit pcm format, even tried with microphone still the same issue. is there anything i need to check with endpoint silence phones?

**Comment by rohithkodali** [comment]
hi nicolay, 

   tried custom-built English model, the issue is same, recognition is not proper, most of time it is empty only even Audio has speech in it
trained on 1600 hours of data, working well with other decoders (online2-wav-nnet3-latgen-faster)
model info:
sample frequency: 16000
model type: nnet3 (CNN-TDNN)
silence_phones: 1:2:3:4:5
pitch:false

        "--endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10",
        feature_info_.silence_weighting_config.silence_phones_str = "1:2:3:4:5:6:7:8:9:10";
I tried changing at both these places in model.cc file but result was same.

**Comment by rohithkodali** [comment]
after removing the old vosk completely and installed and changing the silence phones list, English started working well. need to test with the other models
