### ISSUE TITLE
Raspberry PI 3 B+ Kaldi Docker Image Issues - Does not match host platform

### ISSUE THREAD

**Issue by mjrevel** [alphacep/vosk-api#530]
Having a bit of trouble following the Vosk [install guide](https://alphacephei.com/vosk/install). When I tried to get the latest Kaldi Docker image (alphacep/kaldi-en:latest) I received the error 

> WARNING: The requested image's platform (linux/amd64 does not match the detected host platform (linux/arm/v7)...

 I'm familiar with what this error means but there doesn't seem to be an image available with the cpu architecture I'm using.

For those running Vosk on a PI how did you get around this? Did you end up having to compile from source?

**Comment by nshmyrev** [comment]
You can install vosk with pip, then simply run server from git clone. There is no need to run docker in rpi3, it is very slow.

**Comment by solyarisoftware** [comment]
@mjrevel could you close the issue? :-)
