### ISSUE TITLE
AttributeError: cffi library  ''''''\vosk-api-master\python\vosk\libvosk.dll' has no function, constant or global variable

### ISSUE THREAD

**Issue by liukai123456789** [alphacep/vosk-api#531]
When I run test_microphone.py in pycharm,such an error will appear:AttributeError: cffi library  ''''''\vosk-api-master\python\vosk\libvosk.dll' has no function, constant or global variable named 'vosk_model_free','vosk_model_new'.Does anyone know how to solve it, version:vosk0.3.21

**Comment by nshmyrev** [comment]
Check if it works without pycharm.

**Comment by liukai123456789** [comment]
Thank you for your reply. I run it directly in cmd. It works normally. So I wonder why there is such a problem。

**Comment by nshmyrev** [comment]
Maybe it fails to find the library in path. You probably can add some debug prints to see where it looks for the library.
