### ISSUE TITLE
Reopen Android Docs

### ISSUE THREAD

**Issue by ian-yang-02** [alphacep/vosk-api#532]
#522 Reopened - inserted this reply:

"The README file for the vosk-android-demo project that exists already says that the demo implements speaker verification, and I was wondering if it was necessary to import the necessary functionality from this repo or whether the demo project already contained the functionality, and I simply could not find it.

Also, I am quite new to Android development. I am trying to take in speaker audio (not an existing audio file) and use the speaker verification to compare it to an existing database of audio files. I am comfortable creating the speaker models, but I am not sure how to write to a model to compare with the existing speaker models using the given functionality. The vosk-android-demo as it comes uses the recognition as I would like (live input of audio) but I am not sure how to generate a model from that input to compare and verify speaker.

I have this right now in the VoskActivity.java class in the android-demo project, but I am sure I am not doing it correctly:

private void recognizeSpeaker() {
Model model = new Model(/model path/);
//how to receive model data??
SpeakerModel spkmod = new SpeakerModel(/path/);
Recognizer recog = new Recognizer(model, spkmod, 16000.0f);
recog.getResult(); //does this return the speaker?
}

Thanks for this wonderful project, I have learned a lot already and am happy to keep working and debugging."

Thanks again.

**Comment by nshmyrev** [comment]
Hi. There is no need to create additional issues, you can continue discussion or reopen original problem #522
