### ISSUE TITLE
System sound not be heard

### ISSUE THREAD

**Issue by hossein1113** [alphacep/vosk-api#533]
I am using the python and it works quite well, my question is how can I make the system sounds not be heard, and just the external audio
Thanks

**Comment by nshmyrev** [comment]
on what OS/programming language?

**Comment by hossein1113** [comment]
@nshmyrev 
I am using ubuntu and python programming
I need somthing same this:
input = microphone_audioBlock - systemOutput_audioBlock

**Comment by nshmyrev** [comment]
There is an acoustic echo cancellation plugin in Pulseaudio which you can try:

https://wiki.archlinux.org/title/PulseAudio#Microphone_echo/noise_cancellation

It is not perfect algorithm, can be improved.

**Comment by hossein1113** [comment]
@nshmyrev
thanks.
