### ISSUE TITLE
RNNLM, training and decoding resource and time

### ISSUE THREAD

**Issue by lalimili6** [alphacep/vosk-api#534]
Hi, Dear
Thanks, for this code
some questions about RNNLM.

- I Kaldi we have TensorFlow-based RNNLM and recently PyTorch-based, which does support for RNNLM rescoring in VOSK?
   - can you link a egs in Kaldi or share your RNNLM training?
- can you explain your experiments in RNNLM? How many resources? latency? and results?
- At a glance, is RNNLM an optimal method compared with without rescoring or ARPA-rescoring? (latency + resource + results ... )

best regards

**Comment by nshmyrev** [comment]
> I Kaldi we have TensorFlow-based RNNLM and recently PyTorch-based, which does support for RNNLM rescoring in VOSK?

Vosk supports kaldi-native RNNLM (not tensorflow or pytorch). We try to stay within kaldi to avoid external dependencies.

> can you link a egs in Kaldi or share your RNNLM training?

https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/local/rnnlm/tuning/run_lstm_tdnn_1b.sh

> can you explain your experiments in RNNLM? How many resources? latency? and results?

It is slower but more accurate and more compact

> At a glance, is RNNLM an optimal method compared with without rescoring or ARPA-rescoring? (latency + resource + results ... )

Yes, it is superior.

**Comment by nshmyrev** [comment]
@lalimili6 close the issue if you have your questions answered

**Comment by lalimili6** [comment]
nice, many thanks
