### ISSUE TITLE
Sound Device Module Not Found (test_microphone.py)

### ISSUE THREAD

**Issue by ankerFromMarc** [alphacep/vosk-api#535]
When I try testing the real time recognition by wirting python test_microphone.py or python3 test_microphone.py I get this Error:
Traceback (most recent call last):
  File "test_microphone.py", line 6, in <module>
    import sounddevice as sd

I am struggeling on finding the problem.

**Comment by nshmyrev** [comment]
pip3 install sounddevice

**Comment by ankerFromMarc** [comment]
thank your very much <3
