### ISSUE TITLE
Getting the weight value from the speech model.

### ISSUE THREAD

**Issue by AssAssinsninja7** [alphacep/vosk-api#536]
Hello, I'm implementing a keyword detection with a MFCC and an NN to train the validation data. What I'm basically trying to do is extending the Vosk engine and specifically the speech model with my own data around the "Actual phrases" in relation to the speech models words (aka compare weights and adjust accordingly). This takes me to my problem, I need to access the weight value from grammar that matches the detected incoming sound/ text. Is there any way of accessing this through the engine or am I screwed?

I'm programming in C#, any help would mean the world.

**Comment by nshmyrev** [comment]
I'm not sure what do you mean by "weight". Probably you meant confidence of the results. Confidence is returned in json result, but it might not be perfect for keyword detection:

https://github.com/alphacep/vosk-api/blob/e6bd200c856346ff745d77eafc75d63528398833/src/vosk_api.h#L146

**Comment by AssAssinsninja7** [comment]
> I'm not sure what do you mean by "weight". Probably you meant confidence of the results. Confidence is returned in json result, but it might not be perfect for keyword detection:
> 
> https://github.com/alphacep/vosk-api/blob/e6bd200c856346ff745d77eafc75d63528398833/src/vosk_api.h#L146

Yeah sorry, by weight I mean the final coefficient's extracted from the incoming sound stream. As I mentioned I'm using MFCC coefficient extraction for reading and converting the incoming sound stream. But I'm not sure if the "confidence" matches this, if the way we get it is based on some other recognition technique. 

Note: My final weight/ recognition values for the words are normalized in between the range of 0 and 1. And its this value that I want to compare to the speech models "possibly" own coefficient values for each word detected.

**Comment by nshmyrev** [comment]
> Note: My final weight/ recognition values for the words are normalized in between the range of 0 and 1. And its this value that I want to compare to the speech models "possibly" own coefficient values for each word detected.

Confidence is also between 0.0 and 1.0, you can compare.

**Comment by AssAssinsninja7** [comment]
> > Note: My final weight/ recognition values for the words are normalized in between the range of 0 and 1. And its this value that I want to compare to the speech models "possibly" own coefficient values for each word detected.
> 
> Confidence is also between 0.0 and 1.0, you can compare.

Hmm, yes I noticed that. But how is the confidence reached? I'm assuming that you send in the recording and between which interval you want to look (start & end). Then the coefficient extraction does it's thing, returning the updated confidence? Or am I completely wrong?

 *       "conf" : 1.000000,
 *       "end" : 1.110000,
 *       "start" : 0.870000,

**Comment by nshmyrev** [comment]
To learn theory about confidence scoring you can read a classical paper:

Finding consensus in speech recognition: word error minimization and other applications of confusion networks
L. Mangu, E. Brill, A. Stolcke
https://arxiv.org/abs/cs/0010012

**Comment by AssAssinsninja7** [comment]
> To learn theory about confidence scoring you can read a classical paper:
> 
> Finding consensus in speech recognition: word error minimization and other applications of confusion networks
> L. Mangu, E. Brill, A. Stolcke
> https://arxiv.org/abs/cs/0010012

You're a fucking saint! Read through the paper, and from my understanding they use "MF-PLP" for coefficient extraction (instead of MFCC) and then uses HMM for the training. In theory I should be able to use the confidence to estimate it. I'm thinking that should be enough, although I might have to replace the MFCC with a PLP if my MFCC values are too off. 

But anyways, thanks for the help. Closing this thread. :)

**Comment by nshmyrev** [comment]
> MFCC with a PLP if my MFCC values are too off

There is no big difference between mfcc and plp, you can continue using them. If you experience problems the root is somewhere else.

**Comment by AssAssinsninja7** [comment]
> > MFCC with a PLP if my MFCC values are too off
> 
> There is no big difference between mfcc and plp, you can continue using them. If you experience problems the root is somewhere else.

Ok, I understood that they produced the same type of output but that the technique for the PLP generates a more accurate and robust system. Anyways, thanks for the feedback. I will keep that in mind when I start testing it again. :)
