### ISSUE TITLE
Dynamic Linking Error

### ISSUE THREAD

**Issue by MaiVanBinh** [alphacep/vosk-api#538]
Hi. have error when run code in nodejs. 
Error: Dynamic Linking Error: Win32 error 126
Anyone can help me. thanks you
![image](https://user-images.githubusercontent.com/55869650/118241158-0710d500-b4c6-11eb-9a6f-ec4f99dccfbe.png)

**Comment by MaiVanBinh** [comment]
same previous issues. So i close thanks.

**Comment by nshmyrev** [comment]
Same as #457. I have just published 0.3.27 on npm, it should fix your problem. Please update.
