### ISSUE TITLE
Vosk in Windows

### ISSUE THREAD

**Issue by ANJALI2022** [alphacep/vosk-api#539]
Hi Team,

can you please guide me with **vosk installation in windows**, I am following the below link
https://medium.com/analytics-vidhya/offline-speech-recognition-made-easy-with-vosk-c61f7b720215

In the above link after pip install vosk, the next step is to clone the **"Vosk Github repository"** in the **root folder**. This instruction is unclear to me.
Can any one of you help?

Thanks,
Anjali

**Comment by nshmyrev** [comment]
> can you please guide me with vosk installation in windows, I am following the below link
> https://medium.com/analytics-vidhya/offline-speech-recognition-made-easy-with-vosk-c61f7b720215

You'd better follow our documentation

> In the above link after pip install vosk, the next step is to clone the "Vosk Github repository" in the root folder. This instruction is unclear to me.

You can clone repository anywhere.

**Comment by ANJALI2022** [comment]
hey @nshmyrev, can you please paste the link of your documentation here?
Would be a big help.

Thanks!
