### ISSUE TITLE
Fine-tuning on Indian English Vosk Model

### ISSUE THREAD

**Issue by Archan2607** [alphacep/vosk-api#540]
Hello 
Really appreciate the model you have created, it's very helpful in the application that we are creating. In our scenario we want to append more words to the vosk-model-small-en-in-0.4 model by fine-tuning it. Some quick help i needed for that:

1. Is fine-tuning possible on the indian english small models or it is possible on only some of the vosk models?
2. Is there any proper documentation or steps we can follow to do fine-tuning on the vosk models? 

Thanks

**Comment by nshmyrev** [comment]
Same as #185 

You can subscribe to the original issue to get updates.

**Comment by aashu359** [comment]
i am fine tunning th vosk model in ubantu can you guid the steps which i have to followe to fine tune it. i am using vosk- model-en-in-0.5
