### ISSUE TITLE
architecture/research paper?

### ISSUE THREAD

**Issue by lmessinger** [alphacep/vosk-api#542]
Hi everyone

I wondered how we can understand the model and architecture of VOSK? is there any research paper this is based on?

many thanks
Lior

**Comment by nshmyrev** [comment]
> is there any research paper this is based on

There is no single paper describing Vosk.

Vosk/Kaldi toolkit is based on a multiyear research by Daniel Povey and students:

https://danielpovey.com/publications.html

and also research from openfst developers:

https://research.google/pubs/pub35189/

**Comment by lmessinger** [comment]
Great-thanks! This is impressive.
 If I understand correctly, It is based on WFT  which kind of probabilistic
state machine?
Btw, is there any deep learning in the pipeline?

**Comment by nshmyrev** [comment]
Vosk is based on a common DNN-HMM architecture. Deep neural network is used for sound scoring (acoustic scoring), HMM and WFST frameworks are used for time models (language models).

**Comment by lmessinger** [comment]
Got it. Many thanks.

**Comment by nshmyrev** [comment]
You are welcome. Please close the issue if you don't have other questions.

**Comment by karimmhamdihabemus** [comment]
hi sir, can I get your email I have an little issue that i want to ask you about ?
