### ISSUE TITLE
initializer for ctype 'char *' must be a cdata pointer, not _cffi_backend.buffer

### ISSUE THREAD

**Issue by ludwigsaux** [alphacep/vosk-api#543]
Hi ! 

I have this error "initializer for ctype 'char *' must be a cdata pointer, not _cffi_backend.buffer" when using vosk api with python. It appears when starting test.microphone after the load of G.carpa

I don't know what is that. Do you have any ideas ?

**Comment by nshmyrev** [comment]
You probably have outdated test_microphone.py, recent only has `bytes()` call to convert from buffer to bytes. Here:

https://github.com/alphacep/vosk-api/blob/e6bd200c856346ff745d77eafc75d63528398833/python/example/test_microphone.py#L23
