### ISSUE TITLE
Error While Compiling libvosk

### ISSUE THREAD

**Issue by sadrasabouri** [alphacep/vosk-api#554]
Hi all.
I have a problem compiling libvosk.
All the resources compiled well but here is the log for libvosk compile:
```
g++ --shared -s -o libvosk.so kaldi_recognizer.o language_model.o spk_model.o vosk_api.o /home/kaldinew/kaldi/src/online2/kaldi-online2.a /home/kaldinew/kaldi/src/decoder/kaldi-decoder.a /home/kaldinew/kaldi/src/ivector/kaldi-ivector.a /home/kaldinew/kaldi/src/gmm/kaldi-gmm.a /home/kaldinew/kaldi/src/nnet3/kaldi-nnet3.a /home/kaldinew/kaldi/src/tree/kaldi-tree.a /home/kaldinew/kaldi/src/feat/kaldi-feat.a /home/kaldinew/kaldi/src/lat/kaldi-lat.a /home/kaldinew/kaldi/src/lm/kaldi-lm.a /home/kaldinew/kaldi/src/rnnlm/kaldi-rnnlm.a /home/kaldinew/kaldi/src/hmm/kaldi-hmm.a /home/kaldinew/kaldi/src/transform/kaldi-transform.a /home/kaldinew/kaldi/src/cudamatrix/kaldi-cudamatrix.a /home/kaldinew/kaldi/src/matrix/kaldi-matrix.a /home/kaldinew/kaldi/src/fstext/kaldi-fstext.a /home/kaldinew/kaldi/src/util/kaldi-util.a /home/kaldinew/kaldi/src/base/kaldi-base.a /home/kaldinew/kaldi/tools/openfst/lib/libfst.a /home/kaldinew/kaldi/tools/openfst/lib/libfstngram.a /home/kaldinew/kaldi/tools/OpenBLAS/install/lib/libopenblas.a  -lm -latomic 
/usr/bin/ld: /home/kaldinew/kaldi/src/online2/kaldi-online2.a(online-ivector-feature.o): relocation R_X86_64_PC32 against symbol `_ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:62: recipe for target 'libvosk.so' failed
make: *** [libvosk.so] Error 1
```
What can I do in order to make it work?

<br>

JFYI in the `Makefile` I just change the KALDI_ROOT to proper value and remove some of Openblas libraries due to some problems.

<pre> ifeq ($(HAVE_OPENBLAS_CLAPACK), 1)
 LIBS += \
<font color="#CC0000">-       $(OPENBLAS_ROOT)/lib/libopenblas.a \</font>
<font color="#CC0000">-       $(OPENBLAS_ROOT)/lib/liblapack.a \</font>
<font color="#CC0000">-       $(OPENBLAS_ROOT)/lib/libblas.a \</font>
<font color="#CC0000">-       $(OPENBLAS_ROOT)/lib/libf2c.a</font>
<font color="#4E9A06">+</font>       <font color="#4E9A06">$(OPENBLAS_ROOT)/lib/libopenblas.a</font><span style="background-color:#CC0000"> </span>
 endif
</pre>

**Comment by nshmyrev** [comment]
You need to compile kaldi with `--shared`. See our docker file for details.

For the second change, you need openblas_clapack build, not openblas.

**Comment by sadrasabouri** [comment]
Thank you.
I'll check it and close this issue ASAP.
