### ISSUE TITLE
InputFinished?

### ISSUE THREAD

**Issue by lmessinger** [alphacep/vosk-api#555]
Hi

We are using the Vosk server and once we receive a partial result the system expects, we want to stop the recognition until we start over another sentence. 
what's the way to let the engine know that this sentence is over? I saw Kaldi has InputFinished but Vosk doesnt support it

thanks
Lior

**Comment by nshmyrev** [comment]
You can call Result(), it will start over.

I'll introduce new method to reset result soon, it should be better. So I'll keep this open.

**Comment by lmessinger** [comment]
that worked. thank you.

**Comment by nshmyrev** [comment]
We have now Reset method to reset the recognizer.

https://github.com/alphacep/vosk-api/blob/d489bc40e42226bc9b9ef2935197a8e3f34ca1d8/src/vosk_api.h#L230
