### ISSUE TITLE
no SetMaxAlternatives?

### ISSUE THREAD

**Issue by lmessinger** [alphacep/vosk-api#557]
Hi
sometimes i get the error that KaldiRecognizer doesnt have the method SetMaxAlternatives
I think when i use KaldiRecognizer with vosk-model-en-us-daanzu-20200905 it happens. 
any ideas?

**Comment by sskorol** [comment]
You may want to follow the [release updates](https://github.com/alphacep/vosk-api/releases). Max alternatives feature wasn't released yet. So if you really want it, you have to build Vosk on your own or just wait for a new release.

**Comment by nshmyrev** [comment]
I have uploaded 0.3.28 with SetMaxAlternatives to pip:

https://pypi.org/project/vosk/0.3.28/
