### ISSUE TITLE
Add jitpack build

### ISSUE THREAD

**Issue by nshmyrev** [alphacep/vosk-api#558]
So we can distribute things for F-droid, see

https://forum.f-droid.org/t/google-voice-foss-replica/13629/8

**Comment by k3b** [comment]
For details see https://jitpack.io/docs/ANDROID/ and https://jitpack.io/docs/BUILDING/ 

I am currently experimenting how to create a gradle only android lib that includes ndk and downloading the c++ source modules without the need for a bash script

**Comment by k3b** [comment]
@nshmyrev i have created https://github.com/k3b/vosk-api-jitpack.io as an attempt to create the lib in gradle only without any bash script.
* I have granted you write support there so i hope that we together can solve this issue there.
* The goal is to make the lib compatible with android.
* the project can be opened with android studio.

Note that i have never worked before with android-ndk and cmake. the last time i programmed in c++ was 20 years ago (windows-3.0)

-----

what i have done so far:

* analysed build-vosk.sh
  * vosk depends on 'https://github.com/xianyi/OpenBLAS.git' which already has a cmake OpenBLAS/CMakeLists.txt

Created a new android project with a ndk subproject "vosk-api"
* has a gradle step to download 'https://github.com/xianyi/OpenBLAS.git' to vosk-api/libs/OpenBLAS 
  * (see [settings.gradle in project root](https://github.com/k3b/vosk-api-jitpack.io/blob/master/settings.gradle))
* in [vosk-api/build.gradle](https://github.com/k3b/vosk-api-jitpack.io/blob/master/vosk-api/build.gradle) there is the commented out section externalNativeBuild/cmake marked with !!! that tries to compile OpenBLAS/CMakeLists.txt
  * when removing the comment compile failed with "When cross compi"ling, a TARGET is required."
    * for android every native code has to go to "native-lib" 
    * I assume that "OpenBLAS/CMakeLists.txt" need somthing like 
      * if (ANDROID)
         *  target_link_libraries(native-lib SHARED ?????)
      * endif ()

can you help me solving that issue

**Comment by nshmyrev** [comment]
> can you help me solving that issue

Hi, thank you for starting this. Some notes:

1. I wanted to look a bit later on that too
2. I don't think a separate project is needed, you can do it within vosk-api. I believe you can specify the build command in jitpack.yml so it will pick the right folder.
3. I don't think you need to rework everything with cmake. You just add build-kaldi script to gradle as a task and it will be invoked on build. I hope jitpack allows build of a bigger c++ project.

**Comment by k3b** [comment]
Thanks for reply.

The seperate project is just an experiment where i can play and learn without polluting the original.

I already learned about

* gradle plugin com.alexvasilkov.git-dependencies to clone git repositories
* android studio with ndk

I agree that building using jitpack.yml  is probably much less effort than recreating the build in native gradle.

"jitpack.yml" is provider specific so it will not work with travis or under windows where there is no bash-shell.

I will try to learn more about android c++ integration.

Can you help me what should be put into  OpenBLAS/CMakeLists.txt to android specific target lib.

    if (???ANDROID???)
        target_link_libraries(native-lib SHARED ?????)
    endif ()

**Comment by nshmyrev** [comment]
> Can you help me what should be put into OpenBLAS/CMakeLists.txt to android specific target lib.

I don't think you need to put something specific. It is already there:

https://github.com/xianyi/OpenBLAS/blob/42f048cf6c04e51de6c7a3ade5af71b0c4dcea0d/CMakeLists.txt#L190

**Comment by k3b** [comment]
thanks. 

i already found the solution. the error with missing "target" was a missing environment variable. i go on learning ....

**Comment by k3b** [comment]
I finally stopped trying to create a gradle-native-build because 
config.h is not generated in vosk-api/src/main/cpp/clonedRepositories/OpenBLAS/Makefile.system

I cannot do this without a coderewrite.

I hope that  nshmyrev -s jitpack.yml aproach will work

**Comment by k3b** [comment]
I tried with [jitpack.yml](https://github.com/k3b/vosk-api/blob/master/jitpack.yml) but it does not compile


publishing: 

* https://github.com/k3b/vosk-api/ 
** with [jitpack.yml](https://github.com/k3b/vosk-api/blob/master/jitpack.yml)

consumig as 

* implementation 'com.github.k3b:vosk-api:0.3.27.4'
** https://jitpack.io/com/github/k3b/vosk-api/0.3.27.4/vosk-api-0.3.27.4.pom
** https://jitpack.io/com/github/k3b/vosk-api/0.3.27.4/build.log

**Comment by nshmyrev** [comment]
> but it does not compile

The log says you need to define ANDROID_NDK_HOME, probably also in jitpack.yml

**Comment by k3b** [comment]
> The log says you need to define ANDROID_NDK_HOME, probably also in jitpack.yml

i thought that would be done with sdkmanager --install "ndk;21.3.6528147"

**Comment by k3b** [comment]
https://stackoverflow.com/questions/67791300/how-to-install-android-ndk-using-a-jitpack-yml-without-gradle

**Comment by nshmyrev** [comment]
@k3b jitpack doesn't define ANROID_NDK_HOME, but it defines ANDROID_HOME. You can probably modify build-vosk.sh script like this:

      ANDROID_NDK_HOME?=$ANDROID_HOME/ndk-bundle

and it should go forward

**Comment by k3b** [comment]
@nshmyrev have you tried to upload your aar lib via https://central.sonatype.org/publish/ ? it is among the [trusted maven repos](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L137)

**Comment by nshmyrev** [comment]
Yeah, we had bad experience with sonatype before. I'd better go with jitpack. But I'm sorry I didn't had time to check yet.

**Comment by Stypox** [comment]
Is anyone still working on this? I'd like to publish the [Dicio](https://github.com/Stypox/dicio-android) assistant on F-Droid but that needs this issue to be resolved. If nobody is working on it I might try myself, though I don't have much experience with build scripts and NDK.

**Comment by nshmyrev** [comment]
> Is anyone still working on this?

No, I don't think so

> I'd like to publish the Dicio assistant on F-Droid but that needs this issue to be resolved. 

Cool app!

Please try and let me know if you need any help. If it doesn't work, maybe I'll register to sonatype in the end, not sure.

**Comment by nshmyrev** [comment]
I decided to go ahead with sonatype. Created an issue at https://issues.sonatype.org/browse/OSSRH-74850

**Comment by nshmyrev** [comment]
Done https://s01.oss.sonatype.org/content/repositories/releases/com/alphacephei/vosk-android/0.3.32/, not sure if it is public already or not

**Comment by nshmyrev** [comment]
We are on mavencentral already

https://repo1.maven.org/maven2/com/alphacephei/vosk-android/

**Comment by Stypox** [comment]
Thank you very much :-D

**Comment by nshmyrev** [comment]
Thank you @Stypox, your patch was extremely helpful
