### ISSUE TITLE
speaker_recognition, how to generate the fingerprints of the speaker

### ISSUE THREAD

**Issue by HamiguaLu** [alphacep/vosk-api#559]
Hi there
Really appreciate your great job
I am quite new to Kaldi and Speaker regognition, so forgive me if this is a silly question

In test_speaker.py ：
 
> We compare speakers with cosine distance. We can keep one or several fingerprints for the speaker in a database
>  to distingusih among users.
> **spk_sig = [-1.110417,0.09703002,,..................-0.486526]**

So spk_sig must be generated based on speaker's voice data, correct?
How can I generate it?

Also another issue is that it seems in this test_speaker.py,  it performe speech regognition and speaker regognition at same time
Is it possible to only support speaker regognition?

**Comment by nshmyrev** [comment]
> How can I generate it?

You recognize a chunk of user speech just like in test_speaker.py, thats it.

> Is it possible to only support speaker regognition?

Not yet

**Comment by nshmyrev** [comment]
Same as 

https://github.com/alphacep/vosk-api/issues/405
