### ISSUE TITLE
How create Ukranian or Russian-Ukranian languige model ?

### ISSUE THREAD

**Issue by tarasfrompir** [alphacep/vosk-api#56]
Can yoy transcribe this process, or wheare i can read this?

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/41

**Comment by andreyshmelev** [comment]
Hi
# You can also specify the possible word or phrase list as JSON list, the order doesn't have to be strict
rec = KaldiRecognizer(model, wf.getframerate(), '["oh one two three four five six seven eight nine zero", "[unk]"]')
a question:
what , "[unk]" means?

**Comment by nshmyrev** [comment]
> what , "[unk]" means?

unk means unknown word, any other word not from the grammar.

**Comment by andreyshmelev** [comment]
> > what , "[unk]" means?
> 
> unk means unknown word, any other word not from the grammar.

Thank you. How Should i properly use this method for train words "start, stop"
