### ISSUE TITLE
Can't Use The C API !

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#560]
Hi, i have just tried Vosk with Python and it is working great to be honest, but i want to use the C API. So i checked the C folder to test the examples, ran the make file and i got ld errors as i expected. And i literally didn't find any info online on how to use The C API. Also i didn't find in the docs as well. So can anyone please point me to the right direction on how to use the C API ? Using Linux By The Way.

**Comment by nshmyrev** [comment]
> ran the make file and i got ld errors as i expected

It is not expected

> So can anyone please point me to the right direction on how to use the C API ?

Some basic linux development tutorial with core ideas should help you:

https://opensource.com/article/21/2/linux-software-libraries

**Comment by ghost** [comment]
@nshmyrev Thanks for the reply, the link was helpful in general, but not in my case. I have just cloned the repo as is, and didn't change anything. I just navigated to the C folder and ran make. Is there anything i must do in addition ? If i am missing something, then please point me to it, if not, i guess i will close the issue then. Look i am relatively new to these kind of compilations and C in general, i have always used Python so pardon me if this is a silly question. Thanks for the help.

**Comment by Karim-Fadi** [comment]
@nshmyrev I have also noticed that in the make file of src there is some paths that dont exist in the repo. For example, there is paths to tools/openfst and paths to tools/OpenBLAS/install. And these Directories doesn't exist at all in the Kaldi Repos. So i always get errors like "No Such File or directory". So If you guide me on this, i will really appreciate it.

**Comment by nshmyrev** [comment]
> Is there anything i must do in addition ?

You probably didn't download the binary library from the releases.

**Comment by ghost** [comment]
@nshmyrev Yes you are right. After moving the .so file to /usr/lib. Everything worked like a charm.
