### ISSUE TITLE
No instructions running C Example! libvosk.so missing

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#561]
I cloned The vosk api repo, installed the binary, successfully built The C Examples. But They produce the following error:

LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)

And i really can't understand, where is model/mfcc.conf file so that it can't open it ?

Any clue ?

**Comment by nshmyrev** [comment]
You need to download and unpack the model

**Comment by ghost** [comment]
How could I forget.
