### ISSUE TITLE
Just about speed !

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#562]
I recently tried Vosk and i was really impressed by the ease of setup and accuracy, but one thing really lacked: “Speed”. I am using Vosk for home automation and the command gets recognized after at least 5 seconds, so it is really Slow. I even tried the C API hoping to get better performance compared to Python, but to my astonishment, I literally got 0 improvements, it is literally the same speed. I even tried other models other than the small English US one, but nothing happened. So is there any way to speed the things up a little bit ?!? Also in Vosk’s website under the models tab, there is a table of models with a column titled “word error rate/ speed”. I understand that the word error rate is (lower is better) but i can’t really understand the speed, does higher numbers means faster or the other way around ?

**Comment by nshmyrev** [comment]
> and the command gets recognized after at least 5 seconds

On what hardware?

**Comment by ghost** [comment]
@nshmyrev Raspberry Pi 4 8GB

**Comment by nshmyrev** [comment]
Is it also 5 seconds with our python microphone demo test_microphone.py? For every command?

**Comment by ghost** [comment]
@nshmyrev no when it comes to microphone, it gets recognized in a range between 1 - 2 seconds which is absolutely fine but the major problem is that accuracy is really bad for some reason so i don’t use it.

**Comment by Karim-Fadi** [comment]
@nshmyrev no when it comes to microphone, it gets recognized in a range between 1 - 2 seconds which is absolutely fine but the major problem is that accuracy is really bad for some reason so i don’t use it.

**Comment by ghost** [comment]
@nshmyrev is there any other models that are faster and doesn’t require beast hardware so that it can run on a Raspberry Pi 4 ? And actually i will pick speed over accuracy.

**Comment by nshmyrev** [comment]
To debug audio issues you need to record an audio file with your speech and share it.

As for speed issue, you probably reload the model every time, it is a bad idea. Once a model is loaded it decodes fast like in microphone and all other demos.

**Comment by ghost** [comment]
@nshmyrev Ok, one last question, How exactly am i reloading the model each time ? I mean i just unpacked the model and that is it. So what do you really mean by uploading it each time ? Also please tell me what the speed numbers of the models represent ? Does higher numbers means higher speeds ?

**Comment by nshmyrev** [comment]
> Ok, one last question

You asked 4 questions instead of 1.

**Comment by solyarisoftware** [comment]
@Karim-Fadi  Vosk is maybe the fastest ASR among offline opensource engines.  You have to load in memory your model ONCE. 
Using grammars, latencies are ~< 0.1 secs for short sentences. See: https://github.com/solyarisoftware/voskJs/tree/master/examples#sentence-based-speech-to-text-specifyng-a-grammar

**Comment by zyb8543d** [comment]
@solyarisoftware In fact ,the speed is really slow, I compare the speed of vosk source codes with Kaldi online codes, a 24s audio needs 15s for vosk api but 5s for Kaldi online. At the same time , I have load the model in memory.

**Comment by nshmyrev** [comment]
> In fact ,the speed is really slow

Kaldi and vosk speeds are identical. If you have issues you'd better open a separate issue here and provide a necessary information to reproduce your problems.

**Comment by solyarisoftware** [comment]
@v-yunbin please eventually open a a new issue specifying the exact configuration (as I did in my link) and a full comparison context.

BTW Generally speaking, I believe it doesn't make sense to compare an offline engine (e.g. Vosk) with online services. But remaining in-topic, I'm challenging you! Please demonstrate us that the best performance cloud service of your choice (google or anything) is faster than a no-GPU offline Vosk, that, when tuned with grammars, perhaps give you result in few tents of milliseconds on a decent single core CPU...

**Comment by zyb8543d** [comment]
> > In fact ,the speed is really slow
> 
> Kaldi and vosk speeds are identical. If you have issues you'd better open a separate issue here and provide a necessary information to reproduce your problems.

I open a new issue  , you can see it at https://github.com/alphacep/vosk-api/issues/566#issue-907340569
