### ISSUE TITLE
libvosk missing

### ISSUE THREAD

**Issue by rossisthebest** [alphacep/vosk-api#564]
When trying to compile the example for C#, i'm getting the following error:

Unable to load DLL 'libvosk' or one of its dependencies: The specified module could not be found. (0x8007007E)

I also had to compile the Nuget package from source, as the latest published version (0.3.27) doesn't contain methods for VoskRecognizer.SetMaxAlternatives() or VoskRecognizer.SetSpkModel().

The code also seems to reference a file called "test.wav" but can't see any examples where that's been supplied. Can you confirm this is supposed to created by the user?

**Comment by nshmyrev** [comment]
> Unable to load DLL 'libvosk' or one of its dependencies: The specified module could not be found. (0x8007007E)

Is this with a package you got from nuget or with the package you created yourself? If the latter you probably didn't package properly.

> The code also seems to reference a file called "test.wav" but can't see any examples where that's been supplied. Can you confirm this is supposed to created by the user

You can find test.wav inside the repository vosk-api/python/example/test.wav

**Comment by rossisthebest** [comment]
Hi Nickolay,

Thanks for replying. Thank you for helping me locate the test.wav file.

In terms of creating the package, yes I had to create it myself as the latest one published to Nuget.org is only 0.3.27 and doesn't support the example files. I don't think it's the way I've generated the package, as the source files indicate they have a dependency on this DLL but it's not in the lib folder (or any of the others in this repository):

VoskPINVOKE.cs:
[global::System.Runtime.InteropServices.DllImport("libvosk", EntryPoint="vosk_model_new")]

**Comment by nshmyrev** [comment]
> a dependency on this DLL but it's not in the lib folder 

You can build it from source or extract prebuilt one from python package. Or you can just wait for the next version. Or you can pick the demo code from the released version.

**Comment by rossisthebest** [comment]
Hi Nickolay,

I've extracted the files from vosk-win64-0.3.27.zip at https://github.com/alphacep/vosk-api/releases/tag/0.3.27. This gets me passed the line "Vosk.Vosk.SetLogLevel(0);", but it is now having difficulty with initialising the Model object:

![image](https://user-images.githubusercontent.com/14776692/120115532-017ce580-c17c-11eb-92e8-397a1c14b0de.png)

Any ideas?

**Comment by rossisthebest** [comment]
Just noticed this error in the ouput:

ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf

I'm having a dig through all the source files now to see if i can find mfcc.conf

**Comment by rossisthebest** [comment]
"You need to download and unpack the model"

Looks like you've already resolved this under issue 561:

https://github.com/alphacep/vosk-api/issues/561

I'll give that a go

**Comment by nshmyrev** [comment]
Lets track in #561
