### ISSUE TITLE
Horrible Microphone Accuracy!

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#567]
When transcribing an audio file, i can confidently say that if the file is well recorded, it will achieve up to 90 or even 95 % accuracy. However for some reason, the microphone accuracy in the Python example is REALLY Horrible. It is not even usable. In the good times, it achieves 10 % accuracy. So why is that ? Even the video linked in the docs shows the same thing. So is there any way to improve it ? I also made sure of Mic noise and all this stuff. And when i record with the same mic (which is really high quality) an audio file then transcribe it, the accuracy is high as mentioned. But with Microphone, horrible. Does this have to do with the way the Python script captures audio ? Any help ?

**Comment by nshmyrev** [comment]
What OS, hardware?

**Comment by ghost** [comment]
Arch Linux. Ryzen 5 3600 CPU, no GPU, 16 RAM.

**Comment by nshmyrev** [comment]
Add -filename argument and share recorded file:

https://github.com/alphacep/vosk-api/blob/4ea9885d44ca3ab96df969002e2e6b2c895c2183/python/example/test_microphone.py#L37

**Comment by solyarisoftware** [comment]
@Karim-Fadi 
and also: 
- record yourself a file on your computer
- listen it, to verify with your ears :)

```
#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "usage  : $0 filename (without suffix)"
    echo "example: $0 sample"
    exit 0
  else
    audiofile=$1.wav
fi

echo "recording file $audiofile (press Ctrl+C to stop recording)"

# recording with sox
sox -d -b 16 -c 1 -r 16k $audiofile 

# info about the recorded file
mediainfo $audiofile

# play the recorded file
aplay $audiofile
```

**Comment by ghost** [comment]
> Add -filename argument and share recorded file:
> 
> https://github.com/alphacep/vosk-api/blob/4ea9885d44ca3ab96df969002e2e6b2c895c2183/python/example/test_microphone.py#L37

When i tried to do so, the file was saved but when i tried to play it with play, i got a can’t open file error. So i tried to play it with mpg123 and to my surprise it was a 1 second empty audio file with nothing recorded. I even tried with multiple microphones but the same problem happened. Anyway if the problem persists, i will just record an audio with the awesome sox and then transcribe it, i will also write a script to automate the process.

**Comment by solyarisoftware** [comment]
maybe the issue is related to your audio driver  config

**Comment by nshmyrev** [comment]
> the file was saved but when i tried to play it with play

You need to share the audio file.

> Anyway if the problem persists, i will just record an audio with the awesome sox and then transcribe it

I doubt it is an optimal way.

**Comment by nshmyrev** [comment]
Feel free to reopen once you have some extra data to share.
