### ISSUE TITLE
cudaMemcpyAsync undefined symbol - issue

### ISSUE THREAD

**Issue by arunbaby0** [alphacep/vosk-api#568]
I am using python3.8 and this is the only version installed in my system.

`python3 test_simple.py 
Traceback (most recent call last):
  File "test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "/usr/local/lib/python3.8/dist-packages/vosk-0.3.29-py3.8.egg/vosk/__init__.py", line 21, in <module>
    _c = open_dll()
  File "/usr/local/lib/python3.8/dist-packages/vosk-0.3.29-py3.8.egg/vosk/__init__.py", line 15, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
OSError: cannot load library '/usr/local/lib/python3.8/dist-packages/vosk-0.3.29-py3.8.egg/vosk/libvosk.so': /usr/local/lib/python3.8/dist-packages/vosk-0.3.29-py3.8.egg/vosk/libvosk.so: undefined symbol: cudaMemcpyAsync`

**Comment by nshmyrev** [comment]
Looks like you compiled it yourself incorrectly. You need to build kaldi for linking with vosk without cuda.

**Comment by arunbaby0** [comment]
Thanks a lot for the quick response. I have the following doubts.

1) VOSK-api cannot use CUDA(GPU) while decoding, is this correct?
2) Is yes, Is there a way to enable it?
3) Also if the model is large, does CPU decoding perform at <1 RTF?

Thanks in advance.

**Comment by GaetanLepage** [comment]
@arunbaby0 I have the exact same problem, did you manage to run vosk with GPU support ?
If yes, are you using cuda or not ?

EDIT: I managed to make it work:
- compile `kaldi` with `--use-cuda=yes`
- compile `vosk-api` like this: `KALDI_ROOT=/opt/kaldi HAVE_CUDA=1 make`

It worked for me like this !

**Comment by arunbaby0** [comment]
Yes. As @nshmyrev Mentioned, Once I compiled using --use-cuda=yes, it worked fine.
