### ISSUE TITLE
Not installing via pip3 on PopOS

### ISSUE THREAD

**Issue by Mirppc** [alphacep/vosk-api#57]
I am on Pop-OS 19.10 and after installing python3-pip i rant the command _pip3 install vosk_ and get this result.

_Collecting vosk_
_  Could not find a version that satisfies the requirement vosk (from versions: )_
_  No matching distribution found for vosk_

It shows up doing a pip3 search.

pip3 search vosk
vosk (0.3.3)  - API for Kaldi and Vosk

Kind of confused as this error would likely happen if it was not built for the architecture of my system yet per the readme on the vosk-api source it says that there is an ARM and X86_64 build.

The main goal is to get something set up to take some old family interviews and convert them into text.

First goal is to get something working.

**Comment by nshmyrev** [comment]
Provide the information about:

1. Hardware
2. Python version
3. Pip version

**Comment by Mirppc** [comment]
Two different sytems and OS's where now tested.  Same error

PopOS 19.10
HP Z440
CPU: Quad Core Intel Xeon E5-1620 v3 (-MT MCP-) speed/min/max: 1197/1200/3600 MHz Kernel: 5.3.0-7642-generic x86_64 
Up: 17d 23h 50m Mem: 9597.6/32024.1 MiB (30.0%) Storage: 1.89 TiB (22.7% used) Procs: 416 Shell: bash 5.0.3 inxi: 3.0.36 

python3 -V
Python 3.7.5
pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)


Dell Poweredge T410
Opensuse Leap 15.1
CPU(s):2 Hexa core Intel Xeon X5660s (-HT-MCP-SMP-) speed:2792 MHz (max) Kernel:4.12.14-lp151.28.32-default x86_64 Up:119 days 23:10 Mem:37136.8/64401.0MB HDD:5958.9GB(23.5% used) Procs:593 Client:Shell inxi~2.3.40  

python3 -V
Python 3.6.9

pip3 --version
pip 10.0.1 from /usr/lib/python3.6/site-packages/pip (python 3.6)


Same issue on both.

**Comment by nshmyrev** [comment]
Please upgrade pip3 to pip 19:

https://github.com/alphacep/vosk-api#python-installation-from-pypi

**Comment by Mirppc** [comment]
thank you.
