### ISSUE TITLE
getting started with a kaldi model

### ISSUE THREAD

**Issue by mooseyboots** [alphacep/vosk-api#570]
hi voskland,

i am trying to test out some models based on the python instructions on your website's install page. i have successfully run test_srt.py on the example provided in the instructions (vosk-model-small-en-us-0.15.zip, renamed to model in the test dir as per instructions), but when i try the same python test on a kaldi model (eg kaldi-generic-fr-tdnn_f-r20191016, also renamed to model as per instructions), it returns

```
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf

```

the kaldi models have different directory structures, so the test can't find the files it needs to get going. is it possible to test these larger models easily? sorry if i'm missing something obvious.

**Comment by nshmyrev** [comment]
> is it possible to test these larger models easily? 

Yes,  you need to rearrange file inside the model properly as per doc:

https://alphacephei.com/vosk/models#model-structure

You can also just download our French models, they are much more accurate than kaldi-generic-fr-tdnn_f-r20191016.

**Comment by nshmyrev** [comment]
Same as #41
