### ISSUE TITLE
AttributeError: 'KaldiRecognizer' object has no attribute '_handle'

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#571]
your new release has this bug. ! please check if maybe I am on mistake.

**Comment by nshmyrev** [comment]
Please don't leave the issues open. Close them if they work for you. @Tortoise17

**Comment by Tortoise17** [comment]
Now I have error like below

```

if rec.AcceptWaveform(data):
AttributeError: 'tuple' object has no attribute 'AcceptWaveform'
```

`Vosk=0.3.32`

Ihave changed according to your above mentioned recipe.
