### ISSUE TITLE
parallel processing for all files in folder

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#572]
Is there any additional available threads execution possibility with vosk to get files processed depending on the number of processors? with MPI or OpenMP or any ? to increase no of workers.

**Comment by nshmyrev** [comment]
You just create many recognizers.

**Comment by Tortoise17** [comment]
can you guide how or in .py script additions?

**Comment by nshmyrev** [comment]
> can you guide how or in .py script additions?

Sure, but you need to try yourself first

**Comment by nshmyrev** [comment]
You can also check

https://github.com/alphacep/vosk-api/blob/master/python/test/transcribe_scp.py

**Comment by solyarisoftware** [comment]
@Tortoise17 I believe the script Nicolay proposed solves you question.

Or, simply run separate background OS processes for each input file, maybe with a bash script, running in parallel considering that if you exceed the number of available cores you host will be sitting :-)

```
# bash pseudocode
transcript file1.wav &
transcript fileN.wav &
```

Please close the issue.
