### ISSUE TITLE
Accuracy deceasing on my testsets with corpa rescoing after update latest version

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#573]
1. test a testset  from  part of audio  https://alphacephei.com/test-other/pykaldi-speed/test-speed.zip, it seems has some gain with latest version.
corpa rescoring  with 0.3.27
`那玩意想问问你要明确了刚才这两道菜怎么要这种还得太好了。那咱们接下来这道菜您有没有按要求每个我挣这么多菜啊，就是咱们做一个稍微百万一段二中完美耳鸣，拉袜子，拉我们张让耳朵吃辣的耳朵。沃尔沃所有用提着一桌那儿肯定还得是全民认为物流。多爱用用了。`
corpa rescoring  with  0.3.21
`那玩意想问问你要明确了，刚才是包菜怎么样剧本还得太好了。那咱们接着这道菜您拥有而要求卖，我真更多菜啊，这人做一个稍微百万一段而更完美，耳鸣厚拉不拉我们张让耳朵爱吃辣的耳朵。沃尔沃用提着一桌那儿肯定还得是全民认为物流多爱，偶尔用用了。`
2. test my testset(private testset)
 Corpa rescoring  with 0.3.27 becomes bad  on my testset than corpa rescoring  with  0.3.21.

**Comment by nshmyrev** [comment]
Yes, we fixed that in 0.3.29, please update

**Comment by zyb8543d** [comment]
@nshmyrev ok ，I close the issue
