### ISSUE TITLE
 Cannot open config file: model/mfcc.conf

### ISSUE THREAD

**Issue by Mujtabaomar111** [alphacep/vosk-api#575]
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf

Hi i have this problem and also i have follwoed the whole instruction as you don

**Comment by nshmyrev** [comment]
You need to download and unpack the model from https://alphacephei.com/vosk/models

**Comment by Mujtabaomar111** [comment]
i downloaded the models but again i ahve the same problem 
C:\Users\Mujtaba\Desktop\python\example>test_ffmpeg.py test.wav
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf


![Screenshot 2021-06-08 122326](https://user-images.githubusercontent.com/53365007/121145658-6c04e400-c854-11eb-9bf1-5589d5da094e.png)
 I tried the models but it didnt work
![2](https://user-images.githubusercontent.com/53365007/121147293-fbf75d80-c855-11eb-9b5f-43e622b94bf4.png)
![1](https://user-images.githubusercontent.com/53365007/121147328-031e6b80-c856-11eb-9b21-37130bfb0e1c.png)

**Comment by nshmyrev** [comment]
Show what is inside model folder on your screenshot.

**Comment by Mujtabaomar111** [comment]
[image: image.png]

**Comment by Mujtabaomar111** [comment]
[image: Untitled.png]

**Comment by Mujtabaomar111** [comment]
![Untitled](https://user-images.githubusercontent.com/53365007/121486606-88d12100-c9e6-11eb-80ef-155a9273cefa.png)

**Comment by nshmyrev** [comment]
conf and other folders must be directly in the model foder, not in subfolder vosk-model-en-us-daanzu-20200905

**Comment by Mujtabaomar111** [comment]
I foud this problem

C:\Users\Mujtaba\Desktop\python\example>test_ffmpeg.py test.wav
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.171862 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:278) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo model/graph/phones/word_boundary.int
Traceback (most recent call last):
  File "C:\Users\Mujtaba\Desktop\python\example\test_ffmpeg.py", line 22, in <module>
    stdout=subprocess.PIPE)
  File "C:\Users\Mujtaba\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Mujtaba\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Mujtabaomar111** [comment]
Thanks sir that problem solved but i faced to a new problem

I foud this problem

C:\Users\Mujtaba\Desktop\python\example>test_ffmpeg.py test.wav
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=10
max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones
1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan
components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.171862
seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from
model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing
derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Loading HCL and G from
model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:278) Loading words from
model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo model/graph/phones/
word_boundary.int
Traceback (most recent call last):
File "C:\Users\Mujtaba\Desktop\python\example\test_ffmpeg.py", line 22, in
stdout=subprocess.PIPE)
File
"C:\Users\Mujtaba\AppData\Local\Programs\Python\Python37\lib\subprocess.py",
line 756, in init
restore_signals, start_new_session)
File
"C:\Users\Mujtaba\AppData\Local\Programs\Python\Python37\lib\subprocess.py",
line 1155, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by nshmyrev** [comment]
You need ffmpeg binary in path.

**Comment by Mujtabaomar111** [comment]
how i can do it
i need for your instrction

**Comment by Mujtabaomar111** [comment]
![image](https://user-images.githubusercontent.com/53365007/121500624-ba9cb480-c9f3-11eb-8243-a33bfa5d3f6c.png)

**Comment by nshmyrev** [comment]
ffmpeg.exe

**Comment by Mujtabaomar111** [comment]
Hi sir!
I couldn't do it.
I will be happy if you remotely troubleshoot it by any disk

**Comment by Mujtabaomar111** [comment]
I did it but faced to this problem
![ww](https://user-images.githubusercontent.com/53365007/122165224-261bd180-ce8d-11eb-9b35-30505724aabb.png)
