### ISSUE TITLE
Need Help For Static Library !

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#576]
This is more like of a feature request rather than a bug. I need static version of the library, so i thought i would build it from source, but unfortunately when i cloned kaldi’s repo and everything needed, and tried to do so, i got errors of missing packages like gfortan and other stuff. I am on Arch, and for some reason pacman can’t fetch these dependencies or it can’t resolve some dependencies for some reason. So i am having trouble doing this stuff. So i wonder if there is a way i can get a static version for the library. I mean it would be amazing, if you added them to the release section. This is not an issue or a bug, so I totally understand if you close the issue. But yeah, this is a feature request. Thanks.

**Comment by ghost** [comment]
Is there any updates on this ?

**Comment by nshmyrev** [comment]
It is low priority for us as well.
