### ISSUE TITLE
Fine-Tuning Farsi Model on new Specific domain dataset

### ISSUE THREAD

**Issue by rose768** [alphacep/vosk-api#577]
Hello,
Thanks to your powerful toolkit. I used vosk-model-fa-0.5 and test it with Persian Mozilla Common Voice dataset. The result was good but when I test it with another persian dataset that is Persian telephony dataset the prediction was not accurate. How I can fine-tune vosk-model-fa-0.5 on new Persian Specific domain dataset?

**Environment overview**

Environment location: Google Colab

**Environment details**

OS version : "Ubuntu20.04.3 LTS"

**Comment by nshmyrev** [comment]
Finetuning will not help with telephony, you have to train from scratch.

Same as https://github.com/alphacep/vosk-api/issues/185

**Comment by rose768** [comment]
> Finetuning will not help with telephony, you have to train from scratch.
> 
> Same as #185

Thanks for your help. How can I train vosk-model-fa-0.5 from scratch with Persian telephony audio dataset?
