### ISSUE TITLE
Fine-tuning model in specific domain

### ISSUE THREAD

**Issue by rose768** [alphacep/vosk-api#578]
Hi, I used vosk-model-fa-0.5 and test it with the Persian Common Voice dataset. The results was great but when I test it with another Persian dataset link telephony dataset the result is not good as Common voice. How can I fine-tune the vosk-model-fa-0.5 model with Persina Specefic domain dataset?
Thanks a lot

**Environment overview**

Environment location: Google Colab

NeMo version: 1.0.0

**Environment details**

OS version : "Ubuntu20.04.3 LTS"
PyTorch version : "1.7.1"

**Comment by nshmyrev** [comment]
You already asked the same question before:

https://github.com/alphacep/vosk-api/issues/577
