### ISSUE TITLE
Building forked android library on Macbook Pro M1

### ISSUE THREAD

**Issue by Tadejo9** [alphacep/vosk-api#579]
Hello everyone,

#### My system
MacBook Pro M1 (2020)
Big Sur 11.4

---
I've forked this library and deleted all but android folder, because it is the only one I will be using. 

I would like to build a jar and deploy it to Github/Gitlab as package to access it from an Android app.

Are there any instructions for building files or is there a docker image that i can run and develop in?

This is the error trace I'm getting after running a task `buildVosk`.
[build-stack-trace.txt](https://github.com/alphacep/vosk-api/files/6622056/build-stack-trace.txt)

Have a nice day!

**Comment by nshmyrev** [comment]
The script expects linux

**Comment by Tadejo9** [comment]
Thank you for the response.

Would it pass if i built it in docker? Or should I virtualize linux?

**Comment by nshmyrev** [comment]
Same as #260 actually
