### ISSUE TITLE
C# Build issues

### ISSUE THREAD

**Issue by verloka** [alphacep/vosk-api#58]
Есть ошибка при построении из исходников как у Вас описано в reamde. Строится все ок, но при попытке запустить тестовый exe файл вываливается ошибка.

```
BadImageFormatException: Была сделана попытка загрузить 
программу, имеющую неверный формат. 
(Исключение из HRESULT: 0x8007000B)
```

Если использовать Visual Studio и те файлы, что сгенерировал swig - ошибка та же. Строил и под х86 и под х64.

![Безымянный](https://user-images.githubusercontent.com/5623092/78753549-9fad5b00-797e-11ea-919e-adce686f14f1.png)

**Comment by nshmyrev** [comment]
Настройки компиляции не совпадают с нужными. Подробно можно прочесть здесь:

https://docs.microsoft.com/en-us/dotnet/api/system.badimageformatexception?view=netframework-4.8

**Comment by verloka** [comment]
> Настройки компиляции не совпадают с нужными. Подробно можно прочесть здесь:
> 
> https://docs.microsoft.com/en-us/dotnet/api/system.badimageformatexception?view=netframework-4.8

Где я должен использовать эти настройки компиляции? Пример из вашего readme не работает.

Как я уже писал, смена разрядности не помогает.

**Comment by nshmyrev** [comment]
> Где я должен использовать эти настройки компиляции? 

При сборке библиотеки.

> Пример из вашего readme не работает.

В примере написано **mono**, а не .NET.

> Как я уже писал, смена разрядности не помогает.

Там не только смена разрядности, а еще и другие заморочки:

Reflecting on C++ executable files may throw this exception. This is most likely caused by the C++ compiler stripping the relocation addresses or the .Reloc section from the executable file. To preserve the .relocation address in a C++ executable file, specify /fixed:no when linking.

**Comment by verloka** [comment]
Я от плюсов очень далек, можете подсказать, куда мне указать `/fixed:no` ?
Где-то в vosk-api/csharp/Makefile ?

**Comment by verloka** [comment]
> > Где я должен использовать эти настройки компиляции?
> 
> При сборке библиотеки.
> 
> > Пример из вашего readme не работает.
> 
> В примере написано **mono**, а не .NET.
> 
> > Как я уже писал, смена разрядности не помогает.
> 
> Там не только смена разрядности, а еще и другие заморочки:
> 
> Reflecting on C++ executable files may throw this exception. This is most likely caused by the C++ compiler stripping the relocation addresses or the .Reloc section from the executable file. To preserve the .relocation address in a C++ executable file, specify /fixed:no when linking.

Mожете подсказать, куда мне указать /fixed:no ?
Где-то в vosk-api/csharp/Makefile ?

**Comment by nshmyrev** [comment]
Придётся разобраться самому. Предлагаю начать со сборки простого примера вроде такого https://manski.net/2012/05/pinvoke-tutorial-basics-part-1/
