### ISSUE TITLE
Python vosk srt example failed to use with vosk v0.3.30

### ISSUE THREAD

**Issue by xqqy** [alphacep/vosk-api#580]
Dear maintainer
Using together with the Kdenlive and example here, I have found recent update(v0.3.30) on pypi are not working for `test_srt.py` anymore because there is not a 'result' in all 'jres' anymore, and may cause all voice to srt failed.
Maybe there is some api changed?

**Comment by NTT123** [comment]
@xqqy I discovered that `rec.SetWords(True)` gets `result` back.

**Comment by zyb8543d** [comment]
It's not directly related，`rec.SetWords(True)` just for returning best path with  words and time stamps. Default only return best path or partial result.

**Comment by NTT123** [comment]
With version 0.3.30, it contains timestamp also. See https://github.com/alphacep/vosk-api/commit/75bedfe06df51ab58e82c0d42676b8dbfc576177

**Comment by nshmyrev** [comment]
Yeah, we changed the API slightly. I wonder if we need to submit kdenlive patch.

**Comment by nshmyrev** [comment]
I hope this one is fixed
