### ISSUE TITLE
I cant run vsok api with whole english models Python 

### ISSUE THREAD

**Issue by Mujtabaomar111** [alphacep/vosk-api#581]
C:\Users\Mujtaba\Desktop\python\example>test_ffmpeg.py test.wav
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.171862 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:278) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo model/graph/phones/word_boundary.int
Traceback (most recent call last):
File "C:\Users\Mujtaba\Desktop\python\example\test_ffmpeg.py", line 22, in
stdout=subprocess.PIPE)
File "C:\Users\Mujtaba\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in init
restore_signals, start_new_session)
File "C:\Users\Mujtaba\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by nshmyrev** [comment]
Same as #575

**Comment by Mujtabaomar111** [comment]
[image: image.png]
