### ISSUE TITLE
Japanese

### ISSUE THREAD

**Issue by hidemat** [alphacep/vosk-api#585]
Is japanese planned for support any time soon?

**Comment by nshmyrev** [comment]
Sure, but I don't think it will be fast, we need to find the data for it.

**Comment by hidemat** [comment]
Nice, any way I can help?

**Comment by nshmyrev** [comment]
It depends on your skills and capabilities. You can get access to https://github.com/laboroai/LaboroTVSpeech and train yourself for example.

**Comment by nshmyrev** [comment]
We have released Japanese recently
