### ISSUE TITLE
Erratic Behavior of OpenFST SymbolTable

### ISSUE THREAD

**Issue by CatalinVoss** [alphacep/vosk-api#588]
When I compile OpenFST  from https://github.com/alphacep/openfst on a Mac from scratch using a pipeline very similar to the one in the Dockerfile, the resulting `SymbolTable` behaves extremely oddly.

At first, it won't return symbols for known words, but the reverse lookup will work

```
auto result = word_syms->Find(sym_test); // should be 115144, but returns -1
std::cout << "Test lookup for hello: " << result <<std::endl; // prints -1
std::cout << "Reverse lookup for hello: " << word_syms->Find(115144) <<std::endl; // prints "hello" correctly
```

Then, calling `Find()` repeatedly will get it to work eventually, but sometimes the symbol returned will correspond just to the first letter of the word. It will also return matches for words that are clearly not in the symbol table.

Any idea what this might be? It feels like a hashing issue of some sort.

I also saw @nshmyrev comment on http://www.openfst.org/twiki/bin/view/Forum/FstForum about the `string_hash_ranges` deprecation warnings and am wondering if that might be related.

Thank you!

**Comment by nshmyrev** [comment]
I haven't seen anything like that, what is your OS and compiler exactly?

The difference might be due to compiler mismatch like you compiled openfst with one compiler and compile vosk with another compiler.

**Comment by CatalinVoss** [comment]
Indeed! It was a C++11 vs. 17 mismatch.  🙌

**Comment by CatalinVoss** [comment]
Thanks Nickolay!
