### ISSUE TITLE
Export transcript in segmentation or fragments

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#589]
I have to ask if or how is it possible to get the export in segmentation? If it is possible while export.?

**Comment by nshmyrev** [comment]
I'm sorry, I don't get what you want to export and what do you mean by "export" in detail.

**Comment by kch0p** [comment]
I think he's asking what command to use to export all of the "text" together into a .txt file at the end? Or if there's a command like that currently?
