### ISSUE TITLE
Final result empty because of too much silence at the end?

### ISSUE THREAD

**Issue by fquirin** [alphacep/vosk-api#590]
I'm currently building the [new SEPIA STT WebSocket server](https://github.com/SEPIA-Framework/sepia-docs/discussions/112) and the first beta integration of Vosk is already working pretty well :slightly_smiling_face: :+1: , but there is one thing that is giving me some headaches :grimacing: .

I'm sending chunks of audio to the recognizer, basically in the same way the vosk-server demo does:
```
if self._recognizer.AcceptWaveform(chunk):
    result = self._recognizer.Result()
else:
    result = self._recognizer.PartialResult()
```
and then at some point I stop the audio input and call `result = self._recognizer.FinalResult()`.

Now the problem is that sometimes the last partial result is empty and if that happens final will be empty as well.
I think this is because internally the recognizer starts a new section/sentence which is totally fine and understandable but it would be good if we can catch the event and get an "intermediate" final result.

**Comment by fquirin** [comment]
Ok, so I was browsing the cc code a bit and realized that `AcceptWaveform` actually does what I need and spits out "intermediate" final results before the "reset" :+1: 
I think the Python examples are a bit confusing here and suggest that `AcceptWaveform` just processes data before a partial result is even possible :thinking:

**Comment by nshmyrev** [comment]
Hi @fquirin. I'm sorry, I don't get the problem. If you have empty final result we return it, what else do you expect?

**Comment by fquirin** [comment]
Hi Nickolay,
the problem is that I don't fully understand when `AcceptWaveform()` returns true and what the difference is between `Result()` compared to `PartialResult()` or `FinalResult()` ;-)
Maybe I missed some documentation here?

**Comment by nshmyrev** [comment]
AcceptWaveform returns true when silence is detected and you can retrieve the result with Result(). If silence is not detected you can retrieve PartialResult() only. FinalResult means the stream is ended, you flush the buffers and retrieve remaining result.

We'll be changing this API so Vosk will decide by itself which result to for every submission or if it needs to return multiple results.

**Comment by fquirin** [comment]
Thanks for clarifying :+1:
Will the changes break the old API? ... do I have to be prepared to fix my code soon? :-p

**Comment by nshmyrev** [comment]
> Will the changes break the old API? 

Yes, sorry

> do I have to be prepared to fix my code soon?

Sure, I'll let you know

**Comment by fquirin** [comment]
> Sure, I'll let you know

:sweat_smile:  ok thanks

Btw: This is actually a new issue but confidence levels are not normalized to 1 it seems. Any tips on how to estimate if confidence is high or low? :-)

**Comment by nshmyrev** [comment]
> This is actually a new issue but confidence levels are not normalized to 1 it seems. 

Please open a new issue and provide an example file

**Comment by fquirin** [comment]
I've created a new issue here: https://github.com/alphacep/vosk-api/issues/604 and consider this one solved :-)

**Comment by solyarisoftware** [comment]
>AcceptWaveform returns true when silence is detected and you can retrieve the result with Result(). If silence is not detected you can retrieve PartialResult() only. FinalResult means the stream is ended, you flush the buffers and retrieve remaining result.

>We'll be changing this API so Vosk will decide by itself which result to for every submission or if it needs to return multiple results.


Hi Nicolay, just a thought: following nodejs/javascript way it could be nice to generate a (Recognizer) [event](https://blog.logrocket.com/building-custom-node-js-event-emitters/) when the AcceptWaveform generates new outputs (single words or multi words). In that way, in the client application I would like to do something nice like

```javascript
// single word detected
recognizer.on('word', result => {  
  console.log(result) 
})

//  multi words detected
recognizer.on('words', results => {  
  console.log(results) 
})
```  

Just an idea

**Comment by solyarisoftware** [comment]
Hi @Nicolay
FYI, I implemented my above proposal in vokjs. See:
- https://github.com/solyarisoftware/voskJs#streaming-based-transcript-api
- https://github.com/solyarisoftware/voskJs/blob/master/voskjs.js#L339
