### ISSUE TITLE
v0.3.30 wheel files?

### ISSUE THREAD

**Issue by fquirin** [alphacep/vosk-api#592]
I've just realized that my Windows version of Vosk is 0.3.30 but the GitHub releases end with 0.3.27.

Will you upload the wheel files for 0.3.30? I'm looking especially for the Arm64/Aaarch64 file for Rasperry Pi OS 64bit :grin: since I had to completely disable "words" and "alternatives" feature to avoid Python errors ^^.

**Comment by nshmyrev** [comment]
Done, thank you for reporting!

https://github.com/alphacep/vosk-api/releases/tag/0.3.30

**Comment by fquirin** [comment]
Awesome! Thanks a lot @nshmyrev  :+1:
