### ISSUE TITLE
v0.3.30 npm package missing / changelog (minor request)

### ISSUE THREAD

**Issue by solyarisoftware** [alphacep/vosk-api#594]
Hi Nicolay 

you didn't published last version of node package:

```
$ npm info vosk

vosk@0.3.27 | Apache-2.0 | deps: 5 | versions: 6
Node binding for continuous offline voice recoginition with Vosk library.
https://github.com/alphacep/vosk-api#readme

keywords: speech, speech recognition, voice

dist
.tarball: https://registry.npmjs.org/vosk/-/vosk-0.3.27.tgz
.shasum: 1b6205e3750381223bc9ee628e96e3d95e6fe95c
.integrity: sha512-+1WxODmScEqJmuqFRRqD9d1AxiqnNvED1E6/fnV9RlxxrDWUuvPRtRo19BIacd7QalH67GR8wGAHjbfFHH3//Q==
.unpackedSize: 77.7 MB

dependencies:
async: ^3.2.0     ffi-napi: ^4.0.3  mic: ^2.1.2       ref-napi: >=2.0.0 wav: ^1.0.2       

maintainers:
- nshmyrev <nshmyrev@gmail.com>

dist-tags:
latest: 0.3.27  

published a month ago by nshmyrev <nshmyrev@gmail.com>

```

If it’s just an oversight, could you make a `npm publish`? Thanks!

---

A collateral request/suggestion: when you release a "main" release (e.g. v0.3.30) I'd suggest to publish a small documentation (just few lines) to track updates, as new features. I mean just writing down really few lines in a CHANGELOG.md (I do [this](https://github.com/solyarisoftware/voskJs/blob/master/CHANGELOG.md) just as a rough example) to introduce ne functionalities. 

BTW, reading code I guess new functions are recognizer methods `setMaxAlternatives` and `setWords`, but why you stated that "API changed unfortunately" ? It seems to me that the interface isn't broken.

Thanks for your great work and your continuous support to people! 
Giorgio

**Comment by nshmyrev** [comment]
> If it’s just an oversight, could you make a npm publish? Thanks!

Done

> A collateral request/suggestion: when you release a "main" release (e.g. v0.3.30) I'd suggest to publish a small documentation (just few lines) to track updates, as new features. I mean just writing down really few lines in a CHANGELOG.md (I do this just as a rough example) to introduce ne functionalities.

We will consider that, thank you

> BTW, reading code I guess new functions are recognizer methods setMaxAlternatives and setWords, but why you stated that "API changed unfortunately" ? It seems to me that the interface isn't broken.

It doesn't print words anymore if you don't mention setWords(True) like it was before.

**Comment by solyarisoftware** [comment]
Thanks Nicolay.

Maybe it could be a good idea to add a `npm publish` everytime you git commit? :-)

BTW, beside the suggested CHANGELOG.md, I'd propose to insert in this [README.md](https://github.com/alphacep/vosk-api/tree/master/nodejs) a "install" section" to remind people they have to do `npm install vosk` in the project directory (here an [example of the install section](https://github.com/solyarisoftware/voskjs#-install)) ;-)

 About last point, maybe you would avoided API change just reversing the logic, setting setWords(True) by default. But evidently there are good reasons why setWords(False) as default is better. Maybe to save performances/log data in long transcripts? Never mind.
 
Thanks
