### ISSUE TITLE
Could not resolve com.alphacephei:vosk:0.3.29.

### ISSUE THREAD

**Issue by Yellowstrawberrys** [alphacep/vosk-api#597]
gradle version is 7.0
Java version is 8

```
Could not resolve com.alphacephei:vosk:0.3.29.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by Yellowstrawberrys** [comment]
I tried every version but it doesn't worked too. :(

**Comment by nshmyrev** [comment]
You need to add a link to maven repo:

https://alphacephei.com/maven/

In Gradle its

```
repositories {
    mavenCentral()
    maven {
        url 'https://alphacephei.com/maven/'
    }
}
```

**Comment by Yellowstrawberrys** [comment]
I used but it doesn't work too
![image](https://user-images.githubusercontent.com/77413533/122687142-30cfc100-d215-11eb-986f-81cd4179d88a.png)

**Comment by nshmyrev** [comment]
Try to run demo code first:

https://github.com/alphacep/vosk-api/tree/master/java/demo

if still doesn't work, provide full build log

**Comment by Yellowstrawberrys** [comment]
```
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: ./model/mfcc.conf
Exception in thread "main" java.lang.Error: Invalid memory access
	at org.vosk.LibVosk.vosk_model_new(Native Method)
	at org.vosk.Model.<init>(Model.java:10)
	at org.vosk.demo.DecoderDemo.main(DecoderDemo.java:21)
```
it's working but it gets error

![image](https://user-images.githubusercontent.com/77413533/122687825-d9cbeb00-d218-11eb-9308-20cc76a35e85.png)

**Comment by nshmyrev** [comment]
You didn't arrange model files properly.

**Comment by Yellowstrawberrys** [comment]
how to make config file?

**Comment by nshmyrev** [comment]
You dont' have to make it, it is already inside the model. You just need to point a proper path to the model in the code.

**Comment by Yellowstrawberrys** [comment]
but it said there aren't config file in model

**Comment by nshmyrev** [comment]
> but it said there aren't config file in model

In every model there is a config file, it is either in the top folder or in conf subfolder of the top folder.

**Comment by Yellowstrawberrys** [comment]
I have question about api,
Can I use AudioInputStream or do I need to use InputSteam?
(in line 27 or line 22)

**Comment by nshmyrev** [comment]
> Can I use AudioInputStream or do I need to use InputSteam?

Have you ever heard about inheritance in OOP?

> (in line 27 or line 22)

Of which file?
