### ISSUE TITLE
Build vosk natively for electron

### ISSUE THREAD

**Issue by himat** [alphacep/vosk-api#598]
I'm trying to import vosk in an electron project, but it's not working:
At the `require("vosk")` line that I have in my js file, there is a js console error printed in the electron renderer console that says:`Uncaught Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=80 uv=1 libc=glibc node=12.14.1 electron=9.4.4 webpack=true`

I tried to use [electron-rebuild](https://www.npmjs.com/package/electron-rebuild) to rebuild it, and so I ran `$(npm bin)/electron-rebuild` in my electron project directory with vosk already installed via npm, and the electron-rebuild cli said that it rebuilt node-ffi. But when I re-ran my electron project, the same error still showed up.

What is the proper way to rebuild vosk for electron?
I saw this issue, but I couldn't really follow what was tried there: https://github.com/alphacep/vosk-api/issues/466

**Comment by nshmyrev** [comment]
I would start with testing that ffi works in your electron

**Comment by himat** [comment]
That was helpful actually.
I found that ffi by itself wasn't working with their example, so I fixed that by adding ffi-napi to my webpack externals like here https://github.com/node-ffi-napi/node-ffi-napi/issues/157. And I did the same with vosk now.

So now I don't get the same native build not found error.
But I get this error instead:
```
TypeError: rec.setMaxAlternatives is not a function
    at testVosk.ts:32
    at Generator.next (<anonymous>)
    at testFfi.ts:14
    at new Promise (<anonymous>)
    at __awaiter (testFfi.ts:14)
    at Reader.<anonymous> (testVosk.ts:26)
    at Reader.emit (events.js:223)
    at Reader._onSubchunk1 (reader.js:152)
    at process (index.js:270)
    at index.js:204
```

Here's the code I'm running (just the same as the vosk nodejs test_simple.js code https://github.com/alphacep/vosk-api/blob/master/nodejs/demo/test_simple.js)

```
const MODEL_PATH = "./models/vosk-model-small-en-us-0.15";
const FILE_NAME = "./local/test.wav";

export const runVosk = () => {
  if (!fs.existsSync(MODEL_PATH)) {
    console.log(
      "Please download the model from https://alphacephei.com/vosk/models and unpack as " +
        MODEL_PATH +
        " in the current folder."
    );
    process.exit();
  }

  vosk.setLogLevel(0);
  const model = new vosk.Model(MODEL_PATH);

  const wfReader = new wav.Reader();
  const wfReadable = new Readable().wrap(wfReader);

  wfReader.on("format", async ({ audioFormat, sampleRate, channels }) => {
    if (audioFormat != 1 || channels != 1) {
      console.error("Audio file must be WAV format mono PCM.");
      process.exit(1);
    }
    const rec = new vosk.Recognizer({ model: model, sampleRate: sampleRate });
    rec.setMaxAlternatives(10); // ***error here
    rec.setWords(true);
    for await (const data of wfReadable) {
      const end_of_speech = rec.acceptWaveform(data);
      if (end_of_speech) {
        console.log(JSON.stringify(rec.result(), null, 4));
      }
    }
    console.log(JSON.stringify(rec.finalResult(rec), null, 4));
    rec.free();
  });

  fs.createReadStream(FILE_NAME, { highWaterMark: 4096 })
    .pipe(wfReader)
    .on("finish", function (err) {
      model.free();
    });
};

```

**Comment by solyarisoftware** [comment]
@himat 
I don't use elctron but I think: 
1. you didn't install the module dependencies (e.g. ffi-napi), and 
2. the reason you get `TypeError: rec.setMaxAlternatives is not a function` is because this function is part of last vosk release (the npm package has been updated yesterday).

Suggestions:
- assure the you have installed all vosk dependencies. Usually you do this just with  `npm install vosk@latest` in your project directory.
- assure you have the last vosk version (0.3.30 )

```
$ npm info vosk

vosk@0.3.30 | Apache-2.0 | deps: 5 | versions: 8
Node binding for continuous offline voice recoginition with Vosk library.
https://github.com/alphacep/vosk-api#readme

keywords: speech, speech recognition, voice

dist
.tarball: https://registry.npmjs.org/vosk/-/vosk-0.3.30.tgz
.shasum: 6faef8f041a10fc9daabec9d2d3f1941e4014cd8
.integrity: sha512-WvVJpvbPMekbPXZq/tbBhNgegU+atubyhvTzORtej0EhvZvgYqET+8p5ipgfp0EKSYLEilaISoS5xcPHNbQpSg==
.unpackedSize: 77.9 MB

dependencies:
async: ^3.2.0     ffi-napi: ^4.0.3  mic: ^2.1.2       ref-napi: >=2.0.0 wav: ^1.0.2       

maintainers:
- nshmyrev <nshmyrev@gmail.com>

dist-tags:
latest: 0.3.30  

published 14 hours ago by nshmyrev <nshmyrev@gmail.com>
```

**Comment by nshmyrev** [comment]
Lets track this in #466
