### ISSUE TITLE
What does “ERROR: fstsymbols: Saving osymbols but there are no output symbols” means and how can i solve it?

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#599]
I wanted to update the language model of Kaldi model used in Vosk. I was following the Updating the language model in Vosk Adaptation Document.

I had this **ERROR: fstsymbols: Saving osymbols but there are no output symbols** when I try to run `fstsymbols --save_osymbols=words.txt Gr.fst > /dev/null`. I guess the words.txt is the new text which I want to recognize right?

**Comment by nshmyrev** [comment]
It says the FST Gr.fst has not output symbols. It is not an expected situation, something went wrong.

**Comment by nshmyrev** [comment]
> how can i solve it

You need to provide more information where did you find this bad Gr.fst

**Comment by ghost** [comment]
> > how can i solve it
> 
> You need to provide more information where did you find this bad Gr.fst

I get the Gr.fst from the "graph" folder in vosk-model-en-us-daanzu-20200905-lgraph. This model is downloaded from Vosk.

**Comment by nshmyrev** [comment]
There is words.txt already in this model, you can skip that step

**Comment by ghost** [comment]
Okay Thanks
