### ISSUE TITLE
Is there any documentation for python?

### ISSUE THREAD

**Issue by MikeyBeez** [alphacep/vosk-api#60]
I can run your test_microphone.py script, and the results are stunningly accurate!  You've created a fantastic English model.  But I would like to control how results are printed.  I only want to last line with the completed text.  Right now, it shows a word, then two words, then three, etc.  So I don't know how I can parse it for commands.  BTW, does one need to install kaldi first?  I did, but in retrospect, I'm not sure that I needed too.   You might want to update your readme to reflect that.  Cheers, and thank you!!

**Comment by MikeyBeez** [comment]
All I needed to do was look carefully at the output.  Duh!  Sorry.

**Comment by nshmyrev** [comment]
Ok, thank you. Documentation indeed requires some more work. Let us know if you have further questions. There are more accurate models too, but they are bigger in size.

**Comment by MikeyBeez** [comment]
You're terrific to do this.  Where is the KaldiRecognizer api documentation or code?  Is it code from kaldi or vosk? I don't know how to work with rec.Result and rec.PartialResult.  Are they returning text or a json object?  Are there other methods?  I think I can try using Dir from a python command line, but I'll need to refresh my memory on that.  If there is documentation, that would help.  One thing I find funny is that I the vosk-api instructions are to import vosk, which seems to be a separate repository.   Cheers, and thanks again.

**Comment by MikeyBeez** [comment]
Never mind.  I figured out it's a string; so I used the split method.  I've just what I need now for my virtual assistant. I won't even need google in the cloud!   I've tested your model, and it is understanding all my voice commands.  Cheers!

**Comment by nshmyrev** [comment]
> I figured out it's a string; so I used the split method. I've just what I need now for my virtual assistant.

its json object actually, you can use json.loads to parse it.

**Comment by MikeyBeez** [comment]
In case others need this:  while True:
    data = stream.read(2000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        #print(rec.Result())
        # I commented out this line and added the 3 lines below
        myResult = rec.Result()
        myList = myResult.split("text")
        print(myList[1])
    # I commented out everything below
    #else:
    #    print(rec.PartialResult())
    #    print("two")

#print(rec.FinalResult())

**Comment by MikeyBeez** [comment]
Thank you, Nickolay.  BTW, did I need to build kaldi?  Or did I do a lot of work for nothing?  Cheers!

**Comment by nshmyrev** [comment]
> Thank you, Nickolay. BTW, did I need to build kaldi? Or did I do a lot of work for nothing? Cheers!

If you want to play with the vocabulary and phrases, yes. Otherwise you don't need to build kaldi, simple `pip install` works.

**Comment by MikeyBeez** [comment]
Wonderful.  This will make it so much easier for others who read my instructions.  If you are interested, look at my repository named Juliet.  It's working well now.  I had to modify the kaldi-api example code to close the pyaudio stream.  Now it doesn't crash.   Anyway, just thank you, again and again.  :)

**Comment by nshmyrev** [comment]
@MikeyBeez thanks, I'll follow your progress. Hope to bring you some more features and accuracy too! Let me know if you have further questions.

**Comment by 812406210** [comment]
> > I figured out it's a string; so I used the split method. I've just what I need now for my virtual assistant.
> 
> its json object actually, you can use json.loads to parse it.

hello ,i  have a question, i run test_ffmpeg.py  and parse rec.Result() use json ，but the result is null ,can you tell  me how to solve it, thanks
![image](https://user-images.githubusercontent.com/22192011/110889409-0a9ea900-8329-11eb-9ced-f9661a127b64.png)

**Comment by 812406210** [comment]
> Wonderful. This will make it so much easier for others who read my instructions. If you are interested, look at my repository named Juliet. It's working well now. I had to modify the kaldi-api example code to close the pyaudio stream. Now it doesn't crash. Anyway, just thank you, again and again. :)



> In case others need this: while True:
> data = stream.read(2000)
> if len(data) == 0:
> break
> if rec.AcceptWaveform(data):
> #print(rec.Result())
> # I commented out this line and added the 3 lines below
> myResult = rec.Result()
> myList = myResult.split("text")
> print(myList[1])
> # I commented out everything below
> #else:
> # print(rec.PartialResult())
> # print("two")
> 
> #print(rec.FinalResult())

hello ,i have a question , how can i use json  to parse rec.Result().
i use it to parse result,but  the parse result is null 
![Uploading image.png…]()

**Comment by nshmyrev** [comment]
@812406210 start a new issue, do not post to the old one. As for parsing you can do like this:

     jres = json.loads(rec.Result())

**Comment by 812406210** [comment]
thanks， i see other issue ,use it
