### ISSUE TITLE
Train Custom Vosk Model

### ISSUE THREAD

**Issue by DevelopedByAnurag** [alphacep/vosk-api#609]
Hi, I was looking to train a custom vosk model for which I had a look at https://alphacephei.com/vosk/models and trained a simple khaldi model but as Stated on the link too I am not able to run the model. Is there any way to convert Khaldi model to Vosk or a Documentation for how to train a custom Vosk model. that explains steps on How to train a Vosk Model ?

**Comment by LuggerMan** [comment]
Hello @DevelopedByAnurag , u can look here -> https://github.com/kaldi-asr/kaldi/tree/master/egs/wsj/s5/steps/nnet3/chain2 and start from there, it contains most up to date version of scripts to train a chain model. Conversion is not possible afaik

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/41
