### ISSUE TITLE
Improve Accuracy with Alternative Results

### ISSUE THREAD

**Issue by destinyb-realityi** [alphacep/vosk-api#61]
I had an idea to possibly help improve speech results with Vosk API. 
When the results are returned to the client application via Vosk API, they're returned in an array with each object in the array containing a word and it's confidence level. 

What I'm proposing is instead of the objects containing a single word, it should return an array of possible words that each word could be. 

The purpose of this is if an application is looking for a specific sentence, it’s easier to search through a variety of possibilities rather than one result. With one result it leaves room for possible error and the user having to repeat themselves several times. 

Example: 
**NOTE**: I apologize if my example doesn't make a whole lot of sense, just used the best _alternative_ words I could think sound alike. 
```json
[
    {
        "confidence": 0.999998,
        "word": "Hello",
        "alternatives": [
            "Mellow",
            "Yellow"
        ]
    },
    {
        "confidence": 1.000000,
        "word": "There",
        "alternatives": [
            "Bear",
            "Bare",
            "Share",
            "Care"
        ]
    }
]
```

**Comment by nshmyrev** [comment]
Great idea, we might want to implement it some time in the future. The problem with such per-word lists is mainly in the timings, wth the buckets timings become not really accurate. It is probably better to return n-best lists google-style.

**Comment by destinyb-realityi** [comment]
Understood. Do you have any suggestions in a meantime on how to improve accuracy or determine "alternative" words? 

I had this idea when I was testing the Vosk API in my Android project. 
The accuracy was good a lot of the time, but others it would respond with words that sounded really similar to what I was saying. 

The biggest purpose of this is to implement "Google Home" like app but not require the person to have to repeat themselves, at least not often

**Comment by nshmyrev** [comment]
Accuracy improvement requires systematic approach, it is hard to give you the advice without detailed description of assistant functionality and everything.

**Comment by destinyb-realityi** [comment]
The application is a pretty basic interactive app. The purpose of the voice recognition in the app is so the user can interact with the app without having to physically touch the screen. 

For example, the user says "Go to x page" or "Show me x product" and the application would do that

**Comment by nshmyrev** [comment]
Ok, and what kind of product and how many of them?

**Comment by destinyb-realityi** [comment]
Could be any type of product. Think of a departmental catalog from amazon for example. TVs, Washers, Stoves, Cameras, etc.

**Comment by destinyb-realityi** [comment]
I don't think I'd have the user say the name of the product though, just to make accuracy simpler. If there was a catalog or something, I'd probably just have them say which number in the catalog the product is. Rather than the whole name

**Comment by nshmyrev** [comment]
Well, selection from a big inventory (> 1000 entries) requires some research and might not be that straightforward. You need a test database, integration of inventory with the decoder and maybe some tricks. There are companies built around similar technology like [W3W](https://what3words.com/). It definitely goes beyond this issue.

**Comment by destinyb-realityi** [comment]
I wasn't planning on having the whole inventory being accessed from voice commands though. As I previously stated I was planning on having basic commands to allow people to navigate through-out the application. 

Examples: 
- Go to catalog
- Go home 
- Show product one
- Show product three
- Compare product one two and three

The goal is to use very simple, easy to pronounce words to allow users to navigate through the application. Which is why I wasn't planning on having them have to say the whole product name.

**Comment by nshmyrev** [comment]
Ok, to get help on the accuracy you must:

1. Provide a detailed and complete description of the commands you want to recognize.
2. Provide the audio samples where you see the bad accuracy.
3. Provide the reference transcription for the samples above.

**Comment by destinyb-realityi** [comment]
How would you like to receive the audio samples?

**Comment by nshmyrev** [comment]
> How would you like to receive the audio samples?

Suggest two-three-four ways that work for you, I'll choose

**Comment by nshmyrev** [comment]
Lets continue to track this feature in #76

**Comment by dpny518** [comment]
how about taking ideas from mindmeld
```
https://www.mindmeld.com/docs/userguide/voice.html?highlight=asr#leveraging-asr-n-best-lists
https://github.com/cisco/mindmeld/blob/master/mindmeld/components/entity_resolver.py
```
