### ISSUE TITLE
SystemExit: TypeError: byte indices must be integers or slices, not str

### ISSUE THREAD

**Issue by nadhirhasan** [alphacep/vosk-api#613]
when i use vosk to my project it's get TypeError.how to handle this error.

**Comment by nshmyrev** [comment]
You need to provide more details if you need help

**Comment by nadhirhasan** [comment]
![input method](https://user-images.githubusercontent.com/86673541/124048866-e4fef200-da34-11eb-8368-6a11b456b1e6.png)
![vosk method](https://user-images.githubusercontent.com/86673541/124048896-f7792b80-da34-11eb-8061-8c0af26334b9.png)



sorry for the late reply.
there you can see two photos.when i use input method there is no error.but when i use vosk i immediatly got error

**Comment by nadhirhasan** [comment]
please help me

**Comment by nshmyrev** [comment]
Feel free to reopen once you have more details
