### ISSUE TITLE
Can vosk api support lm rescore?

### ISSUE THREAD

**Issue by joewale** [alphacep/vosk-api#614]

**Comment by nshmyrev** [comment]
Yes, our big models use carpa/rnnlm rescoring.

**Comment by joewale** [comment]
Thank you for your quick reply. The big model you mentioned is the model named "vosk-model-en-us-aspire-0.2"?  Can the rescore processing also support chinese model?

**Comment by nshmyrev** [comment]
We don't have Chinese models with rescoring but you can create one, yes.

**Comment by joewale** [comment]
ok，I have a try, thanks a lot
