### ISSUE TITLE
A speech segmentation model with phone level 

### ISSUE THREAD

**Issue by HCRJeewantha** [alphacep/vosk-api#615]
![Capture](https://user-images.githubusercontent.com/52495212/123998353-0a690d00-d9ef-11eb-890d-27942b0e3fc2.PNG)
hello, this is a spectrogram of the "hippopotamus" word. I'm trying to divide it into syllables level and get their start and end times, can I do it using intensity values? or is there any efficient way to do that using VOSK?  I developed word segmentation using VOSK.

**Comment by nshmyrev** [comment]
We have pull request for that, not yet merged:

https://github.com/alphacep/vosk-api/pull/528

**Comment by HCRJeewantha** [comment]
can I know what day that feature gonna available sir?
