### ISSUE TITLE
transcription and speakers

### ISSUE THREAD

**Issue by buscon** [alphacep/vosk-api#616]
hi,

I am using vosk for a transcription of an interview with 2 different persons.

Is there an example of how I can create an output text file that looks like:
[00:19] hello, we are now starting the interview. are you ready?

[00:27] yes, I do.

[00:31] ok, so here is my first question: what did you do during the experiment?

and so on.
I do not need proper speaker separation, It would be useful to have sentence separation when there is a small silence.

Thanks.

**Comment by nshmyrev** [comment]
No, Vosk does not support speaker separation

Tracked at https://github.com/alphacep/vosk-api/issues/405
