### ISSUE TITLE
Why Vosk in C slower than in Python?

### ISSUE THREAD

**Issue by mengxin19891107** [alphacep/vosk-api#618]
I have installed and build vosk in C++ on Raspi, it works. But I have noticed that, it works must slower than in Python. Why?
Thanks a lot if anyone explains it. Very appreciate!

**Comment by nshmyrev** [comment]
Did you build yourself of use prebuilt binaries? Maybe prebuilt binaries are ok, you can get the from releases.

**Comment by mengxin19891107** [comment]
I built vosk from source, and I want to bring vosk into QT5. I am sorry, what do you mean prebuilt binaries? I had build the libraries from kaldi. Thanks a lot for your answer!

**Comment by nshmyrev** [comment]
Try this library https://github.com/alphacep/vosk-api/releases/download/0.3.30/vosk-linux-armv7l-0.3.30.zip

**Comment by gantnermengxin** [comment]
Thanks so much with the link! I have already tried today with the prebuild library, it works really faster than before. I build the new one with the Makefile in /vosk-api/c/Makefile, it seems that it doesn't any liebraries of Kaldi? Is it so? Also it seems like, with the prebuild library also need no more fst and openblas liabraries?

**Comment by mengxin19891107** [comment]
Thanks so much with the link! I have already tried today with the prebuild library, it works really faster than before. I build the new one with the Makefile in /vosk-api/c/Makefile, it seems that it doesn't any liebraries of Kaldi? Is it so? Also it seems like, with the prebuild library also need no more fst and openblas liabraries?

**Comment by nshmyrev** [comment]
Yes, you can check https://github.com/alphacep/vosk-api/blob/master/travis/Dockerfile.dockcross to see how build it properly. Most likely you don't have some necessary optimization enabled.

**Comment by mengxin19891107** [comment]
Thank you so much!
