### ISSUE TITLE
Unable to load libvosk in C# on Ubuntu

### ISSUE THREAD

**Issue by hubbux** [alphacep/vosk-api#621]
I'm trying to run Vosk on Ubuntu. I use OpenTK to supply Vosk with microphone data and on Windows everything just works fine. But on Linux I get that problem:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libvosk' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibvosk: cannot open shared object file: No such file or directory
   at Vosk.VoskPINVOKE.new_Model(String jarg1)
   at LinuxTest.Program.Main(String[] args) in D:\Programming\.Net\LinuxTest\Program.cs:line 17
```

The files are:
```
libgcc_s_seh-1.dll  libvosk.dll          LinuxTest.deps.json  LinuxTest.exe  LinuxTest.runtimeconfig.dev.json  model       ref
libstdc++-6.dll     libwinpthread-1.dll  LinuxTest.dll        LinuxTest.pdb  LinuxTest.runtimeconfig.json      OpenTK.dll  Vosk.dll
```

So everything should be in the same directory.
This is built using .NET Core 5.0, tried x64 and x86. I used the NuGet package and not the source

**Comment by nshmyrev** [comment]
Ubuntu nuget package has libvosk.so, you can extract it from there.

**Comment by hubbux** [comment]
I am sorry but I can't seem to get it to work. I have built it on Linux and the libvosk.so is there. The error is still the same.
I may be asking much but if you have the time and are willing to do it, could I ask you to try it yourself and see if it works for you / tell me you file structure?

**Comment by nshmyrev** [comment]
> could I ask you to try it yourself 

Sure, what should I try exactly?

> D:\Programming\.Net\LinuxTest\Program.cs

Is it Linux or Window  Linux Subsystem?

**Comment by hubbux** [comment]
Please just try to run it on a Linux system. I have tried it on Ubuntu Server 21.04 x64. Because it doesn't matter if I build on Windows and port it to Linux or build it directly on Linux.
Thanks

**Comment by nshmyrev** [comment]
> Please just try to run it on a Linux system

I run the demo from our code on Linux. It works.

**Comment by nshmyrev** [comment]
You can try to run 'ldd libvosk.so', maybe libatomic is missing on your linux system.

**Comment by hubbux** [comment]
Thank you so much.
It really was libatomic that was missing
