### ISSUE TITLE
Segmentation Fault on Virtual Machine

### ISSUE THREAD

**Issue by Squalmals** [alphacep/vosk-api#624]
I am running a linux virtual machine (Pop!_OS v21.04, VMWare Workstation 16 Player, Intel i5 8600k, 4 allocated cores, 8gb allocated ram). When running the example file `test_microphone.py` in any configuration, I am greeted with this output:

`python3 test_microphone.py`
`Segmentation fault (core dumped)`

I have attached my valgrind outpout below:
[errorlog.txt](https://github.com/alphacep/vosk-api/files/6772835/errorlog.txt)

Notes:
I installed vosk using instructions from [here](https://medium.com/analytics-vidhya/offline-speech-recognition-made-easy-with-vosk-c61f7b720215), along with PortAudio with instructions from [here](http://portaudio.com/docs/v19-doxydocs/compile_linux.html)

**Comment by nshmyrev** [comment]
Does file decoding work for you?

**Comment by Squalmals** [comment]
> 
> 
> Does file decoding work for you?

It would appear that using the testing files to extract text from a prerecorded wav file works normally, but the microphone testing file still produces a segmentation fault, and occasionally a maloc/aborted error.

**Comment by nshmyrev** [comment]
> It would appear that using the testing files to extract text from a prerecorded wav file works normally, but the microphone testing file still produces a segmentation fault, and occasionally a maloc/aborted error.

It is probably an issue with portaudio library you installed, it should have a conflicting runtime inside it. Try to revert your portaudio changes and install portaudio from distribution.

**Comment by nshmyrev** [comment]
Let us know if you were able to make it work
