### ISSUE TITLE
i can not use vosk api nodejs 

### ISSUE THREAD

**Issue by emircankizilkaya** [alphacep/vosk-api#631]
when ı start test_microphone.js. it starts but can not take my voice or any voice. i installed all essential modules but nothing happened.  
this is my folder design. 
![1](https://user-images.githubusercontent.com/86236546/125615068-ea228c38-f427-4051-8b91-9c4d422e1f6e.png)

and when i write node test_microphone.js on console what happened.
![2](https://user-images.githubusercontent.com/86236546/125615369-e1b6ecb8-c62b-4ec8-a611-5f6482a31942.png)

**Comment by nshmyrev** [comment]
Probably microphone records just noise or sample rate is wrong. Try to set 44100. Also try to dump the audio to a file and listen if there is sound at all.

**Comment by emircankizilkaya** [comment]
![3](https://user-images.githubusercontent.com/86236546/125616919-ab2c311f-997e-451d-b876-18a1c9e044a2.png)
i only changed 
vosk=require("vosk"); 
in code.
how can i set 44100 and how can i dump the audio to a file and listen if there is sound at all.

by the way can you help me in dc or zoom?

**Comment by solyarisoftware** [comment]
> how can i set 44100 

const SAMPLE_RATE = 44100

BTW, as Nicolay suggested, verify first if your pc is able to record from the mic. Use any program like audacity or any audio recorder program.

**Comment by emircankizilkaya** [comment]
yes, i tried and my computer can record from the mic very good. also i did the sample rate 44100 but nothing happened. can you help me on dc or zoom . please

**Comment by solyarisoftware** [comment]
Share the recording , please

**Comment by emircankizilkaya** [comment]
this is my testing the microphone record
https://user-images.githubusercontent.com/86236546/125626041-6cf26a4c-a602-49b1-a0b8-5a76c499412c.mp4
 
by the way when i run python code for vosk. it will work very good at console. i had a problem for only nodejs.

**Comment by solyarisoftware** [comment]
I see. The problem could be related to the mic npm package:

https://www.npmjs.com/package/mic

I read that, on windows OS, it uses Sox behind the scenes.

Did you install Sox on Windows? If no, do it.

BTW, I do not use windows and the mic package too.

**Comment by emircankizilkaya** [comment]
i run it on linux centos8 and i installed all the essential packages again. now ı run the test_microphone.js but then it stops spontaneously.

![Ekran görüntüsü 2021-07-16 103528](https://user-images.githubusercontent.com/86236546/125910381-ccaf58ee-92e1-4140-b9c9-824a523a3c37.png)

**Comment by emircankizilkaya** [comment]
please help me

**Comment by sadrasabouri** [comment]
As @solyarisoftware said you should install `sox` library for windows and probably add its instillation path to `PATH` environmental variables. I think tThe issue is not related to vosk-api, you can find a library for nodejs that best suits you (look at `recordrtc` for example) and please update this issue with the result so that we can change our dependency library from `mic` to anything better.

Thak you.

**Comment by emircankizilkaya** [comment]
i installed sox and added to path but nothing change. Then i try this code on the linux and i lived the issue what i told in the previous comment. I am wondering that , did you run this codes before installing github! Because i can not do anything for problems.

**Comment by sadrasabouri** [comment]
You ran the example on a CentOS. I myself tested it on Ubuntu 20.04 LTS and it works fine.
As I said the microphone library is not that much a big deal you can test other libraries to find the best for your case.
Any microphone library will provide vosk-api a audio stream piping into `recognizer` and all of them should work in a identical manner after they actually work.

**Comment by emircankizilkaya** [comment]
so,i write my problem here because i can not solve . now you say me ,test library bla bla bla .  my problem is that how can i run test_microphone.js  on my computer?????????? it has windows and centos8 . you told me you try on ubuntu 20.04. What you mean i delete my OS and install ubuntu for this example. İ I've been asking for 2 days if someone can help me live (zoom or dc), no one is interested. if i knew i would already do it

**Comment by emircankizilkaya** [comment]
sadra help me please

**Comment by nshmyrev** [comment]
Something sox related probably
