### ISSUE TITLE
Impossible to compile test_vosk.c

### ISSUE THREAD

**Issue by NorisAlberto** [alphacep/vosk-api#632]
First of all i'm sorry if i'm getting something wrong but i'm pretty new at the linux game. 

The issue is that i cannot compile the test_vosk.c file if i try to:
`gcc test_vosk.c -o test_vosk`
i get: 

```

test_vosk.c:1:10: fatal error: vosk_api.h: No such file or directory
 #include <vosk_api.h>
          ^~~~~~~~~~~~
compilation terminated.

```
but if i try to `make` the Makefile in the c directory it gives me:
```
g++ test_vosk.o -o test_vosk -L../src -lvosk -ldl -lpthread -Wl,-rpath=../src
/usr/bin/ld: cannot find -lvosk
collect2: error: ld returned 1 exit status
Makefile:7: recipe for target 'test_vosk' failed
make: *** [test_vosk] Error 1

```

**Comment by nshmyrev** [comment]
You can download prebuilt binary here:

https://github.com/alphacep/vosk-api/releases/download/v0.3.30/vosk-linux-x86-0.3.30.zip

**Comment by nshmyrev** [comment]
Same as #561

**Comment by NorisAlberto** [comment]
Thanks!
For future reference after downloading the 'prebuilt binary' you'll have to put the .so inside the `/lib` directory.
`make` the Makefile inside the c directory and then go to #561

**Comment by mgiugliano** [comment]
The precompiled (static) libraries do not unfortunately include the version for macOs. Any suggestion on how to call vosk-api from C on a Mac?

**Comment by nshmyrev** [comment]
@mgiugliano https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-osx-0.3.42.zip

**Comment by mgiugliano** [comment]
> @mgiugliano https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-osx-0.3.42.zip

Thanks immensely and, should I have missed it, accept my sincere apologies.
