### ISSUE TITLE
Impossible to run ./test_vosk of test_vosk.c

### ISSUE THREAD

**Issue by NorisAlberto** [alphacep/vosk-api#633]
After the #632 issue i was able to `make` the makefile in the c directory but unfortunately now there are new errors that i can't figure out. In fact trying to `./test_vosk` the compiled of test_vosk.c i get 
```
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)
```
so as stated in #561 i downloaded a [model](http://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip) put it inside a folder named 'model' inside the c directory and run the scipt once again but now i get:
```
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.019964 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo model/graph/phones/word_boundary.int
```
and if i run `./test_vosk_speaker` of the test_vosk_speaker.c i get a different error
```
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0200009 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo model/graph/phones/word_boundary.int
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: spk-model/mfcc.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)
```
it looks like there's something wrong with Kaldi maybe? (even though running the python script everything works fine).
Any help would be super appreciated, Thanks.

**Comment by sadrasabouri** [comment]
Hi. Have you try downloading [vosk-model-spk-0.4.zip](https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip) and extract it into a directory named `spk-model/` (which is a different model for speaker identification)?
It may help you because as I see in the log vosk-api is trying to find `mfcc.conf` file for speaker identification.

**Comment by NorisAlberto** [comment]
So, i've tried as you suggested by downloading the [vosk-model-spk-0.4.zip](https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip) and extracting everything in a folder named spk-model in the /c directory of vosk-api folder. 
But now running `./test_vosk_speaker` gives me:
```
LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.019515 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo model/graph/phones/word_boundary.int
WARNING (VoskAPI:Check():nnet-nnet.cc:789) Node tdnn6.relu is never used to compute any output.
WARNING (VoskAPI:Check():nnet-nnet.cc:789) Node tdnn6.batchnorm is never used to compute any output.
WARNING (VoskAPI:Check():nnet-nnet.cc:789) Node output.affine is never used to compute any output.
WARNING (VoskAPI:Check():nnet-nnet.cc:789) Node output.log-softmax is never used to compute any output.
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 4 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 4 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 0 components, removed 4
Segmentation fault (core dumped)
```
At least now the error is different but it didn't took me very far unfortunately, moreover this didn't change the output of `./test_vosk`.

There must be some form of 'how to' because i'm actually just trying to run the base .c examples ... but i cannot find any.

**Comment by sadrasabouri** [comment]
Can you provide me with more details, like your OS and ...?
So that I can reproduce the bug?

**Comment by NorisAlberto** [comment]
Yes, thank you i'll try to tell you everything that i know I've done.

My device:
I'm on a dual boot with Windows 10 and Ubuntu 18.04.5 LTS 
Intel® Core™ i7-8565U CPU @ 1.80GHz × 8 
NVIDIA GeForce MX130/PCIe/SSE2

1. I downloaded Kaldi on an external drive because i don't have enough space on my laptop by following the [guide](https://kaldi-asr.org/doc/install.html) that they provide on their website and then installed it by reading and doing what stated in the INSTALL
2. `pip3 install vosk`
3. `git clone https://github.com/alphacep/vosk-api`
4. downloaded the [prebuilt binary](https://github.com/alphacep/vosk-api/releases/download/v0.3.30/vosk-linux-x86-0.3.30.zip), extracted it and put it in the /lib directory 
5. Went to vosk-api/c and ran `make`
6. In the same directory did:
```
wget https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.15.zip
unzip vosk-model-small-en-us-0.15.zip
mv vosk-model-small-en-us-0.15 model
```
7. Then running `./test_vosk` it gives me the error that i posted previously.

**Comment by nshmyrev** [comment]
> I downloaded Kaldi on an external drive because i don't have enough space on my laptop by following the guide that they provide on their website and then installed it by reading and doing what stated in the INSTALL

Not required

> pip3 install vosk

not required

> Then running ./test_vosk it gives me the error that i posted previously.

You need to copy python/exampe/test.wav to src/c folder.

**Comment by NorisAlberto** [comment]
Thank you!!!! I was finally able to make it work.
I followed this:
> You need to copy python/exampe/test.wav to src/c folder.

but instead of putting the test.wav in the vosk-api/src/c folder (which doesn't actually exists) i put it inside the vosk-api/c and now it works.
