### ISSUE TITLE
ASSERTION_FAILED (VoskAPI:ComputeFinalCosts():lattice-faster-decoder.cc:540)

### ISSUE THREAD

**Issue by fquirin** [alphacep/vosk-api#634]
Hi Vosk Team :-)

This one is going to be tricky and I wasn't really sure if I should post it at all, but maybe someone has an idea.
I saw this error once that crashed my server:
```
ASSERTION_FAILED (VoskAPI:ComputeFinalCosts():lattice-faster-decoder.cc:540) Assertion failed: (!decoding_finalized_)
```

It seems to be some kind of race condition since I haven't been able to reproduce it yet and I have no other information about it :-(
This is the (very) rough chain of events:
- Create a recognizer: `self._recognizer = KaldiRecognizer(self._model, self._sample_rate)`
- Stream audio chunks and process them via `self._recognizer.AcceptWaveform(chunk)`
- If AcceptWaveform returns true use `self._recognizer.Result()` else use `self._recognizer.PartialResult()`
- To stop the process call `self._recognizer.FinalResult()` (if final is pending) or `self._recognizer.Reset()`

I think what maybe happened was that AcceptWaveform, FinalResult or Reset were called at a bad time (maybe my state tracking failed or was victim of some race condition).

Can anyone make any sense of this error? :sweat_smile: Maybe its is related to one of the mentioned functions being called when they shouldn't have?
Any help would be appreciated :-)

**Comment by nshmyrev** [comment]
Reset is not for you, you can call FinalResult always.

We recently fixed Reset so it doesn't output this mistake. You'll maybe wait for the next release.

**Comment by fquirin** [comment]
Thanks for the info!
So if the last result was "final" and I want to stop all processes and release resources I just leave the recognizer alone instead of calling Reset()?

**Comment by nshmyrev** [comment]
> So if the last result was "final"

If you finalized the stream and called getFinalResult in the end there is no need to call Reset.

**Comment by fquirin** [comment]
'getFinalResult' would be `recognizer.FinalResult()` for Python correct? :-)

**Comment by nshmyrev** [comment]
> 'getFinalResult' would be recognizer.FinalResult() for Python correct? :-)

Yes
