### ISSUE TITLE
Broken links to english models.

### ISSUE THREAD

**Issue by lailacampos** [alphacep/vosk-api#637]
Hello. I'm trying to download the first two english models in the official Vosk page but the links appear broken.
Nothing happens when I click on them. Is there another way I can download them?
Here's the address where I'm trying to download from: [https://alphacephei.com/vosk/models](url)
I'm interested in the vosk-model-en-us-0.20 and vosk-model-small-en-us-0.15 models.

**Comment by nshmyrev** [comment]
Links work fine. Probably you can try different browser if your one is too old. Or you have some blocker somewhere.

**Comment by lailacampos** [comment]
> Links work fine. Probably you can try different browser if your one is too old. Or you have some blocker somewhere.

You're right. It did work in Edge for some reason, even though my chrome is up to date.
Thank you.
