### ISSUE TITLE
Do i need to use VOSK model every time

### ISSUE THREAD

**Issue by HCRJeewantha** [alphacep/vosk-api#638]
The vosk model that I'm using is the vosk-model-en-us-aspire-0.2 (1.4GB). Every time needs quite an amount of time to load the vosk model. Is it necessary to recreate the vosk object every time? It takes much time to load the model if we only load the model once. It can save up at least half of the time.

**Comment by nshmyrev** [comment]
> It takes much time to load the model

We have https://github.com/alphacep/vosk-server project which preloads the model
