### ISSUE TITLE
Word Probability adjustment

### ISSUE THREAD

**Issue by ammyt** [alphacep/vosk-api#64]
Hello, I read in the adaptation docs about the possibility of adjusting probabilities of certain words. Since my project requires a very limited set of vocabulary (20-30 words), I think this would be the way to go for me. I am using one of the models provided, so I guess I only have to do the 3 steps mentioned? Also, how should the text mentioned in step 1 look like?

Is there anymore documentation I can read about this?

Great work!

**Comment by nshmyrev** [comment]
You can probably try this example first: https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py
