### ISSUE TITLE
What should be the structure of the model with dynamic graph

### ISSUE THREAD

**Issue by joewale** [alphacep/vosk-api#644]

**Comment by joewale** [comment]
Hi , nshmyrev ,  what is the file architecture of model directory for dynamic graph generated by mkgraph_lookahead.sh ?

1.  Is it right as follows?

.
├── am
│   ├── final.mdl
│   ├── frame_subsampling_factor
│   └── tree
├── conf
│   ├── mfcc.conf
│   └── model.conf
├── graph
│   ├── HCLG.fst
│   ├── phones
│   │   ├── align_lexicon.int
│   │   ├── align_lexicon.txt
│   │   ├── disambig.int
│   │   ├── disambig.txt
│   │   ├── optional_silence.csl
│   │   ├── optional_silence.int
│   │   ├── optional_silence.txt
│   │   ├── silence.csl
│   │   ├── word_boundary.int
│   │   └── word_boundary.txt
│   ├── phones.txt
│   └── words.txt
├── ivector
│   ├── final.dubm
│   ├── final.ie
│   ├── final.mat
│   ├── global_cmvn.stats
│   ├── ivector.conf
│   ├── mfcc.conf
│   ├── online_cmvn.conf
│   └── splice.conf
└── rescore
    ├── Gr.fst
    └── HCLr.fst


2. The log of model initialization with the above model folder is as follows. Is is seem right to load the model with dynamic graph ?

LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0829799 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from /data/joewzheng/git_project/vosk-api/model/model_cn/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:263) Loading HCLG from /data/joewzheng/git_project/vosk-api/model/model_cn/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo /data/joewzheng/git_project/vosk-api/model/model_cn/graph/phones/word_boundary.int

**Comment by nshmyrev** [comment]
> Is it right as follows?

No, Gr and Hclr must be in graph folder. You can check other models for example

**Comment by joewale** [comment]
HCLG.fst is need in graph folder ?   where can I get the models for example with dynamic graph generated by mkgraph_lookahead.sh ?

**Comment by nshmyrev** [comment]
> HCLG.fst is need in graph folder ? 

No

> where can I get the models for example with dynamic graph generated by mkgraph_lookahead.sh ?

https://alphacephei.com/vosk/models/vosk-model-small-cn-0.3.zip

**Comment by joewale** [comment]
Thanks for your quick reply. I create the graph folder following the graph zip you support, and get the error. Is there some problem?

LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0815241 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from /data/joewzheng/git_project/vosk-api/model/model_cn_lookahead/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Loading HCL and G from /data/joewzheng/git_project/vosk-api/model/model_cn_lookahead/HCLr.fst /data/joewzheng/git_project/vosk-api/model/model_cn_lookahead/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo /data/joewzheng/git_project/vosk-api/model/model_cn_lookahead/word_boundary.int
Segmentation fault

**Comment by nshmyrev** [comment]
You can collect backtrace with gdb/valgrind to understand where is the problem. Maybe some file is missing in your model.

**Comment by joewale** [comment]
Thanks nshmyrev. I have found the problem and fixed it.
