### ISSUE TITLE
Use microphone in .c 

### ISSUE THREAD

**Issue by NorisAlberto** [alphacep/vosk-api#649]
Hi, 
is there a fast way to add the possibility of using the microphone also in the .c programs?
Is there maybe already a working example somewhere?
And if not do you recommend using [Portaudio](http://www.portaudio.com/)?
Thanks, in advance!

**Comment by nshmyrev** [comment]
It depends on the app you want to build. In general platform-specific audio API is better than portaudio. Unless you want a multi-platform demo.

**Comment by NorisAlberto** [comment]
Yes you're right since I'm trying to build a linux specific solution maybe Portaudio isn't the best one.
I see there are Linux specific APIs such as:
- Jack
- Oss
- Alsa
- Asihpi
Do you have tips on which one could work well with vosk?

**Comment by nshmyrev** [comment]
It doesn't matter which API to use, they all work as long as they record sound. On linux you might try pulseaudio probably.

**Comment by nshmyrev** [comment]
Same as #845
