### ISSUE TITLE
How I can use on Android without embedded models

### ISSUE THREAD

**Issue by michoael** [alphacep/vosk-api#651]
I want to use without download models because the size of the app 
or 
download model after download app when choosing a language
thanks

**Comment by nshmyrev** [comment]
We still plan to implement it, not there yet.

It is definitely in plans.

Code is here:

https://github.com/alphacep/vosk-android-demo/pull/147

**Comment by michoael** [comment]
thanks for your answer 
yes i used this demo and download model english and dutch in assets but i need user download models after download app becouse size app is very big
no way to download after install app

**Comment by solyarisoftware** [comment]
Hi,
a workaround could be to renounce to the native app, 

1. using instead a web solution (running inside a browser), see by example related project: 

    https://github.com/ccoreilly/vosk-browser

2. Less appealing to you maybe, manage ASR tasks on a server ...

My two cents
