### ISSUE TITLE
Partial confidence

### ISSUE THREAD

**Issue by abb128** [alphacep/vosk-api#655]
Is there a way to get the confidence level of a partial result? I am making an accessibility tool and I think it would be helpful to see the confidence, because there are cases where the words are complete nonsense if a foreign language is spoken or music is being played.

**Comment by nshmyrev** [comment]
There is some Kaldi support for that as described in https://www.danielpovey.com/files/2019_asru_incremental_determinization.pdf
but it didn't yet get into Vosk. We might try to add it one day.

**Comment by nshmyrev** [comment]
We now integrated it in 0.3.38, see setPartialWords(Tre).
