### ISSUE TITLE
why byte length is 4096?

### ISSUE THREAD

**Issue by lzwcyd** [alphacep/vosk-api#662]
```
public static String parse(InputStream in) throws UnsupportedAudioFileException, IOException {
        LibVosk.setLogLevel(LogLevel.DEBUG);
        try (Model model = new Model("vosk-en-us-model");
             InputStream ais = AudioSystem.getAudioInputStream(in);
             Recognizer recognizer = new Recognizer(model, 16000)) {

            int nbytes;
            byte[] b = new byte[4096];
            while ((nbytes = ais.read(b)) >= 0) {
                if (recognizer.acceptWaveForm(b, nbytes)) {
                    System.out.println(recognizer.getResult());
                } else {
                    System.out.println(recognizer.getPartialResult());
                }
            }

            return recognizer.getFinalResult();
        }
    }
```

why byte length is 4096?
I want to know this, please.

**Comment by nshmyrev** [comment]
It is an optimal chunk length to detect silences (about 0.1-0.2 seconds).

**Comment by lzwcyd** [comment]
Thank you, I have another question. I can recognize it normally when I use the microphone to input, but when I recognize the voice file, there will be no result. Here is my file
[record.wav.zip](https://github.com/alphacep/vosk-api/files/6977548/record.wav.zip)

**Comment by lzwcyd** [comment]
I think it may be a file problem. Could you please provide some suitable audio file parameters? E.g., sampling rate, etc

**Comment by nshmyrev** [comment]
> I think it may be a file problem. Could you please provide some suitable audio file parameters? E.g., sampling rate, etc

This audio file is OK. The content is Chinese? Chinese model decodes with the following result:

  "text" : "问答 本周 主要 更新 功能 一 栏 欢迎 体验 建议"

**Comment by lzwcyd** [comment]
> > I think it may be a file problem. Could you please provide some suitable audio file parameters? E.g., sampling rate, etc
> 
> This audio file is OK. The content is Chinese? Chinese model decodes with the following result:
> 
> "text" : "问答 本周 主要 更新 功能 一 栏 欢迎 体验 建议"

Yes, but I can't recognize the result here. Here is my code. Can you check it for me? Thank you very much.
```
  public FinalResultDto speechRecognition(MultipartFile file)
      throws IOException, UnsupportedAudioFileException {
    try (Model model = new Model("model");
        InputStream ais =
            AudioSystem.getAudioInputStream(new BufferedInputStream(file.getInputStream()));
        Recognizer recognizer = new Recognizer(model, 16000)) {

      int nbytes;
      byte[] b = new byte[4096];
      while ((nbytes = ais.read(b)) >= 0) {
        recognizer.acceptWaveForm(b, nbytes);
        log.debug("result: {}",recognizer.getResult());
        log.debug("partialResult : {}", recognizer.getPartialResult());
      }
      return objectMapper.readValue(recognizer.getFinalResult(), FinalResultDto.class);
    }
  }
```

**Comment by lzwcyd** [comment]
> > > I think it may be a file problem. Could you please provide some suitable audio file parameters? E.g., sampling rate, etc
> > 
> > 
> > This audio file is OK. The content is Chinese? Chinese model decodes with the following result:
> > "text" : "问答 本周 主要 更新 功能 一 栏 欢迎 体验 建议"
> 
> Yes, but I can't recognize the result here. Here is my code. Can you check it for me? Thank you very much.
> 
> ```
>   public FinalResultDto speechRecognition(MultipartFile file)
>       throws IOException, UnsupportedAudioFileException {
>     try (Model model = new Model("model");
>         InputStream ais =
>             AudioSystem.getAudioInputStream(new BufferedInputStream(file.getInputStream()));
>         Recognizer recognizer = new Recognizer(model, 16000)) {
> 
>       int nbytes;
>       byte[] b = new byte[4096];
>       while ((nbytes = ais.read(b)) >= 0) {
>         recognizer.acceptWaveForm(b, nbytes);
>         log.debug("result: {}",recognizer.getResult());
>         log.debug("partialResult : {}", recognizer.getPartialResult());
>       }
>       return objectMapper.readValue(recognizer.getFinalResult(), FinalResultDto.class);
>     }
>   }
> ```

The strange thing is that I can use another voice file normally
[自由在高处(男童).wav.zip](https://github.com/alphacep/vosk-api/files/6977778/wav.zip)
This makes me very puzzled.

**Comment by nshmyrev** [comment]
>       return objectMapper.readValue(recognizer.getFinalResult(), FinalResultDto.class);

You need to return all results, not just final.

**Comment by lzwcyd** [comment]
> You need to return all results, not just final.

 record.wav.zip all results is "呢吧 嘿嗯 好[SPK] 歌啊".This makes me even more confused.

**Comment by lzwcyd** [comment]
> > You need to return all results, not just final.
> 
> record.wav.zip all results is "呢吧 嘿嗯 好[SPK] 歌啊".This makes me even more confused.
At the same time, I also used vosk-server, but the results were also unsatisfactory.
here is my code ： 
```

  private ArrayList<String> results = new ArrayList<String>();

  private CountDownLatch recieveLatch;

  public FinalResultDto speechRecognition(MultipartFile file)
      throws IOException, WebSocketException, InterruptedException {
    WebSocketFactory factory = new WebSocketFactory();
    WebSocket ws = factory.createSocket("ws://localhost:2700");
    ws.addListener(
        new WebSocketAdapter() {
          @Override
          public void onTextMessage(WebSocket websocket, String message) {
            results.add(message);
            recieveLatch.countDown();
          }
        });
    ws.connect();

    DataInputStream dis = new DataInputStream(file.getInputStream());
    byte[] buf = new byte[8000];
    while (true) {
      int nbytes = dis.read(buf);
      if (nbytes < 0) break;
      recieveLatch = new CountDownLatch(1);
      ws.sendBinary(buf);
      recieveLatch.await();
    }
    recieveLatch = new CountDownLatch(1);
    ws.sendText("{\"eof\" : 1}");
    recieveLatch.await();
    ws.disconnect();
    log.info("results : {}", results);
    return null;
  }
```


here is result

```
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : "发 [FIL]"
}, {
  "partial" : "发 [FIL]"
}, {
  "partial" : "发 [FIL]"
}, {
  "partial" : "发 [FIL] 哦"
}, {
  "result" : [{
      "conf" : 0.134505,
      "end" : 5.430000,
      "start" : 0.000000,
      "word" : "发"
    }, {
      "conf" : 1.000000,
      "end" : 9.363597,
      "start" : 5.534881,
      "word" : "[FIL]"
    }, {
      "conf" : 0.928628,
      "end" : 10.530000,
      "start" : 9.900000,
      "word" : "哦"
    }],
  "text" : "发 [FIL] 哦"
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : "啊"
}, {
  "partial" : "啊"
}, {
  "partial" : "啊"
}, {
  "result" : [{
      "conf" : 0.762381,
      "end" : 13.920000,
      "start" : 11.040000,
      "word" : "[FIL]"
    }],
  "text" : "[FIL]"
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : "[FIL]"
}, {
  "partial" : "[FIL]"
}, {
  "result" : [{
      "conf" : 1.000000,
      "end" : 16.140000,
      "start" : 13.920000,
      "word" : "[FIL]"
    }],
  "text" : "[FIL]"
}, {
  "partial" : ""
}, {
  "partial" : "啊啊"
}, {
  "result" : [{
      "conf" : 0.816291,
      "end" : 18.480000,
      "start" : 17.040000,
      "word" : "[SPK]"
    }],
  "text" : "[SPK]"
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : "啊"
}, {
  "result" : [{
      "conf" : 0.776087,
      "end" : 22.400652,
      "start" : 18.480000,
      "word" : "[SPK]"
    }],
  "text" : "[SPK]"
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "result" : [{
      "conf" : 0.984228,
      "end" : 26.220000,
      "start" : 22.560000,
      "word" : "[FIL]"
    }],
  "text" : "[FIL]"
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "result" : [{
      "conf" : 0.678501,
      "end" : 33.359890,
      "start" : 28.276166,
      "word" : "[FIL]"
    }],
  "text" : "[FIL]"
}, {
  "partial" : ""
}, {
  "partial" : "哦"
}, {
  "result" : [{
      "conf" : 0.946397,
      "end" : 34.379707,
      "start" : 33.780000,
      "word" : "哦"
    }],
  "text" : "哦"
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "result" : [{
      "conf" : 0.470927,
      "end" : 36.240000,
      "start" : 35.040000,
      "word" : "[SPK]"
    }],
  "text" : "[SPK]"
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "partial" : ""
}, {
  "result" : [{
      "conf" : 0.469083,
      "end" : 50.190000,
      "start" : 40.080000,
      "word" : "呢"
    }],
  "text" : "呢"
}]
```

**Comment by lzwcyd** [comment]
> > ```
> >   return objectMapper.readValue(recognizer.getFinalResult(), FinalResultDto.class);
> > ```
> 
> You need to return all results, not just final.

Could you please share your code? Maybe it can enlighten me.

**Comment by lzwcyd** [comment]
> > > You need to return all results, not just final.
> > 
> > 
> > record.wav.zip all results is "呢吧 嘿嗯 好[SPK] 歌啊".This makes me even more confused.
> > At the same time, I also used vosk-server, but the results were also unsatisfactory.
> > here is my code ：
> 
> ```
> 
>   private ArrayList<String> results = new ArrayList<String>();
> 
>   private CountDownLatch recieveLatch;
> 
>   public FinalResultDto speechRecognition(MultipartFile file)
>       throws IOException, WebSocketException, InterruptedException {
>     WebSocketFactory factory = new WebSocketFactory();
>     WebSocket ws = factory.createSocket("ws://localhost:2700");
>     ws.addListener(
>         new WebSocketAdapter() {
>           @Override
>           public void onTextMessage(WebSocket websocket, String message) {
>             results.add(message);
>             recieveLatch.countDown();
>           }
>         });
>     ws.connect();
> 
>     DataInputStream dis = new DataInputStream(file.getInputStream());
>     byte[] buf = new byte[8000];
>     while (true) {
>       int nbytes = dis.read(buf);
>       if (nbytes < 0) break;
>       recieveLatch = new CountDownLatch(1);
>       ws.sendBinary(buf);
>       recieveLatch.await();
>     }
>     recieveLatch = new CountDownLatch(1);
>     ws.sendText("{\"eof\" : 1}");
>     recieveLatch.await();
>     ws.disconnect();
>     log.info("results : {}", results);
>     return null;
>   }
> ```
> 
> here is result
> 
> ```
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : "发 [FIL]"
> }, {
>   "partial" : "发 [FIL]"
> }, {
>   "partial" : "发 [FIL]"
> }, {
>   "partial" : "发 [FIL] 哦"
> }, {
>   "result" : [{
>       "conf" : 0.134505,
>       "end" : 5.430000,
>       "start" : 0.000000,
>       "word" : "发"
>     }, {
>       "conf" : 1.000000,
>       "end" : 9.363597,
>       "start" : 5.534881,
>       "word" : "[FIL]"
>     }, {
>       "conf" : 0.928628,
>       "end" : 10.530000,
>       "start" : 9.900000,
>       "word" : "哦"
>     }],
>   "text" : "发 [FIL] 哦"
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : "啊"
> }, {
>   "partial" : "啊"
> }, {
>   "partial" : "啊"
> }, {
>   "result" : [{
>       "conf" : 0.762381,
>       "end" : 13.920000,
>       "start" : 11.040000,
>       "word" : "[FIL]"
>     }],
>   "text" : "[FIL]"
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : "[FIL]"
> }, {
>   "partial" : "[FIL]"
> }, {
>   "result" : [{
>       "conf" : 1.000000,
>       "end" : 16.140000,
>       "start" : 13.920000,
>       "word" : "[FIL]"
>     }],
>   "text" : "[FIL]"
> }, {
>   "partial" : ""
> }, {
>   "partial" : "啊啊"
> }, {
>   "result" : [{
>       "conf" : 0.816291,
>       "end" : 18.480000,
>       "start" : 17.040000,
>       "word" : "[SPK]"
>     }],
>   "text" : "[SPK]"
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : "啊"
> }, {
>   "result" : [{
>       "conf" : 0.776087,
>       "end" : 22.400652,
>       "start" : 18.480000,
>       "word" : "[SPK]"
>     }],
>   "text" : "[SPK]"
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "result" : [{
>       "conf" : 0.984228,
>       "end" : 26.220000,
>       "start" : 22.560000,
>       "word" : "[FIL]"
>     }],
>   "text" : "[FIL]"
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "result" : [{
>       "conf" : 0.678501,
>       "end" : 33.359890,
>       "start" : 28.276166,
>       "word" : "[FIL]"
>     }],
>   "text" : "[FIL]"
> }, {
>   "partial" : ""
> }, {
>   "partial" : "哦"
> }, {
>   "result" : [{
>       "conf" : 0.946397,
>       "end" : 34.379707,
>       "start" : 33.780000,
>       "word" : "哦"
>     }],
>   "text" : "哦"
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "result" : [{
>       "conf" : 0.470927,
>       "end" : 36.240000,
>       "start" : 35.040000,
>       "word" : "[SPK]"
>     }],
>   "text" : "[SPK]"
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "partial" : ""
> }, {
>   "result" : [{
>       "conf" : 0.469083,
>       "end" : 50.190000,
>       "start" : 40.080000,
>       "word" : "呢"
>     }],
>   "text" : "呢"
> }]
> ```

l use `docker run -d -p 2700:2700 alphacep/kaldi-cn:latest` to run server

**Comment by nshmyrev** [comment]
You need to make sure that sample rate you use to init the recognizer matches the audio sample rate. For websocket example you need to resample audio to 8khz.

**Comment by lzwcyd** [comment]
> You need to make sure that sample rate you use to init the recognizer matches the audio sample rate. For websocket example you need to resample audio to 8khz.

Thank you for reminding me, can't 44khz audio be parsed normally?

**Comment by nshmyrev** [comment]
> Thank you for reminding me, can't 44khz audio be parsed normally?

You can process 44khz if you configure recognizer in 44k mode (pass 44100 in constructor for API and send 44100 config to the server).
