### ISSUE TITLE
Hi, I want to get to know about the Vosk's structue, like the acoustic model or decodeing detail, is there and paper for reference?

### ISSUE THREAD

**Issue by skevince** [alphacep/vosk-api#668]

**Comment by nshmyrev** [comment]
Same as #542

**Comment by skevince** [comment]
> Same as #542

Anyway, I'm wondering what's the biggest difference between Vosk and Kaldi?

**Comment by nshmyrev** [comment]
> Anyway, I'm wondering what's the biggest difference between Vosk and Kaldi?

Vosk is built on top of kaldi for plug-and-play speech recognition in many languages.

**Comment by skevince** [comment]
> > Anyway, I'm wondering what's the biggest difference between Vosk and Kaldi?
> 
> Vosk is built on top of Kaldi for plug-and-play speech recognition in many languages.

Cool, so there is no much difference between them. What about chunks stored in the database based on LSH hash value? I believe Kaldi doesn't have this kind of strategy when decoding.
