### ISSUE TITLE
Model loaded in GPU but inference is on CPU

### ISSUE THREAD

**Issue by Kashif-Inam** [alphacep/vosk-api#669]
I needed GPU inference for vosk api so I followed the installation using 
https://github.com/alphacep/vosk-api/blob/master/travis/Dockerfile.manylinux 

I am using gtx 1080ti with cuda 10.1

and after that, I compiled vosk src using Cuda as HAVE_CUDA = 1

after installation of vosk using cuda GpuInit() function works properly the model is loaded into the memory of GPU but the inference is still being done on cpu

I am using vosk aspire model

![Screenshot from 2021-08-20 15-43-13](https://user-images.githubusercontent.com/49473894/130223870-5e3527f8-590a-4ef3-a4e0-d648ae20504d.jpg)

kindly help me out on how to run inference on GPU

**Comment by nshmyrev** [comment]
We added full gpu support just couple days ago. Tracked in #74
