### ISSUE TITLE
Is it possible to make a Ukrainian model

### ISSUE THREAD

**Issue by tarasfrompir** [alphacep/vosk-api#67]

**Comment by nshmyrev** [comment]
Taras, you already asked about it in #56, its perfectly possible, you just need to collect the data and train the Kaldi model according to mini_librispeech recipe. You can ask in our telegram @speech_recognition_ru group, probably someone else will be interested.

I don't think we will have Ukrainian any time soon.

**Comment by nshmyrev** [comment]
Same as #41

**Comment by tarasfrompir** [comment]
Ну мой первый вопрос звучал - как создать модель.
А второй уже - сами можете это сделать? ато я что то туплю если честно....
