### ISSUE TITLE
Can't install VOSK on Nvidia AGX Xavier

### ISSUE THREAD

**Issue by smeza29** [alphacep/vosk-api#671]
Hello! I need some help installing Vosk. When I run **pip3 install vosk** I get the following error:

ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk

Also, when running **pip3 install https://github.com/alphacep/vosk-api/releases/download/0.3.15/vosk-0.3.15-cp37-cp37m-linux_aarch64.whl** I get:

ERROR: vosk-0.3.15-cp37-cp37m-linux_aarch64.whl is not a supported wheel on this platform.

I'm using an Nvidia AGX Xavier with the following specs:

LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	        18.04
Codename:	bionic

Python version: 3.6.9

Pip version: 21.2.4

Any advice?

**Comment by sskorol** [comment]
0.3.15 version is quite outdated. Most likely this platform hasn't been supported yet.
Try the latest one first: https://pypi.org/project/vosk/#history
But honestly, if you use Xavier, you may want to build Vosk with GPU support to reveal its full potential.
You can also check build scripts and docker images [here](https://github.com/sskorol/vosk-api-gpu). I use these Dockerfiles for building GPU-version on Nano/Xavier NX.

**Comment by smeza29** [comment]
I downloaded the latest version as you mentioned and was able to install it, thanks! Also thank you for the information on Vosk with GPU support, will definitely take a look into that.
