### ISSUE TITLE
Can not get lib with Golang; Windows

### ISSUE THREAD

**Issue by elias506** [alphacep/vosk-api#672]
When i try `go get github.com/alphacep/vosk-api/go` library i catch error
```
# github.com/alphacep/vosk-api/go
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lvosk
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
```
OS - Windows

Explain step by step what I should do pls

**Comment by nshmyrev** [comment]
You can download prebuilt libraries and unpack into current folder, then the linker will find them:

https://github.com/alphacep/vosk-api/releases/download/v0.3.30/vosk-win64-0.3.30.zip

As for -ldl, you can probably remove it from flags, it is probably not necessary.

**Comment by elias506** [comment]
But where shoud i unpack these dll files?

**Comment by nshmyrev** [comment]
In the folder where you run your command

**Comment by elias506** [comment]
Nope, linker can not find it(

**Comment by nshmyrev** [comment]
I see the file has the following:

```
// #cgo CPPFLAGS: -I ${SRCDIR}/../src
// #cgo LDFLAGS: -L ${SRCDIR}/../src -lvosk -ldl -lpthread
```

so you might try to put this into something like ../src or fix the flags in the sources with `-L{$SRCDIR}`

**Comment by elias506** [comment]
new error:

..\..\go\src\github.com\alphacep\vosk-api\go\vosk.go:6:11: fatal error: vosk_api.h: No such file or directory
    6 | // #include <vosk_api.h>
      |           ^~~~~~~~~~~~
compilation terminated.

**Comment by elias506** [comment]
the last one remains:

C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
collect2.exe: error: ld returned 1 exit status

"cannot find -lvosk" is gone

Where can i download -ldl to my gcc?

**Comment by elias506** [comment]
sry im stupid, wait for it)

**Comment by elias506** [comment]
Hey, thank you so much! It works! But how can i create `.srt` file with it?

**Comment by nshmyrev** [comment]
You can use this package probably:

https://github.com/asticode/go-astisub

**Comment by elias506** [comment]
I mean, that i get only text without words like this:
```
{
    "text": "bla bla bla"
}
```

So i cant parse it to Srt

**Comment by elias506** [comment]
I mean, that i get only text without words like this:
```
{
    "text": "bla bla bla"
}
```
So i cant parse it to Srt

**Comment by hajsf** [comment]
> Where can i download -ldl to my gcc?

Where did you find it, I've the same issue, missing -ldl

**Comment by nshmyrev** [comment]
@hajsf you don't need -ldl on Windows, you can just remove it from flags

**Comment by hajsf** [comment]
> @hajsf you don't need -ldl on Windows, you can just remove it from flags

Thanks, I got `exit status 0xc0000135`

**Comment by hajsf** [comment]
> @hajsf you don't need -ldl on Windows, you can just remove it from flags

I got `exit status 0xc0000135`

**Comment by nshmyrev** [comment]
Read the full output, probably it can't find the model

**Comment by hajsf** [comment]
> Read the full output

This is every and only thing I got:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/98168280/177028560-abdf900b-0787-4969-894a-f694b6aebcaf.png">

My full code is:
```go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"os"

	vosk "github.com/alphacep/vosk-api/go"
)

func main() {
	fmt.Println("start")
	var filename string
	flag.StringVar(&filename, "f", "", "./audio/data.oga") // file to transcribe
	flag.Parse()
	println("hgi")

	model, err := vosk.NewModel("models/vosk-model-ar-mgb2-0.4.zip")
	if err != nil {
		fmt.Println("Error reading model,", err)
	}

	sampleRate := 16000.0
	rec, err := vosk.NewRecognizer(model, sampleRate)
	if err != nil {
		//	log.Fatal(err)
		fmt.Println("Error creating recognizer,", err)
	}
	rec.SetWords(1)

	file, err := os.Open(filename)
	if err != nil {
		// panic(err)
		fmt.Println("Error could not open file", err)
	}
	defer file.Close()

	reader := bufio.NewReader(file)
	buf := make([]byte, 4096)

	for {
		_, err := reader.Read(buf)
		if err != nil {
			if err != io.EOF {
				//	log.Fatal(err)
				fmt.Println("Error end of file", err)
			}

			break
		}

		if rec.AcceptWaveform(buf) != 0 {
			fmt.Println(string(rec.Result()))
		}
	}

	fmt.Println(string(rec.FinalResult()))
}
```

**Comment by nshmyrev** [comment]
> 	model, err := vosk.NewModel("models/vosk-model-ar-mgb2-0.4.zip")

It should be a folder, not zip

**Comment by hajsf** [comment]
> It should be a folder, not zip

I changed it but still same result my friend, as you see even the first line `fmt.Println("start")` is not executed.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/98168280/177041580-d9246852-f6c0-4938-b665-e11a9b574586.png">

**Comment by nshmyrev** [comment]
135 means that dll not found. Probably you miss some dlls still like winpthread or libstdc++

https://stackoverflow.com/questions/11432940/what-does-error-code-0xc0000135-mean-when-starting-a-net-application

**Comment by hajsf** [comment]
> https://stackoverflow.com/questions/11432940/what-does-error-code-0xc0000135-mean-when-starting-a-net-application

I installed [.NET SDK x64](https://dotnet.microsoft.com/en-us/download) but still getting the same error.

**Comment by nshmyrev** [comment]
The missing files are likely a part of vosk binary release package, not sdk

**Comment by hajsf** [comment]
> The missing files are likely a part of vosk binary release package

But I downloaded the vosk binary from [https://github.com/alphacep/vosk-api/releases/tag/v0.3.42](https://github.com/alphacep/vosk-api/releases/tag/v0.3.42) and added them to the path `vosk-api-master\vosk-api-master\src`

**Comment by nshmyrev** [comment]
@hajsf Dlls have to be in the current folder as well, not just in src. Windows linker searches for DLLs in current folder.

**Comment by hajsf** [comment]
> Windows linker searches for DLLs in current folder
 Thanks, we are improving :)

The resulting text is empty  :(

I'll try with other files, and update you. thanks a lot

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/98168280/177719099-871a570a-c536-4f90-8b01-b2720232b4e3.png">

**Comment by nshmyrev** [comment]
Audio has to be wav pcm 16khz 16bit. You can convert compressed oga to pcm with ffmpeg before recognition. Check python example for details

**Comment by hajsf** [comment]
> Audio has to be wav pcm 16khz 16bit. You can convert compressed oga to pcm with ffmpeg before recognition

Thanks, I downloaded the `ffmpeg` from [here](https://github.com/BtbN/FFmpeg-Builds/releases), and used [ffmpeg-go](https://github.com/u2takey/ffmpeg-go) to convert the audio file to `.wav` which had been done correctly.

But still getting the same result"
```bash
{
  "text" : ""
}
```

Am I missing something, or this means the vosk api could not understand the voice and and convert it to text, the voice is in Arabic.

Below is my full code and app structure:
```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"

	vosk "github.com/alphacep/vosk-api/go"
	ffmpeg "github.com/u2takey/ffmpeg-go"
)

func main() {
	fmt.Println("start")
	var filename string = "./audio/data.oga"
	model, err := vosk.NewModel("models/vosk-model-ar-mgb2-0.4")
	//model, err := vosk.NewModel("vosk-model-small-en-us-0.15")
	if err != nil {
		fmt.Println("Error reading model,", err)
	}
	sampleRate := 16000.0
	rec, err := vosk.NewRecognizer(model, sampleRate)
	if err != nil {
		fmt.Println("Error creating recognizer,", err)
	}
	rec.SetWords(1)

	err = ffmpeg.Input("./audio/data.oga").
		Output("./audio/data.wav", ffmpeg.KwArgs{"c:v": "libx265"}).
		OverWriteOutput().ErrorToStdOut().Run()
	if err != nil {
		fmt.Println("Failed to convert audio file to wav:", err)
	}

	fmt.Println("filename is:", "./audio/data.wav")
	audio, err := os.Open("./audio/data.wav") 
	if err != nil {
		fmt.Println("Error could not open file", err)
	}
	defer audio.Close()

	reader := bufio.NewReader(audio)
	buf := make([]byte, 4096)

	for {
		_, err := reader.Read(buf)
		if err != nil {
			if err != io.EOF {
				fmt.Println("Error end of file", err)
			}

			break
		}

		if rec.AcceptWaveform(buf) != 0 {
			fmt.Println(string(rec.Result()))
		}
	}

	fmt.Println(string(rec.FinalResult()))
}
```

![image](https://user-images.githubusercontent.com/98168280/177728511-cffcc1b9-9180-4f22-a0b7-0feff87bd047.png)

The output I got is:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/98168280/177730340-fc0d2e57-bd39-4bbd-b23c-59f1e3faf0fb.png">

**Comment by nshmyrev** [comment]
Since you convered to 48khz, change 16000 to 48000 in Recognizer constructor

**Comment by hajsf** [comment]
> change 16000 to 48000 in Recognizer constructor

Worked greatly. Thanks a lot.

Now, it looks there is an issue to display Arabic, will look into it.

My full working code now is:
```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"

	vosk "github.com/alphacep/vosk-api/go"
	ffmpeg "github.com/u2takey/ffmpeg-go"
)

func main() {

	//model, err := vosk.NewModel("models/vosk-model-en-us-0.22-lgraph"// vosk-model-small-en-us-0.15 does not contain model files
	// "text" : "hi yet this is just at this"
	//model, err := vosk.NewModel("models/vosk-model-en-us-0.22")
	// "text" : "hi there this is just at this"
	model, err := vosk.NewModel("models/vosk-model-ar-mgb2-0.4")

	if err != nil {
		fmt.Println("Error reading model,", err)
	}
	sampleRate := 48000.0
	rec, err := vosk.NewRecognizer(model, sampleRate)
	if err != nil {
		fmt.Println("Error creating recognizer,", err)
	}
	rec.SetWords(1)
	fmt.Println("here")
	err = ffmpeg.Input("./audio/data.oga").
		Output("./audio/data.wav", ffmpeg.KwArgs{"c:v": "libx265"}).
		OverWriteOutput().ErrorToStdOut().Run()
	if err != nil {
		fmt.Println("Failed to convert audio file to wav:", err)
	}
	fmt.Println("and here")
	fmt.Println("filename is:", "./audio/data.wav")
	audio, err := os.Open("./audio/data.wav")
	if err != nil {
		fmt.Println("Error could not open file", err)
	}
	defer audio.Close()

	reader := bufio.NewReader(audio)
	buf := make([]byte, 4096)

	for {
		_, err := reader.Read(buf)
		if err != nil {
			if err != io.EOF {
				fmt.Println("Error end of file", err)
			}

			break
		}

		if rec.AcceptWaveform(buf) != 0 {
			// fmt.Println(string(rec.Result()))
		}
	}

	fmt.Println("full text:", string(rec.FinalResult()))
      
        finalJSON := string(rec.FinalResult())
	data := SpokenText{}

	err = json.Unmarshal([]byte(finalJSON), &data)
	if err != nil {
		fmt.Println(err.Error())
	}

	fmt.Printf("Spoken text: %s", data.Text)
}

type RecognizerResult struct {
	conf, end, start float64
	word             string
}
type SpokenText struct {
	Result []RecognizerResult `json:"result"`
	Text   string             `json:"text"`
}
``` 

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/98168280/177751055-20035e84-3b7a-4d90-a627-df787faf6280.png">
