### ISSUE TITLE
model.cc:326:53: error: 'OUTPUT' is not a member of 'fst::ProjectType'

### ISSUE THREAD

**Issue by hbanpi** [alphacep/vosk-api#675]
When I build it with comand
`KALDI_MKL=0 KALDI_CUDA=on KALDI_ROOT=/my/data/projects/kaldi make`
I got an error
`root@my-desktop:/my/data/projects/kaldi/vosk-api/src# KALDI_MKL=0 KALDI_CUDA=on KALDI_ROOT=/my/data/projects/kaldi make`
`g++ -g -O3 -std=c++17 -fPIC -DFST_NO_DYNAMIC_LINKING -I. -I/my/data/projects/kaldi/src -I/my/data/projects/kaldi/tools/openfst/include`
`-I/my/data/projects/kaldi/tools/OpenBLAS/install/include -c -o model.o model.cc`
`model.cc: In member function 'void Model::ReadDataFiles()':`
`model.cc:326:53: error: 'OUTPUT' is not a member of 'fst::ProjectType'`
`         fst::Project(std_lm_fst_, fst::ProjectType::OUTPUT);`
`                                                     ^~~~~~`
`Makefile:80: recipe for target 'model.o' failed`
`make: *** [model.o] Error 1`

Please help me to fix it.
Thanks.

**Comment by nshmyrev** [comment]
You need our openfst version, see the docker file for details

**Comment by hbanpi** [comment]
> You need our openfst version, see the docker file for details

Thanks for your replay. But I can not find the docker file under https://github.com/alphacep/vosk-api
Would you please give me an url of the docker file.
Thanks.

**Comment by nshmyrev** [comment]
> Would you please give me an url of the docker file.

https://github.com/alphacep/vosk-api/blob/master/travis/Dockerfile.manylinux

**Comment by hbanpi** [comment]
@nshmyrev 
I got it.
Thank you very much.
