### ISSUE TITLE
Re-building the Model in vosk-android-demo

### ISSUE THREAD

**Issue by CommuniG8** [alphacep/vosk-api#676]
I'm using the Model from vosk-android-demo to test in a new Android App that is memory constrained on an Android device.
The App only needs to listen to a small number of simple commands and so does not need the full grammar and vocabulary used in vosk-android-demo.
On the Alphacep site in Adaptations that is a procedure for re-building the Grammar (Gr.fst) but this depends on the Model's words.txt file which is only created on a full Model rebuild.
I read about https://alphacephei.com/kaldi/en-android-compile-graph.tar.gz for rebuilding Models but this does not seem to exists any more.
Can you help me in pointing me to the correct source of information to perform a rebuild?

**Comment by nshmyrev** [comment]
Same as #198 and #165

As mentioned, you have to mail contact@alphacephei.com

**Comment by CommuniG8** [comment]
Thanks you I'll do that.
