### ISSUE TITLE
Models error Fatal error

### ISSUE THREAD

**Issue by stodgysam** [alphacep/vosk-api#677]
I am working with vsok in linux. I cannot download the small and medium models. The links seem to not be working. I am also having trouble with the larger model. I ran it I am getting a fatal error, below:

LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from model/rescore/G.carpa
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

**Comment by nshmyrev** [comment]
I have checked, small models download just fine.

> I ran it I am getting a fatal error, below:

You do not have enough memory to run this.

**Comment by stodgysam** [comment]
> I have checked, small models download just fine.
> 
> 
> 
> > I ran it I am getting a fatal error, below:
> 
> 
> 
> You do not have enough memory to run this.
> 
> 
What is the memory requirement?

**Comment by nshmyrev** [comment]
> What is the memory requirement?

8Gb

**Comment by stodgysam** [comment]
My raspberry pi 4 has 8gb of ram. I did get the English other model to work. I am still unable to download the vosk-model-en-us-0.20 file from alphacephei.com on multiple devices. Is there another location I can download from?

**Comment by nshmyrev** [comment]
vosk-model-en-us-0.20 is not suitable for RPi4 anyway, it is a model for servers.

**Comment by stodgysam** [comment]
I see. Thank you for your assistance.
