### ISSUE TITLE
latest release incomplete

### ISSUE THREAD

**Issue by kakulukia** [alphacep/vosk-api#680]
i just tried to install vosk and although visible at PYPI the new version cant be installed

    pip install vosk==0.3.31
    ERROR: Could not find a version that satisfies the requirement vosk==0.3.31 (from versions: 0.3.15, 0.3.21, 0.3.29, 0.3.30) 
    ERROR: No matching distribution found for vosk==0.3.31

`pip install vosk` will install 0.3.30 instead
`poetry add vosk` will see version 0.3.31, but also fail to install it

**Comment by sadrasabouri** [comment]
I just can't reproduce your mentioned issue.
I tried:
```
$ pip install vosk==0.3.31
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Collecting vosk==0.3.31
  Downloading vosk-0.3.31-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (7.0 MB)
     |████████████████████████████████| 7.0 MB 336 kB/s 
Requirement already satisfied: cffi>=1.0 in ./.local/lib/python3.8/site-packages (from vosk==0.3.31) (1.14.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages/pycparser-2.20-py3.8.egg (from cffi>=1.0->vosk==0.3.31) (2.20)
Installing collected packages: vosk
  Attempting uninstall: vosk
    Found existing installation: vosk 0.3.22
    Uninstalling vosk-0.3.22:
      Successfully uninstalled vosk-0.3.22
Successfully installed vosk-0.3.31
```
and all the things go well.
Can you provide us with more details?

**Comment by kakulukia** [comment]
hmmm .. the issue still exists

    pip install vosk==0.3.31
    ERROR: Could not find a version that satisfies the requirement vosk==0.3.31 (from versions: 0.3.15, 0.3.21, 0.3.29, 0.3.30)
    ERROR: No matching distribution found for vosk==0.3.31
    pip --version
    pip 21.2.4 from /Users/andy/projects/voiceRecognitionTest/.direnv/python-3.9.4/lib/python3.9/site-packages/pip (python 3.9)

As you can see on that list in the error message even more versions are missing and i cant install 0.3.22 either.
pip and python versions are above. Im on OSX. What other details might be helpful?

Looking at pypi i can see all the releases myself, but somehow at least my pip cant. Haven't seen that with any other packe yet. :/

**Comment by kakulukia** [comment]
Something was done differently when releasing 0.3.30 and 0.3.31 .. that should be a good clue. Who did it and how?

**Comment by sadrasabouri** [comment]
It maybe a cache problem.
Let me reproduce this bug and I'll update this thread soon.
If you are in a hurry you can install from source, like:
```
git clone https://github.com/alphacep/vosk-api.git
cd vosk-api/python
sudo python setup.py install
```

**Comment by sadrasabouri** [comment]
Also you can take a look at these same issue:
+ [Why is pip installing an old version of my package?](https://stackoverflow.com/questions/14617136/why-is-pip-installing-an-old-version-of-my-package)
+ [pip fails to find package even though it is available on PyPI](https://github.com/pypa/pip/issues/4888)

**Comment by aeirya** [comment]
I'm also having the same problem (osx). 

I think the problem may be due to the package not having been released for mac yet.
Compare [v0.3.30](https://github.com/alphacep/vosk-api/releases/tag/v0.3.30) and [v0.3.31](https://github.com/alphacep/vosk-api/releases/tag/v0.3.31).  You'd see ``` vosk-0.3.31-py3-none-macosx_10_6_x86_64.whl ```
and ``` vosk-osx-0.3.31.zip ``` releases are missing.

The funny thing is running ```code  yolk -V vosk``` on my mac only returns ``` vosk 0.3.31 ```  which actually doesn't support what I just said.

**Comment by aeirya** [comment]
@kakulukia 
> although visible at PYPI the new version cant be installed

I just checked [PYPI](https://pypi.org/project/vosk/#files) and saw linux and windows releases but not for mac os.

I guess we should wait =)

**Comment by kakulukia** [comment]
My bet is, that there is no automatic build tool that always uploads all platform builds and somebody is doing that by hand .. with a smaller focus on OSX :)

I just did install the latest version on Ubuntu and Windows - this worked just fine. But whoever feels responsible for that please make the releases more consisten and probalby automate it to not leave some users like me behind having to work on older versions.

Luckily its that that big of a gap as 0.3.21 -> 0.3.29

**Comment by nshmyrev** [comment]
There is osx on pypi now
