### ISSUE TITLE
kaldi model export files compatibility with vosk API

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#682]
I have trained kaldi engine. I got all files exported successfully.  Now I am making it useable with vosk API.
The missing files I am facing is 
`model.conf `
and 
`G.carpa`

I already have `G.arpa`.
Can you guide me how to export them? Infact I have used default values. I have not put any customized` model.conf`. 
I found script for` G.carpa` but failed to manage export from `lm.arpa` file. Also, for` model.conf` I could not find any routine. Your help is highly appreciated.

**Comment by Tortoise17** [comment]
I am retraining engine with the already set `model.conf` now. but` G.carpa`?

**Comment by nshmyrev** [comment]
rescore folder with G.fst and G.carpa is optional, you can delete it if needed.

To create G.carpa from big language model you can use the following kaldi script:

utils/build_const_arpa_lm.sh lm.gz data/lang_test data/lang_test_rescore

**Comment by Tortoise17** [comment]
@nshmyrev  thank you. and `model.conf` must be the self created file before training? or if not set for training, can get the default one?

**Comment by nshmyrev** [comment]
> or if not set for training, can get the default one?

You can get default one in any model

**Comment by Tortoise17** [comment]
@nshmyrev 
can you guide me what dimensions I am missing while training or providing here?
```

LOG (VoskAPI:ReadDataFiles():vosk/model.cc:194) Decoding params beam=16 max-active=7000 lattice-beam=10
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.072473 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:246) Loading HCLG from model_new/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:265) Loading words from model_new/graph/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:273) Loading winfo model_new/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:281) Loading CARPA model from model_new/rescore/G.carpa
WARNING (VoskAPI:Check():nnet-nnet.cc:789) Node tdnn6.relu is never used to compute any output.
WARNING (VoskAPI:Check():nnet-nnet.cc:789) Node tdnn6.batchnorm is never used to compute any output.
WARNING (VoskAPI:Check():nnet-nnet.cc:789) Node output.affine is never used to compute any output.
WARNING (VoskAPI:Check():nnet-nnet.cc:789) Node output.log-softmax is never used to compute any output.
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 4 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 4 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 0 components, removed 4
ERROR (VoskAPI:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:46) Input feature dimension mismatch: got 30 but network expects 40
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError




Aborted (core dumped)
```

**Comment by Tortoise17** [comment]
@nshmyrev I tried default and trained model. It didn't work. Still dimensions issue.

**Comment by Tortoise17** [comment]
Is there any way where I can find from the model to set the model.conf after training.
