### ISSUE TITLE
Effects of allow-upsample=true option

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#689]
My testset samplerate is 8000Khz
My asr model input default samplerate is 1600Khz
I set “— allow-upsample=true” in mfcc.conf，it doesn‘t work.

**Comment by nshmyrev** [comment]
What do you mean by "doesn't work" please?

**Comment by zyb8543d** [comment]
@nshmyrev It  means  that use  a asr model default samplerate is 1600Khz to recognize  a 8000Khz speech without "-- allow-upsample=true" and with "-- allow-upsample=true" both have same recognizition result.

**Comment by nshmyrev** [comment]
> both have same recognizition result

Probably you do not specify the sample rate in recognizer constructor properly. If you recognize 8000 you need to specify 8000 in recognizer constructor. 

Without allow-upsample it will then cause an error saying that model rate doesn't match audio rate. With upsample it will work with probably low accuracy.

**Comment by zyb8543d** [comment]
@nshmyrev  I use a asr model default samplerate is 1600Khz to recognize a 8000Khz speech with "-- allow-upsample=true” and  specify 16000 in recognizer constructor，but the recognizition results are all wrong.

**Comment by nshmyrev** [comment]
> and specify 16000 in recognizer constructor

In recognizer constructor you specify the audio rate, not model rate. You need to specify 8000 there.

**Comment by v-yunbin** [comment]
“—allow-upsample=true” means “8000KHZ->16000KHZ”, so I think it should specify 16000KZ
.

**Comment by v-yunbin** [comment]
> > and specify 16000 in recognizer constructor
> 
> In recognizer constructor you specify the audio rate, not model rate. You need to specify 8000 there.

“—allow-upsample=true” means “8000KHZ->16000KHZ”, so I think it should specify 16000KZ
.

**Comment by zyb8543d** [comment]
> > and specify 16000 in recognizer constructor
> 
> In recognizer constructor you specify the audio rate, not model rate. You need to specify 8000 there.

thanks，I will try it.

**Comment by v-yunbin** [comment]
> > > and specify 16000 in recognizer constructor
> > 
> > 
> > In recognizer constructor you specify the audio rate, not model rate. You need to specify 8000 there.
> 
> thanks，I will try it.

It work，for some audio，most recognizition result has been lost，for other audios ，it‘s normal.

**Comment by zyb8543d** [comment]
@nshmyrev It work，but most recognizition result has been lost.

**Comment by nshmyrev** [comment]
> @nshmyrev It work，but most recognizition result has been lost.

It is kind of expected. If your 16000 model didn't see 8000 files during training it will not recognize them well.

**Comment by zyb8543d** [comment]
@nshmyrev so I should train a 16000khz model with 16hkz data （ part of data from 8khz and other from 16khz），upsample 8khz data can be recognized well？

**Comment by nshmyrev** [comment]
Yes, it is the modern approach to train 16000 model with a mix of 16000 speech and upsampled 8000 speech.

**Comment by zyb8543d** [comment]
thank you very much，I close the issue
