### ISSUE TITLE
如何在识别器中指定识别列表中的词语

### ISSUE THREAD

**Issue by Sooloom** [alphacep/vosk-api#690]
我看了下python中的示例

rec = KaldiRecognizer(model, wf.getframerate(), '["oh one two three four five six seven eight nine zero", "[unk]"]')

请问这个在c# 中如何表达？而且用的是Kaldi识别器，C# 中可以调用吗？

另外， '["oh one two three four five six seven eight nine zero", "[unk]"]' 这段字符串是什么意思？后面跟着的 [unk] 代表什么定义？有没有具体文档可以参考啊？

**Comment by nshmyrev** [comment]
> 请问这个在c# 中如何表达?

同样的方法 

    auto rec = new VoskRecognizer(model, rate, "[\"oh one two three four five six seven eight nine zero\", \"[unk]\"]")

https://github.com/alphacep/vosk-api/blob/master/csharp/nuget/src/VoskRecognizer.cs#L38

> 而且用的是Kaldi识别器，C# 中可以调用吗？

是的

> 另外， '["oh one two three four five six seven eight nine zero", "[unk]"]' 这段字符串是什么意思？

它是您希望在 json 格式的音频中听到的句子列表

> 后面跟着的 [unk] 代表什么定义？有没有具体文档可以参考啊？

[unk] 是一个发音不明的词

**Comment by Sooloom** [comment]
谢谢，另外
oh one two three four five six seven eight nine zero
这些词语需要添加在model里面的words.txt文件中吗？如果我需要添加新词呢？

**Comment by nshmyrev** [comment]
您只能使用words.txt 中的单词，还不能添加其他单词。

目的是调整单词概率，而不是添加新单词

**Comment by Sooloom** [comment]
已经正常识别了，谢谢！
2021/9/17 13:38:48		{
  "result" : [{
      "conf" : 0.757231,
      "end" : 13.530000,
      "start" : 8.880000,
      "word" : "分不清"
    }],
  "text" : "分不清"
}
不过，识别速度好像比较慢，从mic说话到result，需要用时1秒以上，能提高识别速度吗？

**Comment by nshmyrev** [comment]
这与识别速度无关。 这是关于延迟。 我们需要训练下一代中国模型来解决这个问题。 您可以检查英文模型进行比较。 不过，中文培训有确切的截止日期。

**Comment by nshmyrev** [comment]
如果您还有其他问题，请重新打开
