### ISSUE TITLE
How add words to big Russian model and use this model then?

### ISSUE THREAD

**Issue by gubri** [alphacep/vosk-api#694]
--install kaldi, Phonetisaurus etc.
--change path.sh to my kaldi root
--add words to extra.txt
--run compile.sh
and all OK.

How i can assembly bigrumodel from it to use it?

**Comment by nshmyrev** [comment]
I suppose tutorial covers that in "outputs" section:

https://alphacephei.com/vosk/lm#outputs

**Comment by gubri** [comment]
For large model pick the following parts:

exp/chain/tdnn/graph === **this directory updated after .sh but is empty**
data/lang_test_rescore/G.fst and data/lang_test_rescore/G.carpa into rescore folder  ==== **I don't have this files. Why they don't create?**

**Comment by nshmyrev** [comment]
There were previous errors, you can check them in the script output

**Comment by gubri** [comment]
Oh, yes
i don't have these files/ Can i solve this problem?

steps/nnet2/check_ivectors_compatible.sh: WARNING: One of the directories do not contain iVector ID.
steps/nnet2/check_ivectors_compatible.sh: WARNING: That means it's you who's reponsible for keeping 
steps/nnet2/check_ivectors_compatible.sh: WARNING: the directories compatible

Please check your command
steps/lmrescore_const_arpa.sh data/lang_test data/lang_test_rescore data/test_sova_devices exp/chain/tdnn/decode_test_sova_devices exp/chain/tdnn/decode_test_sova_devices_rescore
steps/lmrescore_const_arpa.sh: Missing file data/lang_test/G.fst
rnnlm/lmrescore_pruned.sh --lattice-prune-beam 4 --max-ngram-order 4 data/lang_test exp/rnnlm_out data/test_sova_devices exp/chain/tdnn/decode_test_sova_devices exp/chain/tdnn/decode_test_sova_devices_rnnlm
rnnlm/lmrescore_pruned.sh: file data/lang_test/G.fst not found; looking for data/lang_test/G.carpa
rnnlm/lmrescore_pruned.sh: Missing file data/lang_test/G.carpa

**Comment by gubri** [comment]
Also i have problem with 
**line 18: ngram: command not found**

i install ngram and openfst but vosk don't see it

**Comment by nshmyrev** [comment]
It is a good time to learn about PATH environment variable.

**Comment by gubri** [comment]
Я установил kaldi. в path.sh прописал пути к нему + ngram есть(путь тоже прописан)
но ngram rкоманду не видит
ngram-count переделав в ngramcount видит, но флаги не нравятся

Пути тлько в path.sh менять?

**Comment by gubri** [comment]
> It is a good time to learn about PATH environment variable.

We have Path.sh
in It we have kaldi root path/ But where SRILM and Phonetisaurus root path?
Because i have installed SRILM (which have ngram lib etc.) but vosk script don't see it(((

**Comment by gubri** [comment]
I solved my problem
install kaldi,srilm,photeticus   

For path.sh  
export Path = {PATH TO ngram (like  /SRILM/bin/i686-m64) }
