### ISSUE TITLE
Vosk installation in Windows for working with cpp

### ISSUE THREAD

**Issue by Krishnayan-Bhatt** [alphacep/vosk-api#696]
Hi, I am new in API building. I need to use Vosk with cpp code for later use in project in Windows 10. But unable to install Vosk. Is there anyone who has already done it or is there any vosk.exe type of thing which I can use readily in windows for building another API. It will be helpful if step by step procedure is provided. Any type of help will be appreciated.

**Comment by nshmyrev** [comment]
You can download prebuilt binary here:

https://github.com/alphacep/vosk-api/releases/download/v0.3.31/vosk-win64-0.3.31.zip
