### ISSUE TITLE
Streaming to server - wav header?

### ISSUE THREAD

**Issue by ab36245** [alphacep/vosk-api#700]
I'm new to this so apologies if this has been asked before.

I want to be able to stream simple pcm data from a client to a server and generate text responses. The vosk-api and vosk-server examples are pretty good, and I'm starting to get how this works.

A simple question though is regarding wav formatting. The examples, both vosk-api and vosk-server, use wav files. If I am streaming data from a client I will not be generating a wav header (or do I need to?) so I'm not sure how I can get this to work.

Any suggestions/explanations appreciated. If there's documentation addressing this feel free to tell me to RTFM

**Comment by nshmyrev** [comment]
You don't need the header, you just send data to the server. Make sure the sample rate matches the server configuration.

**Comment by ab36245** [comment]
Thank you. My problem was exactly as you say, that I hadn't carefully checked the sampling rates. It all works fine now.

Excellent piece of software btw!
