### ISSUE TITLE
Re-scoring fails and shows error!

### ISSUE THREAD

**Issue by jubaer145** [alphacep/vosk-api#702]
For re-scoring, I've kept my **G.carpa** and **G.fst** file in the **model/rescore** folder. Then I wanted to test the **python/test/transcribe_scp.py** for transcribing my file. But I get the following error: 

`WARNING (VoskAPI:AlignLattice():word-align-lattice.cc:310) Trying to word-align empty lattice.
ASSERTION_FAILED (VoskAPI:CompactLatticeStateTimes():lattice-functions.cc:114) Assertion failed: (lat.Start() == 0)
Aborted (core dumped)`

Can you please tell me what the problem is? I can not figure it out...

**Comment by LuggerMan** [comment]
@jubaer145 provide your model and **all** the mentioned files

**Comment by jubaer145** [comment]
> @jubaer145 provide your model and **all** the mentioned files
How can I share the files here? They are  quite big in size. The model is for Bengali language. Can you please share any insight?

**Comment by nshmyrev** [comment]
This should be fixed in ad5bec114da79911b3625a281b5abd5902efca9f
