### ISSUE TITLE
Grammar don't work

### ISSUE THREAD

**Issue by ydslash** [alphacep/vosk-api#705]
publc VoskRecognizer(Model model, float sample_rate, string grammar)

i want to add word into model dynamic, using grammar like '["命令"]'

but it totally dont work, no result comes out .

**Comment by nshmyrev** [comment]
What do you see in the script output?

**Comment by ydslash** [comment]
publc VoskRecognizer(Model model, float sample_rate)

works goods. 

publc VoskRecognizer(Model model, float sample_rate, string grammar)

PartialResult ="" FinalResult=""

**Comment by nshmyrev** [comment]
You are welcome to share the audio file an the script to reproduce your problem.

**Comment by ydslash** [comment]
is there any doc about SpkModel or grammar

**Comment by ydslash** [comment]
not any wav works when i  use grammar. it total no response

**Comment by ydslash** [comment]
i use  vosk-model-small-cn-0.3  in c#

**Comment by ydslash** [comment]
i want to add word into model dynamic, so it can recognize some words not so popular

**Comment by ydslash** [comment]
Example : new Recognizer(model, 16000, "household")
Exception : WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:61) Expecting array of strings, got: 'household'

someone meet problem  ,i  try it ,"household" , it throw exception

but when i use '["命另"]'  no exception

**Comment by nshmyrev** [comment]
Share particular script and wav file which doesn't work

**Comment by nahakiole** [comment]
I was able to get it working like this:

```java
Recognizer rec = new Recognizer(model, 16000.0f, "[\"hugo\",\"hallo\",\"stop\", \"tonne\", \"mülltonne\",  \"[unk]\"]");
```

But I get a lot of false positives, as it tries to match words to it even when I say other words. Is there no documentation for this function?

**Comment by nshmyrev** [comment]
@nahakiole you have to open a separate issue.

@ydslash let us know if you can provide requested information
