### ISSUE TITLE
use test_ffmpeg with srt output?

### ISSUE THREAD

**Issue by tomasmueller** [alphacep/vosk-api#706]
test_ffmpeg works very gold but only with json output. test_srt works but i have to convert the file to wav first. For some reasons piping the file to WAV with ffmpeg doesnt work. Can i use test_ffmpeg and with srt output?

**Comment by nshmyrev** [comment]
Are you trying server client code?

**Comment by tomasmueller** [comment]
i dont know what you mean.

i installed vosk and srt using pip and downloaded the model for my language.

**Comment by nshmyrev** [comment]
> test_srt works but i have to convert the file to wav first.

test_srt also uses ffmpeg and can process any audio/video file, does it work for you?

**Comment by tomasmueller** [comment]
thats strange, now it works. as i tried this first there was an error. perhaps because i used the small model at the first time?
