### ISSUE TITLE
Output from trained model

### ISSUE THREAD

**Issue by gubri** [alphacep/vosk-api#709]
Hello again)))
I trained model (...ru-compile)/ Don't have in process any errors;'

Firstly
I get graph directory, but don't get lgraph (for small model)
If i only copy  .fst file to model i have error:
_kaldi:nnet3:DecodableAmnetLoopedOnline ...._

Also In big model it doesnt create G.carpa (when i trained model ALL OK)
and when i run STT it crashed with new big model (I have enough memory and little file)

**thank you in advance**

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/694
