### ISSUE TITLE
Specify custom Android logger

### ISSUE THREAD

**Issue by DanielNovak** [alphacep/vosk-api#71]
Is there a way how to specify a custom logger for Android API? I noticed some logs in our app with "KaldiDemo" tag. It seems that the android default logger is hardwired here: https://github.com/alphacep/vosk-api/blob/80e60b9118e16385390a19e56d1b78ed34136d3a/src/model.cc#L50 

It would be great if there was a setter method for custom logger in Model.java (it can be just some simple listener with string method).

**Comment by nshmyrev** [comment]
Thats on purpose to increase library awareness ;)

One day we might try to fix that, I'd be happy to consider a pull request.

**Comment by DanielNovak** [comment]
:-D Okay, I will maybe try to do a PR later.

**Comment by nshmyrev** [comment]
Ok, I implemented the method Vosk.SetLogLevel to disable the log, so you can disable information messages. Messages are not very important anyway.

Having custom java handler called from C code would be a bit problematic, I would avoid that, but I think the implemented API should be ok.
