### ISSUE TITLE
VoskAPI:LatticeWordAligner() Lattice has input epsilons and/or is not input-deterministic

### ISSUE THREAD

**Issue by bartolootrit** [alphacep/vosk-api#713]
Hello. 
Vosk Python 0.3.31 with vosk-model-small-ru-0.15

`FinalResult()` produces a warning: `(VoskAPI:LatticeWordAligner():word-align-lattice.cc:263) [Lattice has input epsilons and/or is not input-deterministic (in Mohri sense)]-- i.e. lattice is not deterministic.  Word-alignment may be slow and-or blow up in memory.`

According to [Don't align lattice twice](https://github.com/alphacep/vosk-api/commit/558b4dd69e75e7f5d0644c5221302b6035cbfe99) commint it's fixed in v0.3.31, but it persists.

This [notebook](https://colab.research.google.com/drive/1ED_x7Uj7UuukYYKEYU3ZKKVtvBCH3Sa8?usp=sharing) helps to reproduce the issue.

**Comment by nshmyrev** [comment]
Should be fixed now, will be part of the next release.

**Comment by nshmyrev** [comment]
Thank you!
