### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by russele7** [alphacep/vosk-api#715]
@nshmyrev 
Dear Nickolay,
I am trying your examples test_ffmpeg.py / test_simple.py with big Russian model < vosk-model-ru-0.10.zip > and I got error < Segmentation fault (core dumped)>
Report with valgrind is in attachment.
I am using:
• Ubuntu 20.04.1 LTS
• Python 3.8.10
• vosk==0.3.31
• CPU - Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
P.S. small Russian model < vosk-model-small-ru-0.15> working succesfully without error.
Could you please help and advice with resolving this issue.
[valgrind.txt](https://github.com/alphacep/vosk-api/files/7327581/valgrind.txt)
Thank you in advance!

**Comment by nshmyrev** [comment]
How much memory do you have? You probably don't have enough. You need 8Gb.

**Comment by russele7** [comment]
Nickolay, thank’s a lot,
Problem is solved. Actually I have 16 Gb memory.  But, as found out,  we need 8 Gb of  FREE memory. Printscreen is in attachment – memory condition during the program works. Hope it will help other users.
![Снимок](https://user-images.githubusercontent.com/64725397/136918284-1a687e0d-98dd-4ed1-b794-e0b6c40bae79.JPG)

**Comment by nshmyrev** [comment]
Same as #677

**Comment by japita-se** [comment]
memory is not an issue to me
