### ISSUE TITLE
Lost recognition results when applying  vosk on debian operating system

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#721]
base info:
```
vosk version: vosk-api-0.3.2.1
operating system: Debian9.11 x86_64
python version: 3.7
pip version: 20.0.2
```
I test same wav file , when I decode on centos 7.9, I get "今天天气很不错呢我们去哪里玩你有什么计划吗"
but  I decode on debian 7.9, I get  "今天天气错呢我们哪玩有什么划吗"

**Comment by nshmyrev** [comment]
Dear, I'm sorry, maybe something with the model you trained, hard to say. Can you reproduce this with pretrained models?

**Comment by zyb8543d** [comment]
@nshmyrev I am very sorry，the disambig_tid.int file was deleted due to a mistake by the packaging engineer，sorry for wasting your time.

**Comment by nshmyrev** [comment]
@v-yunbin you are welcome, hopefully the rest goes great!
