### ISSUE TITLE
How to train good model with proper rejection

### ISSUE THREAD

**Issue by bbpp0317** [alphacep/vosk-api#722]
we use vosk-api examples vosk-api/python/example/test_words.py ,using model vosk-model-small-en-us-0.15.zip , withi simple grammar such as
  how are you | thank you | good bye | <UNK> , If not the phrases in the list, we want to get <UNK> --- the performance is good. 

  However, we want to use our own data and train in the way of mini_librispeech, but we can't get a good reject into <UNK>, could you tell me how 
  you train your model  the recipe and data preparation/transcription that might contribute to this difference? 
  
  we have optional_silence  as  SIL and SPN
  and lexcicon <UNK>  PRN
  
  We have no idea yet, and we downloaded some other VOSK models, some have good rejection power, and some don't . 
  
 
  The following is the help I want,
  1.how to train a model and use test_words.py can recognize [unk]，Can you provide your training script. We'll adjust it to the format you use as needed.
  2.Is [unk] obtained through the training language model, or does the training data  need to have nonsense speech and  <unk> transcripts
  3.If we can't train the model, we can adapt the existing model. -- We also want to adapt the model vosk-model-small-en-us-0.15.zip you provide. But we need the tree file.

**Comment by nshmyrev** [comment]
Sorry, @bbpp0317 as I said you need to ask somewhere else. Kaldi-help group probably.
