### ISSUE TITLE
Vosk NPM throws error on RPI4

### ISSUE THREAD

**Issue by LilahCodes** [alphacep/vosk-api#724]
I found a similar issue but no solution was provided, here's the error i'm getting;
`
Error: Dynamic Linking Error: /home/pi/Desktop/Code/Discord/CD-Bot/node_modules/vosk/lib/linux-x86_64/libvosk.so: wrong ELF class: ELFCLASS64
`

Im using the [vosk-model-small-en-us-0.15](http://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip) model on raspberry pi 4.

Any ideas?
Thanks in advance

**Comment by nshmyrev** [comment]
Same as #620, we do not support node on rpi4 yet. You can download prebuilt binary from releases yourself and replace the libvosk.so in the node package, then it will work.
