### ISSUE TITLE
Create a simple command line tool for transcription

### ISSUE THREAD

**Issue by nshmyrev** [alphacep/vosk-api#727]
So user can transcribe audio files like this:

     vosk-transcribe file.mp3 file.txt

**Comment by solyarisoftware** [comment]
Hi Nicolay!

bad news: I'm currently busy at work and I can't take the task.

Months ago I tried to do something like that in voskjs, my vosk wrapper, see:
https://github.com/solyarisoftware/voskjs#command-line-tools

tips:
- take in input the model (of course)
- as you wrote it could be useful to convert audio codec and maybe comment out the best /needed practice (ehi mp3 is bad, please use a 16 bit 16kx mono, etc.)
 - it would be interesting to optionally print out a verbose report with meaningful info like: 
   - latency
   - accuracy (if the ground truth target text is specified along with the audio  `vosk-transcribe my_name_is_giorgio.mp3 --model xxxx --text "my name is giorgio"` ) 
   - rtf (real-time-ratio)
   - take in input the optional vosk grammar (--grammar "one,two,three,four,..."` ) 

- silent mode: just print out the raw transcript text    
- verbose mode: print to stdout all time/partial results 
   
   
```
voskjs --audio=audio/sentencesWithSilences.wav --model=models/vosk-model-small-en-us-0.15 --tableevents

voskjs is a CLI utility to test Vosk-api features
package @solyarisoftware/voskjs version 1.2.7, Vosk-api version 0.3.30

Statistics:

model directory      : models/vosk-model-small-en-us-0.15
speech file name     : audio/sentencesWithSilences.wav
grammar              : not specified. Default: NO
sample rate          : not specified. Default: 16000
max alternatives     : undefined
text only / JSON     : JSON
Vosk debug level     : -1

load model latency   : 2001ms
transcript latency   : 1707ms
transcript text      : one two three four five six seven eight nine zero one two three stop 

Events table:

| time   | event        | text                                     |
| ------ | ------------ | ---------------------------------------- |
|     66 | partial      | 
|    489 | partial      | one
|    538 | partial      | one two
|    592 | partial      | one two three
|    635 | endOfSpeech  | one two three
|    668 | partial      | 
|    847 | partial      | for
|    882 | partial      | four five six
|    977 | partial      | four five six seven
|   1099 | partial      | four five six seven eight
|   1169 | endOfSpeech  | four five six seven eight
|   1194 | partial      | 
|   1322 | partial      | nine
|   1381 | partial      | nine zero
|   1456 | partial      | nine zero one
|   1498 | partial      | nine zero one two
|   1550 | partial      | nine zero one two three
|   1630 | partial      | nine zero one two three stop
|   1649 | endOfSpeech  | nine zero one two three stop
|   1677 | partial      | 
|   1706 | final        | 

```

**Comment by madkote** [comment]
@solyarisoftware to be in JS is a requirement? in python, the task is quite simple.

**Comment by solyarisoftware** [comment]
@madkote I guess python would be perfect

**Comment by nshmyrev** [comment]
No worries, it is just a reminder issue, we'll implement it soon ourselves.

**Comment by solyarisoftware** [comment]
yes. another tip/idea: 
it could be useful / fun to supply a spoken language detector/classifier, on top of the vosk ASR. To be used to select the <vosk language model> in case `--model <vosk language model>`  command line parameter option is not specified ;-)

by example:

    vosk-transcribe file.mp3
    
let's assume that `file.mp3` is an audio file containing russian language utterance 

"Меня зовут Джорджио и я итальянец"

So vosk-transcribe could detect the language (russian in this case) and it could propose to use one of available russian langauge models in vosk (e.g. `vosk-model-ru-0.10` or `vosk-model-small-ru-0.15`, downloading the selected one, if not already present in a local storage directory e.g. ~/.vosk/models/)

:-)

**Comment by o-oconnell** [comment]
@nshmyrev I implemented a tool for this and caching/searching transcription results: https://github.com/o-oconnell/mp4grep

**Comment by nshmyrev** [comment]
@o-oconnell Cool, thank you for sharing! I've added to the list of projects using Vosk.

**Comment by nshmyrev** [comment]
@Vadim-cloud-star issue for you

**Comment by nshmyrev** [comment]
@Vadim-cloud-star See https://github.com/petewarden/spchcat

**Comment by nshmyrev** [comment]
Should be solved now.

**Comment by wbob** [comment]
I was looking to read the commits introducing the cli args - they're at https://github.com/alphacep/vosk-api/pull/941 and history of https://github.com/alphacep/vosk-api/blob/master/python/vosk/transcriber/cli.py

**Comment by m-fuchs** [comment]
Is it possible to get the complete JSON code with vosk-transcriber? I only see txt and srt as output type.

**Comment by vadimdddd** [comment]
@m-fuchs, I think it is not so hard to do that, let's wait what Nikolay will say.

**Comment by vadimdddd** [comment]
@m-fuchs, ok, I put your question in my task list.

**Comment by ptandler** [comment]
In case someone reading this issue is interested, I found https://github.com/ideasman42/nerd-dictation which works quite well and provides simple access speech to text for using in Linux using the vosk-api.
