### ISSUE TITLE
Vosk lower accuracy and missing ivector configs

### ISSUE THREAD

**Issue by maltium** [alphacep/vosk-api#735]
I have self trained a model that I've been using with _online2-wav-nnet3-latgen-faster_ with --do-endpointing=false. Now that I've discovered vosk, I thought I'd give it a go. Accuracy is noticeably worse when using vosk with my model. Is this to be expected?

After comparing the contents of the vosk model directory with the one I use with _online2-wav-nnet3-latgen-faster_, I found that some ivector extractor configs are missing from the vosk model directory. My _ivector_extractor.conf_ looks like so:

```
--splice-config=kaldi-data/conf/splice.conf
--cmvn-config=kaldi-data/conf/online_cmvn.conf
--lda-matrix=kaldi-data/ivector_extractor/final.mat
--global-cmvn-stats=kaldi-data/ivector_extractor/global_cmvn.stats
--diag-ubm=kaldi-data/ivector_extractor/final.dubm
--ivector-extractor=kaldi-data/ivector_extractor/final.ie
--num-gselect=5
--min-post=0.025
--posterior-scale=0.1
--max-remembered-frames=1000
--max-count=100
--ivector-period=10
--online-cmvn-iextractor=true
```

I'm thinking that these missing configs in vosk could explain the mismatch in performance when compared to _online2-wav-nnet3-latgen-faster_. Any thoughts or pointers on this?

**Comment by nshmyrev** [comment]
If you trained your model with online cmvn, you need to make sure you have the file 'am/global_cmvn.stats' so that vosk switches to online cmvn mode. During model load you should see a line 'Reading CMVN stats from..'

**Comment by maltium** [comment]
I did train with online cmvn (based on mini_librispeech 1k recipe). After adding the file to am/global_cmvn.stats as you suggested I'm getting a high word deletion rate. Maybe only 1 out of 5 words is being picked up so now the results have degraded immensely.

**Comment by nshmyrev** [comment]
> based on mini_librispeech 1k recipe

We specifically recommend 1j in documentation

> I'm getting a high word deletion rate

Probably cmn values are wrong. Where did you get them?

**Comment by maltium** [comment]
cmn values are obtained from my trained model. It's very possible that a mixup occured but still puzzled how it does not affect online2-wav-nnet3-latgen-faster.

In any case, I will re-train without online cmvn so I'll close this one. Thank you.
