### ISSUE TITLE
Computing acoustic likelihoods and language model scores

### ISSUE THREAD

**Issue by rutujaubale** [alphacep/vosk-api#736]
I would like to extract word-level acoustic likelihood scores and language model scores for 1-best hypothesis. Is it possible to reuse this method https://github.com/alphacep/vosk-api/blob/master/src/kaldi_recognizer.cc#L465? Any guidance will be appreciated. Thanks!

**Comment by nshmyrev** [comment]
Sorry, Rutuja, I can not help you there as it is not directly related to Vosk. You can ask on kaldi group probably.
