### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by honuvo** [alphacep/vosk-api#737]
Hi,
I'm running python 3.7.5 that comes with PyCharm and have a problem I can't seem to get my head around.
The machine has 16GB ram and an i5-3570 running Windows10

Using the german model "vosk-model-small-de-0.15" everything works fine and i got my program up and running. Great SST by the way :)

However, when using "vosk-model-de-0.21" I get the mentioned error. Here is the full log.

> LOG (VoskAPI:ReadDataFiles():model.cc:211) Decoding params beam=13 max-active=7000 lattice-beam=6
> LOG (VoskAPI:ReadDataFiles():model.cc:214) Silence phones 1:2:3:4:5:6:7:8:9:10
> LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
> LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
> LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0784509 seconds in looped compilation.
> LOG (VoskAPI:ReadDataFiles():model.cc:238) Loading i-vector extractor from model-big/ivector/final.ie
> LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
> LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
> LOG (VoskAPI:ReadDataFiles():model.cc:268) Loading HCLG from model-big/graph/HCLG.fst
> LOG (VoskAPI:ReadDataFiles():model.cc:283) Loading words from model-big/graph/words.txt
> LOG (VoskAPI:ReadDataFiles():model.cc:292) Loading winfo model-big/graph/phones/word_boundary.int
> LOG (VoskAPI:ReadDataFiles():model.cc:299) Loading subtract G.fst model from model-big/rescore/G.fst
> LOG (VoskAPI:ReadDataFiles():model.cc:301) Loading CARPA model from model-big/rescore/G.carpa
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> 
> Process finished with exit code 3

All I could find online was one other person trying a big model on a raspi4 where he was told it's not suitable for such a small machine. What can I do to look for a solution?

Regards,
Simon

**Comment by nshmyrev** [comment]
> Great SST by the way :)

Thank you

> However, when using "vosk-model-de-0.21" I get the mentioned error. Here is the full log.

Big model should require like 4Gb. Are you sure you are not using 32-bit python? It might be a limitation. 64-bit python should help.

**Comment by honuvo** [comment]
Doink...
That's it. Works like a (py)charm now, thank you. Little embarrassed, I only checked the IDE for 64bit, not the actual python-binary. Happily closing this issue :)
