### ISSUE TITLE
Adding Thai language support to Vosk

### ISSUE THREAD

**Issue by zairosoft** [alphacep/vosk-api#739]
how to add thai language to vosk?

Now there is a robot project in Thai language. But now I don't know how to training model thai language

**Comment by nshmyrev** [comment]
We can cooperate on this. You can help to collect the data from youtube. You can contact me in telegram https://t.me/nshmyrev to discuss the details.

**Comment by nshmyrev** [comment]
Or you can mail me nshmyrev@alphacephei.com and suggest meeting time.

**Comment by zairosoft** [comment]
@nshmyrev 
now can training thai language already

common voice dataset

https://github.com/vistec-AI/commonvoice-th
https://github.com/vistec-AI/commonvoice-th/releases

**Comment by nshmyrev** [comment]
> now can training thai language already

Thats cool. Still, the model is pretty basic. If you need bigger model let me know

**Comment by zairosoft** [comment]
Hello @nshmyrev 
I have compiled videos youtube thai for you.
common voice dataset Thai language is not accurate

https://www.youtube.com/watch?v=a8hpFVr8I04&list=PL-12kwWj1-LeQFI5f1SeeFygdmKy3TVSz&index=1&t=58s

**Comment by nshmyrev** [comment]
@nakhonsoft sorry, I don't understand anything from the video. Its in Thai ;) any action required from me?
