### ISSUE TITLE
Memory leak with the Node.js package

### ISSUE THREAD

**Issue by AntoRin** [alphacep/vosk-api#742]
Each time a new audio is processed by Vosk, the memory goes up by around 400 MB, and never comes down. 

I am streaming the output from ffmpeg through a Transform stream that processes the audio data and outputs speech recognition data. For some reason, streaming takes even more memory than the synchronous version -- memory usage increases by around 700 to 800 MB per audio.

Here's my code for reference:

```const { Transform } = require("stream");
const vosk = require("vosk");

class VoskProcessor extends Transform {
   constructor({ modelPath, sampleRate }, streamOptions = undefined) {
      super(streamOptions);

      vosk.setLogLevel(0);
      this.rec = new vosk.Recognizer({ model: new vosk.Model(modelPath), sampleRate });
      this.rec.setWords(true);
   }

   _transform(chunk, encoding, cb) {
      this.rec.acceptWaveformAsync(chunk).then(value => {
         if (value) {
            this.push(JSON.stringify(this.rec.result()));
         } else {
            this.push(JSON.stringify({}));
         }
         cb();
      });
   }
}

module.exports = { VoskProcessor };
```

**Comment by nshmyrev** [comment]
How about `recognizer.free()` as in 

https://github.com/alphacep/vosk-api/blob/4ccdda44acef5253929bb1a7c8651a948fe4d5c9/nodejs/demo/test_simple.js#L39

**Comment by AntoRin** [comment]
> How about `recognizer.free()` as in
> 
> https://github.com/alphacep/vosk-api/blob/4ccdda44acef5253929bb1a7c8651a948fe4d5c9/nodejs/demo/test_simple.js#L39

Ha! This. did the trick.
But I had to do MODEL.free() too.

Besides, is it okay to create a new Model for every audio? Or should I use the same Model for every process? Which is recommended? 

Thank you so much for the help, @nshmyrev .

**Comment by nshmyrev** [comment]
> Besides, is it okay to create a new Model for every audio?

No

> Or should I use the same Model for every process?

Yes

**Comment by AntoRin** [comment]
> > Besides, is it okay to create a new Model for every audio?
> 
> No
> 
> > Or should I use the same Model for every process?
> 
> Yes

Thank you so much! I really, really appreciate it :)
