### ISSUE TITLE
Endpoint rules - silence [documentation]

### ISSUE THREAD

**Issue by madkote** [alphacep/vosk-api#744]
Please provide some explanation and ways on the usage of endpoint rules.

Example `vosk-model-en-us-0.22` has configuration with following values
```
--endpoint.rule2.min-trailing-silence=0.5
--endpoint.rule3.min-trailing-silence=0.75
--endpoint.rule4.min-trailing-silence=1.0
```

The configuration above will produce an empty `final` for silence after **7 seconds** after last decoding and then **every 5 seconds** empty `final` result, when silence continues.

**Questions**
- How the values come together?
  * 7sec - ? First silence after a decoding
  * 5sec - ? Other silence after a first silence
- How to control the first silence 7sec (e.g. reduce from 7sec to 3.5sec)
- How to control the second silence 5sec (e.g. reduce from 5sec to 2.5sec)

-------
**Example**
I can not share my audio, but it works on any audio with long silences between utterances.

Additional notes:
- `timestamp` is time in the audio stream (debugging).
- `duration` and `offset` are taken from `results` (also for debugging).
```
....
{'duration': 1.14,
  'offset': 172.8,
  'result': [{'conf': 0.920729,
              'end': 172.92,
              'start': 172.8,
              'word': 'NINE'},
             {'conf': 0.977197,
              'end': 173.37,
              'start': 172.95,
              'word': 'THIRTY'},
             {'conf': 0.977197,
              'end': 174.06,
              'start': 173.43,
              'word': 'AM'}],
  'text': 'NINE THIRTY AM'},
 {'text': '', 'timestamp': 180.0},
 {'text': '', 'timestamp': 185.1},
 {'text': '', 'timestamp': 190.1},
 {'text': '', 'timestamp': 195.2},
 {'duration': 0.0,
  'offset': 195.87,
  'result': [{'conf': 0.443562,
              'end': 196.26,
              'start': 195.87,
              'word': 'NO'}],
  'text': 'NO'},
....
```

Many thanks in advance!

**Comment by nshmyrev** [comment]
> some other configuration might use a reversed order.

Which other configuration exactly

> accordingly to Kaldi documentation, rules are evaluated as OR, whereby rule4 and rule5 will trigger independent of decoding state. 

What exactly Kaldi documentation says and where.

**Comment by madkote** [comment]
> > some other configuration might use a reversed order.
> 
> Which other configuration exactly
> 
> > accordingly to Kaldi documentation, rules are evaluated as OR, whereby rule4 and rule5 will trigger independent of decoding state.
> 
> What exactly Kaldi documentation says and where.

Initial comment updated. thx

**Comment by nshmyrev** [comment]
You have too many questions here, it is hard to help you that way. Can you ask a single focused question first and provide the details? What is the problem you have.

**Comment by madkote** [comment]
> You have too many questions here, it is hard to help you that way. Can you ask a single focused question first and provide the details? What is the problem you have.

Updated and simplified the initial comment - now it is only about how to control silence events. Thx!

**Comment by madkote** [comment]
@nshmyrev I have confused you and myself with 7sec and 5 sec - it is always 5 sec. My fault, was comparing stream timestamps and decoder timestamps, which are slightly different (issues exists already).
The current issue is resolved by using rule1.

Thank you for patience with me.

**Comment by nshmyrev** [comment]
Same as #380
