### ISSUE TITLE
Extending dictionary of German Small model

### ISSUE THREAD

**Issue by errmac** [alphacep/vosk-api#745]
Hi, 
first of all big thanks for your work!

The small German model ([vosk-model-small-de-0.15](https://alphacephei.com/vosk/models/vosk-model-small-de-0.15.zip)) just works fairly well for me, except for a lot off  
(spoken) numbers in the range of up to 200.
I need to recognize all of these number-words in different "flavours".
(For example: 182 = "einhundertzweiundachtzig" | "hundertzweiundachtzig" | "hundertundzweiundachtzig" | "einhundertundzweiundachtzig")

So as far as I understand, there's **no need to adapt acoustic or language model, but only to extend the phonetic dictionary**
(according to [https://alphacephei.com/vosk/adaptation](https://alphacephei.com/vosk/adaptation) ) and therefore I need the **compilation package** of the small model (?)

Is this the correct approach and is it possible to download the compilation package of the small DE model from somwhere?

Thx very much in advance...

**Comment by nshmyrev** [comment]
> (For example: 182 = "einhundertzweiundachtzig" | "hundertzweiundachtzig" | "hundertundzweiundachtzig" | "einhundertundzweiundachtzig")

Make them separate words like 'einhundert zweiundachtzig', it will probably work easier.

For update package mail contact@alphacephei.com

**Comment by errmac** [comment]
Yes, I thought about that as an alternative and I'm currently evaluating it with good results...
If I'll get stuck, I will ask for the compilation package via mail
Thanks again!
