### ISSUE TITLE
Time delays in spoken and transcription for longer audio

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#747]
I found out in two models 
de_21 
us_en_21/22 both

when we use longer files like more than 12/13 min, there is time shift and delays in spoken and transcription timing. specially this is the case when audio is 30/40/50min long.

Is this because of my any mistake or this is normal-
I have used audio wav format 16k file . Please if you can guide me how to handle this issue.

**Comment by Tortoise17** [comment]
I am using command to convert mp4 to wav
`ffmpeg -i input.mp4 -vn -acodec pcm_s16le -ar 16000 -ac 1 output.wav`

and version for vosk api is `vosk 0.3.17`

**Comment by nshmyrev** [comment]
Try the latest version 0.3.32
