### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'AcceptWaveform'

### ISSUE THREAD

**Issue by Tortoise17** [alphacep/vosk-api#748]
With the previous routine, everything worked well

When I changed to Vosk from 0.3.15 to 0.3.33

I faced this issue, 

`AttributeError: 'KaldiRecognizer' object has no attribute '_handle'`
but, I tried to fix this by
`
rec = KaldiRecognizer(model, wf.getframerate(), spk_model)`

and now 
```
 if rec.AcceptWaveform(data):
AttributeError: 'tuple' object has no attribute 'AcceptWaveform'
```

I tried some ways to get it fixed, and it hangs without doing anything. 
I am trying to get the transcript and speaker info at the same time with the both models usage. 

Can u guide what to do this and how to get it fixed. 

Until vosk 0.3.15 it was working out class.

**Comment by nshmyrev** [comment]
It should be some simple error in your own code. You can print value of 'rec' to see why it is assigned to tuple.
