### ISSUE TITLE
Speech to Text with multiple Languages and switch between Languages

### ISSUE THREAD

**Issue by tomasmueller** [alphacep/vosk-api#749]
I use Vosk API with a very simple shell script that works perfect for german audio files

`python3 /home/thomas/bin/vosk-api/python/example/test_srt.py input > output.srt`

I use the "big" german model (vosk-model-de-0.21) thats extracted more than 3GB big. I have problems when there are english words in the german text. Can i use both the german AND the english model at the same time or is the only way to learn the  english words to the german model?

How can i switch between the german and the english model when the media file is english? The command line above is using the model stored in "/home/thomas/bin/vosk-api/python/example/model/" and thats the german model. When i download the english model and extract it the german will be overwritten.

**Comment by nshmyrev** [comment]
> Can i use both the german AND the english model at the same time or is the only way to learn the english words to the german model?

We do not have this feature yet unfortunately

> How can i switch between the german and the english model when the media file is english? 

You can run language detector on a file first to detect a language. Like this one:

https://huggingface.co/TalTechNLP/voxlingua107-epaca-tdnn

**Comment by tomasmueller** [comment]
I have created a new folder 'example-eng' wth the same scripts for english and check the language with ffprobe. Then i go the the correct folder and run the script.

I will test the language detector this weekend.

Is there an option to show the progress?

**Comment by nshmyrev** [comment]
Let us know if you need other information. The original problem is tracked at #233 actually
