### ISSUE TITLE
Question on how to perform lm rescoring

### ISSUE THREAD

**Issue by zaowad** [alphacep/vosk-api#75]
Hi, i found there is no script to add lm-rescoring. Can you please guide me on how to perform rescoring with small_lm(G.fst) and large_lm(G.carpa) .?

**Comment by zaowad** [comment]
> carpa rescoring is now implemented in vosk-api
> 
> rnnlm rescoring still pending

Thanks a lot Mr @nshmyrev  . That was a big help

**Comment by v-yunbin** [comment]
@nshmyrev whether the fst rescoring is supported？ I put "G.fst" in folder "rescore", it seems not work.

**Comment by nshmyrev** [comment]
RNNLM rescoring implemented now in ee8663e6d914816f8befb4f4c5abec08f693b2c0
