### ISSUE TITLE
Pip3 install not working on mac M1

### ISSUE THREAD

**Issue by jwbrown** [alphacep/vosk-api#750]
Mac M1 (Mac OS 11.6 big sur)

python3 --version && pip3 --version && pip3 -v install vosk -U
Python 3.9.5
pip 21.3.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)
Using pip 21.3.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk

I have this working on my PI but would like to also run it on my mac for development...  Any direction how i can get the install to work?

**Comment by nshmyrev** [comment]
Sorry, we do not support M1 yet. You can probably use Vosk on your laptop with x86 emulation. See for details

https://github.com/alphacep/vosk-api/issues/692
