### ISSUE TITLE
Error when compiling vosk source for android target

### ISSUE THREAD

**Issue by nprantik** [alphacep/vosk-api#751]
I am trying to compile Vosk from source for Android target and have been getting the following errors.
[vosk_issues.txt](https://github.com/alphacep/vosk-api/files/7486461/vosk_issues.txt)

**Comment by nshmyrev** [comment]
What is your ndk/sdk version?

**Comment by nprantik** [comment]
NDK version is 21
SDK Platform API level is 31

**Comment by nshmyrev** [comment]
Can you try to update ndk?

**Comment by nprantik** [comment]
I tried doing so, but getting the same errors

**Comment by nprantik** [comment]
Can you tell me which NDK version should work.

**Comment by nshmyrev** [comment]
Can you try the latest r23b (23.1.7779620)

**Comment by nprantik** [comment]
I am getting the same issues even after using latest NDK

**Comment by nshmyrev** [comment]
Share the latest log please

**Comment by nprantik** [comment]
[vosk_issues_NDK_23_latest.txt](https://github.com/alphacep/vosk-api/files/7491928/vosk_issues_NDK_23_latest.txt)

**Comment by nshmyrev** [comment]
Hey, I pushed some updates. Its strange it worked for you before. You have to many items in your path, I'd use cleaner PATH.

Please try to pull latest changes, build from clean state and share an updated log.

**Comment by nprantik** [comment]
I pulled the latest changes and built from a clean state, getting same issues.
[vosk_updated_issues_NDK_23.txt](https://github.com/alphacep/vosk-api/files/7493917/vosk_updated_issues_NDK_23.txt)

**Comment by nshmyrev** [comment]
> I pulled the latest changes and built from a clean state, getting same issues. [vosk_updated_issues_NDK_23.txt](https://github.com/alphacep/vosk-api/files/7493917/vosk_updated_issues_NDK_23.txt)

>  AR=arm-linux-androideabi-ar

This is certainly not the latest state. Latest says:

https://github.com/alphacep/vosk-api/blob/f71c62ad0ffe978c318994d0df3636949e98af8f/android/lib/build-vosk.sh#L43

**Comment by nprantik** [comment]
The shared log has
AR=llvm-ar (Line 15)

**Comment by nprantik** [comment]
Attaching the logs again
[vosk_updated_issues_NDK_23.txt](https://github.com/alphacep/vosk-api/files/7495501/vosk_updated_issues_NDK_23.txt)

**Comment by nshmyrev** [comment]
Ok, this one is better. Please also share the output of the `set` command

**Comment by nprantik** [comment]
The shared log has all the output generated from the build-vosk.sh script.
set -x command enables a mode of the shell where all executed commands are printed to the terminal

**Comment by nshmyrev** [comment]
I'm asking for the output of the `set` command with the environment variables you have.

**Comment by nprantik** [comment]
Attaching the output of set command
[set_output.txt](https://github.com/alphacep/vosk-api/files/7496099/set_output.txt)

**Comment by nshmyrev** [comment]
In your environment I see some not so nice things affecting compiler:

CPLUS_INCLUDE_PATH=:/usr/include/python3.6
CFLAGS='-I/usr/local/cuda-10.2/include '

could you please try to cleanup the environment. You can try something like https://unix.stackexchange.com/questions/48994/how-to-run-a-program-in-a-clean-environment-in-bash

**Comment by nshmyrev** [comment]
Fee free to reopen/comment once you have extra information
