### ISSUE TITLE
how to train custom model

### ISSUE THREAD

**Issue by smil4ever** [alphacep/vosk-api#754]
wo want to train ourself asr model, but i do not find how to do in the docs, please introduce official model how to train.

**Comment by andrzej-onja** [comment]
https://alphacephei.com/vosk/models there is a section about training. Haven't done it myself though

**Comment by smil4ever** [comment]
thanks

**Comment by smil4ever** [comment]
that is right

**Comment by nshmyrev** [comment]
The issue discussed here: #41
