### ISSUE TITLE
Is it free? If so, what is the price?

### ISSUE THREAD

**Issue by Richtechwy** [alphacep/vosk-api#761]
Is it free? If so, what is the price?

**Comment by nshmyrev** [comment]
It is free

**Comment by Richtechwy** [comment]
Hi，
Is Vosk completely open source. Can it be used commercially?

**Comment by Richtechwy** [comment]
Hi，
Is Vosk completely open source?&nbsp;Can it be used commercially?&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Nickolay V. ***@***.***&gt;;
Date: &nbsp;Tue, Nov 16, 2021 10:55 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [alphacep/vosk-api] Is it free? If so, what is the price? (Issue #761)

&nbsp;



 
It is free
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nshmyrev** [comment]
> Is Vosk completely open source. 

Yes

> Can it be used commercially?

Yes

**Comment by Richtechwy** [comment]
Think you

**Comment by reactivespace** [comment]
what is price of Vosk Enterprise version
