### ISSUE TITLE
It would be good to have Dart/Flutter implementation

### ISSUE THREAD

**Issue by denisano** [alphacep/vosk-api#762]
Flutter+Dart is a popular programming platform from Google to build  android/ios, web, desktop and embedded apps from a single codebase. Its popularity is grown quickly. So it would be great to have ready to use Vosk implementation on Dart/Flutter.

**Comment by nshmyrev** [comment]
Sure, thank you. We have some ongoing work here:

https://github.com/alphacep/vosk-api/issues/262

not fully complete yet. Contributions are welcome of course!
