### ISSUE TITLE
How to improve peed and recognition accuracy in Unity

### ISSUE THREAD

**Issue by Richtechwy** [alphacep/vosk-api#763]
I have run your Unity example and found that the accuracy of speech recognition and recognition response speed are not very good. May I ask how to improve it?（vosk-stt-unity）

**Comment by Tetsujinfr** [comment]
hum, can you give a bit more dtail? E.g. which model did you use for your test?

**Comment by nshmyrev** [comment]
Feel free to comment with additional details to reopen.
