### ISSUE TITLE
Generate Model for speaker recognition on Android

### ISSUE THREAD

**Issue by chefchefchef** [alphacep/vosk-api#765]
I want to implement speaker recognition on android. For the speaker I just have a (always different) audio-file (wav). I see there is currently no possibility to generate the necessary model/mfcc-files from that wav-file on android but I would like to ask, if you are planning something in the near future to provide in the vosk-api projekt for android?

**Comment by nshmyrev** [comment]
Speaker recognition already works on android, you just load speaker model and every result will have xvector included.

**Comment by chefchefchef** [comment]
yes I see one can use the speaker model on android. my case is that I don't yet have a vosk-speaker-model. I only have a sample (wav-file) of the speaker on the phone and I would like to use that sample to generate the vosk-speaker-model. all done only on android. as I see in the API there is no "generate speaker model"-method on the android project. or am I wrong? would it be possible to provide such a method for android?

**Comment by nshmyrev** [comment]
The API to generate speaker model (x-vector) is the same as recognition, you need to read about x-vectors. You can also check python example test_speaker.py

We track this issue in #405

**Comment by chefchefchef** [comment]
I know that I need the x-vectors and have to compare them etc. I have used other libraries before. But I'm struggling earlier. What I'm struggling with is:
- I downloaded the vosk-model-spk-0.4 which I use as "model"
- The "spk_model" I have to "generate" on the android phone. On the android I only have the wav-file from the speaker. How do I get the speaker model from the wav-file?

**Comment by puvvadasaikiran** [comment]
vosk-model-spk-0.4  is spk-model
model is refered to asr model
