### ISSUE TITLE
VOSK installation : ERROR: No matching distribution found for vosk | Mac

### ISSUE THREAD

**Issue by puneet0311** [alphacep/vosk-api#766]
trying to install VOSK on mac pro M1 but getting below exception. I have installed python 3.8.12 version but still same issue

ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk

puneetgupta@~ % /Users/puneetgupta/.pyenv/versions/3.8.12/bin/pip3 --version && /Users/puneetgupta/.pyenv/versions/3.8.12/bin/pip3 -v install vosk -U
pip 21.1.1 from /Users/puneetgupta/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pip (python 3.8)
Using pip 21.1.1 from /Users/puneetgupta/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/c8/xgq4wy3d7s7d6ttbcgjvjfd40000gn/T/pip-ephem-wheel-cache-jgsdqhoo
Created temporary directory: /private/var/folders/c8/xgq4wy3d7s7d6ttbcgjvjfd40000gn/T/pip-req-tracker-socqb_fv
Initialized build tracking at /private/var/folders/c8/xgq4wy3d7s7d6ttbcgjvjfd40000gn/T/pip-req-tracker-socqb_fv
Created build tracker: /private/var/folders/c8/xgq4wy3d7s7d6ttbcgjvjfd40000gn/T/pip-req-tracker-socqb_fv
Entered build tracker: /private/var/folders/c8/xgq4wy3d7s7d6ttbcgjvjfd40000gn/T/pip-req-tracker-socqb_fv
Created temporary directory: /private/var/folders/c8/xgq4wy3d7s7d6ttbcgjvjfd40000gn/T/pip-install-rcc7nfo1
1 location(s) to search for versions of vosk:
* https://pypi.org/simple/vosk/
Fetching project page and analyzing links: https://pypi.org/simple/vosk/
Getting page https://pypi.org/simple/vosk/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/vosk/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/vosk/ HTTP/1.1" 304 0
  Skipping link: none of the wheel's tags (cp34-cp34m-manylinux2010_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/f8/87/16f70e6d04518377a02463b57644efe3b7f0fae328601079c9a7ac847739/vosk-0.3-cp34-cp34m-manylinux2010_x86_64.whl#sha256=9029063e4550862a71b3978311f24c367792857d5d2d8dfeec7a6a01c2c7ed68 (from https://pypi.org/simple/vosk/) (requires-python:>=3.5)

**Comment by nshmyrev** [comment]
We do not support M1 yet, sorry. We track this issue in #692
