### ISSUE TITLE
Adding OOV words on the fly

### ISSUE THREAD

**Issue by shashankmc** [alphacep/vosk-api#767]
Hi,

I'm trying to include OOVs to the recognizer vocabulary in real time as seen here - https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py and add technical OOVs like so -

`rec = KaldiRecognizer(model, wf.getframerate(), '["paleoanthropology", "[unk]"]')`

I'm primarily adding technical words into the recognizer but WER isn't changing. I'm a noob at this and trying to get better results compared to the pre-trained model.

1. First off, is this the right approach of doing it without training the language model?
2. If this is incorrect, what should I be doing to add OOVs to the vocabulary without having to retrain the model?

Any help would be really appreciated, thank you!

**Comment by RafNie** [comment]
You can only use words from vocabulary (words.txt file).
You would have to create the new language model HCLG with yours OOV words.

Replacing only G part is possible for words form the lexicon. For new words is needed also creating HCL part which contain phoneme representation of words.

**Comment by shashankmc** [comment]
Oh. Why does it say explicitly in the shared link that the recognizer's vocabulary can be modified? Am I misunderstanding the meaning of it?

**Comment by nshmyrev** [comment]
> Why does it say explicitly in the shared link that the recognizer's vocabulary can be modified?

I don't see anything like "modified" on https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py

  > Am I misunderstanding the meaning of it?
  
  Yes

**Comment by shashankmc** [comment]
Sorry, this is the link - https://alphacephei.com/vosk/adaptation from which I was redirected to the above link.

**Comment by nshmyrev** [comment]
Same as #725
