### ISSUE TITLE
Training German

### ISSUE THREAD

**Issue by ErnstTmp** [alphacep/vosk-api#768]
Hello,
can you comment how vosk-model-de-0.21 was trained - which data was used, and how many hours? Which recipe did you use?
Thanks a lot,
Ernst

**Comment by nshmyrev** [comment]
Hi. You can find some information here:

https://alphacephei.com/nsh/2020/08/09/german.html

we don't share the recipes, but they are more or less standard. Totally there was 5k hours of data.

**Comment by ErnstTmp** [comment]
Thanks! Would you be able to provide consulting to help us set this up for us?

**Comment by nshmyrev** [comment]
Please contact me on nshmyrev@alphacephei.com, I'd be happy to discuss.
