### ISSUE TITLE
Does Vosk support any TPU/NPU, etc. out of the box?

### ISSUE THREAD

**Issue by etlweather** [alphacep/vosk-api#769]
There are various AI accelerator such as Coral AI TPU, Intel Compute Stick, etc. as well as some SoC with NPU for AI built-in like Orange PI 4B and others.

Just wondering if Vosk can benefit from those right out-of-the-box, or would it require extensive modifications.

**Comment by nshmyrev** [comment]
No, we do not support anything like that.
