### ISSUE TITLE
Support online cmvn ivector

### ISSUE THREAD

**Issue by lalimili6** [alphacep/vosk-api#77]
Hi Nickolay
Is Kaldi-WebSocket support online cmvn?
https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/local/chain/tuning/run_tdnn_1i.sh
https://github.com/kaldi-asr/kaldi/pull/3560/files

my results on this model are different.

best regards

**Comment by nshmyrev** [comment]
We now enable online cmvn if there is am/global_cmvn.stats:

https://github.com/alphacep/vosk-api/blob/a4721de8aaef8f75ad63b0281d9f58bc4bdff51e/src/model.cc#L266
