### ISSUE TITLE
Alignments 

### ISSUE THREAD

**Issue by ErnstTmp** [alphacep/vosk-api#773]
Hello!
In order to refine the German Vosk model, I would need the alignment files. Ali*.gz for the model vosk-model-de-0.21. Are they publicly available or is there a way to get them?

Thanks a lot,
Ernst

**Comment by nshmyrev** [comment]
Alignments created during adaptation with audio files and the model using the script nnet3/align.sh. Morever, they are not needed for adaptation, you need lats with nnet3/align_lats.sh, not alignments. You do not need to recreate ivector.

You can check daanzu scripts for details

https://github.com/daanzu/kaldi_ag_training/blob/main/run_finetune_tdnn_1a_daanzu.sh

**Comment by ErnstTmp** [comment]
Thanks a lot! I tried to run the script, but I could not finish it since L.fst was missing. Also, it seems to require the alignments.
align_lats.sh also seems to fail. The error messages are this:

# Stage 5
# Align the new dataset with source NN
# Wed Dec  8 22:19:16 CET 2021

steps/nnet3/align_lats.sh --cmd utils/run.pl --nj 8 --acoustic-scale 1.0 --scale-opts --transition-scale=1.0 --self-loop-scale=1.0 --online-ivector-dir exp/nnet3_chain/ivectors_finetune_sp_vp_hires --generate_ali_from_lats true data/finetune_sp_vp_hires data/lang ./exp/model_src_dir exp/nnet3_chain/lats_finetune_sp_vp_hires
steps/nnet2/check_ivectors_compatible.sh: WARNING: One of the directories do not contain iVector ID.
steps/nnet2/check_ivectors_compatible.sh: WARNING: That means it's you who's reponsible for keeping 
steps/nnet2/check_ivectors_compatible.sh: WARNING: the directories compatible
steps/nnet3/align_lats.sh: no such file data/lang/L.fst

In the beginning of run_finetune_tdnn_1a_daanzu.sh it says that these files are needed:

#   tree_dir (tree final.mdl **ali.*.gz** phones.txt)
#   lang_dir (oov.int **L.fst** words.txt phones.txt phones/disambig.int)
#   conf_dir (mfcc.conf mfcc_hires.conf)

Missing are in the vosk model the files Ali*.gz and L.fst. How can I overcome this?

Thanks, Ernst
