### ISSUE TITLE
The accurate and speed of comparing openblas with mkl

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#774]
I compare mkl and openblas，find that mkl is faster than openblas for speed，but using mkl leads into a word lost and using openblas is normal.

**Comment by nshmyrev** [comment]
>  I compare mkl and openblas，find that mkl is faster than openblas for speed

Yes

> but using mkl leads into a word lost and using openblas is normal.

It might be due to some instability of your model. Like unstable ivector or something. With more or less robust training results should be the same.

**Comment by v-yunbin** [comment]
I  close the issue，it is due to that I compile kaldi with openblas and compile vosk with mkl.
1. compile kaldi with mkl and compile vosk with mkl
2. compile kaldi with openblas and compile vosk with openblas
For the two above  case, I get consistent recognizing results.
