### ISSUE TITLE
What is the use of SetWords and SetMaxAlernatives

### ISSUE THREAD

**Issue by etlweather** [alphacep/vosk-api#775]
I have been searching the web, this repo and the web site and I can't find any documentation for the `KaldiRecognizer` API. It has `SetMaxAlternatives` and `SetWords` methods which I am trying to understand what impact these options have.

Is there a place where this is defined? Or could I get an explanation?

**Comment by nshmyrev** [comment]
SetMaxAlternatives enables alternative transcriptions in the output, SetWords enables word times.

You can check the docs here:

https://github.com/alphacep/vosk-api/blob/master/src/vosk_api.h#L151

https://github.com/alphacep/vosk-api/blob/master/src/vosk_api.h#L187

**Comment by etlweather** [comment]
Oh, great, somehow missed that!
