### ISSUE TITLE
Another project using Vosk

### ISSUE THREAD

**Issue by bablokb** [alphacep/vosk-api#778]
Hi,

not an issue, just an information so that  you can add it to your list: I'm using Vosk successfully in my project https://github.com/bablokb/pi-webradio to control an internet radio (on, off, switching channels and so on).

Thanks for your work! It was very easy to implement thanks to all of your examples.

Bernhard

**Comment by nshmyrev** [comment]
Amazing, thank you for sharing. We added it to the list of projects at our website!

**Comment by nshmyrev** [comment]
Posted on Raspberry Forum too:

https://forums.raspberrypi.com/viewtopic.php?t=325391

let us know if you need something, Bernhard.
