### ISSUE TITLE
Slow to load big model due to big memory requirements

### ISSUE THREAD

**Issue by fquirin** [alphacep/vosk-api#779]
Hi,

I've tested the newer [vosk-model-de-0.21](https://alphacephei.com/vosk/models/vosk-model-de-0.21.zip) with Vosk 0.3.32 and the basic test script (taken from python/examples using a 8s WAV in German) and realized that it is incredibly slow (~1min 40s) compared to the older [vosk-model-de-0.6](https://alphacephei.com/vosk/models/vosk-model-de-0.6.zip) (basically real-time ~8s).

The step that takes "forever" is:  
`LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading RNNLM model from model/rnnlm/final.raw`  

Is this expected or is there something else going on? :thinking:   
My test system is an Intel Core i3 with 8GB RAM.

**Comment by nshmyrev** [comment]
You don't have enough memory to run this fast, it requires 16gb. You can delete rnnlm folder from the model, it will be faster.

**Comment by fquirin** [comment]
Ok, I see :-/ Thanks for the blazing fast answer! :grin: 
Might be useful to add this as a note to the model? To you have a rough idea of the impact on WER? :slightly_smiling_face:

**Comment by nshmyrev** [comment]
> Might be useful to add this as a note to the model? 

Sure, please submit a pull request to vosk-space project

> To you have a rough idea of the impact on WER? 🙂

in general rnnlm provides much more readable transcripts, but WER improvement is about 5% relative.

**Comment by fquirin** [comment]
> Sure, please submit a pull request to vosk-space project

Done.

Btw, something I noticed when playing with the small DE model (v0.15 ~45MB) and the larger ones (v0.6 and v0.21): The smaller one seems more robust against noise. It rarely triggers any random words in continuous mode where as the larger ones recognize "nun" and "einen" quite often even in a rather quite environment.

**Comment by nshmyrev** [comment]
Yes, it might be like that. Usually the bigger the model is the harder to make it robust.

I added a note about model resources alphacep/vosk-space@db216cb
