### ISSUE TITLE
can i use this without downloading language models in c#

### ISSUE THREAD

**Issue by smd-11** [alphacep/vosk-api#782]

**Comment by nshmyrev** [comment]
No, sorry, you have to download models first. Automatic download is not yet implemented.

**Comment by smd-11** [comment]
is there any server that i can send stream from my microphone and it will convert

**Comment by nshmyrev** [comment]
Yes, vosk-server:

https://github.com/alphacep/vosk-server

https://github.com/alphacep/vosk-server/blob/master/client-samples/csharp/test.cs

You can directly get speech input from the server too:

https://github.com/alphacep/vosk-server/tree/master/websocket-microphone

**Comment by smd-11** [comment]
i am getting unable to connect to remote server when using vosk server using test.cs code in my project

**Comment by nshmyrev** [comment]
Tell us more about it!

**Comment by smd-11** [comment]
i am getting 
Unable to connect to remote server in 

 async Task DecodeFile() method at line

                await ws.ConnectAsync(new Uri("wss://api.alphacephei.com/asr/en/"), CancellationToken.None);

**Comment by nshmyrev** [comment]
Try with a local server instead
