### ISSUE TITLE
Testing with microphone fail

### ISSUE THREAD

**Issue by wizVR-zhangjun** [alphacep/vosk-api#784]
![image](https://user-images.githubusercontent.com/60952586/145504803-a96e8b20-caf0-4d8d-b571-1e1e8566dd5a.png)

**Comment by nshmyrev** [comment]
Try `test_microphone.py -u ws://localhost:2700`. Or just `test_microphone.py` without url.

**Comment by nshmyrev** [comment]
I fixed the instructions on website.
