### ISSUE TITLE
Vosk model taking time to load

### ISSUE THREAD

**Issue by danishkhan3621** [alphacep/vosk-api#785]
Model instance is created every time i run the code is there any way to use same model reference because it is taking 30s time to handle every request.

**Comment by nshmyrev** [comment]
Do not create model every time, load it once.

**Comment by danishkhan3621** [comment]
`model = Model("model")` this model instance is being created should i use cache to store model in python

```
class Model(object):

    def __init__(self, model_path):
        super().__init__()
        self._handle = _c.vosk_model_new(model_path.encode('utf-8'))

        if self._handle == _ffi.NULL:
            raise Exception("Failed to create a model")

    def __del__(self):
        _c.vosk_model_free(self._handle)

    def vosk_model_find_word(self, word):
        return _c.vosk_model_find_word(self._handle, word.encode('utf-8'))
```

**Comment by nshmyrev** [comment]
> should i use cache to store model in python

No

See the vosk-server code for proper implementation:

https://github.com/alphacep/vosk-server/blob/master/websocket/asr_server.py

model is created one time.

**Comment by danishkhan3621** [comment]
Okay Thanks, i was using this https://github.com/alphacep/vosk-api/tree/master/python/example code, Are both the codes different?

**Comment by nshmyrev** [comment]
> Are both the codes different?

They are examples

**Comment by danishkhan3621** [comment]
Thanks Can you please provide some links related to server setup and how to use it

**Comment by nshmyrev** [comment]
Some information is here https://alphacephei.com/vosk/server
