### ISSUE TITLE
french model adoption

### ISSUE THREAD

**Issue by sravani40** [alphacep/vosk-api#787]
i want to adopt large french model by training language model for my data. that linto model when i am trying to change language model getting errors. may be phonemes incompatible. can i know the procedure for adoption of french model. i want to change language model only. and which tool you have used for generating the lexicon for french words?

**Comment by nshmyrev** [comment]
The documentation is here:

https://alphacephei.com/vosk/lm

> and which tool you have used for generating the lexicon for french words?

we use phonetisaurus
