### ISSUE TITLE
compile-graph.sh: line 15: ngram-count: command not found

### ISSUE THREAD

**Issue by sravani40** [alphacep/vosk-api#789]
i have installed srilm still getting same error.

export PATH=$PWD/utils:$KALDI_ROOT/src/bin:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/tools/openfst-1.6.7/bin:$KALDI_ROOT/tools/srilm/lm/src:$KALDI_ROOT/src/fstbin:$KALDI_ROOT/src/gmmbin:$KALDI_ROOT/src/featbin:$KALDI_ROOT/src/lm:$KALDI_ROOT/src/sgmmbin:$KALDI_ROOT/src/sgmm2bin:$KALDI_ROOT/src/fgmmbin:$KALDI_ROOT/src/latbin:$KALDI_ROOT/src/nnetbin:$KALDI_ROOT/src/nnet2bin:$KALDI_ROOT/src/online2bin:$KALDI_ROOT/src/ivectorbin:$KALDI_ROOT/src/lmbin:$KALDI_ROOT/src/chainbin:$KALDI_ROOT/src/nnet3bin:$KALDI_ROOT/src/rnnlmbin:$PWD:$PATH:$KALDI_ROOT/tools/sph2pipe_v2.5
export PATH=$KALDI_ROOT/tools/ngram-1.3.7/src/bin:$PATH
export LD_LIBRARY_PATH=$KALDI_ROOT/tools/openfst/lib/fst/
export LC_ALL=C

**Comment by nshmyrev** [comment]
It is an issue about PATH variable and location of srilm binaries

**Comment by japita-se** [comment]
How did you solve it?

**Comment by bbergeron0** [comment]
@japita-se run `extra/install_srilm.sh` within kaldi's `tools` directory. Then run `. <path_to_kaldi>/tools/env.sh`. The dot before the path is important.

**Comment by SaintE419** [comment]
@nshmyrev @bbergeron0 The old installation connection is dead.Which version of srilm can meet the requirements?
![image](https://github.com/user-attachments/assets/ca6d9ec5-238d-4530-960f-034dae0e39d5)

**Comment by nshmyrev** [comment]
@SaintE419 https://github.com/BitSpeech/SRILM
