### ISSUE TITLE
language model adaptation for pretrained models

### ISSUE THREAD

**Issue by 123srikanth** [alphacep/vosk-api#790]
Hi there I have downloaded vosk pretrained model for US English and I want to train it on my own data so for that it was mentioned in the same blog to add the extra texts into db/extra.txt but in  db/extra.txt file I can see only the words being present so is it only the words that I have to add there? I wanted to add sentences will that work if I add sentences in db/extra.txt file

**Comment by nshmyrev** [comment]
Yes, it will work

**Comment by 123srikanth** [comment]
Thank you @nshmyrev
