### ISSUE TITLE
en-us Model downloads broken

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [alphacep/vosk-api#799]
Trying to download en-us models do nothing; Downloading speaker identification model does work.

**Comment by nshmyrev** [comment]
Which URL exactly?

**Comment by TheDrawingCoder-Gamer** [comment]
http://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip

**Comment by nshmyrev** [comment]
Probably you have some certificate issue. You can try to download with curl and share the log

**Comment by TheDrawingCoder-Gamer** [comment]
Looks like it's an error 301 page

**Comment by TheDrawingCoder-Gamer** [comment]
```
PS C:\Users\benha\Documents\GitHub\att-whodoo> curl http://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

**Comment by nshmyrev** [comment]
Should be fixed now with https://github.com/alphacep/vosk-space/commit/5d6ed1f8b5f6d5650a908ff7fd44f59b5471de2c
