### ISSUE TITLE
How can i only get text results ?

### ISSUE THREAD

**Issue by cryptolake** [alphacep/vosk-api#80]
Hi sorry to bother everyone but I couldn't my find my answer elsewhere but i want to get the text results without all the debug info.

**Comment by nshmyrev** [comment]
See

https://github.com/alphacep/vosk-api/blob/master/python/example/test_text.py

also if you want to disable logs add 

```
from vosk import SetLogLevel
SetLogLevel(-1)
```

**Comment by cryptolake** [comment]
Thank you !! so it is json format i dont know how i havent thought of that.
