### ISSUE TITLE
Mac Build - PartialResult slow

### ISSUE THREAD

**Issue by benydc** [alphacep/vosk-api#81]
Hello, I compiled a dynamic library to be used in macOS platform, I had some issues with gfortran but eventually imported the lib:
```
c++ -dynamiclib -o vosk.dylib \
vosk_api.cc \
kaldi_recognizer.cc \
spk_model.cc \
model.cc \
-I/${KALDI_ROOT}/src \
-I/${KALDI_ROOT}/tools/openfst/include \
-std=c++11 -O3 \
/${KALDI_ROOT}/src/online2/kaldi-online2.a \
/${KALDI_ROOT}/src/decoder/kaldi-decoder.a \
/${KALDI_ROOT}/src/ivector/kaldi-ivector.a \
/${KALDI_ROOT}/src/gmm/kaldi-gmm.a \
/${KALDI_ROOT}/src/nnet3/kaldi-nnet3.a \
/${KALDI_ROOT}/src/tree/kaldi-tree.a \
/${KALDI_ROOT}/src/feat/kaldi-feat.a \
/${KALDI_ROOT}/src/lat/kaldi-lat.a \
/${KALDI_ROOT}/src/hmm/kaldi-hmm.a \
/${KALDI_ROOT}/src/transform/kaldi-transform.a \
/${KALDI_ROOT}/src/cudamatrix/kaldi-cudamatrix.a \
/${KALDI_ROOT}/src/matrix/kaldi-matrix.a \
/${KALDI_ROOT}/src/fstext/kaldi-fstext.a \
/${KALDI_ROOT}/src/util/kaldi-util.a \
/${KALDI_ROOT}/src/base/kaldi-base.a \
/${KALDI_ROOT}/tools/openfst/lib/libfst.a \
/${KALDI_ROOT}/tools/openfst/lib/libfstngram.a \
/${KALDI_ROOT}/tools/OpenBLAS/libopenblas.a \
./gfortran.5.dylib \
-lstdc++
```

I had to copy the gfortran .dylib and change the ID to @rpath and along with it's depended libraries.

When I run the vosk speech recognition in swift takes about 2s until I see the result, I'm not sure if the issue is with the audio data or the lib built. I measured the time process and swift shows me it was processed in milliseconds...

this is my code in swift for recognizer:

```swift
    func recognize(data: Data) {
        let ptr = (data as NSData).bytes.assumingMemoryBound(to: Int8.self)
        
        let acceptResult = vosk_recognizer_accept_waveform(recognizer, ptr, Int32(data.count))
        
        let result: UnsafePointer<Int8>
        
        if acceptResult > 0 {
            result = vosk_recognizer_result(recognizer)!
        } else {
            result = vosk_recognizer_partial_result(recognizer)!
        }
        
        let resultString = String(validatingUTF8: result)!
        
        let text = getTextFromResult(resultString)
        
        if !text.isEmpty {
            delegate?.didRecognizeSpeech(text)
        }
    }
```

**Comment by nshmyrev** [comment]
Openblas is most resource-intensive thing. Maybe you compiled it without optimization. You need to find a way to profile the app on osx to figure out what is slow. Like http://iosbrain.com/blog/2018/11/24/using-xcode-instruments-time-profiler-template-to-optimize-swift-code/ should help.

**Comment by nshmyrev** [comment]
Btw, Kaldi on osx uses Accelerate framework instead of openblas/gfortran. You should use it too.

**Comment by nshmyrev** [comment]
We have recently pushed an update for python for osx:

Please try and see if it works for you 

https://github.com/alphacep/vosk-api/releases/download/0.3.7/vosk-0.3.7-cp38-cp38-macosx_10_12_x86_64.whl

**Comment by nshmyrev** [comment]
Result on my side:

i7 server 4Ghz
```
time ./test_simple.py test.wav
real	0m1.325s
user	0m1.308s
sys	0m0.064s
```

Macbook pro 13 2.4Ghz
```
real	0m2.922s
user	0m2.752s
sys	0m0.266s
```

More or less reasonable values I think.

**Comment by nshmyrev** [comment]
Feel free to reopen if you have further questions.
