### ISSUE TITLE
Segmentation fault (core dumped) when finetune LM

### ISSUE THREAD

**Issue by Asma-droid** [alphacep/vosk-api#815]
Hello,

I'am trying to finetune a LM or a personalized model. It worked well until the last two weeks.

Today, i have got the problem of Segmentation fault. More precisely i have got that 

LOG (VoskAPI:ReadDataFiles():model.cc:206) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:209) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0149479 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:233) Loading i-vector extractor from /srv/nas_data/asma-kaldi/egs/multi_database_french_model/s5/CommonVoice_french_Vosk_Model_final/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:263) Loading HCLG from /srv/nas_data/asma-kaldi/egs/multi_database_french_model/s5/CommonVoice_french_Vosk_Model_final/model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:278) Loading words from /srv/nas_data/asma-kaldi/egs/multi_database_french_model/s5/CommonVoice_french_Vosk_Model_final/model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:287) Loading winfo /srv/nas_data/asma-kaldi/egs/multi_database_french_model/s5/CommonVoice_french_Vosk_Model_final/model/graph/phones/word_boundary.int
Segmentation fault (core dumped)

I have tried to finetune with a small data but i still have the same problem. I would like to note that i have 126 Go of memory. 

The vosk version i use is 0.3.32

I cannot identify the problem.

**Comment by nshmyrev** [comment]
Share the model

**Comment by nshmyrev** [comment]
In the original issue #791
