### ISSUE TITLE
How to get golang vosk working?

### ISSUE THREAD

**Issue by Techno-Fox** [alphacep/vosk-api#816]
When ever I try to compile it gives the error

```
# github.com/alphacep/vosk-api/go
../../pkg/mod/github.com/alphacep/vosk-api/go@v0.3.36/vosk.go:6:11: fatal error: vosk_api.h: No such file or directory
    6 | // #include <vosk_api.h>
      |           ^~~~~~~~~~~~
compilation terminated.
```

**Comment by nshmyrev** [comment]
You have to run this from vosk-api/go folder so it finds the headers according to the CGO specification in the file. You can follow the details from #708

**Comment by Techno-Fox** [comment]
Thank you for replying so fast. I'll try this

**Comment by Techno-Fox** [comment]
running go get github.com/alphacep/vosk-api/go            
inside the vosk-api/go directory yields this
 `                                                                                                               
/usr/bin/ld: cannot find -lvosk
collect2: error: ld returned 1 exit status
`

**Comment by nshmyrev** [comment]
Thats some progress. You need to download libvosk.so from the releases and put it in src folder.

https://github.com/alphacep/vosk-api/releases/download/v0.3.32/vosk-linux-x86_64-0.3.32.zip

**Comment by Techno-Fox** [comment]
That works. Thank you. Though wouldn't it make sense to include the libvosk.so by default? (Correct me, if I'm wrong)

**Comment by nshmyrev** [comment]
In general I'm not happy with cgo process, as discussed in the issue linked above, hopefully we will improve one day.

**Comment by Techno-Fox** [comment]
One can hope. I was trying this, as I'm currently working a project in python, and if for whatever reason I should need to rewrite it to a compiled language I was looking at Go, and Rust. I've ran into some issues on the rust side (https://github.com/shakacode/vosk-rs) with the build script, though they are working on that. I wanted to see how I would get the project started in Go. Thank you for your help.

**Comment by Techno-Fox** [comment]
And here's the hope python can be compiled one day, not with pyinstaller, or nuitka, like the python team just comes out with a compiler, that would be nice.

**Comment by shrkx** [comment]
> One can hope. I was trying this, as I'm currently working a project in python, and if for whatever reason I should need to rewrite it to a compiled language I was looking at Go, and Rust. I've ran into some issues on the rust side (https://github.com/shakacode/vosk-rs) with the build script, though they are working on that. I wanted to see how I would get the project started in Go. Thank you for your help.


Have you implemented it using Golang on the Windows system ,I have installed gcc

# github.com/alphacep/vosk-api/go
..\..\..\pkg\mod\github.com\alphacep\vosk-api\go@v0.3.50\vosk.go:7:11: fatal error: vosk_api.h: No such file or directory
    7 | // #include <vosk_api.h>
      |           ^~~~~~~~~~~~
compilation terminated.

![1734578501582](https://github.com/user-attachments/assets/b0d7588b-5e71-4744-9281-7e6ff6945bbf)
