### ISSUE TITLE
Cannot run npm script on Raspberry Pi

### ISSUE THREAD

**Issue by milkywayfarer** [alphacep/vosk-api#818]
The npm demo scripts and index.js give out Dynamic Linking Error: wrong ELF class: ELFCLASS64. How to run Volk on Raspbian and try its functions?

OS: Raspbian
NPM and Node.js: latest

**Comment by nshmyrev** [comment]
Hi. This needs work. We need to add libvosk rpi binary into npm package. Originally tracked at #620, lets discuss there.
