### ISSUE TITLE
pip does not have the latest update

### ISSUE THREAD

**Issue by chard4** [alphacep/vosk-api#82]
pip version: 20.1
python version: 3.7

When trying to run the test_simple.py example, I get an error that says:
ImportError: cannot import name 'SetLogLevel' from 'vosk'

If I look in the __init__.py of the installed vosk, it indeed does not have SetLogLevel.

Is the only way to get the new logging feature to build from source?

**Comment by nshmyrev** [comment]
Let me upload this new version.

**Comment by nshmyrev** [comment]
Fixed now, version 0.3.7 is uploaded. Please update!
