### ISSUE TITLE
Kaldi OpenBLAS doesn't produce liblapack.a, libblas.a, or libf2c.a

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [alphacep/vosk-api#820]
(Sorry if this has been answered/an easy question, I couldn't find any issues on kaldi or vosk related to this)
running `sudo make PREFIX=$(pwd)/install USE_LOCKING=1 USE_THREAD=0 all install` in the OpenBLAS folder produced by kaldi does not produce the required .a files, which is required by vosk thus making vosk compilation not work. 
Vosk Compilation: 
`KALDI_ROOT="$HOME/Documents/github/kaldi" make -j 8`
https://gist.github.com/TheDrawingCoder-Gamer/793923d7e21d377cb2298e3021e1805d

**Comment by nshmyrev** [comment]
We require openblas-clapack, not just openblas:

https://github.com/alphacep/vosk-api/blob/64dfc65d51c62290c8ab1dd14fe58f51841c6ccb/travis/Dockerfile.manylinux#L21

**Comment by TheDrawingCoder-Gamer** [comment]
Oh ok...  The docker creates C++ lib in the process of making python correct? I want to get the C++ api to write bindings for a different language.

**Comment by nshmyrev** [comment]
You can run docker commands yourself, you can also download prebuilt libvosk.so file from releases.

**Comment by TheDrawingCoder-Gamer** [comment]
the prebuilt ones 😐  oh ok

**Comment by F3d3Dr0** [comment]
> We require openblas-clapack, not just openblas:
> 
> https://github.com/alphacep/vosk-api/blob/64dfc65d51c62290c8ab1dd14fe58f51841c6ccb/travis/Dockerfile.manylinux#L21

This command not work for me.... where is the  prebuilt libvosk.so?

**Comment by nshmyrev** [comment]
> This command not work for me.... where is the prebuilt libvosk.so?

here:

https://github.com/alphacep/vosk-api/releases/tag/v0.3.45

for example

https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-linux-x86_64-0.3.45.zip
