### ISSUE TITLE
Windows static library

### ISSUE THREAD

**Issue by APT64** [alphacep/vosk-api#821]
Hello, is there an opportunity to compile a .lib library in this solution? If so, what tools should I use / is there a ready-made library? Sorry for my poor English, would it be convenient for you to switch to Russian?

**Comment by nshmyrev** [comment]
> Hello, is there an opportunity to compile a .lib library in this solution?

 You can convert prebuilt dll from releases to an import file like here:

https://stackoverflow.com/questions/9360280/how-to-make-a-lib-file-when-have-a-dll-file-and-a-header-file

see also

https://stackoverflow.com/questions/27824102/how-do-import-libraries-work-and-why-doesnt-mingw-need-them

If you build from source you can add importlib option to dump .dll.a for linking

Also related issue #381

> Sorry for my poor English, would it be convenient for you to switch to Russian?

Да, конечно.

**Comment by APT64** [comment]
Хотел уведомить Вас, что на текущий момент сборка win и win32 через докер не работает. Не существует такого брэнча, а также устарел ./configure. На счет импортов сейчас попробую)

**Comment by nshmyrev** [comment]
Исправил и добавил implib тоже в c32099705f66fb632dfae6a20ca2e185bce542ed
