### ISSUE TITLE
Proper nouns should have a capital letter as first letter

### ISSUE THREAD

**Issue by O2Pri** [alphacep/vosk-api#822]
VOSK recognises several proper nouns but when they are transcribed all their letters are lowercase instead of having a capital letter as first letter. Encountered in English and French.
For instance:
  - elizabeth --> Elizabeth
  - richard --> Richard
  - london --> Londres
  - paris --> Paris

**Comment by nshmyrev** [comment]
Hi. Thank you for reporting. We have an issue about it #152

We actually released the models for recasepunc already, you can find them on https://alphacephei.com/vosk/models and in the original recasepunc page.  They work fine, not just fully integrated.
