### ISSUE TITLE
Transcribe mp3 into python variable 

### ISSUE THREAD

**Issue by Pavlinchen** [alphacep/vosk-api#825]
Hi there,
I'm trying to create a transcribing tool in python (basically "understanding" said words of a .mp3 and saving the text to a python variable).
Unfortunately I can't seem to get  just the clean output of the file due to EndOfSpeech.
So it just throws me parts of the transcription.
How can I do/fix that?

Thank you very much in advance!

**Comment by nshmyrev** [comment]
Try like this: https://github.com/alphacep/vosk-api/blob/master/python/example/test_srt.py

Instead of adding every line to srt, add it to a string.

**Comment by Pavlinchen** [comment]
Hi Mate,
that worked!

Thank you very much for your help, appreciate it!
Have a good one and stay healthy!
