### ISSUE TITLE
Memory leak for very long stream

### ISSUE THREAD

**Issue by nshmyrev** [alphacep/vosk-api#83]
As reported by Sebastian Dunnink

i've been trying out your vosk api and it's working great so far, very
easy to install and use. however i came across one problem, which is
that after about 20 seconds of runtime (a script based on your
microphone example) it uses up one more megabyte of ram. i found it by
chance while trying to understand why it stopped after several hours
of runtime. below is my script, i run it inside a screen instance.

**Comment by MikeyBeez** [comment]
You need to close the stream.

**Comment by dpny518** [comment]
I want to leave the stream open indefinitely, my goal is to use the asr as wake word system, and when it recognizes certain words trigger an action. 
Any suggestions on how to use offline asr with continuous stream running indefinitely and avoid memory leaks?

**Comment by MikeyBeez** [comment]
Take a look at my program, Juliet.  https://github.com/MikeyBeez/Juliet

**Comment by dpny518** [comment]
@MikeyBeez thank you, i checked it out, it seems you just check the output to see if a string is in it.
```
 while True:
        # listen for command. Speech to text listener logic is called from inside the myCommand function.
        output = mycommand.myCommand()[3:]
        # Remember,  the mycommand function takes in 
        # audio from the microphone and returns text.
        # Therefore, the "output" variable is text.
        if 'juli' in output:
            print('Julia responds:\n')
```

But I don't see any code for resetting, or handling memory issues

**Comment by MikeyBeez** [comment]
import pyaudio
from vosk import Model, KaldiRecognizer

def myCommand():
    # "listens for commands"
    # We imported vosk up above.
    p = pyaudio.PyAudio()
    stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=8000)
    stream.start_stream()
    model = Model("model-en")
    rec = KaldiRecognizer(model, 16000)
    while True:
        data = stream.read(2000)
        if len(data) == 0:
            break
        if rec.AcceptWaveform(data):
        #print(rec.Result())
        # I commented out this line and added the 3 lines below
            myResult = rec.Result()
            myList = myResult.split("text")
            command = myList[1]
            stream.stop_stream()
            stream.close()
            p.terminate()
            return command

**Comment by MikeyBeez** [comment]
I rewrote this:  from vosk import Model, KaldiRecognizer

import pyaudio

p = pyaudio.PyAudio()
stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=8000)

model = Model("model-en")
rec = KaldiRecognizer(model, 16000)

while True:
    stream.start_stream()
    data = stream.read(2000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        #print(rec.Result())
        # I commented out this line and added the 3 lines below
        myResult = rec.Result()
        myList = myResult.split("text")
        print(myList[1])
        stream.stop_stream()

**Comment by nshmyrev** [comment]
This should be fixed in commit https://github.com/alphacep/vosk-api/commit/ee9bacb092d397add2c887cb5b2f6d7938247fa5 and version 0.3.8
