### ISSUE TITLE
start and end times are not matching actual wav file

### ISSUE THREAD

**Issue by padmalcom** [alphacep/vosk-api#833]
Hi, I'm using vosk with python, version 0.3.32. When I have vosk analyze my wav file on word level, I get start and end times that do not match the wav file. Here is the final result. The wav is only 4 seconds long.

```
{
  "result" : [{
      "conf" : 1.000000,
      "end" : 5.889250,
      "start" : 5.289250,
      "word" : "heute"
    }, {
      "conf" : 1.000000,
      "end" : 6.489250,
      "start" : 5.979250,
      "word" : "ist"
    }, {
      "conf" : 1.000000,
      "end" : 7.299250,
      "start" : 6.489250,
      "word" : "freitag"
    }] ...
}
```

Attached you find my wav file (had to zip it for github).

[meeting.zip](https://github.com/alphacep/vosk-api/files/7950376/meeting.zip)

Thanks for your help.

**Comment by nshmyrev** [comment]
Most likely you initialized recognizer at 8khz but the audio is 16khz. So it doubles the times. Check your code, the recognizer constructor.

**Comment by padmalcom** [comment]
Hi, I initialized with recognizer with a samplerate of 16000. So this should not be the error.

I tried to find a specification of the properties of a wav file that is expected by vosk but I didn't find any. Can you have a look if there is something wrong (e.g. bitrate?)?

![grafik](https://user-images.githubusercontent.com/3961950/151368258-ed6e1b3e-b9db-4e41-95c2-d127dc86bba5.png)

**Comment by padmalcom** [comment]
Okay I found out what my issue was. I was using the KaldiRecognizer multiple times and switched between SetWords true and false. I used the Reset() function but it did not seem to reset the recognizer completely. So when I initialized the recogniter, the start and end times are correct.

**Comment by nshmyrev** [comment]
Ok, great. Reset is not supposed to reset the times, it only resets current results. To drop the one one have to call FinalResult or reinit the recognizer.
