### ISSUE TITLE
Is noise filtering possible in python?

### ISSUE THREAD

**Issue by vadysa** [alphacep/vosk-api#834]
Hello, I have strong noises on my audio recordings and I can’t recognize words, are there any solutions to this problem? (I have a small dictionary of words that need to be recognized)

**Comment by nshmyrev** [comment]
What kind of noises. It is better to provide an example.

**Comment by vadysa** [comment]
This noise is always there.
[1.zip](https://github.com/alphacep/vosk-api/files/7964119/1.zip)

**Comment by nshmyrev** [comment]
What is it, a factory or what?

**Comment by vadysa** [comment]
Yes, this is a factory, the sound is stationary.

**Comment by nshmyrev** [comment]
Ok. For factory recording there are noise cancelling microphones, they reduce the noise significantly.

**Comment by vadysa** [comment]
Is it possible to programmatically remove noise?

**Comment by vadysa** [comment]
[An example of how I think it is possible to implement this.txt](https://github.com/alphacep/vosk-api/files/7964221/An.example.of.how.I.think.it.is.possible.to.implement.this.txt)

**Comment by nshmyrev** [comment]
Yes, you can use any wave-u-net packages, like https://github.com/facebookresearch/denoiser. Ideally you want to tune them.

**Comment by vadysa** [comment]
Yes, this looks like what I need. Thanks a lot.

**Comment by vadysa** [comment]
Just in case, what are the noise-cancelling microphones. Can you provide examples or advice?

**Comment by tlt-dev** [comment]
Personnaly, I'm using the ReSpeaker Mic Array v2.0 that is quite good in noisy environment with built-in algorithms for speech recognition, including noise suppression
https://wiki.seeedstudio.com/ReSpeaker_Mic_Array_v2.0/

**Comment by farooqkz** [comment]
I think this issue must get closed.
