### ISSUE TITLE
Is it ok for clients to auto-download models from your server?

### ISSUE THREAD

**Issue by maxkrieger** [alphacep/vosk-api#838]
I have an app with a few thousand Android users. I'm looking forward to adopting Vosk, but wondering what the best practice is with supporting multiple models.
I want to make it possible to download other languages on the fly, and not bundle the English model in the app, to prevent redundancy with say German. But I don't want to freeload off of your bandwidth - can I hotlink the app to download from https://alphacephei.com/vosk/models, or would you prefer some other method?

**Comment by nshmyrev** [comment]
We are planning to make download a common way to distribute models as in https://github.com/alphacep/vosk-android-service/tree/master/app/src/main/java/org/vosk/service. However, given we might pay for the traffic for huge volumes (> 10Tb of data), we are also not against if you host models in another place. There is no strong requirements here.

Maybe later we can think of CDN and you can rely on our service.

**Comment by maxkrieger** [comment]
Fantastic, thanks - might self host for ya. Feel free to close this or leave it open till you develop that feature/cdn.

**Comment by nshmyrev** [comment]
We just pushed in autodownload, same as #11 

Commit is fb4ed21a7fc85b5122036404116102680549f72a

**Comment by maxkrieger** [comment]
thanks so much!
