### ISSUE TITLE
missing latest version 0.3.32 for armv6l

### ISSUE THREAD

**Issue by freddii** [alphacep/vosk-api#840]
The latest version i get for my pi1 is:
vosk-0.3.15-cp37-cp37m-linux_armv6l.whl

But for this version the test_simple.py fails with:
AttributeError: 'KaldiRecognizer' object has no attribute 'SetWords'

in #595 its recommended to upgrade vosk to version version 0.3.30 but thats not possible for armv6l.whl

**Comment by nshmyrev** [comment]
We decided to drop support for armv6l, it is not powerful enough anyway to run the engine.

**Comment by freddii** [comment]
ok so i will keep using the latest supported version of the example with:

git reset --hard 3e33860c472546bbce501fc847203de6c9976a94
