### ISSUE TITLE
How to get phonemes timing.

### ISSUE THREAD

**Issue by bongblender** [alphacep/vosk-api#842]
I know, how to get word start and end time, but here I want to know , is there any way to get phonemes timing.
Some things Like Home = ho : om : e
Thanks in advance.

**Comment by nshmyrev** [comment]
Same as #687

**Comment by bongblender** [comment]
Thanks a lot..

**Comment by bongblender** [comment]
Is there any further plan to add this option, I am talking about.. something like lowerquality/gentle.

**Comment by nshmyrev** [comment]
No it is not a priority
