### ISSUE TITLE
Please Tell Required System Configuration?

### ISSUE THREAD

**Issue by mukeshbadgujar** [alphacep/vosk-api#848]
Can you please Suggest Best System Configuration need to work on this Project. 

Eg. Vosk Model Building, Model Adaptation etc. 

Please give us System Configuration, required pc, gpu, ram etc.  

Because i can't found it anywhere, and i getting many cuda and gup , memory , ram errors.

**Comment by nshmyrev** [comment]
Nvidia DGX A100 is one of the good:

https://www.nvidia.com/en-us/data-center/dgx-a100/

**Comment by mukeshbadgujar** [comment]
Please Suggest RAM how much GB of RAM Requirement

**Comment by nshmyrev** [comment]
Click on the link and read the specs ;)

**Comment by mukeshbadgujar** [comment]
Ok Sir. thanks for Reply.😊
