### ISSUE TITLE
When testing getting import error: ImportError: cannot import name '_vosk' from 'vosk'

### ISSUE THREAD

**Issue by fsiep** [alphacep/vosk-api#85]
System: Raspberry Pi 4 with 2 GB RAM and 2 GB of swap
OS: Kali Linux 2020.1 64 Bit
Python: v3.7

Installation: pip for vosk did not work. Cloned Github Kaldi repository according to instructions (Project website) and compiled Kaldi.  After successful built, cloned vosk-api from GitHub and build according to instructions (Project website). Everything seem to have compiled fine.

When testing with "test_simple.py" and test.wav (according to website instructions) getting the following error:

Traceback (most recent call last):
  File "test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "/usr/local/lib/python3.7/dist-packages/vosk-0.3.7-py3.7-linux-aarch64.egg/vosk/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/vosk-0.3.7-py3.7-linux-aarch64.egg/vosk/vosk.py", line 13, in <module>
ImportError: cannot import name '_vosk' from 'vosk' (/usr/local/lib/python3.7/dist-packages/vosk-0.3.7-py3.7-linux-aarch64.egg/vosk/__init__.py)

Any help/feedback/constructive comment is greatly appreciated

**Comment by nshmyrev** [comment]
pip doesn't support aarch64. Please run

       ldd /usr/local/lib/python3.7/dist-packages/vosk-0.3.7-py3.7-linux-aarch64.egg/vosk/ 

and provide the output.

You can also try 


     pip3 install https://github.com/alphacep/vosk-api/releases/download/0.3.7/vosk-0.3.7-cp37-cp37m-linux_aarch64.whl

It is the precompiled version

**Comment by fsiep** [comment]
Here is the output of the ldd command:

ldd: /usr/local/lib/python3.7/dist-packages/vosk-0.3.7-py3.7-linux-aarch64.egg/vosk/: No such file or directory

I see the egg file and here is the content:

Archive:  /usr/local/lib/python3.7/dist-packages/vosk-0.3.7-py3.7-linux-aarcegg
  Length      Date    Time    Name
---------  ---------- -----   ----
      741  2020-05-04 14:38   EGG-INFO/PKG-INFO
      147  2020-05-04 14:38   EGG-INFO/SOURCES.txt
        1  2020-05-04 14:38   EGG-INFO/dependency_links.txt
       14  2020-05-04 14:41   EGG-INFO/native_libs.txt
       11  2020-05-04 14:38   EGG-INFO/top_level.txt
        1  2020-05-04 14:41   EGG-INFO/zip-safe
       65  2020-05-04 14:37   vosk/__init__.py
  7789008  2020-05-04 14:41   vosk/_vosk.so
     3615  2020-05-04 14:38   vosk/vosk.py
      234  2020-05-04 14:41   vosk/__pycache__/__init__.cpython-37.pyc
     5210  2020-05-04 14:41   vosk/__pycache__/vosk.cpython-37.pyc
---------                     -------
  7799047                     11 files

If I unzip the egg file and run ldd against _vosk.so I get this output:

        linux-vdso.so.1 (0x0000007fb2582000)
        libgfortran.so.5 => /lib/aarch64-linux-gnu/libgfortran.so.5 (0x0000007fb1c5a000)
        libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007fb1a83000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007fb19d9000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007fb19b4000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007fb1845000)
        /lib/ld-linux-aarch64.so.1 (0x0000007fb2554000)

BTW thank you for the quick reply!

**Comment by nshmyrev** [comment]
Please remove old vosk files and try install with 

KALDI_ROOT=/home/user/kaldi python3 ./setup.py install --user --single-version-externally-managed --root=/

**Comment by fsiep** [comment]
That did do the trick. I only had to rename the folder 'model-en" to 'model' and the example file works now on the Raspberry Pi4. THANK YOU!
