### ISSUE TITLE
Proper way to generate srt file?

### ISSUE THREAD

**Issue by ls-milkyway** [alphacep/vosk-api#850]
Not much in to coding....but replaced last 3 lines in the code of test_srt.py:
`subtitle = open('subtitle.srt', 'w')
print ((srt.compose(transcribe())), file = subtitle)
subtitle.close()`
to generate subtitle.srt file.....is it the correct way? Further would like to know:
1) Is ffmpeg command produces optimized output ( I mean source file's attribute & quality is not hampered in anyway)?
2) _Is there a way to remove silence from video file to generate the srt file while preserving the time-stamps....this will tremendously decrease the transcribing time._

**Comment by nshmyrev** [comment]
> Is ffmpeg command produces optimized output ( I mean source file's attribute & quality is not hampered in anyway)?

Yes.

> Is there a way to remove silence from video file to generate the srt file while preserving the time-stamps....this will tremendously decrease the transcribing time.

Its better to keep things as is.

**Comment by ls-milkyway** [comment]
Actually, my work is partly related to generate subtitle files for large videos (~ 3 hours)....so I guess removing silence will be a better option...putting ideas based [on this post](https://towardsdatascience.com/generating-subtitles-automatically-using-mozilla-deepspeech-562c633936a7) ...it's main project at github called [Autosub](https://github.com/abhirooptalasila/AutoSub)

Will compare the 2 ...but I guess vosk has more models in various languages ....._please shed some light:_ if I find some deep-search models ...better than vosk...then how can I transform them to vosk?....or any links where I can put some time to improve existing models or start  ...say a finnish model (currently not in vosk) from scratch?
Thanks.

**Comment by nshmyrev** [comment]
>  if I find some deep-search models
 
 it is extremely unlikely
 
 > then how can I transform them to vosk?

You can not transform models between toolkits.

> or any links where I can put some time to improve existing models or start ...say a finnish model (currently not in vosk) from scratch?

Model training is covered in https://alphacephei.com/vosk/models#training-your-own-model

**Comment by ls-milkyway** [comment]
Hmm..
But I strongly believe there is huge scope to improve audio inputs by using FFMPEG. Google [has documentation](https://cloud.google.com/speech-to-text/docs/optimizing-audio-files-for-speech-to-text) regarding it...plus users are curious to know [ways to do it](https://superuser.com/questions/733061/reduce-background-noise-and-optimize-the-speech-from-an-audio-clip-using-ffmpeg).

Scope of models becomes very less if inputs are not up to the mark.

Tried vosk's Portuguese model with background music & mur-mur  ...did well...but completely missed many dialogues (20-30%)...in the final generated srt file (also I don't understand why would one like to have a srt output on console...as they are meant to be the files that are always used with video??)

**Comment by ls-milkyway** [comment]
Hmm...sorry for typo "deep-search" instead of deep-speech.

I believe the scope of improvement of input audio is very high....and very important as models will only output depending upon input.....hence suggest improving input audio ...I mean can [google's optimization guide ](https://cloud.google.com/speech-to-text/docs/optimizing-audio-files-for-speech-to-text) OR [general optimization](https://superuser.com/questions/733061/reduce-background-noise-and-optimize-the-speech-from-an-audio-clip-using-ffmpeg) help me in any way?

I generated a srt file using vosk's Portuguese model...output is ok ...but 20% of dialogues failed to transcribe.....may be due to the presence of background music, noise or multiple chit-chat.

**Comment by nshmyrev** [comment]
We have big Portuguese models, not sure if we release them soon. Finnish actually too.

**Comment by ls-milkyway** [comment]
ok ....one last question....does optimizing input audio will help me any way? If yes, then plz provide link to the guide...thanks.

**Comment by nshmyrev** [comment]
> does optimizing input audio will help me any way

https://cloud.google.com/speech-to-text/docs/optimizing-audio-files-for-speech-to-text 

is ok

**Comment by ls-milkyway** [comment]
> Not much in to coding....but replaced last 3 lines in the code of test_srt.py: `subtitle = open('subtitle.srt', 'w') print ((srt.compose(transcribe())), file = subtitle) subtitle.close()` to generate subtitle.srt file.....is it the correct way? 

I was trying turkish model....and:
On line 54 i.e "print ((srt.compose(transcribe())), file = subtitle)" ...added to test.srt.py ...as stated above....I am getting error:

Traceback (most recent call last):
  File "test_srt.py", line 54, in <module>
    print ((srt.compose(transcribe())), file = subtitle)
  File "*:\****\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 38: character maps to <undefined>

Most probably character encoding problem....if I use "print ((srt.compose(transcribe())).encode("utf-8"), file = subtitle)"....then there is no error ..but srt file generated is full with non-recognized characters.....plz suggest.
