### ISSUE TITLE
adding custom model tdnn_lstm kaldi for demo android fail?

### ISSUE THREAD

**Issue by mlexplore1122** [alphacep/vosk-api#857]
Hi there,
I have open issuse in [vosk-android-demo](https://github.com/alphacep/vosk-android-demo) but don't have anyone reply, so I open new issue here. Link my issue in vosk [issuse about add custom model in android demo failed](https://github.com/alphacep/vosk-android-demo/issues/177)
Additional info, I have know about change folder model name, and setting name folder in gradle. 
![a303da0a3fcbf395aada](https://user-images.githubusercontent.com/68678036/154408050-faccece0-a868-4a27-88ae-32a38ab89b9f.jpg)

![9074af0c48cd8493dddc](https://user-images.githubusercontent.com/68678036/154408031-a1c8d1ec-73ef-4bef-b2d0-9ef080699581.jpg)
but it's still failed: 
![116223a33e63f23dab72 (1)](https://user-images.githubusercontent.com/68678036/154408109-fa4311f2-65f4-482d-869a-3e4f5b517d6f.jpg)

Can you suggest what wrong with my setup. Thank you.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-android-demo/issues/177, I replied there.
