### ISSUE TITLE
Grammar format in Recognizer: does formatting matter?

### ISSUE THREAD

**Issue by portsample** [alphacep/vosk-api#859]
Both this format,

    Recognizer rec = new Recognizer(model, 16000, "[\"one\",\"two\",\"three\",\"four\",\"red\",\"[unk]\"]");

and this format,

    Recognizer rec = new Recognizer(model, 16000, "[\"one two three four red\",\"[unk]\"]");

will work with the recognizer. 
Which is better and why? Thanks in advance.

**Comment by nshmyrev** [comment]
Those are not formats but different phrase lists. In first phrase list you have six phrases of a single words, in second you have one phrase of five words.

**Comment by portsample** [comment]
The words are keywords that are recognized by the application and then parsed accordingly. Is there a reason why each keyword should be an individual phrase (first example), or can all keywords be in the same phrase? Does it matter? Thanks.

**Comment by nshmyrev** [comment]
It depends on what phrase you want to recognize - individual words or a single phrase.

**Comment by portsample** [comment]
Okay. I see your point. Thanks.

**Comment by nshmyrev** [comment]
We need to put this in documentation
