### ISSUE TITLE
Speaker Identification

### ISSUE THREAD

**Issue by verloka** [alphacep/vosk-api#86]
У вас в ридми написано:

```
8. Позволяет идентифицировать говорящего
```

Есть примеры как это осуществить?

**Comment by nshmyrev** [comment]
https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py

**Comment by verloka** [comment]
> https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py

Что такое spk_model_path = "model-spk" ? Что это за spk-model?

**Comment by verloka** [comment]
> https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py

Вот тут хранятся отпечатки людей:
https://github.com/alphacep/vosk-api/blob/944dc87531729f4c99e27e8ea412cbf66da40f93/python/example/test_speaker.py#L33

А вот тут сопоставляется слово с отпечатком
https://github.com/alphacep/vosk-api/blob/944dc87531729f4c99e27e8ea412cbf66da40f93/python/example/test_speaker.py#L35

Верно я понимаю?

**Comment by nshmyrev** [comment]
Да.

**Comment by verloka** [comment]
> Да.

Еще вопрос, в этом массиве несколько отпечатков или этот массив и есть отпечаток (одного человека)?

**Comment by nshmyrev** [comment]
Массив и есть отпечаток.

**Comment by verloka** [comment]
> Массив и есть отпечаток.

каким образом можно сгенерировать этот отпечаток?

**Comment by nshmyrev** [comment]
Распознать файл, получить отпечаток из результата.

**Comment by verloka** [comment]
> Распознать файл, получить отпечаток из результата.

Допустим, есть файл в котором монолог человека А, получаем отпечаток.
Есть второй файл в котором диалог человека А и Б.
Возможно ли отличить человека А из этого диалога имея его отпечаток, полученный из файла с монологом?

т.е. получить реплики человека А

**Comment by nshmyrev** [comment]
> Возможно ли отличить человека А из этого диалога имея его отпечаток, полученный из файла с монологом?

Да, каждую фразу сравниваете с отпечатком.

**Comment by verloka** [comment]
> > Возможно ли отличить человека А из этого диалога имея его отпечаток, полученный из файла с монологом?
> 
> Да, каждую фразу сравниваете с отпечатком.

Спасибо
