### ISSUE TITLE
CUDA based images, CPU is still a bottleneck, is this expected?

### ISSUE THREAD

**Issue by modjke** [alphacep/vosk-api#860]
CUDA-enabled images (not a batch-gpu) build from source on Win10 WSL2 Ubuntu 20
Model: [vosk-model-en-us-0.22](https://alphacephei.com/vosk/models/vosk-model-en-us-0.22.zip) 
Spec: i7 2700K / 1080TI 11G
Testing by concurrenlty pushing PCM data via websocket (PCM mono 8k wav file)
CPU utilization reaches 100%, while CUDA is 18% at most.
Is this expected or am i doing something wrong?

**Comment by nshmyrev** [comment]
Yes, it is expected.
