### ISSUE TITLE
Unexpected behaviour with BatchRecognizer

### ISSUE THREAD

**Issue by arkadybag** [alphacep/vosk-api#861]
_All experiments based on `docker image alphacep/kaldi-en-gpu`_

In case the size of chunk for `BatchRecognizer` is more than the limit (which we don't know), `.Result(batch_id)` returns only part of recognized words.
But the same works good for `KaldiRecognizer`

[Example audio](https://stitcher-injected.simplecastaudio.com/c80b603a-35e1-4531-9f82-ac7d54df004d/episodes/e26d676f-9a46-48b1-bd7c-346e07806779/audio/128/default.mp3/default.mp3_4a6f84d72d1b237f8d128e8a8c88fe26_37619070.mp3?aid=rss_feed&awCollectionId=c80b603a-35e1-4531-9f82-ac7d54df004d&awEpisodeId=e26d676f-9a46-48b1-bd7c-346e07806779&feed=jZLi00b4&hash_redirect=1&x-total-bytes=37619070&x-ais-classified=streaming&listeningSessionID=0CD_382_47__d7bdc9c2f30f66f213ead06afaafd6e80177dd55)

**Comment by arkadybag** [comment]
_Command to convert mp3 to wav that I used:_ 
`ffmpeg -i  FILE.mp3 -ar 16000 -ac 1 default.wav`

**Test script:**

```
import json
import math
import wave

from vosk import BatchRecognizer
from vosk import GpuInit
from vosk import KaldiRecognizer
from vosk import Model

GpuInit()

wf = wave.open("default.wav", "rb")
batch_size = math.ceil(wf.getnframes() / 10)

# 1/10 of all audio
# suppose that this huge fragment should be one big batch
data = wf.readframes(batch_size)


def batch():
    rec = BatchRecognizer()
    rec.AcceptWaveform(1, data)
    rec.FinishStream(1)
    rec.Wait()
    return json.loads(rec.Result(1))["text"]


def kaldi():
    model = Model("model")
    rec = KaldiRecognizer(model, 16000)
    rec.AcceptWaveform(data)
    return json.loads(rec.FinalResult())["text"]


batch_text = batch()
kaldi_text = kaldi()

print("batch text:", batch_text)
print("kaldi text:", kaldi_text)

assert batch_text == kaldi_text
```



**Output:**

**batch text:** 
>for context this was recorded on monday december twenty first twenty twenty on this episode we talk a bit about trump's pardon power and how he might use it on the following tuesday and wednesday of the same week he issued forty one parton's including ones for roger stone paul manafort george papadopoulos his own laws father charles kushner in for preta

**kaldi text:** 
>for context this was recorded on monday december twenty first twenty twenty on this episode we talk a bit about trump's pardon power and how he might use it on the following tuesday and wednesday of the same week he issued forty one pardons including ones for roger stone paul manafort george papadopoulos his son in law's father charles kushner and for pretend soldiers who work for blackwater who were convicted of killing fourteen innocent people without provocation in baghdad we obviously didn't know about them at the time of the recording but we talked about anticipating these kinds of disgusting pardons there will be more to come i am sure okay on with the show so on december eleventh the united states supreme court considered some extraordinary claims about their two thousand and twenty election and it turns out they didn't want to hear them at all so this is the case of texas versus pennsylvania now if you remember and there's a lot that's been happening in december but in the first week of december the state of texas filed a lawsuit directly at the united states supreme court they challenge the election procedures in four swing states that biden won georgia michigan pennsylvania and wisconsin no texas was asking the supreme court to stop these four states from casting their electoral votes for biden instead they wanted to have the state legislatures decide they'll understand what texas is asking the supreme court to do in this case to have the supreme court throw out millions of lawfully cast votes you might remember what trump said right after the death of justice ruth bader ginsburg i think this will end up in the supreme court and i think it's very important we have nine justices and of course he got his wish and justice amy coney barrett was nominated and confirmed just before election day now in the case of texas vs pennsylvania the supreme court receive more than a dozen amicus or friend of the court briefs these are briefs filed by parties who are not directly involved in the case but went away in an important supreme court case it's common to see dozens and dozens of such briefs but if you consider what the claims are in this case and what texas was asking for the friend of the court briefs are alarming they include a brief filed in support of texas by more than one hundred house republicans and a brief in support of texas filed by seventeen republican state attorneys general those are the top lawyers representing the states what were they asking for they were all asking for millions of lawfully cast votes to be thrown out and the attorney general for pennsylvania one of the defendants states in this lawsuit said in his reply that the texas request to the supreme court was nothing less than a seditious abuse of the judicial process but on december eleventh the supreme court in a brief unsigned order said the state of texas' motion for leave to file a bill of complaint is denied for lack of standing under article three of the constitution and just two days later trump tweeted the fact that the supreme court wouldn't find standing in an original jurisdiction matter between multiple states and including the president of the states is absurd it is enumerated in the constitution they just chickened out and didn't want to rule on the merits of the case so bad for our country what is that tweet talking about that's a good question i don't even know if trump knows what that tweet is talking about yeah definitely came from his account that he tweeted it but in any event what's original jurisdiction let's start with that we talk about a court's jurisdiction we're talking about the ability or power


**Traceback (most recent call last):
  File "test.py", line 41, in <module>
    assert batch_text == kaldi_text
AssertionError**

**Comment by nshmyrev** [comment]
Because batch recognizer handles the endpointer by itself I believe you have to retrieve the results from result queue multiple times after it ends.

**Comment by arkadybag** [comment]
Yes, you are right. Thanks!
