### ISSUE TITLE
Is it possible to trim the dictionary?

### ISSUE THREAD

**Issue by ArtemRotov** [alphacep/vosk-api#862]
I use a small Russian dictionary, but it has too much vocabulary (for my purposes). Is it possible to somehow trim the dictionary, leaving only certain words in it? If this is possible, do you have any documentation for this? Very thanks!

**Comment by ArtemRotov** [comment]
ok, I found a [solution ](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py) that can help me (probably). Can you tell me what the JSON file should look like for this example? and how to call it instead of directly writing words? sorry for my English :)

**Comment by ArtemRotov** [comment]
Also, could you tell me what the difference is between: 
`recording = KaldiRecognizer(model, 16000, '["oh one two three four five six seven eight nine zero", "[unk]"]')`

and: 
`recording = KaldiRecognizer(model, 16000, '["oh", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "zero", "[unk]"]')`

**Comment by nshmyrev** [comment]
This question answered here:

https://github.com/alphacep/vosk-api/issues/859

**Comment by ArtemRotov** [comment]
Okay, what about the JSON sheet format? How should it look for both cases? and how to connect it? I will be very grateful if you answer.

**Comment by nshmyrev** [comment]
I do not get any of your questions. You'd better clarify.

**Comment by ArtemRotov** [comment]
[This ](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py)example says that you can feed a JSON sheet as input instead of typing the words directly into the script. 
1. What should a JSON sheet look like for this purpose?
2. How do I plug it into a function instead of a set of words:
`recording = KaldiRecognizer(model, 16000, '["oh one two three four five six seven eight nine zero", "[unk]"]')`

**Comment by ArtemRotov** [comment]
@nshmyrev Can I expect to get an answer? Or at least links where I can find the answer.

**Comment by nshmyrev** [comment]
I don't understand what do you mean by "sheet". You'd better write in Russian instead.

**Comment by ArtemRotov** [comment]
@nshmyrev 
I'm sorry.
RU:   В[ этом](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py) примере у вас написано `# You can also specify the possible word or phrase list as JSON list, the order doesn't have to be strict`, но нет примера как это сделать. Я имею большой список слов и не могу вручную записать их таким образом: `rec = KaldiRecognizer(model, wf.getframerate(), '["oh one two three four five six seven eight nine zero", "[unk]"]')` . Можете показать как создать JSON файл с списком используемых слов и подключить его в программу? 

EN:  In [this example](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py), you have written `# You can also specify the possible word or phrase list as JSON list, the order doesn't have to be strict`, but there is no example of how to do this. I have a large list of words and cannot manually write them down like this: `rec = KaldiRecognizer(model, wf.getframerate(), '["oh one two three four five six seven eight nine zero", "[unk]"]')` . Can you show me how to create a JSON file with a list of used words and connect it to the program?

**Comment by nshmyrev** [comment]
There is no problem to create json objects from python program, you can use something like https://stackoverflow.com/questions/19795012/how-to-convert-a-list-of-numbers-to-jsonarray-in-python

**Comment by ArtemRotov** [comment]
@nshmyrev  Thank you :)
