### ISSUE TITLE
Feature request: iOS Build

### ISSUE THREAD

**Issue by normano** [alphacep/vosk-api#863]
I've tried emailing and didn't get a response. I requested an iOS build so I could explore making an ios flutter plugin since it appears that it is not supported in your current flutter repository. If you have instructions for building it, that is also appreciated.

**Comment by nshmyrev** [comment]
Same as #45

**Comment by normano** [comment]
To anyone else looking to get an iOS build, it appears you have to have a commercial application or something on the app store already 😂. Dismissed me over email for wanting a build for a purely personal project for educational purposes. It's weird to explore things apparently for the hardware that you have. These guys need to be clear on what they are looking for when you contact them. i.e. no personal projects.

I asked for build instructions because I figured the onus of the work would be on me so they don't have to take much time for something I can do. Forget wanting to contribute a flutter IOS plugin as a bonus. Why be courteous to people who want to be jerks to you? 🙄

Definitely Hacker news worthy.
