### ISSUE TITLE
More practical information about speaker embeddings

### ISSUE THREAD

**Issue by filippo-d** [alphacep/vosk-api#87]
Hi,
thanks for your great job.
Please could you add some basic info for non-speech scientist about the 'spk' vector returned by Result() function?
I improved the readability merging adjacent texts where the speaker distance is low.
The recognizer sometime retuns data containing speaker embeddings only, no text no words no timing
Please what's the meaning?

**Comment by nshmyrev** [comment]
> Please could you add some basic info for non-speech scientist about the 'spk' vector returned by Result() function?

Sure, a bit later.

> The recognizer sometime retuns data containing speaker embeddings only, no text no words no timing

For short noises it is possible. In such cases speaker vector is not very reliable, you can drop it.

**Comment by nshmyrev** [comment]
Lets track this in issue #99
