### ISSUE TITLE
can I limit the dictionary in C/C++?

### ISSUE THREAD

**Issue by alexribeirodesa** [alphacep/vosk-api#874]
I'm using more than one dictionary (en, es, pt) at same time, and i'd like to limit the recognition dictionary to just the words I need to make it more efficient, but I didn't found how can I do that in C, there any sample or documentation to do that? thanks :)

**Comment by nshmyrev** [comment]
Like https://github.com/alphacep/vosk-api/blob/master/src/vosk_api.h#L130 ?

**Comment by alexribeirodesa** [comment]
here how it works, the last one is a json array string! it very easy :) thx nshmyrev!

`
recognizer = vosk_recognizer_new_grm(model, 16000.0, "[\"hello\", \"word\"]");
`

**Comment by rwst** [comment]
Confirm that it works nicely. Question: does the output adhere to the given grammar? I have seen a different behaviour:
When given the grammar `"ay one", "ay two"` (simplified) it recognizes the spoken `"ay one two"` as `"ay one two"`. Not that it matters much as it can be filtered easily later...

**Comment by nshmyrev** [comment]
> Question: does the output adhere to the given grammar? 

No, you have to filter after recognition

**Comment by alexribeirodesa** [comment]
> Confirm that it works nicely. Question: does the output adhere to the given grammar? I have seen a different behaviour: When given the grammar `"ay one", "ay two"` (simplified) it recognizes the spoken `"ay one two"` as `"ay one two"`. Not that it matters much as it can be filtered easily later...

I really don't know about this as I'm working with simple words, but a issue I has is when I use a big dictionary it just stops working with no errors, it just stop return the results... But this is another issue, I think this thread is closed with my post from feb 28...
