### ISSUE TITLE
Is VoskRecognizer thread safe?

### ISSUE THREAD

**Issue by Yu-Qi** [alphacep/vosk-api#877]
We have some sound-to-text applications whose qps is up to 100. But each of our Vosk model need cpu 1 core & memory 1 GB. We're afraid that the computation resource is not enough.

So we try to create multiple VoskRecognizers and share one model object by go-routine. 
But before starting, we still can't find any document can gurantee that the way is thread safe.
Plz help us ><

**Comment by nshmyrev** [comment]
> But each of our Vosk model need cpu 1 core & memory 1 GB.

Less than that

> But before starting, we still can't find any document can gurantee that the way is thread safe.

It is safe

> is up to 100

GPU server might be an option for you

**Comment by farooqkz** [comment]
If it is thread safe, I suggest that get added to docs somewhere and close this issue.
