### ISSUE TITLE
Adding additional words to KaldiRecognizer at runtime **only** recognizes those words

### ISSUE THREAD

**Issue by jalustig** [alphacep/vosk-api#878]
I am following the example in `test_words.py `and calling the recognizer as such:

 `rec = KaldiRecognizer(model, wf.getframerate(), '["word1","word2","[unk]"]')`

However, when I subsequently run the script, the transcription _only_ contains those words and not any other ones. This of course defeats the purpose. I am getting very good results without setting  the grammar, but I want to be able to specify a few words (mostly names and technical terms) which Vosk would then identify right. Notably, with the grammar it does recognize these words which were a problem before, but then _only_ those words.

**Comment by nshmyrev** [comment]
Yes, this is how it works. You can add words before with compilation scripts

**Comment by jalustig** [comment]
Thanks. I'm a bit confused, I see a few examples where people do something like this but they would only get a few words out if it *only* recognized the words provided at runtime. is there a way to add words at runtime that supplement the grammar/dictionary, instead of totally replacing it?

**Comment by nshmyrev** [comment]
> is there a way to add words at runtime that supplement the grammar/dictionary, instead of totally replacing it

No

**Comment by nshmyrev** [comment]
Same as #725
