### ISSUE TITLE
Vosk-api python Vietnamese model error rate

### ISSUE THREAD

**Issue by nqdlab** [alphacep/vosk-api#879]
Hello, thanks for this great Vosk ASR engine. I'm using the Vietnamese model and want to learn how to lower the error rate. Can someone tell me where to start ? And which project of the current Vietnamese model please?

**Comment by nshmyrev** [comment]
> Can someone tell me where to start?

Start with collecting diverse transcribed speech data from various sources. Youtube is a good candidate. You need at least 1000 hours.

> And which project of the current Vietnamese model please?

We don't have a specific project for the languages, we just released training recipe though: https://github.com/alphacep/vosk-api/tree/master/training

**Comment by nqdlab** [comment]
@nshmyrev thank you for the answer. I will try to learn the training setup. Hope there will be more document updated in README.

**Comment by nqdlab** [comment]
Provide this info for who has the same concern. What I'm looking for is in this link:
https://alphacephei.com/vosk/models
