### ISSUE TITLE
Android: Save the audio stream

### ISSUE THREAD

**Issue by dhamya** [alphacep/vosk-api#880]
Thanks for this amazing repo!

I did not see any flag to optionally record audio stream in the Android APIs. Whats the process to request a feature - just file an issue like this? Here's what I was thinking:

1. Accept a flag to indicate if user wants to store the audio at initialization and store the audio at user specified file loc
2. Have a method/flag that can be called/turned on to save only part of the speech (e.g. a command followed by wake word trigger saving audio until next terminate command received)

I'll be happy to code & contribute such ability - are there instructions on how to setup the Android API test fmwk?

**Comment by nshmyrev** [comment]
> Thanks for this amazing repo!

You are welcome!

> I did not see any flag to optionally record audio stream in the Android APIs.

We have an issue https://github.com/alphacep/vosk-android-demo/issues/16 about that

> Have a method/flag that can be called/turned on to save only part of the speech (e.g. a command followed by wake word trigger saving audio until next terminate command received)

A method to access the audio on result would be great. It cans simply store the data as a buffer and return it in result.

> I'll be happy to code & contribute such ability - are there instructions on how to setup the Android API test fmwk?

It would be great. The build for the jar is done with gradle in this folder:

https://github.com/alphacep/vosk-api/tree/master/android/lib

**Comment by nshmyrev** [comment]
Lets continue this discussion in the original issue above.
