### ISSUE TITLE
[Question] Number to Number instead of text

### ISSUE THREAD

**Issue by merc74** [alphacep/vosk-api#887]
First great work with this project. It works very well.

Is it possible to have the number as number instead of having the number translated to text?
I would like to be able to call 1, 2, 3 and have the number written as 1, 2, 3, and not one, two, three.

**Comment by nshmyrev** [comment]
Thank you. For conversion to numbers you can use postprocessing step like text2num, see https://github.com/alphacep/vosk-api/issues/627
