### ISSUE TITLE
Compilation stops on missing kaldi-online2.a file

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#888]
https://github.com/alphacep/vosk-api/blob/3951834df26fff07a054a701613e2c819aa261d7/src/Makefile#L38

**Comment by ghost** [comment]
make: *** No rule to make target '/home/peter/../public_data/aplikácie/kaldi/src/online2/kaldi-online2.a', needed by 'libvosk.so'.  Stop.

**Comment by nshmyrev** [comment]
Yes, you need to compile Kaldi first

**Comment by nshmyrev** [comment]
Let us know if you have extra questions
