### ISSUE TITLE
libkaldi_jni.so support for 32-bit architecture?

### ISSUE THREAD

**Issue by ammyt** [alphacep/vosk-api#89]
I have noticed that the app would immediately crash on x86 devices, This is probably because there is no libkaldi_jni.so for x86.

Using the x86-64 Library causes `libkaldi_jni.so is 64-bit instead of 32-bit` as expected.
Can this be added?

**Comment by nshmyrev** [comment]
I have added x86 build and also pushed x86 aar to kaldi-android-demo. This problem should be fixed now.
