### ISSUE TITLE
support for context biasing 

### ISSUE THREAD

**Issue by zyb8543d** [alphacep/vosk-api#890]
whether to have a plan for context biasing or hot words, and add score for specified domain word or person name.
like this, https://mp.weixin.qq.com/s/5FLXU-jUjUVcpXtQaJbhfA

**Comment by nshmyrev** [comment]
We have it here:

https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py#L20

**Comment by zyb8543d** [comment]
> We have it here:
> 
> https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py#L20
vosk  for  phrase word list seems different from  the context biasing. I have try  the vosk phrase word list and all rec result from phrase word list. But the context biasing just increase the rec accurate of  words in phrase word list.
for example:
A audio transcribled with  “我买了一个洗面奶”，rec model recgnized the audio as "我买了一个洗面乃"。
with context biasing,  add hot words"洗面奶", the true recgnized  result will be "我买了一个洗面奶"
with vosk  for  phrase word list ["洗面奶","[unk]"]，the true recgnized  result will be “unk unk 洗面奶”

**Comment by v-yunbin** [comment]
@nshmyrev  vosk  for  phrase word list seems different from  the context biasing. I have try  the vosk phrase word list and all rec result from phrase word list. But the context biasing just increase the rec accurate of  words in phrase word list.
for example:
A audio transcribled with  “我买了一个洗面奶”，rec model recgnized the audio as "我买了一个洗面乃"。
with context biasing,  add hot words"洗面奶", the true recgnized  result will be "我买了一个洗面奶"
with vosk  for  phrase word list ["洗面奶","<UNK>"]，the true recgnized  result will be “<UNK><UNK>洗面奶”

**Comment by zyb8543d** [comment]
@nshmyrev A  context biasing realization in https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/context_graph.cc

**Comment by nshmyrev** [comment]
Same as #646 actually
