### ISSUE TITLE
Language Model Adaptation (Large Russian)

### ISSUE THREAD

**Issue by russele7** [alphacep/vosk-api#896]
Dear Nikolay,
First of all thank you very much for really cool product!
Could you please help me.
I want to update (or maybe you call this adapt / compile) large Russian model for my specific texts.
My system is - ubuntu 20.04.4 LTS
I used your manual - https://alphacephei.com/vosk/lm  (points  <Software> and <Update process>)
Also I watched your tutorial - https://www.youtube.com/watch?v=xWUIGUVfOTg&t=2769s

Here is my steps:

Software:
-	phonetisaurus . I installed phonetisaurus for my python3 and checked, that this library can be imported in python code. Also I solved warnings about PATH.  See detailed information in -  **phonetisaurus.txt** and **path.jpeg**
-	SRILM. I followed the instruction - - https://www.youtube.com/watch?v=bd_m5BU2oSc.   In the end I run <make test>  => see result in **srilm_test.txt**
-	Kaldi. I just downloaded repository from github and didn’t make any additional installation.

Update process:
1.	<Download the update package, for example: Russian - https://alphacephei.com/vosk/models/vosk-model-ru-0.22-compile.zip> . Done
2.	<Unpack and properly point to KALDI_ROOT in the path.sh script >. Done. Also please find in attachement my file **path_sh.JPG** and file **kaldi.JPG** (information about location of kaldi folder).
3.	< Add your extra texts into db/extra.txt > I didn’t add. Just want to run pipeline for checking.
4.	< Optionally add manual words phones into db/extra.dic > I didn’t add. Just want to run pipeline for checking.
5.	< Run compile-graph.sh. Update takes about 15 minutes. Watch errors in the process.> Here I got mistakes and really don’t know how to solve it.   File **report.txt**   is in attachement.
Really hope for your help.
[phonetisaurus.txt](https://github.com/alphacep/vosk-server/files/8287349/phonetisaurus.txt)
![path](https://user-images.githubusercontent.com/64725397/158830178-3f281ffc-d689-411e-8eb5-b62eecde957d.JPG)
[srilm_test.txt](https://github.com/alphacep/vosk-server/files/8287372/srilm_test.txt)
![kaldi](https://user-images.githubusercontent.com/64725397/158830660-1cf55677-8a7d-48fa-a15e-29f658939f80.JPG)
![path_sh](https://user-images.githubusercontent.com/64725397/158830964-b7d59d62-e008-4820-a69c-8590322ff7a0.JPG)
[report.txt](https://github.com/alphacep/vosk-server/files/8287391/report.txt)

**Comment by nshmyrev** [comment]
You need to solve problems one by one. For the "not a valid identifier" issue you need to remove space after = in `export KALDI_ROOT= /mnt...` line

**Comment by nshmyrev** [comment]
to solve phonetisaurus issue, update `./dict.py` to `python3 ./dict.py` or check you installed phonetisaurus in python3, not python2.

**Comment by nshmyrev** [comment]
For srilm issue, add SRILM binaries in PATH

**Comment by nshmyrev** [comment]
Let us know if you have extra questions please
