### ISSUE TITLE
Install problem with nodejs on macos

### ISSUE THREAD

**Issue by mshelman11** [alphacep/vosk-api#897]
Similar to an earlier post after cloning repo vosk-api and attempting to run demo/test-simple getting below error. It is looking for .....vosk-api/nodejs/lib/osx-x86_64/libvosk.dylib. There isn't any such lib folder nor any file libyosk.dylib on the computer.

Please help.

Error: Dynamic Linking Error: dlopen(/Users/michaelshelman/vosk/vosk-api/nodejs/lib/osx-x86_64/libvosk.dylib, 2): image not found
    at new DynamicLibrary (/Users/michaelshelman/vosk/vosk-api/nodejs/node_modules/ffi-napi/lib/dynamic_library.js:75:11)
    at Object.Library (/Users/michaelshelman/vosk/vosk-api/nodejs/node_modules/ffi-napi/lib/library.js:47:10)
    at Object.<anonymous> (/Users/michaelshelman/vosk/vosk-api/nodejs/index.js:84:21)

**Comment by nshmyrev** [comment]
You can download the binary here:

https://github.com/alphacep/vosk-api/releases/download/v0.3.32/vosk-osx-0.3.32.zip

I believe the binary should be there if you install with npm, not trying to run the source as is.

**Comment by mshelman11** [comment]
Thanks for this but i'm not sure what to do with it.
I cloned the repo then ran npm install. I don't have lib folder or
libvosk.dylib.
When I unzip vosk-osx-0.3.32.zip
<https://github.com/alphacep/vosk-api/releases/download/v0.3.32/vosk-osx-0.3.32.zip>
it
yields libvosk.dyld and vosk_api.h. Again, not sure what to do with it.

**Comment by nshmyrev** [comment]
Put it in the folder /Users/michaelshelman/vosk/vosk-api/nodejs/lib/osx-x86_64/libvosk.dylib

**Comment by Colt-crypto** [comment]
Hi, I have the same issue.
There's no lib folder after running yarn / npm install.

libvosk.dylib is not in the above zip link

Thanks in advance

**Comment by nshmyrev** [comment]
I download this file:

https://registry.npmjs.org/vosk/-/vosk-0.3.32.tgz

dylib is there

**Comment by mshelman11** [comment]
Now file is found but I am getting 'no suitable image found - wrong
architecture' probably because i have M1 chip not x86..

**Comment by nshmyrev** [comment]
Ok, it is the same as https://github.com/alphacep/vosk-api/issues/692 then

**Comment by nshmyrev** [comment]
We published 0.3.39 osx with universal binary

**Comment by codesoda** [comment]
@nshmyrev It looks like the 0.3.39 release is not available. Perhaps it was removed? Any possibility of having OSX universal binaries re-added to new releases?

**Comment by mattkenefick** [comment]
@codesoda https://registry.npmjs.org/vosk/-/vosk-0.3.39.tgz

**Comment by chinarui-na** [comment]
@mattkenefick  i met this error after build electron app use electron-build, i use vosk-0.3.39 and `libvosk.dylib` exist
```
Uncaught Exception:
Error: Dynamic Linking Error: dlopen(/Applications/vosk.app/Contents/Resources/app.asar/node_modules/vosk/lib/osx-universal/libvosk.dylib, 0x0002): 
tried: '/Applications/vosk.app/Contents/Resources/app.asar/node_modules/vosk/lib/osx-universal/libvosk.dylib' (errno=20), '/System/Volumes/Preboot/Cryptexes/OS/Applications/vosk.app/Contents/Resources/app.asar/node_modules/vosk/lib/osx-universal/libvosk.dylib' (no such file),
 '/Applications/vosk.app/Contents/Resources/app.asar/node_modules/vosk/lib/osx-universal/libvosk.dylib' (errno=20)
at new DynamicLibrary (/Applications/vosk.app/Contents/Resources/app.asar/node_modules/ffi-napi/lib/dynamic_library.js:75:11)
```
Please help me

**Comment by nshmyrev** [comment]
Hello. We can not publish updated version for now, details here:

https://github.com/alphacep/vosk-api/issues/1422
