### ISSUE TITLE
you may not have installed OpenFst. See ../tools/INSTALL ***

### ISSUE THREAD

**Issue by liuyibox** [alphacep/vosk-api#9]
After the installation OK with OpenBLAS, errors comes when unzip and install fst. The error message is below:

>Install OK!
make[1]: Leaving directory '/home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64/OpenBLAS'
make: Leaving directory '/home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64/OpenBLAS'

>+ cd /home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64
>+ wget -c -T 10 -t 1 http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.6.7.tar.gz
--2020-01-03 15:00:45--  http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.6.7.tar.gz
Resolving www.openfst.org (www.openfst.org)... 206.196.111.47
Connecting to www.openfst.org (www.openfst.org)|206.196.111.47|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1230836 (1.2M) [application/x-gzip]
Saving to: ‘openfst-1.6.7.tar.gz’
>
>     0K .......... .......... .......... .......... ..........  4%  571K 2s
>    50K .......... .......... .......... .......... ..........  8% 1010K 2s
>   100K .......... .......... .......... .......... .......... 12% 11.5M 1s
>   150K .......... .......... .......... .......... .......... 16%  865K 1s
>   200K .......... .......... .......... .......... .......... 20% 10.9M 1s
>   250K .......... .......... .......... .......... .......... 24% 11.6M 1s
>   300K .......... .......... .......... .......... .......... 29% 25.1K 5s
>   350K .......... .......... .......... .......... .......... 33%  163M 4s
>   400K ......                                                 33%  413 =17s
>
>2020-01-03 15:01:13 (23.6 KB/s) - Read error at byte 415799/1230836 (Connection timed out). Giving up.
>
>+ wget -c -T 10 -t 3 http://www.openslr.org/resources/2/openfst-1.6.7.tar.gz
--2020-01-03 15:01:13--  http://www.openslr.org/resources/2/openfst-1.6.7.tar.gz
Resolving www.openslr.org (www.openslr.org)... 46.101.158.64
Connecting to www.openslr.org (www.openslr.org)|46.101.158.64|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable
>
>    The file is already fully retrieved; nothing to do.
>
>+ tar -zxvf openfst-1.6.7.tar.gz
>openfst-1.6.7/
openfst-1.6.7/ltmain.sh
openfst-1.6.7/install-sh
openfst-1.6.7/aclocal.m4
openfst-1.6.7/missing
openfst-1.6.7/ar-lib
openfst-1.6.7/INSTALL
openfst-1.6.7/COPYING
openfst-1.6.7/README
openfst-1.6.7/m4/
openfst-1.6.7/m4/ltversion.m4
openfst-1.6.7/m4/libtool.m4
openfst-1.6.7/m4/ltoptions.m4
openfst-1.6.7/m4/lt~obsolete.m4
openfst-1.6.7/m4/ltsugar.m4
openfst-1.6.7/m4/ac_python_devel.m4
openfst-1.6.7/compile
openfst-1.6.7/depcomp
openfst-1.6.7/AUTHORS
openfst-1.6.7/NEWS
openfst-1.6.7/Makefile.in
openfst-1.6.7/config.h.in
openfst-1.6.7/configure.ac
openfst-1.6.7/config.guess
openfst-1.6.7/test-driver
openfst-1.6.7/src/
openfst-1.6.7/src/bin/
openfst-1.6.7/src/bin/fstshortestpath-main.cc
openfst-1.6.7/src/bin/fstprint.cc
openfst-1.6.7/src/bin/fstcompile-main.cc
openfst-1.6.7/src/bin/fstisomorphic.cc
openfst-1.6.7/src/bin/fstcompose-main.cc
openfst-1.6.7/src/bin/fstconnect-main.cc
openfst-1.6.7/src/bin/fstprune.cc
openfst-1.6.7/src/bin/fstinfo.cc
openfst-1.6.7/src/bin/fstdraw.cc
openfst-1.6.7/src/bin/fstprint-main.cc
openfst-1.6.7/src/bin/fstunion.cc
openfst-1.6.7/src/bin/fstrandgen-main.cc
openfst-1.6.7/src/bin/fstrandgen.cc
openfst-1.6.7/src/bin/fstsymbols-main.cc
openfst-1.6.7/src/bin/fstepsnormalize-main.cc
openfst-1.6.7/src/bin/fstpush.cc
openfst-1.6.7/src/bin/fstconcat-main.cc
openfst-1.6.7/src/bin/fstdeterminize-main.cc
openfst-1.6.7/src/bin/fstencode-main.cc
openfst-1.6.7/src/bin/fstmap.cc
openfst-1.6.7/src/bin/fstisomorphic-main.cc
openfst-1.6.7/src/bin/fstminimize-main.cc
openfst-1.6.7/src/bin/fstreweight-main.cc
openfst-1.6.7/src/bin/fstreplace-main.cc
openfst-1.6.7/src/bin/fstarcsort-main.cc
openfst-1.6.7/src/bin/fstdifference-main.cc
openfst-1.6.7/src/bin/fstpush-main.cc
openfst-1.6.7/src/bin/Makefile.in
openfst-1.6.7/src/bin/fstsymbols.cc
openfst-1.6.7/src/bin/fstepsnormalize.cc
openfst-1.6.7/src/bin/fstconvert.cc
openfst-1.6.7/src/bin/fstintersect-main.cc
openfst-1.6.7/src/bin/fstshortestpath.cc
openfst-1.6.7/src/bin/fstdifference.cc
openfst-1.6.7/src/bin/fstconnect.cc
openfst-1.6.7/src/bin/fstinvert-main.cc
openfst-1.6.7/src/bin/fstequivalent-main.cc
openfst-1.6.7/src/bin/fstequal-main.cc
openfst-1.6.7/src/bin/fstclosure.cc
openfst-1.6.7/src/bin/fstunion-main.cc
openfst-1.6.7/src/bin/fstencode.cc
openfst-1.6.7/src/bin/fstcompose.cc
openfst-1.6.7/src/bin/fstprune-main.cc
openfst-1.6.7/src/bin/fstminimize.cc
openfst-1.6.7/src/bin/fsttopsort.cc
openfst-1.6.7/src/bin/fstinvert.cc
openfst-1.6.7/src/bin/fstproject-main.cc
openfst-1.6.7/src/bin/fstintersect.cc
openfst-1.6.7/src/bin/fstinfo-main.cc
openfst-1.6.7/src/bin/fstreweight.cc
openfst-1.6.7/src/bin/fstclosure-main.cc
openfst-1.6.7/src/bin/fsttopsort-main.cc
openfst-1.6.7/src/bin/fstcompile.cc
openfst-1.6.7/src/bin/fstreplace.cc
openfst-1.6.7/src/bin/fstconcat.cc
openfst-1.6.7/src/bin/fstdisambiguate-main.cc
openfst-1.6.7/src/bin/fstreverse-main.cc
openfst-1.6.7/src/bin/fstproject.cc
openfst-1.6.7/src/bin/fstsynchronize-main.cc
openfst-1.6.7/src/bin/fstequivalent.cc
openfst-1.6.7/src/bin/fstdraw-main.cc
openfst-1.6.7/src/bin/fstrelabel.cc
openfst-1.6.7/src/bin/fstarcsort.cc
openfst-1.6.7/src/bin/fstdeterminize.cc
openfst-1.6.7/src/bin/Makefile.am
openfst-1.6.7/src/bin/fstconvert-main.cc
openfst-1.6.7/src/bin/fstrelabel-main.cc
openfst-1.6.7/src/bin/fstreverse.cc
openfst-1.6.7/src/bin/fstdisambiguate.cc
openfst-1.6.7/src/bin/fstshortestdistance.cc
openfst-1.6.7/src/bin/fstshortestdistance-main.cc
openfst-1.6.7/src/bin/fstequal.cc
openfst-1.6.7/src/bin/fstrmepsilon.cc
openfst-1.6.7/src/bin/fstsynchronize.cc
openfst-1.6.7/src/bin/fstmap-main.cc
openfst-1.6.7/src/bin/fstrmepsilon-main.cc
openfst-1.6.7/src/Makefile.in
openfst-1.6.7/src/include/
openfst-1.6.7/src/include/Makefile.in
openfst-1.6.7/src/include/Makefile.am
openfst-1.6.7/src/include/fst/
openfst-1.6.7/src/include/fst/reweight.h
openfst-1.6.7/src/include/fst/union.h
openfst-1.6.7/src/include/fst/replace-util.h
openfst-1.6.7/src/include/fst/visit.h
openfst-1.6.7/src/include/fst/pair-weight.h
openfst-1.6.7/src/include/fst/generic-register.h
openfst-1.6.7/src/include/fst/flags.h
openfst-1.6.7/src/include/fst/weight.h
openfst-1.6.7/src/include/fst/compose.h
openfst-1.6.7/src/include/fst/randequivalent.h
openfst-1.6.7/src/include/fst/expanded-fst.h
openfst-1.6.7/src/include/fst/set-weight.h
openfst-1.6.7/src/include/fst/arc-map.h
openfst-1.6.7/src/include/fst/determinize.h
openfst-1.6.7/src/include/fst/types.h
openfst-1.6.7/src/include/fst/config.h
openfst-1.6.7/src/include/fst/lookahead-matcher.h
openfst-1.6.7/src/include/fst/statesort.h
openfst-1.6.7/src/include/fst/prune.h
openfst-1.6.7/src/include/fst/verify.h
openfst-1.6.7/src/include/fst/rmfinalepsilon.h
openfst-1.6.7/src/include/fst/register.h
openfst-1.6.7/src/include/fst/state-map.h
openfst-1.6.7/src/include/fst/state-table.h
openfst-1.6.7/src/include/fst/properties.h
openfst-1.6.7/src/include/fst/replace.h
openfst-1.6.7/src/include/fst/edit-fst.h
openfst-1.6.7/src/include/fst/map.h
openfst-1.6.7/src/include/fst/arcfilter.h
openfst-1.6.7/src/include/fst/matcher.h
openfst-1.6.7/src/include/fst/union-weight.h
openfst-1.6.7/src/include/fst/product-weight.h
openfst-1.6.7/src/include/fst/label-reachable.h
openfst-1.6.7/src/include/fst/icu.h
openfst-1.6.7/src/include/fst/symbol-table.h
openfst-1.6.7/src/include/fst/const-fst.h
openfst-1.6.7/src/include/fst/equivalent.h
openfst-1.6.7/src/include/fst/util.h
openfst-1.6.7/src/include/fst/filter-state.h
openfst-1.6.7/src/include/fst/union-find.h
openfst-1.6.7/src/include/fst/complement.h
openfst-1.6.7/src/include/fst/dfs-visit.h
openfst-1.6.7/src/include/fst/relabel.h
openfst-1.6.7/src/include/fst/sparse-power-weight.h
openfst-1.6.7/src/include/fst/float-weight.h
openfst-1.6.7/src/include/fst/epsnormalize.h
openfst-1.6.7/src/include/fst/push.h
openfst-1.6.7/src/include/fst/rational.h
openfst-1.6.7/src/include/fst/config.h.in
openfst-1.6.7/src/include/fst/compact-fst.h
openfst-1.6.7/src/include/fst/fst-decl.h
openfst-1.6.7/src/include/fst/symbol-table-ops.h
openfst-1.6.7/src/include/fst/lock.h
openfst-1.6.7/src/include/fst/mapped-file.h
openfst-1.6.7/src/include/fst/matcher-fst.h
openfst-1.6.7/src/include/fst/arc-arena.h
openfst-1.6.7/src/include/fst/synchronize.h
openfst-1.6.7/src/include/fst/project.h
openfst-1.6.7/src/include/fst/state-reachable.h
openfst-1.6.7/src/include/fst/vector-fst.h
openfst-1.6.7/src/include/fst/sparse-tuple-weight.h
openfst-1.6.7/src/include/fst/heap.h
openfst-1.6.7/src/include/fst/memory.h
>
>gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
>+ cd openfst-1.6.7
>+ CXX=aarch64-linux-android21-clang++
>+ CXXFLAGS=' -O3 -DFST_NO_DYNAMIC_LINKING'
>+ ./configure --prefix=/home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64/local --enable-shared --enable-static --with-pic --disable-bin --enable-lookahead-fsts --enable-ngram-fsts --host=aarch64-linux-android --build=x86-linux-gnu
./build-kaldi.sh: line 82: ./configure: No such file or directory
>+ make -j 8
make: *** No targets specified and no makefile found.  Stop.
>+ make install
make: *** No rule to make target 'install'.  Stop.
>+ cd /home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64
>+ git clone -b android-mix --single-branch https://github.com/alphacep/kaldi
Cloning into 'kaldi'...
>+ cd /home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64/kaldi/src
>+ CXX=aarch64-linux-android21-clang++
>+ CXXFLAGS=' -O3 -DFST_NO_DYNAMIC_LINKING'
>+ ./configure --use-cuda=no --mathlib=OPENBLAS --shared --android-incdir=/home/liuyi/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include --host=aarch64-linux-android --openblas-root=/home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64/local --fst-root=/home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64/local --fst-version=1.6.7
Configuring KALDI to use OPENBLAS.
Checking compiler aarch64-linux-android21-clang++ ...
Checking OpenFst library in /home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64/local ...
>***configure failed: Could not find file /home/liuyi/Documents/VoiceAssist/vosk-api/android/build/kaldi_arm_64/local/include/fst/fst.h:
  you may not have installed OpenFst. See ../tools/INSTALL ***
>+ make -j 8 depend
Makefile:30: kaldi.mk: No such file or directory
kaldi.mk does not exist; you have to run ./configure
Makefile:90: recipe for target 'kaldi.mk' failed
make: *** [kaldi.mk] Error 1
>+ make -j 8 online2
Makefile:30: kaldi.mk: No such file or directory
kaldi.mk does not exist; you have to run ./configure
Makefile:90: recipe for target 'kaldi.mk' failed
make: *** [kaldi.mk] Error 1
>
> Task :kaldi FAILED
>
FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':kaldi'.
> Process 'command './build-kaldi.sh'' finished with non-zero exit value 2
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>
>* Get more help at https://help.gradle.org
>
>Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings
>
>BUILD FAILED in 8m 57s
1 actionable task: 1 executed

**Comment by nshmyrev** [comment]
You have the same problem with wget as before, remove the first wget and use just the second one.

**Comment by liuyibox** [comment]
Thanks. I tried to make some changes. Now the compilation error comes to be about java itself. Before this error, `gradle build` just went through `Build kaldi_jni_armeabi-v7a`, `Build kaldi_jni_arm64-v8a` and `Build kaldi_jni_x86_64`
> Task :compileDebugJavaWithJavac FAILED
>Fatal Error: Unable to find package java.lang in classpath or bootclasspath
>
>FAILURE: Build failed with an exception.
>
>* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
>
>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>
>* Get more help at https://help.gradle.org
>
>Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 36m 59s
25 actionable tasks: 25 executed

Is this only related to my java configuration on ubuntu? I do believe that I have not update any java-related thing. I am using the default java configuration on ubuntu. After the `java -version` command, the output is:
>openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

**Comment by liuyibox** [comment]
This error is due to Ubuntu open-jdk itself. I removed every default Ubuntu java configuration and reinstalled oracle jdk. It works now. This repo produces both debug and release kaldi android archives.

**Comment by nshmyrev** [comment]
@liuyibox Congratulations!
