### ISSUE TITLE
[Java] Getting no results

### ISSUE THREAD

**Issue by proohit** [alphacep/vosk-api#900]
Thanks for your dedicated work on Vosk! I'm trying to use Vosk in Java for voice recognition with JDA in Discord. However, I am getting no results at all from the recognizer. The input format is the following:
`48KHz 16bit stereo signed BigEndian PCM`
Please see the following snippet for my usage:
```java
        Recognizer rec;
        ...
        Model model = new Model(modelPath);
        rec = new Recognizer(model, 16000);
        ...
        byte[] voice = userAudio.getAudioData(1.0);
        AudioFormat originalFormat = new AudioFormat(48000.0f, 16, 2, true, true);
        AudioFormat targetFormat = new AudioFormat(16000.0f, 16, 1, true, false);

        int length = voice.length;
        ByteArrayInputStream bais = new ByteArrayInputStream(voice);
        AudioInputStream originalStream = new AudioInputStream(bais, originalFormat, length);
        AudioInputStream transcodedStream = AudioSystem.getAudioInputStream(targetFormat, originalStream);
        try {
            byte[] formattedVoice = transcodedStream.readAllBytes();
            if (rec.acceptWaveForm(formattedVoice, formattedVoice.length)) {
                String result = rec.getResult();
                System.out.println(result);
            }
        } catch (Exception e) {
            Logger.error(e);
        }
```
The model seems to load correctly:
```txt
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.024034 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from path/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:281) Loading HCL and G from path/model/graph/HCLr.fst path/model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:302) Loading winfo path/model/graph/phones/word_boundary.int
```
The format should be correctly represented by javax.sound.sampled.AudioFormat. See here:
```java
AudioFormat(float sampleRate, int sampleSizeInBits, int channels, boolean signed, boolean bigEndian)
```
The conversion itself doesn't throw anything, so I guess it is correctly transcoding.

Am I missing something here? Thanks in advance!

**Comment by nshmyrev** [comment]
You need to store the audio you feed to the recognizer to a file and listen it. You can also check with audio editor if file is corrupted somehow / silent.

**Comment by proohit** [comment]
I buffered a 48k byte array of the transcoded voice into a wave file.
```java
           ...
           byte[] allData = new byte[48000];
           ...
            ByteArrayOutputStream baos = new ByteArrayOutputStream(48000);
            baos.write(allData);
            baos.write(formattedVoice);
            allData = baos.toByteArray();
            if (allData.length > 48000) {
                ByteArrayInputStream bais2 = new ByteArrayInputStream(allData);
                AudioInputStream targetStream = new AudioInputStream(bais2, targetFormat, allData.length);
                AudioSystem.write(targetStream, AudioFileFormat.Type.WAVE,
                        new java.io.File("/.../test.wav"));
            }
```
The audio is what I was speaking, although it didn't have good quality but definitely not corrupted.

**Comment by nshmyrev** [comment]
Ok. In your code you do not call FinalResult, you'd better follow the samples. If you want to process the whole file at once you don't need if condition, you just call FinalResult.

**Comment by proohit** [comment]
Before I forget it: I'm using vosk ’0.3.32’ with the small English model ’vosk-model-small-en-us-0.15’

**Comment by proohit** [comment]
It does not work when calling `Recognizer#getFinalResult` since it returns an empty string, but works with `Recognizer#getPartialResult`. I don't have a full wave byte array but instead small chunks of the spoken voice. Is there a way  to let Vosk handle some kind of "timeout" after which `Recognizer#getFinalResult` returns the final results? Or does Vosk not even save the history temporarily?

Right now, I'm thinking of implementing the timeout logic myself, since it should be user independent. I know however from [vosk-browser](https://github.com/ccoreilly/vosk-browser) that we get events on `result` being finalResult and `partialResult`.

**Comment by nshmyrev** [comment]
> Please see the following snippet for my usage:

            byte[] formattedVoice = transcodedStream.readAllBytes();

> I don't have a full wave byte array but instead small chunks of the spoken voice.

Those two statements are contradictory

Please follow our code sample here precisely:

https://github.com/alphacep/vosk-api/blob/master/java/demo/src/main/java/org/vosk/demo/DecoderDemo.java

**Comment by proohit** [comment]
`voice` and `formattedVoice` are just 20ms of data, provided by JDA/Discord. `readAllBytes` refers to all bytes from that chunk. The method is documented as follows:
`net.dv8tion.jda.api.audio.UserAudio.getAudioData`
> Provides 20 Milliseconds of combined audio data in 48KHz 16bit stereo signed BigEndian PCM. (...)

**Comment by nshmyrev** [comment]
> voice and formattedVoice are just 20ms of data, provided by JDA/Discord

Why your sample code has no loop as in our demo code then

https://github.com/alphacep/vosk-api/blob/master/java/demo/src/main/java/org/vosk/demo/DecoderDemo.java#L27

**Comment by proohit** [comment]
Ah yeah, sorry I should have clarified that. And thank you a lot for you patience!

I'm getting the voice data via asynchronous events in 20ms intervals, if there has been spoken anything. Keep in mind that these events are coming from an external server (discord). Everytime someone on the registered voice channel speaks, a method `handleUserAudio` is called to handle those events. In this case, the snippet above is the implementation of this method. The method gets a parameter of type `UserAudio` which exposes a method `getAudioData` to extract the spoken voice as a byte array. From that object, I can also extract the user that speaked. To answer your question, in this case we don't need any loop because this method is called when there is new data available.

Please let my share my updated snippet which is a little more readable for all the future readers out there :).
```java
    @Override
    // This gets called asynchronously when a user starts speaking
    // userAudio exposes the audio data and the user
    public void handleUserAudio(UserAudio userAudio) {
        // rec is our Recognizer
        if (rec != null) {
            try {
                byte[] voice = userAudio.getAudioData(1.0);
                byte[] transcodedVoice = transcodeVoice(voice);
                rec.acceptWaveForm(transcodedVoice, transcodedVoice.length);
                String result = rec.getPartialResult();
                Logger.info(result);
            } catch (Exception e) {
                Logger.error(e);
            }
        }
    }

    private byte[] transcodeVoice(byte[] voice) throws IOException {
        AudioFormat originalFormat = new AudioFormat(48000.0f, 16, 2, true, true);
        AudioFormat targetFormat = new AudioFormat(16000.0f, 16, 1, true, false);

        int length = voice.length;
        ByteArrayInputStream bais = new ByteArrayInputStream(voice);
        AudioInputStream originalStream = new AudioInputStream(bais, originalFormat, length);
        AudioInputStream transcodedStream = AudioSystem.getAudioInputStream(targetFormat, originalStream);
        return transcodedStream.readAllBytes();
    }
```
As stated above, `getPartialResult` now correctly returns the transcript. But all the transcribed bytes are saved into one long string now. Vosk-browser had some kind of timeout integrated and fired events on `partialResult` and `result`, meaning final result, including the confidence. I wanted to ask for a good practice on how to handle that or if vosk already does that and there are just Java bindings missing.

**Comment by nshmyrev** [comment]
Ok, now bring back if condition and getResult to your code and thats it
