### ISSUE TITLE
[Feature Request] Possibility of using dynamic linking for dependencies

### ISSUE THREAD

**Issue by auroraanon38** [alphacep/vosk-api#902]
I would like having the option of having Vosk itself rely on shared objects for its dependencies Kaldi and OpenFST.

This would make it easier to package for various distros, namely Guix.

**Comment by nshmyrev** [comment]
Than you for your proposal, however, we modify both packages significantly and we are not going to work with stock openfst. Openfst upstream doesn't accept our patches.

https://www.openfst.org/twiki/bin/view/Forum/FstForum#Speedup%20lookahead%20composition
