### ISSUE TITLE
Start time and End time of each word in Java

### ISSUE THREAD

**Issue by kromoxpro** [alphacep/vosk-api#903]
Hi,

I have seen in Python, Vosk in NonPartial results ("text" field) includes an array of each word with start time, end time and confidence.

But in Java I can't get that data. I only get arrays with field "text" without the additional data mentioned above.

Is there any way to get this data using Vosk in Java?

Thanks.

**Comment by nshmyrev** [comment]
You can add a call after constructor

      recognizer.setWords(true)

to make recognizer return words. See also [here](https://github.com/alphacep/vosk-api/blob/master/java/lib/src/main/java/org/vosk/Recognizer.java#L27)

**Comment by nshmyrev** [comment]
And [here](https://github.com/alphacep/vosk-api/blob/master/src/vosk_api.h#L198)

**Comment by kromoxpro** [comment]
Thank You @nshmyrev! It's works!
