### ISSUE TITLE
Some (maybe) dummy questions in C#

### ISSUE THREAD

**Issue by qwerty13** [alphacep/vosk-api#904]
Hi
i used nuget package of vosk in a sample c# Project and successfully get result from "vosk-model-small-fa-0.5" and "vosk-model-fa-0.5" models:

```
Model model = new Model(AppDomain.CurrentDomain.BaseDirectory + txt_path.Text);
_recognizer = new VoskRecognizer(model, 16000);
```

but there is some questions:
1- i make model object with "vosk-model-ar-mgb2-0.4" and it's very slow and hangy (on a core-i7 and 16g RAM), make with "vosk-model-spk-0.4" and it said that this is not a model, why?

2- i make a recognizer with grammer and it failed:
`_recognizer = new VoskRecognizer(model, 16000, "یک دو سه");
`
> System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

english grammer words faileds too.

3- any plan to add phonemes output? it can be very useful...

4- i compare VoskRecognizer Class and vosk_api.h, is it true that some functions are not in c# class? vosk_recognizer_set_words, vosk_model_find_word, vosk_gpu_init, ...

**Comment by nshmyrev** [comment]
> i make model object with "vosk-model-ar-mgb2-0.4" and it's very slow and hangy (on a core-i7 and 16g RAM),

You need to check memory usage, probably your memory is full

> make with "vosk-model-spk-0.4" and it said that this is not a model, why?

For speaker mode there is another class SpkModel

https://github.com/alphacep/vosk-api/blob/master/csharp/nuget/src/SpkModel.cs

> 2- i make a recognizer with grammer and it failed:

Grammar has to be a json string, see the examples in the code

> 3- any plan to add phonemes output? it can be very useful...

No, we do not have plans for phonemes

> i compare VoskRecognizer Class and vosk_api.h, is it true that some functions are not in c# class? vosk_recognizer_set_words, vosk_model_find_word, vosk_gpu_init, ..

SetWords is there:

https://github.com/alphacep/vosk-api/blob/master/csharp/nuget/src/VoskRecognizer.cs#L45

find word is also there:

https://github.com/alphacep/vosk-api/blob/master/csharp/nuget/src/Model.cs#L35

As for some other functions, feel free to submit a patch to add them.
