### ISSUE TITLE
Apple silicon

### ISSUE THREAD

**Issue by aivoicesystems** [alphacep/vosk-api#905]
I realise that there are lots of similar issues already related to a native M1 (Apple silicon) port, but I am interested in trying to get a true native port running on my Macbook M1 Pro and I'm willing to give things a try to get it going.

I have followed the set of build commands in the Dockerfile [here](https://github.com/alphacep/vosk-api/blob/master/travis/Dockerfile.manylinux#L26) (without running docker) and managed to get kaldi to compile.

So my question is, what is the next step required to get a native python and, ideally for my use, java version of the api going?

**Comment by nshmyrev** [comment]
Same as #692

Once you compiled kaldi you run make in vosk-api/src to build dylib and thats it.

**Comment by aivoicesystems** [comment]
OK, thanks. Are you interested in a couple of minor tweaks to the build process to get it to run cleanly on a mac? It's an almost trivial PR if you want one.

**Comment by nshmyrev** [comment]
Yes, sure

**Comment by aivoicesystems** [comment]
OK, I'll put one together

**Comment by nshmyrev** [comment]
Thank you

**Comment by sskorol** [comment]
@aivoicesystems can you share details on changes required to build it on m1?

**Comment by aivoicesystems** [comment]
I'm putting together a script to build for an M1 which is based on the Dockerfile.manylinux I linked to above.

Building kaldi is not too difficult but there are a few places you can slip up.

1. The build relies on a case-sensitive filesystem - out of the box a MacOS fs is not. I built a case-sensitve fs to get this to work
2. There is actually a minor bug in the OpenBLAS code which causes the compilation to fail: stdio.h is not included in one file. My script has to patch the code to get it to compile.
3. cp -t is not support in Darwin - the fix is simple
4. sed -i requires an argument on Darwin (for the backup file)
5. nproc is not supported - I haven't found a generic solution for this yet - just hard-coded a number for make -j

@sskorol re you interested in testing the script when it's done?

**Comment by sskorol** [comment]
Yes, I have M1 and can test it.

**Comment by aivoicesystems** [comment]
Here's a script which builds kaldi for Apple silicon.

@sskorol can you try it out? All you need is a case-sensitive file system and the standard development tools.

[build-macos-sh.zip](https://github.com/alphacep/vosk-api/files/8485754/build-macos-sh.zip)

**Comment by sskorol** [comment]
@aivoicesystems thanks, will test it this weekend.

**Comment by aivoicesystems** [comment]
@nshmyrev could we re-open this issue? There are several things still to work through if this is going to go anywhere.

**Comment by nshmyrev** [comment]
We discuss this issue in #692

**Comment by aivoicesystems** [comment]
Ok thanks. I'll move discussion into there
