### ISSUE TITLE
about some model questions

### ISSUE THREAD

**Issue by Veango** [alphacep/vosk-api#908]
hello,i notice that code if model has hclg.fst, it doesn't use decode.fst
decoder_ = new kaldi::SingleUtteranceNnet3Decoder(model_->nnet3_decoding_config_,
            *model_->trans_model_,
            *model_->decodable_info_,
            model_->hclg_fst_ ? *model_->hclg_fst_ : *decode_fst_,
            feature_pipeline_);
my question is 
1:if the model has hclg.fst, it certainly hasn't hclr.fst and gr.fst fisles？
2: if the model just have hclg.fst, it doesn't support set the grammar？

**Comment by nshmyrev** [comment]
> if the model has hclg.fst, it certainly hasn't hclr.fst and gr.fst fisles？

Yes, although it is a good idea to have all of them probably.

> 2: if the model just have hclg.fst, it doesn't support set the grammar？

Yes

**Comment by Veango** [comment]
thank you so much
