### ISSUE TITLE
model fr on website corrupted

### ISSUE THREAD

**Issue by gmat** [alphacep/vosk-api#910]
Hi,
I just notice that the download file for the french linto model is corrupted on your website.
Here the hash of the current download. With this file zip managers failed with CRC errors.
```
sha1sum vosk-model-fr-0.6-linto-2.2.0\(1\).zip 
4208edf62db0e6de04a81454a3cfe10788e54bd5  vosk-model-fr-0.6-linto-2.2.0(1).zip
```
the old good one as this hash
```
sha1sum vosk-model-fr-0.6-linto-2.2.0.zip 
9109abef2c2273565265b54c5aeea2e77dad6c34  vosk-model-fr-0.6-linto-2.2.0.zip
```

**Comment by nshmyrev** [comment]
Not sure how it happened. I've updated the archive, it should work now. Thank you for report.
