### ISSUE TITLE
Can not load libvosk.so in pyinstaller binary

### ISSUE THREAD

**Issue by karimmhamdihabemus** [alphacep/vosk-api#911]
I build an executable with pyinstaller and when ever I run on the device I get this error.
![vosk error](https://user-images.githubusercontent.com/99814844/162178459-107ec0c1-a843-43c1-abb4-fe85f6072fbd.png)

**Comment by nshmyrev** [comment]
I believe you need to add --hidden-import for libvosk, did you do that? 

https://stackoverflow.com/questions/57771657/pyinstaller-create-an-executable-with-external-libraries

**Comment by karimmhamdihabemus** [comment]
unfortunately i did that but it didnt work ..

**Comment by nshmyrev** [comment]
Ok, you'd better report in detail what have you done with the command line and provide an example to reproduce you problem.

**Comment by nshmyrev** [comment]
Same as #602
