### ISSUE TITLE
vosk go package not working

### ISSUE THREAD

**Issue by ashish-navana** [alphacep/vosk-api#912]
When i tried to run the example code given in the `go/example` folder it was throwing error saying could not find `vosk_api.h` file. I ran `go get "github.com/alphacep/vosk-api/go"` to fetch the package and it seems like only `go` folder is getting fetched, not the `src` folder or anything else.  Am I missing anything?

**Comment by nshmyrev** [comment]
Hi.

You are expected to download prebuilt binaries from releases. See also https://github.com/alphacep/vosk-api/issues/708
