### ISSUE TITLE
Remove logs and get only text in java

### ISSUE THREAD

**Issue by ahmedsaheed** [alphacep/vosk-api#913]
Hi I was wondering how I'd be able to get rid of the debug logs and only get the text.

I would appreciate it if anyone can help me with this. thanks

**Comment by nshmyrev** [comment]
To disable debug you can run `setLogLevel(LogLevel.WARNINGS)`

https://github.com/alphacep/vosk-api/blob/master/java/lib/src/main/java/org/vosk/LibVosk.java#L85

**Comment by nshmyrev** [comment]
Please close the issue if it works for you
