### ISSUE TITLE
System.AccessViolationException is thrown

### ISSUE THREAD

**Issue by TzippyFreedman** [alphacep/vosk-api#917]
I cloned the project, and when Im running the demo project, Im getting the following exception: System.AccessViolationException with the message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Im running the csharp demo, on windows 64-bit with dotnet version 6.0.201.
Please help!

**Comment by nshmyrev** [comment]
You probably didn't download the model as it should say in the log above.

**Comment by TzippyFreedman** [comment]
@nshmyrev Thanks for your help. how was I supposed to download the model? I didnt download any model

**Comment by nshmyrev** [comment]
yes

**Comment by TzippyFreedman** [comment]
How do I download the model? Thanks for your help!!

**Comment by nshmyrev** [comment]
Here: https://alphacephei.com/vosk/models

**Comment by TzippyFreedman** [comment]
THanks. Do I need to actually run the model? If yes, then how? thank you.

**Comment by nshmyrev** [comment]
You download and unpack it

**Comment by nshmyrev** [comment]
Same as #824
