### ISSUE TITLE
Re-using model to recognize another audio has a bug with timestamps of individual words

### ISSUE THREAD

**Issue by dchaplinsky** [alphacep/vosk-api#919]
I'm building a python webservice to generate subtitles for the audio fragments, thus `rec.SetWords(True)`.

Loading the big model to decode each separate audio file doesn't seems like a sane idea: time to load the model might be the same as decoding of the short fragment, not to mention i/o.

Unfortunately, even with `KaldiRecognizer.Reset` my solution has the following flaw: timestamps of the words from the second fragment are shifted (by the length of the previous fragment).

It seems that either here: https://github.com/alphacep/vosk-api/blob/master/src/recognizer.cc#L833
someone needs to call `InitState` (or set `samples_processed_` to zero), or `InitState` method should be exposed to the  bindings here https://github.com/alphacep/vosk-api/blob/master/src/vosk_api.cc.

I can submit a pull request for that (well, first option is trivial but I do not know the side effects, second option I can only do python/c++ part).

**Comment by dchaplinsky** [comment]
@nshmyrev maybe?

**Comment by nshmyrev** [comment]
You need to create new recognizer for every new stream.

**Comment by dchaplinsky** [comment]
Thanks for the prompt reply. Why one needs `Reset` then?

**Comment by nshmyrev** [comment]
Reset is used for interactive applications to reset current utterance results.
