### ISSUE TITLE
Aspire model not working

### ISSUE THREAD

**Issue by MikeyBeez** [alphacep/vosk-api#92]
Thank ou for your excellent software.  I've been running vosk for about a month.  I just downloaded the new large aspire model and moved it to model-en.  With the new model, vosk crashes.  I've moved the old model back in place, and it works fine.  What am I missing?  Is there a document on how to switch models?    
Ubuntu 18.04
python 3.6
vosk  0.3.3

**Comment by nshmyrev** [comment]
Please upgrade to vosk 0.3.7

**Comment by MikeyBeez** [comment]
Thank you Nickolay.  You're a great guy!
