### ISSUE TITLE
How to stop print the noise as word

### ISSUE THREAD

**Issue by Aanraa** [alphacep/vosk-api#926]
I've made my vosk model using kaldi. However, after I run the test_microphone.py, it prints trained word when some noise is occured even i didnt say anything.  

![Screenshot 2022-04-15 220621](https://user-images.githubusercontent.com/61553824/163580596-1b30d7f1-6178-44e9-8fec-9e4e636beda2.png)

**Comment by nshmyrev** [comment]
Train model with proper noise augmentation

**Comment by Aanraa** [comment]
can you tell me some details of how I do that? @nshmyrev pls

**Comment by nshmyrev** [comment]
Check for augment_data_dir.sh in existing recipes

**Comment by nshmyrev** [comment]
Similar issue in #837
