### ISSUE TITLE
Please tell me how much estimated time kaldi will take for Lattice Generation while Creating ASR Model.

### ISSUE THREAD

**Issue by mukeshbadgujar** [alphacep/vosk-api#927]
eg. if I have 500 Hrs of Data almost about 3 Lakhs text/audio Files (300K). so, how much time it will take to process the whole model,

I have put it on run form 10 days. and it is still continuously running.

system conf:
Ram: 32GB
GPU 8GB Nvidia RTX 3070Ti
16 Core CPU Intel
Python 3.7

**Comment by nshmyrev** [comment]
Lattice generation should take 1 day maximum

**Comment by mukeshbadgujar** [comment]
> Lattice generation should take 1 day maximum

Ok, I need to check What I did wrong.
