### ISSUE TITLE
How much Time and Space is required for Kaldi Vosk Model Building.

### ISSUE THREAD

**Issue by mukeshbadgujar** [alphacep/vosk-api#928]
Can you please tell me, 

a normal Kaldi setup with 600k Audio and text samples of 1000Hrs of data which is about 150GB+ Space taken.

This data if i put on model building, then how much time and space on ssd is required to proceed model creation.

Also i mention that, kaldi will generate many logs files and Generating Training Samples and Examples for Validating and Diagnostic. So it will take more space. But i don't know how much.

So, can you tell me, the Time and Space on HDD/SSD Required.

**Comment by nshmyrev** [comment]
You can get 5TB HDD to stay safe.
