### ISSUE TITLE
VOSK model not working?

### ISSUE THREAD

**Issue by Douglasonen** [alphacep/vosk-api#929]
I have been trying to work with vosk , sucessfully installed vosk and pyaudio 
The issue is, when i try to create a model as bellow;
model = Model(r"vosk-model-small-en-us-0.15")
i get an error saying ''the specified folder vosk-model-small-en-us-0.15'' does not contain model file.

How do i solve this guys?

**Comment by nshmyrev** [comment]
Please edit the title first to match the problem description

**Comment by nshmyrev** [comment]
You need to download and unpack the model yourself

**Comment by Douglasonen** [comment]
> You need to download and unpack the model yourself

Thanks a lot am trying it all out

**Comment by nshmyrev** [comment]
I suppose this one is solved. Let us know if you need extra help.
