### ISSUE TITLE
Raspberry Pi Zero V2 supports Python Vosk? 

### ISSUE THREAD

**Issue by AngeloIannielli** [alphacep/vosk-api#933]
Hi!

I want to upgrade my hardware. I need to use Vosk with it, but I don't known which version of Raspberry Pi I should buy. 
I asked for Raspberry Zero yet, so I alredy know this device can't support the module. Is the same with Zero 2? And Raspberry 2 or 3?
Which version is recommended?

Thanks for help!

**Comment by nshmyrev** [comment]
RPi4 is the best choice

**Comment by AngeloIannielli** [comment]
Thanks

**Comment by nshmyrev** [comment]
Same as #918
