### ISSUE TITLE
Finetuning causes Errors

### ISSUE THREAD

**Issue by vikraman22** [alphacep/vosk-api#934]
I'm trying to finetune the US English Model using this script [finetune](https://github.com/kaldi-asr/kaldi/blob/master/egs/aishell2/s5/local/nnet3/tuning/finetune_tdnn_1a.sh) mentioned in the acoustic model adaptation documentation, but this causes a lot of errors like this one as they didn't specify the required files for finetuning.

`Traceback (most recent call last):
  File "steps/nnet3/train_dnn.py", line 459, in main
    train(args, run_opts)
  File "steps/nnet3/train_dnn.py", line 216, in train
    "{1}".format(str(e), '{0}/configs'.format(args.dir)))
Exception: KeyError 'model_left_context': Variables need to be defined in exp/nnet3/tdnn_sp_finetune/configs`

How do I solve this error? Initially the configs directory was missing and it caused this error and I manually created the configs directory.

`Exception: Either --trainer.input-model option should be supplied, and exist; or the exp/nnet3/tdnn_sp_finetune/configs directory should exist.
exp/nnet3/tdnn_sp_finetune/configs is the output of make_configs.py
`
Is there any contents that I can look into so that I can add the required files prior to exceptions.

**Comment by nshmyrev** [comment]
Hi

It is the same issue as #185, no need to create a new issue about it, you can comment there. In general you need to understand what you are doing.
