### ISSUE TITLE
Armbian problem 

### ISSUE THREAD

**Issue by mavericky87** [alphacep/vosk-api#936]
hello I use vosk successfully on a Raspberry pi without any problem, now I would like to use a banana pi m2 zero board, on this I have installed armbian, I have updated python to version 3.8 and pip3 to 20, unfortunately however when I try to install with pip3 install vosk , always gives me errors in photos; what is the right procedure to install vosk on armbian? or is it not compatible? thank you very much for the great work you do 
![IMG_20220423_135320](https://user-images.githubusercontent.com/100438984/164917141-7dd2e01a-c595-4f81-8617-24be0a6967f1.jpg)
![IMG_20220423_193112](https://user-images.githubusercontent.com/100438984/164917543-5fdc6cba-c604-485f-8e16-f01bd730a859.jpg)

**Comment by nshmyrev** [comment]
You need to install python development package, soemthing like `apt install python3-dev`

**Comment by mavericky87** [comment]
Thanks a lot after the installation of package of python-dev and cffi, my script with vosk works fine :)

**Comment by nshmyrev** [comment]
Great, congratulations
