### ISSUE TITLE
"Can't create decoding graph" when running test_words.py 

### ISSUE THREAD

**Issue by andrewgomella** [alphacep/vosk-api#94]
Test_simple.py runs perfectly with the same audio file. When I add some words to the KaldiRecognizer grammar argument, as in "test_words.py", I get the following error and "Python has stopped working" windows pop-up. 

`ERROR (VoskAPI:KaldiRecognizer():build-libkaldiwrap/kaldi_recognizer.cc:82) Can't create decoding graph`

Full output:
> python test_words.py scanner.wav
LOG (VoskAPI:ConfigureV2():build-libkaldiwrap/model.cc:202) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ConfigureV2():build-libkaldiwrap/model.cc:205) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0299699 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():build-libkaldiwrap/model.cc:254) Loading HCLG from model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():build-libkaldiwrap/model.cc:273) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():build-libkaldiwrap/model.cc:281) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():build-libkaldiwrap/model.cc:289) Loading CARPA model from model/rescore/G.carpa
ERROR (VoskAPI:KaldiRecognizer():build-libkaldiwrap/kaldi_recognizer.cc:82) Can't create decoding graph

Python 3.8.2 on Windows
pip 20.1

Tested on my Linux install and same script runs fine.

**Comment by nshmyrev** [comment]
Dynamic graphs only work with small android models.

**Comment by andrewgomella** [comment]
Got it.. missed that point. Thanks.
