### ISSUE TITLE
Extend model search path

### ISSUE THREAD

**Issue by nshmyrev** [alphacep/vosk-api#944]
Like I wrote before we need to look for models in 3 places: /usr/share/vosk, /home/user/.cache/vosk, os.env('VOSK_MODEL_PATH').

**Comment by besentv** [comment]
Would it be possible to also introduce a default path for Windows? Maybe something like c:\users\<user>\AppData\Local\vosk ?

**Comment by nshmyrev** [comment]
Yes, we can do that too, @vadimdddd

**Comment by nshmyrev** [comment]
Done
