### ISSUE TITLE
Problem audio with sudo user

### ISSUE THREAD

**Issue by mavericky87** [alphacep/vosk-api#945]
Hi I've been using the vosk library for a few months with my python script on raspberry, everything works perfectly when I start the script with "python3 script.py" now I need to start the script with sudo privileges, so if I try to start it with "sudo python3 script.py "the audio does not start gives me the error of audio devices not present as seen in the picture. I tried some solutions but it doesn't work, because without compiling with sudo everything works, if I start with sudo the audio doesn't work? Just the audio part is not recognized. Thanks a lot for the help.
![279263701_1328699867652207_6895259665640516008_n](https://user-images.githubusercontent.com/100438984/165944645-3df06e20-8976-41f0-a665-f788e8c3b99a.jpg)

**Comment by nshmyrev** [comment]
You probably want to run pulseaudio in systemwide mode

**Comment by mavericky87** [comment]
I'm sorry I didn't quite understand what you can tell me, I have to enable pulse audio in system wide mode to make it work even when I use "sudo python3 script.py"? in case I found this procedure:
https://github.com/shivasiddharth/PulseAudio-System-Wide
 but I did not understand if you are recommending me to activate the wide mode system on pulse audio or to deactivate it?  thanks a lot

**Comment by nshmyrev** [comment]
you want to activate systemwide mode since sudo runs under superuser.

**Comment by mavericky87** [comment]
Ok thanks I solved with a systemwide mode the problem was that sudo has not audio on boot but now Is perfect
