### ISSUE TITLE
Issue with the manually trained model

### ISSUE THREAD

**Issue by Ramanibharathi** [alphacep/vosk-api#947]
I trained a vosk model from scratch following this [tutorial](https://github.com/matteo-39/vosk-build-model) and it uses 
`local/chain/tuning/run_tdnn_1j.sh ` for training.
Finally I copied the required files and created the vosk model for STT.

But while I tried test_simple.py it produced the following dimension mismatch error

adminuser@Air example % python3 test_simple.py ../aligner/sample/boy1.wav ../aligner/sample/boy.txt model
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0801659 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Reading CMVN stats from model/am/global_cmvn.stats
LOG (VoskAPI:ReadDataFiles():model.cc:278) Loading HCLG from model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:293) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:302) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:309) Loading subtract G.fst model from model/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:311) Loading CARPA model from model/rescore/G.carpa
ERROR (VoskAPI:OnlineTransform():online-feature.cc:533) Dimension mismatch: source features have dimension 140 and LDA #cols is 281
Traceback (most recent call last):
  File "/Users/adminuser/Desktop/vosk/vosk-api/python/example/test_simple.py", line 20, in <module>
    rec = KaldiRecognizer(model, wf.getframerate())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vosk-0.3.32-py3.9.egg/vosk/__init__.py", line 61, in __init__
    raise Exception("Failed to create a recognizer")
Exception: Failed to create a recognizer

I later found that it was because of modifying the mfcc.conf the default was as follows 

--use-energy=false   # use average of log energy, not energy.
--num-mel-bins=40     # similar to Google's setup.
--num-ceps=40     # there is no dimensionality reduction.
--low-freq=20     # low cutoff frequency for mel bins... this is high-bandwidth data, so
                  # there might be some information at the low end.
--high-freq=-400 # high cutoff frequently, relative to Nyquist of 8000 (=7600)

and I changed it to 
`
--use-energy=false
--sample-frequency=8000
--num-mel-bins=40
--num-ceps=40
--low-freq=100
--high-freq=3700
`

but this didn't cause the dimension error but didn't produce output as expected 

adminuser@MacBook-Air example % python3 test_simple.py ../aligner/sample/boy6.wav
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.078588 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:266) Reading CMVN stats from model/am/global_cmvn.stats
LOG (VoskAPI:ReadDataFiles():model.cc:278) Loading HCLG from model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:293) Loading words from model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:302) Loading winfo model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:309) Loading subtract G.fst model from model/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:311) Loading CARPA model from model/rescore/G.carpa
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}
{
  "partial" : ""
}

Can you help me in resolving this issue @nshmyrev

**Comment by nshmyrev** [comment]
This tutorial is wrong, our training process is here:

https://github.com/alphacep/vosk-api/tree/master/training

**Comment by Ramanibharathi** [comment]
So I have to place the required files in data/train for acoustic model and data/local/dict for language model  and run
./run.sh. Is that right? Also does you script work if I'm not using gpu?

**Comment by nshmyrev** [comment]
> So I have to place the required files in data/train for acoustic model and data/local/dict for language model and run
./run.sh. Is that right? 

yes

> Also does you script work if I'm not using gpu?

gpu is required

**Comment by Ramanibharathi** [comment]
Thanks for replying @nshmyrev. But what would be the reason for the issue! Is it because of the training or some changes with mfcc.conf or other files would make it to work?

**Comment by nshmyrev** [comment]
mfcc.conf doesn't match the one used during training

**Comment by Ramanibharathi** [comment]
okay @nshmyrev. In which directory should I create data/lang and data/train directories.
 kaldi/egs/wsj/s5 or kaldi/egs/mini_librispeech/s5 ? Also Where should I place the vosk-api directory I guess on egs is that right?

**Comment by Ramanibharathi** [comment]
@nshmyrev Could you please tell in which directory should I place the vosk-api directory in order to start training

**Comment by nshmyrev** [comment]
> @nshmyrev Could you please tell in which directory should I place the vosk-api directory in order to start training

Try to figure out yourself, it is very straightforward thing.

**Comment by Ramanibharathi** [comment]
I saw the symbolic links and placed them in egs directory. I ran the script from kaldi/egs/vosk-api/training. The download started for some files but after a while the execution stops due to missing files. The data/train and data/local/dict are placed in kaldi/egs/wsj/s5 directory.

--> data/lang/L.fst is olabel sorted
--> data/lang/L_disambig.fst is olabel sorted
--> SUCCESS [validating lang directory data/lang]
steps/make_mfcc.sh --cmd run.pl --nj 10 data/train exp/make_mfcc/train
steps/make_mfcc.sh: no such file data/train/wav.scp
steps/compute_cmvn_stats.sh data/train exp/make_mfcc/train
steps/compute_cmvn_stats.sh: no such file data/train/feats.scp
steps/train_mono.sh --nj 10 --cmd run.pl data/train data/lang exp/mono
steps/train_mono.sh: Initializing monophone system.
feat-to-dim 'ark,s,cs:apply-cmvn --utt2spk=ark:data/train/split10/1/utt2spk scp:data/train/split10/1/cmvn.scp scp:data/train/split10/1/feats.scp ark:- | add-deltas ark:- ark:- |' - 
add-deltas ark:- ark:- 
apply-cmvn --utt2spk=ark:data/train/split10/1/utt2spk scp:data/train/split10/1/cmvn.scp scp:data/train/split10/1/feats.scp ark:- 
WARNING (apply-cmvn[5.5.1019~1-aefbd]:Open():util/kaldi-table-inl.h:106) Failed to open script file data/train/split10/1/feats.scp
ERROR (apply-cmvn[5.5.1019~1-aefbd]:SequentialTableReader():util/kaldi-table-inl.h:860) Error constructing TableReader: rspecifier is scp:data/train/split10/1/feats.scp

and as a result rest of the steps are also getting errors due to missing files

Also I tried placing it in the kaldi/egs/wsj/s5 directory I got the following error
`The standard file /content/kaldi/egs/wsj/s5/vosk-api/training/../../../tools/config/common_path.sh is not present -> Exit!`

**Comment by Ramanibharathi** [comment]
Can you please help with this @nshmyrev. I have been trying for the past 2 hours

**Comment by nshmyrev** [comment]
training folder should be in kaldi/egs/vosk-api/training

**Comment by Ramanibharathi** [comment]
Thanks a lot @nshmyrev !

**Comment by Ramanibharathi** [comment]
@nshmyrev I trained a model and tested it using test_simple.py. The results were as follows 

```
"result" : [{
      "conf" : 1.000000,
      "end" : 1.200000,
      "start" : 0.000000,
      "word" : "PEOPLE"
    }, {
      "conf" : 1.000000,
      "end" : 1.800000,
      "start" : 1.200000,
      "word" : "DON'T"
    }, {
      "conf" : 1.000000,
      "end" : 1.890000,
      "start" : 1.800000,
      "word" : "WANT"
    }, {
      "conf" : 1.000000,
      "end" : 1.920000,
      "start" : 1.890000,
      "word" : "TO"
    }
```

I realised that the words are uppercase because of the text input for training had entirely uppercase letters. In the resultant vosk-model if I changed the words.txt to lowercase and tried STT and it works fine. Is it okay to change the words.txt in the result vosk model?

**Comment by nshmyrev** [comment]
> Is it okay to change the words.txt in the result vosk model?

Yes
