### ISSUE TITLE
question - release plan

### ISSUE THREAD

**Issue by madkote** [alphacep/vosk-api#948]
Hi, since last release [0.3.32](https://github.com/alphacep/vosk-api/releases/tag/v0.3.32) there so many changes...
is there a release plan for 2022?

thx!

**Comment by nshmyrev** [comment]
We have 0.3.37 already ;) Actually we are doing some new python API with model autodownload, there will be new release after that.

**Comment by madkote** [comment]
aha, because [Releases](https://github.com/alphacep/vosk-api/releases) does not mention that.

btw: 0.3.37 - same API as before no dramatic changes?

**Comment by madkote** [comment]
@nshmyrev is there also a proper CHANGELOG to see, what has been updated / fixed / etc - so people can estimate efforts for updating.

**Comment by nshmyrev** [comment]
> @nshmyrev is there also a proper CHANGELOG to see, what has been updated / fixed / etc - so people can estimate efforts for updating.

No sorry
