### ISSUE TITLE
How to access org.vosk.android.SpeechService in csharp?

### ISSUE THREAD

**Issue by bleh05** [alphacep/vosk-api#949]
I am trying to use vosk's microphone service in a c# application but I don't know how to import it. I've tried binding the jar but I still couldn't find the speechservice in the functions.

**Comment by nshmyrev** [comment]
You have to write it yourself in C#

**Comment by sergiogut1805** [comment]
Search in the past forum questions, this already solved. 

C#: Vosk + Naudio.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/986
