### ISSUE TITLE
Publish JVM artifacts

### ISSUE THREAD

**Issue by breandan** [alphacep/vosk-api#95]
It would be nice to publish the JVM artifacts somewhere, either by setting up a JVM build on TravisCI or via an artifact repository like [JitPack](https://jitpack.io/). It should be possible to bundle the Kaldi builds for various platforms inside, using something like JavaCPP (cf. [javacpp-presets](https://github.com/bytedeco/javacpp-presets/#downloads)).

**Comment by nalbion** [comment]
I've tried to automate the build process here:
https://github.com/nalbion/vosk-api/blob/master/.github/workflows/ci.yml

...but I'm having a few issues:
https://github.com/nalbion/vosk-api/actions

**Comment by nalbion** [comment]
My CI pipeline is getting closer. Soon it should be possible for Maven to download `kaldi-windows.zip` (or `kaldi-linux.zip`) from Github's maven repo 

The Makefile in vosk-api/java is set up for Linux.

**Comment by nshmyrev** [comment]
@nalbion looks nice overall. We build on Windows with mingw though, it will make your build process much easier.

**Comment by nshmyrev** [comment]
Now published. Demo project is here:

https://github.com/alphacep/vosk-api/tree/master/java/demo

**Comment by nalbion** [comment]
Thanks @nshmyrev

**Comment by nalbion** [comment]
@nshmyrev on Windows it's looking for `win32-x86-64/vosk.dll` but your library provides `win32-x86-64/libvosk.dll`.

@breandan is there something that has to be configured to get IntelliJ to load native libs from a dependency jar?

My work so far: https://github.com/OpenASR/idear/compare/feature/vosk-api

```java.lang.UnsatisfiedLinkError: Unable to load library 'vosk':
The specified module could not be found.

Native library (win32-x86-64/vosk.dll) not found in resource path (
C:\Program Files\Java\jdk1.8.0_231\lib\tools.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\idea_rt.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\idea.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\bootstrap.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\extensions.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\util.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\openapi.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\trove4j.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\jdom.jar;
C:\Users\nalbi\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2020.2\4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6\ideaIC-2020.2\lib\log4j.jar)
```

**Comment by breandan** [comment]
@nalbion Looks great! There are few threads [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000123070--Jar-with-native-libraries-is-not-added-to-the-runtime-classpath-thru-module-dependencies) and [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206796465-how-to-load-a-native-dll-#5125202), although [that plugin](https://github.com/JetBrains/clearcase) is outdated and does not use Gradle. If the native library is [too large](https://github.com/OpenASR/idear/issues/59) to ship inside the plugin, we can also download the native library dynamically and load it ourselves similar to what this library [does](https://github.com/tudo-aqua/z3-turnkey/blob/master/src/main/java/com/microsoft/z3/Z3Loader.java). Let's move the IntelliJ Platform discussion to OpenASR/idear#52 if possible.

edit: Although if the JAR is packaged correctly, it should just work. Can you get the vanilla demo to work from your development environment?

**Comment by breandan** [comment]
@nshmyrev Although it appears to have loaded the native library, when I ran the demo on my machine, it failed with the following error:

```
LOG (VoskAPI:ReadDataFiles():model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model/mfcc.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
```

[This is the full output](https://scans.gradle.com/s/axbsf6jyueme2) I received.

**Comment by nalbion** [comment]
@breandan I'm guessing that you updated the path `C:\\sw-dev\\vosk-model-en-us-aspire-0.2` and downloaded a model from https://alphacephei.com/vosk/models

The file it's trying to load is at `C:\sw-dev\vosk-model-en-us-aspire-0.2\conf`

**Comment by breandan** [comment]
My bad! After following the [Python installation instructions](https://alphacephei.com/vosk/install#python) and updating the [model path](https://github.com/alphacep/vosk-api/blob/db41f16051bd1f5ed7d44b9a69280321c875da7c/java/demo/src/main/java/org/vosk/demo/DecoderDemo.java#L21), then running demo worked for me, producing [this output](https://scans.gradle.com/s/rdmmwn4a7lbqe/console-log?anchor=292). Thanks!

**Comment by nalbion** [comment]
@nshmyrev I get the same problem when I run your demo:

> C:\Users\nalbi\src\com\github\alphacep\vosk-api\java\demo>gradle run

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'vosk':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/vosk.dll) not found in resource path ([
file:/C:/Users/nalbi/src/com/github/alphacep/vosk-api/java/demo/build/classes/java/main/, 
file:/C:/Users/nalbi/src/com/github/alphacep/vosk-api/java/demo/build/resources/main, 
file:/C:/Users/nalbi/.gradle/caches/modules-2/files-2.1/com.alphacephei/vosk/0.3.21/6ae769e4ce0bb6143c35e5e45a07f97f44c88b1f/vosk-0.3.21.jar, 
file:/C:/Users/nalbi/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.7.0/a04e3db7cf0011d1b6a4bcfaee30ab20f077014b/jna-5.7.0.jar
])
```
