### ISSUE TITLE
Can we append/extend the model we built with kaldi vosk?

### ISSUE THREAD

**Issue by mukeshbadgujar** [alphacep/vosk-api#952]
Suppose i am building model with 300k speech data.

And after model created, if i want to add some 10 to 20 files of data in that model. 

How i can do that?

**Comment by nshmyrev** [comment]
There is no much sense to add 20 files to model trained on 300 hours of data, it will not change anything

**Comment by mukeshbadgujar** [comment]
Sorry, but i just given a example of 20 to 30 files,

I mean by this can we append 200 to 400 hrs of data in already built model? And how?

Please give any reference...

**Comment by nshmyrev** [comment]
You have to train again
