### ISSUE TITLE
Making longer output strings

### ISSUE THREAD

**Issue by portsample** [alphacep/vosk-api#954]
Hello-

Recognized speech in Vosk is outputted as strings that are produced by the following, 

    public void onResult(String s) {
        szVoskOutput = null;  //01/28 this was = " ", or blank
        try {
            JSONObject o = new JSONObject(s);
            if (o.has("text")) {
                szVoskOutput = o.getString("text");
            }
        } catch (JSONException ignored) {
            Log.e("JSONException", "...ignored szVoskOutput string.");
        }
        parseWords();
    }

These strings are defined in length by when the speaker pauses for a second or two. I would like to extend this pause after which the string ends to approximately 10 seconds. This will make the strings longer. I've checked documentation and cannot find anything specific for this adjustment. Thanks in advance.

**Comment by nshmyrev** [comment]
We do not have such option. You'd better just join the chunks if you need longer ones.

**Comment by portsample** [comment]
Thanks.
