### ISSUE TITLE
Exception thrown at 0x0000000067DE5F30 (libvosk.dll) in VoskDemo.exe: 0xC0000005: Access violation writing location 0x00000000000008D4 

### ISSUE THREAD

**Issue by KienNguyen1105** [alphacep/vosk-api#955]
Exception thrown at 0x0000000067DE5F30 (libvosk.dll) in VoskDemo.exe: 0xC0000005: Access violation writing location 0x00000000000008D4 

![image](https://user-images.githubusercontent.com/104954432/167059540-6e255ca8-e40c-45f2-8708-dc5bfca157bc.png)
I have no clue what's happening there. I'm guessing I'm accessing the model incorrectly.
Anyway, the line I'm having trouble with right now is VoskRecognizer rec = new VoskRecognizer(model, 16000.0f);
That's the line throwing the error. Can you help me?

**Comment by nshmyrev** [comment]
Model is not properly initialized because you didn't download model folder probably. You can check console output for details.

**Comment by KienNguyen1105** [comment]
> Model is not properly initialized because you didn't download model folder probably. You can check console output for details.

![image](https://user-images.githubusercontent.com/104954432/167358362-dcfd1ce4-0db9-4595-bd37-ce219f1ac37f.png)
I downloaded the correct model folder. But I don't know where the model folder is exactly, can you help me?
