### ISSUE TITLE
How can I reduce the likelihood of homophones/How to modify the LM’s ngram to increase the probability of certain words?

### ISSUE THREAD

**Issue by bbergeron0** [alphacep/vosk-api#956]
Hi, so far the vanilla Vosk model works great but it often interpret certain utterances as the wrong homonym (like “back,” which is more often interpreted as “that,” “but,” or even “doc”). I don’t know much about ASR and speech recognition, but a few research taught me the best course of action would be to tune Kaldi’s language model.

Following the [“model adaptation” guide](https://alphacephei.com/vosk/adaptation), I’ve compiled a text.txt file containing all 15 words used by our application and fed it to Kaldi’s toolchain. Unfortunately, the resulting model was interpreting ANY utterence as a homonym of these 15 words, so our app was consistently triggered by false positives.

How can I increase the likelihood of obtaining the right homonyms, but not too much?

**Comment by nshmyrev** [comment]
You can interpolate domain-specific LM with generic LM as in https://alphacephei.com/vosk/lm. Update package for small English model is here:  https://alphacephei.com/vosk/models/vosk-model-en-us-0.15-compile.tar.gz

**Comment by bbergeron0** [comment]
Thanks, I found this ["Vosk - Language model interpolation with generic model"](https://alphacephei.com/vosk/lm#language-model-interpolation-with-generic-model). The whole page has a lot of scattered information, I will piece them together next week and I'll close this issue once I have a shell script snippet to share with the next guy. Have a nice weekend.

**Comment by jimdinunzio** [comment]
Hi, I am also interested in updating the small English model. However, the link above does not work. 
The correct one is https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15-compile.tar.gz
For the large model it is here: https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-compile.zip.

**Comment by bbergeron0** [comment]
Thanks, Jim.
```
ngram -lm your.lm -ppl test.txt -debug 2 > your.ppl
ngram -lm generic.lm -ppl test.txt -debug 2 > generic.ppl
compute-best-mix your.ppl generic.ppl
```
This makes sense. However I don't have a `text.txt` so I think I'll pick random factors for the interpolation until I have something good.

Here's what I'm trying to do: 
```
ngram -lm your.lm -mix-lm generic.lm -lambda <factor from above> -write-lm mixed.lm 
```
There’s `db/en-150k-0.4-android.lm.gz` inside the aforementioned archive which I can use for `generic.lm`. But I also need to make and provide my own `your.lm`. I’ll search through Kaldi’s ’egs/’ directory for hints on how to do create my own lm. So far Kaldi’s doc isn't helping, so I’ll be thankful if anyone can provide any kind of help.

**Comment by bbergeron0** [comment]
In Vosk’s small English model, there’s Gr.fst which, if I understand correctly, contains the lm’s ngram. I don’t have any text data, I don’t have any audio data, so modifying an existing n-gram would be way easier than training or interpolation from scratch. I just want to push one word higher than its homophones. How’s that approach? Can Kaldi’s toolchain do that?

**Comment by nshmyrev** [comment]
> I don’t have any text data

put your word in extra.txt and run the compilation script, it will recompile Gr.fst

**Comment by jimdinunzio** [comment]
If I have partial phrases with a variable but known vocabulary word in it that I want to elevate by putting them in extra.txt such as "My name is ..." or "update location of ..." or "turn ... degrees clockwise"  where ... represents the variable portion do i just leave the word out or is [unk] appropriate here?
Thanks!

**Comment by jimdinunzio** [comment]
Hi,
To help users compile the graph you may consider adding some hints for installation. New text in boldface.

The following software must be pre-installed on a server:

Kaldi  - **(See http://kaldi-asr.org/doc/install.html#install_install)**
SRILM - **(use install_srilm.sh in Kaldi tools directory)**
Phonetisaurus (with pip3 install phonetisaurus)

and for inside the model "compile" directory preparation:
**Make a soft link to utils and steps directory**
**ln -sT (path to kaldi)/egs/wsj/s5/steps steps**
**ln -sT (path to kaldi)/egs/wsj/s5/utils utils**

**Comment by bbergeron0** [comment]
I’ve pieced the documentation together and managed to get “back” to be emitted more often than “that” or other synonims, but a few words disappeared in the process, like “search,” “sierra,” and “down.” At first I thought the small English *-compile model was simply not as complete as the compiled model of the same name, but after reverting to the default small model, these words didn’t come back. I hate caching.

Be right back whenever I get my dictionary back.

**Comment by bbergeron0** [comment]
Alright I did it.

Here’s the solution I came up with:
1. Compile Kaldi and the required tools (I can’t tell which ones, it’s a trial and error process). Read `INSTALL` at the root of your Kaldi directory for more details. Make sure the variable `$KALDI_ROOT` points to your local Kaldi directory throughout the next steps.
2. Download and extract your “compile” model. For me it’s “vosk-model-small-en-us-0.15-compile.” I can’t guarantee the solution will work with other models. Let’s refer to the extracted “compile” model as `MODEL_COMPILE` from now on.
3. Write whatever in `$MODEL_COMPILE/db/extra.txt`. In my case, I added a new word, and wrote all command and keywords our applications will handle. At the end of the process, the new word was successfully recognized, and I had fewer issues regarding homophones.
4. Source Kaldi `env.sh`: `. $KALDI_ROOT/tools/env.sh`
5. run `$MODEL_COMPILE/compile-graph.sh`

The model should now be compiled, you may now build a model archive, where `$MODEL` is your output folder:
```
mkdir                                                  $(MODEL)/am
cp $(MODEL_COMPILE)/exp/tdnn/final.mdl                 $(MODEL)/am/final.mdl
mkdir                                                  $(MODEL)/conf
cp mfcc.conf                                           $(MODEL)/conf/mfcc.conf
cp model.conf                                          $(MODEL)/conf/model.conf
mkdir                                                  $(MODEL)/graph
cp $(MODEL_COMPILE)/exp/tdnn/lgraph/disambig_tid.int   $(MODEL)/graph/disambig_tid.int
cp $(MODEL_COMPILE)/exp/tdnn/lgraph/Gr.fst             $(MODEL)/graph/Gr.fst
cp $(MODEL_COMPILE)/exp/tdnn/lgraph/HCLr.fst           $(MODEL)/graph/HCLr.fst
mkdir                                                  $(MODEL)/graph/phones
cp $(MODEL_COMPILE)/data/lang/phones/word_boundary.int $(MODEL)/graph/phones/word_boundary.int
mkdir                                                  $(MODEL)/ivector
cp $(MODEL_COMPILE)/exp/extractor/final.dubm           $(MODEL)/ivector/final.dubm
cp $(MODEL_COMPILE)/exp/extractor/final.ie             $(MODEL)/ivector/final.ie
cp $(MODEL_COMPILE)/exp/extractor/final.mat            $(MODEL)/ivector/final.mat
cp $(MODEL_COMPILE)/exp/extractor/global_cmvn.stats    $(MODEL)/ivector/global_cmvn.stats
cp $(MODEL_COMPILE)/exp/extractor/online_cmvn.conf     $(MODEL)/ivector/online_cmvn.conf
sed 's/ /\n/g' \
   $(MODEL_COMPILE)/exp/extractor/splice_opts        > $(MODEL)/ivector/splice.conf
```
Zip it, and ta-da!

**Comment by nshmyrev** [comment]
Congrats!
