### ISSUE TITLE
Trying to run vosk with C

### ISSUE THREAD

**Issue by vikraman22** [alphacep/vosk-api#960]
I'm trying to run vosk through C. When I try to run the make file I get the following error

adminuser@MacBook-Air c % sudo make
g++ test_vosk.o -o test_vosk -L../src -lvosk -ldl -lpthread -Wl,-rpath=../src
ld: library not found for -lvosk
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I included the libvosk.dyld in ../src directory but still the issue was not resolved.

**Comment by nshmyrev** [comment]
Maybe you need to rename it to dylib. Are you on mac M1 by any chance?

**Comment by vikraman22** [comment]
I'm using macbook air(2017) @nshmyrev

**Comment by nshmyrev** [comment]
Ok, then you can probably rename dyld to dylib and it should work

**Comment by vikraman22** [comment]
But still the issue persists! Even after renaming libvosk.dyld to libvosk.dylib

**Comment by nshmyrev** [comment]
add `-vvv` to command line and share the output.

**Comment by vikraman22** [comment]
The output is as follows

adminuser@Macbook-Air c % sudo make -vvv
Password:
GNU Make 3.81
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0

Does this provide any information?

**Comment by nshmyrev** [comment]
add -vvv to gcc command line, not to make.

**Comment by vikraman22** [comment]
adminuser@Macbook-Air c % gcc -vvv test_vosk.c
clang: error: unknown argument: '-vvv'

**Comment by nshmyrev** [comment]
g++ --verbose test_vosk.c -o test_vosk -L../src -lvosk -ldl -lpthread -Wl,-rpath=../src

**Comment by vikraman22** [comment]
running the command cause 

test_vosk.c:1:10: fatal error: 'vosk_api.h' file not found
#include <vosk_api.h>

I checked the src/ directory the vosk_api.h file was present in it.

**Comment by nshmyrev** [comment]
Run this:
      
`g++ --verbose test_vosk.c -o test_vosk -I../src -L../src -lvosk -ldl -lpthread -Wl,-rpath=../src
`

**Comment by vikraman22** [comment]
This causes 

ld: unknown option: -rpath=../src
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mddelk** [comment]
Looks like the `=` in `rpath` is causing this for `clang`. 

Apparently using the `=` there [is a GNU extension](https://stackoverflow.com/a/32400674/7132678) - you should be able to use `,` instead.

Try this

```
g++ --verbose test_vosk.c -o test_vosk -I../src -L../src -lvosk -ldl -lpthread -Wl,-rpath,../src 
```

**Comment by nshmyrev** [comment]
This seems solved. Let us know if you need extra help.
