### ISSUE TITLE
ERROR (VoskAPI:Model():model.cc:122) Folder 'model' does not contain model files.

### ISSUE THREAD

**Issue by rupertbj** [alphacep/vosk-api#968]
I'm getting the error above, but I have downloaded the model zip file and unpacked it, and the model files are there.
I've even set it's path in my .zhsrc to try to resolve the issue, but I can't get it to work?
My script has the following for model:
`def takeCommand():
    model = Model("model")
    rec = KaldiRecognizer(model, 16000)`
Any help would be very gratefully received!
Many thanks,
Rupert

**Comment by nshmyrev** [comment]
If you are not sure why relative path doesn't work, specify an absolute path to the model.

**Comment by rupertbj** [comment]
I have... at least I think I have!
I added the following to my .zshrc file:
`export PATH="$PATH:/home/rupstar/Computer/vosk-api/python/example/model"`

**Comment by nshmyrev** [comment]
PATH is for executables, not for models. You have to specify absolute path in model constructor argument.

**Comment by rupertbj** [comment]
Forgive my ineptitude, but what or where is the "model constructor argument"?
I'm trying to use a model I've downloaded.
Should I be doing amending my script as follows?:
`def takeCommand(): /home/rupstar/Computer/vosk-api/python/example/model = Model("model") rec = KaldiRecognizer(model, 16000)`

**Comment by nshmyrev** [comment]
```
def takeCommand(): model = Model("/home/rupstar/Computer/vosk-api/python/example/model") 
rec = KaldiRecognizer(model, 16000)
```

**Comment by rupertbj** [comment]
Wonderful... that's working perfectly again now. Thank you!
Now to research what a relative path is!!
