### ISSUE TITLE
Install Vosk on Jetson Xavier

### ISSUE THREAD

**Issue by AndriyIvanov** [alphacep/vosk-api#97]
I want to install Vosk on Jetson Xavier. Python3 version is 3.6.9, pip3 version is 20.1. Operating system is Ubuntu 18.04 (Jetpack 4.3). But after "pip3 install vosk" I receive: "ERROR: Could not find a version that satisfies the requirement vosk (from versions: none). ERROR: No matching distribution found for vosk". Do you have any suggestions about?

**Comment by nshmyrev** [comment]
Try

pip3 install https://github.com/alphacep/vosk-api/releases/download/0.3.7/vosk-0.3.7-cp36-cp36m-linux_aarch64.whl

**Comment by AndriyIvanov** [comment]
Many thanks! It works for this wheel. Everything was installed!
