### ISSUE TITLE
New model for Brazilian Portuguese :brazil: 

### ISSUE THREAD

**Issue by cassiotbatista** [alphacep/vosk-api#971]
Hello,

By following the recommendation "[To add a new model here create an issue on Github](https://alphacephei.com/vosk/models)", here I am.

 I've trained a model for general Portuguese, but hopefully biased towards Brazilian Portuguese using FalaBrasil Group's resources. Details are as follows:

- 16 kHz wideband, chain model with GPL v3.0 license
- trained over 8 public datasets + 3 private: https://github.com/falabrasil/speech-datasets
- `fb-falabrasil` recipe for Kaldi: https://github.com/falabrasil/kaldi-br
- Model files versioned on GitLab LFS: https://gitlab.com/fb-resources/kaldi-br 
- Lexicon, LMs and other stuff also versioned on GitLab LFS: https://gitlab.com/fb-resources

WER values comprise a single test with 4-gram CARPA online decoding with beam=10 for FalaBrasil, and 1st pass only for Vosk's model. Some values seem unusually large (odd column), so I still need some time to address them with care later.

| dataset       | fb v0.1.1 | vosk pt v0.3 | odd  |
|:-------------:|:---------:|:------------:|:----:|
| coddef        |  2.48     |    9.17      |      |
| cetuc         |  6.39     |   17.59      |      |
| constituicao  |  3.18     |   10.74      |      |
| coraa         | 52.97     |   65.99      | \*\* |
| cv            | 24.03     |   38.81      |      |
| lapsbm        |  9.84     |   21.25      |      |
| lapsstory     | 14.06     |   18.60      |      |
| mls           | 27.52     |   40.65      | \*   |
| mtedx         | 31.04     |   37.65      |     |
| spoltech      | 15.83     |   31.21      |      |
| vf            | 19.32     |   35.34      |      |
| westpoint     |  6.37     |   16.50      |      |

Mostly tested directly on Kaldi, minor tests on Vosk mostly to check compatibility. More tests with the latter would be appreciated :smile: Beware both `HCLG` and `HCL + G` are being versioned together for now because I'm not sure which provides a better performance.

**Comment by nshmyrev** [comment]
Model is published, thank you!
