### ISSUE TITLE
Training by using my own data

### ISSUE THREAD

**Issue by miziworld** [alphacep/vosk-api#972]
Hello, Thank you for your project.
This is my first time using vosk.
Looking at it, vosk seems to be running based on kaldi. Looking inside the model file, it seems to be the same file created when training with kaldi. If I train in kaldi with my dataset and replace the model currently required by vosk with mine, will it work smoothly? Or is there something else I need to add in vosk?

**Comment by nshmyrev** [comment]
> If I train in kaldi with my dataset and replace the model currently required by vosk with mine, will it work smoothly?

Yes it will work. We also recommend to look on our training recipe: https://github.com/alphacep/vosk-api/tree/master/training

**Comment by nshmyrev** [comment]
Same as #41
