### ISSUE TITLE
Access GPU decoder with pip install

### ISSUE THREAD

**Issue by DerBrunoIR** [alphacep/vosk-api#974]
The import issue occures when i copy [test_gpu_batch.py](https://github.com/alphacep/vosk-api/blob/06a761ecbd40804c7fa50efb8bd570ac6899c899/python/example/test_gpu_batch.py#L11) into pycharm. Then BatchModel and BatchRecognizer can not be referenced by pycharm.
I tried to replace them with Model and KadiRecognizer (like in test_ffmpeg.py) but it seems they miss the following methodes  FinishStream(), Wait(). 
My setup: Im using python 3.9 and vosk is installed via pip. And a model is in my content root.

And a bad ; is [here](https://github.com/alphacep/vosk-api/blob/06a761ecbd40804c7fa50efb8bd570ac6899c899/python/example/test_gpu_batch.py#L33).

By the way thats my first issue. If there is anything to notice, i'd be glad to get some advices :)

**Comment by nshmyrev** [comment]
Sorry, GPU build is not available with PIP yet, you have to build yourself.

We fixed syntax error just now in def8c93711b638700013adcf55ad1be07d89b1bd

**Comment by nshmyrev** [comment]
Same as #835
