### ISSUE TITLE
Running as another user

### ISSUE THREAD

**Issue by boulder47** [alphacep/vosk-api#976]
Hi, 
I love this project, it’s been working like a charm with the help of the example scripts.
I’m using Ubuntu, installed the vosk-api in the user home dir, it runs fine from there,

I’m writing a website front end that uses Apache2 and a php website that runs a python script for vosk.
In the process, I’ve discovered it’s not working with other user accounts on the system, namely the user ‘www-data’ that Apache uses, 

It’s working fine under the normal user account, but when I call it from the website front end, user ‘www-data’ it’s giving an error of Libvosk.so not found, sudo commands aren’t working either for it.

Any help would be appreciated 

Thanks.

**Comment by nshmyrev** [comment]
You'd better check php client for vosk-server:

https://github.com/alphacep/vosk-server/tree/master/client-samples/php

**Comment by boulder47** [comment]
I figured it out.
checked on my sudoers and added correct permissions.
then when calling the script, from which directory its running from, need to be the 'model" dir for the script to find and use,
with a bit of debugging its now working.
I now have a file manager frontend web interface for vosk.

**Comment by nshmyrev** [comment]
Great, thanks for sharing!
