### ISSUE TITLE
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

### ISSUE THREAD

**Issue by puvvadasaikiran** [alphacep/vosk-api#977]
Hello,
I was trying to use VOSK decoding audio(ASR) with event_loop to decrease the time needed to decod set of audio_files
but encountered the error below

`BLAS : Program is Terminated. Because you tried to allocate too many memory regions.`

using asr-server provided in websocket implementation
data flow : 
-------given a audio files, audio is segmented via VAD into smaller files, 
-------decoding starts parallelly using python's asyncio

Edit:
works fine if base audio file is less than 5 mins but when its 10 mins the following error is thrown

**Comment by nshmyrev** [comment]
You simply do not have enough memory to run this. Increase system memory or use smaller model.

**Comment by puvvadasaikiran** [comment]
> You simply do not have enough memory to run this. Increase system memory or use smaller model.

memory is not an issue ig, 200Gb RAM is available

**Comment by nshmyrev** [comment]
Ok, which vosk version do you have? Also, what is your hardware, how many CPUs.

**Comment by puvvadasaikiran** [comment]
> Ok, which vosk version do you have? Also, what is your hardware, how many CPUs.

Ver (0.3.37) of vosk and 64 core CPU

**Comment by puvvadasaikiran** [comment]
problem resolved for now by keeping number of parallel tasks lower than Number of CPU cores

**Comment by nshmyrev** [comment]
We do not recommend 0.3.37 btw, i had critical issue, update to 0.3.38 and please try if problem persists. Also please verify 0.3.32.

**Comment by puvvadasaikiran** [comment]
Sure, will do that 
Thank you
