### ISSUE TITLE
32 bit Linux build

### ISSUE THREAD

**Issue by ghost** [alphacep/vosk-api#978]
Hello.
It would be great if you could post (at least once) a build for old 32 bit linux (ubuntu 16.04 level). 32 bit Vosk is only in Mageia 8 (community repository) and seems to be nowhere else.
I'm trying to compile openfst-kaldi myself, but I'm having some trouble with it. Some errors and high memory consumption by the gcc compiler when building algo-test (although, I disabled all tests in cmake). Clang 8 uses less memory compared to gcc, but it gives an error after an hour of building.
So if you could post a ready vosk.so static, I would be very grateful.

My main system is ubuntu 16.04-2016 i386 (python 3.8 from ppa) and I can of course connect to Mageia 8 via chroot and use vosk from the command line (test_ffmpeg.py), but it's not very practical.

There is one peculiarity. For i686 builds you have to specify:
```
export CFLAGS="-mfpmath=sse -msse2"
export CXXFLAGS="-mfpmath=sse -msse2"
```
Because Vosk uses SSE2 instructions and they are disabled by default in the 32 bit compiler.

I really hope you can help, if it's not too much trouble for you.

UPD: There is no suitable build at pypi.org either.  I forgot to say that I have installed gcc 10 compiler with c++17 support, which I use. As well as a new cmake.

**Comment by nshmyrev** [comment]
It is actually easy to use dockcross to cross-build, we added support for it in ff2c80d5f1dd2f0a21a5a63a98739a4103309f18 just now

The binaries are also available in releases: 

https://github.com/alphacep/vosk-api/releases/download/v0.3.38/vosk-0.3.38-py3-none-linux_x86.whl

https://github.com/alphacep/vosk-api/releases/download/v0.3.38/vosk-linux-x86-0.3.38.zip

**Comment by ghost** [comment]
Thank you. In version 0.3.38, released on May 24, 2022, there is indeed an x86 linux version, which was not there before. In the past, the ELF64 was hiding under x86, which confused me at first.

However, it looks like 0.3.38 won't work for me:
```
ldd libvosk.so
/lib/i386-linux-gnu/libm.so.6: version 'GLIBC_2.27' not found (required by libvosk.so)
/lib/i386-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by libvosk.so)
```
ubuntu 16.04 uses glibc (libc6) 2.23
glibs incompatibility is very bad and is unlikely to be resolved by swapping libraries.
2.27 corresponds to ubuntu 18.04 (2018)
I understand this is very bad, old 32 bit linux... just the win10 times.

**Comment by ghost** [comment]
Well, since I built (before) glibc 2.32 and gcc 10 myself under xenial i386 environment, I just loaded `ld-linux.so.2, libcc1.so.0, libgcc_s.so.1, libm.so.6, libstdc++.so.6 (6.0.28)` via LD_LIBRARY_PATH and it worked (wow). I will share them with you (gcc10 took 12 hours to compile, for example).
[gcc10-glibc2.32-xenial-i386.zip](https://github.com/alphacep/vosk-api/files/8765683/gcc10-glibc2.32-xenial-i386.zip)
vosk-0.3.38-py3-none-linux_x86.whl I had to unpack and install manually (by copying).

```
cd /home/denis/vosk-api/python/example
LD_LIBRARY_PATH=/home/denis/gcc10-glibc ./test_ffmpeg.py /home/denis/audio.ac3 | grep "text"
LD_LIBRARY_PATH=/home/denis/gcc10-glibc ./test_srt.py /home/denis/audio.wav > /home/denis/audio.srt
```
Thank you for adding support for linux x86 in 0.3.38.

UPD: Sorry, I forgot to strip ld-linux.so.2 and libm.so.6.
