### ISSUE TITLE
Add Android and iOS binaries to releases.

### ISSUE THREAD

**Issue by philipag** [alphacep/vosk-api#979]
I see the latest release 3.38 has Linux, mac OS, and windows binaries.  Since Android and iOS are also supported, would it not make sense to include the Android+iOS binary libraries and sources in the releases as well?  Is there a particular reason not to?  The main issue is that it is highly non-trivial to build those so it would be much better if the release bundle included them....

**Comment by nshmyrev** [comment]
Hi. I've just pushed vosk-android-0.3.38 to maven. As for iOS, we are actually updating it for M1, it will be available on request soon.
