### ISSUE TITLE
Still crashing

### ISSUE THREAD

**Issue by MikeyBeez** [alphacep/vosk-api#98]
As always, thank you so much for all your hard work and excellent program.  I updated vosk to 0.3.7 and I still crash with the new 1.4 GB aspire model.    vosk 0.3.7 works fine with the old model.  I wonder if I am installing the model incorrectly.  The directory is model-en.  

❯ tree model-en
model-en
├── vosk-model-en-us-aspire-0.2
│   ├── am
│   │   ├── final.mdl
│   │   ├── frame_subsampling_factor
│   │   └── tree
│   ├── conf
│   │   ├── mfcc.conf
│   │   └── model.conf
│   ├── graph
│   │   ├── HCLG.fst
│   │   ├── phones
│   │   │   └── word_boundary.int
│   │   ├── phones.txt
│   │   └── words.txt
│   ├── ivector
│   │   ├── final.dubm
│   │   ├── final.ie
│   │   ├── final.mat
│   │   ├── global_cmvn.stats
│   │   ├── ivector.conf
│   │   ├── mfcc.conf
│   │   ├── online_cmvn.conf
│   │   └── splice.conf
│   ├── README
│   └── rescore
│       ├── G.carpa
│       └── G.fst
└── vosk-model-en-us-aspire-0.2.zip

ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: model-en/mfcc.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError

Hopefully this helps you debug your excellent code.  Please let me know if you need anything more.

**Comment by nshmyrev** [comment]
vosk-model-en-us-aspire-0.2 should be renamed as model-en, not placed inside like this:

```
├─ model-en
│ am
│  ├── final.mdl
│  ├── frame_subsampling_factor
│  └── tree
│─ conf
│ ├── mfcc.conf
│ └── model.conf
│   
...

```

**Comment by MikeyBeez** [comment]
Thank you.  I'm such an idiot. ;)   I hope you're well.  Cheers!

**Comment by suyashcjoshi** [comment]
I ran into the same problem then realized the folder structure..thanks!
