### ISSUE TITLE
Some files aren't writable in Dutch (nl) models on site

### ISSUE THREAD

**Issue by AlexMisiulia** [alphacep/vosk-api#980]
In [vosk-model-nl-spraakherkenning-0.6](https://alphacephei.com/vosk/models/vosk-model-nl-spraakherkenning-0.6.zip) and [vosk-model-nl-spraakherkenning-0.6-lgraph](https://alphacephei.com/vosk/models/vosk-model-nl-spraakherkenning-0.6-lgraph.zip) files `conf/mfcc.conf` `online_cmvn.conf` have mod `-rw-------`, but in all other languages have `-rw-r--r--`. Because of that I have errors when reading them as a group.

Is it possible to fix them (`chmod 644 conf/mfcc.conf ivector/online_cmvn.conf`)  and upload to the server?

**Comment by nshmyrev** [comment]
Done, thank you for the report
