### ISSUE TITLE
Exception("Failed to create a model") for raspberry pi-4

### ISSUE THREAD

**Issue by cirenehc** [alphacep/vosk-api#995]
I'm getting the following error when initializing the model using the python lib for raspberry pi4.

Note that my code works fine on my mac.
Model: vosk-model-en-us-0.22

```
import vosk

# Python code that failed.
model = vosk.Model(ASR_MODEL_PATH)
```
Error message
```
File "/home/pi/src/normal/venv/lib/python3.9/site-packages/vosk/__init__.py", line 29, in __init__
    raise Exception("Failed to create a model")
```

Also, the example on https://alphacephei.com/vosk/install doesn't work.
```
$ git clone https://github.com/alphacep/vosk-api
$ cd vosk-api/python/example
$ python3 ./test_simple.py test.wav
Exception ignored in: <function Model.__del__ at 0xb66f4cd0>
Traceback (most recent call last):
  File "/home/pi/src/normal/venv/lib/python3.9/site-packages/vosk/__init__.py", line 32, in __del__
    _c.vosk_model_free(self._handle)
AttributeError: 'Model' object has no attribute '_handle'
Traceback (most recent call last):
  File "/home/pi/src/vosk-api/python/example/./test_simple.py", line 16, in <module>
    model = Model(lang="en-us")
TypeError: __init__() got an unexpected keyword argument 'lang'
```

**Comment by nshmyrev** [comment]
>    raise Exception("Failed to create a model")

This model is too big for RPI4, it requires like 8Gb of memory just for recognition. You need to use smaller model (at least lgraph version)

> TypeError: __init__() got an unexpected keyword argument 'lang'

Please upgrade to vosk-0.3.42

**Comment by cirenehc** [comment]
Thanks Nikolay. Both of your solutions work.
