### ISSUE TITLE
Models not found in java.

### ISSUE THREAD

**Issue by xaimepardal** [alphacep/vosk-api#996]
I am using maven and springboot to implement vosk.
I am not able to indicate the path to folder with models.

`ERROR (VoskAPI:Model():model.cc:122) Folder '/models/es' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.`

I have models saved in `src/resources/models` and I am indicating that route in the constructor.

Code:

`new Model("/models/en)`

Directory tree:
![image-title](https://i.ibb.co/Z2h4tdx/Captura-de-pantalla-de-2022-06-06-11-22-20.png)

What should I indicate in the constructor so that it loads the models of the folder "en"?
Thanks.

**Comment by nshmyrev** [comment]
You have to specify path in the filesystem, the code can not load model directly from resources. You have to unpack model yourself from resources before loading them.

**Comment by xaimepardal** [comment]
> You have to specify path in the filesystem, the code can not load model directly from resources. You have to unpack model yourself from resources before loading them.

The models are already unpacked, they are not zip. 

Should I save the models outside the src, in the system?
That is what I understood.
Thanks.

**Comment by nshmyrev** [comment]
Then specify an absolute file path instead of relative.

**Comment by nshmyrev** [comment]
> Should I save the models outside the src, in the system?

By unpacked I mean "unpacked into the file system"

**Comment by xaimepardal** [comment]
Ok, I understand. I have used absolute paths to the system instead of using the files packed in the .jar.
Thanks for your help.
